### ISSUE TITLE
Issues in the Me Box, Notifications, Messages 

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10006]
In my local site, there's an issue, the notifications, me box, messages are wrong. The alert state (numbers on the top) are appearing in white stroke and the hover is red. The correct color is red.

I'm using Keystone.
Theme Options: Default

Wrong:
<img width="244" alt="Screen Shot 2020-01-28 at 2 16 52 PM" src="https://user-images.githubusercontent.com/45467951/73297552-c78f7e00-41d9-11ea-8a09-f47938fcacfe.png">

Correct:
<img width="434" alt="Screen Shot 2020-01-28 at 2 24 11 PM" src="https://user-images.githubusercontent.com/45467951/73297618-dfff9880-41d9-11ea-9ba6-3d35e4a945b2.png">

All States:
<img width="172" alt="Screen Shot 2020-01-28 at 2 27 27 PM" src="https://user-images.githubusercontent.com/45467951/73297940-78961880-41da-11ea-9bbd-9f6d8e79d258.png">

If you have any questions, let me know.

Thanks.

**Comment by charrondev** [comment]
Closing as we aren't making further modifications to keystone. It is not meant to comply with these designs. We have foundation now.
