### ISSUE TITLE
Buttons take full width breaking the layout

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#10011]
Buttons started having full width since the latest release (2020.002).

![Screen Shot 2020-01-29 at 10 41 06 AM](https://user-images.githubusercontent.com/31521020/73371995-8902cd80-4284-11ea-84c8-5109eade72eb.png)

I did some digging and found out it's the style coming from `{{LOCAL_URL}}/dist/forum/addons/dashboard.min.css?h=4.0-2020.002-SNAPSHOT`.

Style applied is:

```
input, select, textarea {
    width: 100%;
}
```

It doesn't fit for `input[type="submit"]` which should be visually represented by buttons.

**Comment by igraziatto** [comment]
Also not working great for radios and checkboxes (page below is the `post/discussion` page)

![Screen Shot 2020-01-29 at 10 58 45 AM](https://user-images.githubusercontent.com/31521020/73373254-64a7f080-4286-11ea-9611-8a58063ebb87.png)

**Comment by charrondev** [comment]
Fixed https://github.com/vanilla/vanilla/pull/9997
and Backported https://github.com/vanilla/vanilla/pull/9998

almost immediately after the release.
