### ISSUE TITLE
The Search's color in the Title Bar is wrong

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10016]
The Search's color is wrong on the Title Bar. See below the image:
<img width="1363" alt="SEARCH" src="https://user-images.githubusercontent.com/45467951/73492716-3d811a00-437f-11ea-9026-b4767bbd465e.png">

Correct one:
<img width="719" alt="Screen Shot 2020-01-30 at 4 42 03 PM" src="https://user-images.githubusercontent.com/45467951/73492857-876a0000-437f-11ea-8f50-d9ce2a46ef8f.png">

If you have any questions, let me know.

**Comment by slafleche** [comment]
Will be fixed with: https://github.com/vanilla/vanilla/pull/10032
