### ISSUE TITLE
Upload external files to the theme editor pages

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#10020]
As a themer I want to be able to upload files such as images for use in my HTML/CSS.

## Acceptance Criteria

- Dragging/dropping a file onto the Monaco editor will upload it and either:
    - Insert its URL at the current cursor position.
    - Copy its URL to the clipboard with some sort of toaster message saying so.
- The files should be uploaded to the CDN and be kept track of in our media table so that we can maybe add a management page later.

**Comment by vrjrobitaille** [comment]
@charrondev I believe you implemented something last week that could be used for a PBI like this one. Can you add a quick note about it here?
