### ISSUE TITLE
Refactor search bar to remove search button

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#10027]
Refactor search to match the mobile look and feel. The search button will only be shown when you tab onto it.

We want to remove the search button for the following reasons:

- The button is very opinionated from a theming point of view.
- In the future, we want to add a dropdown to the search box. Having a dropdown and a button won't look good.

Because this is a fairly significant visual change to make we should make sure that design has their say.

Mockup: https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec5896838853828f4b797bc

**Comment by vrjrobitaille** [comment]
Notes from discussion with Adam today - this  issue  is part of Context Based search, rather than unifying search. We'll need to evaluate how this affects our theme variations, but we'll tackle this issue when  Context  Based search comes  up.
