### ISSUE TITLE
Spelling is wrong - Dashboard

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10063]
On the Dashboard > Discussion > Subcommunities, in the modal, the spelling of a word is wrong (product column). It is saying "Assosciate" but the correct is "Associate". Could you change it?

See the screenshot:
<img width="1024" alt="Screen Shot 2020-02-10 at 10 49 43 AM" src="https://user-images.githubusercontent.com/45467951/74166040-f0f5d400-4bf3-11ea-8a14-9c33bd252469.png">

**Comment by tburry** [comment]
The work on this is done, but it's blocked on the translation order so I'll get it out if the WIP column.
