### ISSUE TITLE
Device Tags - Mockups

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10088]
The Knowledge Base will have a new feature - Device Tags.

Create mockups showing tags.
- Update the Filter Results (search). We'll show another input for tags
- Where is the best place to put tags in the Article Page?

Examples:
- Zendesk does the "device tags". They call labels.

**Comment by tburry** [comment]
Issue moved to [vanilla/knowledge #1550](https://github.com/vanilla/knowledge/issues/1550) via [**ZenHub**](https://www.zenhub.com/)
