### ISSUE TITLE
Foundation theme (Staff forum) tags missing styling

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10111]
Screenshot of bug:
![Screen Shot 2020-02-19 at 2 39 51 PM](https://user-images.githubusercontent.com/24961134/74871401-631f9480-5329-11ea-8ca3-d2f397a0cb31.png)

I would expect them to look closer to this:
![Screen Shot 2020-02-19 at 3 06 40 PM](https://user-images.githubusercontent.com/24961134/74871428-73d00a80-5329-11ea-99d2-41aa55c05fe6.png)

**Comment by vrjrobitaille** [comment]
Thanks Brendan! We've also picked this up during QA, handling that over here - https://github.com/vanilla/vanilla/issues/10220
