### ISSUE TITLE
Foundation Theme - New Discussion button in hamburger menu

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10120]
In the current foundation theme, the only posting button is below the content section. 

![Screen Shot 2020-02-21 at 9 39 51 AM](https://user-images.githubusercontent.com/24961134/75043851-ae9f8300-548e-11ea-9528-bae78bd45ebf.png)

In Keystone, it was accessible from the hamburger menu at the top, which personally, I found to be a decent spot since they don't have to scroll all the way down. 

![Screen Shot 2020-02-21 at 9 40 15 AM](https://user-images.githubusercontent.com/24961134/75043773-90398780-548e-11ea-8859-95b39a90f8c9.png)

With Foundation, it's not in the hamburger 

![Screen Shot 2020-02-21 at 9 37 49 AM](https://user-images.githubusercontent.com/24961134/75043872-b3fccd80-548e-11ea-83fd-d5bc65a7af44.png)

This is a design choice so it's a bit of an opinion thing but I noticed the difference and thought maybe it's an oversight given that Keystone had it.

**Comment by charrondev** [comment]
We have a decent design implemented for mobile at least. https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5cdc322579517d1e138da9c9

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/9696
