### ISSUE TITLE
Staff forum spacing issues

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10135]
The spacing between the side panel navigation (on the right) and the discussion are too close. See the screenshot below:
<img width="1141" alt="Screen Shot 2020-02-26 at 3 34 00 PM" src="https://user-images.githubusercontent.com/45467951/75394529-51f0fd80-58be-11ea-82ff-103398b71e33.png">

The spacing should be 60px.

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #2263](https://github.com/vanilla/internal/issues/2263) via [**ZenHub**](https://www.zenhub.com/)
