### ISSUE TITLE
Internal permission expansion from having a record specific permission is confusing in UI

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#10144]
## Scenario

- Admin creates custom role `View1KB`
- Admin removes general `kb.view` permission from the user.
- Admin Creates a user `User1` with `View1KB`
- `User1` hits any endpoint that checks for kb.view permission.
- User passes general check for `kb.view`. 

## Source Code

We check if there is any value at all for the permission, not if it exists generically.

https://github.com/vanilla/vanilla/blob/978119bdc451284b2cd4785e66319d3292152f7b/library/Vanilla/Permissions.php#L404

## UI confusion

At this point I doubt we could change this behaviour, but it is something that should be better reflected in the UI. If the user has custom with a foreign ID, that permission should be disabled and forced to be checked in the user interface so that the UI matches up the internal permission representation.

**Comment by alex-mtl** [comment]
@charrondev I believe we implemented new GlobalPermissionCheck Trait to fix this issue?
