### ISSUE TITLE
DateTimeFormatter is not accessible without `use` statement

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#10141]
When I add `use Vanilla\Formatting\DateTimeFormatter;` to the top of my plugin, everything is okay. But without that, I get a fatal "Class 'DateTimeFormatter' not found" error. I do not know if that can or should be changed, but since Gdn_Format is deprecated and the DateTimeFormatter is the replacement, it might be worth to mention that somewhere (at least in some upgrade docs)

**Comment by tburry** [comment]
This sounds like an issue in your code rather than our framework. A use statement just tells PHP the full name of a class.
