### ISSUE TITLE
Tabulations in a category's title should be converted to dashes(-) in the slug creation

### ISSUE THREAD

**Issue by vanilla-dbarbier** [vanilla/vanilla#10176]
**Describe the bug**
Categories titles have spaces( ) changed to dashes(-) upon slug creation. This does not apply to tabulation characters(\t) and potentially other **whitespace characters**, but it should. This has the potential to break navigation.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? **Yes**
2. Did you follow our generic troubleshooting steps already? **Could you provide me with a link to this. I'll keep it handy**
3. What Vanilla version are you using? **Version 4.0-2020.004-SNAPSHOT**
4. When did the issue start? **Since I started using the platform**

**To Reproduce**
![image](https://user-images.githubusercontent.com/61435952/76126827-29f44f00-5fce-11ea-9b23-1874c898740d.png)
1-See the attached image. The grey rectangles are tabulation characters.
2-I would advise you try that category title with the category url.
3-This will save but won’t be properly digested that the core’s url generator.
4-The outputed url(front-end navigation) will return a Page not found error.

**Expected behavior**
If **all whitespaces** were converted to dashes or simply removed from the url slug, this would likely fix the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/61435952/76126827-29f44f00-5fce-11ea-9b23-1874c898740d.png)

**Additional context**

**Comment by bleistivt** [comment]
I'm curious: What's the use case for having tabs in category titles in the first place?

I just confirmed that Vanilla replaces tabs in discussion titles with slashes which is the correct behaviour, as this is user generated content. But category titles can only be set by Admins or forum managers.

**Comment by vanilla-dbarbier** [comment]
There is no use case for it. :)
It is simply a validation error that has been overlooked and the outcome is unexpected. This is obviously a very low priority bug.

When specifying a Category url, I am unable to insert spaces, otherwise I get the following message:

> Url code can not contain slashes, quotes or tag characters.
> Url code cannot be numeric, contain spaces or be the name of an internal method.

Which is fantastic.

But if the url is allowed to have **whitespaces characters** or **%**(such as %09 or %02) this does breaks navigation on the frontend.

----------
It's great that the fields sanitation works well in the front-end.
I also understand as this interface is solely used by Admins & forum managers that it mitigates drastically the issue.

That being said, I do not believe that type of data should be _allowed_ in the database because it breaks navigation and is hazardous.

Code is often reused. At some point, this code _could_ be the foundation of what may become a frontend issue.

By all mean, send me feedback. Should this bug not have been filed?
Thanks!

**Comment by bleistivt** [comment]
I'm not a maintainer, but to me it is a perfectly valid bug, albeit low priority as you said.

I just thought you may wanted to denote subcategories using indentation for example, for which there is a better way, obviously.
