### ISSUE TITLE
Wrong profile picture when viewing mobile profile

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#10189]
I'm pretty sure I should see my own avatar in the upper right corner, and not the one of the profile user: 
![Screenshot_20200311-092058__01](https://user-images.githubusercontent.com/5205806/76396936-7c40c180-637a-11ea-9c1d-2c72f0ab0234.jpg)

I cannot check right now, if this is only an issue on open.vanillaforums.com

**Comment by igraziatto** [comment]
This issue was fixed in the theme-boilerplate a while back: https://github.com/vanilla/vanilla/issues/8731
I'm pretty sure open-vf-com just needs an update in the boilerplate package.
