### ISSUE TITLE
Image upload with responsive options

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#10209]
A recurring problem with image uploads is we need a responsive solution. We need a way to declare an image upload with breakpoints and separate uploads for each.

Data structure:

Example 1, single image, no breakpoints
```
{
	image: string,
}
```

Example 2, image with breakpoints
```
{
	image: {
		default: string,
		responsive: [{
			[breakpoint1]: {
				image: string;
				description: string;
			},
			[breakpoint2]: {
				image: string;
				description: string;
			}
			[breakpoint3]: {
				image: string;
				description: string;
			}
		}]
	}
}
```

The array will generate CSS with breakpoints. 

@ElisaAlmeida we need a design. I'm thinking if an input supports responsive images, it should have some type of toggle to expand additional uploads, with a label telling at what point does the image get used. We may also want a note that they will need to resize their browsers to see the preview?

**Comment by ElisaAlmeida** [comment]
The mockups:
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5e7370100200ac02f534d826

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/10389
