### ISSUE TITLE
Foundation: New Discussion Page issues

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10221]
New Discussion Page Issues:
1. The icons should have the same hover state that KB has it. (blue instead of gray)
2. The radio button should be the new one. 
3. The text "You can use Markdown in your post" could be smaller and closer to the
text area. And the word "markdown" should show that it's a link. It could be a blue link.
4. The buttons padding should be 12px. And it's weird the 4 buttons together, maybe we should change that?
5. Tags should be like the tags in the KB (gray instead of white) and same padding

<img width="835" alt="Screen Shot 2020-03-11 at 2 54 54 PM" src="https://user-images.githubusercontent.com/45467951/76468026-52f75400-63c1-11ea-981d-2978465d0577.png">

<img width="798" alt="Screen Shot 2020-03-11 at 3 10 49 PM" src="https://user-images.githubusercontent.com/45467951/76467994-407d1a80-63c1-11ea-89b1-a5280fe5184f.png">

**Comment by vrjrobitaille** [comment]
@ElisaAlmeida Can we make sure to test this with Rich Editor as well as that has some different styles
