### ISSUE TITLE
Foundation: Unable to dismiss my notifications

### ISSUE THREAD

**Issue by GeetikaMuthyam** [vanilla/vanilla#10229]
- [ ] Not only as an Admin but by being other users I should also be able to clear my notifications
1. Log in as an admin, I click on the 'Notifications tab'.
2. then I click on the 'All Notifications' button.
3. I navigate to the 'Notifications' page, there I am able to delete my notifications.
4. But when I logged in as another role, I don't have permission to delete my notifications.

![image](https://user-images.githubusercontent.com/45467951/76466331-d2832400-63bd-11ea-92f8-6e1c95d2249a.png)

- [ ] Home/Profile/Social, I see the connect button is in the wrong format.
1. When I click on the Profile
2. Then I navigate to Social.
3. I see the connect button format is wrong.
4. And also, I see the 'email' under the username is cutting off.

![image](https://user-images.githubusercontent.com/56363201/76524013-c50e7e00-643f-11ea-9b4e-00ff7f747fce.png)

**Comment by vrjrobitaille** [comment]
@GeetikaMuthyam I broke your issue out into individual reports

- Profile image  cut off  -   https://github.com/vanilla/vanilla/issues/10250
- Edit profile error - https://github.com/vanilla/vanilla/issues/10249
- Multiple tabs don't  close - https://github.com/vanilla/vanilla/issues/10248

**Comment by charrondev** [comment]
Closing for https://github.com/vanilla/vanilla/issues/9804
