### ISSUE TITLE
Foundation - Rich Editor menu issues

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#10242]
![image](https://user-images.githubusercontent.com/1770056/77005496-4336bd00-6937-11ea-9820-aaba59b452a9.png)

Menu items are too large in foundation rich editor menu.

**Comment by vrjrobitaille** [comment]
Looks ok to me now: 

![Screen Shot 2020-04-09 at 4.56.47 PM.png](https://images.zenhubusercontent.com/578e4ab0e40e5714b16c4114/30be9d1a-471b-4bd3-987a-b70447221555)
