### ISSUE TITLE
CountComments cannot accept a NULL value on DBA recalculate

### ISSUE THREAD

**Issue by MrCaspan** [vanilla/vanilla#10303]
**Describe the bug**
Possibility for a SQL command would return a NULL for a column that cannot be NULLable

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
Yes, Brand New install 

2. Did you follow our generic troubleshooting steps already?
Yes

3. What Vanilla version are you using?
3.3

4. When did the issue start?
As soon as I imported

**To Reproduce**
When using the dba tool to fix any column counts after an import it recalculates the CountComments for the Discussion table and if there are no comments for a discussion the getCountSQL() will return NULL and this CountComments cannot accept a NULL value.

**Expected behavior**
The getCountSQL() should return 0 if it finds no children of the Discussion

**Additional context**
How to fix

If you look at the function getCountSQL() in /application/dashboard/model/class.importmodel.php
the following line could return NULL

```
$result = "update :_$parentTable p
    set p.$parentColumnName = (
      select $aggregate(c.$childColumnName)
      from :_$childTable c
      where p.$parentJoinColumn = c.$childJoinColumn﻿)";
```
i have replace the code with an IFNULL so that if it ever returns NULL it will actually return 0

```
    $result = "update :_$parentTable p
         set p.$parentColumnName = (
           select IFNULL($aggregate(c.$childColumnName),0)
           from :_$childTable c
           where p.$parentJoinColumn = c.$childJoinColumn)";

```

**Comment by vredeling** [comment]
This suggestion solution works.
