### ISSUE TITLE
New comment count button suggestion

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10323]
I think we could change the "new comment count button". 
We have 2 options here:
- 1st option: increase the lateral size of the button. (I think the text is really close to the edge).
WRONG:
<img width="850" alt="Screen Shot 2020-03-30 at 3 19 40 PM" src="https://user-images.githubusercontent.com/45467951/77956818-8599bb80-72a0-11ea-917e-3e41f1a3bf78.png">

SUGGESTION:
<img width="850" alt="bug_space_new" src="https://user-images.githubusercontent.com/45467951/77956862-9c401280-72a0-11ea-8c33-964e8ae98946.png">

- 2nd option: Change button style. 
![bug_space_new_op3](https://user-images.githubusercontent.com/45467951/77958149-9ba87b80-72a2-11ea-8b0e-b7c381860e16.jpg)

I prefer the 2nd option but if @slafleche doesn't have a lot of time, he can implement the 1st one.

**Comment by slafleche** [comment]
I'm working on this, I'll have a PR out probably after the demo.
