### ISSUE TITLE
Check color is wrong

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10324]
In the Staff forum > View > All. The check icon in the dropdown is wrong. Right now is white but it's supposed to be blue (primary color).

WRONG:

<img width="356" alt="Screen Shot 2020-03-30 at 4 45 35 PM" src="https://user-images.githubusercontent.com/45467951/77960653-b11fa480-72a6-11ea-9535-0d3c9c53763e.png">

The correct color is BLUE.

**Comment by GeetikaMuthyam** [comment]
QA Results:

I still see the colour of view all in staff forums in dark grey as shown below:

<img width="778" alt="Screen Shot 2020-05-18 at 7 09 36 PM" src="https://user-images.githubusercontent.com/56363201/82267773-4f40fa00-993b-11ea-987f-73e1b6043f6d.png">

**Comment by GeetikaMuthyam** [comment]
It's done because, got confirmation from Stephane, that the design requirement has changed to grey from blue.
