### ISSUE TITLE
Action/History log

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#10349]
**Describe the Feature**
A log of actions made in Vanilla. 
This log would be *part of core* and would contain actions made by users of the forum.
These logs would be kept for a good amount of time (couple weeks/months) and their only purpose would be to make it easy to know when something happened and who actually did it. 

**User Story**
- Someone delete a User
- An administrator is made aware that a certain user is now missing
- The administrator check the logs and see that the user was deleted by one of its moderator exactly 12 days ago
- The moderator is fired and the administrator restore the user from an old backup he had of is forum
- Everyone is now happy!

Currently there is no clear/concise/easy/foolproof way to determine when some records have been deleted and by whom!!

**Acceptance Criteria**

- [ ] Destructive actions must be logged
   - [ ] Delete user
   - [ ] Delete comment
   - [ ] Delete discussion
   - *Please help me fill the rest of this. Thanks*
- Logs must be cleaned out of the live DB after a reasonable amount of time to prevent if from growing out of proportion
   - Optionally it would be really nice if the cleaned logs could be sent to an archive site like AWS. Configurable by the administrator.

**Additional context**
This is currently a problem that our Support/CSM/Ops team have to deal with. It is really hard to know when something happened and most of the time require multiple people to investigate in team to possibly find out what happened.

There are 2 resources that are currently existing which do not meet the above criteria:
- GDN_Log: Most of the time there is no log at all in there. Especially for users.
- GDN_EventLog: There's nothing regarding users resources in there AFAIK and it's always polluted by Analytics logs on  top of being an opt-in feature for our Hosting solution.

**Related Issues**
https://github.com/vanilla/dev-inter-ops/issues/29

**Comment by tburry** [comment]
We had some discussion about this. Currently, we do log comment and discussion deletes. We don't specifically log user deletes, but users are never really deleted, they are just flagged. Given that we have a case where user rows have gone missing I think we have some investigation to do there.

**Comment by charrondev** [comment]
One additional thought on this. We don't correctly follow user spoofing, but since this table will could big relatively quickly, I want to make sure we have a couple DB columns in here from the start as we will likely have future use for them.

- A general purpose json `attributes` column. (generic view only data, that could be different for different actions).
- An indexed "type" field. A few types might be "delete", "spoof", "permissionchange".

A couple ideas I can think would be good to add in the future.

- Tracking whenever a user spoofs another one.
- Tracking when a vanilla employee vfspoofs.
- Tracking when a user's role or rank is changed.
- Tracking when a role's permissions are changed.

**Comment by DaazKu** [comment]
> We had some discussion about this. Currently, we do log comment and discussion deletes. We don't specifically log user deletes, but users are never really deleted, they are just flagged.

The main goal of this issue is really to have more tracking capabilities regarded to actions make by users. That being said it this comes with the actual resources that were affected when said resources were destroyed this is even better!

**Comment by dannimajdalani** [comment]
> Tracking whenever a user spoofs another one.
> Tracking when a vanilla employee vfspoofs.
> Tracking when a user's role or rank is changed.
> Tracking when a role's permissions are changed.

A great idea to implement. I've had a few recent tickets were this would have been very helpful.
