### ISSUE TITLE
Input & buttons don't have enough padding with large border radiuses

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#10347]
~- Crank the border radius of your inputs and buttons.~
~- Notice the text can feel a little off-center in the input. (This is just adding more padding so the text doesn't start too deep in the curve)~
- We should have some algorithm to force a minimum border padding based on the border radius.
  - Theme control will change buttons and search bar boarder radius
    - [ ] 20px button padding for buttons
    - [ ] 16px for inputs at max roundedness

**Comment by GeetikaMuthyam** [comment]
**Testing Results:**
Bug : https://github.com/vanilla/knowledge/issues/1753
