### ISSUE TITLE
Discussion following filter applied after disabling SaveFollowingPreference

### ISSUE THREAD

**Issue by danni-stark** [vanilla/vanilla#10357]
### Details

Vanilla.SaveFollowingPreference config allows users to save followed Discussions, a config is added to the user's preference "followedDiscussion".

### Issue

When SaveFollowingPreference is disabled, we still apply the follow filter from the user's preference https://github.com/vanilla/vanilla/blob/681db04a18da73165bea6f0b1174444029a0c322/applications/vanilla/controllers/class.discussionscontroller.php#L161

Navigating to discussions/unanswered would return a discussion list filtered by the followed discussion. There currently isn't a UI for disabling the followedDiscussions filter (It needs to be removed from the db).
<img width="133" alt="Screen Shot 2020-04-02 at 5 47 51 PM" src="https://user-images.githubusercontent.com/31856281/78303146-1cb57c00-750a-11ea-9a88-2155eefc30d1.png">

Pagination on the other hand does not apply that filter. Having multiple pages of unasnwered questions would return the correct number of pages, without any discussions.

<img width="154" alt="Screen Shot 2020-04-02 at 5 52 25 PM" src="https://user-images.githubusercontent.com/31856281/78303483-bc730a00-750a-11ea-9039-e5cd88732606.png">
<img width="132" alt="Screen Shot 2020-04-02 at 5 52 09 PM" src="https://user-images.githubusercontent.com/31856281/78303500-c3018180-750a-11ea-8256-9d082aca6e1b.png">
<img width="89" alt="Screen Shot 2020-04-02 at 5 52 17 PM" src="https://user-images.githubusercontent.com/31856281/78303508-c72d9f00-750a-11ea-83c4-b92342b81fc9.png">

**Comment by vrjrobitaille** [comment]
@initvector I think this would be on your team to fix. Can we sync up on this? Clients have escalated this issue.

**Comment by vrjrobitaille** [comment]
@tburry We've received an escalation about this issue. Seems it's in both of our Iceboxes. Can we sync up on this in the morning and determine next steps?

**Comment by igraziatto** [comment]
Related: https://github.com/vanilla/support/issues/2327

**Comment by dannimajdalani** [comment]
This has created 2 support tickets so far. It should get fixed.
