### ISSUE TITLE
Foundation Theme interferes with JSConnect Sign Out.

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#10387]
In the Foundation Theme, the Sign Out link in the Me Box logs the user out of the forum but will not redirect to the Sign Out URL configured in JSConnect.

```
https://mysite.vanillaforums.com/entry/signout?TransientKey=KT6LmGwzHxVwh7ry&Target=https%3A%2F%2Fpaddykelly.vanillastaging.com%2F&override=0
``` 

which never redirects us to the Authentication Provider. Where as with Keystone you go to:

```
https://mysite.vanillaforums.com/entry/signout?TransientKey=NSkQMiWckUPv2tUc
```

which redirects to

```
https://sso.vanilla.localhost/jsconnect/signout?vfcookie=vf_paddykelly_XV99N
```

**Comment by igraziatto** [comment]
The issue is located in the titleBar and not the Foundation theme. I tested locally with Keystone and `$Configuration['Feature']['DataDrivenTitleBar']['Enabled'] = true;` and issue persists.

**Comment by igraziatto** [comment]
The issue seems to be that the signout URL is not set as the same as the original mebox. In the original mebox the signOut URL comes from the PHP function `signOutUrl()`. In the new mebox it's set on the component itself.
