### ISSUE TITLE
Design Search Results Pages for Social Groups & Category Search

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10412]
## Context

- Categories and social groups will be added to the global search index so that they show up in search results. We will add names and descriptions as search fields and results. Categories and groups will be included in regular search results and will be able to be specifically filtered via the advanced search form. 
- If possible and if the scope isn't too high, I'd also like to take the opportunity to implement some more feedback. We've also received requests around:
  - Adding Q&A Statuses (i.e. Answered vs Unanswered) on search results pages
  - Having a clearer view of Ideas and their statuses 

## User story:
As a user I want to easily find different types of content via search.  I should be able to identify which search results are:
- Articles
- Discussions
- Questions
- Answers
- Ideas
- Polls
- Categories
- Social Groups
- Users

Which search results appear first by default will be determined by how Sphinx is configured. 

## Acceptance Criteria: 
- Each search result type should be easily identifiable
- Advanced search filters should sill be included on the search results page
- Design of search filter should also be reviewed -
![Screen Shot 2020-04-13 at 4.00.43 PM.png](https://images.zenhubusercontent.com/578e4ab0e40e5714b16c4114/f2e68043-8829-41df-8211-1f7c27f4498c)

**Comment by ElisaAlmeida** [comment]
Mockups Desktop:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea986fa3d4612bf64e34ffc
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec6865cb36ecb4973f5b6cb
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec5889385a6b34883c3679b
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec5896838853828f4b797bc

Mockups Mobile:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec807464cd6d8460b036fa1
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec8074630c6ab4948e1c443
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec81361ed18a9466d31dff7
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec8074733cc444a8860f65e
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec8074664b54745eda540ff
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec807472491e92a892a6399

Member's page:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec6bfcd1e1c1446059cd2b5
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ec823e93a6d1a2952756f22
