### ISSUE TITLE
Ability to insert a pocket after the banner

### ISSUE THREAD

**Issue by rhysboswarva** [vanilla/vanilla#10417]
Ability to insert a pocket after the banner

From a selling point being able to put any front end code throughout the page is nice to be able to say.  However with Foundation and the new Theme Editor (which is awesome) you can no longer place Custom pockets.  This is fine, but there is one key position on the page that is missing.  The ability to place code right after the banner.  e.g. Tiles are a popular GUI feature that can't be done, without either Custom Dev, or placing a pocket after the banner.

Examples:

![image](https://user-images.githubusercontent.com/923781/79239496-a0dafe00-7e3e-11ea-8473-7d275a91e869.png)

![image](https://user-images.githubusercontent.com/923781/79239555-b3edce00-7e3e-11ea-948b-4cd997a01675.png)

Thanks 
Rhys

**Comment by slafleche** [comment]
@rhysboswarva am I right to assume the client would be satisfied with a customized home page? What exactly do they want to add?

**Comment by rhysboswarva** [comment]
No, it's the ability to add content below the banner.   Not sure what a "customized home page" is.  

like this:
![image](https://user-images.githubusercontent.com/923781/81183840-a6c78900-8f7d-11ea-8645-803781c5ac86.png)

**Comment by slafleche** [comment]
We do plan to allow the client to customize their home page with widgets. I feel like what they want here could be achieved with custom tile widgets on their home page?

**Comment by charrondev** [comment]
@slafleche That is not in our pipeline until much later in the year, and even then doesn't have the ability to customize through the dashboard.

The scope here, is there's a position beneath the banner where many people want to put some custom HTML widget.

The scope between another pocket location and a overhauled homepage system with some UI is massive.

**Comment by vrjrobitaille** [comment]
100% Example here is King's community, they've placed a "Join now!" CTA below the banner for Guest users. Smartsheet has also placed a Covid banner below their community bannner

<img width="1421" alt="Screen Shot 2020-05-06 at 5 20 23 PM" src="https://user-images.githubusercontent.com/18470831/81229496-e6ae6080-8fbd-11ea-8862-74edacd46710.png">

<img width="1410" alt="Screen Shot 2020-05-06 at 5 21 08 PM" src="https://user-images.githubusercontent.com/18470831/81229543-ff1e7b00-8fbd-11ea-8b5a-8d4bcab92e40.png">

**Comment by charrondev** [comment]
Note, this location would only be available for foundation.

**Comment by slafleche** [comment]
We will be using a feature flag in the theme to display the pocket.
