### ISSUE TITLE
Foundation: Social group edit group button hidden

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10438]
When trying to edit the group you have created, the edit button is hidden behind the announcement button:

![Screen Shot 2020-04-15 at 8 27 30 AM](https://user-images.githubusercontent.com/24961134/79351710-01ce0900-7f07-11ea-8c2f-48d55a7b0ea1.png)

**Comment by Bparm** [comment]
Any idea when we're going to fix this?

**Comment by vrjrobitaille** [comment]
Is this still occurring @Bparm We fixed it in another ticket for a customer in the last release. https://github.com/vanilla/support/issues/1892

**Comment by vrjrobitaille** [comment]
Confirmed issue is solved on Brendanès demo. Closing this out.
