### ISSUE TITLE
Pockets: More configuration options

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10435]
Within our pockets functionality, due to the fact that with the new theming editor and foundation theme you cannot use custom pocket locations, it would be wise to add some additional configuration options.

Some easy ones that I think would help

-Subcommunity/category chooser (flow down unless otherwise stated like with the hero image plugin)
-Choose roles that see the pocket's content.

More examples
https://blog.vanillaforums.com/product/power-pockets-adding-custom-html-js-vanilla-forum

For the category chooser, it would allow you only show specific ads in specific sections or make another kind of CTA only in that section.

By role it would be quite useful. Maybe you only want a survey to pop-up for a certain group of users or you want to display a message to the guest role to get them to register.

**Comment by vrjrobitaille** [comment]
Agreed. We had a long and difficult battle with some clients who had their ad code all straightened out, but needed a lot of help figuring out how to use conditional statements to get the ads to appear where they needed to. This would have been solved with the ability to configure a pocket to a specific category, similarly to how we handle Moderation Messages. 

We also have another client who needed to go through services to create custom pocket locations per subcommunity, which would be nice to avoid.

**Comment by vrjrobitaille** [comment]
Basic user stories here are:

- As an Admin, I want to create a Pocket to appear in a specific category or set of categories so I can create CTA and ads specific to my content category.
- As an Admin, I want to create a Pocket to appear in a specific subcommunity, so I can create targetted CTA, translated cookie conset forms and things of this nature.
- As an Admin, I want to create a Pocket to appear for a specific group of users based on their roles & permissions so I can create targetted CTAs for free vs premium userss, or guest vs registered users.

**Comment by charrondev** [comment]
## Additional Form elements

- Role Chooser (`<MultiRoleInput />`)
- Category chooser (`<CommunityCategoryInput />`)
- Checkbox for category inheritence
