### ISSUE TITLE
Design Event Creation Page

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10451]
## Context
Categories and Social Groups will support events. Users will need a page where they can create and edit event details and settings. Social Groups currently has this page - https://demo.vanillawip.com/en/event/add/2

![Screen Shot 2020-04-16 at 6.19.46 PM.png](https://images.zenhubusercontent.com/578e4ab0e40e5714b16c4114/3552ef79-cb24-4105-b1f3-30096246b1d0)

Users will need to be able to configure: 
- A title for the event
- A description, using Rich Editor
- A location
- A date
  - This will support setting a start and end date and time

We need to prepare for 2 scenarios: 
1. A user is creating a new event within a Social group - for this, we don't need anything beyond to fields mentioned above.
2. A user is creating a new event to post within community. For this they will need to have some way of configuring where the event should appear. We definitely need a way of configuring which categories the event should appear in, but I foresee the following options being requested longterm:
   - 1 or more categories 
  - On the homepage 
  - On the categories page 
  - On the discussions pages (nice to have)
  - On the KB chooser page(nice to have)

**Comment by ElisaAlmeida** [comment]
The "New event" page has the same width as the "New Discussion" one. (before was different)
We'll use the Rich Editor as default.
See the mockups:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea0b0d60046c27b9779e5aa
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea0b19e55b9ee51bbc01e03
