### ISSUE TITLE
Design Event Page

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10450]
## Context

Categories and social groups will support events. Event pages will provide the user with more information about the event in question. This page should show: 

- The Event Name
- Descripttion
- Date
- Location
- Who is attending the event

As an Admin, Mod, or Group leader, I shouuld also be able to see: 
- Who is not attending the eventt
- Who responded with a "Maybe" 

As a member, if I have no yet RSVP-ed to the event, I should have a prompt asking me if I am attending, with the options of yes, no and maybe. If I have RSVP-ed, selection should be displayed on this page, and I should have the option to change my answer at a later date. 

## Example:
![image (14).png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/0d6c9c66-c858-42ad-99fc-cbf856233f71)

![image (15).png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/2e80597f-b282-4ad9-bb65-26f9abac7ebc)

**Comment by ElisaAlmeida** [comment]
New Event Page:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea30df8c00cd52468d4cbdc

The **V1** will just appear the 10 avatars and the numbers. 
The **V2** will have a clickable number where the admin user will be able to see who is going/maybe/not going to the event:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea1e92d724b6078b7460cd3
