### ISSUE TITLE
Design Events List Page

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10452]
## Context
Categories and Social Groups will support events. There should be a page where users can see all upcoming events. 

Each Social Group has an "All Events" page for that specific group. e.g. -  https://demo.vanillawip.com/en/events/group/2-montreal-user-group

We would like to redesign this page for use in Social Groups. The design should also take into consideration a use case where we may implement an "All Events" page on community, where the user could see all event across any category or social group they have permission to view. 

## Acceptance Criteria
- The list of events should show a summary of: 
  - Event title
  - Description
  - Event date/time
  - Event location 
  - If this is a Social Group event, this should display the Social Group's name. 
 - It should be apparent to the end user, which events they are participating in, and which events they can still RSVP to, either by having some sort of "My upcoming events" section or some sort of "Attending" tag on the event list.
- This list would likely be permission gated i.e. 
  - Users would only see events configured to display in categories they have permission to see, or events configured to display on homepages. 
  - Public Groups, and groups they are members of.

**Comment by ElisaAlmeida** [comment]
Mockup Events list page:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ea200fa4adf596eb6445d47
