### ISSUE TITLE
Foundation: Edit Profile icon is wrong

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#10468]
**Describe the bug**
![Screen Shot 2020-04-20 at 10 56 08 AM](https://user-images.githubusercontent.com/31521020/79766165-995f9d00-82f5-11ea-9dfe-e6955ea5ba4c.png)

**Vanilla info**
4. When did the issue start? Release 2020.007 I believe.

**To Reproduce**
1. Go to a profile page you have permissions to edit.

**Expected behavior**
![Screen Shot 2020-04-20 at 10 58 39 AM](https://user-images.githubusercontent.com/31521020/79766381-e80d3700-82f5-11ea-895e-c57560ed512a.png)
(Keystone)

**Comment by charrondev** [comment]
@igraziatto is this on your localhost? I think caching may be playing a role, because the icon is correct on infra sites which have proper cache busting.

![image](https://user-images.githubusercontent.com/1770056/79784277-054eff00-8310-11ea-867a-8c8bf835bc06.png)

**Comment by charrondev** [comment]
If it is on infra it points to improper cache-busting on the icon fonts in use there.

**Comment by igraziatto** [comment]
The first screenshot if from the staff forum and the second if from my local using keystone.

**Comment by igraziatto** [comment]
Might be caching. It seems to be right now.

**Comment by charrondev** [comment]
Closing as it seems to be resolved. It may have also been an issue with some odd branch combination on the staff forum. That happens occasionally.
