### ISSUE TITLE
Proposal: APIv2 user spoofing header

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#10470]
## User Story

Vanilla currently offers the capability to administrators to persistently spoof a user session through it's interface with the `Spoof` plugin.

Automation/APIv2 workflows tend not to want to persistently session a lower-permissioned user and don't want to maintain potentially millions of access tokens.

## The Proposal

A new header will be supported in all APIv2 requests. It will look like this

```http
# User ID
Authorization: Bearer <your_access_token>
x-vanilla-spoof: user '493024'

# SmartID by name
x-vanilla-spoof: user '$name: JohnyAppleseeed'

# SmartID by email
x-vanilla-spoof: user '$email: johny@domain.com'

# SmartID by sso foreignID.
x-vanilla-spoof: user '$samlsso: 53205205'
```

See [further information on SmartIDs in APIv2](https://success.vanillaforums.com/kb/articles/46-smart-ids).

## How the Header Works

- The authenticated user making the request **must** have the `Settings.Manage` permission. If this permission is not present on initially authenticated user, a permission error will be returned (403).
- Once authenticated the following will happen
  1. The user in the header will be located (either directly or through SmartID).
    a. If the user cannot be found a Not Found error will be returned (404).
  2. For the rest of the duration of the request, all user information, **including permissions** will match the permissions of the user specified in the header.
- No persistent session will be generated for the user specified in the header.
- If the header is not present the request will proceed with user specified in the access token or current authentication.

**Comment by tburry** [comment]
This is most likely something I'll be taking up. Can I ask a few questions?

- Adding the "user" and single quotes parts to the header seems extraneous. Do you have a reason for wanting this?
- I would like the header to take an integer ID and then use our smart ID middleware to resolve against name, email, or SSO ID. I'm not sure the middleware likes having a space.
- I'll want to add the spoof info to logs using the `LogDecorator`.
- Why not use the regular spoof permission?
