### ISSUE TITLE
Community Events

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10491]
This is the Team Supreme task for - https://github.com/vanillaforums/oracle/issues/2, created here to allow for internal discussion and breakdown.

## Context
- Category pages need to support creating and listing events.  
- We currently have this functionality in Social Groups and want to leverage this same Event system and data structure so that users can create events in community. 
- We still need to collect final requirement details from the customer, but should be able to get started on our MVP implementation and easily be able to make small changes to match the customer requirements once they are received. Things I foresee in those requirements which we should be prepared to tackle later:
  - Placement of Events List on categories page
  - Potential need to permission gate events placed in specific categories
  - Potential need for additional info when creating events

## MVP Description
The first basic implementation needs to drive value for our existing customers by simply  -
- Allowing Mods to create events in community 
- Allowing users to view and RSVP to those events

We also know that we need the ability to list certain events in specific categories. So we know we need to  
- Create an "Upcoming Events" component, widget or module that can be added to category pages, and themes, 
- Create a setting for Events where we can configure the categories in which the event will appear.

## User Stories
- **As an Admin or Mod I want to create a new event in my community**
  - On community pages I will have a prompt to create an event (in the "New Discussion" dropdown?). This prompt will open the Event Creation page.  e.g. - https://demo.vanillawip.com/en/event/add/2
  - On the event creation page I can configure the event name, description, start and end date/time and the location of the event. 
  - Members will not be able to create new events. 
- **As a user I want to see a list of upcoming events in community so I can know which events I might be able to attend.**
  - I will be able to access a list of all upcoming events in community
  - Each event listed will show a summary of the event - name, description, date, location with a prompt to RSVP e.g. https://demo.vanillawip.com/en/events/group/2-montreal-user-group
  - I can click on an event and see its details and attendees e.g. - https://demo.vanillawip.com/en/event/1-lunch-and-learn
- **As an Admin I want to attach my event to a specific category**
  - When I create a new event, or edit an existing event, I will be able to select one or multiple categories in which my category will appear. 
  - When an event is attached to a specific category, this event will appear in a component, widget or module on this category page. 

## Acceptance Criteria: 
- Community events will use the same event data structure as social groups, but will add additional fields to show where the event is attached. This will allow us to use the same APIs for events rather than have to rebuild them from scratch.
- Adding an event to a category will have a separate permission that will allow event creation to be limited to moderators or staff. Users with the permission will be able to add an event while viewing the category via its options menu. The UI for adding/editing the event will be the same as the one used in the social group except the category will have a more basic header above the event.
- In order to view events within a category, there will be a module for displaying upcoming events that can be placed within the category via theming.

## Mockups In Progress:

Event Creation - https://github.com/vanilla/vanilla/issues/10451
Event List - https://github.com/vanilla/vanilla/issues/10452
Event Detail - https://github.com/vanilla/vanilla/issues/10450
Events in Categories - https://github.com/vanilla/vanilla/issues/104444

**Comment by charrondev** [comment]
Issue moved to [vanilla/internal #2439](https://github.com/vanilla/internal/issues/2439) via [**ZenHub**](https://www.zenhub.com/)
