### ISSUE TITLE
googlesignin - Photo is *** characters too long prevents login

### ISSUE THREAD

**Issue by dusti0777** [vanilla/vanilla#10514]
googlesignin - Photo is *** characters too long prevents login

**Describe the bug**

A user had a PDF as an image in his google profile. 
When he tried to login with the SSO (Sign In with Google) login was denied with the error: 

Photo is 560 characters too long.

**Vanilla info**
Vanilla 3.2 and vanilla 3.3

**To Reproduce**

1. Click on 'Sign In with Google'
2. error: Photo is *** characters too long

**Expected behavior**

- Login should not be prevented.
- check filetype of avatars from SSO 
- just ignore the the avatar if not an image 
- log the user in without avatar.
- create a log

**Comment by grintor** [comment]
Any update on this? We have users that cannot sign in. Also see this:
https://open.vanillaforums.com/discussion/38125/bug-with-sso-photo-is-560-characters-too-long

**Comment by carlafranca** [comment]
Try to replicate locally but getting an error.
I created the Google-signIn credentials in 1 password.
