### ISSUE TITLE
Design New Groups Landing Page

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10544]
@vrjrobitaille commented on [Sun May 03 2020](https://github.com/vanilla/knowledge/issues/1816)

## Context
Our Groups pages are in dire need of a face lift. 

As it stands today, the Group's landing page displays:

- My Groups
- New Groups
- Popular Groups
- A group's search module

Our new Group's page should show at a minimum
- My Groups
- All Groups
- A groups Search Module. 

## Customer Feedback
- It can be difficult to navigate back to main community pages. Can we include Quicklinks in the side panel?
- If you don't have many groups, the group's landing page shows the same groups in all three sections. Instead of showing all three options by default, show one view of all groups with filters. Always include "My groups"

## Considerations
- Eventually we will likely want to widgetize this page's set up. By default widgets should include everything we currently offer :
  - My Groups
  - All Groups
  - Popular Groups
  - Groups Search Module
- Other Group Widget ideas:
   - My Upcoming Events
   - New Groups
   - Featured Groups

## Wireframe
![Groups Landing Page.png](https://images.zenhubusercontent.com/578e4ab0e40e5714b16c4114/216f0719-326c-46b3-84c0-52dd726652ff)

**Comment by vrjrobitaille** [comment]
This is done, just  needs to be presented to the devs for  feedback - https://zpl.io/b6zDLOP

**Comment by vrjrobitaille** [comment]
We discussed these designs in Refinement today. As a first version, we'll  implement Option 3 here - https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ed80f0990fdb1ba46f8f14a

This will allow us to more easily deliver other layout options in the future. Our other options are great, but we've decided a better image upload experience is required to make these options usable in  real-world situations.

**Comment by ElisaAlmeida** [comment]
Desktop Mockups:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5f0caed755ca998e0f3dfd1f
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5f0caeda1df2a99cbac09ea9

Mobile Mockups:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5f087d8e80d37581ecf51252
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5f0cb2c40b521c8d2c574619
