### ISSUE TITLE
Design Group Page

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#10545]
## Context
Groups are in need of a face lift. 

Our current group pages include:
- A banner
- Group title
- Group description
- Group Icon
- Creation Date
- Group Owners & Leaders
- Number of Members
- Creation Date
- Section for announcements
- Section for discussions
- Section for events

Our new pages should include the same information but in a cleaner, updated layout.

## Considerations:
- We may want to eventually widgetize this page's set up. Default widgets should be:
   - Announcements
   - Discussions
   - Upcoming Group Events
   - Member List

## Wireframes:

![Screen Shot 2020-05-03 at 4.40.13 PM.png](https://images.zenhubusercontent.com/578e4ab0e40e5714b16c4114/d72f3e22-f4f4-4136-85d1-3371e7c52dcb)

**Comment by vrjrobitaille** [comment]
Also done,  just needs dev feedback - https://zpl.io/b6zDLOP

**Comment by vrjrobitaille** [comment]
Discussed in today's Refinement meeting. We've gotten an estimate from the team and some feedback.

Let's get 1 more option that merges Annoouncement and Discussionss into one module similar to how we display Announcements at the top of the list on the Recent Discussions page. We also have a pending task to add the # of appplicants and/or pending invitations there are.

<img width="226" alt="Screen Shot 2020-07-02 at 5 43 07 PM" src="https://user-images.githubusercontent.com/18470831/86411744-8705c600-bc8b-11ea-9f9c-bc60057672a8.png">

**Comment by ElisaAlmeida** [comment]
Desktop:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5ed7e0d33686a3b90e73244d

Mobile:
https://app.zeplin.io/project/5d0cf6049d476859d62a1512/screen/5f0e0f22a4bc428d33c47719
