### ISSUE TITLE
Rich Editor: Add rich embed support for Instagram Live/Stories

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#10572]
Currently, the Rich Editor supports embedding instagram posts. All Instagram images have a subfolder of /p/ in the URL (confirm how you're embedding IG already).

The request is to add stories and live(TV) to the embeds. 

Stories: https://www.instagram.com/s/aGlnaGxpZ2h0OjE3ODg2MTExOTczNTI2Nzgz?igshid=110wyhuanb93z&story_media_id=2292951088930558871

TV: https://www.instagram.com/tv/B_x4gCgl7Mw/?igshid=1iv7rqdmmj87m

Use case: Being able to share live or story content from IG to the community.

**Comment by charrondev** [comment]
Scope of the issue is:

- Add support for these URL patterns.
- Add tests for them.
