### ISSUE TITLE
Discussion & Comment Editing Not Persisting

### ISSUE THREAD

**Issue by rossdotparker** [vanilla/vanilla#10583]
**Describe the bug**
In v3.2 and v3.3 we are setting the Discussion & Comment Editing setting to allow editing within a month, but every time we reload the page it resets to the default:

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? Seems to be core related.
2. Did you follow our generic troubleshooting steps already? Not sure where to find these.
3. What Vanilla version are you using? v3.3
4. When did the issue start? v3.2

**To Reproduce**
1. Go to Dashboard
2. Click on Settings
3. Scroll down to Discussion & Comment Editing
4. Change the value.
5. Save
6. Return to step 1., and notice that in step 3. the setting has reverted.

**Expected behavior**
The setting changes, and the change persists.

**Screenshots**
<img width="655" alt="Screenshot 2020-05-14 at 2 48 28 PM" src="https://user-images.githubusercontent.com/5436438/81902238-5e017700-95f2-11ea-95f9-0eead54b247e.png">

**Additional context**
Thanks for working to provide a great forum platform : )

**Comment by bleistivt** [comment]
Check if your conf/config.php is writeable by PHP.

**Comment by rossdotparker** [comment]
Hi @bleistivt that did the trick, thanks! I assumed this was stored in a database, and so did not even think of file permissions. My bad. Thanks : )

**Comment by rossdotparker** [comment]
Actually, it seems not to have worked properly. The setting has indeed written to the file:

$Configuration['Garden']['EditContentTimeout'] = '-1';

But, it comes up in the interface as "Authors may never edit", and authors cannot edit their own content.

I'm stumped!
