### ISSUE TITLE
Rich Editor not closing `strong` tag breaking the HTML

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#10802]
The Rich Editor is failing to close `strong` tags when inside a group (like a heading for example) and more `strong` content is following.

This issue was reported twice already:
- https://github.com/vanilla/support/issues/1452
- https://github.com/vanilla/support/issues/1451

You can notice the issue happening on [this community](https://community.king.com/en/candy-crush-saga/discussion/278308/finished-win-gold-bars-tag-you-re-the-one-contest/p18#Comment_597996) where from this comment beyond all other comments in the same page are bold (and it ends up breaking the bottom pagination).  

It seems the issue is isolated to that comment specifically and that the issue is isolated, but it's not, if you navigate on that discussion you can see the same issue happening on pages 13,14,15, and 16.

**To Reproduce**
1. Get the comment body from that comment linked above ([you can get it from here](https://community.king.com/en/candy-crush-saga/discussion/278308/finished-win-gold-bars-tag-you-re-the-one-contest/p18.json))
2. Make a comment in a discussion on your local using the **rich** format with that body.
3. Make a few more comments
4. See all the comments after the copied comment get bolded.
5. If your discussion has pagination, you can also observe the bottom pagination breaking.

**Expected behavior**
For the `strong` tag to close within its parent.

**Additional context**
I believe the issue is on https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Quill/BlotGroup.php#L215 where it doesn't have a statement to identify if any tags where left unclosed before it closes the terminator.

**Comment by charrondev** [comment]
Step 1 is to get a reproducing issue into the fixtures for `RichFormatTest`.
