### ISSUE TITLE
Embed any video plateform

### ISSUE THREAD

**Issue by webafrancois** [vanilla/vanilla#10819]
**Describe the Feature**
Today, exist some Federate videos platforms like Peertube (https://joinpeertube.org/) which could be be integrated in a Vanilla forum. But URL can't be filtering like Youtube or Vimeo because everybody can have his proper server on his proper domain with peertube instance like those 500 instances :
* https://the-federation.info/peertube

**Acceptance Criteria**

It would be great if Vanilla support any iframe with an option in Dashbord like this : 
[ ] enable any iframe.
which don't use the filter and accept <iframe>.

Then, any filter should be accept if the admin make this choice.

**Comment by Unkorneglosk** [comment]
I think it may be a nightmare to allow any iframe. 
But still, there should be a way to support PeerTube.
Maybe add a check to the instances list and filter like every other video plateform.
