### ISSUE TITLE
Add a DomUtils::pregReplaceCallback() function and processor

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#10820]
We are getting close to the point where we will be able to address a long standing issue with Civil Tongue where there is no central place to process user generated strings. Getting that capacity is currently in the backlog of Team Supreme, but ICB Force will do the actual Civil Tongue functionality.

To get ready for that work I would like to see a `DomUtils::pregReplaceCallback()` function and corresponding processor. Why? Well, at the heart of Civil Tongue is just a plain ol' call to [preg_replace](https://github.com/vanilla/addons/blob/master/plugins/CivilTongueEx/Library/ContentFilter.php#L35). However, the problem with this is that it doesn't respect HTML and can badly mangle it. A replacer that acts on a `DomDocument` would be much better.

I'm thinking of something like the following:

```php
public static function pregReplaceCallback(DOMDocument $dom, $pattern, callable $callback, array $attributes = ['title', 'alt', 'aria-label']): int
```

This function will go through the DOM and perform a `preg_replace_callback` on text nodes and the given attributes. It will return a count of the number of replacements made.

## Acceptance Criteria

- Do a bit of research or ping some devs in slack for good default attributes to replace. We want all attributes that contain text. Stephane is a good person to ask.
- We want the utility function and the processor.
- We want tests. Assert replacements and counts.

**Comment by charrondev** [comment]
An xpath of `//text()` should get you all of the text nodes.
