### ISSUE TITLE
{debug_vars} in docs should just be {debug}

### ISSUE THREAD

**Issue by motoenth** [vanilla/vanilla#10849]
If {debug_vars} is added to default.master.tpl as currently described in docs, it will throw a browser error...

![debug_vars](https://user-images.githubusercontent.com/1969581/85617098-b03faa00-b62c-11ea-9d7d-d062f5c2749d.jpg)

If {debug} is used, new window with Smarty vars appears as expected...

![debug](https://user-images.githubusercontent.com/1969581/85617315-0c0a3300-b62d-11ea-94c0-5ac2f4816520.jpg)

Thank you all for such great forum platform. Two thumbs up!! 👍 👍

**Comment by tburry** [comment]
I think this is an inconsistency in versions. We had changed to `{debug_vars}` to output variables that does a bit of filtering on things like email addresses and password hashes in order to protect themers from leaking sensitive data during development.

**Comment by motoenth** [comment]
It's obviously up to you guys. Honestly, I've never been successful at getting {debug_vars} to output _anything_ :/

Sold a PHP/MySQL Classified Ads script for years before Craigslist took over the country. We used Smarty. It's a GREAT template engine. Back then, our struggle was convincing our customers just how powerful Smarty is. My guess is you guys may experience the same thing PLUS having to overcome the age of Smarty.

Anyhoo - like I said, this forum bundle is _AWESOME!_ Thanks for making a non-commercial version available. Proud to have the Vanilla logo on every page! 👍

**Comment by charrondev** [comment]
@motoenth This is probably because the `{debug_vars}` will only be available starting in the 4.0 release which is still in progress.
