### ISSUE TITLE
Dashboard issue

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10930]
Issues on the Dashboard > KB > Universal Content: 

- the search bar has a bug. One side has a border-radius and the other one doesn't... 
- the padding between the search bar and the line is wrong (too close).

![Screen Shot 2020-08-19 at 6 00 57 PM](https://user-images.githubusercontent.com/45467951/90694282-5f23ef00-e246-11ea-8263-fd60ce7ab2b0.png)

**Comment by genihoker** [comment]
Still trying to find out what bug is this type of[,](https://theductlessrangehood.com/) but want to learn about this dashbaord code issue.
