### ISSUE TITLE
Opentext mockup

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#10989]
Opentext has a community with us:
https://forums.opentext.com/forums/support

We need to redesign a new Opentext community.
Some Opentext issues:
https://github.com/vanillaforums/estimates/issues/1392
https://github.com/vanillaforums/estimates/issues/1404
https://github.com/vanillaforums/estimates/issues/1405
https://github.com/vanillaforums/estimates/issues/1406

**Comment by vrjrobitaille** [comment]
Issue moved to [vanilla/vanilla-cloud #1977](https://github.com/vanilla/vanilla-cloud/issues/1977) via [**ZenHub**](https://www.zenhub.com/)
