### ISSUE TITLE
Sitemap Addon typo on CountDiscussions

### ISSUE THREAD

**Issue by rosdyana** [vanilla/vanilla#11007]
**Describe the bug**
https://github.com/vanilla/vanilla/blob/4c86174062b8e6563a952edda25cdacb71bb4d57/plugins/Sitemaps/class.sitemaps.plugin.php#L126

I think there is a typo there, 

it should be "CountDiscussions" instead of "countDiscussions".

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? this is official addon problem
2. Did you follow our generic troubleshooting steps already? yes
3. What Vanilla version are you using? 3.3
4. When did the issue start? immediatelly

**To Reproduce**
1. Go to addon page
2. Open the sitemap addon settings
3. Enable the Discussion Based Sitemaps
4. Check the generated sitemap xml is not correct

**Expected behavior**
The generated sitemap xml is limited to 1000 for each pages, the problem will happened on the next 1000+ pages, it will be always return to not found exception because of those typo.

**Screenshots**
![image](https://user-images.githubusercontent.com/4516635/106080551-3e938580-6152-11eb-8031-eaf20f531128.png)

**Additional context**

**Comment by cchabilall83** [comment]
quick fix https://github.com/vanilla/vanilla-cloud/pull/1991

**Comment by rosdyana-asus** [comment]
> quick fix [vanilla/vanilla-cloud#1991](https://github.com/vanilla/vanilla-cloud/pull/1991)

@cchabilall83 nice, but unfortunately I am not able to see that private branch 😊

**Comment by rosdyana** [comment]
> quick fix [vanilla/vanilla-cloud#1991](https://github.com/vanilla/vanilla-cloud/pull/1991)

@cchabilall83, nice but sadly I am not able to see that private branch 😊
