### ISSUE TITLE
Default Category Permissions won't save

### ISSUE THREAD

**Issue by Unkorneglosk** [vanilla/vanilla#11011]
I don't see exactly why this behaviour happens, but it seemed it happend to me when having a lot of categories (more than 30ish). 
So, at a point, when i edit a role permissions, the default categroy permissions would be cleared. 
And when I edit this role again, it will always fail to save anything for that table. 
I can still edit other permissions. 
Oh and when it happens for one role, it will happens for every other role i try to edit after that.
So now users are unable to see discussions, participate. 
I disabled all plugins and the bug is still there. 

My forum is running on Vanilla 3.3.

**Comment by Unkorneglosk** [comment]
Okay it seems that, at some points, it looks like something is worng with the "PermissionCategory -1" row. I deleted it, checked all boxes and now it seems to work correctly.
I did open an issue here because it not only happened on one of my live forums but also on the dev one, who has yet no addon activated.
"Resolved" the same way.

**Comment by hazeelowod35** [comment]
Thank you for your contributions
