### ISSUE TITLE
"Permission Problem" After Changing Member Permissions

### ISSUE THREAD

**Issue by douglasgreen** [vanilla/vanilla#11028]
I'm running Vanilla 2021.003 RC2.

 I wanted to test a change to member permissions. So I did the following:

1. Clicked Roles & Permissions
2. Edited the member role
3. Checked the box to give permission to delete comments
4. Clicked save

Now when a member logs in all they see is the message "Permission Problem". Is that a bug in Vanilla Forums?

I tried changing the permissions back to what they were but that didn't fix it. I also tried more than one member account but they all had the permission problem message.

**Comment by BlakeUpham** [comment]
Was there a solution to this issue?

**Comment by Kailashaghera** [comment]
I am having same problem with Version 2021.009. Is this a bug. I did not change any permissions but I just saved "members" permissions without any change and now all users are not able to see the forums and categories nor any post.

**Comment by Blake254** [comment]
> I am having same problem with Version 2021.009. Is this a bug. I did not change any permissions but I just saved "members" permissions without any change and now all users are not able to see the forums and categories nor any post.

I had this same issue. My fix was to go into the database and manually set each of the permission values in the 'GDN_Permission' Table.
