### ISSUE TITLE
EXIF-based image rotation broken due to incorrect parameter typing in ImageResizer.php

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#11073]
Bug is here: https://github.com/vanilla/vanilla/blob/8b460a8d64df77f5bb1ce7a1b4e2b09efb3a38f6/library/Vanilla/ImageResizer.php#L347

Expected function signature: `exif(string $source, int $imageType)`
Actual function signature: `exif(string $source, string $imageType)`

This bug breaks EXIF image rotation (and probably other EXIF functions too I didn't dig into it any further)

**Comment by bleistivt** [comment]
still a problem
