### ISSUE TITLE
richEditorLegacy.scss hides entire body

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#11086]
Vanilla 2021.012: upgrading to this version causes the entire site to vanish due to a `body { visibility: hidden; }` in richEditorLegacy.scss (with Keynote theme selected; also happens with Bootstrap theme. Same issue applies to result screen in /utility/update).

See example at https://staging.forum.loopyapp.com.

**Comment by rockymontana** [comment]
I even get that on /dashboard/setup 🤦

**Comment by Github-Newbie5432** [comment]
Yep this affects every build afterwards too right up to 2022.021, took me forever to work out! 

Wouldn't cross your fingers too much for a fix though as it looks like the Open Source release has pretty much been abandoned at the moment, and with PHP 7.4 about to hit end of life , Vanilla doesn't support PHP 8 :(

**Comment by michaeltyson** [comment]
Yeah. Pretty grumpy about all that.

**Comment by rockymontana** [comment]
I quit using it mostly because of it. Didn't have time to mess around with it so I went with another system instead.
Hope they'll fix it though, but like @Github-Newbie5432 says - there are a lot of other things that might need higher priority.

**Comment by michaeltyson** [comment]
Out of curiosity.. what did you move to? I'm pretty confident that I'll need to find another platform too.

**Comment by Github-Newbie5432** [comment]
Hi Everyone,

I built 2023.001 this morning from source and this seems to be fixed in this release. Have uploaded the release here if you'd like to download (it works out-of-the-box on PHP 8.1.12 + PHP 8.2.1 without any workarounds!)

https://open.vanillaforums.com/discussion/39237/vanilla-2023-001-open-source-release-php-8-works-built-from-source
