### ISSUE TITLE
Recalculate Conversation.CountParticipants results in invalid SQL due to ambigious subquery. 

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#11128]
**Describe the bug**
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select count(uc.ConversationID) from GDN_UserConversation uc where uc.Conversati' at line 2"

Recalculate Conversation.CountParticipants result in invalid SQL
CountParticipants option is using a sub query which refers to c.CountParticipants but c is not defined in that select statement.

https://github.com/vanilla/vanilla/blob/cb6f17dac13d0437ceaf19f3c91f70f68c143e5d/applications/conversations/models/class.conversationmodel.php#L80-L88

results is a query like so 

`update GDN_Conversation set c.CountParticipants=(select count(uc.ConversationID) from GDN_UserConversation uc where uc.ConversationID = c.ConversationID and uc.Deleted = 0);`

this would result in the following error if run manually 

 _**You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select count(uc.ConversationID) from GDN_UserConversation uc where uc.ConversationID = c.ConversationID and uc' at line 1**_

While you could argue the update statement defines c. c needs to be defined in the subquery to be understood. MySQL Update even supports joins or better still split it up into two statements. 

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? yes
2. Did you follow our generic troubleshooting steps already? yes
3. What Vanilla version are you using? 2021.012
4. When did the issue start? when run /dba/counts Recalculate Conversation.CountParticipants

**To Reproduce**
1. Go to /dba/counts 
2. click on Recalculate Conversation.CountParticipants
3. Start 

**Expected behavior**
for count to update correctly without error

**Comment by Github-Newbie5432** [comment]
I built 2023.001 this morning from source and this seems to be fixed in this release. Have uploaded the release here if you'd like to download (it works out-of-the-box on PHP 8.1.12 + PHP 8.2.1 without any workarounds!)

https://open.vanillaforums.com/discussion/39237/vanilla-2023-001-open-source-release-php-8-works-built-from-source
