### ISSUE TITLE
Layout returning Request failed with status code 404 with 2021011 and latest github

### ISSUE THREAD

**Issue by jayk1961** [vanilla/vanilla#11147]
When in Settings->Layout, Request failed with status code 404 is returned. 

No errors in logs, only the access, which is:

This is all that is returned in the apache2 access log:

111.111.111.111 - - [04/Jan/2022:21:08:32 +0000] "POST /index.php?p=/dashboard/userpreferencesectionlandingpage HTTP/1.1" 200 822 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:32 +0000] "GET /index.php?p=/dashboard/settings/layout HTTP/1.1" 200 21034 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:32 +0000] "GET /api/v2/locales/en/translations.js?h=2021.024 HTTP/1.1" 404 488 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:33 +0000] "GET /api/v2/themes/keystone?revisionID= HTTP/1.1" 404 488 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:33 +0000] "GET /api/v2/config?select=discussions.layout%2Ccategories.layout%2Croutes.defaultController HTTP/1.1" 404 488 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:33 +0000] "POST /index.php?p=/settings/analyticstick.json HTTP/1.1" 200 751 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:33 +0000] "GET /index.php?p=/utility/getfeed/news/5/extended HTTP/1.1" 200 2152 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
111.111.111.111 - - [04/Jan/2022:21:08:33 +0000] "GET /index.php?p=/utility/getfeed/releases/5/extended HTTP/1.1" 200 3137 "http://AWEBSITE.COM/index.php?p=/dashboard/settings/layout" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? 

Yes. This is a *FRESH* install with newly created database. I've refreshed it many times by re-downloading, and deleting the database. I cannot get rid of this Layout 404 error that displays in red.

2. Did you follow our generic troubleshooting steps already?

Yes, I did. 

3. What Vanilla version are you using?

I tried with the latest version, 2021011.zip and github latest. Same error.

4. When did the issue start?

This is a new install on Ubuntu. PHP 7.4, mysql-8, apache2.4.48, composer1, php-fpm 7.4.

Click on Settings->Layout

URL: DOMAIN/index.php?p=/dashboard/settings/layout
Error: Request failed with status code 404

Scrolled up down, did not see anything. 

**Additional context**
If I can debug this further, please let me know. I don't see any File not found, Can't write, or any errors.

**Comment by charrondev** [comment]
It seems your web server is not configured correctly. Since at the 3.0 releases, "pretty urls" (or urls the way the entire rest of the internet work) have been required.

Eg. your URLs should be `DOMAIN/dashboard/settings/layout`.

https://open.vanillaforums.com/discussion/comment/220157/?__hstc=125439637.5830b955f5c6f3101471c54d01795f52.1565689223156.1566534918186.1566544065652.69&__hssc=125439637.46.1566544065652&__hsfp=3718556565#Comment_220157

This should show you how to do it with Apache. If you are using nginx you can look at our docker example:

https://github.com/vanilla/vanilla-docker/blob/master/resources/etc/nginx/sites-available/dev.vanilla.localhost.conf#L60
