### ISSUE TITLE
Problem: 2022.002-oss is named 2022.001-oss

### ISSUE THREAD

**Issue by Neustradamus** [vanilla/vanilla#11156]
Problem: https://github.com/vanilla/vanilla/releases/tag/2022.002-oss is named 2022.001-oss

Can you rename it?

https://github.com/vanilla/vanilla/releases/tag/2022.001-oss is good.

**Comment by charrondev** [comment]
Yup I've fixed it!

**Comment by Neustradamus** [comment]
@charrondev: Thanks for the quickly change! :)
