### ISSUE TITLE
usmallint type is included in database structure for MySql but also disallowed 

### ISSUE THREAD

**Issue by timanderson** [vanilla/vanilla#11150]
The file applications/dashboard/settings/structure.php defines tables including Media and Ban which define column types of usmallint and uint.

The file library/database/class.mysqlstructure.php defines $validColumnTypes which does not include usmallint or uint.

As a result, when you run utility/structure or utility/update you get an exception "The specified data type (smallint unsigned) is not accepted for the MySQL database."

Either usmallint should not be used, or it should be added to the valid column types, I am not sure what the rationale was for excluding it.

My current fix is to change these types to int.

**Comment by charrondev** [comment]
Are you using percona? On our setups it looks like `usmallint` gets passed in the table creation to percona, which creates a column like this `smallint(5) unsigned`. Our driver knows how to understand that.

**Comment by timanderson** [comment]
No I am using MySQL Community Edition.
