### ISSUE TITLE
Setup fails on Plesk - + nginx

### ISSUE THREAD

**Issue by Elf36** [vanilla/vanilla#11168]
🚨 The issue tracker is not for questions 🚨

we have installed Vanilla with a few extra tweaks and is working on one server.
We have moved the code to a new plesk server and installed using Plesk's composer GUI without error however when we go to login we get the following error.
the browser tries to load the setup page and it appears a connection to a database is tried.

We have nginx in front and a valid SSL cert -

`2022-12-12 23:54:03	Error	[privateIP]	504	GET /index.php?p=/dashboard/setup HTTP/2.0	https://hubs.ourhostserver.com:8443/	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0	160 	nginx SSL/TLS access
2022-12-12 23:54:03	Error			Stack trace:
#0 /var/www/vhosts/forum.example.com/httpdocs/library/database/class.database.php(143): Gdn_Database->newPDO('host=dbhost;dbn...', 'dbuser', '')
#1 /var/www/vhosts/forum.example.com/httpdocs/library/Vanilla/Models/LockService.php(76): Gdn_Database->connection()
#2 /var/www/vhosts/forum.example.com/httpdocs/library/Vanilla/Models/LockService.php(36): Vanilla\Models\LockService->createPdoStore()
#3 [internal function]: Vanilla\Models\LockService->__construct(Object(Garden\Container\Container))
#4 /				nginx error
2022-12-12 23:54:03	Error	[privateIP]		2091810#0: *1570 upstream timed out (110: Connection timed out) while reading response header from upstream`

in php log we get -

An error occurred while attempting to connect to the database. dsn: host=dbhost;dbname=dbname;host=dbhost;dbname=dbname ...
 
The error message is defined in the code (in /var/www/vhosts/[forum.example.com//httpdocs/library/database/class.database.php](http://forum.example.com//httpdocs/library/database/class.database.php)). See Stack trace in the domain Logs:

**Comment by janicebel** [comment]
Here are some troubleshooting steps you can try to resolve this issue:

Check Database Credentials: Verify that the database credentials (host, username, and password) used in the configuration are correct and match the database settings on the new Plesk server. Ensure there are no typos or mistakes in the credentials.

Database Accessibility: Ensure that the database server is accessible from the new Plesk server. Check if there are any firewall rules or security settings that might be blocking the connection.

Test Database Connection: You can try to test the database connection manually to see if it works. You can create a simple PHP script to establish a connection to the database using the same credentials used by Vanilla. This will help you verify if the database server is reachable and the credentials are correct.

Check Database Privileges: Make sure that the database user has the necessary privileges to access the database. The user should have at least read and write permissions for the database.

Database Host: Double-check the database host value in the configuration. It should be the hostname or IP address of the database server where the database is located.

Regards
hoodies revenge
