### ISSUE TITLE
constraint errors on composer update and install!

### ISSUE THREAD

**Issue by NukeSheriff** [vanilla/vanilla#11167]
Problem 1
    - metasyntactical/composer-plugin-license-check is locked to version v0.5.0 and an update of this package was not requested.
    - metasyntactical/composer-plugin-license-check v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.
  Problem 2
    - wikimedia/composer-merge-plugin is locked to version v1.4.1 and an update of this package was not requested.
    - wikimedia/composer-merge-plugin v1.4.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.2.0] but it does not match the constraint.

**Comment by Blitheness** [comment]
You're using composer 2. Vanilla for some reason won't upgrade from Composer 1.

Solution: use composer v1

**Comment by ernestbuffington** [comment]
Composer 1 is being retired, just got off the phone with chad.

**Comment by ernestbuffington** [comment]
You can use both versions of the composer if you set up your server to do so but most folks are not going to do that. It's sad because I really dig the vanilla forum.
