### ISSUE TITLE
 Custom Fields 'Private' visibility and editing permissions not working

### ISSUE THREAD

**Issue by AltB** [vanilla/vanilla#11173]
Fields with visibility **private** is not shown when editing my own profile (I should be able to see and edit **public** and **private** fields).
Fields with only visibility **public** are shown but save do nothing (no js/api error). Only roles with personalinfo.view permission can save them.

**Vanilla versions tested**
All versions with the new profile extended fields system 2023.001 and 2023.002(own build or other custom builds).
Tested on copy of existing forum and on blank forum (apache, nginx docker, php7.4 and php8.x).

**To Reproduce**
Add 1 or 2 members basic users
Add 3 profile's fields : 1 public, 1 private, 1 internal

Try to edit /save your profile : you see only public fields and cannot save (with proper profile edit permission set). You should see public and private fields and could save themes properly without using personalinfo.view permission (who permit to see all users private information).

**Comment by alteiis** [comment]
In 2023.006 like previous @charrondev

In UserProfiles.hooks.ts (line 62 -65) : 
Visibility filtering only check hasPermission("personalInfo.view") not if the current user is editing his profile. So react render only fields with visibility set to 'public' for members (no 'personalinfoview' persmission).
Api is ok and get all custom fields for current user (api check if user get is own profile).

    const profileFields = useMemo<ProfileField[] | undefined>(() => {
        if (!profileFieldApiNames || profileFieldApiNames?.status !== LoadStatus.SUCCESS) {
            return undefined;
        }
        return Object.values(profileFieldsByApiName)
            .filter(({ apiName }) => profileFieldApiNames.data!.includes(apiName))
            .filter(
                filterPermissions
                    ? (profileField) => {
                          switch (profileField.visibility) {
                              case ProfileFieldVisibility.PUBLIC:
                                  return true;
                              case ProfileFieldVisibility.PRIVATE:
                                  return hasPermission("personalInfo.view");
                              case ProfileFieldVisibility.INTERNAL:
                                  return hasPermission("internalInfo.view");

**Comment by newworldapk** [comment]
Field permissions specify the access level for each field in an object.Required Editions [instapro](https://instapro-apk.com/) and User Permissions Available in: Salesforce Classic

**Comment by olivia431** [comment]
Hello there,
Based on the information provided, it seems like there may be a bug in the Vanilla forum software related to the visibility settings of profile fields. To troubleshoot the issue, you could try the following steps:

Check the permissions settings for profile editing and ensure that the proper permissions are granted to the relevant user roles.
Double-check the visibility settings for each profile field to ensure that they are set correctly.
Check the Vanilla forum software documentation or community forums to see if others have reported similar issues or if there are any known solutions or workarounds.
Consider contacting the Vanilla forum support team for further assistance in troubleshooting and resolving the issue.
It may also be helpful to provide more specific information about the error, such as any error messages that are displayed, in order to better diagnose the issue[.](https://modlonely.com)

**Comment by newworldapk** [comment]
visibility filtering only checks hasPermission("personalInfo.view") not if the current user [televisión libre](https://futbollibres.online) is editing his profile. So react render only fields with visibility set to 'public' for members

**Comment by janicebel** [comment]
Here are some possible explanations and steps to resolve the issue:

Check Profile Field Settings: Ensure that the profile fields you created have the correct visibility settings. For the private field, it should be set to only be visible to the user (its owner). For the public field, it should be visible to everyone. For the internal field, it might be limited to certain user roles or permissions.

Review User Permissions: Verify that the users trying to edit their profiles have the necessary permissions to edit their own profile fields. They should have permission to edit both public and private fields on their own profile.

Personalinfo.view Permission: Check the personalinfo.view permission to see if it is correctly configured. This permission should be given to roles that need to view all users' private information, but it should not be required for users to save their own public fields.
Regards
Oshas
