### ISSUE TITLE
Analytics Not Working

### ISSUE THREAD

**Issue by AathifMahir** [vanilla/vanilla#11179]
Analytics not working on Vanilla OSS Release, It always says Page Not Found whenever we visit the Analytics Page on Dashboard.

![Screenshot_20230728_150903_Chrome.jpg](https://github.com/vanilla/vanilla/assets/17165402/1fb24b26-a8aa-48a7-a813-56ac25678eb7)

But that has to say, Analytics Does show Data when it comes to Profile Section, Regarding when the User Profile is Created, How Many No of Posts and etc..

Tried Solution:
Disabled All the Adblockers, Tried Different Browser, Tried Different Installation using Docker and etc..

Even on Js Console, There's no error to be found

**Edit:**
If anyone knows, what is happening here. Would you mind showing some light in this issue. Is this related to some subscription that I should acquire from higher logic or something wrong with my installation. I'm not sure

**Comment by sleepyowl12** [comment]
Could someone please shed some light on this issue? I'm unsure if it's related to a subscription that needs to be acquired from Higher Logic or if there's a problem with my installation on my video [downloader](https://pinterestdownloadonline.com/) site. Any insights would be greatly appreciated.
