### ISSUE TITLE
Fibers package not supported in node > v16.x

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#11180]
**Describe the bug**
with node > 16 fibres package  is no longer supported. 
https://github.com/laverdet/node-fibers

>NOTE OF OBSOLESCENCE -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then async/await, Promises, and Generators were standardized and the ecosystem as a whole has moved in that direction.

**Vanilla info**
2023.016 build from scratch

**To Reproduce**
To build 
run ./bin/release.sh
with version 2023.016

with result in

```bash
Building frontend assets

TS_NODE_PROJECT=/home/name/vanilla-release-2023.016/build/temp/vanilla/build/tsconfig.json node  -r /home/name/vanilla-release-2023.016/build/temp/vanilla/node_modules/ts-node/register /home/name/vanilla-release-2023.016/build/temp/vanilla/build/scripts/build.ts -i   2>&1
Installing node_modules with yarn.
Copying monaco editor to /dist
ℹ Compiling Admin-new
node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (core dumped)
The build failed with code 134
BUILD FAILED
/home/name/vanilla-release-2023.016/build/temp/vanilla/build/build.xml:25:47: Composer execution failed

Total time: 2 minutes  6.18 seconds


==================== Copying & Cleanup ====================
Build failed. Unable to locate built file at /home/name/vanilla-release-2023.016/build/temp/vanilla/build/vanilla.zip
Failed to build vanilla-2023.016.zip to:
 /home/name/vanilla-release-2023.016/build/releases/vanilla-2023.016.zip
```

**Expected behaviour**
To build without error

**Workaround**
use node version < 16

e.g. with `nvm use [version]` / `nvm alias default [version]` 

Then it will compile.

**Comment by juliecampbell** [comment]
Are there any updates on this? Our client's server is going to need to update to using Node 18 in the near future, and this is blocking us from doing so.
