### ISSUE TITLE
How to update from GitHub

### ISSUE THREAD

**Issue by luisgzafra** [vanilla/vanilla#11184]
Hello,

I am trying to update my Vanilla Forums from version 2023.016 to the latest release on GitHub.

I am replacing the old files with the new ones but it doesn't work.

How Can I do it?

Thanks.

**Comment by Vell61** [comment]
+1

**Comment by luisgzafra** [comment]
[Build release](https://open.vanillaforums.com/discussion/39452/vanilla-2024-001-open-source-release)
