### ISSUE TITLE
Allow users to delete their own post

### ISSUE THREAD

**Issue by HotBlack77** [vanilla/vanilla#1364]
See http://vanillaforums.org/discussion/comment/161632 for a discussion that lead to this submission

Currently it is possible to allow users to edit their own posts, but its is not possible to allow user to delete their own posts (permission can be given to allow a user to delete all posts in a category but that is not desirable).

The idea is simply to allow this behaviour; next to the button that allows a user to edit his post, add another button which allows them to simply delete it. Further, it would be useful if when a user with a specific permission views the discussion (e.g.an  admin)  they can see a place-holder for deleted posts which when clicked shows the deleted post and possibly allows the admin to reinstate it (and then prevents further deletion).

**Comment by atikmahbub** [comment]
efe
