### ISSUE TITLE
Moving discussion doesn't update "most recent post" for each category

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#1410]

**Comment by linc** [comment]
Fixed by #2202

**Comment by bleistivt** [comment]
Imo this part should be moved into its own method on the CategoryModel:

https://github.com/vanilla/vanilla/blob/fd6484796abd2af457ab0a62cbc463e1bd88886e/applications/vanilla/models/class.commentmodel.php#L906-L930

This could then be called when moving discussions.

**Comment by linc** [comment]
From briefly glancing at that, I'd agree.

**Comment by linc** [comment]
This is the dumbest bug ever.
