### ISSUE TITLE
Link parser breaks on non-ascii characters

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#1414]
Accented characters break the URL pattern matcher

http://vanillaforums.com/discussion/687

**Comment by bleistivt** [comment]
Just tried out the library. I also fails on that link:
``http://www.canalrcnmsn.com/noticias/la_dos_ví_del_tlc ``

The fix I suggested works and doesn't breaks the link callback like an external library would.

It requires regex unicode support though, so this is related:
https://github.com/vanilla/vanilla/issues/2017
