### ISSUE TITLE
'Edit Profile' Outputting Wrong Smarty {$User} Data

### ISSUE THREAD

**Issue by shadowdare** [vanilla/vanilla#1447]
If you visit another user's page (/profile/edit/4/example) and have permissions to do so, {$User} in Smarty is supposed to output the currently logged in user's data. Other pages such as notification preferences for a different user work normally as it should.

{$Profile} data works as it should with Smarty, but the {$User} data is being replaced with the data of the profile currently being edited, when instead it should show the current logged in user data.

**Comment by linc** [comment]
Probably related to #2194

**Comment by linc** [comment]
This appears to be fixed.
