### ISSUE TITLE
Pull : Add better styling to pre and code texts in ButtonBar (and MarkDown)

### ISSUE THREAD

**Issue by UnderDogg** [vanilla/vanilla#1526]
As seen here : **http://vanillaforums.org/discussion/22684/code-snippet#latest**

Code snippet:

For improving the < pre > and < code > tag styling for users using buttonbar. I have added this to our css, and I am happy with the look. You would need to add this code block to your custom.css file.

    code, pre {
    white-space: pre-wrap; /* css-3 */
    white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
    white-space: -pre-wrap; /* Opera 4-6 */
    white-space: -o-pre-wrap; /* Opera 7 */
    word-wrap: break-word;
    line-height:21px;
    }

I cannot add a pull request, so therefore this 'bug report'

**Comment by bleistivt** [comment]
Can be closed, pre and code tags are already styled:

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/design/style.css#L1995-L2012

I checked ButtonBars behaviour too, it is correct:
``<code></code>`` is added for inline code and ``<pre><code></code></pre>`` is added for multiline code blocks

**Comment by linc** [comment]
Thanks!
