### ISSUE TITLE
0-comment discussions incorrectly marked as read for guests

### ISSUE THREAD

**Issue by lifeisfoo** [vanilla/vanilla#1556]
Vanilla 2.1a38: If using "categories" as homepage and "mixed layout", when browsing as a guest some discussions in homepage are marked as read. This occur only when the discussion has "0 comments";When the discussion has at least 1 comment, it is marked as unread (as expected).
The bug is not present in example.com/discussions view.

Function flow:
class.categoriescontroller.php Index() (Line 78 - case "mixed")
class.categoriescontroller.php Discussions() (Line 296 - ```$this->CategoryDiscussionData[$Category->CategoryID] = $DiscussionModel->Get(0, $t\
his->DiscussionsPerCategory, array('d.CategoryID' => $Category->CategoryID, 'Announce' => 'all\
'));```)
class.discussionmodel.php Get (Line 359~ ```$this->AddDiscussionColumns($Data);```)
class.discussionmodel.php AddDiscussionsColumns()
class.discussionmodel.php Calculate():
```php
// cut....
//probably the bug is here
      if (!property_exists($Discussion, 'Read')) {
         $Discussion->Read = !(bool)$Discussion->CountUnreadComments;

         if ($Category && !is_null($Category['DateMarkedRead'])) {

            // If the category was marked explicitly read at some point, see if that applies h\
ere                                                                                            
            if ($Category['DateMarkedRead'] > $Discussion->DateLastComment)
               $Discussion->Read = TRUE;

            if ($Discussion->Read)
               $Discussion->CountUnreadComments = 0;
         }
      }

```

**Comment by bleistivt** [comment]
I can reproduce this:
![ss 2015-02-21 at 06 34 28](https://cloud.githubusercontent.com/assets/5205806/6315131/512cdaa0-b9f8-11e4-8d65-dc6dbf77a58f.png)
