### ISSUE TITLE
Enabling Plug-ins - The addon could not be enabled because it generated a fatal error:

### ISSUE THREAD

**Issue by bbsforum** [vanilla/vanilla#1561]
This just started since upgrading today to 2.1b1. Now the strange thing is after this error happens. If I still go back and click Enable a second time the plug-in will be enabled and work just fine. But no matter what plug-in I try this with (old, new, whatever) I am getting this error. I've literally gone down the line of plug-ins and it happens every time.

It shows a distorted look of the site (including messing up the sidebar of vanilla, screenshots attached) and scrolling down the page it says:

Page Not Found

   
The page you were looking for could not be found.

Here are the screenshots. This is what I have to scroll past to get to the list of plug-ins and then when I enable that second time, it works.

![bbsforum-plugin1](https://f.cloud.github.com/assets/4060004/339415/59c092d2-9d36-11e2-9ccb-994edf97fb08.jpg)

![bbsforum-plugin2](https://f.cloud.github.com/assets/4060004/339428/9291eec6-9d36-11e2-8137-b935061875e4.jpg)

**Comment by bleistivt** [comment]
The commit log suggests, that this was fixed in master, too (and still is)

**Comment by linc** [comment]
Thanks!
