### ISSUE TITLE
If profile don't have a photo use photo provided by UserPhotoDefaultUrl();

### ISSUE THREAD

**Issue by lifeisfoo** [vanilla/vanilla#1580]
But leave the text 'Add a Profile Picture' over the image.

In file application/dashboard/views/modules/userphoto.php.

**Comment by bleistivt** [comment]
The issue still exists.
Vanillicon/Gravatar awkwardly works around that:

https://github.com/vanilla/vanilla/blob/master/plugins/Gravatar/default.php#L19-L38

**Comment by linc** [comment]
What I'd really like to see here is pluggable avatar functionality in core that obsoletes the Vanillicon and Gravatar plugins. Avatar options should be:

* None (default)
* Vanillicons
* Gravatars
* Uploaded image (new feature)
* [plugin-generated methods]

I'm also fine with a solution that sets 'none' as the config default for existing installs and then we switch to a Vanillicon default in the following release.

**Comment by linc** [comment]
I'm guessing the best way of approaching this will be to put a new `UserPhotoDefaultUrl` in core that handles all these scenarios while maintaining backwards compatibility to current setups. Then the Gravatar & Vanillicon addons can get turned off with /utility/update.

Interested in @tburry's thoughts on this.

**Comment by bleistivt** [comment]
This was closed by #2936
