### ISSUE TITLE
Table Layout for Discussions are inconsistent

### ISSUE THREAD

**Issue by johansten** [vanilla/vanilla#1595]
Even if selected in the prefs, setting layout to "Table" isn't respected on all the places that shows discussions. 

I don't have my notes on exactly why this is the case, but I fixed this locally a while ago. What I did was to move layout selection away from the discussion controller (which isn't executed for all discussions), down to discussions/discussions.php (which actually IS executed for all discussions),

See here:
https://github.com/johansten/Garden/commit/643c8dbcbece3b026e24dddad357ed02496a5bd5

https://github.com/johansten/Garden/commit/6f495fbed76a726f705cfcdcceb230666fd4cdbb

This solution loses some of the css, but at least it renders Table layout where it should.

**Comment by bleistivt** [comment]
At this point I would suggest not changing this, at least not before the next release. It is inconsistent, but themers probably expect it to be the way it is.

**Comment by linc** [comment]
OK, removing milestone.
