### ISSUE TITLE
Profile Extender Bug in Vanilla 2.2

### ISSUE THREAD

**Issue by aery** [vanilla/vanilla#1611]
Environment: Local Host (WAMP)
Apache Version :
    2.2.22  
PHP Version :
    5.4.3  
MySQL Version :
    5.5.24  

And Vanilla 2.2

After activating supplied Profile extender plugin and adding a new field, it does not show up in old profiles (Probably because its empty). Though on editing profiles and after inserting value, it starts to show.

It must show even if its empty so that it can motivate user to update his details.

**Comment by linc** [comment]
The behavior of Profile Extender currently is to hide empty values by default to keep profiles clean.
