### ISSUE TITLE
Non integer time zones

### ISSUE THREAD

**Issue by amoschou** [vanilla/vanilla#1626]
GDN_User.HourOffset in the database has type INT. This results in some rounding error for some users, especially if the user lives in a non integer time zone like UTC+09:30, but indeed, theoretically, for any user if the server time and the local time differ by a non whole number of hours. It should allow decimal values to work in the general case. Original description at http://vanillaforums.org/discussion/24166/non-integer-time-zones.

**Comment by linc** [comment]
We don't currently plan to implement this. I'd accept a pull request for it.

**Comment by mtschirs** [comment]
Wouldn't it be useful to keep this issue open as an enhancement? This keeps it visible for possible contributors and prevents this issue from being raised again in the future.

**Comment by linc** [comment]
I feel the cognitive load of needing to re-scrub a bug every time I go thru the backlog outweighs the benefit of it being "noted" for the future. If it is really important, we'll hear about it again one day. In the meantime, their is real benefit to maintaining a tight, vetted issue list.
