### ISSUE TITLE
Error on updating category

### ISSUE THREAD

**Issue by aolee** [vanilla/vanilla#1630]
Hi,

I'm using Vanila 2.2.

Just want to report that im having problem updating my category, i noticed that if the checkbox 

"This category is archived." or 

"Hide from the recent discussions page."

is unchecked the value for these two during update are "" , please see attached error. but if checked everything saves.
![screen shot 2013-07-15 at 10 59 47 pm](https://f.cloud.github.com/assets/700718/798411/24430066-ed60-11e2-8167-a0794664dc90.png)
![Uploading Screen Shot 2013-07-15 at 10.59.26 PM.png . . .]()

**Comment by linc** [comment]
This is a MySQL strict mode error that I believe was fixed generally.
