### ISSUE TITLE
Mixing up Controller for events BeforeCommentRender, etc on Comment Post

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#1633]
in 2.1 if want to target the `BeforeCommentRender` form from a comment submission, that request is dispatched to the `PostController`, however the view is from the `DiscussionController` set. 

All fine so good. 

The `BeforeCommentRender` requires you to hook the DiscussionController event. Well you might say this is fair enough becuase you are using the `DiscussionController` view, however this event doesn't physically exist in the `DiscussionController` for one and it is not in a view it is in the `PostController`, and it is actually the `PostController` that fires the event. 

This follows through on later events, and from views that are not technically rendered from the discussion controller in this case, even if they are discussion controller views.

Maybe these views should be DiscussionController referenced, but I line has to be drawn somewhere.

This is a bit of a confusing compatibility issue. 

The difference between 2.0 and 2.1 in this case essentially is:

`$this->ClassName = 'DiscussionController';`

You can set the `$this->ControllerName = 'discussion';` without issue, however the hook uses the `ClassName`. 

My personal opinion is you should stick to what was actually dispatched, regardless of where the view is from, unless of of course you want a proxy design pattern, which is a bit late in the day to switch. 

It kind of calls into question how these 'cross' views are referenced, although I admit to being a hypocrite for some times. Perhaps the more explicit rather than implicit method is called for.  

I'm guessing you changed this to get something working, as this is the only controller location I found the 'ClassName' set for this ends.

**Comment by linc** [comment]
Can you suggest a code fix for this? I follow the general problem but don't see a clear path forward to "fix" this.
