### ISSUE TITLE
Mentioning usernames with characters like like ä, ö, ü, ñ breaks

### ISSUE THREAD

**Issue by UnderDogg** [vanilla/vanilla#1651]
**From:**
http://vanillaforums.org/discussion/15263/user-doesn-t-always-work

**Phreak:**
I think this very important as linkings are now broken if @usern**ä**me is written for example. The text only link is "@usern" while "äme" is treated like standard text. As username registration with these character is possible it would be great.

**Lincoln:**
I believe this was fixed for 2.1 if you have the proper regex libraries (most modern PHP installs do).
I made this patch to the URL matcher, not mentions. It should get a bug 
ticket.

**Comment by linc** [comment]
https://github.com/vanilla/vanilla/pull/2501
