### ISSUE TITLE
[INF] Prevent Forum Administrator from Receiving Duplicate Welcome Stub Message

### ISSUE THREAD

**Issue by cuthbeorht** [vanilla/vanilla#1691]
The stub content currently uses DiscussionModel->GetCount to determine whether to add stub content when an update is triggered. If a forum has discussions, it shouldn't fire. However, a forum set to Private Community (zero guest access) will get a count of zero because GetCount respects permissions. Therefore a Private Community will always get the stub content on every update.

Reference: vf 2822

**Comment by linc** [comment]
#2400
