### ISSUE TITLE
Small error in Gdn_Auth leading to annoying bugs when trying to make auth plugins work...

### ISSUE THREAD

**Issue by zedrdave** [vanilla/vanilla#1715]
Gdn_Auth::AssociateUser() does weird things with its $Success variable:

when doing an insert, it just ignores the value returned. 

when doing a replace, it uses the value returned by Replace(). Except as best as I can see, the Replace() function doesn't have a return value, meaning it always gets set to false...

In effect, $Success always returns true when $UserID > 0, and false otherwise... Which is most likely not the expected behaviour (took me a few hours figuring out why my auth plugin was failing).

**Comment by linc** [comment]
We'd accept a pull request to correct this, but have no other plans to address it.
