### ISSUE TITLE
Timezone issue for logged in users

### ISSUE THREAD

**Issue by aolee** [vanilla/vanilla#1745]
Hi, I notice there's a difference the way timezones are being saved in the GDN_User HourOffset column for vanilla 2.0.18 and 2.1b2.

I had encounter an issue after migrating the data from 2.0.18.6 to 2.1b. this timezone issue happens after user successfully signs in.

Scenario: 

My server is set to Asia/Singapore (same in PHP.ini and i forced the bootstrap.php to use Asia/Singapore) 

in 2.0.18 HourOffset are being saved as 0,

while in 2.1b, HourOffset is saved as 8 (which is the timezone my pc is set)

The problem i noticed now is all my discussions/comments are 8hrs ahead. 

I did managed to trace and fixed the issue but don't know if this is a full proof solution.
(line 482 to 486 on the screenshot for file class.format.php)

![screen shot 2013-11-26 at 2 14 35 am](https://f.cloud.github.com/assets/700718/1615767/62e61a3a-55ff-11e3-95a9-4f6dffd5d5bd.png)

Please let me know if you need more info.

**Comment by linc** [comment]
This was indeed a change in how we handled timezones when moving from 2.0.18 to 2.1 where we forced UTC rather than letting the server set it.

**Comment by bleistivt** [comment]
Now that UTC is forced and Vanilla 2.0 is out of support, can this be closed?
