### ISSUE TITLE
Disable plugin fails when folder does not match case of Plugin Name in array

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#1750]
in library/core/pluginmanager.php

change around line 1035 in vanilla 2.1b2

from

  // 2. Perform necessary hook action
      $this->_PluginHook($PluginName, self::ACTION_DISABLE, TRUE);

to

   
       $RealRoot = GetValue('RealRoot', $Plugin);
       $PluginName = preg_replace('/.*plugins\//', '', $RealRoot); 
      // 2. Perform necessary hook action
      $this->_PluginHook($PluginName, self::ACTION_DISABLE, TRUE);

this will retrieve the actual folder and set the config correctly and disable the plugin.

unfortunately my connection is to slow to use github pull push, etc.

**Comment by bleistivt** [comment]
The documentation now says:
> The array key (FancyPlugin above) must exactly match the folder name, including capitalization.
http://docs.vanillaforums.com/developers/plugins/quickstart/

So I wouldn't allow this - a wrong folder name voids your warranty.
