### ISSUE TITLE
2.1b2 - First message in new conversations don't send email notification

### ISSUE THREAD

**Issue by miksansegundo** [vanilla/vanilla#1758]
In a fresh install of 2.1b2 when I create a new conversation with a new message there isn't a notification by email only in first message. The bug is only in the first message and in email notification.

By default is checked this setting in Notification Preferences. 

Is it a real bug or I miss something?

Thanks!

**Comment by davidemms** [comment]
Hi does this mean it should be fixed for all repositories on github? I'm currently experiencing this problem. When an issue is first logged for a repository I own I don't get a notification, I only get them if there are subsequent comments in the thread. I just wanted to check if the above fix has been rolled out.

Thanks
David

**Comment by linc** [comment]
You're commenting on an issue for Vanilla Forums software, not GitHub.

**Comment by davidemms** [comment]
Doh! Thanks.
