### ISSUE TITLE
/categories/all shows LastDiscussionTitle only for discussions with 2+ comments

### ISSUE THREAD

**Issue by hughtopping** [vanilla/vanilla#1771]
Expected
--------------

The LastDiscussionTitle span should show the latest discussion for the category on the /categories/all page at all times.

Actual
----------

The LastDiscussionTitle span is only shown for discussions with more than 2 comments. Therefore, when a discussion is first posted, the LastDiscussionTitle will not be shown until the discussion receives an additional comment.

Repro steps
-------------------

1. Have an empty category.
2. Create a new discussion in that category.
3. Go to the /categories/all page. Note that the LastDiscussionTitle span is not generated.
4. Go back to the discussion and add a comment to the same discussion.
5. Return to the /categories/all page. Note that the LastDiscussionTitle span is now displayed.

**Comment by initvector** [comment]
I am unable to reproduce this issue.  Can you confirm this is still a problem in the latest version of the master branch?
