### ISSUE TITLE
Missing Activity Log: "[user] changed his profile picture"

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#1774]
this bug was found by aolee.

and here is the discussion with my suggested solution.  you might have a better solution.

http://vanillaforums.org/discussion/25924/missing-activity-log-user-changed-his-profile-picture

problem is with the current code $OldPhoto will actually always be equal to $Photo because the check is made too late. Therefore an activity record will never be written.

Yes I believe you found a bug in

/applications/dashboard/models/usermodel.php

to make it add to activity and check photo correctly...
you could change the code form

    $this->SQL->Put($this->Name, $Fields, array($this->PrimaryKey => $UserID));
    // Record activity if the person changed his/her photo.
    $Photo = ArrayValue('Photo', $FormPostValues);
    if ($Photo !== FALSE) {
    if (GetValue('CheckExisting', $Settings)) {
    $User = $this->GetID($UserID);
    $OldPhoto = GetValue('Photo', $User);
    }
    to
    if (GetValue('CheckExisting', $Settings)) {
    $OldPhoto = GetValue('Photo', $User);
    }
    $this->SQL->Put($this->Name, $Fields, array($this->PrimaryKey => $UserID));
    // Record activity if the person changed his/her photo.
    $Photo = ArrayValue('Photo', $FormPostValues);
    if ($Photo !== FALSE) {
    if (GetValue('CheckExisting', $Settings)) {
    $User = $this->GetID($UserID);
    // $OldPhoto = GetValue('Photo', $User);
    }

**Comment by linc** [comment]
I'd actually like to remove this activity type entirely.
