### ISSUE TITLE
RSS feed does not include announcements

### ISSUE THREAD

**Issue by kwill** [vanilla/vanilla#1775]
Steps to reproduce:

 * Visit any category with announcements (for example, http://vanillaforums.org/categories/blog/ )
 * Confirm date of announcement (in this case, http://vanillaforums.org/discussion/25668/dec-2013-security-update-2-0-18-10-and-2-1b2 )
 * Visit feed for that category ( http://vanillaforums.org/categories/blog/feed.rss )

What should happen:

 * Announcement post appears in RSS feed in chronological order
 * (Extra) If post is edited, should it appear in feed only once, but at new date?

What happens instead:

 * Post does not appear

Also reported here: http://vanillaforums.org/discussion/19751/announcements-don-t-get-picked-up-by-the-rss-feed

**Comment by bleistivt** [comment]
I just needed this myself and wrote a plugin that solves this by merging the data:
```php
public function categoriesController_render_before($sender) {
    if ($sender->SyndicationMethod !== SYNDICATION_NONE && Gdn_Theme::inSection('DiscussionList')) {
        $rssData = array_merge(
            $sender->AnnounceData->resultArray(),
            $sender->DiscussionData->resultArray()
        );
        $sender->DiscussionData->importDataset($rssData);
        $sender->DiscussionData->datasetType(DATASET_TYPE_OBJECT);
    }
}
```
A little too hacky to put in the core imo, but no views would need to be changed.
