### ISSUE TITLE
Popin links issue

### ISSUE THREAD

**Issue by markconde** [vanilla/vanilla#1785]
Popins not loading if Vanilla is installed in a subdirectory and Me module is loaded in another application (not vanilla) and on a different theme

![Popin not loaded](https://f.cloud.github.com/assets/5916819/2156758/62e4b302-9466-11e3-9721-4475bb5e44a4.png)
![Error shown on screen](https://f.cloud.github.com/assets/5916819/2156759/63362cf0-9466-11e3-88d2-be9bf565bd70.png)

The fix is to edit the view for the Me module and use Gdn_Theme::Link to format it properly. It happens for the first 3 icons

**Comment by linc** [comment]
Pretty confident this got fixed.
