### ISSUE TITLE
When connecting FB or Twitter to profiles Error returns stating SSL needed

### ISSUE THREAD

**Issue by pixelnated** [vanilla/vanilla#1889]
Vanilla Version: 2.1
Where: Home › Profile › Social
Task: Connecting either Facebook or Twitter to a profile. When being returned to forums the following error is given for each:

Whoops!
SSL is required

**Comment by linc** [comment]
It isn't possible to do a secure SSO connection without SSL being enabled. This is (correctly) required by the services, so we have no control over this.
