### ISSUE TITLE
Google Sign In: deprecating OpenID 2.0 for Oauth2 (Google+)

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#1891]
https://developers.google.com/accounts/docs/OpenID

We gotta move over; it'll make the addon experience better anyway because we can put it under Social and get rid of the 2-step addon enable/dependency.

**Comment by TiGR** [comment]
@tburry your plugin link is broken.

Google Sing In (openid) is no longer working. Google+ plugin is not working on vanilla 2.1.10 (call to undefined function SocialSignInButton). Is there any working plugin that utilizes google+ sign in?

**Comment by linc** [comment]
GooglePlus is in for 2.2.
