### ISSUE TITLE
Increment in DiscussionsModel (issue with ActiveEnabled)

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#1899]
for me this is true:
Gdn::Cache()->ActiveEnabled())

but  if

Vanilla.Views.Denormalize is set to TRUE in your config.php

IncrementBy will always be 0.

because

$Views % $WritebackLimit is always equal to 1

if (C('Vanilla.Views.Denormalize', FALSE) && Gdn::Cache()->ActiveEnabled()) {

evaluates to TRUE

then

$Views = Gdn::Cache()->Increment($CacheKey);

viewis always evaluates to 1

if (($Views % $WritebackLimit) == 0) {

always evaluates to 1

and $IncrementBy never gets set and is always 0

and incrementBy is never set to 1 because it can't be reached unless Vanilla.Views.Denormalize is FALSE or Gdn::Cache()->ActiveEnabled() is false.

never set here: $IncrementBy = 1;

therefore the database never updates.

**Comment by linc** [comment]
This was fixed by adding a check for `Gdn::cache()->type() != Gdn_Cache::CACHE_TYPE_NULL`.
