### ISSUE TITLE
Thread page shows blank forum

### ISSUE THREAD

**Issue by CephNightmare** [vanilla/vanilla#1916]
My problem occured after dragging the vanilla files onto my domain. I succesfully used the setup that Vanilla prompts you with and everything seemed to run smoothly.

Unfortunately, i wanted to view the first thread that Vanilla made, but i was linked to a blank page. Did anyone else have a similar problem?

the main page: http://66943.glr-imd.nl/forum/
the blank page: http://66943.glr-imd.nl/forum/discussion/1/bam-you-ve-got-a-sweet-forum#latest

**Comment by linc** [comment]
I suggest pursuing this sort of issue via the [community forum](http://vanillaforums.org/discussions) since this is likely an error in your server config, not the software.
