### ISSUE TITLE
Untranslatable text in dashboards view banner.php

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#1936]
In the file /applications/dashboard/views/settings/banner.php "FaviconDescription" is used twice as translation code and so one text is untranslatable:

https://github.com/vanilla/vanilla/blob/2.1/applications/dashboard/views/settings/banner.php#L119
https://github.com/vanilla/vanilla/blob/2.1/applications/dashboard/views/settings/banner.php#L137

**Comment by Tama63** [comment]
Looks like this has been fixed on `master`

**Comment by linc** [comment]
Thanks!
