### ISSUE TITLE
view counter will not increment if magic quotes is off

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#1938]
this could be a trapped error if magic quotes is off.

 Gdn_Statistics_Tick_Handler in /applications/vanilla/settings/classhooks.php

 in the 

public function Gdn_Statistics_Tick_Handler($Sender, $Args) {
$Path = Gdn::Request()->Post('Path');
$Args = Gdn::Request()->Post('Args');
parse_str($Args, $Args);
$ResolvedPath = trim(Gdn::Request()->Post('ResolvedPath'), '/');
$ResolvedArgs = json_decode(Gdn::Request()->Post('ResolvedArgs'));

or do a preg_replace on ResolvedArgs to remove "\" that causes DiscussionID to be null when it actually has an escaped valid DiscussionID

or put this explicitly in installation instructions "magic quotes should be on for vanilla to function properly"

see
http://vanillaforums.org/discussion/comment/208288/#Comment_208288
http://vanillaforums.org/discussion/comment/208291/#Comment_208291

**Comment by linc** [comment]
We just nuked all magic quote refs.
