### ISSUE TITLE
When using Connect registration method, users prompted for user/password when doing an action that requires log-in

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#1940]
Vanilla 2.1
jsConnect 1.4.1

I use the Connect registration method along with jsConnect. It's my intention that all users are created and logged in through the remote site; there is no one that is forum-only. The sign-in UI on my main page does as I intend - I get "Register" and  "Sign in with" buttons pointing to the remote site.

The problem is that when a non-signed in user attempts an action that requires sign-in (e.g. create a new discussion), they get sent to /entry/signin?Target=post%2Fdiscussion which includes a user name and password field as well as jsConnect's "Register" and  "Sign in with" buttons. This page should only have jsConnect's buttons; it should not include the user name and password fields.

**Comment by linc** [comment]
Did you designate the jsConnect connection as 'Default'? That should forcibly redirect the `/entry/signin` endpoint to yours.

**Comment by JasonBarnabe** [comment]
No, it's not default. See https://github.com/vanilla/addons/issues/92.

**Comment by JasonBarnabe** [comment]
With the connection set as default, this works in master. In 2.1, you get to a Vanilla sign-in page with email and password, and a section that says "Or you can..." with nothing under it.
