### ISSUE TITLE
ActivityComment (not wall post) not notified.

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#1941]
Not to be confused with this
https://github.com/vanilla/vanilla/issues/1663

It appears that comments on activity items (nested), rather than wall post, aren't notified. 

This illustrates what works or not:
![](https://dl.dropboxusercontent.com/u/15933183/notifications.png)

it is a bit confusing  but certainly I can't find any architecture that does anything with 

`ActivityComment` notifications. `WallPost` yes.

This whole section 

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.activitymodel.php#L891-L942

has nothing that would notify, neither does the controller. 

There is also reference to `GetValue('Bump', $Activity['Data'])`, but no reference to where it is set.

**Comment by linc** [comment]
We fixed this.
