### ISSUE TITLE
Autoloader problems - Class 'Gdn' not found

### ISSUE THREAD

**Issue by acedude** [vanilla/vanilla#1953]
Looks like clear install of Vanilla (master branch zipball) on fresh vagrant box (PHP 5.4, Apache, Debian) has some problems with autoloading. Here's the error:

```
Fatal error: Class 'Gdn' not found in /var/www/library/core/functions.general.php on line 464
```

I tried multiple configurations (Windows, Ubuntu, PHP 5.5) without success.

Here's the error after using 2.1 relase:

```
Fatal error: Class 'Gdn_Url' not found in /var/www/library/core/functions.general.php on line 271 
```

And finally, the same guy in relase 2.0.18.11:

```
Fatal error: Class 'Gdn_Url' not found in /var/www/library/core/functions.general.php on line 335
```

**Comment by adrianspeyer** [comment]
I am running into this issue when I use the changes from https://github.com/vanilla/vanilla/commit/94422e1d737b2fea041aa5904df306f60b8d782d#diff-1ac972e79b4b41917a7c6fa8e2d5cd59
