### ISSUE TITLE
Change log only for moderator-powered actions

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#1961]
Related to the discussion in #972.

On the dashboard, there's Moderation - Change Log. This says it's every edit or delete. I personally find this kind of useless... What do I care if someone edited their post?

What I would like to see is a log of actions that moderators are taking using powers above those that normal users have. I'd even like to make this log visible to regular users, in the interests of transparency.

**Comment by linc** [comment]
We're reworking the moderation log soon.
