### ISSUE TITLE
When a flagged item is deleted, the flag should be dismissed

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#1970]
Usually, I will notice spam in the discussion list and delete it before I check the flagged item list. If a user flagged a discussion I deleted, the flag sticks around, and then I have to dismiss each flag. It's especially annoying when I delete a user who posted lots of spam, then have to dismiss a bunch of stuff.

When a flagged item is deleted, the flag should be dismissed as well.

**Comment by linc** [comment]
I'd accept this as a pull request, but it's not a defect nor roadmapped.
