### ISSUE TITLE
Hiding and showing Preview/Edit buttons with class only

### ISSUE THREAD

**Issue by lumio** [vanilla/vanilla#1973]
Hello, I just found a nice-to-have thing when adding a new comment to a thread.

##### Current state
When adding a comment, we have several buttons under the textarea, including `Preview`, `Edit` (which is hidden by default), `Save Draft` and `Post Comment`.

When clicking on `Preview` that button disappears and `Edit` appears.

Now instead of removing the `Hidden`-class on the `Edit` button, `display: inline` is given directly to the DOM element. (probably by just doing `$.hide()` and `$.show()`)

That has one major disadvantage: There is not a clean way to have a different display property beside `inline`.

##### A maybe cleaner way to hide and display elements
Now my request is to use `$.addClass('Hidden')` and `$.removeClass('Hidden')` instead of using `$.hide()` and `$.show()`. That allows theme designers to add more specific styles to those buttons.

This behaviour could probably be used instead of all `.hide()` and `.show()` calls throughout the page.

What do you think?
Thank you for reading! Keep up the good work!

**Comment by bleistivt** [comment]
This was implemented in #2132
