### ISSUE TITLE
DateSetInvitations always 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by Democide** [vanilla/vanilla#1981]
I am having an issue with my board on Vanilla 2.1 and the invitation system.

Invitations don't regenerate and the DateSetInvitations is always 0. I presume these two are related.

More information is here: 

http://vanillaforums.org/discussion/26996/some-users-don-t-have-the-invite-text-field-on-2-1/p2

**Comment by linc** [comment]
I believe we fixed null handling in 2.2. I'm no longer able to find any evidence of this happening presently.
