### ISSUE TITLE
Embedding assumes HTTP and thus fails for HTTPS

### ISSUE THREAD

**Issue by jarrett** [vanilla/vanilla#1982]
embed.js (remote.js in the embed plugin) has `http://` hard-coded in a number of strings. Thus, if you embed the forum on an HTTPS page, the HTTPS page will refuse to display the forum. It should support HTTPS, either via autodetection if possible, or else via a config option.

**Comment by linc** [comment]
"embedvanilla" is no longer used because this feature is in core and does support https.
