### ISSUE TITLE
Chrome Console Javascript Error: Embed.js:280

### ISSUE THREAD

**Issue by Xarcell** [vanilla/vanilla#1993]
Vanilla 2.1 Stable

Javascript error in Chrome console when you embed the forum:

"Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.  - embed.js:280"

**Comment by linc** [comment]
I've never seen this error. I'd need a working example of how to reproduce this reliably to look into it. I suggest starting on vanillaforums.org/discussions

**Comment by Xarcell** [comment]
Well I haven't looked at this issue in over a year. Couldn't tell you much about it at this point in time.
