### ISSUE TITLE
Version check / upgrade prompt in core

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2018]
Administrators should see an upgrade prompt when a security release for their current branch is released. Preferably a separate notice for when the next dot upgrade is ready too.

**Comment by bleistivt** [comment]
Is there a public API to check for the latest release?

The only thing I can think of is:
https://open.vanillaforums.com/addon/vanilla-core.json

**Comment by linc** [comment]
That endpoint would probably work. I'd consider making a new, dedicated endpoint in the `community` repo for this, since we'd be pouring quite a bit of concrete around it to start having thousands of sites calling in to it forever.
