### ISSUE TITLE
Vanilla 2.1.1 "Something has gone wrong." [FIXED]

### ISSUE THREAD

**Issue by kostyakoz** [vanilla/vanilla#2020]
**UPD:** I've fixed it. Just set permissions 777 for `/cache/Smarty/compile`.

Hi guys, I have `PHP 5.4.16 (FPM)` + `Nginx` + `MariaDB` (mysql). After Vanilla installation I have it error on homepage:

![2014-08-06 18 42 11](https://cloud.githubusercontent.com/assets/1935229/3828456/ddc31524-1d77-11e4-8a6f-9a7ef9ab42e3.png)

Dashboards works fine:

![2014-08-06 18 43 29](https://cloud.githubusercontent.com/assets/1935229/3828487/0eca0466-1d78-11e4-84cb-10cfe183d644.png)

**Comment by HarinduJayakody** [comment]
Thanks :) This was so helpful for me..

**Comment by Liiijabn** [comment]
Thank you so much! That was helpful!
