### ISSUE TITLE
Nested categories with display as categories.

### ISSUE THREAD

**Issue by John0x00** [vanilla/vanilla#2029]
Steps to reproduce:

Setup some nested categories:

![Category Setup](https://www.evernote.com/shard/s30/sh/1d2bebc9-8bf5-4f96-87d5-41d42349f5c3/95b3683893a4f7fe5c8b73c1a58526a6/deep/0/Categories---Vanilla-2.png)

Set the top level of the nesting to be displayed as categories.

![Category Setup 2](https://www.evernote.com/shard/s30/sh/9f3ce432-e5da-4148-8fae-b69182e1bd77/27f758d1c5384f1561772d623dc7d99b/deep/0/Edit-Category---Vanilla-2.png)

Now when viewing /categories/general we now see:

![Category View](https://www.evernote.com/shard/s30/sh/ef88d989-d63d-4d68-a053-9365f1ec6426/9a47a1a4a7a3110e621fc1577171757e/deep/0/General---Vanilla-2.png)

This view should show the selected category 'general' at the top and should have the description for the category.

**Comment by linc** [comment]
@tburry was this resolved?

**Comment by linc** [comment]
This was fixed.
