### ISSUE TITLE
Activity input field is a TextBox instead of BodyBox

### ISSUE THREAD

**Issue by Acccent** [vanilla/vanilla#2059]
Hi,

The input field in the activity page is a TextBox (see line 13 of dashboard/views/activity/all.php: `echo Wrap($this->Form->TextBox('Comment', array('MultiLine' => TRUE)), 'div', array('class' => 'TextBoxWrapper clearfix'));` ) instead of a BodyBox.

As a result some plugins (for instance, mediumeditor) fail to attach themselves to it. Posting an activity update from a profile page does use a BodyBox, so I don't see why it shouldn't be the same for the activity page.

This is resolved by changing the previously mentioned line to this: `echo Wrap($this->Form->BodyBox('Comment'), 'div', array('class' => 'TextBoxWrapper clearfix'));`.
Note: comments on activities use a TextBox as well, but that seems more logical.

**Comment by bleistivt** [comment]
this has been fixed #3214

**Comment by hgtonight** [comment]
Confirmed this is fixed in master and release/2.3 but not in release/2.2
