### ISSUE TITLE
Bug with OAuth if host has the PHP OAuth extension installed

### ISSUE THREAD

**Issue by Acccent** [vanilla/vanilla#2061]
Hi,

When a forum's host already has the OAuth extension installed on their server, it conflicts with the file library/vendors/oauth/OAuth.php, which attempts to define a new 'OAuthException' class.

This notably breaks Twitter Social Connect: it can't be enabled from the admin dashboard, and if the value is manually added to config.php, the whole website can stop functioning.

One possible way to fix this is to wrap the OAuthException class definition in OAuth.php with `if(!class_exists('OAuthException'))`, or to simply comment it out.

Cheers!

**Comment by Acccent** [comment]
Issue is back in latest update.

**Comment by bleistivt** [comment]
Are you referring to 2.1.8p2? Because it was never fixed there.

But it's still in master:
https://github.com/bleistivt/vanilla/blob/master/library/vendors/oauth/OAuth.php

**Comment by linc** [comment]
I am content to let this wait for the next version, I think. I'm hoping 2.1.9 will be the end of the line anyway.

**Comment by Acccent** [comment]
Ah, okay. It's just that I made the update and encountered the problem again, so I was confused. :)

**Comment by jfarthing84** [comment]
How did this not make it into 2.1.11?
