### ISSUE TITLE
2.1: Profile Extender forms not pre-populated

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2080]
See: http://vanillaforums.org/discussion/27874/profile-extender-fields-blank-when-editing-profile

https://github.com/vanilla/vanilla/blob/2.1/plugins/ProfileExtender/class.profileextender.plugin.php#L229

$Sender->Data('User') is empty because it is only set in ProfileController->Edit as of 2.2

**Comment by linc** [comment]
I think I am going to close this since it will naturally close with the next release and I haven't gotten a PR for this.

**Comment by alexcroox** [comment]
Was this fixed? Still seeing it in 2.1.9
