### ISSUE TITLE
Probable issue with discussion sorting via config statements.

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2083]
in discussions model ....
https://github.com/vanilla/vanilla/blob/2.1/applications/vanilla/models/class.discussionmodel.php#L282
see. ....
getwhere has no concept of

$this->EventArguments['SortField'] = C('Vanilla.Discussions.SortField', 'd.DateLastComment');
$this->EventArguments['SortDirection'] = C('Vanilla.Discussions.SortDirection', 'desc');

 public function GetWhere($Where = array(), $Offset = 0, $Limit = FALSE) {
if (!$Limit)
$Limit = C('Vanilla.Discussions.PerPage', 30);
if (!is_array($Where))
$Where = array();
$Sql = $this->SQL;
// Build up the base query. Self-join for optimization.
$Sql->Select('d2.*')
->From('Discussion d')
->Join('Discussion d2', 'd.DiscussionID = d2.DiscussionID')
->OrderBy('d.DateLastComment', 'desc')
->Limit($Limit, $Offset);

http://vanillaforums.org/discussion/comment/215320/#Comment_215320

controller calls different method.
http://vanillaforums.org/discussion/comment/215321/#Comment_215321

**Comment by bleistivt** [comment]
this is fixed in master
