### ISSUE TITLE
CSS Naming Consistency

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2096]
To my understanding panel modules do have  
a) the class "**Box**"
b) an additional class "**BoxModulename**"/"**ModulenameBox**" or something similar

I've seen that following modules  
a) do **not have** a class "**Box**"
 - \applications\dashboard\views\modules\me.php
 - \applications\dashboard\views\modules\userbox.php  

b) do **not have** a class "**Box**" **but** a class "**BoxFilter**"
 - \applications\vanilla\views\modules\discussionfilter.php
 - \applications\dashboard\views\modules\activityfilter.php
 - \applications\dashboard\views\modules\profilefilter.php  

c) do **not have** a class "**Box**" **but** a class "**BoxButtons**"
 - \applications\vanilla\views\modules\newdiscussion.php

I would suggest to add the "Box" class to this modules.
<hr />

And simply for consistency, I would suggest following changes:
(module, as is, proposal)

\applications\dashboard\views\modules\recentactivity.php
`<div id="RecentActivity" class="Box">`
.Box .BoxRecentActivity

\applications\vanilla\views\modules\categorymoderators.php:
`<div class="Box Moderators">`
.Box .BoxCategoryModerators

\applications\dashboard\views\modules\guest.php:
`<div class="Box GuestBox">`
.Box .BoxGuest

\applications\dashboard\views\modules\me.php:
`echo '<div class="MeBox'.$CssClass.'">';`
.Box .BoxMe

\applications\dashboard\views\modules\me.php:
`echo '<div class="MeBox MeBox-SignIn'.$CssClass.'">';`
.Box .BoxMe .BoxMe-SignIn

\applications\dashboard\views\modules\signedin.php:
`<div class="Box ProfileBox">`
.Box .BoxSignedIn

\applications\dashboard\views\modules\userbox.php:
`echo '<div class="UserBox">';`
.Box .BoxUserBox

\applications\vanilla\views\modules\promotedcontent.php:
`<div class="Box BoxPromoted">`
.Box .BoxPromotedContent

\applications\dashboard\views\modules\recentuser.php:
`<div class="Box RecentUsers">`
.Box .BoxRecentUser (renaming the module to recentuser**s**.php would make sense to me, too)

\applications\dashboard\views\modules\sidemenu.php:
`echo '<div class="Box Group '.GetValue('class', $Item['Attributes']).'">';`
.Box .BoxSideMenu

I would expect that the only major problem would be the MeBox because that one is styled individually in some themes, while the rest is not as popular.

**Comment by linc** [comment]
This is gonna require a PR to move forward.
