### ISSUE TITLE
No CSS for tables in user posts

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#2139]
Users can post tables in the messages using HTML and Markdown. The default theme includes "Reset CSS" which makes the tables dumb-looking. This is a two column, two row table:

![table](https://cloud.githubusercontent.com/assets/583995/4445282/1aa1ff78-47f8-11e4-9deb-fb4938fcdd98.png)

Remove Reset CSS or include a reasonable style for tables in posts.

**Comment by linc** [comment]
Reset CSS involves a lot more than just the UGC area, so adding some _very_ basic styling here would be appropriate.
