### ISSUE TITLE
links to documentation in vanilla code that you might want to update

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2152]
applications/dashboard/views/statistics/index.php:19:   echo '<li>', Anchor(T('StatisticsDocumentation'), 'http://vanillaforums.org/docs/vanillastatistics'), '</li>';

applications/dashboard/views/statistics/index.php:29:   <?php echo T("The Vanilla Statistics plugin turns your forum's dashboard into an analytics reporting tool", "Vanilla Statistics turns your forum's dashboard into an analytics reporting tool, allowing you to review activity on your forum over specific time periods. You can <a href=\"http://vanillaforums.org/docs/vanillastatistics\">read more about Vanilla Statistics</a> in our documentation."); ?>

applications/dashboard/views/settings/homepage.php:47:   echo Wrap(Anchor(T("ConfiguringVanilla's Homepage"), 'http://vanillaforums.org/docs/homepage'), 'li');

applications/dashboard/views/settings/locales.php:8:   echo '<li>', Anchor(T('Enabling a Locale Pack'), 'http://vanillaforums.org/docs/Localization#Enabling'), '</li>';

applications/dashboard/views/settings/locales.php:9:   echo '<li>', Anchor(T('Internationalization & Localization'), 'http://vanillaforums.org/docs/Localization'), '</li>';

applications/vanilla/views/settings/managecategories.php:17:   echo Wrap(Anchor(T('Managing Categories'), 'http://vanillaforums.org/docs/managecategories'), 'li');

applications/vanilla/views/settings/managecategories.php:18:   echo Wrap(Anchor(T('Adding & Editing Categories'), 'http://vanillaforums.org/
docs/managecategories#add'), 'li');

applications/vanilla/settings/class.hooks.php:9: * @link http://vanillaforums.org/docs/PluginQuickStart

library/core/class.statistics.php:626:               $Warning .= T('Your config.php file is not writable.<br/> Find out <a href="http://vanillaforums.org/docs/vanillastatistics">how to fix this &raquo;</a>');
plugins/VanillaStats/views/dashboardlocalhost.php:7:   echo '<li>', Anchor(T('Using Vanilla Stats on localhost'), 'http://vanillaforums.org/docs/VanillaStatistics#localhost'), '</li>';

assuming your docs are now: docs.vanillaforums.com

since you seemed to say http://vanillaforums.org/docs  is no longer updated.

**Comment by linc** [comment]
@adrianspeyer

**Comment by adrianspeyer** [comment]
@linc most were done, and here are the last three that fixes the rest
https://github.com/vanilla/vanilla/pull/2500
https://github.com/vanilla/vanilla/pull/2499
https://github.com/vanilla/vanilla/pull/2498
