### ISSUE TITLE
"Conversation" link no CSS/circular href

### ISSUE THREAD

**Issue by tuoni** [vanilla/vanilla#2157]
In pop-up notifications, click the "conversation" link
![1](https://cloud.githubusercontent.com/assets/1938113/4533395/93804b22-4d9b-11e4-86ba-d76ea33ba90c.png)

You're met with an un-CSS'd page in the parent, thusly:
![1](https://cloud.githubusercontent.com/assets/1938113/4533426/d7ccfc9e-4d9b-11e4-8e40-bac9fd72a09d.png)

Also, if you click on the same "conversation" link in your /profile/notifications, it links to /profile/notifications

**Comment by agcyphers** [comment]
I'm facing the same issue with 2.1.8.  I added a user to a conversation, and their email contained a link to "/profile/notificationspopin?DeliveryType=VIEW".  The link in their popin when they visit the site and click the button to view their notifications also takes them to this page.

**Comment by linc** [comment]
From these descriptions, I suspect what's happening is that there's no link being set at all on that activity's template. I'd like to get this in 2.1.9. Anyone know if this is an issue on `master`?

**Comment by agcyphers** [comment]
I don't know if this what you mean, but here's the GDN_ActivityType row for it:

	21	AddedToConversation	0	0	%1$s added %3$s to a %8$s.	%1$s added %3$s to a %8$s.	conversation	1	0

**Comment by agcyphers** [comment]
I'm also trying to locate the record I saw last night that included a braced URL: {UrlSomething}

**Comment by agcyphers** [comment]
Ah, I'm thinking of line 618 in class.conversationmodel.php

**Comment by agcyphers** [comment]
Just a note to say that I just received a notification for being added to a conversation where the link's href is explicitly set to the notifications page, IE:
<a href="http://forum.com/profile/notifications">conversation</a>

**Comment by linc** [comment]
This was fixed.
