### ISSUE TITLE
Translation of Roles Description

### ISSUE THREAD

**Issue by carlosten** [vanilla/vanilla#2180]
Coming from:
 http://vanillaforums.org/discussion/comment/217349/#Comment_217349

Bug:
Setting the translation for the roles description in the localizable files, will not take effect. 

Code used:
$Definition['Guest Role Description'] = 'Los invitados solo pueden ver el contenido. Toda la g...
$Definition['Unconfirmed Role Description'] = 'Los usuarios deben confirmar su email al regist....
$Definition['Applicant Role Description'] = 'Los usuarios que quieren ser miembros pero todaví...
$Definition['Member Role Description'] = 'Los miembros pueden participar en discusiones.';
$Definition['Moderator Role Description'] = 'Los moderadores pueden editar casi todo el conten...
$Definition['Administrator Role Description'] = 'Los administradores pueden hacer cualquier co...

**Comment by linc** [comment]
You can edit these in the Dashboard. We're not currently targeting this for a fix ourselves.
