### ISSUE TITLE
Both GetMentions and Gdn_Format::Mentions using Gdn::Factory('MentionsFormatter'); when one is matching not formating.

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#2208]
The code to formatting (replacing) the mentions is `Gdn_Format::Mentions($String)` the code for getting the matches is `GetMentions($String)` They both allow for override with `$Formatter = Gdn::Factory('MentionsFormatter');` except that is confusing matching with replacing. 

So if anyone uses that override it would break the notification or they would need to tell if they are in the model or not. It would make more sense to have `$Matcher = Gdn::Factory('MentionsMatcher');` as well.

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/comment/218365#Comment_218365

**Comment by linc** [comment]
I think we've gotten these back in sync.
