### ISSUE TITLE
Host header attack

### ISSUE THREAD

**Issue by grahammills** [vanilla/vanilla#2211]
Acunetix flags /categories and some other URLs as vulnerable.

http://www.skeletonscribe.net/2013/05/practical-http-host-header-attacks.html

e.g.

*Host header evilhost5V2akNRW.com was reflected inside a LINK tag (href attribute).*

GET /categories HTTP/1.1
Host: foo.bar
X-Forwarded-Host: evilhost5V2akNRW.com

**Comment by linc** [comment]
The request object has since been refactored, and I'm no longer able to replicate this behavior.
