### ISSUE TITLE
"Hide from the recent discussions page" also hides in /categories 

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2215]
When you mark a category with "Hide from the recent discussions page" it will also be hidden in the /categories index. That is a misleading phrase for admins.  
See here: http://vanillaforums.org/discussion/comment/218416#Comment_218416

Categories marked this way are filtered out in CategoryWatch so this setting has a *global* effect.
   
I do not know what the intention has been and so the solution might either be   
a) renaming the checkbox so that it is more obvious that such categories are filtered out nearly everywhere or
b) don't check for "HideAllDiscussions" in CategoryWatch and let the recent discussion view hook the event CategoryModel_CategoryWatch to do the filtering on demand

**Comment by linc** [comment]
I believe this was fixed with the addition of the `$AllDiscussions` param.
