### ISSUE TITLE
Update process includes overwriting .htaccess

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2216]
In order to update from version X.Y to X.Z you would usually just copy all files to your new location. But the .htaccess file is a "core" file that has to be changed in some cases (I guess it is the only one). If you simply copy all files to your server, you'll overwrite your customized .htaccess, rendering your installation possibly unusable.

I suggest to rename the file.

**Comment by linc** [comment]
I think to do this, the setup process needs to auto-rename the htaccess file if it's going to have a '.dist' name or whatever. And, it needs a fallback in case it isn't writable to prompt the user to do this. So this is a bit of work, not just renaming a file. I'd like to see this in 2.2, but I'd like to see the community tackle it in the next couple weeks if that's going to happen.

**Comment by linc** [comment]
Looking for your perspective on this @initvector not necessarily an immediate fix.

**Comment by linc** [comment]
Cosign.

**Comment by initvector** [comment]
For the sake of internal tracking, I'm closing this task in favor of following progress on the associated pull request: https://github.com/vanilla/vanilla/pull/4736

**Comment by linc** [comment]
This will be in 2.4.
