### ISSUE TITLE
Category UrlCode = CategoriesController method name should not be allowed

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2217]
If I create a new category "Discussions" it will have the UrlCode "discussions", which conflicts with the "/categories/discussions" view, rendered by CategoriesController Discussions method. Same goes with a category "All".
I think there should be a validation added to the CategoryModels Save method that prevents all method names of the CategoriesController as UrlCodes.

**Comment by bleistivt** [comment]
fixed in #3077

**Comment by hgtonight** [comment]
Confirmed in master and release/2.3
