### ISSUE TITLE
DiscussionModel BeforeGetCount event not fired

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2222]
When GetCount(); is called without arguments (like in DiscussionsController->Index) the counts are calculated from the CountDiscussions cache of the categories, rendering the BeforeGetCount event useless:

https://github.com/vanilla/vanilla/blob/6942247be3fcb27479d8ce68581e6e033a06d328/applications/vanilla/models/class.discussionmodel.php#L1058-L1072

**Comment by linc** [comment]
Are you requesting an earlier hook to use? I'm reluctant to move an existing hook, and I don't wanna make a new one for no reason.

**Comment by bleistivt** [comment]
The problem is that there is no way to modify the discussion counts in some cases.

You can always modify the discussions fetched using `beforeGet`, but `beforeGetCount` sometimes just doesn't work, which is inconsistent.
This will also lead to a faulty pager showing a wrong number of pages.

The `$Wheres` eventarg is not used by the non-cache logic. Thus moving the hook above the hightlighted piece of code I linked to should be safe.

I'll be happy to submit a pull request.

**Comment by linc** [comment]
A PR is always best. 👍

**Comment by DaazKu** [comment]
PR is under review.
