### ISSUE TITLE
Social Connect displays "Connect" option to end user before fully configured

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#2232]
When configuring Facebook and other social connects, the connection must be "Enabled" before the settings cog is available. This is fine, except that this also causes the connect to become available to end users, even if it is not yet fully configured. This causes the end user to see a JSON error when clicking the Connect button.

Correct workflow is that the user-side rendering of a Social Connect should depend on both isEnabled *and* isConfigured.

**Comment by linc** [comment]
This was fixed.
