### ISSUE TITLE
PluralTranslate is ignorant of what it needs to do

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#2246]
`PluralTranslate` is written based on the assumption that when referring to n items, if n=1 you use a singular form, and if n!=1, you use a plural form. This assumption works in English and some other languages, but is incorrect in a number of other languages, most notably Chinese, French, Arabic, and Russian. Refer to [this document](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html) for more than you ever wanted to know.

[Transifex supports this](http://docs.transifex.com/developer/formats/#plurals), but only "as long as the format itself supports them". I don't know Vanilla uses a format that does.

**Comment by linc** [comment]
Looking to resurface this for thoughts. Is this something we should pursue?
