### ISSUE TITLE
Accepted answers do not display attached files

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2252]
when a user accepts an answer, with the Q&A plugin on vanilla forums, the zip file disappears, mentioned somewhere a few times in the past year.

http://vanillaforums.org/discussion/comment/218786/#Comment_218786

I didn't file this on add-ons github - because this is a specific problem with vanilla forum and your forum specific add-ons are different apparently then the add-ons in github or so I think,
move the issue to where you want.  but could someone kindly fix.

Bedtime story here:

http://vanillaforums.org/discussion/comment/218841/#Comment_218841

**Comment by linc** [comment]
Bug in Q&A and/or FileUpload in the addons repo, not core.
