### ISSUE TITLE
Deleting a user and its associated content does not update category discussion count

### ISSUE THREAD

**Issue by jstsch** [vanilla/vanilla#2267]
I just trashed a user/bot who spammed tons of new threads throughout the forum. After deleting its content, the _n discussions_ count for each category stayed at the original number. After posting a new thread in the category, the discussion count is correct again.

Steps to reproduce:

1) Delete a user from the dashboard
2) Choose to also delete all content

* Expected result: the user is deleted, the content is gone, and the discussion counts on categories are updated
* Actual result: the user is deleted, the content is gone, the discussion count on categories are not updated 

Vanilla Version 2.1.3

PS: very happy with Vanilla since setting it up about half a year ago :) thanks a lot!

**Comment by linc** [comment]
So, this is actually a scaling strategy. If we force your entire forum to recalculate everything when you delete a spammer, it could actually bring down your database. By lazily letting it readjust as folks comment, we can safely bring things back in line. Temporary inaccuracy is an acceptable tradeoff for that, we think, and as your forum grows this will become far less obvious.
