### ISSUE TITLE
XSS when outputting user name

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#2289]
User name is not escaped when output in many places and this can lead to XSS. User names are by default limited to `\d\w_` but can contain other characters if `Garden.User.ValidationRegex` is changed or jsConnect is used.

Given a user name of `">--><script>alert('');</script>`

The script is executed at the following places:

User profile page (you may need replace the user name in the URL to get it to load): `<dd class="Name" itemprop="name">">--><script>alert('');</script></dd>`

After receiving a PM from that user and opening the inbox flyopen: `<b class="Subject"><a href="/index.php?p=/messages/1#latest">"&gt;--&gt;<script>alert('');</script></a></b>`

All pages (when logged in as that user): `<!-- <li><a href="/index.php?p=/profile" class="">">--><script>alert('');</script></a></li>`

Dashboard (when logged in as that user): `<a href="/index.php?p=/profile/3/%22%3E--%3E%3Cscript%3Ealert%28%27%27%29%3B%3C%2Fscript%3E" class="Profile">">--><script>alert('');</script></a><a href="/index.php?p=/entry/signout&amp;TransientKey=Y0V183X6AA7U" class="Leave">Sign Out</a>         </div>`

**Comment by linc** [comment]
This is patched.
