### ISSUE TITLE
Tagging /utility/structure error when upgrading from 2.0.18  to 2.1.6

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2291]
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'alter table `GDN_Tag` add unique index UX_Tag (`Name`, `CategoryID`)' at line 4|Gdn_Database|Query|/* 'unique index UX_Tag (`Name`)' => 'unique index UX_Tag (`Name`, `CategoryID`)' */ alter table `GDN_Tag` drop index UX_Tag; alter table `GDN_Tag` add unique index UX_Tag (`Name`, `CategoryID`);

where I saw this happen.

had tagging enabled in 2,0.18  so there was a tag table.
all plugins disabled.

user attempted upgrade
run utlility/structure

above error occurred.

had user go to  phpmyadmin and go to your database and

    run this
    alter table GDN_Tag drop index UX_Tag

and run /utility/structure again and it fixed issue

details here:
http://vanillaforums.org/discussion/comment/220308/#Comment_220308

http://vanillaforums.org/discussion/comment/220308/#Comment_220308

not sure if this is edge effect or why more people haven't reported issue, but 3 different sites reported issue in one day.

**Comment by linc** [comment]
I believe we fixed this with 2.1.8p2.
