### ISSUE TITLE
Definitions not read. re: ConfirmDeleteCommentHeading  and ConfirmDeleteCommentText

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2306]
neither
ConfirmDeleteCommentText

or
ConfirmDeleteCommentHeading

are loaded when discussions.js is called 
https://github.com/vanilla/vanilla/blob/master/applications/vanilla/js/discussion.js#L320

I could make it work by adding to class.controller.php

```
  if (!array_key_exists('ConfirmDeleteCommentHeading',  $this->_Definitions))
          $this->_Definitions['ConfirmDeleteCommentHeading'] = T('Delete Comment');
```

 if (!array_key_exists('ConfirmDeleteCommentText',  $this->_Definitions))
              $this->_Definitions['ConfirmDeleteCommentText'] = T('Are you sure you want to delete this comment?');

see:

http://vanillaforums.org/discussion/28620/how-to-tranlsate-some-kind-of-text

**Comment by DaazKu** [comment]
Fixed [a long time ago](https://github.com/vanilla/vanilla/commit/fcb5302382c8658a26ebf925c909450bc1922bc7).
