### ISSUE TITLE
Facebook: Avatar image is skewed

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2309]
This is an issue related to the Facebook plugin. Discussion thumbnails should set the width and height parameters rather than specify type=large (https://graph.facebook.com/[id]/picture?type=large vs https://graph.facebook.com/[id]/picture?width=X&height=X).

**Comment by jamesinc** [comment]
If you would like a not-recommended workaround for this issue, you can make a small change to `/library/core/functions.render.php`:

In the `UserPhoto` function, find this if block:
```php
      if ($Photo) {
         if (!isUrl($Photo)) {
            $PhotoUrl = Gdn_Upload::Url(ChangeBasename($Photo, 'n%s'));
```

and add an `else if` between the first case and else. The final if...else if... else block will look like this:

```php
         if (!isUrl($Photo)) {
            $PhotoUrl = Gdn_Upload::Url(ChangeBasename($Photo, 'n%s'));
         } else if (strpos($Photo, "graph.facebook.com") != FALSE) {
            // Handle Facebook URLs
            $ThumbSize = Gdn::Config('Garden.Thumbnail.Size', 40);
            $PhotoUrl = explode('?', $Photo)[0] . "?width=$ThumbSize&height=$ThumbSize";
         } else {
            $PhotoUrl = $Photo;
         }
```

I think you could do it the right way by hooking various events and finding and replacing URL references, but it looked more complicated. I have my site's source repo setup with vanilla's source as a branch of the site's implementation, so it's easy for me to merge in updated versions of Vanilla. If you're not doing this, beware it means you will need to manually re-apply the patch after updating.

**Comment by linc** [comment]
Member-suggested fix here: http://vanillaforums.org/discussion/31222/bugfix-facebook-user-images-lose-aspect-ratio-due-to-incorrect-api-call

**Comment by battaglia01** [comment]
FYI, this is the same member and I just submitted a PR for this. This way is way simpler and lets Facebook deal with the cropping.
