### ISSUE TITLE
Text-only formatting truncates at <

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2320]
`<` is being interpreted as an HTML opening tag. Makes it hard to `<3` someone.

**Comment by bleistivt** [comment]
The problems with `<` only start there. Everything until the next `>` is interpreted as an invalid tag and escaped.

Example:

    test <3 test <a href="http://vanillaforums.com">link1</a><a href="http://vanillaforums.com">link2</a>
    
    test <3 
    <a href="http://vanillaforums.com">link3</a>

This is a HTMLawed issue:
http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedTest.php
