### ISSUE TITLE
Category headings can be posted in if reached through the breadcrumb trail

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2323]
"I have my board set to use top-level Categories as headings, which works great except for one thing. The breadcrumb navigation allows users to get into a "heading" category, and then post stuff (but only in the current heading category, not the other ones). I don't want them in here at all, and I definitely don't want them posting stuff."

**Comment by DaazKu** [comment]
- The breadcrumb navigation has been fixed.
- The dropdown has been fixed (if you go on the category directly by typing its name in the URL)

I've added a little fix (#5092) to reject invalid categoryIDs.
