### ISSUE TITLE
Handle EXIF orientation in UploadImage

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2345]
> Update: I got a couple of original images from a poster. According to exiftool, they have an "orientation" attribute defined, which doesn't appear to be handled by SaveImageAs in class.uploadimage.php.  The images are properly oriented when I view them on my desktop (Mac), but it looks like the SaveImageAs code simply reads the width/height attributes and ignores the request to rotate.

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/comment/221216#Comment_221216

**Comment by webstey** [comment]
I submitted a PR for this, but it created a new issue.  Is there a way I could have submitted my PR as a proposed fix for this issue instead?

**Comment by hgtonight** [comment]
@webstey You just reference it as #number in your PR. Add a comment that says "Closes #2345" and github will do the linking for you.

**Comment by webstey** [comment]
TYAH!  (Thanks Yet Again HgTonight :) )

**Comment by linc** [comment]
And to cross-link on GitHub, just mention it.

Related:  #2438

**Comment by linc** [comment]
![screen shot 2015-01-26 at 11 41 04 am](https://cloud.githubusercontent.com/assets/117672/5903541/45d37176-a550-11e4-906d-6f57cc3dc618.png)

**Comment by webstey** [comment]
I think I've got it worked out. Awaiting confirmation from @linc and merge :)  FYI, works on 2.1.8.
