### ISSUE TITLE
Locale pt-BR: Warning: printf(): Too few arguments

### ISSUE THREAD

**Issue by retyikk** [vanilla/vanilla#2349]
Hi there everyone,

First of all, I don't know if here is the place to send this message, I'm sorry if it's not. And I'm sorry about my english too. :)

I received this error (Warning: printf(): Too few arguments) when I set Default Locale to pt-BR.
![vanilla-error](https://cloud.githubusercontent.com/assets/5360477/5436050/062f35a0-8449-11e4-9840-66ebe6fa990c.png)

I changed this line to: 
   printf(Plural($Score, 
      '%s point', '%s points'), 
      BigPlural($Score, '%s point'));

And it work. I don't know if this is correct. Hope it helps.

Thank you.

**Comment by linc** [comment]
I don't believe this is still an issue.
