### ISSUE TITLE
Parent categories' Most Recent discussion should include discussions from sub-categories

### ISSUE THREAD

**Issue by KevBelisle** [vanilla/vanilla#2358]
Similarly to issue #2357, even if the most recent discussion in a category happens to be in a sub-category, it should still appear as the most recent discussion for the parent category.

**Comment by adrianspeyer** [comment]
I can confirm this does happen on master as well, version Version 2.2.16.9. One solution might be to to use "Display root categories as headings", but might need work for all situations. One solution was offered : http://vanillaforums.org/discussion/comment/221698/#Comment_221698, but it needs further refinement.

**Comment by tburry** [comment]
We had tried this before and it was a complete UX failure in pretty much all communities.

Try setting the `Vanilla.ExpandCategories` config setting to get what you want.
