### ISSUE TITLE
reCaptcha api key URL is no longer valid

### ISSUE THREAD

**Issue by hgtonight** [vanilla/vanilla#2360]
...

To use reCAPTCHA you must get an API key from https://www.google.com/recaptcha/admin/create"

But when you click on that link you get a page not found error.

...

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/28809/recaptcha-stopping-new-user-registration/p1

**Comment by linc** [comment]
@adrianspeyer

**Comment by adrianspeyer** [comment]
@linc https://github.com/vanilla/vanilla/pull/2497, but you need to review line 204. It seems, according to comment we need to use this new library than current one shipped with Vanilla.

**Comment by linc** [comment]
@adrianspeyer I recommend we just ditch everything from the `?` onward and just return the same basic URL as your other edits.
