### ISSUE TITLE
System User email address raised by Anonymoose.

### ISSUE THREAD

**Issue by peregrine-web** [vanilla/vanilla#2363]
see discussion

http://vanillaforums.org/discussion/28826/system-user-account

anonymoose comment: 
System user account has email of system@domain.com which is a valid email, since domain.com is a valid domain. Potentially bad for resetting the password of the "System" account.

**Comment by Anonymoosed** [comment]
invalid.com is not a reserved domain, see http://invalid.com

**Comment by SchlesserClaude** [comment]
example.org and example.com at domains especially reserverd for that purpose by the Internet Assigned Numbers Authority: http://www.iana.org/domains/reserved

**Comment by hgtonight** [comment]
@SchlesserClaude from your link: http://tools.ietf.org/html/rfc6761 section 6.4 recognizes `invalid.` domains as special.

@Anonymoosed people not following standards is not a reason to not follow them.

**Comment by Anonymoosed** [comment]
@hgtonight That's not someone not following standards, that's a valid domain. 

You were thinking of this: http://domain.invalid/ is invalid. http://invalid.com/ is a valid domain.
