### ISSUE TITLE
BeforeDiscussionName Event is not fired for table view

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2375]
Not sure if BeforeDiscussionName event has never been active in table view or if it has been deactivated on purpose: https://github.com/vanilla/vanilla/blob/master/applications/vanilla/views/discussions/table_functions.php#L44-47

**Comment by bleistivt** [comment]
this has been fixed #2758

**Comment by hgtonight** [comment]
Fixed in master and release/2.3
