### ISSUE TITLE
Profile links break on usernames with forward slashes

### ISSUE THREAD

**Issue by wilson29thid** [vanilla/vanilla#2376]
We use ranks as part of our usernames in our community, and one of the ranks is `T/5`. Any profile links for these members give a 404 because of the forward slash. Originally it was an apache 404, but I added `AllowEncodedSlashes On` to the site `.conf` file and now it at least lets it through to the application. But Vanilla also gives a 404, user not found. Here's the trace:

```
#0 /var/www/html/forums/applications/dashboard/controllers/class.profilecontroller.php(1387): NotFoundException('User')
#1 /var/www/html/forums/applications/dashboard/controllers/class.profilecontroller.php(413): ProfileController->GetUserInfo('8', 'T', '5 Smith')
#2 [internal function]: ProfileController->Index('8', 'T', '5 Smith', false)
#3 /var/www/html/forums/library/core/class.dispatcher.php(350): call_user_func_array(Array, Array)
#4 /var/www/html/forums/index.php(46): Gdn_Dispatcher->Dispatch()
#5 {main}
```

Anything I can do here?

**Comment by wilson29thid** [comment]
If someone can give general direction I can troubleshoot and submit a pull request if that's helpful?

**Comment by linc** [comment]
We probably don't want to allow usernames with a slash in the first place. The trick is reconciling this with jsConnect in a way that doesn't break a connection with a bad username is passed.

**Comment by linc** [comment]
How we'll handle this: https://github.com/vanilla/vanilla/issues/4960
