### ISSUE TITLE
V2.2 Database setup error: incorrect integer value in the gdn_permission table

### ISSUE THREAD

**Issue by aboufeta** [vanilla/vanilla#2384]
(This comes from a post on the vanilla forum)
Hi there, I'm trying to install the latest version of Vanilla(running on a windows wamp 5.3.6 install), the master branch from the git repo. I'm doing this because I'd like to use the API application which requires a v2.2 version.

I can't get to make the setup work, because of the following database error: incorrect integer value in the gdn_permission table
    Incorrect integer value: 'Garden.Moderation.Manage' for column 'Garden.Curation.Manage' at row 1|Gdn_Database|Query|insert GDN_Permission (Garden.Email.View,Garden.Settings.Manage,Garden.Settings.View,Garden.Messages.Manage,Garden.SignIn.Allow,Garden.Users.Add,Garden.Users.Edit,Garden.Users.Delete,Garden.Users.Approve,Garden.Activity.Delete,Garden.Activity.View,Garden.Profiles.View,Garden.Profiles.Edit,Garden.Curation.Manage,Garden.Moderation.Manage,Garden.PersonalInfo.View,Garden.AdvancedNotifications.Allow,RoleID,JunctionTable,JunctionColumn) values (:GardenEmailView, :GardenSettingsManage, :GardenSettingsView, :GardenMessagesManage, :GardenSignInAllow, :GardenUsersAdd, :GardenUsersEdit, :GardenUsersDelete, :GardenUsersApprove, :GardenActivityDelete, :GardenActivityView, :GardenProfilesView, :GardenProfilesEdit, :GardenCurationManage, :GardenModerationManage, :GardenPersonalInfoView, :GardenAdvancedNotificationsAllow, :RoleID, :JunctionTable, :JunctionColumn)_
    
So that you know, I can install and setp a v2.1.6 version of Vanilla without problem.

So far, based on more or less similar help messages I've found on the net, I have : * checked mysql strict mode on the server, * created the vanilla schema without '_' in the name * created the vanilla schema from mysql workbench, and from php myadmin (each time from the wizard and by sql query) * checked the users rights (root and vanilla user) * ... And, I'm aware that the branch is not stable.

I'd gladly help you investigate this issue.

**Comment by linc** [comment]
Sounds like a MySQL strict error. You could disable that mode as a workaround. If anyone can contribute a fix for core, that'd be great. We probably won't tackle this on our own as we don't officially support that mode.

**Comment by linc** [comment]
We're using #2862 as the canonical copy of this bug now. Thanks for reporting it!
