### ISSUE TITLE
A deleted RoleID could be reassigned which leads to a possible security flaw

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2385]
http://vanillaforums.org/discussion/comment/223294/#Comment_223294   
   
1. Create role   
2. Assign user to role    
3. Delete role    
4. Create new role   
If a role is deleted and no replacement role is chosen for users with that role, the entries in UserRole are not deleted.   
The next role created will get the same RoleID and because the UserRole entries still exist in db, the users assigned to the deleted role are already assigned to the new role.

**Comment by linc** [comment]
Shouldn't auto increment cause it to skip the deleted RoleID?

The undeleted UserRole records is definitely a bug.

**Comment by R-J** [comment]
Turns out that innodb “forgets“ last auto incremented id and simply uses max(id) + 1 while myisam uses auto increment as expected. So easy fix would be to change the db engine for Role table but I think it is cleaner to delete garbage from UserRole after role is deleted

**Comment by linc** [comment]
Nice insight, thanks.
