### ISSUE TITLE
Mention adds [] if you press enter after name

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2386]
I was quickly writing a post and I noticed when I click enter after an auto-complete mention, it adds a [].

![image](https://cloud.githubusercontent.com/assets/425366/5663962/52c60540-971a-11e4-8861-1b3ef63fb577.png)

It's hard to get rid of too.

**Comment by linc** [comment]
Current `master`?

**Comment by adrianspeyer** [comment]
I noticed the issue on .org forum and on my hosted forum on cl1. Possibly source Advanced Editor
