### ISSUE TITLE
Gdn_Form should support serialized input arrays

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2388]
There have been multiple reports about the category/permissions settings screen exceeding  max_input_vars.

**Comment by linc** [comment]
Wow, really? Do we know what hosts?

**Comment by hgtonight** [comment]
The default PHP max_input_vars is set to 1000.

Meaning it should occur on all hosts.

**Comment by linc** [comment]
Oh we're talking about someone with a whack-load of categories, right?

**Comment by bleistivt** [comment]
Yes, quite a lot:
http://vanillaforums.org/discussion/28947/unable-to-edit-all-roles-permissions

But what this user reports is still in the range of what vanilla should be able to handle, imo.

**Comment by linc** [comment]
It's actually the roles causing the issue there. Vanilla isn't really designed for 100 individually private-roled categories. The UI alone would make that a nightmare.

**Comment by linc** [comment]
I'm inclined to say this is outside the scope of something we want to support right now. If you want dozens or hundreds of private categories, you want a Social Groups type of solution which isn't currently part of Vanilla. Adding serialized input arrays is just kludging a workaround to solve a poblem we're not trying to solve with categories & roles.

**Comment by bleistivt** [comment]
I see. Personally I'd also advocate against any more than ~15 categories and roles. 

Until we have some sort of groups applications for open source I may take a stab at developing a plugin to circumvent this.
