### ISSUE TITLE
Update Utility Fails: vanillaforums.org gives invalid XML

### ISSUE THREAD

**Issue by Anonymoosed** [vanilla/vanilla#2399]
http://vanillaforums.org/vforg/home/getfeed/announce/2/extended/?DeliveryType=VIEW gives an error, but is called from /dashboard/utility/update which then fails.

    Whoops! There was an error.
    FATAL ERROR IN: SimpleXMLElement.__construct();

    "String could not be parsed as XML"

    LOCATION: /var/www/frontend-38e845f0594881/applications/vforg/controllers/class.homecontroller.php
    > 133:             $Url = 'http://blog.vanillaforums.com/feed/';
    > 134:       }
    > 135:       
    > 136:       $RawFeed = file_get_contents($Url);
    >>> 137:       $this->Feed = new SimpleXmlElement($RawFeed);
    > 138:       $this->Render();
    > 139:    }
    > 140: 
    > 141:    public function ProxyFeed($Url) {

    BACKTRACE:
    [/var/www/frontend-38e845f0594881/applications/vforg/controllers/class.homecontroller.php 137] SimpleXMLElement->__construct();
    [/var/www/frontend-38e845f0594881/applications/vforg/controllers/class.homecontroller.php 137] HomeController->GetFeed();
    [/var/www/frontend-38e845f0594881/library/core/class.dispatcher.php 356] PHP::call_user_func_array();
    [/var/www/frontend-0a1cdcba836fe6/index.php 46] Gdn_Dispatcher->Dispatch();

**Comment by linc** [comment]
I believe this was fixed.
