### ISSUE TITLE
GDN_UserAuthentication for Google appears each time you do a Utility Structure Update

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2407]
Everytime you run Utility Update you will get following, not sure it's needed after first time run.

    update GDN_UserAuthenticationProvider `UserAuthenticationProvider`
    set AuthenticationSchemeAlias = 'GooglePlus'
    where AuthenticationSchemeAlias = 'Google+';

Also referenced here: http://vanillaforums.org/discussion/comment/223785/#Comment_223785

**Comment by adrianspeyer** [comment]
issue seems to appear only if you had Google SSO enabled and moved to Google+. Fresh install is fine.

**Comment by adrianspeyer** [comment]
Using version 2.2.100.3, when running utility update multi times, the following shows even after changes made in DB.

`update GDN_Role `Role`
set Type = 'applicant'
where RoleID = '4';

update GDN_Role `Role`
set Type = 'member'
where RoleID = '8';

update GDN_Role `Role`
set Type = 'unconfirmed'
where RoleID = '3';

update GDN_User `User`
set Permissions = ''
where Permissions <> '';

update GDN_UserAuthenticationProvider `UserAuthenticationProvider`
set AuthenticationSchemeAlias = 'GooglePlus'
where AuthenticationSchemeAlias = 'Google+';`

**Comment by linc** [comment]
This was fixed previously.
