### ISSUE TITLE
Image uploads on Windows: Wrong path

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2411]
I haven't dug deeper into this yet, because I don't use windows in production, but this commit breaks image uploads in windows environments:

https://github.com/vanilla/vanilla/commit/a2fa4d0a6cfe05af7e80bfab3d366dbe5ea469e6

When uploading an avatar, the path looks like this:
http://localhost/vanilla-master/uploads/C:///userpics/208/p0ARVZF37D2SC.png

And in the database:
C:///userpics/208/0ARVZF37D2SC.png

The image is actually in:
C:\www\vanilla-master\uploads\userpics\208\0ARVZF37D2SC.png

**Comment by AshVenom** [comment]
Do u use 2.1.6 version? If yes, this bug fixed in 2.1.7 .
If i'm not wrong, its because  "u.photo"  isn't in "GROUP BY" SQL.

**Comment by bleistivt** [comment]
@AshVenom No, this is a different issue only on master. (see the commit I linked to)

**Comment by bleistivt** [comment]
Works on a different setup. Most likely a misconfiguration on my side.
