### ISSUE TITLE
PHP 5.2 / 5.4 check

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2419]
* index.php must be validated as PHP 5.2 compatible so it does not fatal on 5.3+.
* Need to throw an exception or exit on PHP <  5.4.

**Comment by linc** [comment]
Also add checks for PDO & Unicode support for regex.

**Comment by tburry** [comment]
I wonder if a standalone checker would be nice. That way we can also increase requirements over time and people can just run a single page to see if they meet them.

**Comment by linc** [comment]
What I'd really like to see is a something in the Dashboard per #2018 that also incorporated a warning if the coming upgrade was going to fail on their current PHP version.
