### ISSUE TITLE
BBCode: merge NBBC parser & support legacy formatting

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2422]
- [x] NBBC should be brought into core as part of our standard BBCode implementation
- [ ] The special "IPB parsing" we use on imports (that also allows `<br />` tags) should also be incorporated into core, possibly as standard ([SMF also uses it](http://vanillaforums.org/discussion/29107/from-smf-to-vanilla-2-1-how-to-clean-up-bbc-code)).

**Comment by tburry** [comment]
@linc is this done?
