### ISSUE TITLE
Spoilers: refactor into core

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2426]
See notes on related dead PRs: 
https://github.com/vanilla/addons/pull/148
https://github.com/vanilla/internal/pull/114 

Marking for 2.next but that's questionably optimistic.

**Comment by bleistivt** [comment]
What style of spoilers are you going to support?

Currently, with the Spoilers plugin there are the BBCode [spoiler] tags (with a reveal button and optional title) and with Markdown >! you get the minimalist "..."-spoilers

**Comment by hgtonight** [comment]
It all parses to HTML so I would hope the spoiler implementation would be format agnostic.

**Comment by linc** [comment]
The default should be somewhere in the middle. The "..." is a nice idea (referencing the "snip" used in Gmail) but the wrong UI paradigm. We were talking about simply the word "Spoiler" as the toggle button. Maybe add a plus or minus symbol next to it depending on whether it's expanded.

**Comment by bleistivt** [comment]
this has been fixed in #3606
