### ISSUE TITLE
HTML in category description - inconsistent behaviour

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2435]
Category descriptions allow raw HTML, but tags are stripped in the /category view while in the /categories view they are not.

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/comment/224605#Comment_224605

**Comment by linc** [comment]
On the fence about which way to resolve this. I don't really wanna restrict it for no reason, but I also can't think of a strong case for allowing it.

**Comment by phreak** [comment]
Hi @linc and @bleistivt. Do you have an idea how i can work around the stripping. Thanx.

**Comment by phreak** [comment]
It works @bleistivt. A problem related to this looks to be that the page description has a similar issue. It seems that HTML attributes like for example <span> get rendered but class="" inside gets stripped.
