### ISSUE TITLE
Markdown code parsing: new lines & auto-linking

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2445]
(from @tburry)

Consider the following Markdown:

```
This is a paragraph.

`echo 'one';
echo 'two';`
```

This will render an extra empty `<p>` tag in between the first paragraph and the source code which really shouldn't happen. 

Consider the following Markdown:

<pre><code>```
&lt;http://example.com/&gt;
```</code></pre>


This will render a trailing sem-colon. Probably a bug in our autolinking more that Markdown.

**Comment by DaazKu** [comment]
Our autolinking seems to have been fixed.
The extraneous `<p>` is still a problem though
