### ISSUE TITLE
Controllername inconsistency

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2458]
Would make a pull request, if I knew how to resolve this:

If you search for Controllername, you can see 4 different conventions:
https://github.com/vanilla/vanilla/search?p=1&q=controllername&utf8=%E2%9C%93

all lowercase + "controller" (this seems to be the preferred way)
camelcase + "controller"
lowercase without "controller"
camelcase without "controller"

**Comment by linc** [comment]
This is a @tburry question.

My guess is lowercase + "controller". I also suspect a lot of these instances could/should be using "section" detection now that we've added that.

**Comment by bleistivt** [comment]
It seems kind of superflous since there is already Pluggable::$ClassName

**Comment by bleistivt** [comment]
Closing this since I have been using `section()` in favor of `ControllerName` for some time now.
