### ISSUE TITLE
Profile Extender: Adding Birthday field doesn't allow blank

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2465]
Once Birthday is in a profile, a blank one triggers "DateOfBirth is invalid" error, which prevents you from doing basic member management (like changing roles) until you give them one.

**Comment by bleistivt** [comment]
For reference:
http://vanillaforums.org/discussion/comment/215935/#Comment_215935

0-0-0 dates should be filtered out though, because they show up in profiles.

**Comment by bleistivt** [comment]
Related: https://github.com/vanilla/vanilla/issues/2030
