### ISSUE TITLE
Smileys are rendered inside code tags

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2467]
Smiley shortcuts inside code tags will be rendered. See: http://vanillaforums.org/discussion/comment/225036/#Comment_225036   
Text is first parsed for smileys and afterwards handled by the js code renderer so that code already contains smileys.

**Comment by JasonBarnabe** [comment]
More generally, nothing after the `code` start tag should be special except the `code` end tag.

**Comment by valeryan** [comment]
This is also triggering on youtube/vimeo urls inside code blocks. Your formatting should probably skip over everything inside a code block

**Comment by JasonBarnabe** [comment]
With this PR, YouTube links are also left alone when inside `<code>`.
