### ISSUE TITLE
AutoOffset no longer acting as intended

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2469]
Applied AutoOffset fales to config to stop jumping to last unread post:

```
$Configuration['Vanilla']['Comments']['AutoOffset'] = FALSE;
```

 Does not seem to be respected in latest master.

**Comment by charrondev** [comment]
It seems to be failing still non my localhost (running latest master):

## To reproduce

- Create a thread with user a
- Have user b create a comment
- Have user a visit thread
- Observe getting jumped down to that comment.

**Comment by bleistivt** [comment]
Sorry, I tried it with a discussion of 4 pages. It correctly sent me to the first page which didn't contain the `#latest` anchor. So I guess it's half broken: It sends you to the right page but if that page contains a `#latest` anchor it will still be the wrong offset.

What would be the preferred fix?

- Not linking to the #latest anchor form the discussion view?
- Not adding the anchor at all?

**Comment by charrondev** [comment]
I'm leaning towards

> Not adding the anchor at all

Primarily because it keeps everything on the `DiscussionController` side. Do you have an opinions here @linc ?

**Comment by bleistivt** [comment]
@tburry Is Autooffset = off being deprecated?

If not, I don't see how this is working as intended. It should also a really simple fix (adding or not adding the hash, see above). The only thing missing here was the decision of a maintainer how it should be approached.

**Comment by tburry** [comment]
I am just working to get our issues down to a manageable state which involves closing off some issues that are stale and are unlikely to be fixed.

Given that this issue was filed in 2015, it fits that description. Most likely `Vanilla.Comments.AutoOffset` will be deprecated out.
