### ISSUE TITLE
Advanced search: permissions not respected

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2473]
This might just be a caching thing, since this topic was once public. But I don't know the inner workings of the advanced search (I guess it uses Sphinx?), so I'm reporting it here just in case:

http://vanillaforums.org/search?adv=1&search=&discussionid=28945

I can still read the excerpts of all posts of this topic through the advanced search even though it was moved to a category I don't have permission to.

**Comment by linc** [comment]
After 11 days, this issue persists. I believe it never updates the category in the cache.

**Comment by linc** [comment]
Pretty certain this got resolved.
