### ISSUE TITLE
Dirty dishes in sink: find owner and destroy their face

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2491]
Vanilla HQ has been suffering repeated attacks by dirty-dish fairies who don't clean up after themselves. Track them, find them, and destroy them.

**Comment by linc** [comment]
![](http://image-cdn.zap2it.com/images/david-caruso-sunglasses.jpg)

**Comment by adrianspeyer** [comment]
We some suspects. The guilty shall be found.

![](http://www.wired.com/wp-content/uploads/images_blogs/underwire/2014/01/Sherlock.jpg)

**Comment by linc** [comment]
AND DO IT WITH WITTY ONE-LINERS

https://www.youtube.com/watch?v=_sarYH0z948

**Comment by JulieVanilla** [comment]
Obviously, it was aliens.

![foxmulder](https://cloud.githubusercontent.com/assets/8974997/6169938/d17aea5a-b29e-11e4-939e-ad7f04849ab3.jpg)

**Comment by adrianspeyer** [comment]
The cast of Fringe is free, maybe they can help.

**Comment by JulieVanilla** [comment]
Or perhaps we should invest in a copy of this...

![psych](https://cloud.githubusercontent.com/assets/8974997/6170022/793620b6-b29f-11e4-87d6-3f17b922227d.jpg)

**Comment by kaecyra** [comment]
Finally, getting some results!  

![](http://i487.photobucket.com/albums/rr232/papaya00/LJ/2wgfzoojpg.gif)

**Comment by linc** [comment]
Terrance is gone so this is fixed now right? (too soon?)
