### ISSUE TITLE
Make utf8mb4 the MySQL charset of choice

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#2515]
The MySQL `utf8` character set, despite the name, does not support all of UTF-8. Because it only allows for up to 3 bytes per character, it does not support characters on the supplemental plane, most relevantly: emoji and some CJK characters. The `utf8mb4` character set, on the other hand, allows for up to 4 bytes per character, and so supports all of UTF-8. The storage requirements for `utf8mb4` are the same as for `utf8`, except when you use 4-byte characters. [More info here.](http://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html)

I've been running one of my forums on `utf8mb4` for over a year now with no problems, except for #2082.

**Comment by tburry** [comment]
What is the impact of a forum that started in utf8 and then gets changed to utf8mb4?

**Comment by JasonBarnabe** [comment]
My forum *was* initially `utf8` and I switched it to `utf8mb4`. `utf8mb4` is a superset of `utf8` so there is no data conversion required. I've noticed no bad effects other than Vanilla wanting to change back the columns I resized (see #2082) on update.

**Comment by tburry** [comment]
You can see the pull request I've made to address this issue. I'm not sure we'll be able to change the default character set to utf8mb4. Here are some issues we are thinking of.

1. A change on current databases involves a massive update to some really big databases we host and I'm pretty sure an encoding change blocks the database.
2. I don't think older versions of MySQL support utf8mb4.

We could put a collation check on install which we might do. However for problem number 1 we need to have a transition period where we do the following.

1. Save the current encoding to the application config on utility/update. This will lock existing databases into their encoding and prevent the bad update.
2. Wait a release or two to give installations the opportunity to lock their current encoding.
3. Modify the install routine to detect utf8mb4.

You can see that this is quite a bit of effort when really my current pull request should be good enough for advanced admins that can just go into their config and change the collation.

**Comment by JasonBarnabe** [comment]
`utf8mb4` requires MySQL 5.5.3 or above.

I've just tested a bit on a non-Vanilla DB, it doesn't look to me like changing the character set of a table blocks it from reads, at least.

You have the option to set the default encoding on the database but not convert any tables. This would make new installs be `utf8mb4` but not convert any existing tables in existing installs.

**Comment by tburry** [comment]
The command you want to check is this:

```sql
ALTER TABLE somebigtable CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Check out [this table](http://www.slideshare.net/morgo/using-mysql-in-automated-testing/11) on which DML statements block. The third column is the one you want a yes in. Also check out [this discussion](http://vanillaforums.org/discussion/29862/can-someone-with-mysql-5-0-or-5-1-run-a-query-for-me) where I'm trying to get some info about compatibility of utf8mb4.

**Comment by JasonBarnabe** [comment]
Reads seem OK. Writes are blocked.

Running the conversion against production data on my laptop, the tables that took longest are GDN_Log (18s for 17k rows), GDN_UserAuthenticationToken (20s for 10k rows), and GDN_Comment (10s for 70k rows). Hope this is useful to extrapolate the effect on your "really big databases".
