### ISSUE TITLE
Simplify upgrades: notice to delete removed files if they still exist

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2518]
Our upgrade process for open source is "copy these new files over" but every once in a while, we remove a file that can cause problems with that methodology, like the `helper_functions.php` in the default mobile theme, or the `default.master.php` when we went to .tpl. What do we think of adding some basic file deletion to the Dashboard's Structure to nuke those files so we can simplify upgrade instructions?

My only concern would be if someone has hacked those files, but I kinda feel like you voided your warranty in that situation.

---

The consensus appears to be adding a notice that prompts you to delete them yourself.

**Comment by R-J** [comment]
In general: if it is okay for me that all my files are overwritten, it should be okay that some files vanish altogether. But I'd prefer to replace its contents with a short comment

~~~
<?php
// this file is not needed from version x.y onwards
~~~

**Comment by linc** [comment]
@R-J That would defeat the point and further break sites. The files need to be deleted because of view overriding.

**Comment by x00** [comment]
I don't think so.

I think you can tell people to delete files, but that is as far as it should go. 

Once you you are in the business of file management, that is a lot of responsibly on your shoulders. It has consequences such as requiring permission over the files. 

I think Install/Upgrade should be about guiding people. 

If it worked differently, and you were producing a client program for updates an addons, that is one thing becuase it ti not part of web application itself, it is a tool for server management of the framework.

**Comment by chanhong** [comment]
Is it possible to rename or move the file to be deleted and replace it with a holder file with info about the action so that the user have a way to trace back to figure out what to do.

**Comment by x00** [comment]
@chanhong I don't really see the point. What webmaster gives permission to a webapp to do that sort of thing anyway?

**Comment by x00** [comment]
Don't use a sledgehammer to crush a nut. This is a minor inconvience.

**Comment by chanhong** [comment]
ok, then just show in the install instruction that which file to be deleted so that they will have a chance to backup the file themselves and decide what to do with it.

**Comment by x00** [comment]
general feedback mechanism in install/upgrade +1

**Comment by hgtonight** [comment]
Hmm... I don't like the idea of automatically deleting files.

Perhaps an inform message on admin pages saying a file that should be deleted exists would be better? Basically a dismissible message that is inserted in the structure phase?

**Comment by adrianspeyer** [comment]
I agree with @hgtonight, make it clear: "Hey this file does should be removed" maybe part of the utility structure phase?

**Comment by linc** [comment]
I like the message idea & will amend the issue to reflect that.
