### ISSUE TITLE
SafeRedirect & "you are leaving this site" page

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2521]
Currently, the default setting for the `EntryController`'s `Target()` method is to act as an open redirect. If you add `Garden.TrustedDomains` to your config, it closes this open redirect, however this is a bad default for security.

Proposed solution:

1. Add a `Leaving` method to the `HomeController` to serve as a redirect landing page. "You are now leaving {site}" to confirm the user's intent to leave the forum.

2. Add a `SafeRedirect` function which sanitizes redirects against a list of trusted domains, and sends them thru the new `/home/leaving` endpoint if it is not trusted.

3. Add a way of managing the list of trusted domains and/or URLs, and call them in a hookable way so that plugins like jsConnect can add its designated URLs on the fly.

Ability to accept wildcards in the domains / URLs and whether to specifically designate http vs https are design considerations.

**Comment by tburry** [comment]
The place where the domains are currently held is: `C('Garden.TrustedDomains')`.
