### ISSUE TITLE
Import from XenForo uses wrong password hash type

### ISSUE THREAD

**Issue by ukjbrown** [vanilla/vanilla#2545]
There are two methods used by XenForo (henceforth "XF") to store password hashes, it appears Vanilla only supports one. The method that doesn't appear to be supported is named "XenForo_Authentication_Core12" in the XF database. The one supported by Vanilla I believe is known as "XenForo_Authentication_Core11" which is an older method of authentication for XF.

The new method is the same as the "crypt" password HashMethod supported by Vanilla, only you need to deserialize the value to obtain the actual hash so simply updating the HashMethod for all users to "crypt" doesn't work.

This may not work for all XF configurations, but it worked for me... I added the following HashMethod type to class.passwordhash.php and then updated the HashMethod for all imported users to xf12. After I did this I could login to Vanilla and the password was updated to a Vanilla hashed password.

```
case 'xf12':
  $Data = @unserialize($StoredHash);
    if (!is_array($Data))
      $Result = FALSE;
    else {
      $Hash = GetValue('hash', $Data);
      $ComputedHash = crypt($Password, $Hash);               
      $Result = $ComputedHash == $Hash;
    }
  break;
```

Please let me know if there is a better way of doing this (or I made a mistake during import or something). Otherwise, I think it would be useful for the import tool to recognise the new hashing method and support it during the import and login phases.

**Comment by linc** [comment]
Thanks for the heads up, @ukjbrown! Could you make me a password hash of, say, the word 'password' so I can take a look and have something to test with? Is there an easy way to detect the difference between which hash is being used in a XF database? I don't have one handy at the moment.

Thanks for taking the time to puzzle this out and let us know.

**Comment by ukjbrown** [comment]
No worries, unfortunately not at the moment. I don't actually have access to the XF forum I am importing from as it was a database export provided to me by someone who wanted the forum migrating. I had already migrated from XF to MyBB but MyBB is lacking some critical features so I tried Vanilla as an alternative and so far it appears to tick the boxes.

This reminds me, I also had a problem when importing from the tar.gz as it kept failing when I entered the old admin username/password. I wasn't aware of the hashing issue at the time, so I simply modified the import controller to return TRUE for the admin password check. I'm guessing now that this was failing due to the same reason.

An example record I can provide right away is as follows;
user_id = 79
scheme_class = XenForo_Authentication_Core12	
data = a:1:{s:4:"hash";s:60:"$2a$10$02Z0z/YS7hKUd1Vh2mFKheaXIsRcxP2JOZKPR1iGb7f9NWClylM0y";}

**Comment by linc** [comment]
Awesome, thanks. FWIW, the next version of Vanilla won't have that password box on the import page. Lots of folks had trouble with it. The best solution is to leave the password blank and check "Use my current password" instead. There's a couple other "gotchas" we're trying to take out of the process too.

**Comment by ukjbrown** [comment]
For reference, I've modified my class.passwordhash.php as follows as it works with the current import and is a bit neater.

```
case 'xenforo':
  $Data = @unserialize($StoredHash);
  if (!is_array($Data))
    $Result = FALSE;
  else {
    $Hash = GetValue('hash', $Data);           
    if(strlen($Hash) <= 40) {  // xf11 (md5 or sha1)
      $Function = GetValue('hashFunc', $Data);
      if (!$Function)
        $Function = strlen($Hash) == 32 ? 'md5' : 'sha1';
        $Salt = GetValue('salt', $Data);
        $ComputedHash = hash($Function, hash($Function, $Password).$Salt);
      } else {  // xf12
        $ComputedHash = crypt($Password, $Hash);  
      }         
      $Result = $ComputedHash == $Hash;
    }
    break;
```

**Comment by linc** [comment]
@ukjbrown Thanks! Would you mind signing our CLA so I can use that? http://vanillaforums.org/contributors

**Comment by ukjbrown** [comment]
Done.

**Comment by linc** [comment]
Backport to release/2.3
