### ISSUE TITLE
editor doesn't respect image exif orientation

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2552]
Embedded images appear without respect to proper orientation.

Help me Obi @webstey you're my only hope.

**Comment by linc** [comment]
@webstey ? :(

**Comment by webstey** [comment]
I should have some time soon! Sorry!!  Maybe tomorrow!

**Comment by linc** [comment]
No worries, just wanted to see if you were still around :+1:

**Comment by webstey** [comment]
Sorry @linc , I was too busy to help out :(

**Comment by initvector** [comment]
@webstey I stood on the shoulders of your original fix for this, so you certainly *did* help! Thank you!
