### ISSUE TITLE
Quotes / Wysiwyg: Use mention not linked name

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2567]
Other formatting options correctly mention the quoted user. Wysiwyg does a nofollow link for no reason.

**Comment by slafleche** [comment]
@linc I just did a test locally. The BB code adds a "»" link to the comment. The WYSIWYG doesn't. In both cases, the profile link and the QuoteLink are "nofollow". I assume I'm supposed to add the Quote link to WYSIWYG and remove the nofollow for all of them?

**Comment by slafleche** [comment]
@linc Do we want to index the profile pages?

**Comment by DaazKu** [comment]
Profile pages are private in many cases. I don't know what makes them public vs private but since they may be private the no follow makes sense.

**Comment by slafleche** [comment]
Both links have nofollow, it's consistent. This must of been fixed since this task was created in 2015.
