### ISSUE TITLE
Upgrade Smarty library

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2571]
1. We are running 2.6.25 from 2009
2. preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /git/vanilla/library/vendors/Smarty-2.6.25/libs/Smarty_Compiler.class.php line 270

**Comment by navjotjsingh** [comment]
Not just Smarty but you need to upgrade all libraries you ship with Vanilla.

**Comment by Csabbencs** [comment]
For me, php 5.5 with Smarty 2.6.28 still works together well, but Smarty 2.6.25 (supplied with vanilla 2.2) does not. 
For Smarty 3.1, you have to update class.smarty.php for sure.

**Comment by linc** [comment]
thanks for the heads up!
