### ISSUE TITLE
FileUpload: Insert Image inserts HTML into BBCode (have a fix already)

### ISSUE THREAD

**Issue by MichaelPote** [vanilla/vanilla#2585]
I've identified a bug in the FileUpload plugin - it blindly inserts HTML into the comment regardless of your chosen input format.

I've modified the fileupload.js file to load the current InputFormat and modify it's output to support BBCode or HTML depending on your forum settings.

I'm new to open source contributing on GitHub, so if someone could let me know how to submit a pull request that would be great.

I've checked out the 'stage' branch, created a branch called 'hotfix/fileupload' off 'stage' and I've commited the change to that branch, ready to submit a pull request but I'm unable to push to the repo - I get "Invalid Username or Password". I guess I dont have permission?

**Comment by Namek** [comment]
Create fork, push your branch there and then on the main page of the project (not fork this time) click green button with rotating arrows and dots "Compare, review, create a pull request". What you wanna do is create pull request.

**Comment by linc** [comment]
This has been fixed. Tested against 2.5 BBCode and it properly used `[img]` tags.
