### ISSUE TITLE
Translations hard coded 

### ISSUE THREAD

**Issue by BertrandD** [vanilla/vanilla#2639]
Hi there,
 There is an issue wich will be great to solve in js/count.js in the vanilla_assign_comment_counts_by_tag() function.

Indeed, this function does not support translation with the locales definitions. I've noticed this issue when I was trying to use vanilla as my comments manager in wordpress.

I have to translate these 3 vars in the js/count.js code : 

vanilla_comments_none
vanilla_comments_singular
vanilla_comments_plural

Thanks for all

**Comment by tburry** [comment]
This is something you translate yourself on the Wordpress side. That's why we provide you with those variables. Just define your translated versions of those variables above the script include and we'll use your definitions.
