### ISSUE TITLE
Long URLs truncated in notification emails

### ISSUE THREAD

**Issue by chrisvanrun** [vanilla/vanilla#2640]
Recently we had a few problems with the link in the email notification being ill parsed by most e-mail clients. It seems that a line ending was included right in the middle.

Long story short: I think I traced it down to the combination of a rare (+76 char) long URL in combination with the 'quoted-printable' encoding in the library/core/class.email.php.

`$this->PhpMailer->Encoding = 'quoted-printable';`

When commented or set to '8bit' (which is default in phpmailer) the problem was resolved.

**Before (quoted-printable):**
`John Doe commented on February Circle I - Monday=0A=0AFollow the link =
below to check it out:=0Ahttp://louisbonapartesociety.nl/forum/discussion/c=
omment/1753#Comment_1753=0A=0AHave a great day!`

**After (8bit):**
`Monkey Test commented on TESTING SERVICES
Follow the link below to check it out:
http://louisbonapartesociety.nl/forum/discussion/comment/1767#Comment_1767
Have a great day!`

**Comment by bleistivt** [comment]
related #2207

**Comment by beingmojo** [comment]
@chrisvanrun Thank you for reporting the fix for this bug.

**Comment by DaazKu** [comment]
Related: 
https://github.com/vanilla/vanilla/issues/3895
https://github.com/vanilla/vanilla/pull/4603

**Comment by DaazKu** [comment]
I did a test with the following message:
```
Monkey Test commented on TESTING SERVICES Follow the link below to check it out: http://vanilla.dev/discussion/30/test-mentions-aaaaaaa-bbbbbb-ccccccc-dddddd-eeeeee-ffffff-ggggggg#latest Have a great day!
```

No problem on Gmail, Outlook, mailinator...
Seems like updating PHPMailer fixed the problem!
