### ISSUE TITLE
Wordpress functions are always included

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#2654]
In [functions.general.php](https://github.com/vanilla/vanilla/blob/master/library/core/functions.general.php#L15) there is `include PATH_LIBRARY.'/vendors/wordpress/functions.wordpress.php';` but the functions defined in that file are not used anywhere in Vanilla.

I do not have any knowledge about Vanillas Wordpress integration so it might be needed for that otherwise it makes no sense to integrate this. If it is needed, I think it should be enclosed in something like `if embedded= true...`

**Comment by linc** [comment]
That entire file is no longer used to my knowledge.

**Comment by tburry** [comment]
Yeah we have to take this out.
