### ISSUE TITLE
A small issue when displaying a @mention and a small fix.

### ISSUE THREAD

**Issue by d1a8lo24** [vanilla/vanilla#2662]
I had a small issue displaying a @mention  
By the way I am using the Master/Latest version 2.2.x of vanilla with advance editor set with Wysiwyg since the other settings are still causing some problems when it comes to parsing information but that's another issue that I will try to resolve.

The small problem that I had was that when someone mention someone else and they submitted their comment or discussion any mention would display like so **@name ; ** adding a semicolon in front of the mention. Now I don't know if this is the way it suppose to be or is just a small bug. 

In my case I don't like the way it looks but anyway I found that when clicking enter or selecting the username of the person the **&nbsp;** was added right after an somehow when the data was posted and parse it left the semicolon while adding an empty space before it. 

Again I don't know if this a small bug or not but in my case I didn't like the way it looked so I took sometime to fix it and all I really had to do so that the data would parse correctly I made the small change on the following file.

File: jquery.atwho.js
Line: 666
Previous code: 
` content_node = "" + content + "&nbsp;";` 
Code change:
`content_node = "" + content + " &nbsp;";`

**Comment by linc** [comment]
It seems like this might be an encoding issue with your setup. I've never seen that happen or heard of it. Glad you found a workaround tho.
