### ISSUE TITLE
" vs ' usage in different parts oft the codebase

### ISSUE THREAD

**Issue by Tama63** [vanilla/vanilla#2663]
' Seems like the intended uniform standard.

**Comment by linc** [comment]
It really depends on context. We don't have a rule about this.

**Comment by Tama63** [comment]
@linc Such as https://github.com/vanilla/vanilla/blob/master/plugins/Quotes/class.quotes.plugin.php where it suddenly switches

**Comment by linc** [comment]
I don't think this is a problem.
