### ISSUE TITLE
YouTube timestamp parsing 't'

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2669]
Valid URL not supported: https://www.youtube.com/watch?t=40&v=ggMGDjqCFSA
This format doesn't support the preview image: https://www.youtube.com/watch?v=ggMGDjqCFSA#t=40

**Comment by LauraMakesArt** [comment]
Just noting that the second format does seem to load its preview image, at the moment.

**Comment by linc** [comment]
Supplanted by https://github.com/vanilla/vanilla/issues/4985
