### ISSUE TITLE
Can't Save Profile without Setting Birthday

### ISSUE THREAD

**Issue by shadowdare** [vanilla/vanilla#2675]
Since issue #2575 was merged, profile changes still can't be saved without setting the birthday field added via the Profile Extender plugin.

- Setting the birthday dropdown to "Month / Day / Year" will bring up the error "DateOfBirth is not a valid date"
- Also, on the dashboard page to add custom profile fields, you can add two birthday fields. If you add a second one, it will be have a label called "DateOfBirth" and a type of "DateOfBirth"

**Comment by linc** [comment]
Legit bug; shoulda filed this months ago, my bad.

**Comment by linc** [comment]
Waaaaait a minute: #2465 #1870

You're saying this is new behavior for your site?

**Comment by shadowdare** [comment]
Didn't see those issues.

I'm not sure if this behavior existed before the pull requests from #2575, but it certainly exists right now even after the changes from #2575.
