### ISSUE TITLE
SSL access inconsistencies

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2684]
- [ ] Canonical URL is not necessarily using https when accessed over https
- [ ] Share icon (which should be core) isn't using it either.
- [ ] Analytics loading in Dashboard is hard-coded to http
- [ ] Gravatars, avatars, and editor uploads can all use the wrong protocol at times.

**Comment by tburry** [comment]
See also #2656.

**Comment by slafleche** [comment]
The share icon are working correctly.

The Analytics calls to Vanilla change to the current protocol. However, the calls made by keen.js are always in https. I'm assuming that's ok?

Gravatars, avatars, and editor uploads are working correctly.

As for the Canonical urls, the tests I've done seem to all have the same protocol as the current url. I'm not really sure how to set it up so the Canonical url's on a different protocol as the page. @linc are there edge cases I'm missing here?

**Comment by linc** [comment]
It seems like `c('Garden.AllowSSL') || c('Garden.ForceSSL')` should force the canonical to https.

**Comment by slafleche** [comment]
In PR: https://github.com/vanilla/vanilla/pull/5609

**Comment by slafleche** [comment]
Reopening, since PR was no good.

**Comment by DaazKu** [comment]
This is kind of related to https://github.com/vanilla/vanilla/issues/2684
