### ISSUE TITLE
Banning's InsertUserID is the user being banned

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2709]
A user matching a Banning rule (e.g. IP address) gets an Activity record of type `Ban` that has an `InsertUserID` of their own UserID. We use this in other functionality as the origin of the ban which is nonsensical. Suggest we use the SystemUserID instead.

**Comment by tburry** [comment]
How about the InsertUserID of the first GDN_Ban record that ban's them?

**Comment by linc** [comment]
https://github.com/vanilla/vanilla/pull/2736
