### ISSUE TITLE
Suggestion: Making the debug option visible

### ISSUE THREAD

**Issue by xDaizu** [vanilla/vanilla#2744]
It may sound silly, but it took me a while to find out that I could add the line

    $Configuraton['Debug'] = TRUE;

to the conf/config.php file to see the debug info.

What about adding:

    $Configuraton['Debug'] = FALSE;

as default to the config.php file?

**Comment by linc** [comment]
It is in `conf/config-defaults.php` already, which is where we store preset values. The `config.php` file is for settings you have specifically done yourself.
