### ISSUE TITLE
StorageMethod column commented out

### ISSUE THREAD

**Issue by leith** [vanilla/vanilla#2748]
Why is the `StorageMethod` column commented out for the `GDN_Media` table?

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/settings/structure.php#L736

When running an import from [vanilla/porter](https://github.com/vanilla/porter), it expects that column to be there and fails the import.

**Comment by initvector** [comment]
This should be fixed with https://github.com/vanilla/vanilla/commit/4e9ff32cd42fe542feac89316c00f25f877a70d5 and https://github.com/vanilla/porter/commit/026357e3cfccb5a885d09b3823b8f1ace5b3a401
