### ISSUE TITLE
 posix_getpid error

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2749]
Getting the following error while running latest version of master: Fatal error: Call to undefined function posix_getpid() in /home/content/xxxx/applications/vanilla/models/class.categorymodel.php on line 206

**Comment by linc** [comment]
What operating system version?

**Comment by adrianspeyer** [comment]
Windows 7

**Comment by linc** [comment]
I believe #2668 was the fix for this but it was mysteriously closed.

**Comment by adrianspeyer** [comment]
Looks like the contributor closed it. Nice find :)

**Comment by adrianspeyer** [comment]
I should add, this leads to those on windows systems to get a 500 error, if they run master.

**Comment by initvector** [comment]
I do believe this was fixed by #2763

**Comment by adrianspeyer** [comment]
Yes it was, sorry I forgot to close this one :+1:
