### ISSUE TITLE
Hide post content overflow

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2754]
It would be better if Vanilla entirely blocked overflow text/tables/images from posts. Currently, it is possible for long unspaced text chains or `width="100%` properties on elements like `td` to overflow.

**Comment by linc** [comment]
@slafleche A thing to consider for the revamp.

**Comment by slafleche** [comment]
I already have something like that. All user content will be wrapped in a "userContent" class, which will protect ourselves from that type of problem.

**Comment by slafleche** [comment]
I also always put unreasonably long text where user content appears to make sure we properly ellipsis out long text.

**Comment by charrondev** [comment]
This should be resolved with the new default theme.

**Comment by charrondev** [comment]
Fixed in keystone
