### ISSUE TITLE
[Master] Server Error 500 on install

### ISSUE THREAD

**Issue by xDaizu** [vanilla/vanilla#2760]
The current master branch throws server error 500 on install. No more info since there isn't (or I can't find) an error log. Tables are created on database and, at least some of them, initialized.

**Comment by linc** [comment]
This is likely a configuration issue with your server. Please seek troubleshooting assistance on the forum at vanillaforums.org. Filing a technical issue requires a detailed, reproducible problem.

**Comment by xDaizu** [comment]
Of course, I've tried it in 3 very different enviroments before reporting (Windows 7 localhost, Ubuntu localhost, Unix remote server) and same error on the three of them only with the master branch (2.1 branch, 2.2.3.4 tag and 2.2.3.6 tag work). That's why I thought it was code-related.

I'll keep investigating and report my findings.

**Comment by adrianspeyer** [comment]
I assume you are using Windows. This is the issue I had with 500. This fix made it work for me: https://github.com/vanilla/vanilla/pull/2668

**Comment by xDaizu** [comment]
That *DID* work, thank you very much.
