### ISSUE TITLE
Getting started email sends to every recipient multiple times

### ISSUE THREAD

**Issue by hgtonight** [vanilla/vanilla#2761]
Getting started page email sending should be fixed that it won't send copies to every users what you add in list.
let's say that i add 4 email addresses to list
mail1@mail.com,mail2@mail.com,mail3@mail.com,mail4@mail.com 
evey email users will get 4 emails that you have invited user to sign up in your forums.

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/29932/getting-started-email-sending-should-be-fixed/p1

**Comment by hgtonight** [comment]
the `Gdn_Email::Send()` method doesn't reset the fields, so multiple recipients will be sent in the CC field. This results in the first recipient getting x copies of the invite with an incrementing number of CC addresses.

https://github.com/vanilla/vanilla/blob/4821cc6e6b43f632627c15496354db3b077eea95/applications/dashboard/controllers/class.settingscontroller.php#L1161-L1170

Confirmed on 2.1.10

**Comment by linc** [comment]
This feature has been removed.
