### ISSUE TITLE
GDN_AntiSpamLog and GDN_UserAuthenticationToken also can't be utf8mb4

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#2775]
I was testing converting my MySQL DB to `utf8mb4`, and the conversion was problematic for some tables that are not fixed by #2712:

GDN_AntiSpamLog
GDN_UserAuthenticationToken

I'm unsure if these are tables that are no longer used, or perhaps they were added by a plugin. But in either case, my naive let's-convert-all-the-tables method didn't work.

Perhaps these (and others) should get the #2712 treatment, if they exist? Or just dropped if they're no longer used?

**Comment by linc** [comment]
`AntiSpamLog` is not a Vanilla core table.

`UserAuthenticationToken` is still used.
