### ISSUE TITLE
Merging into a redirected discussion

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#2782]
The issue is that if you merge an existing thread with a moved thread, making the moved thread the main discussion, the secondary thread vanishes entirely.

**Steps to Recreate**
* Create a thread and name it, "Test Thread 1". 
* Create a thread and name it, "Test Thread 2". 
* Move the thread named "Test Thread 1" to another category and leave a redirect link. 
* In the original category, select "Test Thread 2" and the redirect link of the moved "Test Thread 1", then select "Merge". 
* Elect to Merge the two selected threads. Choose to make the redirect link of the moved "Test Thread 1" as the primary (or master) thread to merge the "Test Thread 2" (secondary) link into. 

**The result:** the secondary thread, "Test Thread 2" vanishes with any posts that it contained. 
**Expected result:** the secondary thread would be merged into the primary master thread. 
**Alternative expected result:** you can merge a redirect links and only actual threads can be merged.

**Comment by JulieVanilla** [comment]
Should have labels "bug" and "sprinted", but I'm apparently not cool enough to be able to add labels.

**Comment by tburry** [comment]
While it would be nice to have this behave as you want, it kind of irks me that you label this as a "bug". The shadow topic is prefixed with "Moved: " and any moderator with the ability to merge threads should know what that means.

This is an enhancement, plain and simple.

**Comment by JulieVanilla** [comment]
The reason I would use the bug label is because the entire contents of a secondary thread vanish when it's merged into a moved thread with the moved thread as the primary. The contents don't make it into the moved thread, nor does this give any indication that the merge has failed. That content is being unexpectedly removed is why this was presented to me as a bug.

The use-case here is that the moderator assumed that the content of the secondary thread would be merged with the moved thread, instead of having the content be essentially wiped out.
