### ISSUE TITLE
Google Plus plugin makes the login screen blank

### ISSUE THREAD

**Issue by 10by10pixel** [vanilla/vanilla#2789]
**VANILLA VERSION:** 2.1.10  
**PLUGIN VERSION:** Commit #2783  
**EXPECTED RESULT:** Allows user to sign in using a Google Plus button and/or form.  
**ISSUE:** Plugin makes all pages blank.  
**PHP error log:** `[01-Jun-2015 06:38:28 UTC] PHP Fatal error:  Call to undefined function SocialSignInButton() in /home/[user]/public_html/[forum]/plugins/GooglePlus/class.googleplus.plugin.php on line 150`

**Comment by linc** [comment]
That plugin requires 2.2 unfortunately and is mislabelled. You can _perhaps_ copy the function `SocialSignInButton` in `library/core/function.render.php` from the master copy of Vanilla back to your 2.1 installation to remedy this. I'm fixing the minimum version numbers here & 2.2 will go to beta very shortly.
