### ISSUE TITLE
No checkbox on Manage users page v2.1.20

### ISSUE THREAD

**Issue by Gwynwyffar** [vanilla/vanilla#2791]
There's no check box on the User's page to allow Admin to use the "With Checked Users" drop down.  This makes mass deletion of spam accounts exceedingly tedious.

**Comment by linc** [comment]
What dropdown are we talking about?

**Comment by Gwynwyffar** [comment]
On the Users administration page, there are no check boxes so that I can use the "With Checked Users" drop down to mass delete or approve. Upon review I see I am using the Bulk Edit plugin, so it may be an issue with that.
![users](https://cloud.githubusercontent.com/assets/6218173/7936629/901fa5bc-0908-11e5-8a45-ecf09567bf41.jpg)

**Comment by Gwynwyffar** [comment]
It was BulkEdit - updated to v. 1.3 and it's working fine, sorry for the mistake!

**Comment by linc** [comment]
No worries!
