### ISSUE TITLE
Open redirect in /entry endpoints & the TrustedDomains setting

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2800]
1. `EntryController::Target()` has an insecure default. It is an open redirect unless the `Garden.TrustedDomains` config setting is manually set by the admin.
2. `Garden.TrustedDomains` is in the Dashboard under `/embed/advanced` and its description only references its functionality in relation to embedding. Embedding has a similarly permissive default of "unset TrustedDomains means embed anywhere".
3. Our documentation for SSO does not encourage users to set `TrustedDomains`.
4. Changing the behavior of `Target()` to no longer be an open redirect by default (without each site adding their trusted domains) would break hundreds of SSO implementations.

How can we close this open redirect without breaking existing implementations the moment they upgrade?

**Comment by linc** [comment]
Here's my initial proposal:

* Add a step to setup that sets `TrustedDomains` to `false` (or the current domain) so new sites do not have this issue.
* Move `Garden.TrustedDomains` to the Advanced page in the Dashboard and correct its description to mention redirects.
* Add a utility/update method that detects the use of the Connect registration method or enabled embedding. If both are not in use, set `TrustedDomains` to `false` (or the current domain).
* If a side is using embed and/or Connect, add a Dashboard prompt for them to update their TrustedDomains setting.
* Add `TrustedDomains` to our SSO & embed documentation.

**Comment by linc** [comment]
Another solution we've discussed:

* `Redirect()` implement a "Leaving X Site" page that warns you when your Target site isn't on the `TrustedDomains` list.

This has the benefit of immediately providing security to all users at the cost of annoying every user & disrupting workflows until their admins figure out how to fix it (who will then be annoyed with us).

On the whole, I think this would be good, but should be phase 2. Let's give the admins a chance to update their settings and stem the tide of new issues being created before we intercept them all with an interstitial.

**Comment by linc** [comment]
Duplicates https://github.com/vanilla/vanilla/issues/2521 but I'll leave this one and close that one since I added more here.

> Proposed solution:
>
> * Add a Leaving method to the HomeController to serve as a redirect landing page. "You are now leaving {site}" to confirm the user's intent to leave the forum.
> * Add a SafeRedirect function which sanitizes redirects against a list of trusted domains, and sends them thru the new /home/leaving endpoint if it is not trusted.
> * Add a way of managing the list of trusted domains and/or URLs, and call them in a hookable way so that plugins like jsConnect can add its designated URLs on the fly.
> 
> Ability to accept wildcards in the domains / URLs and whether to specifically designate http vs https are design considerations.

**Comment by kaecyra** [comment]
@tburry please weigh in on this core change.

**Comment by tburry** [comment]
The various URLs in the Gdn_UserAuthenticationProvider table should also be considered trusted. An admin shouldn't have to go to two spots to configure them.

**Comment by tburry** [comment]
A few more thoughts:

1. You can add a touchConfig('Garden.TrustedDomains', true) right now to grandfather existing forums settings.
2. Then you'll be able to change the default.
3. The "you are leaving this page" is essential if we are tightening the security. We can't go back to redirects silently not working. This has caused more hours of investigation than a leaving page would ever take to program. It's just a page with a link that it gets from a URL parameter.
4. The various URLs in the Gdn_UserAuthenticationProvider table should also be considered trusted. An admin shouldn't have to go to two spots to configure them. (as per my previous comment).

Most important: **No silent failures.**

**Comment by tburry** [comment]
Also, how about we add a Logger::log(Logger::NOTICE...) call when a safeRedirect() is called and the site doesn't have trusted domains set up (trusted domains is set to true). The log should indicate whether or not the domain is in Gdn_UserAuthenticationProvider.
