### ISSUE TITLE
Font color processor may cause XSS vulnerability

### ISSUE THREAD

**Issue by phoenixlzx** [vanilla/vanilla#2807]
Credits to @RicterZ

Reproduce:

Submit the following code in any textarea that aware of font tag

```
<font color='#FF6699"onmouseover="alert(1)//'>test</font>
```

**Comment by phoenixlzx** [comment]
Verified by @RicterZ

This issue may cause XSS vulnerability.

**Comment by bleistivt** [comment]
I can confirm this. You should send this to support@vanillaforums.com
http://docs.vanillaforums.com/developers/

This is most likely a vulnerability in htmLawed or a misconfiguration
http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/

**Comment by bleistivt** [comment]
This also works here: http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawedTest.php

@tburry @linc

**Comment by phoenixlzx** [comment]
I've sent an Email to support@vanillaforums.com

**Comment by linc** [comment]
Thanks, I've reported this upstream to the Htmlawed creator. They are typically very responsive.
