### ISSUE TITLE
Formatting problems editing wysiwyg posts with Advanced Editor when ForceWysiwyg is enabled

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#2833]
When a post has a YouTube video embedded in it, and you attempt to edit the post, the video is replaced with

`<a rel="nofollow" target="_blank"><img width="640" alt="" height="385"></a>`

So once the post is saved, the video is removed and a broken image is inserted.  This means users with video posts can not edit their post without losing the video.

For example, the following post has an embedded YouTube video:  http://laurasothertest.vanillaforums.com/discussion/834/videotest?new=1

When going to edit the post you see a large blank image:  http://laurasothertest.vanillaforums.com/post/editdiscussion/834

and going to HTML view mode you see the video URL has been removed and a malformed image (no src defined) has been added and wrapped in an anchor tag that has no href defined.

**Comment by Exavior** [comment]
Any progress on this?  It's becoming a serious problem on our forum with a contest we are running.

**Comment by linc** [comment]
Bug manifests only when format is `Wysiwyg` and `Plugins.editor.ForceWysiwyg` is `true`. Causes `$body` to take a trip thru `Gdn_Format::wysiwyg()` which does magic formatting, resulting in an HTML output intended for viewing not editing.

**Comment by linc** [comment]
The desired functionality here is to convert non-HTML formatting into HTML formatting. Unfortunately, all our ways of doing that in Vanilla also roll in our "magic" link/emoticon/mention parsing which is very undesirable here.

One workaround to limit the impact of this bug would be to detect when a post is already in Html or Wysiwyg format and skip this code. Then, only true conversions from Markdown / BBCode / TextEx would be effected. The only easy way around this I see is to let those methods in Gdn_Format be passed a second parameter to optionally skip this step. Thoughts on this, @tburry?

**Comment by tburry** [comment]
Didn't you add another method to Gdn_Format to skip the auto-embedding, mentions, etc? Otherwise, I'd temporarily turn off those settings when converting to wysiwyg and then reset them. I think the conversion is just done on the edit endpoint.

**Comment by HardlyMirage** [comment]
Was this fixed? I'm seeing this in 1.7.2

**Comment by cirphrank** [comment]
3.2 and still unfixed.
