### ISSUE TITLE
Error with Vanilla 2.2b1 in the Frontend

### ISSUE THREAD

**Issue by AlexL777** [vanilla/vanilla#2853]
Hello developers,
I have just tried to install Vanilla 2.2b1, ie update my old installation Vanilla 2.1.11. The problem that came were errors in the frontend. See this mistake made so.

    Unknown column 't.FullName' in 'field list'
    The error occurred on or near: /www/htdocs/xxxxxxxx/cms/vanillaforum/library /database/class.database.php

    408:                 // If we get here then the pdo statement prepared properly.

    409:                 break;

    410: 

    411:             } catch (Gdn_UserException $uex) {

    412:                 trigger_error($uex->getMessage(), E_USER_ERROR);

    413:             } catch (Exception $ex) {

    414:                 list($state, $code, $message) = $PDO->errorInfo();

    415: 

    416:                 // If the error code is consistent with a disconnect, attempt to retry

Maybe you can look at it you times. Thank you in advance.

**Comment by linc** [comment]
Have you run /utility/update to get the new database structure?

**Comment by AlexL777** [comment]
In fact, and it was just because. I have now done it right again and lo and behold everything works. Thanks for the hint :)

**Comment by linc** [comment]
Sure thing! Thanks for checking out the beta.
