### ISSUE TITLE
Text box for leaving a comment disappearing when I leave a comment on a discussion using the source mode, as well as another issue

### ISSUE THREAD

**Issue by McDonalds1** [vanilla/vanilla#2866]
wikiHow recently upgraded it's version of Vanilla for it's <a href="http://forums.wikihow.com/">forum</a>. I like it a lot, but here are two issues that I noticed.

<img src="http://i.imgur.com/ss2jTYp.png"</img>

For the first issue, as noted above in the image, I left a comment on a discussion on that forum, and published it using the source mode. When I clicked the Post Comment button, it posted the comment as intended, but the text box for leaving a comment disappeared. I had to either click the button for the source mode, or refresh the page, to get it to appear again.

The second issue that I had is that in the comment editor (whatever that is called (it is not the source mode)), when I don't press Enter before I type some more text after quoting something, and then post a comment with it, it deletes what I typed, and therefore, I have to type it again.

**Comment by linc** [comment]
This is for the cleditor plugin, which is no longer supported. We recommend upgrading to Advanced Editor immediately.
