### ISSUE TITLE
Adding images with Advanced Editor not inserting into post

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2877]
Result of drag-and-dropping an image into a post with Editor:

<img width="762" alt="screen shot 2015-07-03 at 8 54 21 am" src="https://cloud.githubusercontent.com/assets/117672/8499740/c9b97532-2163-11e5-807e-8b95d17ba118.png">

"Progress" bar at top does not go away. Thumbnail says "inserted" but is not.

**Comment by hgtonight** [comment]
I can confirm this has happened to me as well.

**Comment by Danik** [comment]
I can also confirm this. It seems to work in WYSIWYG mode, but not in the other modes I have tried (BBcode and HTML).

**Comment by linc** [comment]
This has been resolved. Tested in 2.5.
