### ISSUE TITLE
Troll Management: Latest Post

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#2889]
When a user is marked as a troll, their posts still appear in the Latest Post section. This is a clickable link that goes through to the thread, where the content is visible even if the user is marked as a troll. It is NOT visible if a user navigates to that category, but you can get to it via Latest Post.

**Comment by linc** [comment]
This plugin is in the Addons repo. This is a valid concern that should get added to that repo (https://github.com/vanilla/addons/issues) but there's no simple way to take this into consideration without modifying the database structure to incorporate more data. If we never have a troll as the latest post, then it would be the troll who notices they AREN'T there. To do both scenarios, we'd need to modify the database structure. So this is more like a feature request than a bug.

**Comment by linc** [comment]
We can't fix this currently.
