### ISSUE TITLE
(2.2b1) Advanced Editor: after editing, smilies are gone

### ISSUE THREAD

**Issue by Dr-Sommer** [vanilla/vanilla#2892]
When you edit a post, the smilies are gone, showing just a placeholder with the smilie name.
It occures when you check the  "Reinterpret All Posts As Wysiwyg" in the Advanced editor settings.

Here is my post in the Vanilla comunity with images of this issue:
http://vanillaforums.org/discussion/30403/vanilla-2-2-b1-advanced-editor-questions-and-issues

ThX & greetz,

Dr. Sommer :grin:

**Comment by Clem01** [comment]
I have the same problem on version 2.2 !

**Comment by MarcThibeault** [comment]
Same on 2.2 on a fresh install.

**Comment by linc** [comment]
This is fixed in 2.5. I tested a BBCode -> Wysiwyg conversion on a single comment using our Editor with Emoji Extender.
