### ISSUE TITLE
Gdn_Plugin->Dispatch not working as expected

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#2905]
The method `dispatch` in **vanilla/library/core/class.plugin.php** takes two arguments, `$Sender` and `$RequestArgs`. However, apart from checking whether or not it is an array, the `$RequestArgs` argument is competely ignored.

I would expect the dispatch method to offer me the possibility to hand over some arguments to the dispatched method, e.g. by the `$RequestArgs` argument.

Also, what is the reason for having `$Sender->Form = new Gdn_Form();` in the `dispatch()`-method?

**Comment by bleistivt** [comment]
Noticed this too. Ideally it would splat the requestArguments, so that plugin controller methods could be used like real controller methods.

I would guess that the form is for convenience, because most real controllers initalize a form automatically using the $Uses property.
