### ISSUE TITLE
Incorrect path in javascript causes errors 

### ISSUE THREAD

**Issue by robi-bobi** [vanilla/vanilla#2911]
I tried to find similar issue here, but could not, so maybe it is something related to my plugins.
I tried to disable them one by one, with no luck.

When moderating posts javascript will try to send some data to server but to wrong URL.
Check on my screenshot that it goes to root folder of my domain instead of subfolder "/forum" where the vanilla is installed.

<img width="605" alt="screen shot 2015-07-30 at 12 11 51" src="https://cloud.githubusercontent.com/assets/230215/8979839/37ca545e-36b5-11e5-8a87-340753cc6503.png">

**Comment by mtschirs** [comment]
What is the value of the following entries in your conf/config.php?
$Configuration['Garden']['RewriteUrls']
$Configuration['Garden']['WebRoot']
$Configuration['Garden']['StripWebRoot']

**Comment by robi-bobi** [comment]
Thanks for replying.

I only had RewriteUrls:

```php
$Configuration['Garden']['RewriteUrls'] = TRUE;
```

I tried to guess what values for the other two would produce better outcome but with no luck.
Example:
```php
$Configuration['Garden']['WebRoot'] = 'http://www.microstock-bg.com/forum/';
$Configuration['Garden']['StripWebRoot'] = false;
```

**Comment by mtschirs** [comment]
Try
$Configuration['Garden']['WebRoot'] = 'forum';
$Configuration['Garden']['StripWebRoot'] = false;

**Comment by robi-bobi** [comment]
You are fast :)

yes, I just tried this one as I am reading http://vanillaforums.org/discussion/23867/issues-with-cakephp-and-vanillaforums-regarding-app-webroot
Same result.

Is config cached?

**Comment by robi-bobi** [comment]
Cleared /cache/ files, still the same.

I see that gdn.url() is used
Which is defined like this:

```javascript
gdn.url = function(path) {
      if (path.indexOf("//") >= 0)
         return path; // this is an absolute path.

      var urlFormat = gdn.definition("UrlFormat", "/{Path}");
      
      if (path.substr(0, 1) == "/")
         path = path.substr(1);

      if (urlFormat.indexOf("?") >= 0)
         path = path.replace("?", "&");

      return urlFormat.replace("{Path}", path);
   };
```

after some play with it, I saw that urlFormat is equal to "/{Path}" and will always result in returning leading forward slash as url.

So, I suppose I will have to somehow edit that variable to "/forum/{Path}" somehow, correct?

**Comment by robi-bobi** [comment]
I saw my old code in ther (I thought that I have removed it once upgraded).
So, here it is:
```javascript
   // Grab a definition from object in the page
   gdn.definition = function(definition, defaultVal, set) {
      if (defaultVal == null)
         defaultVal = definition;

      //MINE
      if (typeof definitions == 'undefined' ) {
         definitions = [];
      }
      //ENDMINE

      if(!(definition in definitions)) {
         return defaultVal;
      }

      if(set) {
         definitions[definition] = defaultVal;
      }

      return definitions[definition];
   }
```

If I comment my code, I receive following in console:
ReferenceError: definitions is not defined

I suppose this can lead us somewhere?
Hopefully not to a wrongly finished upgrade as the upgrade process is still one of the most non-fluent things in vanilla :)
(I did have some issues last time)

**Comment by mtschirs** [comment]
How about you upload a new clean install of Vanilla to your (staging) server, copy your config.php from your current installation and check if the problem persists?

**Comment by robi-bobi** [comment]
Thanks. Will try that.
