### ISSUE TITLE
Reported Posts shows in search

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#2912]
Posts that are reported posts, show in auto-suggest search. These should be filtered. You can see an example on vanillaforums.org

Search for "Adam Vinatieri"

![pasted_image_2015-07-30__9_11_am](https://cloud.githubusercontent.com/assets/425366/8983801/21b18b52-369b-11e5-9939-0f103e42babb.png)

The offending post has already been removed.

**Comment by linc** [comment]
The auto-suggest is permission-based. You can see it because you have access to that category.

**Comment by adrianspeyer** [comment]
Maybe it's an enhancement to include/exclude reported posts?

**Comment by adrianspeyer** [comment]
Should not be here. Nvrmind
