### ISSUE TITLE
Gateway Timeout in Dashboard using Import

### ISSUE THREAD

**Issue by garyblankenship** [vanilla/vanilla#2917]
I have a large export file generated with Vanilla Porter.  The file **models/class.importmodel.php** contains `set_time_limit(60 * 5);` in multiple places.  This prevents the import from completing.

```
PHP Fatal error:  Maximum execution time of 300 seconds exceeded in
/vanilla.dev/public/applications/dashboard/models/class.importmodel.php on line 1588
```

**Comment by linc** [comment]
How big is this import file exactly? I've never hit this limit after bringing in 30GB+ databases. Typically 5 minutes is already a longer time limit than most servers are set to accept. Have you tried increasing it to see how long it needs?

**Comment by garyblankenship** [comment]
It took about 8 minutes.  I'm developing in vagrant, on a 2GB VM, which may be related to why it took longer.  Still, removing the hard limit of 300s in that class fixed my issue and I was able to complete the import.

**Comment by linc** [comment]
I'd rather go with the narrower solution of increasing the timeout to 10 minutes than remove it entirely, since I'm pretty certain it will open up issues for users with different environment configurations if we strike it entirely.
