### ISSUE TITLE
Gdn_Database query error trapping assumes PDO generates every error message

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#2918]
if you reach the point of 

```
            } catch (Exception $ex) {
                list($state, $code, $message) = $PDO->errorInfo();

                // If the error code is consistent with a disconnect, attempt to retry
                if ($code == 2006 && $try < $tries) {
                    $this->closeConnection();
                    continue;
                }

                trigger_error($message, E_USER_ERROR);
            }
```

This assumes the error is something to do with PDO. I might not be. Therefore `$PDO->errorInfo();` will produce empty values, masking the actual error. 

reference:
http://vanillaforums.org/discussion/30516/email-confirmation-link-throws-a-fatal-error#latest

This Issue was generated from your [forums](http://vanillaforums.org/discussion/comment/232044#Comment_232044)

**Comment by x00** [comment]
https://github.com/vanilla/vanilla/blob/master/library/database/class.database.php#L413-L423

**Comment by charrondev** [comment]
Fixed by https://github.com/vanilla/vanilla/commit/a4543ce3edec1b7419946410b636a6516bc8f291
