### ISSUE TITLE
Make notification subject line configurable

### ISSUE THREAD

**Issue by wackydeli** [vanilla/vanilla#2920]
The subject line of notification emails should be customizable. Some of our users have suggested that they cannot see the thread headline in their email clients (presumably on narrow screens such as mobile phones) because the prefix (forum name) is too long and the rest gets cut off. 

First, the subject line is hardcoded to be prefixed with Garden.Title which is quite long in our case. It also controls the page headline so I do not want to change it. It would be great if there was a separate configurable field such as Garden.EmailSubjectPrefix which would initially be set to Garden.Title but can be changed. 

Ideally, I would change the order to 
  `[<Garden.EmailSubjectPrefix>] <activity headline>: new comment from <commenting user>`
but since this is probably not ideal for everyone I guess it would be best to allow customization of the subject line format. If this is done, the subject prefix would not have to be configurable separately as it could be directly put into the format string.

**Comment by linc** [comment]
The subject format is not hardcoded. Add a `locale.php` file to your `conf` folder with:

```
<?php
$Definitions['[%1$s] %2$s'] = ''[whatever] %2$s'';
```

Retooling the way activity and notifications are generated isn't on the near-term roadmap because it is a hugely complex system.
