### ISSUE TITLE
Image attachment dialog unnecessarily requires a file extension

### ISSUE THREAD

**Issue by primesuspect** [vanilla/vanilla#2925]
The image attachment dialog requires a file extension (.jpg, .gif, etc.) to trigger. Image sharing services such a Twitter or Google+ don't necessarily have file extensions, and Vanilla does honor image embedding without the file extension. Example:

https://lh3.googleusercontent.com/l_2hUDSC4JD8S2fFxikuR5UaoMoI0_bi2o3Z4PqbMs3B=w1698-h955-no

Is perfectly embeddable in a post, but the image URL dialog won't honor it until you put a .jpg or something on the end (which is actually an invalid URL).

**Comment by charrondev** [comment]
I've confirmed this is still an issue in the Rich Editor.

**Comment by charrondev** [comment]
As of the recent embed refactoring, Rich Editor external image embeds do not care about an extension. All that they care about is a mime-type.

The particular image linked in this picture though is not served with an image mime-type. The mime-type returned by the server is of HTML and the response is 404, when requested from HTTP client.

![image](https://user-images.githubusercontent.com/1770056/61432234-bc3fc980-a8fd-11e9-884a-dcdc6eeebda8.png)

![image](https://user-images.githubusercontent.com/1770056/61432387-5142c280-a8fe-11e9-9ad5-9c79b810f94d.png)

My best guess is that this server is using some type of user agent sniffing to detect what to serve, and does like our user agent.

We will not misrepresent our user agent though, so I'm afraid there is nothing that will make this image work. The latest version of master would work with different extension-less images though, as long as they report a proper mime-type.
