### ISSUE TITLE
Signin Popup - Missing translations

### ISSUE THREAD

**Issue by phreak** [vanilla/vanilla#2932]
~/applications/dashboard/views/entry/signin.php

Is missing terms that needs to be made translateable.

Line 25: echo $this->Form->label('Email/Username', 'Email');

Also the sign in methods don't seem to be translateable.
"Sign In with Facebook"
"Sign In with OpenID"
...

**Comment by linc** [comment]
The Label method translates.

The latter are covered by this code: 'Sign In with %s'

**Comment by phreak** [comment]
@linc: OK, can you help me... What is the "label method"?

**Comment by linc** [comment]
`Gdn_Form::label()` - What that first line is calling. Everything wrapped in `label( ... )` is, by definition, translatable, because that label call is running everything thru `t()`.
