### ISSUE TITLE
Change log can fail

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2946]
There are cases where the change log can fail to store an edit or deletion which should get investigated. The easiest way to replicate this is to delete a very very long comment or discussion. I suspect it is exceeding what can be stored in the log table and it just suppresses the issue and vaporizes the content.

**Comment by bleistivt** [comment]
Unlikely with the current structure. The Body field is `text` (64KB) while the Data field on the Log table is `mediumtext` (16MB). It should easily be able to store the row twice (old and new) + serialized.

**Comment by DaazKu** [comment]
Closing this PR in favor of tracking the issue on the PR https://github.com/vanilla/vanilla/pull/5797
