### ISSUE TITLE
"Read" & "Unread" classifications when not signed in.

### ISSUE THREAD

**Issue by cypherpunk** [vanilla/vanilla#2953]
I posted an issue in the userstyles.org forum where it was pointed out that this is a Vanilla problem, so I'll link it here: https://forum.userstyles.org/discussion/46669/styling-visited-threads-on-forum-userstyles-org-2

**Comment by bleistivt** [comment]
This has been fixed in 2.2, see #1846

**Comment by cypherpunk** [comment]
Thanks for the info. Apparently the admin is a few versions behind.
