### ISSUE TITLE
Refactoring Gdn_Form

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#2963]
Fixing the broken Gdn_Form is a good starting point for [incrementally refactoring the Garden framework](http://vanillaforums.org/discussion/comment/229856/#Comment_229856).

What is wrong with Gdn_Form?
- It tries to work around PHP's handling of external variables and fails.
- In doing so, it limits forms to represent flat key - value pairs only, no associative arrays or nested structures.
- Its abstraction (one form = one db table) is broken anyway.
- Its methods such as escapeID() are full of undocumented side-effects and error prone.
- It follows misleading naming conventions (e.g. isMyPostBack()).
- Has misleading doc blocs and comments.
- It is clustered with old, unused code fragments.
- Its coding style is outdated.

Related forum discussions:
- http://vanillaforums.org/discussion/30583/gdn-form-associative-arrays
- http://vanillaforums.org/discussion/comment/232478/#Comment_232478

**Comment by linc** [comment]
This is a very wide issue, much of which has been addressed. In addition to the referenced PR, we've moved to a separate schema layer and have continued to make many other improvements. If there are sections of this you feel should still be addressed with priority, please re-file a narrower issue. Thanks!
