### ISSUE TITLE
Deprecate global getRecord function

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2975]
It's insecure and dependent on non-framework applications.

**Comment by mtschirs** [comment]
getRecord() is used by the social plugins (Twitter, Facebook & Co). There have been a few discussions about this unfortunate dependency already [here](http://vanillaforums.org/discussion/comment/231805/#Comment_231805) and [here](https://github.com/austins/Vanilla-App-Articles/issues/34#issuecomment-75417580).

**Comment by linc** [comment]
The first step is to deprecate the function and remove references to it in core.
