### ISSUE TITLE
Editor should verify images using ImageUpload, not Upload

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2978]
Gdn_ImageUpload has its own image validation method. The editor however seems to perform all validation via Gdn_Upload and only later handle images with Gdn_ImageUpload, after
verification has already been done. As a result, the file type verification method of Gdn_ImageUpload is never called even if the uploaded file is an image.

Reported by @mtschirs

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.

Rich Editor uses the /api/v2/media API with much more rubust handling.
