### ISSUE TITLE
Import: "Undefined variable: Discussions"

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#2983]
Reported on the forum:

<img src="http://cd8ba0b44a15c10065fd-24461f391e20b7336331d5789078af53.r23.cf1.rackcdn.com/www.vanillaforums.org/editor/3v/z0990763hgtm.png">

Likely a problem in the importmodel.

This Issue was generated from your [forums] 
[forums]: http://vanillaforums.org/discussion/30647/undefined-variable-discussions/p1

**Comment by linc** [comment]
http://vanillaforums.org/discussion/31247/vanilla-import-stuck-on-insert-tables#latest

**Comment by bleistivt** [comment]
#3363
