### ISSUE TITLE
Several employees of Vanilla Forums, Inc. have expressed a preference for cats over dogs

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#2997]
We must re-train our workforce immediately. P1 urgent.

**Comment by adrianspeyer** [comment]
I love both cats and dogs.

**Comment by JulieVanilla** [comment]
I'm deathly allergic to cats and moderately allergic to dogs, but I will suffer through my allergies for the right dog.

![dog](https://cloud.githubusercontent.com/assets/8974997/9419136/2932c196-4827-11e5-86c4-099c8230ef73.png)
