### ISSUE TITLE
.htaccess issue in 2.2 

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#3002]
Running on Apache/2.4.12, and root works, but all sub-directories do not.

Leads to "no input file specified" issue on discussions and comments.

Please see discussion:
https://github.com/vanilla/vanilla/commit/3b3d5d4ba0863a0431d8b102b3fd71543ab6ae17#commitcomment-12598537

**Comment by linc** [comment]
We've narrowed this down to GoDaddy (and possibly other hosts) forcibly unsetting `PATH_INFO` despite having a correct CGI setup that should be setting it. Even manually setting `PATH_INFO` is disallowed; it gets spiked and passed as `ORIG_PATH_INFO` instead.

Workaround is going to be to set an `X_PATH_INFO` env variable and fallback to that when `PATH_INFO` is not found even when `X_REWRITE` is detected.

**Comment by adrianspeyer** [comment]
Almost there, but not yet.

**Comment by linc** [comment]
On @initvector's test GoDaddy account, we CAN successfully visit `index.php/discussion` and it creates the correct `PATH_INFO`. This is already further than we got on @adrianspeyer's account, which in itself is suspicious.

However, if you use `index.php?p=discussion` (which should immediately rewrite to `index.php/discussion` and go back thru `.htaccess`) it returns the familiar 'Input file not found.' (GoDaddy's 404 screen). This is where we're currently stuck.

**Comment by adrianspeyer** [comment]
Another question, and wonder if this is related. This commit: https://github.com/vanilla/vanilla/commit/94422e1d737b2fea041aa5904df306f60b8d782d leads to an issue with GDN not found.
