### ISSUE TITLE
Social authentication error

### ISSUE THREAD

**Issue by btafoya** [vanilla/vanilla#3012]
The redirect back to vanilla from Facebook and Twitter is failing due to a path issue...

404 Not Found

The requested URL /index.php//entry/connect/facebook was not found on this server.

Notice the two forward slashes. Any suggestions?

**Comment by btafoya** [comment]
I made a pull request several days ago to deal with this issue but was not merged.

https://github.com/vanilla/vanilla/pull/3005

**Comment by bleistivt** [comment]
> I made a pull request several days ago to deal with this issue but was not merged.

You closed it.
