### ISSUE TITLE
Could not find file 'plugins/Flagging/design/flagging.css' in folder 'vanilla'.

### ISSUE THREAD

**Issue by btafoya** [vanilla/vanilla#3015]
While viewing the demo thread..

http://{site}discussion/1/bam-you-ve-got-a-sweet-forum#latest

Debug Trace shows:
Info    Could not find file 'plugins/Flagging/design/flagging.css' in folder 'vanilla'.

Git Master source.

**Comment by mtschirs** [comment]
Might be related to http://vanillaforums.org/discussion/comment/232071#Comment_232071

**Comment by Data66Tech** [comment]
Thanks, this worked for 2.3 stable for me.
