### ISSUE TITLE
Fatal Error: MessageModel::getMessagesForLocation()

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3016]
PHP Fatal error:  Call to protected method MessageModel::inCategory() from context '' in /var/www/win/promforum/applications/dashboard/models/class.messagemodel.php on line 184

Might really be an issue that needs to be fixed in Vanilla. Line 183-185 of class.messagemodel.php:

```
$Result = array_filter($Result, function ($Message) use ($CategoryID) {
            return MessageModel::inCategory($CategoryID, val('CategoryID', $Message), val('IncludeSubcategories', $Message));
        });
```

The closure no longer has access to private or protected members of MessageModel. A solution could be http://au.php.net/manual/en/closure.bind.php or, as @JoosBuijs suggested, make MessageModel::inCategory() public.

See also http://stackoverflow.com/questions/6644288/using-self-in-an-anonymous-callback for a similar issue.

This Issue was generated from your [forums](http://vanillaforums.org/discussion/comment/233274#Comment_233274)

**Comment by linc** [comment]
Unclear if this was resolved, but our minimum requirements moved to 5.6.
