### ISSUE TITLE
AssetModel_StyleCss equivalent for JavaScript?

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#3020]
It always seemed weird to me that there is no general event for JS file inclusion like there is for CSS.

If there is no reason for this, I'd be glad to add it.

**Comment by linc** [comment]
@kaecyra weren't you doing something with this in preparation for asset minification? Can you remind me?

**Comment by charrondev** [comment]
The `AssetModel` while not deprecated will have no further active work. For current practices see [vanilla's build process](https://docs.vanillaforums.com/developer/tools/building-frontend/) and `WebpackAssetProvider`
