### ISSUE TITLE
New Instagram layout makes our embed look bad

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3026]
Widescreen layout now exists, which our embed doesn't allow for. Example to test: https://instagram.com/p/65PhxOs_RH/

**Comment by phreak** [comment]
Do you mean that general embedding of images and videos (through editor and so on) should acknowledge the general width of a comment list item to look more contemporary. I would 2nd that.

<li class="Item ItemComment" id="Comment_41770">...</li>

**Comment by linc** [comment]
This appears to have been fixed prior to 2.5.
