### ISSUE TITLE
Remove unused Javascript

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3034]
* I can't see vanilla/js/upgrade.js referenced anywhere in the source. Also, vanilla/js/settings.js is empty and could be removed from the SettingsController. What is or was their purpose? Can they be removed?

* js/queue.js is also unused. Can it be removed or - if an applications requires it - moved to that application?

* js/library/json2.js is only needed for EasyXDM which already has js/easyXDM/json2.js. Can it be removed? There is already an alternative JSON implementation via jQuery.parseJSON.

**Comment by linc** [comment]
I believe these are all accurate assessments.
