### ISSUE TITLE
Disentangle Global and Application-Dependend JavaScript

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3036]
The global "js"-folder contains all sorts of JavaScript for the dashboard and vanilla application even though these applications already add their own JavaScript files from their respective "application/xyz/js"-folder. Disentangling this mess is a precondition for further improvements in JavaScript handling.

**js/global.js (exemplary excerpts):**
- Belongs to the dashboard application (from line 175):

```
// Go to notifications if clicking on a user's notification count
$('li.UserNotifications a span').click(function() {
        document.location = gdn.url('/profile/notifications');
        return false;
});
```
- Belongs to the dashboard application (from line 982):

```
$.ajax({
    type: "POST",
    url: gdn.url('dashboard/notifications/inform'),
```
- Belongs to the dashboard application (from line 1114):

```
// Hide/Reveal the "forgot your password" form if the ForgotPassword button is clicked.
$(document).delegate('a.ForgotPassword', 'click', function() {
        // Make sure we have both forms
        if ($('#Form_User_SignIn').length) {
```
- Belongs to the vanilla application (from line 1358):

```
var autosizeTriggers = [
        'clearCommentForm',
        'EditCommentFormLoaded',
        'popupReveal'
        //'appendHtml'
];
```
- Belongs to the dashboard application (from line 1505):

```
// Produce the suggestions based on data either
// cached or retrieved.
if (filter_more && !empty_query && !gdn.atcache[query]) {
        $.getJSON(gdn.url('/user/tagsearch'), {
```

**Belong to the dashboard application:**
- js/vanilla.embed.js
- js/vanilla.embed.local.js

**Beong to the vanilla application:**
- js/embed_local.js
- js/embed.js

**Comment by linc** [comment]
Breaking up / refactoring the global.js file is a great goal. That thing is a mess.

**Comment by linc** [comment]
This will be accomplished in 2.6 by overhauling the front end. We don't plan a refactor of the existing code due to deep compatibility issues.
