### ISSUE TITLE
SliceProvider (core) has dependency on Dashboard (application)

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3037]
Gdn_SliceProvider (core) has a dependency on dashboard/design/slice.css (application):

Line 34 in _library/class.sliceprovider.php_: `$Sender->addCssFile('/applications/dashboard/design/slice.css');`

Better move it to resources/design? Btw: Why is there a global "js"-folder, but not a global "design"-folder? Wouldn't it be better to have all global css/js either under "resources" or directly in the root directory?

**Comment by bleistivt** [comment]
I suspect this could be removed altogether, unless it is used internally,.
I've never seen it being used anywhere and it hasn't been changed since the first commit.

You'll see this kind of dependency on Dashboard in a lot of places though, e.g. Gdn references UserModel and UserMetaModel.
https://github.com/vanilla/vanilla/blob/master/library/core/class.gdn.php

They can be overridden however.

**Comment by mtschirs** [comment]
Gdn_SliceProvider is used muliple times by the dashboard application via:
`Gdn::slice('/dashboard/role/defaultroleswarning');`

Further inspection reveals that role/defaultroleswarning actually does nothing (since Vanilla 2.0):
```
    public function defaultRolesWarning() {
        // Do nothing (for now).
    }
```

The only legitimate (?) use of "Slices" is within "/dashboard/authentication/", where the slice automatically refreshes to display configuration options based on your authenticator choice.

However, the only authenticator I ever encountered was "Password" and the only return value for that one is "The Password Authenticator does not have any custom configuration options."

**Comment by linc** [comment]
Interested in @kaecyra's input on this. I think the Slice mechanism was his addition and it's possible he's using it elsewhere.

**Comment by kaecyra** [comment]
Slices should probably be deprecated, we've got other ideas for how to achieve that kind of effect now, and Slices haven't got docs or much testing behind them anyway. Good candidate to be refactored away.

**Comment by linc** [comment]
Slices are going away. I've added a deprecated notice.

**Comment by linc** [comment]
Slices are gone.
