### ISSUE TITLE
Controller::renderData() uses a blacklist that could leak privileged data

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3044]
Vanilla allows to retrieve the raw values stored in Contoller->Data by setting the DeliveryType to "DATA" (e.g. by appending "?DeliveryType=DATA" to any URL leading to a controller method).

However, Controller->Data can contain sensitive information that would normally not be shown through a view. Therefore, the Controller::renderData() method tries to filter out all kinds of possibly sensitive data:

```
$CleanOutut = c('Api.Clean', true);
if ($CleanOutut) {
        // Remove values that should not be transmitted via api
        $Remove = array('Password', 'HashMethod', 'TransientKey', 'Permissions', 'Attributes', 'AccessToken');

        // Remove PersonalInfo values for unprivileged requests.
        if (!Gdn::session()->checkPermission('Garden.Moderation.Manage')) {
                $Remove[] = 'InsertIPAddress';
                $Remove[] = 'UpdateIPAddress';
                $Remove[] = 'LastIPAddress';
                $Remove[] = 'AllIPAddresses';
                $Remove[] = 'Fingerprint';
                if (C('Api.Clean.Email', true)) {
                        $Remove[] = 'Email';
                }
                $Remove[] = 'DateOfBirth';
                $Remove[] = 'Preferences';
                $Remove[] = 'Banned';
                $Remove[] = 'Admin';
                $Remove[] = 'Confirmed';
                $Remove[] = 'Verified';
                $Remove[] = 'DiscoveryText';
                $Remove[] = 'InviteUserID';
                $Remove[] = 'DateSetInvitations';
                $Remove[] = 'CountInvitations';
                $Remove[] = 'CountNotifications';
                $Remove[] = 'CountBookmarks';
                $Remove[] = 'CountDrafts';
                $Remove[] = 'HourOffset';
                $Remove[] = 'Gender';
                $Remove[] = 'Punished';
                $Remove[] = 'Troll';
        }
        $Data = removeKeysFromNestedArray($Data, $Remove);
}
```

This approach has serious problems leading to real security issues:
- Gdn_Controller has a dependency on all applications and plugins (e.g. it has a filter for "Troll" which is used by the Troll plugin or "CountBookmarks" which is used by the Vanilla application)
- It is impossible to predict and filter out all possibly sensitive data, especially from 3rd party applications.

A complete overhaul is necessary. It is probably an illusion to think that all 'leaks' in this data sieve can be fixed by adding new filters to the core. Since the DATA-DeliveryType is mainly (?) used by Vanilla's proprietary vfapi plugin, your input is required.

**Comment by linc** [comment]
We're well aware of this deficiency. I suspect that reworking this mechanism will be part of our near-term roadmap work as part of much-needed API improvements.

**Comment by charrondev** [comment]
While this can't really be closed at the moment, I'm quite sure nothing new APIv2 and later uses `Gdn_Controller`, or even has a `DeliveryType=DATA`.
