### ISSUE TITLE
Remove Garden.Charset (permanently set it to UTF-8)

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3047]
**Proposal: Remove Garden.Charset as a config option**

Why? Let's set Garden.Charset to something else than _UTF-8_, e.g. _UTF-16_ and see what our website looks like:

ℼ佄呃偙⁅瑨汭ാ格浴⁬慬杮∽敤•汣獡㵳猢楴正⵹潦瑯牥栭浴≬ാ㰉敨摡ാउ洼瑥⁡档牡敳㵴產晴㠭㸢ऍ㰉敭慴渠浡㵥瘢敩灷牯≴挠湯整瑮∽楷瑤㵨敤楶散眭摩桴‬湩瑩慩⵬捳污㵥∱ാउ琼瑩敬䄾瑲歩汥ⴠ丠桩潡䌠楨慮...

How to fix that?

We could manually convert all Smarty output to _UTF-16_:

```
Gdn_Smarty::init() {
    ...
    // Add an output filter converting to UTF-16:
    function convertEncoding($TemplateOutput, &$Smarty) {
        return iconv('UTF-8', 'UTF-16', $TemplateOutput);
    }
    $Smarty->register_outputfilter("convertEncoding");
}
```

However, we now have a ton of JavaScript errors à la "SyntaxError: illegal character".

We can fix that, too, by overriding the charset of the script files:

```
<script charset="utf-8" src="global.js"></script>
```

Converting all our resources to _UTF-16_ instead would cause Smarty & Co. to go berserk, so this is probably the cleaner approach.

But we are not done yet! Just from browsing the Vanilla codebase, it is obvious that everything else but _UTF-8_ causes all kinds of encoding issues:
- bootstrap-theme
  `default.master.tpl: <meta charset="utf-8">`
- dashboard
  admin.master.php: `<?xml version="1.0" encoding="utf-8"?>`
  atom.master: `<?xml version="1.0" encoding="utf-8"?>`
  ...
- library/core
  class.form.php: `htmlentities($Value, ENT_COMPAT, 'UTF-8')`
  class.format.php: `htmlspecialchars($Mixed, ENT_NOQUOTES, 'UTF-8')`
  functions.error.php: `safeHeader('Content-Type: text/html; charset=utf-8')`
  functions.validation.php: `mb_strlen($value, 'UTF-8')`
  ...
- smarty
  `htmlspecialchars($string)`
  ...

This small example serves to show that, even if we manually replace all _UTF-8_ occurences with c('Garden.Charset'), we would still end up in an encoding mess as exemplarily demonstrated by Smarty and the JavaScript issues. Also, we might overlook some of the more exotic XSS vectors.

**To conclude:** Setting Garden.Charset to anything else but _UTF-8_ is very risky. Fixing that would require a whole lot of code modifications and testing. Therefore, removing Garden.Charset from the configuration is probably the best approach.

Also, Garden.LocaleCodeset must always be set to the equivalent of Garden.Charset:

```
$Configuration['Garden']['Charset'] = 'UTF-8';
$Configuration['Garden']['LocaleCodeset'] = 'UTF8';
```

Therefore, if Garden.Charset is removed from the config and set to be _UTF-8_, Garden.LocaleCodeset should also be removed and set to _UTF8_.

**Comment by linc** [comment]
@JasonBarnabe This has no effect on your `utf8mb4` MySQL use, correct?

**Comment by JasonBarnabe** [comment]
As long as this isn't doing anything relating to the DB (connection or table charset) then it shouldn't affect anything. `utf8mb4` *is* UTF-8, after all.

**Comment by linc** [comment]
Roger, just wanted to confirm since it gave me a moment of pause.

**Comment by tburry** [comment]
Cool. Let's move the charset into a constant. For the locale I'd just make a convenience function that converts a character set to a code set by removing dashes or something like that.

**Comment by linc** [comment]
Garden.Charset is only respected by PHPMailer now.

**Comment by DaazKu** [comment]
There is also another reference left in https://github.com/vanilla/vanilla/blob/8fd084cc3a8c0e1fc43ddd2a5ea8230109b017fa/library/core/class.form.php#L2985
