### ISSUE TITLE
Gdn_Controller (core) has dependency on AssetModel (dashboard)

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3048]
Gdn_Controller::xRender() calls AssetModel::getCssFiles() which then includes "dashboard/style/style.css"

Possible solution: AssetModel should become part of the core; getCssFiles() should not automatically include dashboard CSS; CSS from dashboard/style/style.css not exclusively belonging to the dashboard application should be moved elsewhere.

This issue is part of a series clearing the road to better asset handling.

**Comment by linc** [comment]
I think it would be reasonable for AssetModel to move to core.

The Vanilla app's CSS is included in the Dashboard for legacy reasons. It was causing a serious resource loading issue to load both the Dashboard + Vanilla style sheets on every pageload, plus it was more confusing to have multiple style sheets for themers to look for. I suspect we'll need to get to a new base theme (which is itself blocked by a child/parent theme feature to preserve backwards compatibility for existing themes) before we're able to decouple those again. Bit of a rabbit hole.

**Comment by charrondev** [comment]
The `AssetModel` is has been renamed to `Vanilla\Web\Asset\LegacyAssetModel`. It is now in core and is no longer the way we load assets.

Assets are now primarily loaded through `WebpackAssetProvider` and are pre-build using the build process [described in the docs](https://docs.vanillaforums.com/developer/tools/building-frontend/)
