### ISSUE TITLE
Unread status on discussions list should change onclick

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3056]
We recently removed a `no-store` cache header, which had a significant side effect: Now clicking the "Back" browser button will give you a discussion home without an updated read/unread for whatever thread you were just viewing. The previous behavior was that the page would refresh; now it does not. This "broken" behavior was actually desirable because it simplified navigation.

The easiest solution would be to add an onclick handler that updates the discussion list status to switch the CSS from unread to read, and remove the `X new` element. This would keep the correct cache strategy by "fixing" the page before navigating away from the page so it is in the correct state when you return via "Back".

**Comment by linc** [comment]
hat tip to @erobbins for the useful suggestion while the rest of my users were just kvetching. :laughing:

**Comment by bleistivt** [comment]
Noticed this too.

Quick idea: Adding a second class would allow you to highlight the topic you just came from for a short time (e.g. using a fade effect). Discourse does this and I find it also makes navigation easier.

**Comment by initvector** [comment]
Implementing the suggested fix doesn't work for me, at least in Chrome.  The browser seems to be caching what it receives from the server, but not any changes to the document between when the link is clicked and the next page is loaded.

The following JavaScript, tested with the +Baseline theme, will make the appropriate updates to a row in the discussion list. They are noticeably made when the link is clicked.  However, once the discussion page loads and the back button is clicked, the changes are lost.  The page appears as it did on initial load.

```js
$('.DataList.Discussions .Unread.ItemDiscussion .Title a').click(function (event) {
    var discussionRow = $(event.target).closest('.Unread.ItemDiscussion');

    if (discussionRow.length) {
        $(discussionRow).removeClass('Unread');
        $(discussionRow).find('.HasNew.NewCommentCount').addClass('JustNew').empty();
    }
});
```

**Comment by linc** [comment]
Re-adding this header to the Discussions & Category controllers would be an appropriate fix. Those pages typically don't have form data associated with them, and even if they did in some special circumstance, the tradeoff here seems well worth it.
