### ISSUE TITLE
Plugins referenced in core

### ISSUE THREAD

**Issue by mtschirs** [vanilla/vanilla#3069]
There have been made changes to core components to accomodate plugin needs. Event handlers or other means of loose coupling should be used instead.

**Examples:**
- applications/dashboard/modules/class.headmodule.php

```
            // Include facebook open-graph meta information.
            if ($FbAppID = c('Plugins.Facebook.ApplicationID')) {
                $this->addTag('meta', array('property' => 'fb:app_id', 'content' => $FbAppID));
            }
```
- library vendors/SmartyPlugins

```
function smarty_function_pocket($Params, $Smarty) {
   if (!class_exists('PocketsPlugin'))
      return '';
```

**Comment by linc** [comment]
These are reasonable accommodations for important addons that cannot do the designated tasks with hooks. I don't think these need to be modified at this time.
