### ISSUE TITLE
Category Sort/Parenting (UI vs Manual)

### ISSUE THREAD

**Issue by FerusGrim** [vanilla/vanilla#3076]
I've created an [animated gif](https://cloud.githubusercontent.com/assets/5481250/9826876/5226619a-58ab-11e5-9605-79460cc7e2b3.gif) to attempt to explain the problem that I'm encountering.

![in-line](https://cloud.githubusercontent.com/assets/5481250/9826876/5226619a-58ab-11e5-9605-79460cc7e2b3.gif)

Essentially, I cannot move elements up or down in the order. I can move them side-to-side, which means that I can re-organize children with a bit of hassle, but nothing else.

Is this a bug, intended, or a problem with my installation?

Is there a way to manually sort categories? I've looked but haven't found this feature.

**Comment by FerusGrim** [comment]
Thankfully, one of our developers solved this rather annoying issue.

The version of Vanilla that we came with jQuery 1.7 (or _something_, he says).

I'm not sure in which version this issue is solved, but it was resolved when we manually updated to version 1.11.x (latest).

**Comment by linc** [comment]
This is resolved with the new Dashboard landing shortly.
