### ISSUE TITLE
Add notifications for Moderation/Spam Queue

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#3082]
Option for Administrative roles to receive email notifications when items are sent to moderation.

//EDIT:

Version 1 of this task will be to create two new permission'd notifications:

* `Preferences.Email.ModerationQueue`
* `Preferences.Email.SpamQueue`

It will use the GroupBy / rollup functionality on the ActivityModel to keep multiple actions in the same day together. The notification will not include specifics, but rather be a generic message that there are new items in the X queue. It will track users opted in in the same manner as Advanced Notifications. 

No flood control would be included - if you have a high volume to queue traffic, you can obviously just check more frequently rather than waiting for an email if it's happening that often.

Version 2 of this feature would be:

* Set a per-user flag when a notification for X queue is set.
* Do not send notifications for X queue while the flag is set.
* Unset the flag when the user visits the queue.

This is beyond the scope of this task, because we'd like to make this core functionality to the ActivityModel when we revamp how notifications are handled.

**Comment by DaazKu** [comment]
For that feature to make sense, especially for spam, I would probably do:

- A per user config in advanced notifications that would only appear / be effective if you have Garden.Moderation.Manage or Moderation.ModerationQueue.Manage
- These notifications would have a minimum interval that can be set in either minutes, hours, or days. That way you won't get spammed by emails if you have 60 notifications in a short internal. This will be especially handy for the spam queue.

**Comment by adrianspeyer** [comment]
My main thing: As someone who gets a lot of notifications from his users about things that need to be moderated, I would love a solution where you are notified by email the first time a new discussion/comment gets added to the moderation queue since you were last logged in (active). This way you know you have something to review and you don't get an email for every new one.

**Comment by DaazKu** [comment]
The "since last logged" part is tricky that's why I'm leaning toward a minimum delay (internal) between notifications.

**Comment by linc** [comment]
I've added the tentative scope above for a version 1 of this after speaking with Todd. We're tabling this for the short term.
