### ISSUE TITLE
Custom ProfileExtender fields in registration form not saving 

### ISSUE THREAD

**Issue by bryanjamesmiller** [vanilla/vanilla#3105]
After adding customized ProfileExtender fields that display during registration, those fields do not get saved and the user is forced to re-enter the same profile information on their profile page after logging in.

**Comment by linc** [comment]
You're using the Applicant registration method, right?

**Comment by bryanjamesmiller** [comment]
I just realized this issue is for 2.0.17.9 and everything works fine on 2.2.100.8.  Now I just have to figure out how to upgrade from 2.0.17.9 to 2.2.100.8

**Comment by bryanjamesmiller** [comment]
The reason why we're using this version of Vanilla is because it comes pre-installed on GoDaddy's servers...

**Comment by linc** [comment]
Wow 2.0.17 really? That's so bad. :-/

**Comment by bryanjamesmiller** [comment]
@linc Maybe you could re-open this issue.  You might want to check out this thread: http://vanillaforums.org/discussion/comment/234016#Comment_234016 (you probably have seen it already).  Apparently there are some server configurations that prevent ProfileExtender from saving its custom fields that were filled out during registration.  One of those server configurations is GoDaddy's default settings.  I've successfully upgraded to 2.1.11 and I'm still having this issue.  However, I believe I got it working on Digital Ocean, but I also need to use GoDaddy.  I think there may be some 755 settings on GoDaddy that need to be turned to 777, but I'm not sure which.

**Comment by bryanjamesmiller** [comment]
@linc Here's a fix that worked for me https://github.com/vanilla/vanilla/pull/3120 thanks to @peregrine
