### ISSUE TITLE
Add `seamless` attribute to <iframe> for embedded comments

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3113]
@danemacmillan filed internally many moons ago:

The support for `seamless` is somewhat limited, having recently been added to Chrome, available in Opera15+, Safari6+, not yet supported in Firefox, and no word on IE. This attribute allows CSS to cascade into the iframe content body, which would make theming of embedded comments very easy for site owners, and making embedded comments more useful due to ease of integration. Content is still sandboxed, so it's as safe as not having the `seamless` attribute.

I think it would be a good idea to start including it in the embed code. Browsers that don't support it will ignore the attribute.

If this makes it into core, and a fallback would want to be implemented, a solution is to find the CSS in window.parent, which in most cases would point to the main site with its pertinent styling. Maybe describe in docs for site owners that they can include an optional vanilla-embed.css file in their head and it will be included in the `iframe` dynamically, or just include all their CSS in the `iframe` without the need for looking for a specific file.

**Comment by bleistivt** [comment]
https://caniuse.com/#search=seamless

This attribute has been dropped from the spec. Can probably be closed.
