### ISSUE TITLE
Replace data-vocabulary microdata with Schema

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3116]
Another courtesy of @danemacmillan: 

In at least one location, e.g., the breadcrumbs, the microdata format being used, data-vocabulary, is deprecated in favour of Schema.

http://www.data-vocabulary.org/
http://schema.org/

**Comment by charrondev** [comment]
We'll be doing JSON-ld instead https://github.com/vanilla/vanilla/issues/6590
