### ISSUE TITLE
Upgrade reCAPTCHA

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3117]
Filed by @adrianspeyer:

Got email from Google that the Recaptcha on our site is getting old.

"You're receiving this email because you're registered as a website administrator for a site that uses reCAPTCHA.
Google launched reCAPTCHA v2 (i.e. No CAPTCHA reCAPTCHA) in Dec, 2014. The new version provides a more simplified user experience than reCAPTCHA v1, with an enhanced spam fighting mechanism. "

They are probably heading to deprecation. Here is the dev guide for the new version

https://developers.google.com/recaptcha/intro

Here is an open source plugin that does it too:
http://vanillaforums.org/addon/nocaptcharecaptcha-plugin

**Comment by najimi** [comment]
Any updates on this? According to [this thread](http://vanillaforums.org/discussion/30546/no-captcha-recaptcha-0-1-6b-breaks-registration-of-v-2-2), the plugin mentioned here doesn't work with 2.2 which is an issue now that 2.2 is stable. 

Gotta say that I'm glad you guys already had this on the list.

**Comment by linc** [comment]
Not yet, but this is definitely on our radar for the near term. We'd love to get this in ASAP.

**Comment by x00** [comment]
I may do a PR time permitting. it is backward compatable anyway. You can only get new accounts anyway so it is depreciated.

**Comment by x00** [comment]
https://github.com/vanilla/vanilla/pull/3417

**Comment by Rias500** [comment]
Any update on this?

**Comment by linc** [comment]
This was completed.
