### ISSUE TITLE
"Social" Dashboard page spacing got misaligned

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3124]
Connection names are no longer correctly aligned.

<img width="496" alt="screen shot 2015-09-23 at 11 11 37 am" src="https://cloud.githubusercontent.com/assets/117672/10049576/21ce9dca-61e6-11e5-8702-b387b266bcd5.png">

**Comment by adrianspeyer** [comment]
I checked on Chrome and Firefox, and seems to work. Please confirm it's working for you.
