### ISSUE TITLE
Hard-coded non-secure links to ajax.googleapis.com

### ISSUE THREAD

**Issue by alastc** [vanilla/vanilla#3131]
Hi,

I was having trouble with the JSconnect plugin working, I would get a blank screen when selecting the login.
NB: The site is run under SSL/HTTPS

I narrowed it down to the links to http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
Because that is not over a secure connection it wouldn't load, jQuery was missing, and nothing happened!

To fix it I edited two files: 
library/core/class.controller.php (line 1735)
library/vendors/Minify/builder/index.php (line 120)

I'm not sure if I needed to edit both, but the fix is non-destructive.

I changed the link to:
//ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js

If you leave off the "http" it defaults to which-ever the site is using, HTTP or HTTPS.

Could that be applied in core please?

Secondarily it would be nice if the image http://cdn.vanillaforums.com/images/usericon_50.png were available over HTTPS, that triggers a mix-content warning but doesn't break things.

**Comment by linc** [comment]
That'd be an appropriate fix for the Google CDN, yes.

**Comment by iStefo** [comment]
+1!

Temporary fix is to edit the `config.php` and insert the line

```php
$Configuration['Garden']['Cdns']['Disable'] = TRUE;
```

which will use the local version of jQuery (1.7.2 in my case) which will be loaded using the same protocol as the main page.

**Comment by linc** [comment]
This now uses the `//` protocol to allow either mode to work.
