### ISSUE TITLE
`NameUnique = false` breaks login & password reset prompts / inputs and 'Send a Message' links

### ISSUE THREAD

**Issue by clementbirkle** [vanilla/vanilla#3151]
Hello,

Since the activation of $Configuration['Garden']['Registration']['NameUnique'] = '0';
I recognized several problems:

1) New password request: 
The field should not be "e-mail / username" but ONLY "e-mail" because otherwise the password is re-initialized for different users who has the same username.

2) New message (private discussion):
The link of "send a message" to a user from his detailed page is: /messages/add/{username}
If there are multiple users with the same username, it will be confusing. Rather, it should be based on an id, such as: /messages/add/id-{userId} or just /messages/add/{userId}

3) Login:
The login should ONLY be done via an E-MAIL address and not a username for a security question (If multiple users with the same username and the same password).

Thank you for your attention.

**Comment by Clem01** [comment]
4) Same problem with the quotes that are based not on surnames and not on ids. : /
