### ISSUE TITLE
Quote author breaks on name change or NameUnique = false

### ISSUE THREAD

**Issue by Clem01** [vanilla/vanilla#3152]
Currently quotes with Vanilla Editor 2.2 is based on usernames.

If a user change username, quote (link) no longer work...

Why not rather be based on the user id?

Example: @{userId}::{username}

It would also be more functional with the setting: $Configuration['Garden']['Registration']['NameUnique'] = '0';

**Comment by linc** [comment]
We do not plan to support this.
