### ISSUE TITLE
Planned: Move ButtonBar out of vanilla/vanilla and into vanilla/addons

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#3156]
This plugin is now deprecated and should be superseded by `editor`. Since `editor` is now core, `ButtonBar` can move out of core without leaving the product editorless. 

`vanilla/addons` is open source, so this does not take ButtonBar away from those who still want to use and possibly contribute to it.

**Comment by charrondev** [comment]
Closing for https://app.zenhub.com/workspace/o/vanilla/vanilla/issues/7880
