### ISSUE TITLE
Forum breaks in PHP 7.0

### ISSUE THREAD

**Issue by IanSzot** [vanilla/vanilla#3163]
Vanilla Forums breaks in PHP version 7.0

```
[05-Oct-2015 02:22:48 UTC] PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /srv/users/serverpilot/apps/dusty/public/forum/library/core/functions.general.php on line 813
```
The pages won't even load, just a plain white page. Still working fine if downgrade to 5.6

**Comment by kaecyra** [comment]
Thanks Ian,

We haven't started testing PHP 7 compatibility yet, but this is good initial feedback. I have been reading articles about the breaking changes they've made, and they should be fairly easy to resolve.

**Comment by kaecyra** [comment]
Out of curiosity, what version were you running when you encountered this error?

**Comment by IanSzot** [comment]
PHP: 7.0RC3
Forum: 2.1.10

**Comment by kaecyra** [comment]
A more helpful version to run, if you're going to be testing unsupported platforms, is our github master. 

2.1.10 may not end up being PHP7 compatible, and we'd make changes in master first and backport them anyway, if it was going to be supported.

**Comment by tburry** [comment]
I back-ported a fix in 4468ae15eecb2f9b9d77a908565a471f70c997be, however @kaecyra's comment stands. We are currently putting PHP7 development effort into the 2.2.* version of Vanilla.

**Comment by jimaek** [comment]
I am curious, now that 2.2 is released is it PHP7 compatible?

**Comment by linc** [comment]
No, but I expect 2.3 will be.

**Comment by jimaek** [comment]
Thank you
