### ISSUE TITLE
Double @@ formatting issues

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#3172]
Double @@ will not properly render in a code block. 

![image](https://cloud.githubusercontent.com/assets/7501633/10316936/7c2cae74-6c27-11e5-9461-824495862eef.png)
![image](https://cloud.githubusercontent.com/assets/7501633/10316968/9ed8adc4-6c27-11e5-9d86-25482645bd5f.png)

http://laurasothertest.vanillaforums.com/discussion/867/code-block?new=1

**Comment by linc** [comment]
This is fixed in 2.5.
