### ISSUE TITLE
Editor: Cannot create a new line in editor after inserting code

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#3173]
Creating a code block using Advanced Editor essentially traps the end of the post in the code block when viewing as WYSIWYG.  To resolve this, you need to edit in HTML View and add elements after the code block.
### Steps to recreate
1. Create a new comment.
2. Add a code block (under the Format button).
3. Type some body in the code block.
4. Attempt to move the cursor past the code block to continue editing the post.

**Comment by linc** [comment]
This is fixed in 2.5.
