### ISSUE TITLE
Counters not incremented and media files not associated with administrator account

### ISSUE THREAD

**Issue by GO3LIN** [vanilla/vanilla#3192]
Hello, I am testing the version 2.2b1 of vanilla forum and I am facing a problem this days: When I create a new discussion with an account that have the admin role, and then approve it in the moderation queue. The discussion appears in the forum but the counters for its corresponding category are not incremented. Also, when I add a discussion with an attached file, it actually doesn't link it to the discussion in the database, the ForeignTable and ForeignID are set to NULL. But when I try with a member role account, the discussion doesn't need to be approved and the counters and files are working correctly. So I think that there's a problem in the approval system that doesn't trigger the incrementation of the counters and the files linking. I am still investigating to fix that issue and hope you can help me.

**Comment by linc** [comment]
I believe this moderation queue issue has been resolved in 2.5.
