### ISSUE TITLE
vanillicon.css is part of core

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#3193]
Even if the plugin Vanillicon is not activated, the css is loaded on several places (even by the editor plugin): https://github.com/vanilla/vanilla/search?p=2&q=vanillicon.css&type=Code&utf8=%E2%9C%93

The css should be part of the plugin, not the core and adding the css of a plugin should be done by the plugin itself and not by some controllers initialize method.

**Comment by linc** [comment]
I actually wanna do the opposite and put Vanillicon & Gravatar into core as part of the new "Avatars" menu in the Dashboard.

**Comment by R-J** [comment]
I have taken a closer look at the vanillicon.css and have seen that it loads an extended Font Awesome which isn't connected at all to the Vanillicons plugin. So I was just irritated by the identical naming.
