### ISSUE TITLE
Implement local fallback for jQuery jquery.min.js

### ISSUE THREAD

**Issue by oliveratgithub** [vanilla/vanilla#3194]
When developing locally and not having a working Internet connection, Vanilla breaks because the Google hosted jQuery library cannot be loaded.

A local copy of jquery.min.js should be present as a fallback if the external resource cannot be accessed.

**Comment by kaecyra** [comment]
It is present, there is a config setting to disable jQuery loading from CDN.




`Garden.Cdns.Disable`



Tim Gunter
Vice President, Operations
Vanilla Forums
https://vanillaforums.com

**Comment by kaecyra** [comment]
It is present, there is a config setting to disable jQuery loading from CDN.

```
$Configuration['Garden']['Cdns']['Disable'] = true;
```

**Comment by oliveratgithub** [comment]
Oh sweet, didn't even check *facepalm*

**Comment by oliveratgithub** [comment]
Oh, applying this setting actually gives me a 404 error in Vanilla 2.1 beta 1:
`$Configuration['Garden']['Cdns']['Disable'] = true;`

> Failed to load resource: the server responded with a status of 404 (Not Found)
/js/library/jquery-1.10.2.min.map

**Comment by bleistivt** [comment]
This has been fixed, `Garden.Cdns.Disable` works.

**Comment by oliveratgithub** [comment]
I trust in you and therefore finally close this issue 😊
