### ISSUE TITLE
Vanilla 2.1.12 now requires PHP 5.5

### ISSUE THREAD

**Issue by hgtonight** [vanilla/vanilla#3200]
From commit cb8f05af02cb7e913a74d7212ff7572793b95e8e

In `applications/dashboard/controllers/class.utilitycontroller.php` line 195. `empty()` prior to 5.5 requires a variable. http://php.net/manual/en/function.empty.php.

**Comment by kaecyra** [comment]
Either way that's a pretty opaque line of code that should be refactored into something more readable.

**Comment by hgtonight** [comment]
There is also a call to array_column that I missed. Fatal error: Call to undefined function array_column() in /applications/dashboard/controllers/class.utilitycontroller.php on line 344.

I have one final patch incoming.
