### ISSUE TITLE
Special usernames conflict with profile methods

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#3209]
While the profile of a user is called with `/profile/username`, other methods of the profile controller are called like that: `/profile/[discussions|comments|activity|picture|preferences|edit]/username`.
If a user chooses a username from the above list, all other users will immediately not be able to see the normal output of those functions. If for example a user registers himself as "preferences", all users will not be able to change their preferences anymore, because `/profile/preferences` then will be interpreted as a link to a certain userprofile.

I can think of two ways to solve this: one would be a quick and dirty blacklist for valid user names (with the added value that no malicious users can name themself "Administrator" if that name is not already taken) and the other way would be to change the profile controllers way of parsing parameters e.g. so that the first parameter is always the username.

I would favor `/profile/@username` for user profiles since that seems the least obtrusive. That way all the other profile methods could just stay the same.

I'm not sure how non unique names are handled, but I would like to see them like that `/profile/@username.userID`

**Comment by linc** [comment]
A blacklist has been implemented for now.
