### ISSUE TITLE
Not filtering UTF-8 characters disallowed in XML

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3218]
We should clean up our output when generating XML to ensure the error `Char 0x0 out of allowed range` (or whatever character) is never generated by XML readers.

See: http://stackoverflow.com/questions/3466035/how-to-skip-invalid-characters-in-xml-file-using-php

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/7727
