### ISSUE TITLE
"Class Gdn not found" is a really poor error message for broken Cache files

### ISSUE THREAD

**Issue by oliveratgithub** [vanilla/vanilla#3220]
I was really confused by reading "Class Gdn not found" on my dev environment and only by content searching through all Vanilla files, I found that it relates only to broken Cache files - as it says in bootstrap.php:

```php
// Guard against broken cache files
if (!class_exists('Gdn')) {
    // Throwing an exception here would result in a white screen for the user.
    // This error usually indicates the .ini files in /cache are out of date and should be deleted.
    exit("Class Gdn not found.");
}
```

Why not make this more clear and change the exit-message to something like...

```php
exit("Class Gdn not found. Try removing all .ini files in your /cache directory.");
```

...to make this error way easier to understand - and fix?

**Comment by linc** [comment]
See https://github.com/vanilla/vanilla/pull/2288

**Comment by oliveratgithub** [comment]
Closing this thread, same issue is already being discussed as #2288
