### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by DamianSheldon** [vanilla/vanilla#3221]
What's wrong with this?
![screen shot 2015-10-24 at 20 50 58](https://cloud.githubusercontent.com/assets/7088985/10710533/fed89f8c-7a90-11e5-9451-cfcfe51a1a12.png)

**Comment by linc** [comment]
Check your PHP error log and start a discussion on the community forum for troubleshooting help.

I recommend using the 2.2 rc1 over the master branch version.
