### ISSUE TITLE
Can we auto-delete ini files if they're broken?

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3231]
Re: new discussion on #2288, would it be feasible to auto-delete the `/cache/*.ini` files when class Gdn isn't found, then re-test to see if that fixed the issue? It feels like the danger of getting stuck in a loop of dropping those files is incredibly low, versus the high recurrence we see of folks ending up with outdated ini files.

**Comment by tburry** [comment]
I think this can be closed now. The `Gdn` object is now auto-loaded via composer.
