### ISSUE TITLE
Vanilla Master version and Updates

### ISSUE THREAD

**Issue by JamesMercury** [vanilla/vanilla#3232]
Vanilla released a new update about a week ago, majorly a security patch.
Would this and future updates be compatible with the Master 2.2 Vanilla installation required to use Vanilla-api by Kasper?
Thanks.

**Comment by linc** [comment]
Vanilla 2.2 is currently in release candidate stage, and is on the `release/2.2` branch, not `master`. All security work done to 2.1 is likewise being fixed in both those branches.
