### ISSUE TITLE
500 error Can't use method return value in write context in 2.2rc1

### ISSUE THREAD

**Issue by artygrand** [vanilla/vanilla#3238]
PHP Fatal error: Can't use method return value in write context in /applications/dashboard/controllers/class.utilitycontroller.php on line 299

    $step = !empty($this->Form->getFormValue('Scan')) ? 'scan' : (!empty($this->Form->getFormValue('Run')) ? 'run' : 'start');

**Comment by linc** [comment]
Thanks for the report. I have cherry-picked this commit to the 2.2 release to fix this: https://github.com/vanilla/vanilla/commit/7fe2c792f4fcddcf12c8b114f9c725d8fad1c1ed
