### ISSUE TITLE
no input file specified on subdirectories. Version 2.2

### ISSUE THREAD

**Issue by btafoya** [vanilla/vanilla#3239]
I see there are a couple of existing bug reports, but no solutions. I hit this problem when I uploaded a fully functional site from my dev environment (non-cgi) to a virtualmin hosted server (cgi) and was unable to resolve this error. Any help would be greatly appreciated.

**Comment by btafoya** [comment]
Adding a little logic resolved the issue...

index.php
...
if(!isset($_SERVER['PATH_INFO']) && isset($_SERVER['REQUEST_URI'])) {
    $_SERVER['PATH_INFO'] = $_SERVER['REQUEST_URI'];
}
...

**Comment by btafoya** [comment]
Ok, after a ton of experimenting I found the re-write rule was the issue...

I changed...
```
RewriteRule ^(.*)$ index.php/$1 [QSA,E=X_REWRITE:1,L]
```
to
```
RewriteRule ^(.*)$ index.php?/$1 [QSA,E=X_REWRITE:1,L]
```

And it no longer gives us the 'no input file specified' error, but the action still lands you on the home page instead of requested action. Still investigating.

**Comment by btafoya** [comment]
Any help here??? Devs.. it obviously worked prior to version 2.2 so any thoughts to refactoring the request class to function once again?

I have a vmware environment set up with virtualmin running php as fast-cgi as well as a mod-php environment and am debugging in tandem.

**Comment by linc** [comment]
Use 2.2rc1, not the GitHub `master` branch. Your host doesn't properly implement `PATH_INFO`. We're working on a solution for 2.3. In the meantime you won't be able to use the latest `master` version.

**Comment by btafoya** [comment]
OK, gotcha. Thanks!
