### ISSUE TITLE
Cannot merge posts: canEdit method missing from class.discussionmodel.php

### ISSUE THREAD

**Issue by grahammills** [vanilla/vanilla#3240]
Commit 85801a19acc3fdc6c98a7e77104e4b9db9372a1e file plugins/SplitMerge/class.splitmerge.plugin.php refers to DiscussionModel::canEdit which seems to be missing from class.discussionmodel.php

**Comment by linc** [comment]
This is in 2.1.13?

**Comment by grahammills** [comment]
Yes as downloaded from http://vanillaforums.org/discussion/31046/vanilla-2-1-13-security-updates

**Comment by grahammills** [comment]
Looks like the canEdit method is available in the 2.2 branch but not 2.1

**Comment by linc** [comment]
Thanks!

**Comment by linc** [comment]
I've released 2.1.13p1 to address this.
