### ISSUE TITLE
Class Gdn not found with "new" Autoloader file in Version 2.2.1011

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#3255]
Running into an issue with https://github.com/vanilla/vanilla/commit/94422e1d737b2fea041aa5904df306f60b8d782d, which removes  " the remaining references to Gdn_Autoloader::CONTEXT_CORE". Maybe this is somehow tangentially, related to https://github.com/vanilla/vanilla/issues/3002 and our .htaccess issues? 

If I revert to earlier version it works(https://github.com/vanilla/vanilla/commit/9701f00e4da9cd55d1af3d54dfaa52dc5fe178bf). I also cleared cache, so I do not believe this is related to other reported issues with the cache (i.e https://github.com/vanilla/vanilla/pull/2288) and the "Class GDN not found" error.

**Comment by linc** [comment]
http://vanillaforums.org/discussion/31083/vanilla-now-uses-composer
