### ISSUE TITLE
Banned e-mail domains do not seem to be checked when changing an e-mail address

### ISSUE THREAD

**Issue by mpkossen** [vanilla/vanilla#3265]
If someone has registered an account using an e-mail address with a domain that is _not_ in the ban list and then changes the account e-mail address to one with a domain that _is_ in the ban list, there is no error or notification that the new e-mail address domain is not allowed/banned and the e-mail address is changed.

Eventually this results in the account being banned automatically. In my view, though, it should not be able for people to change their e-mail address to one with a banned domain.

**Comment by linc** [comment]
Fair point.
