### ISSUE TITLE
Vanilla Comments login leads to copy of site loading in frame

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#3277]
When using Vanilla Comments, if you are not logged in, once you do, you will be sent to copy of the current site in the iframe.

![image](https://cloud.githubusercontent.com/assets/425366/11127894/91290a2c-8944-11e5-9198-79309c2a23b4.png)

Issue both in Chrome & Firefox with hosted and self-hosted version of Vanilla using the WordPress plugin.

**Comment by linc** [comment]
"self-hosted version" = 2.1.13p1?

**Comment by adrianspeyer** [comment]
@linc 2.2

**Comment by gilvaz** [comment]
@adrianspeyer same issue here.. Did you manage to fix it?

**Comment by adrianspeyer** [comment]
@gilvaz. Nope

**Comment by gilvaz** [comment]
I temporarily disabled the login popup as a workaround adding the following to conf/config.php:

$Configuration['Garden']['SignIn']['Popup'] = FALSE;

**Comment by linc** [comment]
I believe that's the correct fix, and why that setting was added.

**Comment by adrianspeyer** [comment]
Interesting, it seems that unticking "Use popups for sign in pages." does not do anything in the advanced settings for comments. Manually adding it, though does work.

**Comment by adrianspeyer** [comment]
Maybe the default setting should be pop-ups disabled if comments enabled?

**Comment by linc** [comment]
That or at least some warning in the Dashboard about those settings conflicting when you toggle one and not the other.
