### ISSUE TITLE
Bookmarks count archived discussions

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3297]
Currently, the Bookmark counter counts archived discussions. This is problematic as the bookmark page does not display the archived discussions, which can lead to an incorrect count of bookmarked discussions. Further, the pagination seems based on this count, so even if only five bookmarked discussions are displayed, if there are another 50 bookmarked discussions that are archived, pagination will allow for enough pages to display the total of 55 bookmarked discussions.

**Expected behaviour:**
- Bookmark counter ignores archived discussions
- Pagination on bookmark page ignores archived discussions

**Comment by charrondev** [comment]
Merging into duplicate issue https://github.com/vanilla/vanilla/issues/2894
