### ISSUE TITLE
Typo in entry.js, line 51 - #ConectPassword should be #ConnectPassword

### ISSUE THREAD

**Issue by battaglia01** [vanilla/vanilla#3322]
The code block in question is this:

`        if (gdn.definition('NoConnectName', false)) {`
`            $('#ConectPassword').show();`
`            return;`
`        }`

I assume it should be #ConnectPassword. I have no idea what this bug does, but it certainly does something.

What is the protocol here? Are we supposed to open a new hotfix/ branch for this and submit a new PR?

**Comment by linc** [comment]
Nice find. Yes, exactly, and reference this issue in the description.

**Comment by linc** [comment]
Closed by #3325
