### ISSUE TITLE
Quoting a post with TextEx produces null result

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3329]
This happens when desktop is using BBCode and mobile is using TextEx. The conversion doesn't appear to be happening correctly.

**Comment by JulieVanilla** [comment]
Same with WYSIWYG and Markdown.

**Comment by DaazKu** [comment]
Nothing wrong with WYSIWYG and Markdown...

**Comment by DaazKu** [comment]
TextEx was broken all together.
