### ISSUE TITLE
Banner localization

### ISSUE THREAD

**Issue by auguster** [vanilla/vanilla#3333]
It would be nice to add something to make the banner easy to localize (it could use the setting of "Multilingual" plugin).

Here is the discussion on the forum about it: http://vanillaforums.org/discussion/31125/change-banners-language

So far, localization and custom localization of the content (title, banner, categories, ...) of the forum is still an issue. So far the only solution seem to be editing the core code of the forum. This approach is hardly maintainable and is prone to security issue.

**Comment by linc** [comment]
This is supplanted by #4202 which contains a more general strategy for how we want to approach this.
