### ISSUE TITLE
Editor: Code lost when toggling between WYSIWYG and HTML

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#3335]
When toggling "HTML View" in the Advanced Editor, markup is often lost.
### Steps to recreate
1. Set "Post Format" to WYSIWYG in Advanced Editor settings
2. Create a new discussion.
3. Toggle HTML View.
4. Enter `<font color="blue">Hello world.</font>`
5. Toggle back to WYSIWYG.
6. Toggle again to HTML View.

[Screen Capture](http://screencast.com/t/weoo4dco)

_This may be intended behavior.  The WYSIWYG formatter may only be accepting a limited set of markup tags_

**Comment by linc** [comment]
We don't allow `font` tags, so this loss seems acceptable.
