### ISSUE TITLE
Editor: Sometimes attributes are removed

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#3336]
Some markup element attributes are not properly represented when saving.
### Steps to recreate
1. Set "Post Format" to WYSIWYG in Advanced Editor settings
2. Create a new discussion.
3. Toggle HTML View.
4. Enter the following:
   
   ``` html
   <table border="10px" bordercolor="#336699" width="300px">
      <tr>
          <td bgcolor="yellow">Test</td>
              <td>12345</td>
              <td><font color="#336633">Text color</font></td>
      </tr>
   </table>
   ```
5. Post the discussion.
6. Look at the source code of the table.

_This may be intended behavior. The HTML formatter may only be accepting a limited set of element attributes._

**Comment by linc** [comment]
Those are all disallowed attributes in HtmLawed anyway, as far as I recall, so I don't think this is an issue to pursue.
