### ISSUE TITLE
Editor: Cannot add text between back-to-back quotes

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#3337]
When posting a comment containing two back-to-back quotes, you cannot add text between them.
### Steps to recreate
1. Enable the Quotes plug-in
2. Create a discussion
3. Add new comment, quoting the original discussion twice (just click Quote on the discussion, twice).
4. Try to click between the two quotes to add text.

[Screen Capture](http://screencast.com/t/XwiFYkITfN)

**Comment by linc** [comment]
I can do this in 2.5 using Wysiwyg by opening an extra third quote between 2 existing ones, then toggling the "Quote" format off on the middle one.
