### ISSUE TITLE
Tab action from text box inconsistent

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3344]
On discussions, hitting tab (from comment box) will take you to the Add Comment button, so you can type your comment, hit tab and enter, done. In private messages, hitting tab takes you to the Markdown (or whichever format) link instead of send message.

**Comment by ntravis** [comment]
Also, if you edit a comment, hitting tab from the comment results first in going to the box for adding a new comment. Hitting tab again takes from you from the "new comment" box back to the Save Comment button for the edit.

**Comment by ntravis** [comment]
Following up:
[addmessage.php#L32](https://github.com/vanilla/vanilla/blob/master/applications/conversations/views/messages/addmessage.php#L32) needs tab index 1
[addmessage.php#L34](https://github.com/vanilla/vanilla/blob/master/applications/conversations/views/messages/addmessage.php#L32) needs tab index 2

to correct the original problem.

The second issue: The [editcomment.php](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/views/post/editcomment.php) would need to alter the tab index of the parent using JS(?) upon opening to make the tabindex of the "normal" comment box at the bottom equal to 3 and the Add Comment equal to 4. editcomment.php is already making its own comment tabindex=1 and save=2, but the browser is making the original take precedence AFAIK. Hitting save comment could restore the original state of the normal comment box and Add Comment button on exit. If you wanted to avoid hardcoding, you could bring in tabindex value of the original box, set the editcomment to that, then set original box to tabindex+2, and similarly for the Save comment vs Add Comment buttons.
