### ISSUE TITLE
Yaga causes permission denied message after upgrade from 2.1.10 to 2.2

### ISSUE THREAD

**Issue by RodSloan** [vanilla/vanilla#3351]
I upgraded from 2.1.10 to 2.2. When I tried logging in, I recieved "Sorry, permission denied" messages. When I turned the yaga application off (version 1.0.3) in config.php I was able to log in.

New users (added after the update) were able to log in without any problems.

(This is my first bug report, I hope I've covered everything. More info on a related Stack Exchange question: http://stackoverflow.com/questions/33941866/what-might-cause-vanilla-forums-permission-changes-after-an-update)

**Comment by linc** [comment]
Please report problems with third-party plugins using the community forum. Use the "Ask a Question" button here: http://vanillaforums.org/addon/yaga-application
