### ISSUE TITLE
Editor: Quotes behaving erratically in drafts (WYSIWYG)

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3352]
Quotes are sometimes not created properly in WYSIWYG mode.

Steps:
- Quote multiple posts on page 1 of a thread
- Save draft (because else the quotes are not stored if changing pages)
- Switch to page 2
- cursor jumps back to first line of draft, next quote (upon clicking) is placed within another quote if you don't pay attention
- ctrl+z changes to quickly remove the wrongly positioned quote
- move cursor to bottom of saved draft
- try to quote again

In this case, the quote sometimes just won't be generated, you have to either re-start the whole procedure by removing saved text and starting with an empty text box or put the quote together yourself by using and altering the respective html formatting.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
