### ISSUE TITLE
Why font-style: oblique instead of italic?

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#3355]
Since [the beginning of time](https://github.com/vanilla/vanilla/blob/474d00d3dadb287ae0b3ca4da2177745c32c4c3e/applications/vanilla/design/vanilla.screen.css#L393), `em` has had `font-style: oblique`. As I understand it, oblique is merely a rotated version of the font, while italic is specifically designed with different letter shapes. While I'm not yet enough of a typography nerd to complain about this, it appears as though `font-style: oblique` [doesn't always work on Cnrome](https://greasyfork.org/forum/discussion/comment/19588/#Comment_19588).

So I suggest switching it back to the browser-default `font-style: italic`. This will actually [fall back to oblique if italic isn't available](https://developer.mozilla.org/en/docs/Web/CSS/font-style).

**Comment by charrondev** [comment]
Fixed in keystone.
