### ISSUE TITLE
RISKY! Confirmed role deletion 

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#3356]
Yikes! I go into a bit of pickle uploading a client. 

See this
https://github.com/vanilla/vanilla/blob/master/applications/dashboard/settings/structure.php#L107-L121

``` php
// Modify all users with ConfirmEmail role to be unconfirmed
if ($UserExists && !$ConfirmedExists) {
    $ConfirmEmail = c('Garden.Registration.ConfirmEmail', false);
    $ConfirmEmailRoleID = RoleModel::getDefaultRoles(RoleModel::TYPE_UNCONFIRMED);
    if ($ConfirmEmail && !empty($ConfirmEmailRoleID)) {
        // Select unconfirmed users
        $Users = Gdn::sql()->select('UserID')->from('UserRole')->where('RoleID', $ConfirmEmailRoleID)->get();
        $UserIDs = array();
        while ($User = $Users->nextRow(DATASET_TYPE_ARRAY)) {
            $UserIDs[] = $User['UserID'];
        }

        // Update
        Gdn::sql()->update('User')->set('Confirmed', 0)->whereIn('UserID', $UserIDs)->put();
        Gdn::sql()->delete('UserRole', array('RoleID' => $ConfirmEmailRoleID, 'UserID' => $UserIDs));
    }
}
```

There is a perfect storm of possible issues. Originally member role is 4 and default role is 8 at least according to this

https://github.com/vanilla/vanilla/blob/master/conf/config-defaults.php#L59

However it might not be, it might be 8.  In fact that is what you are doing here

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/settings/structure.php#L53

I not sure at what point it became 8, but it could be any number anyway. Another role could also be 8. 

If it is 8 you are in serious trouble. **I ended up with 50K users with no role at all.**

Obviously I had a backup. However I needed to update anyway

So I used this query. 

`INSERT INTO GDN_UserRole (UserID, RoleID) select ur.UserID, 8 from GDN_User ur LEFT JOIN GDN_UserRole r ON r.UserID=ur.UserID WHERE r.UserID IS NULL;`

I figured out that the users without role were exclusively members. Which might not be the case, which would be even more messy. 

I suggest this this type of pruning is too risky. Maybe they could be another way such as an update with a redundant negative id or something.

**Comment by linc** [comment]
I think this was resolved long ago with the introduction of default role types. We do not go by ID when evaluating this anymore, so I don't think this is a problem now.
