### ISSUE TITLE
Send emails notifications by cron jobs

### ISSUE THREAD

**Issue by clementbirkle** [vanilla/vanilla#3368]
In Vanilla 2.2, if you have a discussion with 500 subscribers by email (extreme case).
When adding a comment, 500 emails are sent at once !! (apparently)
I propose to send segmented by cron jobs.

**Comment by linc** [comment]
How would you propose a PHP application install a cron? And how will that work on Windows?

**Comment by Clem01** [comment]
I think something like phpBB.
Linux = cron jobs
Windows & other: When a visitor visits the forum: <img src="/execute/cron" style="display:none;" />

**Comment by bleistivt** [comment]
There is also a plugin that lets you register cron jobs: http://vanillaforums.org/addon/cronjobs-plugin

Many frameworks implement fake cron jobs that are triggered by transparent images.

I would argue however, that you should look into a mail service provide like Sendgrid, Mailgun or Mandrill, if your forum reaches the size where 500 people may subscribe to a single topic.

**Comment by kaecyra** [comment]
And I'd recommend Mandrill if you do that.

**Comment by Clem01** [comment]
Thank you for your replies !
Currently, I use Mandrill for sending emails.
Using Mandrill, if you have to send 500 emails at once, it would take too much time (I think between 40-60 seconds).

**Comment by linc** [comment]
While we'd entertain a solution that *allowed* this while keeping default behavior, we don't plan to do this in core. We do plan to add message queue support to core in the future.
