### ISSUE TITLE
Editor: Editing comment 'deletes' emojis

### ISSUE THREAD

**Issue by CrazyLemon** [vanilla/vanilla#3382]
So lets say you insert an emoji into a comment and post the comment - everything shows just the way you like it but hey! You forgot a dot on the end of the sentence. 
Of course you hurry up and edit the post and first issue - no emojis are show in the editor. If you used ':)' plain old smiley there is nothing shown in WYSIWYG part but when you switch to HTML view you see `<img alt="" height="20">`.
After you add your dot and you save your comment there is a broken image icon shown and no emoji.

So yea, you ignore the issue and think thats just the issue with kids these days because they use these complicated `:smile:` emojis instead. So you try that but na-a. In editor you now see "smile" in a box, in HTML view there's only `<img alt="smile" height="20" title="Image: null">` and when you save the comment then there's a broken image icon with 'smile' (`<img alt="smile" height="20" title="Image: null" src="src">`) but no emoji :cry: 

The version is Version 1.7.2 in Vanilla 2.2 with WYSIWYG mode.

**Comment by linc** [comment]
This is fixed in 2.5.
