### ISSUE TITLE
Polls: Click and Blur events interefering with each other.

### ISSUE THREAD

**Issue by francisbo** [vanilla/vanilla#3387]
When creating a poll if you fill in all the fields then try to immediately click Save Poll, it doesn't save the poll but instead adds a new empty field to the poll form.  This is because there's an OnBlur event on the poll text inputs.  

If the text input is filled, and there is no other empty input, then clicking away from the field you just filled will cause a new empty field to appear.  This OnBlur function starts with a preventDefault() and stopPropagation() so the click on the Save Poll button doesn't register.  This OnBlur is an anonymous function and so cannot be overridden.

The files: 
- internal/plugins/Polls/polls.js
- vanilla/js/library.jquery.duplicate.js

Polls.js: 
- the poll duplication is added from lines 6-10.

jquery.duplicate.js: 
- OnBlur occurs at 119-122.
- OnBlur activates the OnClick located at 84.

**Comment by linc** [comment]
This is the wrong repo, and the issue was resolved.
