### ISSUE TITLE
Better nested quote support

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3390]
The issue come from here: vanilla/porter#63
TL;DR: Nested user quotes using BBCode are not supported.

I also tested quotes from the editor plugin and it doesn't work.
Using the [NBBC plugin](http://vanillaforums.org/get/nbbc-plugin-1.1.0) resolve the problem but I feel like that should be part of the core functionalities

**Comment by bleistivt** [comment]
related:
http://vanillaforums.org/discussion/28649/quotes-1-6-9-vanila-2-1-6-and-bbcode

**Comment by bleistivt** [comment]
This was fixed #3572
