### ISSUE TITLE
Bookmarked discussions with 0 replies don't show author

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3397]
If a bookmarked discussion has 0 replies, the author of the discussion doesn't show up on the listing on the bookmarked discussions page.
![screen shot 2015-12-17 at 12 16 51 pm](https://cloud.githubusercontent.com/assets/8974997/11876585/8d4285c0-a4b8-11e5-8bbd-cf4c7315188a.png)

**Comment by linc** [comment]
![](http://icrontic.com/resources/icrontimoji/facepalm.gif)

**Comment by korelstar** [comment]
I think this should be fixed by #3418

**Comment by JulieVanilla** [comment]
Thanks, @korelstar, I've subscribed to that PR. Appreciate it! :)

**Comment by korelstar** [comment]
@JulieVanilla Have you tested, if #3418 really fixes this bug? If not: there is just a very small diff, you may do it by hand on your vanilla installation: https://github.com/vanilla/vanilla/pull/3418/files

**Comment by JulieVanilla** [comment]
@korelstar I haven't, actually. I work at Vanilla, focusing on the hosted version, and am not a dev, so I haven't been able to try it out. I'm following it now, though, so I'm looking forward to seeing if this does the trick! :)
