### ISSUE TITLE
Update Smarty to 2.6.29

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#3416]
Smarty 2.6.25 compiles .tpl files to empty templates on PHP7
```php
 <?php /* Smarty version 2.6.25, created on 2016-01-02 23:29:56
         compiled from /www/htdocs/vanilla-master/themes/acmobile/views/default.master.tpl */ ?>
```

It works when using a newer 2.x version
https://github.com/smarty-php/smarty/tree/Smarty2

**Comment by austins** [comment]
+1. Can confirm Smarty is one of the issues when running PHP 7.

**Comment by xiphiaz** [comment]
Closed in https://github.com/vanilla/vanilla/pull/3428
