### ISSUE TITLE
Wysiwyg mode in Vanilla Comments breaks quoting and other formatting

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3430]
See PostController:

        // Vanilla Comments save as Text, no matter the format.
        // Kludge to set format to Text if we're Wysiwyg to preserve newlines.
        if ($isEmbeddedComments && ($this->Form->getFormValue('Format', c('Garden.InputFormatter')) === 'Wysiwyg')) {
            $this->Form->setFormValue('Format', 'Text');
        }

The first comment there is a damned lie. If you're using Markdown on the forum, Markdown works in Vanilla Comments. So what we have here is a situation where ONLY Wysiwyg fails to show any formatting inserted into a comment, which includes the HTML inserted by the Quote option.

**Comment by linc** [comment]
This would also block mentions from working.

**Comment by initvector** [comment]
Re: https://github.com/vanilla/vanilla/pull/3275
