### ISSUE TITLE
Add option to disable Mobile Theme

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3432]
Functionally, it would simply assign `Garden.MobileTheme` to the value of `Garden.Theme`. We'd need to do this in code to maintain the association if `Garden.Theme` was changed further.

For UX, maybe a button on the Mobile Theme page that says "Disable mobile theme" or something like that. As @lauramakesart points out, this should include an additional message explaining that you should have a responsive primary theme in place to do this.

**Comment by charrondev** [comment]
This is already "kind of" done with https://github.com/vanilla/vanilla/pull/8412.

We now have

- An `addon.json` field to declare a theme responsive.
- If that is set the theme automatically enables both desktop and mobile. Additionally separate mobile/desktop theme options will not be displayed.
