### ISSUE TITLE
Profile page shows a thread as un-viewed to guest. 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#3456]
https://vanillaforums.org/profile/discussions/10878/Linc 

When logged in, this page adjusts to show you what threads you've viewed, but as a guest this thread: https://vanillaforums.org/discussion/30856/hq-news-vanilla-has-a-new-r-d-lead-spoilers-its-me is highlighted as being unread inexplicably.

**Comment by bleistivt** [comment]
Can confirm for vforg. This seems to be a cache or cloud only issue, I can't reproduce it on self hosted.

**Comment by charrondev** [comment]
I tried to do a skim through the various involved methods:

- `DiscussionModel::getByUser()`
- `DiscussionModel::calculate()`
- `cssClass()` in the discussions `helper_methods.php`

The code is quite convoluted and I don't see an obvious issue. I'd need a debugger and to be able to reproduce it locally to figure this out.

**Comment by charrondev** [comment]
Pretty sure I've figured out the issue. The `$watchUserID` is getting set to user who's profile you are viewing as a guest. So you are seeing the read/unread status of the whoever you are viewing rather than   the guest user.
