### ISSUE TITLE
Formatting options in editor for Warnings & Notes do not function

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#3482]
None of the formatting options (bold, italic, emojis, etc.) toggle anything when warning a user.

Expected functionality: If a formatting button exists, the formatting should work.

Francis said it was likely due to the Advanced Editor overriding Button Bar.

**Comment by beckyvb** [comment]
Addressed here: https://github.com/vanilla/vanilla/pull/3340

**Comment by initvector** [comment]
Closed by #3342
