### ISSUE TITLE
Check for double-uploads per-post, not per-discussion.

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3492]
*Current functionality:*

- Trying to upload a file with the same name as another file anywhere in the discussion results in an error: File is already in this discussion. It will not be uploaded again.

*Requested functionality:*

- Uploading identically-named files works, so long as they're not in the same post.

*Use-case*:

- Especially useful in developer communities or support communities, where being able to upload log files without needing to rename them would be helpful.

**Comment by DaazKu** [comment]
Work as intended.

**Comment by JulieVanilla** [comment]
This is still an issue on production clusters. I just tried this out on my test site on cl311.

![screen shot 2016-10-07 at 5 49 00 pm](https://cloud.githubusercontent.com/assets/8974997/19206390/98f8447c-8cb6-11e6-805e-c0b1b742a2b9.png)

**Comment by JulieVanilla** [comment]
Still an issue on my test site.

**Comment by linc** [comment]
To my knowledge, this is a known & confirmed issue. I've run into it myself.

**Comment by DaazKu** [comment]
I can reproduce now...
