### ISSUE TITLE
Remove Gdn_Format::*(array) functionality

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3499]
Currently, most methods on the **Gdn_Format** class can take an array or a string. If an array is given the function walks the elements and calls itself again on each element. This poses a couple of issues:
1. The format functions add an extra if statement for a limited use-case which affects performance. Since many format functions are called in tight loops this can add up.
2. It adds undue burden to developers maintaining the methods. They always have to think of the array-case. It adds an entire branch of unit testing.

Most importantly, there is a better way. Here is what I propose:
1. Make formatting functions just work on a string or other scalar value.
2. Developers wanting to format an entire array can use **array_walk()** or **array_walk_recursive()** in combination with the desired formatting function.

**Comment by tburry** [comment]
I guess **array_walk()** won't work out of the box, but something like this could be coded:

```php
function applyArray(&$array, $callback) {
    array_walk($array, function (&$elem) {
        $elem = $callback($elem);
    };
}
```

**Comment by charrondev** [comment]
Deprecated and not present in `FormatService::render*()` method.
