### ISSUE TITLE
Media gets size of thumbnail stored instead of original

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3505]
It appears that images uploaded via Advanced Editor get their `Size` property stored from the thumbnail that is generated rather than the original file. This is misleading when the attachment says, for instance "402K" and it's actually a 14MB file.

**Comment by bleistivt** [comment]
I can't reproduce this. Maybe it was fixed in the meantime?

**Comment by charrondev** [comment]
Additionally any future fixed would likely not occur using the bespoke uploading present in Rich Editor and go through the `/api/v2/media` endpoint. I've experienced that sending the correct size.
