### ISSUE TITLE
+ symbol in URL slug renders as %b, truncating URL

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3544]
If a URL slug has a + symbol in it, it renders as %b. This truncates the URL when navigating the forum, resulting in a redirect to the main page if the truncated URL isn't a valid slug.

_Expected behaviour:_

One of:

- The + symbol is properly rendered
- The + symbol is removed from the automatically-generated slug

**Comment by linc** [comment]
https://github.com/vanilla/vanilla/pull/3512
