### ISSUE TITLE
Email Template Text does not respect locale over-ride

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#3550]
Created a new definition for $Definition['EmailNotification'] in a locale.php file found in conf folder, but it does not override default since HTML email templates was added.

**Comment by linc** [comment]
Do you have HTML emails enabled?

**Comment by adrianspeyer** [comment]
I turned it on. Tried it out and then went back to text emails. My locale is now being ignored.

**Comment by linc** [comment]
We've updated the system this week. Old locales will work for certain instances now, but generally we are deprecating / removing them.

**Comment by adrianspeyer** [comment]
Makes sense. I'll take a look. Hopefully there will still be a way to customize some aspects :)

**Comment by beckyvb** [comment]
To customize the text of emails in Vanilla, you can:

1. Set the config setting 'Garden.Email.Prefix' to a string that will be added before the message of any Activity notification email.

2. Add definitions for 'EmailWelcome', 'EmailWelcomeConnect' and/or 'EmailWelcomeRegister' to your locale to override the complete body of the welcome email.

3. Add definitions for the following strings in your locale (this list is not exhaustive):
'Check out the new community forum I\'ve just set up.'
'Hi Pal!'
'%s has created an account for you at %s.'
'%s has invited you to join %s.'
'%s has reset your password at %s.'
'Check it out'
'Confirm My Email Address'
'Confirm Your Email Address'
'Connected With: {ProviderName}'
'Hello!'
'Hello {User.Name}!'
'Hello %s!'
'Find your account information below.'
'Join this Community Now'
'Reset Your Password'
'Sign In Now'
'We\'ve received a request to change your password.'
'You have been approved for membership.'
'You have successfully registered for an account at {Title}.'
'You have successfully connected to {Title}.'
'You need to confirm your email address before you can continue.'
'Your login credentials are:

Email: %s
Password: %s'

'
