### ISSUE TITLE
Editor triple-click + formatting option puts closing tag on newline

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3564]
Reported by forum member using Markdown formatter:

 ~~When you triple-click to select all the text between carriage returns, then click a formatting button, it puts the close of the formatting marks after the second carriage return, breaking the formatting. Seems like it should either know enough not to allow the close to go after the carriage return, or understand how to parse the formatting despite the carriage return.
~~
For example, above, I triple-clicked the paragraph, then selected 'strikethrough'.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
