### ISSUE TITLE
Undefined variable `$GroupData`

### ISSUE THREAD

**Issue by DataTables** [vanilla/vanilla#3582]
I'm getting an error about an undefined variable with Vanilla 2.2, although this appears to also be on the trunk: https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.activitymodel.php#L1563

The `$GroupData` variable isn't defined anywhere and PHP gives an error:

> Undefined variable: GroupData

I'm not entirely sure what the goal there is - sorry for not having a PR to resolve it.

**Comment by beckyvb** [comment]
In a pull request: https://github.com/vanilla/vanilla/pull/3747

**Comment by beckyvb** [comment]
Fixed with https://github.com/vanilla/vanilla/pull/3747
