### ISSUE TITLE
Naughty emoji not parsing correctly

### ISSUE THREAD

**Issue by valeryan** [vanilla/vanilla#3590]
I notices that using just >:) on forum will actually add a smily face in a quote block. 
I posted an example on this thread on page 2. [we just merged a cutom emoji set ...](https://vanillaforums.org/discussion/29205/we-just-merged-a-custom-emoji-set-by-todd-into-core-and-im-totally-in-love-with-it/p2)

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.

We've moved to using native emojis instead of smiley conversion.
