### ISSUE TITLE
Vanillicon icon for code is weird

### ISSUE THREAD

**Issue by CrazyLemon** [vanilla/vanilla#3627]
So if you want to use vanillicon icon for code this weird thing comes up. 
![vanillicon-icon-code](https://cloud.githubusercontent.com/assets/3321382/13958713/7328d61e-f051-11e5-9943-7bf500873251.png)
I would expect the 'universal' icon for code which is either '<>' as on github or '</>' as in font awesome.

**Comment by hgtonight** [comment]
Embrace diversity.

I personally dislike the `<>` icon for code as it implies markup languages.

**Comment by CrazyLemon** [comment]
I'm not against diversity but i prefer something 'universal' against something just... weird.
I can't just keep teaching users which one is for code. 
So instead of `<>` lets just use `{}` ? But python folks might disagree with that one. :)

**Comment by linc** [comment]
Don't think this is gonna happen.
