### ISSUE TITLE
Private Community mode should never block any SSO endpoints

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3638]
The block should be revised to allow for non-standard configurations via `/entry` endpoints.

**Comment by initvector** [comment]
URLs beginning with `/entry` are already excluded in the dispatcher: [class.dispatcher.php:165](https://github.com/vanilla/vanilla/blob/566aa033d9966da4055e1f5a1825daabf0513d47/library/core/class.dispatcher.php#L165)

**Comment by DaazKu** [comment]
Yes but it is set to `self::BLOCK_PERMISSION` and not `self::BLOCK_NEVER` (which may be more appropriate for entry)

**Comment by initvector** [comment]
The logic for determining if a page should be redirected or not in Private Community mode comes down to this:

```php
c('Garden.PrivateCommunity') && $CanBlock > self::BLOCK_PERMISSION
```

The config value would be truthy, `$CanBlock` would be 1, the value of `BLOCK_PERMISSION`.  In the case of `/event` URLs, it should resolve to something like "1 && 1 > 1", which is false.
