### ISSUE TITLE
Spoiler tags giving trouble with Chrome

### ISSUE THREAD

**Issue by dampersand** [vanilla/vanilla#3641]
Hi, I noticed this bug and thought I'd bring it up:

<a href="http://imgur.com/MkfD0Tc.png"><img src="http://imgur.com/MkfD0Tc.png" title="source: imgur.com" /></a>

This is how spoiler tags appear on my browser - two 'show' buttons.  Neither of them have any functionality, either - the tags do correctly hide the text, but the spoiler cannot be expanded.

<3 Vanilla!

**Comment by linc** [comment]
We had a pre-release version of the new native spoilers running on Icrontic for a couple days. I've updated it to the final version now and so this should be fixed now.
