### ISSUE TITLE
Pocket frequency Begins At option doesn't seem work as intended

### ISSUE THREAD

**Issue by francisbo** [vanilla/vanilla#3643]
When you create a Pocket that shows up between comments or discussions and "repeats every" x amount of times, the "frequency" option works fine but the "begins at" option doesn't seem to have its intended effect.  It actually seems to get interpreted as though you had used the "given indexes" option.

I've created a pocket that was set to frequency 3 and begins at 6 but the pocket's information showed up after the 3rd comment even though it was only supposed to show up after the 6th.

<img width="347" alt="screen shot 2016-03-25 at 4 09 56 pm" src="https://cloud.githubusercontent.com/assets/12516778/14053384/38ebcc92-f2a7-11e5-861a-b5465ebc102e.png">

**Comment by initvector** [comment]
Should be fixed by https://github.com/vanilla/addons/pull/317

**Comment by francisbo** [comment]
Verified to be working in my local build.
