### ISSUE TITLE
Declaration signature mismatch

### ISSUE THREAD

**Issue by benjamw** [vanilla/vanilla#3652]
**Declaration of UserModel::delete($UserID, $Options = Array) should be compatible with Gdn_Model::delete($Where = '', $Limit = false, $ResetData = false)**

This is not the only one. This error occurs so much in Vanilla that I've had to modify the code around many instances of `include` and `require` to bypass this issue.

Running on PHP 7, and if Vanilla is going to support PHP 7 anytime soon, this issue is going to have to be addressed.

**Comment by linc** [comment]
Yes, this has been resolved for the upcoming 2.3 release.
