### ISSUE TITLE
It is possible to create a discussion with empty characters as title and body.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3656]
As the title says you can create a discussion with invisible characters (\x01 for example) as the title and body.
You end up with a discussion you cannot click on.

To reproduce easily get to the create discussion screen, open your console and execute this: `$('#Form_Name')[0].value = $('#Form_Body')[0].value = '\x01';`
Then save.

**Comment by smartclash** [comment]
well @DaazKu I Think it should be considered as a security bug as because the client can execute commands and fool the vanilla system which is bad. I think vanilla theme has to take this into consideration.
