### ISSUE TITLE
Update default theme

### ISSUE THREAD

**Issue by smartclash** [vanilla/vanilla#3670]
I am a new developer willing to contribute to vanilla forums. I request you to update the default theme folder so that we can know the basic css class used by vanilla forum

Sorry for making this an issue but still it's important because it has not been touched since a year! 

Sorry again #and hope you will update them soon

**Comment by linc** [comment]
Howdy! We're going to be updating the default theme hopefully later this year. There's a lot of challenges in how we are going to do this to remain backwards compatible with the hundreds (thousands?) of themes already out there. We have lots of ideas tho, so keep your eyes on this issue tracker as our plans start to take form.
