### ISSUE TITLE
Can't sign in on IE8

### ISSUE THREAD

**Issue by jfarthing84** [vanilla/vanilla#3680]
When attmpting to signin via popup on IE8, it always gives errors as if no information has been entered. This doesn't happen when accessing /enty/signin directly.

**Comment by linc** [comment]
If you're the administrator, you could set `Garden.SignIn.Popup = false` in your config as a workaround.

Is this true with the base theme and no additional plugins enabled?

**Comment by jfarthing84** [comment]
Yessir.
