### ISSUE TITLE
Multiple jQuery instances causing some functions to be undefined

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#3681]

**Comment by DaazKu** [comment]
https://developer.mozilla.org/en/docs/Web/HTML/Element/script#attr-async

Maybe removing the async attribute may fix the problem.
My though process here is that if it is blocking the parser the complete event may be thrown after the script execution.

**Comment by DaazKu** [comment]
The real problem is that we have multiple jQuery instances created in the page somehow.

Changing this line:
https://github.com/vanilla/vanilla/blob/01a368fc025151f4c148e73d7a9c4ab150cca0cf/plugins/editor/js/editor.js#L1520
for $ = jQuery "Fix" the problem.

**Comment by DaazKu** [comment]
The bug can be seen on support.vanillaforums.com
We should investigate to be sure that this is not something that can happen everywhere.

**Comment by initvector** [comment]
The originally cited behavior regarding lazy, asynchronous loading of the scripts appears to have been a red herring.  @DaazKu determined the real issue to be the inclusion of a second copy of jQuery on the page, included in a theme, which overwrote the original instance provided by Vanilla.

>The real problem is that we have multiple jQuery instances created in the page somehow.
>
>Changing this line:
>https://github.com/vanilla/vanilla/blob/01a368fc025151f4c148e73d7a9c4ab150cca0cf/plugins/editor/js/editor.js#L1520
>for $ = jQuery "Fix" the problem.
