### ISSUE TITLE
Refactor database attribute serialization

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3685]
We will be migrating database attribute type fields to JSON at some point. To prepare for this we want to pass all serialize() and unserialize() calls with respect to the database through helper functions so that we can later make the change in one place.

1. Add dbencode() and dbdecode() to functions.general. These functions should initially be aliases for serialize() and unserialize(), but dbdecode() will only have one parameter.
2. Replace existing calls to serialize() and unserialize() with dbencode() and dbdecode() where appropriate. This would be in all places where attribute style arrays are being saved/loaded from the database. This should be most if not all calls.
3. Make a note of additional calls to serialize()/unserialize(). We may want to get rid of these too if we can.

**Comment by DaazKu** [comment]
I like this a lot. Just saying.

**Comment by DaazKu** [comment]
The dbencode() function should make sure that the problem in #3715 does not happen anymore.

**Comment by tburry** [comment]
PRs should be as small as possible. Once this PR is merged we can keep going with the feature.

**Comment by hgtonight** [comment]
Please highlight this change in release notes for OS developers.

**Comment by tburry** [comment]
You need to do this to addons and internal too.
