### ISSUE TITLE
Investigate Dashboard app hook that queries DB for roles on every page load

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3686]
Possibly causing excessive database load.

**Comment by tburry** [comment]
@linc I'm trying to press @nervoustwit into why the hook is necessary. I really don't think we should be putting this hook in at all. Here are some reasons:

1. Even if cached, we are incurring I/O when very few installations use or need this data.
2. Do we really need to filter out private roles for the current user? Other users don't see your JSON array.
3. The roles as added are only the role names without IDs meaning we couldn't use the information ourselves very easily.

**Comment by initvector** [comment]
For reference, the specific hook is [gdn_dispatcher_afterControllerCreate_handler](https://github.com/vanilla/vanilla/blob/130ea184285bb098890a0a2a73a1c44e73066f0b/applications/dashboard/settings/class.hooks.php#L426) in the Dashboard application.

**Comment by linc** [comment]
My feedback from the "removal" PR:

> This wasn't just added for a plugin, it was also added to allow the use of third-party analytics systems with role as a tracking value. This hook vastly simplifies that process and reduces the load caused by previous Javascript workarounds pinging `/profile` constantly for this info.

I was hoping (possibly unrealistically) this data could get joined into the user data cache to reduce trips to cache to address point 1. We need to filter private roles because while un-viewable, it's still a potential security issue, like exposing IP or email in the page source - we've declared the data "private" so we need to respect that. I agree it would be more generally useful to also include the RoleID, but I didn't see immediate utility for it since this was a third-party integration point, not targeted for consumption by us.

**Comment by tburry** [comment]
@linc, give me a proposal then.

**Comment by linc** [comment]
I no longer see an issue here. The data call stack from the hook is:

* `RoleModel::getPublicUserRoles()`
* `RoleModel::getByUserID($userID)`
* `Gdn::userModel()->getRoles();`

And that ultimate method is exactly where role caching was added by #3723.

I no longer see this call all the time in my debugbar, and I haven't heard about this from ops in months. So I'm saying Ryan's fix is in and that's all we needed.
