### ISSUE TITLE
Ensure all ARIA attributes have valid values

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3699]
**Client finding:** Element IDs MUST be unique. The page contains duplicate IDs "personal" has been repeated for all `<li>` elements . This adversely impacts behavior of assistive technologies on different platforms and sometimes the content's functionality too.

**Client recommendation:** Ensure all ARIA attributes have valid values. The `<li>` elements have `aria-describedby="personal"`, the `"personal"` value has been repeated in all the `<li>` elements. Aria-described by should have unique and valid ID value given, not the string value.

**Comment by initvector** [comment]
We need some more details on this issue.  The individual who originally reported it has been contacted and asked to provide additional information.  We'll resume work on this issue once we have that information.

**Comment by initvector** [comment]
After further investigation, it was determined this was a false alarm.  Closing.
