### ISSUE TITLE
Doesn't allow to update users

### ISSUE THREAD

**Issue by i2smho** [vanilla/vanilla#3703]
Upgrade mysql to version 5.6.30 with Vanilla 2.2. Work well with mysql 5.1.7. Any idea what is going on?
![screen shot 2016-04-11 at 11 21 09 am](https://cloud.githubusercontent.com/assets/4502918/14464660/c2148fb4-009d-11e6-8916-43f1234f2174.png)

**Comment by linc** [comment]
Strict mode bug. The easiest fix is to disable strict mode until 2.3.

**Comment by DaazKu** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/3326
