### ISSUE TITLE
Load data infile query raise an error when PDO::ATTR_EMULATE_PREPARES is disabled.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3757]
On my current setup:

```
Mac OSX El Capitan
MariaDB 10.1.13-MariaDB Homebrew
PHP 7.0.5 (same error on PHP 5.6.20)
```

I have the following problem:
http://stackoverflow.com/questions/17414556/load-data-infile-and-unbuffered-queries-error

I have to comment out `$PDO->setAttribute(PDO::ATTR_EMULATE_PREPARES, 0);` in Gdn_Database::newPDO() to get rid of the error.

**Comment by tburry** [comment]
That setting is a last line of defense against SQL injection. Can you set that attribute to 1 before your load data call and then disable it again after? If not you may need to make a new PDO with the setting.

**Comment by DaazKu** [comment]
This is not a problem anymore ¯\\\_(ツ)\_/¯
