### ISSUE TITLE
Avatar's image problem

### ISSUE THREAD

**Issue by GabrielEnraged** [vanilla/vanilla#3779]
Hello Vanilla Forums Community, i have a problem when i upload a avatar for my profile : 

Screenshot of the error : 

![error](https://cloud.githubusercontent.com/assets/18049206/14768914/8b6d85f6-0a4d-11e6-94b5-2d05eb0a70dc.JPG)

This image is a JPEG forma. When i try the png forma, it's the same.

So, any ideas to resolve this ?
Thanks,

Gaby

**Comment by linc** [comment]
That error message indicates that `getimagesize()` on the file returned `false`. This indicates that either the file(s) are corrupted or your PHP installation has an issue. If you need additional assistance, please try the community forum at https://vanillaforums.org/discussions.
