### ISSUE TITLE
Expire transientkey at logout

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#3780]
It's currently difficult for us to do things like expiring a transient key at a higher interval than cookies. However, when the user takes the explicit log out action, that's a case where we could tighten our security by invalidating it immediately.

**Comment by initvector** [comment]
Closing this out in favor of a more comprehensive overhaul of how we handle CSRF tokens in Vanilla: https://github.com/vanilla/vanilla/issues/3965
