### ISSUE TITLE
Trying to attach a file after having "de-attached" it causes error

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#3785]
- Attach a file
- Click the "x" next to the file below post editor to "de-attach" it
- Try attaching the same file again
- Result: File is already in this discussion. It will not be uploaded again.

**Expected result:** File is properly attached to the post because the file has not yet been uploaded to the discussion.

**Comment by DaazKu** [comment]
When a file is "uploaded" you cannot re-upload it and that is normal.

When you click on the "x" you just tell the editor to not take the uploaded filed into account anymore. Re-clicking on the file will "bring it back".

Not a bug.

![screen shot 2016-08-23 at 3 13 19 pm](https://cloud.githubusercontent.com/assets/2412909/17906216/679de034-6944-11e6-9c38-4460c178a762.png)
![screen shot 2016-08-23 at 3 13 08 pm](https://cloud.githubusercontent.com/assets/2412909/17906217/67a91a30-6944-11e6-8fef-965284ec2921.png)
