### ISSUE TITLE
Make sure no code uses serialize/unserialize where dbencode/dbdecode should be used

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3802]

**Comment by initvector** [comment]
Looks good to me.  See [this search for serialize](https://github.com/vanilla/vanilla/search?q=serialize+language%3Aphp&type=Code&utf8=%E2%9C%93) and [this search for unserialize](https://github.com/vanilla/vanilla/search?q=unserialize+language%3Aphp&type=Code&utf8=%E2%9C%93).

We still have calls to [`Gdn_Model::serializeRow`](https://github.com/vanilla/vanilla/blob/d89ccb71ab2369b6420bca8ec5b980a7d875291d/library/core/class.model.php#L309), but that function doesn't actually call PHP's `serialize`.  Its values are [passed through `dbencode`](https://github.com/vanilla/vanilla/blob/d89ccb71ab2369b6420bca8ec5b980a7d875291d/library/core/class.model.php#L312).  Similarly, `Gdn_DataSet::unserialize` [passes its values through `dbdecode`](https://github.com/vanilla/vanilla/blob/d89ccb71ab2369b6420bca8ec5b980a7d875291d/library/database/class.dataset.php#L641).

While we do still use `serialize` in some areas (e.g. vendor libraries, cookies, caching), the only function handling DB data that appears to still uses it is `dbencode`.
