### ISSUE TITLE
JSON encode attributes

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3804]
Switch attribute encoding from PHP serialization to JSON encoding. The JSON encoding will be a gradual migration where existing serialized attributes will still be deserialized properly, but newly saved attributes will be in JSON.

**Comment by charrondev** [comment]
With only 1 remaining minor issue left, and no immediate plans for it's implementation I'm closing out this epic in favour of that issue. https://github.com/vanilla/vanilla/issues/4767
