### ISSUE TITLE
Build process checkup

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3833]
Make sure our Phing build is still working well. Try it out. Make sure it has everything it needs. Make sure there aren't some exclusions that need to be added etc.

@linc Can you schedule a task like this once every couple of months or so?

**Comment by linc** [comment]
We're about to start the 2.3 release cycle which is the first one where I can actually use Phing, so I think we'll be more on top of this now that we'll be using it regularly.

**Comment by initvector** [comment]
Everything seems solid as of 13d015ecd6cd88797a0c5d4dc9fbbb99cd1ed7cb

The build process pulls down the latest Composer requirements, only includes whitelisted files and directories (which includes just about everything, outside of composer.* files, testing and build directories), before zipping it all up into an archive with the current version number included in the filename.  I've run a fresh install with the contents of the created archive and all tested functionality seems to perform without issue.
