### ISSUE TITLE
Add support for parent themes

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3838]
- [ ] Add info array recognition and **Addon** methods.
- [ ] Make asset lookup fall to the parent theme before going to the root addon.
- [ ] Make parent theme classes available in the autoloader when child themes are enabled.
- [ ] Fall back to parent theme hooks when a child theme has no theme hooks.

**Comment by Charrondev** [comment]
A few other things that I can imagine should fit here too: 

- Check parent theme's requirements (maybe make sure they don't clash?). This currently doesn't seem to work at all, but will probably need to work for this.
- Will the parents themehooks be overridden entirely? I'm guessing implementing a parents hooks would probably just be extending its class than right?
