### ISSUE TITLE
Remove nested set fields from the database

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3848]

**Comment by initvector** [comment]
`TreeLeft` and `TreeRight` are still used pretty heavily in Vanilla.  Does this issue depend on another being closed first?

### Nested set fields used in Vanilla
1. [applications/vanilla/views/categories/all.php:81](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/views/categories/all.php#L81)
1. [applications/vanilla/controllers/class.vanillasettingscontroller.php:674](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/controllers/class.vanillasettingscontroller.php#L674)
1. [applications/vanilla/models/class.categorymodel.php:150](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L150)
1. [applications/vanilla/models/class.categorymodel.php:1329](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1329)
1. [applications/vanilla/models/class.categorymodel.php:1335](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1335)
1. [applications/vanilla/models/class.categorymodel.php:1376](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1376)
1. [applications/vanilla/models/class.categorymodel.php:1389](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1389)
1. [applications/vanilla/models/class.categorymodel.php:1458](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1458)
1. [applications/vanilla/models/class.categorymodel.php:1460](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1460)
1. [applications/vanilla/models/class.categorymodel.php:1462](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1462)
1. [applications/vanilla/models/class.categorymodel.php:1820](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1820)
1. [applications/vanilla/models/class.categorymodel.php:1828](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1828)
1. [applications/vanilla/models/class.categorymodel.php:1842](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1842)
1. [applications/vanilla/models/class.categorymodel.php:1876](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1876)
1. [applications/vanilla/models/class.categorymodel.php:1879](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1879)
1. [applications/vanilla/models/class.categorymodel.php:1911](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1911)
1. [applications/vanilla/models/class.categorymodel.php:1947](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1947)
1. [applications/vanilla/models/class.categorymodel.php:1982](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1982)
1. [applications/vanilla/models/class.categorymodel.php:1984](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L1984)
1. [applications/vanilla/models/class.categorymodel.php:2178](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L2178)
1. [applications/vanilla/models/class.categorymodel.php:2187](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L2187)
1. [applications/vanilla/models/class.categorymodel.php:2371](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L2371)
1. [applications/vanilla/models/class.categorymodel.php:2380](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L2380)
1. [applications/vanilla/models/class.categorymodel.php:2471](https://github.com/vanilla/vanilla/blob/63a21b8ca60429a208bccaa37451c5c9588d438b/applications/vanilla/models/class.categorymodel.php#L2471)

**Comment by tburry** [comment]
Okay, maybe it's too early for this one.

**Comment by charrondev** [comment]
I'm closing this due to the large amount of current code still using the these and lack of detail. At some point in the future we way wish to make a new category model, at which point these will still not be used, but something like this can be brought up when planning the architecture for it.
