### ISSUE TITLE
Dashboard v3 side nav

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3862]
- [x] The dashboard v3 should use the new nav module, but throw backwards compatible events with the old side menu.
- [x] There will be three nav modules: moderation, settings, and analytics. There is a good change that these will all be on the page at the same time and use javascript to hide/show.

**Comment by beckyvb** [comment]
The backwards compatibility will be addressed in this: https://github.com/vanilla/vanilla/issues/3822
