### ISSUE TITLE
too much empty space in lists

### ISSUE THREAD

**Issue by tchncs** [vanilla/vanilla#3863]
Hi, i just noticed very big spacers in lists and very want them away.
We're using Markdown on our forum.
I searched long but sadly was unable to find out where they come from.
Maybe someone reading this issue is able to help me find them?

Sorry about this maybe invalid issue.
![2016-05-02-205558_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/14964542/d7a6e38e-10a8-11e6-8f90-f8773ca42bed.png)

**Comment by tchncs** [comment]
I did the following now:

`return "". $result ."\n\n";`
instead of
`return "\n". $result ."\n\n";`

i let this issue stay open because this doesnt feel clean to me and im new to this^^

**Comment by linc** [comment]
There's no example here of what input you used to generate that. We've overhauled this system since 2016 and I haven't seen anything like this during my Markdown usage, so I'm gonna close this without further details.
