### ISSUE TITLE
Remove auto-archiving exclude functionality

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#3870]
We found that this feature has little actual customer value and it is currently hidden from sites (although still present). The purpose of this issue is to fully remove it from the code base.

Upon investigation, I found some customers taking advantage of the auto-close functionality, but the exclude functionality is just too fragile to still support.

**Comment by benjamw** [comment]
I was just looking into setting up some kind of "auto-close old threads" setting. Is there anything that I can use in it's place?

I'm on v2.1

**Comment by linc** [comment]
Not currently, no, but that is a classic example of a great plugin functionality.
