### ISSUE TITLE
Remove the e modifier from every regexes. (PHP 7 compatibility)

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3882]
See: https://github.com/vanilla/vanilla/pull/3880

I did a quick search and there are 2 places where the modifier is still used:

https://github.com/vanilla/addons/blob/master/plugins/BluehostFix/class.phpmailer.php
https://github.com/vanilla/vanilla/blob/master/library/vendors/phpmailer/class.phpmailer.php

Updating the library might be a good idea.

**Comment by tburry** [comment]
FYI: We've slightly customized PHP Mailer so a simple switch can't be done. T

**Comment by linc** [comment]
The PHPmailer adjustment should be backported to `release/2.3`.

I'd recommend against updating phpmailer as part of this task. We can file a separate one for that if we want. PHP7 compat is a higher priority.

**Comment by linc** [comment]
There's already a separate task for moving phpmailer to composer, so that is where you can address an upgrade too if you want: https://github.com/vanilla/vanilla/issues/3895

**Comment by linc** [comment]
Recommend doing this fix first or else you'll have a problem backporting.

**Comment by DaazKu** [comment]
You beat me to link #3895 .

**Comment by DaazKu** [comment]
A more intensive search I found regexes using the e modifier in:

- library/vendors/Auth/Yadis/ParseHTML.php
- library/vendors/phpmailer/class.phpmailer.php
- plugins/BluehostFix/class.phpmailer.php
- plugins/NBBC/nbbc/nbbc.php
- plugins/NBBC/nbbc/src/nbbc_parse.php

**Comment by DaazKu** [comment]
Fixed in:
https://github.com/vanilla/vanilla/pull/4120
https://github.com/vanilla/addons/pull/347
