### ISSUE TITLE
Replace simple_html_dom by pQuery

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3897]
We might just want to switch to pQuery, but leave simple_html_dom around as is in a deprecated state.

- [x] Replace simple_html_dom functions/methods in core with pQuery.

**Comment by DaazKu** [comment]
If we switch from simple_html_dom to pQuery I'm gonna just remove simple_html_dom entirely since it is not a class and cannot be autoloaded. Anything that is not currently in our repositories that would reference it will try to include it from the vendor folder anyway.
