### ISSUE TITLE
Upgrade the PHPThumb

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3898]
I'm not really sure where this is used. If it isn't used we should deprecate it.

**Comment by bleistivt** [comment]
I believe it is used to save favicons uploaded from settings/banner as proper .ico files.
https://github.com/vanilla/vanilla/search?utf8=%E2%9C%93&q=imageico (called by Gdn_UploadImage if the target is an .ico file)

It is worth checking if #1937 is still relevant.
