### ISSUE TITLE
Support SVG image uploads

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3903]
I'd like to provide a way of supporting SVG image uploads. This will require some research into security implications, which is the only real barrier to uploads.
- [ ] Research possible ways user-generated SVGs could cause a security threat.
- [ ] Add basic support for SVG uploads.
- [ ] Add a method to check to see if an SVG is in the correct format.
- [ ] SVG uploads must have a .svg file extension.
- [ ] SVGs should be XML.
- [ ] SVGs should not include any `<script>` elements.
- [ ] SVGs should be checked against other possible problems.

Any security errors detected in an SVG should be logged before presenting an error message to the user. The error message should be "Invalid SVG format."

**Comment by charrondev** [comment]
I don't think we can call this won't fix. We're going to need to solve this with our new theming system.

SVG logos are a must have.

**Comment by tburry** [comment]
I think we are okay with just allowing SVGs to be uploaded via the config whitelist. If that's the case we don't need to do anything.

**Comment by mike-masson** [comment]
It doesn't currently seem possible, but SciData wants to be able to embed SVGs on Tuenti. They did allow it as an attachment which is working fine.

I haven't created an issue for it yet as I'm not sure if this should be classified as a Feature Request or a bug.
https://vanillaforums.happyfox.com/staff/ticket/53801

**Comment by tburry** [comment]
We won't be be allowing embeds anytime soon. SVG embeds do require a lot of security checks on the file itself.
