### ISSUE TITLE
Error when adding a message on Manage Messages in Dashboard 

### ISSUE THREAD

**Issue by raykai** [vanilla/vanilla#3911]
Cannot post an information Message in Dashboard > Appearance > Messages

I get this "There was an error performing your request. Please try again." when I try to post an information message on my board on v2.2.1 new install no plugins.

![bug](https://cloud.githubusercontent.com/assets/8138894/15141167/c65fbabe-166c-11e6-8492-255c9626bcbc.JPG)

some one in the forum is saying that if he terns  sql strict mode off  it works. 
https://vanillaforums.org/discussion/comment/235979?

is it required.to have Mysql strict mode off ?

my logs are all clean... so i don't know whats going wrong.

**Comment by raykai** [comment]
i can confirm that by having sql strict mode off works .... im using MySQL 5.7

**Comment by DaazKu** [comment]
This is fixed in master.
Fixed in release/2.2 https://github.com/vanilla/vanilla/commit/720bc3d02b70227a42b7f17aeee5abcd70a8e7fe
