### ISSUE TITLE
Make /entry/connect work for SSO and profile connects

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3915]
More OAuth applications are getting strict with redirect URLs so specifying multiple ones from a plugin is a bad UX. This touches some fairly significant code.

**Comment by DaazKu** [comment]
I'm gonna add here that for LinkedIn you need to provide a redirect URL that matches the `domain` and `path` exactly.
That means that every parameters, in that case, should be passed through the `query`.
