### ISSUE TITLE
Tagging Add Permission not honored when picking tag from "Show Popular Tags"

### ISSUE THREAD

**Issue by rbrahmson** [vanilla/vanilla#3923]
The tag input box as well as the "show popular" tags should not be shown in the New/Edit Discussion window when you lack the Tagging Add permission.

**Comment by charrondev** [comment]
This seems to be inline with the way that permission is supposed to work. Regrettably we don't have long descriptions on each permission, but `Plugins.Tagging.Add` allows users to create _new_ tags.

See [our documentation](https://docs.vanillaforums.com/help/addons/tagging/#permissions)

> Unchecking the “Add” permission will prevent those users from creating new tags but they will still be able to tag their posts with existing ones. This allows administrators to restrict users to a curated pool of tags.
