### ISSUE TITLE
Tagging plugin allows removing of tags even if Add permission not granted

### ISSUE THREAD

**Issue by rbrahmson** [vanilla/vanilla#3924]
Users without the Plugins.Tagging.Add permission can click on the "x" on the existing tag buttons (while adding/editing a discussion) and remove the tags.

Delete should be subject to the Add permission.

**Comment by charrondev** [comment]
This seems to be inline with the way that permission is supposed to work. Regrettably we don't have long descriptions on each permission, but `Plugins.Tagging.Add` allows users to create _new_ tags.

See [our documentation](https://docs.vanillaforums.com/help/addons/tagging/#permissions)

> Unchecking the “Add” permission will prevent those users from creating new tags but they will still be able to tag their posts with existing ones. This allows administrators to restrict users to a curated pool of tags.
