### ISSUE TITLE
GDN_Discussion.CountBookmarks field unused and not calculated

### ISSUE THREAD

**Issue by rbrahmson** [vanilla/vanilla#3925]
Opening this as this entry in the forum was not receiving feedback:
[CountBookmarks not updated in Vanilla 2.2](https://vanillaforums.org/discussion/32069/countbookmarks-not-updated-in-vanilla-2-2)

This worked fine in 2.1 and the change (which some in the forum were not sure was intentional) forced me to write around the issue for a plugin we use.

**Comment by linc** [comment]
From https://github.com/vanilla/vanilla/issues/5013

> In the discussions model you have `bookmarkDiscussion` which updates CountBookmarks, but for some reason you are using a near identical method `bookmarked` which doesn't.
