### ISSUE TITLE
"Display as default" option in dashboard not displaying categories as proper type

### ISSUE THREAD

**Issue by francisbo** [vanilla/vanilla#3952]
I ran into this issue with DMH.  I don't know who else might be affected.

All of their subcommunities were set to "display as default", which would display them as if "categories" was selected.  This worked up until today.  Today the "default" setting started making them appear as though "discussions" was selected.  This switch breaks the styling created for them.  As a temporary fix I've set them all the "category".

**Comment by linc** [comment]
I think the default changed, and that's bad, but now we probably don't want to change it back for the same reason.
