### ISSUE TITLE
Investigate cookie CSRF tokens

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3961]
Putting the CSRF token in the cookie instead of the user table would allow for separate tokens per browser and allow them to be invalidated in one without killing the other browser.

What I want to know is what are the security concerns with this. Post your findings to this issue.

**Comment by initvector** [comment]
Implemented correctly, there should not be any significant security concerns with this method.  It's probably more secure than our current CSRF method in that we wouldn't be recycling tokens.

I believe our best option is the [Double Submit Cookie](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Double_Submit_Cookie) workflow. Using this method, we store a cryptographically-strong random value in a cookie when the user signs in.  Anytime a user performs a potentially sensitive action, the value from the cookie should be appended to the request.  The CSRF token field (or custom header) in the request is verified against the value in the user's cookie.  Nothing is stored on the server, not even in the user's session.  Each sign-in issues a new token for that browser session, so terminating one browser session should not affect a separate browser session.  We rely on access to cookies in the client being secured by the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), which all modern browsers should support.
