### ISSUE TITLE
Switch CSRF tokens to cookies

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#3964]
We want CSRF tokens to go into cookies so that they can change per session, per device. We will be adding a cookie for the CSRF token. Here are some points:
1. The cookie should be HTTP-only.
2. The cookie should be signed with an HMAC so it can't be spoofed.
3. The user ID should be in the token somewhere so that a token can only work for yourself.
4. A new cookie should be generated during a new session and should be deleted on sign out. Perhaps, the cookie can refresh on new visits.
5. Make sure that a cookie that switches still works with existing tabs open. An existing tab will have the wrong cookie so will get a an error, but should be able to be re-posted successfully (this is just making sure to regression test, the feature is already added).
6. If a user doesn't have a CSRF token then a new one should be generated.

**Comment by linc** [comment]
Unclear what I'm supposed to do with this issue. All the other items on this Epic are completed as of sprint 13.

**Comment by tburry** [comment]
@linc, it's in the description.
