### ISSUE TITLE
Category dropdown no longer appearing when editing a discussion

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#3967]
The move toggle is a workaround, however it appears that the category dropdown when editing is no longer available.
![untitled2](https://cloud.githubusercontent.com/assets/15787691/15259323/980c565e-191e-11e6-83c9-5912718aec23.jpg)
![untitled](https://cloud.githubusercontent.com/assets/15787691/15259324/9817c098-191e-11e6-923f-3d1460901369.jpg)

**Comment by DaazKu** [comment]
Not related to vanilla/multisite#42 **

**Comment by DaazKu** [comment]
The dropdown was removed by this commit: [Don’t show the category dropdown when posting to a particular category.](https://github.com/vanilla/vanilla/commit/26ed2960207338c7540c900edcd9ae3a5d3aafba)

This means that we won't be adding the dropdown back.
The correct way to move a discussion is to use the move option from now on.

We may offer a move option in a dropdown in the future. TBD
