### ISSUE TITLE
In This Discussion core plugin not working with MySQL 5.7

### ISSUE THREAD

**Issue by raykai** [vanilla/vanilla#3974]
im getting a 
`Something has gone wrong.`
`We've run into a problem and are unable to handle this request right now. `
`Please check back in a little while.`

i turned on display_errors', 1); in index and i turned on Debug in config but its not showing the error log...

vanilla would need a full test with MySQL 5.7 as many core plugin don't work and some options in Dashboard bugs too.

**Comment by alaric1** [comment]
i seam to have the same error and im using MySQL 5.7 hope to have a hot-fix for MySQL 5.7 as it comes with ubuntu 16.04
