### ISSUE TITLE
How GDN_Log is currently used can cause corruption upon DB server reset

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#3988]
We sometime "move" records into the `Log` table until they are being reviewed (into the data attribute).
This is something that we do for the Moderation/Spam queues.

This is a problem when the last records from a table are moved into the `Log` table just before a DB server reset because InnoDB recalculate AUTO_INCREMENT fields on startup. 
That means that new records are generated using potentially old record IDs (that are currently stored in the `Log` table).

Mix this bug with other plugins like `Reactions` and you can have old reactions applied on new record or even new discussion having old comments right after being created.

**Comment by tburry** [comment]
I'm well aware of this issue (as much as I'm angry at MySQL for it too. I'm guessing we won't really fix this edge case. Hopefully we can just hold out until MySQL 8 which fixes the bug.
