### ISSUE TITLE
MarketPlace error

### ISSUE THREAD

**Issue by Ranvir990** [vanilla/vanilla#4007]
I can not able to edit product but i can Add them and delete them.
One more after successful transaction they are not showing in transaction log

i m getting following error

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.js:1:0
Use of getPreventDefault() is deprecated. Use defaultPrevented instead. jquery.js:5:0
TypeError: $.browser is undefined

**Comment by kaecyra** [comment]
This doesn't seem like its related to Vanilla.

**Comment by hgtonight** [comment]
@Ranvir990 I believe you are looking for the MarketPlace repository which has no affiliation with Vanilla: https://github.com/x00/MarketPlace-Vanilla-Plugin
