### ISSUE TITLE
Smarty_Security::isTrustedPHPFunction case-sensitive

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4014]
`Smarty_Security::isTrustedPHPFunction` uses `in_array` with the values we set for `php_functions` to determine if a function should be allowed or not.  `in_array` is case-sensitive, which makes `Smarty_Security::isTrustedPHPFunction` case-sensitive.  Existing templates often use upper-case-word naming schemes (e.g. InSection) for functions, so they don't mesh with our [new Smarty security policy](https://github.com/vanilla/vanilla/blob/72c743dfdd4e8a3d43aba3acf766366b72249bf1/library/core/class.smarty.php#L117) (e.g. inSection).

1. We can change the casing of the functions to their original casing.
2. We can append the old casings to the new list.
3. We can extend the `Smarty_Security` class, override `isTrustedPHPFunction` to be case-insensitive and use our custom security class for the new security policy.

Any other ideas/suggestions are welcome.

**Comment by tburry** [comment]
I had seen this and we added two versions of our functions. I'm wondering if we can subclass the object and make it case-insensitive?
