### ISSUE TITLE
Merging results in lost/hidden attachments

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4040]
When merging two or more discussions together, the following behaviour is seen:

Discussion 1 (the discussion that others will be merged into) has attachments. These are fine when the discussion has items merged into it.

Discussion 2 (the discussion that will be merged into Discussion 1) has attachments on the first post and on other comments. Any attachments on the first post of the discussion are removed when merged. Attachments on any comments remain.

If you undelete the merged discussion in the change log by restoring the thread deletion, the recovered discussion has the proper attachment in the first post again.

**Expected Behaviour:**
- Attachments should not arbitrarily vanish after a discussion is merged.

**Comment by linc** [comment]
Backport to both `release/1605` and `release/2.3`.
