### ISSUE TITLE
"Import" page bonks when mysql extension not installed

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4073]
The `mysql` PHP  extension is deprecated and now removed on many platforms.

```
Fatal Error in ImportModel._LoadTableLocalInfile();
Call to undefined function mysql_connect()
The error occurred on or near: /applications/dashboard/models/class.importmodel.php

1285:         // We've got to use the mysql_* functions because PDO doesn't support load data local infile well.
1286:         $dblink = mysql_connect(c('Database.Host'), c('Database.User'), c('Database.Password'), false, 128);
```

Minimally we should not throw a fatal error in this circumstance.

**Comment by DaazKu** [comment]
That is the only place in vanilla that the `mysql` extension is used. We can simply replace it by `mysqli` for the time being.
Or check it PDO got fixed.

**Comment by JonatanM** [comment]
I did it but it is not entirely sure

dblink = new mysqli('Database.Host', 'Database.User', 'Database.Password', 'Database.Name');
$Result = mysqli_query($Sql, $dblink);
if ($Result === false) {
$Ex = new Exception(mysql_error($dblink));
mysql_close($dblink);
throw new $Ex;
}

**Comment by DaazKu** [comment]
@JonatanM You should restart the import from scratch after that fix has been done.

**Comment by JonatanM** [comment]
I did it but still continued receiving this error :(

Table GDN_zUser doesn't exist
or
Incorrect integer value: '' for column 'InviteUserID' at row 1

**Comment by DaazKu** [comment]
Are you on windows?

**Comment by JonatanM** [comment]
yes

**Comment by JonatanM** [comment]
Ubuntu 16.04

**Comment by DaazKu** [comment]
What version of Vanilla and Mysql are you running?

**Comment by JonatanM** [comment]
PHP Version 7
mysql 5
Vanilla  2.3b1
Ubuntu 16.04

**Comment by DaazKu** [comment]
As I suspected. MySQL Strict mode problem. I suggest you just deactivate it until we fix the issue.

**Comment by JonatanM** [comment]
Nice @DaazKu you are a ninja uheuheuhe

Sorry for my English, it was a compliment
