### ISSUE TITLE
Registration fails when the reCaptcha plugin is disabled.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4087]
![screen shot 2016-06-09 at 1 46 17 pm](https://cloud.githubusercontent.com/assets/2412909/15940123/9399bb36-2e48-11e6-8903-f34948012ce7.png)

The plugin is disabled so obviously I shouldn't have to enter a captcha...

**Comment by DaazKu** [comment]
Setting `$Configuration['Garden']['Registration']['SkipCaptcha'] = true;` when disabling the plugin may be a possible solution

**Comment by kaecyra** [comment]
SkipCaptcha was not designed for that purpose. The checking of Captcha should automatically downgrade if there is no captcha plugin available. I think.

@tburry

**Comment by DaazKu** [comment]
The second solution should be what needs to be done IMO too.

**Comment by linc** [comment]
Clear this modification with @tburry. I'm in favor of allowing Captcha to be turned off entirely in favor of a different registration method, as long as the default on installation OR upgrade continues to be turning it on automatically.
