### ISSUE TITLE
Special categories (Social Groups, Subcommunities) should not be deletable

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4089]
We have some support request from client that deleted the Social Groups category since they did not know what it was about. These kind of "container" should not be deletable or even presented in the dashboard.

**Comment by linc** [comment]
@tburry Can you look at this as part of the category types refactor in progress?

**Comment by linc** [comment]
Step 1 vanilla/vanilla#4899

**Comment by linc** [comment]
Unsure about the assertion that Subcommunities should be undeletable.

The PRs submitted sufficiently fixes this as far as core is concerned.
