### ISSUE TITLE
UserModel::tagSearch() should always return exact matches

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4090]
In some case it is impossible to refine the search enough to get a username with the default ordering (CountComments).

Let's take for example a forum with a lot of John\* users.
if 'John' have 1 comment and every other user have more than 1 comment he will appear last after the ordering is done. Since we return only the first 10 users that match 'John%' we will never be able to refine the research enough to get the user 'John' to be returned by the function.

This is something that could work.

``` php
        $Search = trim(str_replace(['%', '_'], ['\%', '\_'], $Search));

        switch (c('Garden.MentionsOrder')) {
            case 'Name':
                $order = 'u.Name';
                $direction = 'asc';
                break;
            case 'DateLastActive':
                $order = 'u.DateLastActive';
                $direction = 'desc';
                break;
            case 'CountComments':
            default:
                $order = 'u.CountComments';
                $direction = 'desc';
                break;
        }

        return $this->SQL
            ->select('u.UserID', '', 'id')
            ->select('u.Name', '', 'name')
            ->from('User u')
            ->leftJoin('User u2', 'u2.UserID = u.UserID')
            ->like('u.Name', $Search, 'right')
            ->where('u.Deleted', 0)
            ->orderBy('u2.Name', 'asc')
            ->orderBy($order, $direction)
            ->limit(1)
            ->get()
            ->resultArray();
```

**Comment by charrondev** [comment]
This seems to have been implemented with `UserModel::getMentionSort()`.
 https://github.com/vanilla/vanilla/blob/927939b4a1fe582c71ca3947d75c7e5439848a56/applications/dashboard/models/class.usermodel.php#L2819
