### ISSUE TITLE
Russian keyboard makes discussion tags field unusable because of comma key equivalence

### ISSUE THREAD

**Issue by KitsuneSolar** [vanilla/vanilla#4096]
English key `,` = Russian key `Б`.
Pressing the `Б` tag added. That is, can not use the "Б" button in discussion tags field.

**Comment by KitsuneSolar** [comment]
I checked. Bug working only in google chrome.

**Comment by linc** [comment]
Wow, weird one. Any additional information anyone has about what we're doing wrong here (are we?) would be appreciated.

**Comment by KitsuneSolar** [comment]
Something like that I posted here:

https://github.com/ColdTrick/tag_tools/issues/6

There's a similar problem + link to other issues.

**Comment by KitsuneSolar** [comment]
The same problem in Inbox › New Message > **Recipients**.
It seems that anywhere you use AutoComplete, there is an error.

**Comment by charrondev** [comment]
@KitsuneSolar Are you still able to reproduce this issue? I cannot in the latest version of chrome?

**Comment by charrondev** [comment]
Confirmed by @alex-mtl 
The issue here likely stems from checking `event.keyCode`. In any event that property is deprecated and we should update the usages in various components of ours.
