### ISSUE TITLE
Proposal: make "Vanilla.Discussions.Dismiss" a permission instead of a config setting

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#4100]
By now a forum admin can decide whether dismissing announcements is allowed or not: there is a global config setting for this. I think this feature would be much more powerful if an admin can make an announcement dismissable based on user role and category. This could be reached by using a permission instead of a config setting.

There must be a permission defined in /applications/vanilla/settings/structure.php and the only files where the config setting is used are:

/applications/vanilla/views/discussion/helper_functions.php
/applications/vanilla/controllers/class.discussioncontroller.php
/applications/vanilla/models/class.discussionmodel.php

So changing the way it works would technically be quite easy. I think even setting the permission when running utility/structure based on an existing config setting would make this change unnoticable for a working installation. 

What do you think of it? If you like to, I would try to write the pull request.

**Comment by linc** [comment]
I'd honesty like to just delete the "Dismiss" option entirely. I've never clicked it on purpose, and I've clicked it by accident SO many times and I have to undo it by editing the database. It's ridiculous and a failed experiment IMO.

**Comment by R-J** [comment]
Please don't take it personal, but I dismiss all announcements ;-)

I would miss that feature very much. Sticky threads are only temporarily useful and I like being able to decide when I do not need to see a thread any more.

**Comment by linc** [comment]
Well, adding a permission for it is definitely a non-starter. We want to simplify our permissions, not increase their granularity.
