### ISSUE TITLE
Error in file »class.database.php« at line 412: This command is not supported in the prepared statement protocol yet

### ISSUE THREAD

**Issue by tgp1994** [vanilla/vanilla#4101]
So far I've been following the vanilla porter guide to the letter (what a wonderful tool to have!), and everything has been going great. I put the zipped, exported database into the uploads folder, then when I went to navigate to the Import panel, Vanilla started throwing blank 500 responses at me. I ended up having to import my own "Mega PHP Debug" script at the top of index.php to get any sort of error output, which results in:

E_USER_ERROR Error in file »class.database.php« at line 412: This command is not supported in the prepared statement protocol yet 

Apparently this is referring to the codeblock:

```
catch (Gdn_UserException $uex) {
                trigger_error($uex->getMessage(), E_USER_ERROR);
```

Who knows what command it's actually referring to??

**MySQL 5.5.34**
**PHP Version 5.3.3**

**Comment by DaazKu** [comment]
Put `$Configuration['Debug'] = true;` in your conf/config.php
Post the resulting error here.

**Comment by tgp1994** [comment]
Yep, that was one of the first things I did, didn't make a difference in output though. I'll also add what versions of PHP and MySQL I'm using in a moment.

**Comment by DaazKu** [comment]
What version of vanilla are you using?

**Comment by tgp1994** [comment]
Version 2.2.1 (prebuilt), I also updated my original post with php and mysql versions.

**Comment by tgp1994** [comment]
I went into the class.database.php script where the problem was happening, and I went to insert some code that prints "Executing statement:" then the SQL statement directly below it. Here's what comes out:

> Executing statement:
> select * from GDN_User `User` where UserID = :UserID
> Executing statement:
> show tables like 'GDN_zTest'
> Executing statement:
> drop table `GDN_zTest`
> Executing statement:
> SHOW ENGINES;
> Executing statement:
> create table `GDN_zTest` ( `ID` int not null ) engine=innodb default character set utf8 collate utf8_unicode_ci;
> Executing statement:
> truncate table GDN_zTest;
> Executing statement:
> load data infile '[...]/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines
That last "SQL" statement (load data infile) is the last thing to print before the error pops up.

**Comment by DaazKu** [comment]
Can you replace that 
```php
                trigger_error($uex->getMessage(), E_USER_ERROR);
```
by
```php 
die('<pre>'.print_r([
    'backtrace' => debug_backtrace(false),
    'exception' => $e,
], true);
```

**Comment by tgp1994** [comment]
Hrmm...

> E_PARSE Error in file »class.database.php« at line 411: syntax error, unexpected '[', expecting ')' 

I was actually just working on getting a stacktrace for you, here's a massive one:

> #0 Gdn_Database->query(load data infile '[...]/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines, Array (), Array ([Type] => select,[Slave] => ,[ReturnType] => DataSet)) called at [[...]/htdocs/vanilla/library/database/class.sqldriver.php:1663]
> #1 Gdn_SQLDriver->query(load data infile '[...]/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines, select) called at [[...]/htdocs/vanilla/applications/dashboard/models/class.importmodel.php:1719]
> #2 ImportModel->query(load data infile '[...]/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines) called at [[...]/htdocs/vanilla/applications/dashboard/models/class.importmodel.php:1260]
> #3 ImportModel->_LoadTableOnSameServer(Test, [...]/htdocs/vanilla/uploads/import/test.txt) called at [[...]/htdocs/vanilla/applications/dashboard/models/class.importmodel.php:1413]
> #4 ImportModel->loadTableType() called at [[...]/htdocs/vanilla/applications/dashboard/controllers/class.importcontroller.php:233]
> #5 ImportController->index()
> #6 call_user_func_array(Array ([0] => ImportController Object ([Application] => Dashboard,[ApplicationFolder] => dashboard,[Assets] => Array (),[] => ,[ControllerName] => importcontroller,[CssClass] => ,[Data] => Array ([ImportPaths] => Array ([db:] => This Database,[[...]/htdocs/vanilla/uploads/export_a84345_forums_2016-06-14_191959.txt.gz] => export_a84345_forums_2016-06-14_191959.txt.gz),[Header] => Array (),[Stats] => Array (),[GenerateSQL] => ,[ImportPath] => ,[OriginalFilename] => ,[CurrentStep] => 0),[Head] => HeadModule Object ([] => Array (),[] => Array (),[] => ,[] => ,[] => ,[] => ,[AssetName] => ,[] => dashboard,[Data] => Array (),[] => ImportController Object ( *RECURSION*,[] => default,[Visible] => 1,[] => HeadModule,[EventArguments] => Array (),[Returns] => Array (),[HandlerType] => NORMAL,[FireAs] => ,[] => ,[] => ),[MasterView] => admin,[Menu] => MenuModule Object ([Items] => Array (),[HtmlId] => Menu,[CssClass] => ,[Sort] => Array ([0] => Dashboard,[1] => Discussions,[2] => Questions,[3] => Activity,[4] => Applicants,[5] => Conversations,[6] => User),[] => ,[AssetName] => ,[] => dashboard,[Data] => Array (),[] => ,[] => default,[Visible] => 1,[] => MenuModule,[EventArguments] => Array (),[Returns] => Array (),[HandlerType] => NORMAL,[FireAs] => ,[] => ,[] => ),[ModuleSortContainer] => ,[OriginalRequestMethod] => index,[RedirectUrl] => ,[ResolvedPath] => dashboard/import/index,[ReflectArgs] => Array (),[RequestArgs] => Array (),[RequestMethod] => index,[Request] => Gdn_Request Object ([] => 1,[] => Array ([CONFIGWEBROOT] => ,[CONFIGSTRIPURLS] => ,[HOST] => [...],[METHOD] => GET,[ADDRESS] => 127.0.0.1,[SCHEME] => http,[PORT] => 80,[URI] => /dashboard/import,[FOLDER] => vanilla/,[SCRIPT] => index.php),[] => Array ([Path] => dashboard/import,[OutputFormat] => default,[Filename] => default,[WebRoot] => vanilla,[Domain] => http://[...],[AssetRoot] => /vanilla),[] => ,[] => Array ([get] => Array (),[post] => Array (),[server] => Array ([downgrade-1_0] => 1,[force-response-1_0] => 1,[SCRIPT_URL] => /vanilla/index.php,[SCRIPT_URI] => [...]/vanilla/index.php,[SF_HOST_PREFIX] => axiomengine,[SF_PATH] => [...],[SF_USER] => axiomengine,[VHOST] => [...],[DOCUMENT_ROOT] => /var/www/html,[HTTP_HOST] => [...],[HTTP_CONNECTION] => close,[HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0,[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,[HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5,[HTTP_ACCEPT_ENCODING] => gzip, deflate,[HTTP_REFERER] => [...]/vanilla/index.php?p=/dashboard/statistics,[HTTP_COOKIE] => [...],[HTTP_PRAGMA] => no-cache,[HTTP_CACHE_CONTROL] => no-cache,[HTTP_X_REMOTE_ADDR] => [...],[PATH] => /sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin,[SERVER_SIGNATURE] =>
> Apache/2.2.15 (CentOS) Server at [...] Port 80
> ,[SERVER_SOFTWARE] => Apache/2.2.15 (CentOS),[SERVER_NAME] => [...],[SERVER_ADDR] => 127.0.0.1,[SERVER_PORT] => 80,[REMOTE_ADDR] => 127.0.0.1,[SERVER_ADMIN] => webmaster@sourceforge.net,[SCRIPT_FILENAME] => [...]/htdocs/vanilla/index.php,[REMOTE_PORT] => 49488,[GATEWAY_INTERFACE] => CGI/1.1,[SERVER_PROTOCOL] => HTTP/1.0,[REQUEST_METHOD] => GET,[QUERY_STRING] => p=/dashboard/import,[REQUEST_URI] => /vanilla/index.php?p=/dashboard/import,[SCRIPT_NAME] => /vanilla/index.php,[PHP_SELF] => /vanilla/index.php,[REQUEST_TIME] => 1465935481),[files] => Array (),[cookies] => [...],[SelfUrl] => dashboard/import,[StatusMessage] => ,[SyndicationMethod] => NONE,[Theme] => default,[ThemeOptions] => Array (),[View] => ,[] => Array ([0] => Array ([FileName] => admin.css,[AppFolder] => ,[Options] => ),[1] => Array ([FileName] => magnific-popup.css,[AppFolder] => ,[Options] => )),[] => Array (),[] => XHTML,[] => ALL,[] => ,[] => ,[] => Array ([X-Garden-Version] => Vanilla 2.2.1,[Content-Type] => text/html; charset=utf-8,[Cache-Control] => private, no-cache, no-store, max-age=0, must-revalidate,[Expires] => Sat, 01 Jan 2000 00:00:00 GMT,[Pragma] => no-cache),[] => Array ([0] => addasset,[1] => addbreadcrumb,[2] => addcssfile,[3] => adddefinition,[4] => addinternalmethod,[5] => addjsfile,[6] => addmodule,[7] => allowjsonp,[8] => canonicalurl,[9] => clearcssfiles,[10] => clearjsfiles,[11] => contenttype,[12] => cssfiles,[13] => data,[14] => definitionlist,[15] => deliverymethod,[16] => deliverytype,[17] => description,[18] => errormessages,[19] => fetchview,[20] => fetchviewlocation,[21] => finalize,[22] => getasset,[23] => getimports,[24] => getjson,[25] => getstatusmessage,[26] => image,[27] => informmessage,[28] => intitialize,[29] => isinternal,[30] => jsfiles,[31] => json,[32] => jsontarget,[33] => masterview,[34] => pagename,[35] => permission,[36] => removecssfile,[37] => render,[38] => xrender,[39] => renderasset,[40] => renderdata,[41] => renderexception,[42] => rendermaster,[43] => sendheaders,[44] => setdata,[45] => setformsaved,[46] => setheader,[47] => setjson,[48] => setlastmodified,[49] => statuscode,[50] => title),[] => Array (),[] => Array ([0] => Array ([FileName] => jquery.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[1] => Array ([FileName] => jquery.livequery.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[2] => Array ([FileName] => jquery.form.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[3] => Array ([FileName] => jquery.popup.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[4] => Array ([FileName] => jquery.gardenhandleajaxform.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[5] => Array ([FileName] => magnific-popup.min.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[6] => Array ([FileName] => jquery.autosize.min.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1),[7] => Array ([FileName] => global.js,[AppFolder] => ,[Options] => ,[Version] => 2.2.1)),[] => ,[] => Array (),[] => ,[] => ,[] => ImportController,[EventArguments] => Array (),[Returns] => Array (),[HandlerType] => NORMAL,[FireAs] => ,[] => ,[] => ,[PageName] => dashboard,[EnabledApplications] => Array ([0] => dashboard,[1] => conversations,[2] => vanilla),[Form] => Gdn_Form Object ([Action] => ,[ErrorClass] => Error,[HiddenInputs] => ,[IDPrefix] => Form_,[InputPrefix] => ,[Method] => post,[] => ,[] => ,[] => ,[] => Array (),[_FormValues] => Array ([PathSelect] => ),[] => Array (),[] => Gdn_Form,[EventArguments] => Array (),[Returns] => Array (),[HandlerType] => NORMAL,[FireAs] => ,[] => ,[] => )),[1] => index), Array ()) called at [[...]/htdocs/vanilla/library/core/class.dispatcher.php:329]
> #7 Gdn_Dispatcher->dispatch() called at [[...]/htdocs/vanilla/index.php:46]

**Comment by DaazKu** [comment]
I'm pretty sure the error comes from here:
https://github.com/vanilla/vanilla/blob/Vanilla_2.2.1/applications/dashboard/models/class.importmodel.php#L1219

Here is a patched version of that function
```php
    public function loadTable($Tablename, $Path) {
        $Type = $this->LoadTableType();
        $Result = true;


        if (in_array($Type, ['LoadTableOnSameServer', 'LoadTableLocalInfile', 'LoadTableWithInsert'])) {
            
            // LoadTableWithInsert be 15x slower than the other options.
            try {
                $this->{'_'.$Type}($Tablename, $Path);
            } catch(Exception $e) {
                $Result = false;
            }
        } else {
            throw new Exception("@Error, unknown LoadTableType: $Type");
        }

        return $Result;
    }
```

I did not test it but that should work.

**Comment by DaazKu** [comment]
Ho wait the test is done beforehand from what I can see from your stack trace...

**Comment by tgp1994** [comment]
Yeah I just implemented the patch, and interestingly it got through one statement before erroring out:

> Executing statement:
> select * from GDN_User `User` where UserID = :UserIDE_PARSE Error in file »class.importmodel.php« at line 1224: syntax error, unexpected '['

**Comment by tgp1994** [comment]
I modified the if statement to read `if (in_array($Type, array('LoadTableOnSameServer', 'LoadTableLocalInfile', 'LoadTableWithInsert'))) {` and it looks like we're off.

> Executing statement:
> select * from GDN_User `User` where UserID = :UserID
> Executing statement:
> show tables like 'GDN_zTest'
> Executing statement:
> drop table `GDN_zTest`
> Executing statement:
> SHOW ENGINES;
> Executing statement:
> create table `GDN_zTest` ( `ID` int not null ) engine=innodb default character set utf8 collate utf8_unicode_ci;
> Executing statement:
> truncate table GDN_zTest;
> Executing statement:
> load data infile '/home/project-web/axiomengine/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines
and the error occurs again.

**Comment by DaazKu** [comment]
I'm gonna have to install php5.3.

This try catch https://github.com/vanilla/vanilla/blob/Vanilla_2.2.1/applications/dashboard/models/class.importmodel.php#L1412
should capture the error and everything should run smoothly afterward...

**Comment by tgp1994** [comment]
Alright, thanks for doing that. This is really strange, my hunch is there's some funny Sourceforge fiddling going on in the background...

**Comment by DaazKu** [comment]
I cannot reproduce the error using:

**Vanilla 2.2.1**
**PHP 5.3.29**
**10.1.13-MariaDB Homebrew**

**Comment by tgp1994** [comment]
Why not MySQL?

**Comment by DaazKu** [comment]
Quick question, which requests were giving you error 500?

**Comment by tgp1994** [comment]
The same request to the import page/script, but php returns 500 unless you have this error reporting, otherwise it returned 200.

**Comment by DaazKu** [comment]
So that query failing is something normal and it should not be the cause of the errors 500.

After more tests I did end up with some error 500.
![screen shot 2016-06-15 at 9 43 19 am](https://cloud.githubusercontent.com/assets/2412909/16081927/a818afc4-32dd-11e6-9cde-ff5572f40428.png)

```
jquery.min.js:6 GET http://vanilla.dev/dashboard/log/count/moderate?DeliveryType=VIEW 500 (Internal Server Error)send @ jquery.min.js:6ajax @ jquery.min.js:6(anonymous function) @ global.js?v=2.2.1:653each @ jquery.min.js:4each @ jquery.min.js:4$.fn.popin @ global.js?v=2.2.1:650(anonymous function) @ global.js?v=2.2.1:668c @ jquery.min.js:4fireWith @ jquery.min.js:4ready @ jquery.min.js:4q @ jquery.min.js:4
jquery.min.js:6 POST http://vanilla.dev/dashboard/import/go?DeliveryType=VIEW&DeliveryMethod=JSON 500 (Internal Server Error)send @ jquery.min.js:6ajax @ jquery.min.js:6refreshSteps @ import.js?v=2.2.1:7(anonymous function) @ import.js?v=2.2.1:51c @ jquery.min.js:4fireWith @ jquery.min.js:4ready @ jquery.min.js:4q @ jquery.min.js:4
jquery.min.js:6 POST http://vanilla.dev/dashboard/notifications/inform 500 (Internal Server Error)
```

I have no clue why but enabling the xdebug extension for php fixed these..

If you are experiencing the same issue on a fresh install, you can just refresh until the import is done.

I'll investigate the issue on my side.

**Comment by tgp1994** [comment]
Does refreshing actually help it along though? I'm wondering if it may be an issue with the actual database it's trying to import, perhaps there was an issue when it got exported... Thank you for continuing to investigate this.

**Comment by DaazKu** [comment]
Refreshing helps if you experience the same errors that I've described above, in my case I could finish the export by refreshing.

**Comment by tgp1994** [comment]
Would it be helpful if I gave you a copy of the exported database to see if that might be the culprit?

**Comment by DaazKu** [comment]
I could try that.

**Comment by DaazKu** [comment]
PM me the export.

**Comment by tgp1994** [comment]
@DaazKu I wanted to follow up and say that I emailed the archive to you based on the email address you had posted on GitHub, I'm not sure how to do a PM here.

**Comment by DaazKu** [comment]
I'll try to test with your export today.

**Comment by DaazKu** [comment]
Works like a charm for me.

**Comment by tgp1994** [comment]
Huh, I just tried uploading my own copy with the same PII removed, and it still tries to run this query and failes:

> load data infile '/home/project-web/axiomengine/htdocs/vanilla/uploads/import/test.txt' into table GDN_zTest character set utf8 columns terminated by ',' optionally enclosed by '"' escaped by '\\' lines terminated by '\n' ignore 1 lines

**Comment by tgp1994** [comment]
So I ended up creating my own AMP environment just to get the import done, and naturally it works just like yours. I tried ticking the box for "generate SQL statements" under advanced but it would consistently error out saying something about a users table not existing? Can you reproduce this?
