### ISSUE TITLE
Fatal Error in SetupController.Index();

### ISSUE THREAD

**Issue by Flashbacker** [vanilla/vanilla#4102]
thats happen on my FIRST install of vanilla.. i have no idea what to do.. please help

Vanilla has already been installed.
The error occurred on or near: /var/www/html/applications/dashboard/controllers/class.setupcontroller.php
51:       // Fatal error if Garden has already been installed.
52:       
53:       $Installed = Gdn::Config('Garden.Installed') ? TRUE : FALSE;
54:       if ($Installed)
55:          throw new Exception('Vanilla has already been installed.');
56:       
57:       if (!$this->_CheckPrerequisites()) {
58:          $this->View = 'prerequisites';
59:       } else {
Backtrace:
/var/www/html/applications/dashboard/controllers/class.setupcontroller.phpSetupController->Index();
[/var/www/html/library/core/class.dispatcher.php:322] PHP::call_user_func_array();
[/var/www/html/index.php:53] Gdn_Dispatcher->Dispatch();

    Application: Vanilla
    Application Version: 2.0.18.8
    PHP Version: 5.5.9-1ubuntu4.17
    Operating System: Linux
    Server Software: Apache/2.4.7 (Ubuntu)
    Referer: http://46.101.230.227/index.php?p=/dashboard/setup
    User Agent: Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0
    Request Uri: /index.php?p=/dashboard/setup
    Controller: SetupController
    Method: Index

**Comment by linc** [comment]
Start a discussion on the community forum for assistance: https://vanillaforums.org/discussions

This is very likely an issue with your configuration / server and not a product issue. If however it turns out to be something we can accommodate for, please feel free to revisit it here with additional information later. :)
