### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by garygreen** [vanilla/vanilla#4109]
Any idea / estimate when Vanilla will be compatible? It's the only thing holding up upgrading our servers.

**Comment by linc** [comment]
Evaluating the 2.3 beta and letting us know how it goes on the forum would make it go faster. :) Testing and any final bug fixes is all that's left.

**Comment by garygreen** [comment]
Ok cool, will give it a go. Any upgrade guide for 2.3 so far, anything special or just update files as per usual?

**Comment by linc** [comment]
Pretty standard stuff. Details here: https://vanillaforums.org/discussion/32168/vanilla-2-3-beta
