### ISSUE TITLE
Approving comments don’t update the latest post on categories

### ISSUE THREAD

**Issue by multiaki** [vanilla/vanilla#4115]
I see the issue with the latest post on categories. When moderated post is moderated and approved, the latest post doesn't show the approved comment as the latest.

Using Version 2.2.100.1

**Comment by ralphbrooker** [comment]
Any response?

**Comment by linc** [comment]
This should get confirmed on master branch, first.

**Comment by linc** [comment]
I believe this is the fix: https://github.com/vanilla/vanilla/pull/5422
