### ISSUE TITLE
Cannot create Category when MySQL Strict mode is enabled

### ISSUE THREAD

**Issue by raykai** [vanilla/vanilla#4117]
we get a error when we create a new Category in the dashboard with MySQL 5.7 when Strict mode is enabled. 

works well when Strict mode is off

**Comment by DaazKu** [comment]
What version of vanilla are you using?

**Comment by DaazKu** [comment]
As of now I cannot reproduce the error with
```
sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

**Comment by DaazKu** [comment]
Tested with both PerconaDB and MariaDB.
