### ISSUE TITLE
"Agree to TOS" and "Remember me" check boxes overlapped

### ISSUE THREAD

**Issue by bobopuppyhead-666** [vanilla/vanilla#4131]
Having an issue... the bottom two check boxes on registration page are overlapped (example: http://intua.net/forums/entry/register?Target=categories ), making it impossible to register for the forum due to not being able to agree to the TOS. The check box which is visible is the "remember me" one.

Have tried with Chrome, Safari, IE... always the same in all browsers.

**Comment by beckyvb** [comment]
This is an issue with the theme's CSS, specifically the `position: absolute;` property set on the `form ul li>label` element. The issue needs to be addressed there.
