### ISSUE TITLE
Upload New Picture button in IE not working

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#4139]
Currently: clicking button via edit profile not opening option to add image.

Expected: Choose File pop-up. 

<img width="678" alt="upload" src="https://cloud.githubusercontent.com/assets/15787691/16422783/a3b11256-3d27-11e6-9fbc-650b5185f6db.png">
<img width="708" alt="upload-1" src="https://cloud.githubusercontent.com/assets/15787691/16422784/a3c123bc-3d27-11e6-9811-231a2e21e207.png">

**Comment by DaazKu** [comment]
I'm pretty sure it won't work anywhere (Not just ie). That javascript appear to be invalid.

**Comment by DaazKu** [comment]
https://github.com/vanilla/vanilla/blob/b9fd9264f08fdf5ee5d41e0b7da4bd407ceb8904/applications/dashboard/js/profile.js#L5

Should probably be 
```js
$(".js-new-avatar-upload", $(this).closest('form')).trigger("click");
```

**Comment by matthewbienz** [comment]
I can't replicate in Safari, Chrome, or in Firefox.

**Comment by DaazKu** [comment]
TIL that modern browsers have a native closest method: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

But still. The proposed fix is the solution :D.
