### ISSUE TITLE
Invitations profile page has no pagination

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4142]
There's no way to access more than the last 30 invitations sent from the My Invitations page.

**Comment by linc** [comment]
This is as-intended. There's no pagination because the system isn't designed for mass-invitations. We can increase the limit to 50 but we're not adding this feature.

**Comment by linc** [comment]
https://github.com/vanilla/vanilla/commit/86f1fd282d77d9577492d2ed4582c31777d3daa4
