### ISSUE TITLE
Add ability to set locale of login / registration pages

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4148]
A URL parameter of locale should be accepted (via Multilingual?) to set the language of the `/entry` pages. This would allow a website owner to send users to a language-appropriate gateway page to the forum.

**Comment by charrondev** [comment]
Issue moved to [vanilla/addons #671](https://github.com/vanilla/addons/issues/671) via [**ZenHub**](https://www.zenhub.com/)

**Comment by charrondev** [comment]
I've moved this to the `addons` repo where the `Multilingual` plugin lives.
