### ISSUE TITLE
Support flat categories in category management

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#4155]
Update the dashboard v3 manage categories page to support the flat display type.

- [x] Add the "flat" option to the display as dropdown. There should already be an icon for it.
- [x] Rename the "categories" label to "nested".
- [x] A category with display as of "flat" should display as a link, just like display as "categories". Clicking on the link will nest into it.
- [x] When editing a flat category it will not apply the nested jquery code and the categories will not be able to be ordered. They should be sorted in alphabetical order and be paged. The CSS will otherwise be the same. The handles and expand/collapse buttons should naturally not show.
- [x] When a category in this view has child categories then it should display as a link to edit the children.

**Comment by tburry** [comment]
This task could take more than 12 hours. @linc can you create a part 2 and give it another 8 hours maybe?

**Comment by initvector** [comment]
Closed by #4384 and #4387
