### ISSUE TITLE
Add forwards-compatible methods to Gdn_Request

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#4162]
We are eventually going to want to replace Gdn_Request, but it's going to take a while to untangle. Before that I want to add new-style methods to Gdn_Request that the dispatcher will use.

Here are the additions. Setters should be chainable.

```php
const METHOD_HEAD = 'HEAD';
const METHOD_GET = 'GET';
const METHOD_POST = 'POST';
const METHOD_PUT = 'PUT';
const METHOD_PATCH = 'PATCH';
const METHOD_DELETE = 'DELETE';
const METHOD_OPTIONS = 'OPTIONS';

getHost(), setHost($host)
getHostAndPort()
getScheme(), setScheme($scheme)
getIP(), setIP()
getPath(), setPath($path)
getExt(), setExt($ext)
getPathExt(), setPathExt($path)
getFullPath(), setFullPath() // root + path ext
getRoot(), setRoot($root)
getPort(), setPort($port)
getQuery(), setQuery(array $query), mergeQuery(array $query)
getQueryItem($key, $default = null), setQueryItem($key, $value)
getBody(), setBody(array $body) // this is the post data
getUrl(), setUrl($url) // should parse into parts
```

The long-term goal is to make a request object that has just these methods (+few more probably) and isn't tied to superglobals. We can then add the superglobal parsing to a subclass or elsewhere.

**Comment by tburry** [comment]
Some of these methods should be robust enough to handle a bit of parsing. Check out https://github.com/vanilla/garden/blob/master/src/Request.php#L942 for an example.

**Comment by tburry** [comment]
One annoyance I'd like to see cleared up is with slashes.

- getPath() should always have a leading slash and setPath() should correct for this.
- getRoot() should have a leading slash and no trailing slash unless there is no root in which case it should be empty.

In this way we can make a url our of scheme + hostAndPort + root + path.

Correcting for inappropriate slashes in getters will be nice for programmers.

**Comment by initvector** [comment]
Closing in favor of tracking the issue via the associated PR
