### ISSUE TITLE
Double Spacing in Plain Text Emails

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4183]
Plain text emails have an awful lot of whitespace in them due to double spacing between segments.  This is due to Vanilla [double spacing every segment](https://github.com/vanilla/vanilla/blob/5b87f1de5f1eae532ae42a7907574234d9a36c21/applications/dashboard/library/class.emailtemplate.php#L473).

Maybe some segments need double spacing, but I don't believe *all* of them do.

**Comment by DaazKu** [comment]
How about:

```php
        // Let's add an arbitrary number of <br> in between sections!
        $final = '';
        $count = count($email);
        for($i = 0; $i < $count; $i++) {
            $final .= $email[$i];
            if ($i - 1 !== $count) {
                $nbs = rand(1, 2);
                for ($j = 0; $j < $nbs; $j++) {
                    $final .= '<br>';
                }
            }
        }

        return Gdn_Format::plainText(Gdn_Format::text($final));
```

**Comment by initvector** [comment]
![](http://i.giphy.com/FmyCxAjnOP5Di.gif)

**Comment by DaazKu** [comment]
http://i.imgur.com/a1kZvYb.gif

Because that would be dumb!
