### ISSUE TITLE
Comment draft count persisting after discussion deleted

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4187]
If you save a comment draft on a discussion, then delete the discussion, your comment/draft disappears but your draft count remains unchanged.

### Steps to reproduce
1. Open a comment on an existing discussion.
2. Click "Save Draft" to save your comment.  Do not post it.
3. Note your "My Drafts" count.
4. Delete the discussion your comment draft is associated with.
5. Compare your current "My Drafts" count against the number you recorded in step 3.  They should be the same.
6. Visit the "My Drafts" page.  You should not see your comment draft displayed.

**Comment by bleistivt** [comment]
Dupilcate of #1922
