### ISSUE TITLE
Profile Extender checkboxes not showing up on registration

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4191]
It looks like we're explicitly disallowing checkboxes being displayed on the registration form, even though the checkbox type is hardcoded to be displayed on registration.

See [class.profileextender.plugin.php:85](https://github.com/vanilla/vanilla/blob/6081c14450bd733aacc4e65187019a89e6aabce5/plugins/ProfileExtender/class.profileextender.plugin.php#L85)
Also [class.profileextender.plugin.php:309](https://github.com/vanilla/vanilla/blob/6081c14450bd733aacc4e65187019a89e6aabce5/plugins/ProfileExtender/class.profileextender.plugin.php#L309)

**Comment by linc** [comment]
The very next method's docblock is "Add checkbox fields to registration forms." We're just doing it at a different hook is all.
