### ISSUE TITLE
Disallow Emoji being used as subject

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4196]
Currently, when someone creates a discussion with a subject using an emoji (as in the kind used on mobile devices), this results in an inaccessible discussion with a blank subject line. We should either render the emoji or, perhaps simpler, just disallow these non-standard characters from being used in subjects.

**Comment by DaazKu** [comment]
Kinda related: [It is possible to create a discussion with empty characters as title and body.](https://github.com/vanilla/vanilla/issues/3656)
