### ISSUE TITLE
Share This buttons are cut off in most themes

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4200]
See cornerstone for example: ![screen shot 2016-07-25 at 10 29 46 am](https://cloud.githubusercontent.com/assets/2412909/17104849/c1205a28-5252-11e6-88d6-54f48e8fa1c0.png)

Does the same thing in Deflector, Bootstrap 3, Triple A

**Comment by linc** [comment]
This is in the addons repo.

**Comment by slafleche** [comment]
In PR https://github.com/vanilla/addons/pull/405
