### ISSUE TITLE
Suggestion for editable, multilingual content

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4202]
It would be really useful to have something similar to the WordPress plugin [Advanced Custom Fields](https://www.advancedcustomfields.com/pro/). It allows to easily add custom fields, editable by the client. A dev would have control over which fields are multilingual and which are repeatable. They would be accessible in Smarty for custom theming.

I have 2 use cases:
1. The client has a carousel. They would like to edit the content without needing to call support and getting it done by us. They also need to be able to edit the text for each language enabled.
2. The client wants to have language specific content in their footer. 
## 

For example: a dev could create a "carousel" page in the dashboard.  The carousel has an integer field: the animation speed. It also has a multilingual field: a title. We can also specify repeatable "blocks", like a "slide block", that would contain an image and a multilingual text field.

**Comment by slafleche** [comment]
It also needs to be possible to change the order of the repeatable blocks.

**Comment by charrondev** [comment]
The system for this is being implemented with https://github.com/vanilla/knowledge/issues/1196
