### ISSUE TITLE
Dashboard v3: Style plugin pages

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4207]
All plugin settings pages that look wonky should go in this list

- [x] Flagging
- [x] Touch Icon
- [x] Vanillicon
- [x] Who's Online
- [x] Delete Status (Ideation)
- [x] Event Log (header, mostly)
- [x] Vanilla Pop (header, help)
- [x] Q&A
- [x] Share This
- [x] autosignout
- [x] cleanspeak
- [x] reporting
- [x] sitemaps
- [x] spoof
- [x] microsoft
- [x] salesforce
- [x] viglink
- [x] zendesk
- [x] Custom Domain
- [x] Community Reporting
- [x] vanilla support
- [x] badge requests
- [x] mailchimp 
- [x] import
- [x] sphinx
- [x] feed discussions
- [x] outgoing email (inf)
- [x] disqus

**Comment by kaecyra** [comment]
**Event Log**

Looks like the table isn't full width, and the header has some weird anomalies.
![screen shot 2016-07-29 at 3 48 41 pm](https://cloud.githubusercontent.com/assets/248212/17261492/062fea30-55a4-11e6-8483-f7af7f2c70e1.png)
