### ISSUE TITLE
Dashboard v3: Retrieve images for /homepage settings page

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4214]
The images in /dashboard/settings/homepage come from a sprite sheet and are poor resolution. It would be nice to get a few screenshots from a Bootstrap 3 theme showing these options.

**Comment by DaazKu** [comment]
![screen shot 2016-08-23 at 10 32 46 am](https://cloud.githubusercontent.com/assets/2412909/17896007/0b24295c-691d-11e6-8184-38c7024571ef.png)
![screen shot 2016-08-23 at 10 31 46 am](https://cloud.githubusercontent.com/assets/2412909/17896009/0b3b5d34-691d-11e6-85c6-67edd9c23ec9.png)
