### ISSUE TITLE
Dashboard v3: Toggle load state

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4225]
In the mockups, the toggle originally had a load state. When waiting for an ajax response, a rotating, circular svg should appear in the toggle slider, and the switch should linger in the middle of the toggle well. This hasn't been implemented yet.

**Comment by linc** [comment]
What does this mean?

**Comment by beckyvb** [comment]
Like, when we ajax enable something, there should be some kind of load spinner in the toggle to indicate that the action is pending.

**Comment by tburry** [comment]
Closing since we won't deal with this anytime soon.
