### ISSUE TITLE
'Message' assigned to New Discussion page + a specific category are not displayed when category is selected via dropdown

### ISSUE THREAD

**Issue by verymilan** [vanilla/vanilla#4230]
Hi, i just noticed that messages (above content) for new discussions are only displayed when the discussion is started from the specific category.

If you start the discussion from the main page and select the category, the message will not be shown.
My vanilla instance is on the beta preview state.

**Comment by linc** [comment]
This would require a new endpoint to accommodate since you'd need to do this dynamically.
