### ISSUE TITLE
Dashboard v3: Links & Permission issue

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#4235]
Mebox, notifications are unclear. I have 2 notifications and no way to see them.

![image](https://cloud.githubusercontent.com/assets/425366/17260834/a21c400a-55a0-11e6-8eee-5789b13edbdf.png)

As admin I cannot access http://wqxyz.vanillademo.com/dashboard/settings/plugins, because I should be going to http://wqxyz.vanillademo.com/dashboard/settings/addons instead  (on hosted).

Customer support link at the bottom is in yellow and hard to read.

In customize theme, these links need to be updated:
![image](https://cloud.githubusercontent.com/assets/425366/17261050/fdf223ee-55a1-11e6-9bb2-a87ed57b2e0c.png)

"Our Custom HTML Documentation", should link to http://blog.vanillaforums.com/help-tutorials/how-to-use-custom-theme-part-1-edit-html/. It needs a refresh, or should be added to docs, and linked there. Or link them to here: https://blog.vanillaforums.com/help/vanilla-custom-themes/

"Our Custom CSS Documentation" links to http://vanillaforums.com/help/customcss which-leads to nowhere.

**Comment by beckyvb** [comment]
Fixed, thanks!
