### ISSUE TITLE
Dashboard v3: Badges nav bugged

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4237]
**Call to a member function addGroupToGlobals() on null**

Backtrace:
[/var/www/frontend-9ee4995009db8a/library/core/class.controller.php:1860] PHP::include();
[/var/www/frontend-9ee4995009db8a/library/core/class.controller.php:1321] Gdn_Controller->renderMaster();
[/var/www/frontend-9ee4995009db8a/library/core/class.pluggable.php:199] Gdn_Controller->xRender();
[/var/www/frontend-9ee4995009db8a/plugins/badges/controllers/class.badgecontroller.php:44] Gdn_Pluggable->__call();
[/var/www/frontend-9ee4995009db8a/library/core/class.dispatcher.php:305] BadgeController->all();
[/var/www/frontend-9ee4995009db8a/index.php:39] Gdn_Dispatcher->dispatch();

81:         $dashboardNav = $this->Assets['Panel']['DashboardNavModule'];
82:         $dashboardNav->addGroupToGlobals('', 'globals', 'globals');
83:         $dashboardNav->addLinkToGlobals(t('Sign Out'), SignOutUrl(), 'globals.sign-out');

**Comment by beckyvb** [comment]
This is resolved.
