### ISSUE TITLE
Gifv embed doesn't work in Markdown image tags

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4243]
Markdown formatter.

This embeds: `https://i.imgur.com/Y7v97o4.gifv`

This displays nothing: `![](https://i.imgur.com/Y7v97o4.gifv)`

Folks natural inclination is to use the Advanced Editor to declare it an image URL, so we should support both.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
