### ISSUE TITLE
Regenerate thumbnails

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4245]
We should create an endpoint to regenerate thumbnails in batches. Changing thumbnail size due to theming is not retroactive; the software would need to re-sample the original fullsize image. Side effects would include killing any custom-selected thumbnails.

**Comment by linc** [comment]
Replaced by https://github.com/vanilla/vanilla/issues/4245

**Comment by Charrondev** [comment]
You likely meant this one https://github.com/vanilla/vanilla/issues/4947.

**Comment by linc** [comment]
I did indeed.
