### ISSUE TITLE
Deleting a user's content leaves orphaned conversation messages

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4260]
We delete both the Conversation the deleted user created (or updated) and any conversation messages they've created. This leaves orphaned conversation messages and messes with the CountUnreadConversations, as users may have unread conversation messages but no conversations they belong to.

I think we could just clear out the user's ConversationMessages and perhaps the Conversation if they are the sole contributor.

This issue was identified by a user having inbox notifications, but no inbox messages.

**Comment by linc** [comment]
One scenario to consider here is whether the deleted user is a spammer, and you're trying to prevent a spam conversation from being seen. On the one hand, it's desirable to do that. On the other, they've probably already gotten an email about it which will be confusing, and there are cases where you wouldn't want multi-person conversations deleted that they started.

Short of creating an additional option in the delete sequence for this, I still think annihilation is the correct strategy.
