### ISSUE TITLE
SubcommunityToggleModule add language to link

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4263]
The SubcommunityToggleModule generates a list of links, but there is no indication of the language. There should either be a class, or a data attribute with the language key. 

Example:

`<a href="//localhost/en" data-lang="en" class="active nav-link">English</a>`

**Comment by linc** [comment]
Issue moved to [vanilla/multisite #158](https://github.com/vanilla/multisite/issues/158) via [**ZenHub**](https://www.zenhub.com/)
