### ISSUE TITLE
Discussion "Switch type" option

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4271]
So far we have Q&A and Ideation that both introduce new Types of discussions. There is a discrete process for switching types, and new options are needed in the discussion menu to allow for it.

My proposal is a "Switch type" or "Convert" option that:
- Has a basic form popup view that 1 or more plugins can hook into.
- Fires a generic "Convert" event that plugins can hook into.

This will de-duplicate similar code in addons and give us a clean way of extending this feature as we increase the number of plugins relying on it.

**Comment by RobertBil** [comment]
Hi..i am a new user here. I can try to sort out your problem. Can you please explain whole of your problem? Just share the all related details and i will try to sort it out. Because i also faced the similar type of problem.

**Comment by linc** [comment]
Supplanted by https://github.com/vanilla/vanilla/issues/5387
