### ISSUE TITLE
Markdown link code displaying in Promoted Content Module

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4282]
When Markdown is the input formatter and a link is part of the excerpt in the Promoted Content Module, the code for the link is displaying. We should be stripping this entirely so it doesn't display or we should parse it all. Given this past issue (https://github.com/vanilla/vanilla/issues/3725), I presume stripping the formatting is the choice we're aiming for.

Please see attached screenshot to see an example of the markdown code appearing. 

![promotedcontentmarkdown](https://cloud.githubusercontent.com/assets/8974997/17450221/17d6eae8-5b2d-11e6-87cd-fa31f1e39653.png)

**Comment by DaazKu** [comment]
Not a bug! [Theming issue](https://github.com/vanillaforums/sega/blob/master/themes/dawnofwar/views/modules/helper_functions.php)
