### ISSUE TITLE
MorePager throws fatal error on /profile/notifications

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4289]
> Fatal error
> Aug 08 14:21:01
> Access level to MorePagerModule::$_Totalled must be public (as in class PagerModule) in /var/www/frontend-1c343b5de61808/applications/dashboard/modules/class.morepagermodule.php on line 14

This was found in the error log for cl212

**Comment by kaecyra** [comment]
Example: http://joe.vanillademo.com/profile/notifications

**Comment by linc** [comment]
Appears to have been fixed.
