### ISSUE TITLE
Modern favicon support

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4291]
Nowadays, supporting favicons for all devices is quite complex (https://github.com/audreyr/favicon-cheat-sheet)

Not all clients are going to want to set up all of those favicons, but wanting iPhone and Android home screen icons are not that uncommon. Maybe we can automate resizing of the most common favicon formats from a single image and then if the client really wants to, they can set them individually.

I would also add "theme color" support. Far from perfect browser support for now, but it's easy to add and adds a nice touch. Supported in Chrome, Windows Phone, iOS (with more restricted options) and it's coming to FF (https://bugzilla.mozilla.org/show_bug.cgi?id=1098544)

**Comment by linc** [comment]
We support home screen icons with the Touch Icon addon.

**Comment by beckyvb** [comment]
I agree with @slafleche It would be cool to get on the theme-color/favicon/touch-icon to a settings page in the dashboard in core. It wouldn't take much to implement and would be a nice little feature.

**Comment by bleistivt** [comment]
This issue can be closed. "Touch Icon", "Share Image" & "Mobile Address Bar Color" options are all part of the new dashboard

**Comment by charrondev** [comment]
Agreed.
