### ISSUE TITLE
During setup, folder permissions error persists after chmod 777

### ISSUE THREAD

**Issue by mwcz** [vanilla/vanilla#4294]
I'm attempting to install Vanilla on Fedora 24 under Apache.  `/var/www/html/vanilla` and all its children are owned by the `apache` user, and I've chmodded `cache`, `conf`, and `uploads` as suggested.

    $ ls -l /var/www/html/vanilla
    drwxrwxrwx.  3 apache apache  4096 May  7 09:14 cache
    drwxrwxrwx.  2 apache apache  4096 Aug  9 14:49 conf
    drwxrwxrwx.  2 apache apache  4096 May  7 09:14 uploads
    [ ... more ... ]

But Vanilla still says:

> Some of your folders do not have the correct permissions.
>
> Using your ftp client, or via command line, make sure that the following permissions are set for your vanilla installation:
> 
> chmod -R 777 /var/www/html/vanilla/conf
> chmod -R 777 /var/www/html/vanilla/uploads
> chmod -R 777 /var/www/html/vanilla/cache

I'm able to become the `apache` user and write files in those directories.

    $ sudo -u apache -s
    $ touch /var/www/html/vanilla/conf/foo
    $ mkdir /var/www/html/vanilla/conf/bar

Any ideas why `IsWritable` is still returning false for those directories?

**Comment by linc** [comment]
I suggest seeking assistance from the community on the forum since this is more likely a setup than a software issue. I'd also verify apache is really running as that user, and that you have PHP installed as an Apace module.
