### ISSUE TITLE
Accessibility: Redundant links

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#4297]
Members using assistive technology to have ability to easily listen to links without unnecessary duplication. 

On the discussion page the image and username both link to the same place but are in different <a tag - this causes the screenreader to read out the same thing twice. 

Current: 

```
<a title="JohnSmith" href="/profile/JohnSmith" class="PhotoWrap"><img src="..." alt="JohnSmith" class="ProfilePhoto ProfilePhotoMedium"></a> 
<a href="/profile/JohnSmith" class="Username">JohnSmith</a> 
```

Possible: 
`<a title="JohnSmith" href="/profile/JohnSmith" class="PhotoWrap"><img src="..." alt="JohnSmith" class="ProfilePhoto ProfilePhotoMedium">JohnSmith</a>`

**Comment by slafleche** [comment]
In this particular case, I think we can just assign a `aria-hidden="true"` on the image IF we also have the the link there.
