### ISSUE TITLE
Tagging box "trap"

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#4298]
Add ability for keyboard user to be able to add tags to a post, and then submit the post. 

Keyboard users gets stuck in the tagging box. Normally pressing tab moves the user to the next element, but that's not possible here.

**Comment by linc** [comment]
It's also been reported the 'Enter' button submits the discussion when the tagging box is active. This should also be investigated and remedied as part of this.

**Comment by DaazKu** [comment]
I could not reproduce the 'Enter' problem. The code also prevents it so..
