### ISSUE TITLE
Don't strip question marks and periods from usernames

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4308]
* We currently block questions marks and periods by stripping them before building our user URLs.
* We don't necessarily block users from getting those names (ex: SSO) but then their profile is a 404.
* Can we safely remove that old character stripping provision now?

**Comment by DaazKu** [comment]
Completely removing the line that strip `?` and `&` works great if you are not using the p parameter at all.

If you use nginx location like so:
```nginx
    rewrite ^(.*) /index.php?p=$uri last;
```
you will encounter a bug that is fixed by the code below
```php
        // Make sure that the name will not be split if the p parameter is set.
        // Prevent p=/profile/a&b to be translated to $_GET['p'=>'/profile/a?', 'b'=>'']
        $UserName = str_replace('&', '%26', $UserName);
```

**Comment by linc** [comment]
Let's use the encoding then to preserve it for now. I'm not ready to jettison this compatibility today.
