### ISSUE TITLE
Unicode emoji can be inserted in post, but cannot save & truncates

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#4309]
You are able to add a mobile devices native emojis into our editor when making a post, however these emoji cannot be processed by the database causing the post to cut off where ever one was inserted. Either support for the emoji should be implimented, or the ability to do this from mobile devices should be somehow blocked.

**Comment by linc** [comment]
Solution has two components:

* Using `utf8mb4` encoding for databases whenever available and providing a migration path.
* Either removing or throwing an error regarding Unicode emoji when not allowed by the database.

**Comment by beckyvb** [comment]
This also affects desktop users. Copy-and-pasting unicode emoji 👾 into a post will preview ok, but will truncate a post when saving.

**Comment by DaazKu** [comment]
It is not only affecting emojis but every characters encoded on 4 bytes.
We should think about defaulting to utf8mb4 instead of utf8.

The following configuration needs to be updated:
```json
    "Database": {
        "CharacterEncoding": "utf8mb4",
        "ConnectionOptions": {
            "1002": "set names 'utf8mb4'"
        },
        "ExtendedProperties": {
            "Collate": "utf8mb4_unicode_ci"
        }
    }
```

**Comment by DaazKu** [comment]
See: https://github.com/vanilla/vanilla/issues/5229
