### ISSUE TITLE
Inconsistent array vs object in JSON payload for discussion list

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4310]
Found on a site:

Page 2 was structure like this:

    "Discussions": {
        "0": {

All other pages looked like this:

    "Discussions": [
        {

Reportedly, the page(s) effected shifted over time, implying either a discussion condition (perhaps an announcement status not pinned in the current view or dismissed) that causes its page to show as the incorrect data type.

Refer to https://vanillaforums.teamwork.com/#tasks/4017520 internally for client details.

**Comment by DaazKu** [comment]
This has to be an unset() on the array called from somewhere.

I bet 100$ that the numbers go from 0 to X with one missing somewhere.

[removeAnnouncements()](https://github.com/vanilla/vanilla/blob/f9273a206c1adc08d5aa64ba843d6dc7404288e9/applications/vanilla/models/class.discussionmodel.php#L849) account for that.
