### ISSUE TITLE
Badge API not returning all a user's badges

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#4322]
When using badge API endpoint to retrieve a user's badges, not all badges are being returned.  Does not seem to be returning most recently acquired badges as expected.

**Comment by charrondev** [comment]
Issue moved to [vanilla/internal #1793](https://github.com/vanilla/internal/issues/1793) via [**ZenHub**](https://www.zenhub.com/)

**Comment by charrondev** [comment]
I've moved this to internal where the `badges` plugin lives.
