### ISSUE TITLE
Invalid username requires additional page requests when connecting with SSO

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4330]
If a user is registering on the forum via SSO and provides an invalid username, say a name that is too short, they are given an error indicating so (e.g. "Usernames must be 3-20 characters...").  However, the username field no longer appears on the page.  The user has to click the "Connect" button again, which loads a new page with a "Username is required" error, but this time the username field appears on the page.

It would be ideal if the username field appeared on the same page as the original username error, so the user didn't have to step through multiple pages and an additional error to enter a new username.

Tested with SAML SSO.

**Comment by DaazKu** [comment]
I could not reproduce the issue.

I tried with and without AutoConnect set to true.
With and without Name, Fullname, ConnectName value filled.
With and without an existing account.
With and without an entry in the UserAuthentification table.

Can you still reproduce the issue? If not close it.

**Comment by initvector** [comment]
I can no longer recreate this issue, so I'm going to assume it's been fixed.
