### ISSUE TITLE
Subcategories on "Discussions" category display should respect category layout

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4331]
When you configure a category to display as discussions, the category's discussions are displayed when viewing that category, along with a list of child categories.  The display of the child categories is hardcoded to be in the "list" format.  It would be ideal if it respected the "Categories Layout" setting and could be displayed in the "table" format.

When viewing all categories (e.g. `/categories`), we need a way to display a category, complete with child categories (even in a comma-delimited list).  When viewing that same category with subcategories, we need to be able to see category data in the "table" format.  Here's why our display types don't currently do that:

1. Discussions - If categories are displayed, they're displayed as a list.
2. Nested Categories - Does not display child category information when in a list of categories.
3. Flat Categories - Does not display child category information when in a list of categories.

For the time being, we've kludged the Heading display type to do this (https://github.com/vanilla/vanilla/pull/4329).  When this issue is resolved, that kludge should be reverted.

**Comment by linc** [comment]
It's a bit of weirdness to me that we allow a heading under a heading, and the result of that in the view is to be a clickable subcategory. That kludge almost makes sense because of that weird behavior, so I wonder if we should also address that before removing it.

**Comment by linc** [comment]
This will need feedback from @beckyvb and @tburry before we move on it since this is a tricky thing that effects theming. I've put it in a sprint simply so we don't forget to discuss it further in the coming month.
