### ISSUE TITLE
Unable to create sub communities

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4335]
I get the following error when I try and create a third sub community:

Duplicate entry '0' for key 'UX_Subcommunity_IsDefault'|Gdn_Database|Query|insert GDN_Subcommunity (`Name`, `Folder`, `CategoryID`, `Locale`, `IsDefault`, `DateInserted`, `InsertUserID`, `Attributes`) values (:Name, :Folder, :CategoryID, :Locale, :IsDefault, :DateInserted, :InsertUserID, :Attributes)

**Comment by DaazKu** [comment]
Wrong repo..
