### ISSUE TITLE
Clean up "Hide Category" functionality and UX

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4394]
Currently, this feature is pretty clunky. Hiding categories removes them from the category list, which means there's no easy way to get them back.

Lincoln suggests making the category list ignore the setting, while retaining its effects in /recent to provide a filter. This would mean we'd need to rename the button to reflect the new effect.

**Comment by initvector** [comment]
- [ ] Rename "Hide Category" to "Mute Category".
- [ ] For muted categories, hide their contents on the /recent page.
- [ ] Do not filter out muted categories in category lists.
- [ ] Update `CategoryFollowToggleModule::toString` to return an empty string.
