### ISSUE TITLE
Fix misleading entries in GDN_Activity

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4397]
Email for notifications starts life as an entry in GDN_Activity. There is a column called "Emailed" that indicates how the attempt to send the email went. It can be one of several values:

```
    /** Activity status: The activity was added before this system was put in place. */
    const SENT_ARCHIVE = 1;

    /** Activity status: The activity sent just fine. */
    const SENT_OK = 2;

    /** Activity status: The activity is waiting to be sent. */
    const SENT_PENDING = 3;

    /** Activity status: The activity could not be sent. */
    const SENT_FAIL = 4;

    /** Activity status: There was an error sending the activity, but it can be retried. */
    const SENT_ERROR = 5;
```

The calling code executes $Email->send() but **DOES NOT CHECK THE RETURN**, only catches exceptions. SENT_OK is also assumed, and is the default case.

The problem is that email sending can fail or be skipped entirely based on several conditions such as:

* `Garden.Email.Disabled`
* Lack of Garden.Email.View permission
* Any number of events fired inside send()

This needs bulletproofing.

**Comment by tburry** [comment]
I recommend  having Gdn_Email throw an exception that says the email was skipped and then adding a ActivityModel::SENT_SKIPPED = 6 constant that sets the result.

Can you assign this to someone @linc?
