### ISSUE TITLE
Dashboard v3: Clicking on the setting icon while disconnected gives no feedback.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4399]
If your session expire and you click on the setting icon of the SAML SSO plugin for example you end up with nothing on screen.
An error should be raised!

We should check if the user is still logged. If so display the error message returned by the request. Otherwise we should display: Your session has expired, log in again

![screen shot 2016-09-02 at 3 40 25 pm](https://cloud.githubusercontent.com/assets/2412909/18216276/b6bc3daa-7123-11e6-999c-2f090d90bd4b.png)

Note that this should be addressed globally!

**Comment by beckyvb** [comment]
I've mitigated this by closing the modal and informing the user of an error via notification. There's no way to get the logged-in state of a user AFAIK in this circumstance.
