### ISSUE TITLE
Dashboard v3: form errors are hidden when saving a long form.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4400]
You click save an absolutely nothing happen until you scroll up to see that there are some errors.
Really bad UX.

![screen shot 2016-09-02 at 3 53 13 pm](https://cloud.githubusercontent.com/assets/2412909/18216586/be439422-7125-11e6-8fa5-3cc2a6427696.png)
![screen shot 2016-09-02 at 3 53 39 pm](https://cloud.githubusercontent.com/assets/2412909/18216589/c08cd450-7125-11e6-9f6c-5095d522416b.png)

**Comment by DaazKu** [comment]
> [3:57 PM] Alexandre Chouinard: UX problem.
[4:11 PM] Dan Maitland: Once the user saves the page should scroll back up to the top to display the errors

**Comment by beckyvb** [comment]
Fixed, thanks!
