### ISSUE TITLE
Warnings from DashboardNav.SectionLandingPages not being set

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4411]
https://github.com/vanilla/vanilla/blob/feature/dashboard3/applications/dashboard/modules/class.dashboardnavmodule.php#L174

![screen shot 2016-09-06 at 12 58 50 pm](https://cloud.githubusercontent.com/assets/2412909/18283196/0f18d920-7432-11e6-9879-81a939851446.png)

Check that `$session->getPreference()` is not false!

**Comment by bleistivt** [comment]
fixed by #5451
