### ISSUE TITLE
Dashboard v3: Tables with the Sortable class should have a clear visual that it is sortable.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4412]
See Roles & Permissions.

I think there should be an handle on the first row. Not clicking on that handle should not trigger sorting.

https://github.com/vanilla/vanilla/blob/feature/dashboard3/js/global.js#L455 This code should be updated to reflect that change.

**Comment by linc** [comment]
Closing in favor of https://github.com/vanilla/vanilla/issues/4788
