### ISSUE TITLE
Quote button shows when users don't have posting permissions

### ISSUE THREAD

**Issue by matthewbienz** [vanilla/vanilla#4442]
Users will see the quote option, as the plugin is separate from Reactions

**Comment by Siddy00** [comment]
Hi there.

One of the users of our forum noticed the same issue on version 1.6.10 of the Quotes plugin. We believe we fixed this by making the following changes to the function addQuoteButton (in class.quotes.plugin.php):

Before
```
        if (!Gdn::session()->UserID) {
            return;
        }
```

After
```
        $Session = Gdn::session();

        if (!$Session->UserID) {
            return;
        }

        if (!isset($Args['Discussion']))
            return;

        $CanComment = $Session->checkPermission('Vanilla.Comments.Add', true, 'Category', $Args['Discussion']->PermissionCategoryID);
        if (!$CanComment)
            return;
```

Hope this helps :)
