### ISSUE TITLE
Improve autolink for large images

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#4448]
If a user embeds an image that is wider than the message container and then puts an anchor around the image, Vanilla will put an anchor around the image to link it to itself anyway (the intent being that user clicks on the image to see the full size in a new tab or a plugin or whatever). This leads to a situation where you can have an image inside of an anchor inside of another anchor. See here:

https://github.com/vanilla/vanilla/blob/master/js/global.js#L2063

```js
if (img.naturalWidth() > container.width() && container.width()) {
```

This can be fixed by altering the logic to be

```js
if (img.naturalWidth() > container.width() && container.width() > 0 && !img.parent().is("a")) {
```

**Comment by linc** [comment]
Thanks!

**Comment by DaazKu** [comment]
https://github.com/vanilla/vanilla/blob/master/js/global.js#L2060 does exactly that.
