### ISSUE TITLE
Signin/Out issue with PHP 5.4

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#4450]
When trying to signin on a forum using
`
$Configuration['Garden']['SignIn']['Popup'] = false;`

I get 500 error at:
http://xxxxx.com/forum/entry/signin

Issue does not occur if popup true.

When I sign out (with popup true or false) I get 500 error at: http://xxxxx.com/forum/entry/signout?TransientKey=WxTLFxZHTBxx

Checked error logs and see:  
apache error: End of script output before headers: index.php. 

When I revert to https://github.com/vanilla/vanilla/blob/07f33263ded2f6afc1958e56ba029e19db6c6d30/library/core/class.dispatcher.php

but keep all files as is, it's no longer an issue

I should note, this is not an issue when using PHP 5.5, but considering readme states Vanilla Master is 5.4 compatible, I wanted to bring it up...

**Comment by initvector** [comment]
I cannot recreate this using PHP v5.4 on nginx v1.9, so I'm assuming this might be more of an Apache issue than a 5.4 issue, specifically.

**Comment by adrianspeyer** [comment]
@initvector  When I do run apache with php 5.5 there was no issue

**Comment by initvector** [comment]
If it's 5.4 that's the issue, it should be failing on 5.4, regardless of the web server.  That doesn't seem to be happening here.

I setup an environment using Apache 2.4.7 with PHP v5.4.45 (the latest 5.4 release) running as an Apache module.  I was able to sign-in and out without an issue, having toggled off `Garden.Signin.Popup`.

My suspicion is the hosting provider is using an outdated release of 5.4.
