### ISSUE TITLE
Dashboard v3: Tables in popup are completely destroyed.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4451]
Normal width:
![screen shot 2016-09-12 at 11 54 25 am](https://cloud.githubusercontent.com/assets/2412909/18442724/d54589c0-78df-11e6-955f-4d7dc21f72f9.png)

Ultra collapsed:
![screen shot 2016-09-12 at 11 56 13 am](https://cloud.githubusercontent.com/assets/2412909/18442756/f820e534-78df-11e6-90bb-c60f3014b029.png)

In a popup:
![screen shot 2016-09-12 at 11 55 09 am](https://cloud.githubusercontent.com/assets/2412909/18442770/04fe1e02-78e0-11e6-9f26-ed06eb502af4.png)

**Comment by beckyvb** [comment]
Fixed, thanks!
