### ISSUE TITLE
Dashboard v3: Subcommunity slugs occasionally get duplicated

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4454]
I've noticed some odd behaviour, specifically with subcommunity slugs:

1) Log in as an admin to a site with subcommunities.
2) Go to the Dashboard.
3) Clicking on Moderation will usually bring you to: (sitename)/en/en/dashboard/message (where "en" is the slug for a subcommunity)
4) I'm guessing that the new Dashboard tries to remember what section you were last in within Dashboard and Moderation and Settings, because I'm not always getting that behaviour, particularly if I've moved around within those sections, but it looks as though the default links for Moderation and Settings duplicate the slug in the URL.
5) Slug duplication in the URL leads to a page not found error.

**Comment by DaazKu** [comment]
This: https://github.com/vanilla/vanilla/pull/4334 may fix the problem.

**Comment by beckyvb** [comment]
I recently updated the preference saving. Before I was saving the subdirectory slug (i.e., 'en') in the user preferences. I decided against saving the slug. One reason is that if ever you turned off subcommunities, the user preferences would be moot. So, for any site that System has ever visited under the old regime, there may be user preferences saved with the slug. We then re-add the slug resulting in a 404. The way you can fix this is to navigate to the page manually and then reclick on the panel navigation (which will save the user preference without the slug).

**Comment by beckyvb** [comment]
Related: https://github.com/vanilla/vanilla/issues/4455
