### ISSUE TITLE
Dashboard v3: Switching menu items in Mozilla leads to error

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#4460]
When you click to a different menu item in dashboard, using Mozilla it leads to a weird error growl box. Both I and @DaazKu saw this in action.

![image](https://cloud.githubusercontent.com/assets/425366/18488533/d0b454fc-79c7-11e6-83ee-83314795b8d2.png)

**Comment by DaazKu** [comment]
In firefox the ajax request is killed by the browser since the browser is changing page.
The error callback is then called because the query was aborted.

**Comment by beckyvb** [comment]
Fixed, thanks!
