### ISSUE TITLE
Dashboard v3: Upload default avatar

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#4469]
Some small UX issues with the avatar upload:
1. The page is very wide, your avatar is on one side and the browse and save are on the other, they don't feel like they are related.
2. While it is uploading you do not know that anything is happening. (in fact, for consistency sake, we might want to make the browse photo the same as on the Email settings page)
3. If you upload and then choose an thumbnail size that is larger than what you already have, the avatar becomes stretched (blurry)

**Comment by charrondev** [comment]
Closing because by the time this UI is revisited it will have new mockups & success criteria.
