### ISSUE TITLE
Dashboard v3: Techno Rave Tour 2016

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#4474]
On staging cluster 211, as an admin signing in for the first time, I click through the Welcome Tour and when I reach the end, the page loads and reloads causing a dance party to ensue. 

![2016-09-14_15-54-17](https://cloud.githubusercontent.com/assets/18470831/18528036/3cefca70-7a95-11e6-87fd-f0708dfc2a6e.gif)

**Comment by kaecyra** [comment]
<img width="568" alt="screen shot 2016-09-14 at 4 23 31 pm" src="https://cloud.githubusercontent.com/assets/248212/18528580/a033b5ae-7a97-11e6-8412-e6336e604947.png">
