### ISSUE TITLE
Images attached in Advanced Editor can not be removed on edit

### ISSUE THREAD

**Issue by Danik** [vanilla/vanilla#4480]
There doesn't seem to be any way to remove images that have been attached to a post, at least not that I have found.

Example:
1. Inserting an image
   ![2016-09-15_125850](https://cloud.githubusercontent.com/assets/677889/18547813/9ba68224-7b45-11e6-89aa-f8dbefa827f6.png)
2. Posted the comment, attachment not visible
   ![2016-09-15_125855](https://cloud.githubusercontent.com/assets/677889/18547815/9d9b6fae-7b45-11e6-9769-347ce5688ed0.png)
3. Editing comment to remove image
   ![2016-09-15_125909](https://cloud.githubusercontent.com/assets/677889/18547819/a27306b8-7b45-11e6-8b2e-d017e595b59f.png)
4. Comment edited, image attachment visible
   ![2016-09-15_125914](https://cloud.githubusercontent.com/assets/677889/18547823/a4b3d394-7b45-11e6-98fb-788e6709b5c9.png)
5. But I see no way to remove the image from the post when editing it
   ![2016-09-15_125920](https://cloud.githubusercontent.com/assets/677889/18547825/a70af488-7b45-11e6-8ce0-061553060a87.png)

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
