### ISSUE TITLE
Gdn_Request::get() returns nothing if path is root

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4498]
## Example 1 (Not a bug. See [posts below](https://github.com/vanilla/vanilla/issues/4498#issuecomment-248700186))

testRequest.php

``` php
<?php

define('APPLICATION', 'Vanilla');
define('APPLICATION_VERSION', '2.2.112.3');
define('DS', DIRECTORY_SEPARATOR);
define('PATH_ROOT', getcwd());
require_once(PATH_ROOT.'/bootstrap.php');

$requestObj = Gdn_Request::create();
print_r($requestObj->get());
die();
```

URL: `/testRequest.php?parameter=notEmpty`

Result: 

```
Array
(
)
```

Expected result:

```
Array
(
    [parameter] => notempty
)
```
## Example 2

Put that code at the beginning of any `base_render_before` hook:

``` php
die('<pre>'.print_r(Gdn::request()->get(), true));
```

Go to: `/?parameter=notEmpty`
Same problem.
Go to: `/categories?parameter=notEmpty`
Now it works.

**Comment by tburry** [comment]
I think you want Gdn::request() instead of Gdn_Request::create().

**Comment by DaazKu** [comment]
Ok now I understand why my example bugged.

You have to call either `Gdn_Request::create()->fromEnvironment()` or `Gdn::request()`

Example 2 is still a problem though.

**Comment by bleistivt** [comment]
Testing example 2 I get 

    Array
    (
        [parameter] => notEmpty
    )

for both `/?parameter=notEmpty` and `/categories?parameter=notEmpty`

Gdn_Request was refactored in the meantime. Has this been fixed?

**Comment by charrondev** [comment]
Looks like it.
