### ISSUE TITLE
Dashboard v3 : Missing dropdown in Ranks

### ISSUE THREAD

**Issue by vrjrobitaille** [vanilla/vanilla#4500]
The drop down for Permissions is missing on the Ranks page. 

![screen shot 2016-09-20 at 2 55 33 pm](https://cloud.githubusercontent.com/assets/18470831/18685830/b131a6d6-7f47-11e6-8eb5-085182498ca6.png)

**Comment by LauraMakesArt** [comment]
I dont have permissions to close this, But It does not seem to be true at the moment?
