### ISSUE TITLE
Dashboard v3: Localize the dashboard

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4501]
There are a lot of untranslated strings in the settings page in the dashboard. We should get these into Transifex.

**Comment by beckyvb** [comment]
I think @tburry has built some kind of crawler to find strings contained in the t function before. It would be nice to have a utility like that to use for the dashboard and throughout Vanilla.

**Comment by linc** [comment]
I believe @initvector did some work on the Transifex automation so talk to him first.
