### ISSUE TITLE
Dashboard v3: Avatar in dashboard has two dropdown arrows

### ISSUE THREAD

**Issue by JulieVanilla** [vanilla/vanilla#4507]
Occasionally, there are two dropdown arrows near the avatar appearing in the Dashboard. Please see attached image.

![screen shot 2016-09-21 at 3 03 06 pm](https://cloud.githubusercontent.com/assets/8974997/18725328/d539ec48-800d-11e6-9102-dc8ba0c5d5a1.png)

"I bet some plugin is adding vanillicon.css on base_render_before."

**Comment by linc** [comment]
Don't believe this is still an issue.
