### ISSUE TITLE
Categories homepage loads forever in "modern" layout

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4513]
A particular customer is affected by this so it could be theme related.

Their site is configured for categories to be the homepage. In "mixed" and "table" layout, everything loads correctly. In "modern" layout, the page spins forever while loading, eventually returning a 503 once PHP times out.

**Comment by kaecyra** [comment]
@linc , PM me or something if you want to know who is being affected, I'm not going to post it publicly.

**Comment by tburry** [comment]
I'm looking into this right now.
