### ISSUE TITLE
Recaptcha cross-origin browser blocking issue makes registration fail

### ISSUE THREAD

**Issue by v-k-** [vanilla/vanilla#4516]
Hi. I'm getting this error from register page in my 2.2.1 installation. There have being people reporting problems to register due to recaptcha errors, as per this image 

http://www.thefreshloaf.com/files/u73062/pada.png 

Chrome report this:

A Parser-blocking, cross-origin script, https://www.google.com/recaptcha/api/js/recaptcha.js, is invoked via document.write. This may be blocked by the browser if the device has poor network connectivity.

thanks

**Comment by charrondev** [comment]
This is definitely no longer an issue as of `2.8`. Not 100% sure which release fixed it though.
