### ISSUE TITLE
Quotes: ".QuoteFolding" overlaps

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4528]
If you have more than one **blockquote** embedded in the same .UserQuote, the toggle for each **blockquote** overlap. They are absolutely positioned in the same parent container. the **p**, with the user name needs a class. The **div** wrapping the .QuoteFolding needs a class also. The **p**, the **div** and the **blockquote** need to be wrapped with div with position absolute, so the absolutely positioned .QuoteFolding don't overlap.

Example:

```
> @Stéphane said:
> > Here is a quote
> > Here is another quote
> > And another
> > And another


> @Stéphane said:
> > Here is a quote
> > Here is another quote
> > And another
> > And another
```

Generates this:

```
<blockquote class="UserQuote">
  <div class="QuoteText">

    <p>
      <a href="/en/profile/St%C3%A9phane">@Stéphane</a> said:
    </p>
    <div>
      <a href="" class="QuoteFolding">» show previous quotes</a>
    </div>
    <blockquote class="UserQuote QuoteFolded" style="display: none;">
      <div class="QuoteText">
        <p>Here is a quote<br>
          Here is another quote<br>
          And another<br>
          And another
        </p>
      </div>
    </blockquote>

    <p><a href="/en/profile/St%C3%A9phane">@Stéphane</a> said:</p>
    <div>
      <a href="" class="QuoteFolding">» show previous quotes</a>
    </div>
    <blockquote class="UserQuote QuoteFolded" style="display: none;">
      <div class="QuoteText">
        <p>Here is a quote<br>
          Here is another quote<br>
          And another<br>
          And another
        </p>
      </div>
    </blockquote>
  </div>
</blockquote>
```

Here's the quotes closed, they look ok at first:

![quotesclosed](https://cloud.githubusercontent.com/assets/19651440/18790014/297fe41a-817b-11e6-96c6-c092e20560dc.png)

Then if you open them, you'll see both toggles on top of each other, in the top corner. 

![quotesopen](https://cloud.githubusercontent.com/assets/19651440/18790013/2968be0c-817b-11e6-823c-06dd522afce1.png)

Each quote should be wrapped, so we can have the toggle positioned for each quote.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
