### ISSUE TITLE
Cannot edit photo thumbnail on profile

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4538]
When `Garden.Profile.ShowActivities` is false, it internally redirects `/profile` views to `/profile/discussions`.  `/profile/discussions` does not contain the necessary code to add `cropimage.js` and `cropimage.css`

See: [applications/dashboard/controllers/class.profilecontroller.php:490](https://github.com/vanilla/vanilla/blob/9af22389edf8a89e2415c0171eef88a3f1885abb/applications/dashboard/controllers/class.profilecontroller.php#L490)
See: [applications/dashboard/controllers/class.profilecontroller.php:477](https://github.com/vanilla/vanilla/blob/9af22389edf8a89e2415c0171eef88a3f1885abb/applications/dashboard/controllers/class.profilecontroller.php#L477)
See: [applications/vanilla/settings/class.hooks.php:587](https://github.com/vanilla/vanilla/blob/9af22389edf8a89e2415c0171eef88a3f1885abb/applications/vanilla/settings/class.hooks.php#L587)

**Comment by DaazKu** [comment]
Thanks for those details. Easy fix.
