### ISSUE TITLE
"Undefined index: Control" in Gdn_Form

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4544]
`Gdn_Form::simple` assumes the presence of a [key called Control](https://github.com/vanilla/vanilla/blob/2d72dd56031dbe94da0036216aaacac3dd3f7666/library/core/class.form.php#L2752).  Other areas of this function verify the presence of certain keys with `isset`.  The failure to do so with "Control" means multiple notices can be generated during a request ("Undefined index: Control").

**Comment by charrondev** [comment]
We now touch this value in `Gdn_Form::simple()` https://github.com/vanilla/vanilla/blob/5c7cb145f4cd4d21279b9257488f13a816c8677a/library/core/class.form.php#L2969
