### ISSUE TITLE
Vanilla.Categories.DoHeadings cannot be set anymore

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4547]
The configuration cannot be set but it is still respected in a bunch of places.
We should remove references to it.

This might also cause some weird behaviour when updating from an old version.

**Comment by initvector** [comment]
See: [Instances of Vanilla.Categories.DoHeadings in Vanilla](https://github.com/vanilla/vanilla/search?utf8=%E2%9C%93&q=Vanilla.Categories.DoHeadings) (GitHub's code search isn't great, but it'll get you in the general area.)

Also necessary to review themes for references to this config setting.
