### ISSUE TITLE
Secure Flag on Identity Cookies

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4552]
If a request is being served over HTTPS on a site with `Garden.ForceSSL` enabled, there isn't a good reason we should not be toggling on the secure flag for the identity cookies Vanilla serves.

I propose the following solution:

If its `$secure` parameter is identical to `null`, [`safeCookie`](https://github.com/vanilla/vanilla/blob/c5616600b41438fc8de53eb034e7c74ea882cdf7/library/core/functions.compatibility.php#L591) should check for a truthy value of `Garden.ForceSSL`.  If enabled, verify the current request is over HTTPS.  If both are true, pass `true` as the `$secure` parameter of [`setcookie`](http://php.net/setcookie).  If `safeCookie` has `false` explicitly passed as its `$secure` parameter, this behavior should be skipped.

**Comment by linc** [comment]
release/1609
