### ISSUE TITLE
PHP 7 - Vanilla 2.3

### ISSUE THREAD

**Issue by garygreen** [vanilla/vanilla#4555]
Is there a roadmap when 2.3 is targeted to be released? Any indication would be good because it's pretty much the only dependency left on our system which doesn't support PHP 7.

**Comment by linc** [comment]
We were just talking about this today! https://vanillaforums.org/discussion/32168/vanilla-2-3-beta#latest

There's a single point of failure for releases currently (me) so we need to work on a better system for that. In the meantime, any testing feedback you have from the beta would be much appreciated to speed us on our way.

**Comment by garygreen** [comment]
@linc thanks for your comment but that links to an article way back in May and not an actual update. There definitely needs to be a more clear roadmap for Vanilla because at the moment it seems pretty much up in the air when the next major version will be released.

**Comment by linc** [comment]
The comments were more recent, as I indicated.

**Comment by garygreen** [comment]
@linc Thanks, I didn't see the comments. Just a few things:

> This is what we need to support:
> * Apache & nginx
> * MySQL 5.0 thru 5.7
> * PHP 5.4 thru 7.0

How come the next major upgrade for Vanilla is going to support a no-longer supported PHP version? <= 5.6 [is dead, caput, reached in of life, totally vulnerable to attacks](http://php.net/supported-versions.php)

If people want to risk continuing to run < 5.6, or support servers that require it, they should stick with old vanilla until they are in a position to upgrade. I don't think Vanilla should be held back.

> To my knowledge, we are good on the first 3. The thing that drives me crazy with worry is that I drop this release and find out it breaks on Digital Ocean or GoDaddy or something.

To me it seems like vanilla is stalled because of fear of breaking things so it makes me wonder will 2.3 ever be released? I think waiting for the community to test and generate a feedback report is a slow strategy to push things forward. 😕 

Breaking things is always the fear when releasing a new major version. Truth is, your going to have bugs I can guarantee it - the main thing is there a plan in place to handle those bugs in a quick manner. Creating a patch/minor version is always an option - if people experience problems on their servers, they will come looking for the fix to install.
