### ISSUE TITLE
Allowing the dismissal of Messages conflicts with MySQL's reuse of IDs

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4557]
We have an "Allow users to dismiss this message" option on our messages feature. It stores the `MessageID` in the serialized `Preferences` array on the user's record.

When MySQL restarts, the autoincrement resets to the highest index + 1. This means once an admin deletes all their messages (which is a very reasonable thing to do, especially if they are time-based), or even just the highest-numbered one(s), `MessageID`s recycle.

Result: Users who previously dismissed a message will never see a new one with the same ID.

Possible solutions are to break out dismissed messages onto their own table for co-deletion, or use a `Deleted` flag on the Message table (and also actual-delete messages that are lower than the current max `MessageID`). We'd like to do the latter.

**Comment by bleistivt** [comment]
The described autoincrement behaviour only occurs with InnoDB and has been fixed in MySQL 8.0
https://bugs.mysql.com/bug.php?id=199
https://dev.mysql.com/worklog/task/?id=6204
