### ISSUE TITLE
MeBox Messages dropdown should have subjects clickable, not participants

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#4561]
In the messages dropdown in the MeBox, the subject of the message should be clickable, not the participants. This is confusing UX.

**Comment by linc** [comment]
What I'd really like here is for the entire box to be clickable, and not display the username as tho it is a separate profile link.

**Comment by DaazKu** [comment]
Won't that break theming or other things?

**Comment by linc** [comment]
I doubt folks have been theming the Me Module flyout menu. @beckyvb ?

**Comment by beckyvb** [comment]
The flyout menu does get themed.

**Comment by linc** [comment]
We're gonna risk adding an anchor tag in there to make this work.
