### ISSUE TITLE
Singular and plural string for "%s levels deep"

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4593]
`%s levels deep`

Should allow for singular (level) and plural (levels) as separate strings.

**Comment by linc** [comment]
If it's a translation problem, it should get fixed on Transifex. If our base string doesn't properly accommodate pluralization generally, that should be the issue not something about Spanish.

Please revise or close this issue based on which it is.

**Comment by linc** [comment]
This appears fixed in 2.5.
