### ISSUE TITLE
StopForumSpam blocks silently - 2.2.1 

### ISSUE THREAD

**Issue by v-k-** [vanilla/vanilla#4615]
I've tested creating an account using a disposable mail. StopForumSpam kicks in with a new field asking the applicant to expalin why he/she wants to participate. Upon sending the registration, a page is presented telling the user his/her application is going to be revised by an administrator. So far so good. But as administrator I got no clue that all this happened. No mail, nothing on Applicants, nothing in spam or moderation queue.

Thanks

**Comment by linc** [comment]
This should get reconfirmed on master branch; we may have resolved this for the next release.

**Comment by Kaspar-K** [comment]
VF 2.8.1
SFS 1.0.1
"Upon sending the registration, a page is presented telling the user his/her application is going to be revised by an administrator. So far so good. But as administrator I got no clue that all this happened. No mail, nothing on Applicants, nothing in spam or moderation queue."

It now is shown in "Spam Queue" - but only seen if it is opened. There are no notifications about it.
Nothing in notifications for administrators, nothing shown(like HasNew) next to Applicants, Spam Queue or Moderation Queue.
