### ISSUE TITLE
Dashboard user edit password doesn't hide/show properly

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4636]
Go in the dashboard to edit a user's password.

![screen shot 2016-10-13 at 11 58 38 am](https://cloud.githubusercontent.com/assets/2412909/19356674/96928d20-913c-11e6-94e7-2712a6ad90bf.png)

Click on the **Password Options** label.

![screen shot 2016-10-13 at 11 58 45 am](https://cloud.githubusercontent.com/assets/2412909/19356691/aaa3c31a-913c-11e6-9155-3a8aca3e3f49.png)

Select **Manually set user password. No email notification.**

![screen shot 2016-10-13 at 11 58 51 am](https://cloud.githubusercontent.com/assets/2412909/19356713/bf8a31e2-913c-11e6-9269-cde1d2dc1bdf.png)

The **New Password** section should only show when **Manually set user password. No email notification.** is selected ans be hidden otherwise. Clicking on **Password Options** should have no impact at all in this.

**Comment by linc** [comment]
This is fixed in 2.5.
