### ISSUE TITLE
Automatically quote all usernames in mentions that might require quoting

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4658]
Usernames with spaces are automatically quoted when performing a mention.  There are other usernames, like those with periods, which currently require quoting to be properly formatted, but aren't automatically quoted.

A couple possible solutions:
1. The [`requires_quotation`](https://github.com/vanilla/vanilla/blob/c562d0e97d4348f39ee60890aa993c9710ebd319/js/global.js#L1726) check could be expanded to include additional characters.
2. The way mentions are formatted in posts could be more accommodating to these types of usernames.

**Comment by DaazKu** [comment]
Why aren't we just requiring quoting for all usernames that does not match `/^[a-z\d-_]+$/i`.
We escape quotes and we are done once and for all with that issue.
