### ISSUE TITLE
Augment schema validation behavior

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#4703]
Right now the schema object lets data pass through that has been provided, but isn't in the schema. This is a security risk. I want you to add several behaviors to the schema object to control validation.
- [x] Add a Schema::get/setValidationBehavior() property that sets the validation behavior. The property will take one of several class constants.
- [x] Schema::VALIDATE_REMOVE means that fields that are not in the schema will just be silently removed.
- [x] Schema::VALIDATE_NOTICE will do the same as VALIDATE_REMOVE, but will also trigger an E_USER_NOTICE for each removed field.
- [x] Schema::VALIDATE_EXCEPTION will cause fields that are not in the schema to be added as errors in the thrown ValidationException.
- [x] Make sure these behaviors work for nested fields (e.g. object properties).

**Comment by initvector** [comment]
Closing in favor of tracking this issue on its PR: https://github.com/vanilla/vanilla/pull/4743
