### ISSUE TITLE
Twitter requires twitter:card meta tag to process OpenGraph meta data

### ISSUE THREAD

**Issue by MelVanilla** [vanilla/vanilla#4719]
Twitter docs: https://dev.twitter.com/cards/types/summary-large-image
Image, description, and title will use OG fallbacks: https://dev.twitter.com/cards/markup
A useful tool for evaluating finished product: http://socialdebug.com/

We probably only need to specify 1 tag here to get it working.

**Comment by linc** [comment]
This is a blocker for marketing. I've amended the description with additional information. We can improve our Twitter integration in the future to fully take advantage of their markup. This issue is to make Twitter cards work for forum discussion & comment links only (min necessary).

**Comment by DaazKu** [comment]
https://cards-dev.twitter.com/validator
