### ISSUE TITLE
New CDN address to be SSL?

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#4745]
With CDN moving, I guess we need to changes links for 

https://c3409409.ssl.cf0.rackcdn.com/images/banned_large.png
https://c3409409.ssl.cf0.rackcdn.com/images/banned_100.png

called here

https://github.com/vanilla/vanilla/blob/ec5b13f6713dae42cd835267cea328d8e8559432/applications/dashboard/views/modules/userphoto.php#L20

https://github.com/vanilla/vanilla/blob/a5a1d29ca9bb3dc09650f9b09da8a34316c24c81/library/core/functions.render.php#L1133

https://github.com/vanilla/vanilla/blob/a5a1d29ca9bb3dc09650f9b09da8a34316c24c81/library/core/functions.render.php#L1165

Current CDN would be http://cdn.vanillaforums.com but do we have https://cdn.vanillaforums.com?

**Comment by linc** [comment]
Appears to have been done.
