### ISSUE TITLE
Verify whether import-generated txt files are properly removed

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4748]
Import generated txt files for each table in the database. Those files absolutely need to be removed at the end of the import.

* Verify they are being removed. If not, add a delete.
* If file permission issues could somehow prevent removal, that must be accounted for, e.g. with a warning message.
* If this is indeed a problem that's existed, accommodation must be made to delete or block them. I suggest utility/update as a find-and-destroy mechanism.

**Comment by DaazKu** [comment]
When you hit the "finished" button, [ImportController::restart()](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.importcontroller.php#L218) is called and everything is cleaned.

* ~Verify they are being removed. If not, add a delete.~
  * Nothing to do here
* ~If file permission issues could somehow prevent removal, that must be accounted for, e.g. with a warning message.~
  * Permission check are done at the beginning of the import. Everything should work if the permissions are not changed during the import process.
* ~If this is indeed a problem that's existed, accommodation must be made to delete or block them. I suggest utility/update as a find-and-destroy mechanism.~
  * N/A
