### ISSUE TITLE
Remove serialization in Gdn_Router::_parseRoute

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4767]
We're looking to remove most (all?) usage of `serialize`/`unserialize` in favor of `json_encode`/`json_decode`.  Most of it is straightforward, but `Gdn_Router::_parseRoute` may be a bit tricky.

Per [this comment](https://github.com/vanilla/vanilla/issues/3749#issuecomment-259436508), I've created a dedicated task for this particular usage of serialization.

**Comment by charrondev** [comment]
A quick update here:

I've closed out the epic as this the last remaining task from it. Most other `@unserialize` calls should have been removed from the project.

**Comment by tburry** [comment]
I'm going to close this issue since it looks like routes are being saved/loaded properly without serialization.

I've added a small hardening for the BC code [here](https://github.com/vanilla/vanilla/pull/9487).
