### ISSUE TITLE
Revisit serialization in Gdn_Configuration::get

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4770]
`Gdn_Configuration::get` uses `Gdn_Format::unserialize` on all string values.  We want to move away from (un)serializing values in favor of `dbencode`/`dbdecode`.  This is a little more complicated here, because `Gdn_Format::unserialize` does one of three things with the values it receives:

1. Runs them through `unserialize`
2. Runs them through `json_decode`
3. Returns the original, unmodified value

`dbdecode` will try to decode the value.  If it fails, it'll return false.  This is not compatible with `Gdn_Configuration::get`, since it'll attempt to run values like "default" through `dbdecode` and end up returning a boolean `false`.

This function (and `Gdn_ConfigurationSource::get`) need to be updated to continue functioning as they currently do, but using `dbdecode` instead of `Gdn_Format::unserialize`.

**Comment by charrondev** [comment]
As of 2.8 at least there is no `Gdn_Format::unserialize` calls present in `Gdn_Configuration`. I'm closing out this issue as a result.
