### ISSUE TITLE
discussionsmodule does not display photo when "Discussion Photos" is activated

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4771]
The "Discussion Photos" plugin advertises that it "Displays photo and name of the user who started each discussion anywhere discussions are listed" but that's a lie! It does not show in the Discussions Module.

**Comment by beckyvb** [comment]
Addressing this by adding a param (`showPhotos`) on the discussions module. You can leverage this in Smarty by using the following tag: `{module name="DiscussionsModule" showPhotos=true}` Adding the index photo to the module for anybody who has enabled the plugin  may mess up some themes. I've updated the Discussion Photos plugin description.
