### ISSUE TITLE
Remove invalid attribute "itemprop" from <meta> tags that are part of the <head> section

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4777]
> The Twitter OG meta tags seem to be causing some mark-up errors. This seems very minor (I certainly don't think it's actually an accessibility issue) but also relatively easy to fix in the template. https://validator.w3.org/nu/?doc=https%3A%2F%2Fcommunity.scope.org.uk%2F

**Comment by DaazKu** [comment]
I could not find exactly why but it seems the itemprop cannot be set on meta tags generated in the head section.

This is also what the error from the validator seems to suggest: `Attribute itemprop not allowed on element meta at this point.`
