### ISSUE TITLE
Dashboard v3: Dashboard home page

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#4787]
- [ ] In the dashboard page tables underneath the Chart: Each row should be clickable in it's entirety and not just the title
- [ ] In the Chart we only need to show the year for the fist item and then where ever it changes along the line.
- [ ] If there is not an updates Table then the Recent news table shold go right across
- [ ] When the previous and next buttons are clicked to the timeframe the button should not take on the selected blue state. They are fire and forget.
- [ ] Double check the spacing between the Chart and the tables below. There should be 42px of space between them

**Comment by charrondev** [comment]
Closing because by the time this UI is revisited it will have new mockups & success criteria.
