### ISSUE TITLE
Secure cookie identity being overwritten when visiting HTTP

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4797]
If a site has `Garden.ForceSSL` enabled and is behind HTTPS, its cookies are served with the secure flag.  If a user finds their way to a plain-text HTTP link to the site, their session is reset before they're automatically redirected to the HTTPS site.  This appears to be due to `Gdn_CookieIdentity` attempting to delete identity cookies if they're perceived to be invalid.  This includes requests when the expected cookies do not exist.

Pseudo trace of what's going on:

1. [bootstrap.php:255](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/bootstrap.php#L255)
2. [class.auth.php:59](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.auth.php#L59)
3. [class.session.php:453](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.session.php#L453)
4. [class.auth.php:411](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.auth.php#L411)
5. [class.auth.php:426](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.auth.php#L426)
6. [class.cookieidentity.php:101](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.cookieidentity.php#L101)
7. [class.cookieidentity.php:277](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.cookieidentity.php#L277)
8. [class.cookieidentity.php:294](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.cookieidentity.php#L294)
9. [class.cookieidentity.php:102](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.cookieidentity.php#L102)
10. [class.cookieidentity.php:86](https://github.com/vanilla/vanilla/blob/f77d031dd4cc99afb2c38fb4028fc076f69924af/library/core/class.cookieidentity.php#L86)

`Gdn_CookieIdentity::_checkCookie` and `Gdn_CookieIdentity::_clearIdentity` can (and often do) both delete the same cookie.  This leads to duplicate headers for removing the same cookie.

**Comment by tburry** [comment]
I think one PR should be to not delete identity cookies that don't exist.

**Comment by initvector** [comment]
Closed by #4808
