### ISSUE TITLE
Invalid class for category

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4816]
On Lightspeed stage, the name of this category is "Let's talk business" generates the CSS class: "Section-Category-Let's talk business".

There shouldn't be any spaces and the apostrophe should be removed.

**Comment by beckyvb** [comment]
The CSS class for a category usually takes the category's url code to generate the CSS class, if a CSS class hasn't been explicitly provided in the category settings page. It's likely that the user edited the category to have an invalid CSS class, as this seems like a fairly isolated event.
