### ISSUE TITLE
Dashboard v3: Delete Message redirects to "TRUE"

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4825]
<img width="415" alt="screen shot 2016-11-18 at 10 46 56 am 1" src="https://cloud.githubusercontent.com/assets/117672/20436014/5f5626d0-ad7c-11e6-86d1-ebdadc401953.png">

**Comment by DaazKu** [comment]
Closed by https://github.com/vanilla/vanilla/pull/4823
