### ISSUE TITLE
Remove vendors/Auth in favor of Packagist openid/php-openid

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4838]
This would also be an upgrade from 2.1.2 to 2.3.0.

https://packagist.org/packages/openid/php-openid

**Comment by DaazKu** [comment]
> Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
>
>  Problem 1
    - Installation request for openid/php-openid ~2.3.0 -> satisfiable by openid/php-openid[2.3.0].
    - openid/php-openid 2.3.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.

Do we really want that new dependency?

**Comment by DaazKu** [comment]
I've created the PR https://github.com/vanilla/vanilla/pull/5017 but this library does not seem to be included anywhere..... At least I did not find any include referencing it.

**Comment by linc** [comment]
It was the OpenID plugin. If it's definitely no longer used by that plugin, kill it with fire.

**Comment by DaazKu** [comment]
I checked our repos and our clients repos and did not find anything using it.
I'm gonna remove the library!

**Comment by DaazKu** [comment]
PR is under review!
