### ISSUE TITLE
Move PCLZip dependency to Composer

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4840]
Currently in library/vendors; only used in the importer as far as I can tell. Will also be a version upgrade so please test carefully.

**Comment by DaazKu** [comment]
Only used in `UpdateModel`.
`UpdateModel` is only used for its `runStructure()` method which never call any of its internal methods.

Every methods in there but `runStructure` are essentially dead code.
I'm gonna update mode the library anyway for safety measure but I'll also put a deprecated tag on the methods and file an issue to clean them at the end of the year.

**Comment by DaazKu** [comment]
Deprecating -> https://github.com/vanilla/vanilla/pull/5019

**Comment by DaazKu** [comment]
Cleaning issue: https://github.com/vanilla/vanilla/issues/5020
