### ISSUE TITLE
Move Drupal & WebWiz hashing to a "vanilla/legacy-passwords" repo via Composer

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4842]
Publish this on Packagist (may require Linc or Todd) rather than doing the janky repo include via Composer.

These two methods should be quarantined because Drupal is a GNU GPLv2 license we do not have copyright for, and the WebWiz code has a custom (ambiguously incompatible) license ("Free to distribute as long as code is not modified, and header is kept intact").

**Comment by DaazKu** [comment]
Can I have the repo created please?

**Comment by linc** [comment]
Let's make this optional and gracefully fail if it's not present.

**Comment by DaazKu** [comment]
You can't create an optional dependency using composer but I made sure that Vanilla will work perfectly if the package is removed from the require section.

**Comment by linc** [comment]
Dependency merged.
