### ISSUE TITLE
Database installs with lowercase table and column names on Windows 10

### ISSUE THREAD

**Issue by ronrun** [vanilla/vanilla#4843]
I installed on my pc, which is windows10. Nothing wrong. Then I upload files to the remote server(linux), dump sql from my pc and import into remote sql. 

You have to delete *.ini files in /cache, and set the cache folder writable. Then the page sows "Something has gone wrong" Enabled debug & Reload the page, it says:

 "Table vanillaforum.GDN_UserRole doesn't exist"

How could that be? I check the database, all table names are lower case! 
I upload the orignial source code to remote server, do the installation on it.
Then check the database table names, It is really "GDN_UserRole" on the linux server, not "gdn_userrole" on my windows pc. 

So this is windows, linux issue. Most of the time, windows system is case insensitive. On linux system, all case sensitive.

**Comment by linc** [comment]
I've edited the issue for clarity.

**Comment by DaazKu** [comment]
I've had the same problem between Mac OSX and Linux.
What happens is that the table are created correctly in MySQL but on disk they are lowercased.
I'm pretty sure there is not much we can do about it.

**Comment by linc** [comment]
Sounds like an operating system limitation we can't easily work around.

**Comment by R-J** [comment]
Since Linux is not a requirement, I think it should at least be considered to take care for that.

How about setting `lower_case_table_names` to 2 for Windows systems and to 0 for Linux systems (like it is adviced [here](http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html)) in /utility/structure?

**Comment by DaazKu** [comment]
This is not something that can be changed at runtime.
Changing this can also break your already created tables.

Everything works fine unless you try to move from a case insensitive system to a case sensitive one.

**Comment by linc** [comment]
> Since Linux is not a requirement, I think it should at least be considered to take care of that.

This isn't about not supporting an OS, it's about not supporting seamless data migration between systems with different case sensitivity.
