### ISSUE TITLE
Can't signup on vanillaforums.org

### ISSUE THREAD

**Issue by VeeK727** [vanilla/vanilla#4853]
This s really frustrating but the signup process is failing in every corner of vanillaforums.org. First I tried to register with the register link and filled in all my details. I get an error that says `Tell us why you want to join!`. And a new field has appeared which wasn't here before. Okay, I oblige and enter a reason, click submit again and get another error that says `'User REDIRECT_APPROVE not found`'. 

After trying several times, I tried to login with facebook, it receives the info, then asks for a username and github...something. I'm entering the username of github here.
____________________________
![69](https://cloud.githubusercontent.com/assets/11595460/20552922/ab8dc114-b175-11e6-90a1-4c488a77ed67.jpg)
____________________________
Anyways, I enter both details and click on connect, and get an error
____________________________
![70](https://cloud.githubusercontent.com/assets/11595460/20552929/bf55eb0e-b175-11e6-9135-7e9f3862bc42.jpg)
____________________________
There is no field to enter why I want to join. I click connect again, since github username is already filled in and get this error
____________________________
![71](https://cloud.githubusercontent.com/assets/11595460/20552938/e06d7474-b175-11e6-8b49-78f60bd0ffd2.jpg)
____________________________
And we're back to square one. Can't go anywhere from here.

**Comment by linc** [comment]
I'll take a look soon. I probably goofed up some config.

**Comment by VeeK727** [comment]
It's working now. Did you do something. Anyways if you think, the issue is resolved you can close it now.

**Comment by linc** [comment]
I hadn't done anything, no. Glad it's working now.
