### ISSUE TITLE
Dashboard v3 scrolling issue on short pages

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4868]
When I load `/dashboard/settings/registration`, on my 13" Macbook in Firefox, the footer is generated not too far from the end of the brief settings. I cannot scroll past it, making everything below "Reputation" inaccessible in the sidebar navigation. Toggling a sidebar section closed/open causes the footer to move down the page below the sidebar, fixing the issue for that pageload.

**Comment by slafleche** [comment]
In PR https://github.com/vanilla/vanilla/pull/5506
