### ISSUE TITLE
"Incorrect integer value" error on draft save when no category selected

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#4880]
When composing a new discussion, if one clicks "Save Draft" (or waits for the auto save interval) the following error appears on screen:

```
{ "Code": 256, "Exception": "Incorrect integer value: '' for column 'CategoryID' at row 1|Gdn_Database|Query|insert GDN_Draft \n(Body, CategoryID, InsertUserID, UpdateUserID, Name, Format, DateInserted, DateUpdated) \nvalues (:Body, :CategoryID, :InsertUserID, :UpdateUserID, :Name, :Format, :DateInserted, :DateUpdated)", "Class": "Gdn_ErrorException" }
```

Some digging reveals that this is because the CategoryID field is empty (suspect problems at  [models/class.draftmodel.php:161](https://github.com/vanilla/vanilla/blob/ec5b13f6713dae42cd835267cea328d8e8559432/applications/vanilla/models/class.draftmodel.php#L161)).

**Comment by michaeltyson** [comment]
I've worked around the issue for now by introducing a default category setting. In applications/vanilla/controllers/class.postcontroller.php:107, I've added:

```
        if ($CategoryUrlCode == '' && C('Vanilla.Categories.Default')) {
            $CategoryUrlCode = C('Vanilla.Categories.Default');
        }
```

Then in config.php:

```
$Configuration['Vanilla']['Categories']['Default'] = 'General';
```

**Comment by linc** [comment]
Is this in the current `master`, 2.2, or 2.3?

**Comment by michaeltyson** [comment]
Sorry - this is in 2.3 (although it doesn't appear that routine has changed in master)
