### ISSUE TITLE
Standard way to add a custom home page

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4908]
Since I started making themes, pretty much every client wants a custom home page. There's a lot of different ways to go about it, there should be a standard, built in solution to do it. In the theme tab you should be able to select custom home page (maybe we should also have a new tab in customize theme for it). There should also be a standard view to overwrite.

**Comment by R-J** [comment]
I wouldn't say that the choice of the homepage should be set under the theme sections. There is `/dashboard/settings/homepage` which is explicitly named "Homepage" ;-)

But to set a custom homepage you  need to change the "DefaultController". Look at `/dashboard/routes/edit/DefaultController`.

It might be helpful to mirror that setting under Homepage, but on the other hand that would show one and the same setting at different places, which I think shouldn't be done.

But maybe adding a short hint, something like "*Change the route of the DefaultController if you want to set your homepage manually*" together with an appropriate link would be nice.

**Comment by slafleche** [comment]
My new plan is to create a `default.home.tpl` page. By default, it ONLY contains `{asset name="Content"}`. The idea is that on the home page, we take what goes in the default master's "Content" and just pass it through that view.

This is compatible with existing themes, since by default we do nothing. However, it would allow a theme to overwrite the view and modify it and being future proof.

Longer term we need a better solution to this. This at least gives us a "real" home page view instead of needing to hack the default master for it. I'm also aware many home pages will require to use theme hooks and/or modifying the default master to make more drastic changes. However, I still think this is better than nothing.

It also ties into [other ideas I have](https://github.com/vanilla/multisite/issues/200).

**Comment by charrondev** [comment]
Closing for https://github.com/vanilla/vanilla/issues/9491
