### ISSUE TITLE
Category dropdown not shown when posting to a particular category. 

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#4910]
Up to Vanilla 2.3 if you were looking at a discussion and started a discussion right there, the category dropdown has been already filled with the current category. 

The current master doesn't show this dropdown any more (based on [this commit](https://github.com/vanilla/vanilla/commit/26ed2960207338c7540c900edcd9ae3a5d3aafba))

Into my opinion the previous behavior had several advantages:
1. It was easier to spot which category you were posting to
Now you have to judge by the breadcrumbs. Users might not even think about being in the correct category because they do not have a choice for selecting a more appropriate category.

2. The category could easily be changed
Now if you want to post to a different category, you have to navigate to the home page, before you click on the "New Discussion" button in order to be able to select a category. Although this may sound like "only one click more", I would say that every click counts in regards to usability. In this case it is also not only one click, but one additional page load.

3. A post to the wrong category could be corrected by the user (if he has edit rights)
Now if a user notices he had chosen the wrong category, he would have to ask a moderator or admin for help.

Personally I was really confused when I noticed that behavior. I even thought that this must be some kind of strange bug and I was surprised to find a PR that changed this on purpose.

**Comment by linc** [comment]
Problem is that the category list can be astronomically large and be a scaling challenge to load every time on New Discussion pages, so I believe Todd was trying to limit how often we need to build it. A fine compromise would be to add a "Change Category" option that dynamically loads the list if it's needed.
