### ISSUE TITLE
Correct time zone for guests

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#4927]
Currently, Vanilla will only check the user's time zone when they are logged in. Guests get the forum default time zone (which I suppose is UTC). It would be good for guests to see the proper times as well.

I realize that the time zone logic is done server-side and the time zone is only available from JavaScript. Perhaps dates and times can be output with some JS code to switch to the correct zone when JS is enabled?

**Comment by charrondev** [comment]
This is a gradual process. Some new component are using our new `<DateTime />` react component that using javascript to generate accurate user times.

The implementation of this seems like it will be a gradual thing however.
