### ISSUE TITLE
Dashboard design: Clean up the Main Menu

### ISSUE THREAD

**Issue by danmaitland** [vanilla/vanilla#4936]
Let's clean up the main menu and have it fixed at a height of 60px and have it so it doesn't slide out and back in again.

<img width="721" alt="vanilla_admin_4nov16 sketch 2016-12-13 11-06-05" src="https://cloud.githubusercontent.com/assets/17601564/21147849/54a5ab14-c124-11e6-86e5-4334de2d72c2.png">

Ask Dan for the HTML Export Mock up for detailed specs

**Comment by charrondev** [comment]
The dashboard menu style was updated by @tburry in 2.7.
