### ISSUE TITLE
Error when clicking 'delete poll' after post in 2.3

### ISSUE THREAD

**Issue by webstey** [vanilla/vanilla#4955]
2.3, Cloudy Pro theme.
Steps:
- create new discussion ('include poll' is checked by default for some reason)
- click submit
- on discussion page, click 'delete poll'

Result:
![screen shot 2016-12-21 at 8 17 50 am](https://cloud.githubusercontent.com/assets/9970665/21389188/b5e009a0-c756-11e6-8a27-c7a9b198373f.png)

**Comment by DaazKu** [comment]
The DiscussionPolls plugin is not supported by Vanilla's.
It is an Open Source plugin.

https://open.vanillaforums.com/addon/discussionpolls-plugin
