### ISSUE TITLE
Inconsistent use of new tab/window when parsing UGC links

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4958]
Links in user-generated content inconsistently open in the same or a new window (via `target="_blank"` parameter).

* BBCode (default): New
* BBCode (NBBC): Same (?)
* LinksCallback (basic pasted link): New
* Markdown: Same
* HTML: Same (?)

We should standardize this. I suggest by always opening in a new tab.

**Comment by beckyvb** [comment]
I've done some research on this. There's a vulnerability with `target="_blank"` where the linked page gains control of the window.opener object. We can fix this by adding a `rel="noreferrer noopener"` to the link which effective sets the window.opener to null. See https://mathiasbynens.github.io/rel-noopener/ . I'm more inclined to remove `target="_blank"` altogether. Adding `target="_blank"` forces a behaviour on the user that may not be expected or desirable. If they want to open in a new tab, they can decide to do so. We don't need to force them. The only good argument that I can see for choosing to make our ugc links to use `target="_blank"` is addressed here: https://css-tricks.com/use-target_blank/#article-header-id-7 Opening in a new tab can be beneficial to the user if they're working on something on the page (in Vanilla's case, a new comment). All the same, I recommend we remove `target="_blank"` from all ugc links in favour of letting the user have control over their browsing experience.

**Comment by linc** [comment]
Make it so.
