### ISSUE TITLE
Disallow forward slashes in usernames, even over SSO

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4960]
Vanilla should never allow the creation of a username with a forward slash.

It needs to gracefully error with a good message over SSO.

This should be done with enough flexibility to disallow other characters in the future.

See:
https://github.com/vanilla/vanilla/issues/2471
https://github.com/vanilla/vanilla/issues/2376

**Comment by JasonBarnabe** [comment]
I assume there may be other characters that Vanilla doesn't like, so if you put in a hard restriction, please document the pattern user names must follow so that the SSO host can enforce it as well.

**Comment by DaazKu** [comment]
This is not a problem anymore since https://github.com/vanilla/vanilla/pull/4353
There is still problem with `\` though. (We just need to escape it)

**Comment by linc** [comment]
> There is a still problem with \ though.

Wanna elaborate? The same problem, or a different one?

**Comment by DaazKu** [comment]
![screen shot 2017-01-03 at 10 37 57 am](https://cloud.githubusercontent.com/assets/2412909/21612843/b823d65c-d1a0-11e6-952f-4680208bdbbb.png)

[We replace backslashes by slashes in the dispatcher...](https://github.com/vanilla/vanilla/blob/00210bd5f25d4ac04aff93b3ac11393e3f8c5d2d/library/core/class.dispatcher.php#L306)
