### ISSUE TITLE
Dashboard: Connection is Not Secure after switch from HTTP to HTTPS

### ISSUE THREAD

**Issue by caugner** [vanilla/vanilla#4962]
When using Vanilla 2.3 and switching from HTTP to HTTPS, pages that include the System user's profile photo (such as the section "Recently active users" on "/dashboard/settings" or the System user's profile) yield a "Connection is Not Secure" warning in Firefox (53.0a1) or "Your connection to this site is not fully secure" in Chrome (55.0), because the image is requested via HTTP.

This is a potential security issue, as the cookie (which is not set to "HTTPS only") is sent with the unsecure HTTP request.

**Comment by linc** [comment]
Let's do a quick re-audit of HTTPS in the Dashboard as part of this issue in case there are any other cases besides those avatars.

**Comment by beckyvb** [comment]
Hey @caugner ! I'm trying to diagnose your issue. If possible, can you let me know a few things: do you have the line `$Configuration['Garden']['AllowSSL'] = true;` or `$Configuration['Garden']['ForceSSL'] = true;` set in your config? Do you have any avatar setting plugins enabled (i.e., Gravatar or Vanillicon)?  If you have a default avatar set, is the value of `$Configuration['Garden']['DefaultAvatar']` a relative or absolute path? Thanks!

**Comment by linc** [comment]
Closing for lack of feedback.
