### ISSUE TITLE
CombineAssets does not combine vanillicon.css

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#4968]
I recently set $Configuration['Garden']['CombineAssets'] = TRUE; which nicely combined most of the CSS my forum uses into a single file. However, vanillicon.css does not seem to have been combined.

```html
  <link rel="stylesheet" type="text/css" href="//greasyfork.org/forum/asset/css/desktop/style-af2acf5a.css" media="all" />
  <link rel="stylesheet" type="text/css" href="/forum/resources/design/vanillicon.css?v=2.3" media="all" />
```

Vanilla 2.3.

**Comment by linc** [comment]
That file is compiled separately by design.
