### ISSUE TITLE
Backport mysqli use to 2.3

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4970]
https://open.vanillaforums.com/discussion/32969/call-to-undefined-function-mysql-connect#latest

**Comment by DaazKu** [comment]
I cherry-picked

6be308b57d07a72a09b1417344f5da85a2229d45
584d75a47115d2142bfceb35b781da0a42bdf507
0feaa43ab1067db10668a3b622062345731a38a2

into release/2.3
