### ISSUE TITLE
Remove `Vanilla.Categories.Use` config setting in favour of automatic detection

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4973]
Vanilla checks the value of `Vanilla.Categories.Use` [in almost 15 places](https://github.com/vanilla/vanilla/search?utf8=%E2%9C%93&q=%22Vanilla.Categories.Use%22&type=Code).

We should instead remove the config checks and replace them with a detection of if only the root category is currently present.

**Comment by linc** [comment]
I'd rather file an issue on how to make that config go away and just automatically hide categories if there's only 1 in use.
