### ISSUE TITLE
Dashboard: Messages Management design realignment

### ISSUE THREAD

**Issue by danmaitland** [vanilla/vanilla#4975]
Some small tweaks to the Message Management section based on the current design as well as the create/edit messages modal window.

<img width="1369" alt="vanilla_admin_4nov16 sketch 2017-01-04 09-28-43" src="https://cloud.githubusercontent.com/assets/17601564/21645501/32d4b938-d260-11e6-82e2-afb758d1bf6f.png">

<img width="1367" alt="vanilla_admin_4nov16 sketch 2017-01-04 09-29-19" src="https://cloud.githubusercontent.com/assets/17601564/21645518/47a91570-d260-11e6-979c-235fdb1a5fd1.png">

For the detailed HTML Export spec ask Dan

**Comment by charrondev** [comment]
Closing because if we do circle back to this it will likely be with new mockups.
