### ISSUE TITLE
Add option to disable view option in dashboard for customized themes

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#4984]
With highly customized themes, we often only styles one view for the homepage, categories and discussions. It would be useful to be able to remove the option to change a layout entirely from the dashboard in those cases. That would prevent the client from being able to break their theme.

**Comment by linc** [comment]
I'm not following this exactly, but it sounds like you're trying to file an issue against the Customize Theme addon which isn't in this repo. I think it needs more clarification as well.
