### ISSUE TITLE
Youtube URL having trouble with timestamps

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#4985]
http://laura.vanillademo.com/discussion/567/test#latest

It seems that youtube now serves its urls without a hashtag and its causing problems:

#t=50s - works
#t=52s - works

t=52s - Starts at 0:02
t=2m20s - Starts at 2:00
t=2m29s - Starts at 2:09 

#t=2m20s - Starts at 0:02
#t=2m29s - Starts at 0:02

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
