### ISSUE TITLE
Visiting addon list pages should clear the appropriate cache

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#4989]
Until the enhancements of #3835 are in, we should provide a stop-gap measure that auto-clears the addon cache when you visit the Plugins/Themese/Applications pages. This will help developers and save any site administrator some major headaches, and alleviate the need for a bunch of extra communication overhead for a 2.4 release.

This change should get reviewed by @tburry.

**Comment by initvector** [comment]
Closing in favor of tracking the issue via the associated PR
