### ISSUE TITLE
Registration flagged as SPAM trigger the "Tell us why" message over SSO

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#4991]
> Notice they are getting the "Tell us why" validation message. It looks like this is also used when the registration is flagged as spam, regardless of whether the Approval registration method is used. I think someone made the assumption that the only way a spam check would happen at that step is if it was Akismet intercepting the discovery text of the Approval method, but clearly that isn't so.

It should be confirmed but SSO users should not be checked for spam I think.

**Comment by initvector** [comment]
Closing in favor of tracking the issue on its PR: https://github.com/vanilla/vanilla/pull/5215
