### ISSUE TITLE
Caching and Whitespace in Category Slugs

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#4996]
Vanilla uses category slugs in some of its category cache keys.  [Whitespace is not allowed in memcached keys.](https://github.com/memcached/memcached/blob/d9dfbe0e2613b9c20cb3c4fdd3c55d1bf3a8c8bd/doc/protocol.txt#L48-L49)  If whitespace characters are included in the category slug, it can errors when communicating with the caching server.

Vanilla should either block whitespace characters from being part of category slugs or filtering them out [when generating slug-based category keys](https://github.com/vanilla/vanilla/blob/3f9eef442246f058b82084325e2584a3a523516e/applications/vanilla/library/class.categorycollection.php#L241).

**Comment by DaazKu** [comment]
We should update our memcached class to make sure that keys do not contains invalid characters.

[memcached::store()](https://github.com/vanilla/vanilla/blob/eff2223eb13bec69199cc159a01a59d3138fec2d/library/core/class.memcached.php#L433)
[memcached::get()][https://github.com/vanilla/vanilla/blob/eff2223eb13bec69199cc159a01a59d3138fec2d/library/core/class.memcached.php#L503]
