### ISSUE TITLE
Addons can break forum with RegisterPermissions = true

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5000]
In the addon info array, setting `RegisterPermissions => true` instead of to an array causes a column with name `1` to be created, breaking permission checks. We should fix our handling of this rather than trying to find all addons that do this.

**Comment by DaazKu** [comment]
I don't see that problem.

I enabled the Who's online plugin and set `'RegisterPermissions' => true,` in the plugin info.
I cleared my cache but have not seen any problems.
I checked the **Roles & Permissions** and **Category's custom permissions** section.

Can I have more info?

**Comment by linc** [comment]
https://open.vanillaforums.com/discussion/32975/user-sign-in-permission-denied

**Comment by R-J** [comment]
In the applicationmanager you find that code:

~~~
    public function registerPermissions($applicationName) {
        ...
        $PermissionName = val('RegisterPermissions', $ApplicationInfo, false);
        if ($PermissionName != false) {
            ...
            $PermissionModel->define($PermissionName);
~~~

So **any** value for PluginInfo['RegisterPermissions'] (except `false`) is passed to the PermissionModel->define() and here is where something should be changed:
~~~
    public function define($PermissionNames, $Type = 'tinyint', $JunctionTable = null, $JunctionColumn = null) {
        $PermissionNames = (array)$PermissionNames;
~~~

A `true` will be converted to [true] and the following code creates a column "1" in the permission table:
~~~
        ...
        foreach ($PermissionNames as $Key => $Value) {
            if (is_numeric($Key)) {
                // Only got a permissions name with no default.
                $PermissionName = $Value;
                ...
            }
            ...
            // Define the column.
            $Structure->column($PermissionName, $Type, 0);
~~~


The only thing that worries me a bit is that I wasn't able to reproduce the login problems. Even with such a column my permissions look okay, but when I was looking at the permissions of the guy who come up with this problem, I saw [very strange results](https://open.vanillaforums.com/discussion/comment/240930/#Comment_240930).

**Comment by DaazKu** [comment]
Thank you for this insight @R-J !
I will take a look at this before the end of the week!
