### ISSUE TITLE
Add LastCategoryID in Category Table

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5032]
A new field should be added to the Category table: `LastCategoryID`.  This field will hold the category with the most-recent post for that branch of the tree.  The value should be used when retrieving the aggregate latest-post values for the category.  `CategoryCollection` elements should already have the latest-post fields populated.

A DBA task will also be needed to populate this field, en masse.

**Comment by linc** [comment]
Being handled elsewhere.
