### ISSUE TITLE
Duplicate system user post migration

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5034]
## EDIT:
This is still a bug. We will need to find out the exact cause and fix it!

------------
This is relevant since we clear that config when doing a migration.

**Comment by linc** [comment]
I don't agree this is a bug.

If you don't want a new System user made, it can be set in the config. There's no safe way to detect an existing System user, and there's nothing wrong with a new one being created.

**Comment by DaazKu** [comment]
There is already an attempts a fixing this here: https://github.com/vanilla/vanilla/blob/502ad7315b83cd59255ccbf7def901fbe83098bc/applications/dashboard/settings/structure.php#L138

/profile/System point to the first system account.

**Comment by DaazKu** [comment]
Also, during the migration process, we wipe out that config for it to be regenerated.

**Comment by topcheese13** [comment]
@DaazKu Fix you are referring to (https://github.com/vanilla/vanilla/blob/502ad7315b83cd59255ccbf7def901fbe83098bc/applications/dashboard/settings/structure.php#L138) seems to work. I wasn't able to reproduce the duplication of a System User either locally or on the test site.

**Comment by topcheese13** [comment]
I found out that the multiple System Users issue isn't a result of utility/update but a result of spoofing in when there is no System User set in the config. This happens particularly post migration.

Here is the function I'm referring to:

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermodel.php#L1667
