### ISSUE TITLE
recaptcha problem

### ISSUE THREAD

**Issue by ubuntutest** [vanilla/vanilla#5035]
Hello,
I'm downloaded from here reCAPTCHA plugin.
I've installed it, but how i can make it working?
I'm getting the following error in console:

```
Uncaught Error: Missing required parameters: sitekey
    at new wn (recaptcha__it.js:284)
    at new Wn (recaptcha__it.js:292)
    at ho (recaptcha__it.js:298)
    at recaptcha__it.js:302
    at Me (recaptcha__it.js:55)
    at recaptcha__it.js:301
    at recaptcha__it.js:382
recaptcha__it.js:284 Uncaught Error: Missing required parameters: sitekey
    at new wn (recaptcha__it.js:284)
    at new Wn (recaptcha__it.js:292)
    at ho (recaptcha__it.js:298)
    at recaptcha__it.js:302
    at Me (recaptcha__it.js:55)
    at recaptcha__it.js:301
    at recaptcha__it.js:382
```
I do not have any form where to insert keys
Thank you

**Comment by ubuntutest** [comment]
Anyone?

**Comment by R-J** [comment]
Please look at yourforum.com/dashboard/settings/registration, there you will find two input boxes for entering the public and private key.

**Comment by ubuntutest** [comment]
I've already inserted the keys there.
Maybe they are incorrect
Where do i find it?

**Comment by R-J** [comment]
Is it a new installation? Then you should check the file permissions of your config file. The error message states that your keys are **missing**. Maybe they weren't saved.

**Comment by ubuntutest** [comment]
Something is strange,
I've disabled "reCAPTCHA Support" and "Add Registration Question" and its working pretty good. I have no plugin enabled
