### ISSUE TITLE
Warn when AddonManager encounters a duplicate addon key

### ISSUE THREAD

**Issue by evach-vf** [vanilla/vanilla#5053]
Currently, if an **application** and a **plugin** have the same key name such as `vanillastats`, only the plugin gets scanned and the application is skipped silently, even though it shows as enabled in the dashboard.

It would be useful to warn whenever that happens so that we could troubleshoot the problem without enabling and disabling plugins until we find the culprit.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5672
