### ISSUE TITLE
Discussion Model GetWhere (deprecated notice) / getWhereRecent

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#5070]
The order of Offset and Limit are switched round between 2.2 and 2.3

There is a depreciation notice, but it doesn't take into consideration that the order used to be offset then limit and now is limit then offset. getWhereRecent using this order. 

Personally I think using getWhere in the deprecated form should throw an error.  Currently it is not obvious to developers of plugins, and they will get odd results as a result.

**Comment by x00** [comment]
@Todd according to blame, it used to be the case that getWhereRecent would maintain backward compatibility, but the order of limit and offset was changed. An error, rather than a notice would make more sense. so plugins still using getWhere in this way are made aware to use getWhereRecent and how.

**Comment by tburry** [comment]
Yeah, I made the decision to make getWhereRecent() have an order that is consistent with other calls. Devs that actually make the change will hopefully notice the order. Devs that don't look at notices should still see their use of getWhere() as backwards compatible. Of course law of averages says some devs might just change the function call and deploy.

**Comment by x00** [comment]
getWhere isn't backward compatible and I didn't see the notice in the trace.

**Comment by x00** [comment]
it is getWhere where the order has changed getWhereRecent  is just a new method as far as I'm concerned. I learned by looking at the code.

**Comment by linc** [comment]
I don't think we're going to revisit this at this point.
