### ISSUE TITLE
Update from 2.3 to 2.4 breaks dashboard

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5086]
In 2.4 applications/vanilla/controller/class.settingscontroller.php has been deleted.

The normal upgrade process does not include a deletion step, so the file from 2.3 still exists. As a consequence, all /dashboard/settings links are routed through that router which standard method is "managecategories". That's why several settings are not accessible after a standard update.

It might be better to still supply such a file with only an index method that tells the user something like `'Please delete the file "'.__FILE__.'" manually'` and also give the link to the corresponding views "applications/vanilla/views/settings"

At least the fact that these artifacts exist and must be deleted should be told to admins.

**Comment by linc** [comment]
See also https://github.com/vanilla/vanilla/issues/2518
