### ISSUE TITLE
There is no feedback that a plugin has been auto-enabled

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5087]
When I enabled plugin "A" which requires plugin "B", "B" is automatically enabled. The slider of plugin "A" moves and I get a message "Plugin A Enabled." It would be great if also the slider for plugin "B" would change or at least the message "Plugin B Enabled." would also appear.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: https://github.com/vanilla/vanilla/pull/5669
