### ISSUE TITLE
Create the /api/v2/addons endpoint

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5109]
<s>Depends on #5108.</s>

GET /api/v2/addons

- Get all enabled addons, filtering out those the hidden ones.
- Querystring all=1 will get all addons.
- Querystring search=xxx will search on name and description.

GET /api/v2/addons/\<key\>

- Get the details of a single addon. This will be just the row from the above endpoint.

PATCH /api/v2/addons/\<key\>

- Enable/disable an addon.
- Accepts parameter **enabled**
- Returns the result from the AddonModel->setEnabled

**Comment by initvector** [comment]
Closed by #6160
