### ISSUE TITLE
Mentions: Ampersand should be a terminating character

### ISSUE THREAD

**Issue by jasonsavard** [vanilla/vanilla#5126]
library/core/functions.general.php > getAllMentions()
current:
$parts2 = preg_split('`([\s.,;?!:])`', $part, 2, PREG_SPLIT_DELIM_CAPTURE);
proposed:
$parts2 = preg_split('`([\s.,;?!:&])`', $part, 2, PREG_SPLIT_DELIM_CAPTURE);

library/core/class.format.php > formatMentionsCallback()
same proposed regex should be applied here to and probably refactored as a constant
current:
$parts2 = preg_split('`([\s.,;?!:])`', $str, 2, PREG_SPLIT_DELIM_CAPTURE);
proposed:
$parts2 = preg_split('`([\s.,;?!:&])`', $str, 2, PREG_SPLIT_DELIM_CAPTURE);

**Comment by charrondev** [comment]
It is as of https://github.com/vanilla/vanilla/pull/6817
