### ISSUE TITLE
Enhance category slug validation

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#5127]
The auto generation and backend validation (manual editing) of the slug should respect these points.

- [x] Spaces are not allowed.
  - Slugs should not contain spaces. It was also causing problems with memcached (got fixed)
- [x] `ctype_digit($slug)` should return false.
  - The user will get routed to a category with the ID of the slug otherwise.

Related to https://github.com/vanilla/vanilla/issues/4996

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR.
