### ISSUE TITLE
FINISH HIM! (library/vendors)

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5129]
Remove simplehtmldom (we've forked for 2.4, doooooo it), the /library/vendors folder, and anything that looks for that folder.

Depends on https://github.com/vanilla/vanilla/issues/5128

**Comment by DaazKu** [comment]
Waiting on https://github.com/vanilla/vanilla/pull/5246

**Comment by linc** [comment]
Clear

**Comment by DaazKu** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/5281
