### ISSUE TITLE
Image file sizes getting larger when uploaded (JPG only?)

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5137]
As documented on PA:
http://forums.penny-arcade.com/discussion/209551/vanilla-resizing-images-to-make-them-larger#latest

**Comment by linc** [comment]
The issue appears to be that when we open a compressed JPG image for processing, it can result in the file actually getting larger when it's re-saved. This is going to require some investigation to determine how we want to detect and fix this situation.

Let's make sure we summarize issues on GitHub and not rely on references on other sites.

**Comment by Charrondev** [comment]
A simplish solution here is to check the file size before and after the compression and if the original is smaller use that instead.

This can likely be attributed the person originally compressing the image using a better compressor than us or running it slower.

**Comment by linc** [comment]
There are also the dimensions to consider, which is why we're opening the image and re-saving it to begin with. By simply inspecting filesize, you risk allowing thru an image with dimensions that are too-large, thereby opening us to a different type of support issue.

**Comment by Charrondev** [comment]
Maybe the resize and compression should be different steps? We would need to do the resize, then compare that intermediate result to the final compressed result.

I'd imagine we'll be trying to do more of our resizing on the frontend anyways with a interactive cropper in the future. This would allow people to upload large images more easily (many people have a slow uplink and may accidentally an image of a few megabytes in size). I we attempt to do this on the frontend first we could make their image uploads much faster.

Then the server can check the dimensions. If they are the exact dimensions or a smaller dimension of the same ratio, then the server can skip the resizing step and just do the compression. The results before and after the result are compared and the smaller value is chosen.
