### ISSUE TITLE
WYSIWYG quote author link is broken when previewing HTML

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#5151]
Viewing the HTML of a WYSIWYG-formatted post with a quote in it breaks the link to the quote author.

Steps to reproduce:
1. Make sure you have Advanced Editor enabled and format set to "WYSIWYG"
2. Quote a post
3. Click on the HTML preview

Result:
The link to the author's profile is broken

**Comment by EricChadwick** [comment]
This also occurs when step 3 = Paste text into the editor.

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.
