### ISSUE TITLE
Write the jsonFilter() function

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5156]
As we start making types more restrictive with the Schema and also use JsonSerializable more we will start having issues where json_encode() fails because of one bad value. We already had this happen with dbencode(). To help with this we want a **jsonFilter()** function that can be called on a variable before json_encode().

The things we need to filter now are the following.

- DateTimeInterface: ->format('r'). This is the main one.
- Unpack IP addresses in a similar way to how dbdecode() does it.
- We will add others as separate PRs.

Here is a suggested stub.

```php
function jsonFilter(&$value) {
   $fn = function (&$value, $key = '') use ($fn) {
        // ...
   }

    if (is_array($value)) {
        array_walk_recursive($value, $fn);
    } elseif (...) {
        // ...
    } else {
        $fn($value);
    }
}
```

**Comment by initvector** [comment]
Closing in favor of tracking the issue via the associated PR
