### ISSUE TITLE
Update changelog to include recent releases

### ISSUE THREAD

**Issue by rmzelle** [vanilla/vanilla#5171]
The latest release listed at http://docs.vanillaforums.com/developer/changelog/ is 2.1.6 from 2014, while 2.3 is out (https://open.vanillaforums.com/discussion/32822/vanilla-2-3-is-now-available).

**Comment by scottbuscemi** [comment]
The changelog isn't being updated again... :/

**Comment by charrondev** [comment]
I hadn't noticed that this was so far behind. I've got an update pending with 2.4 -> 2.6 and some general improvements to that doc.

https://github.com/vanilla/docs/pull/287
