### ISSUE TITLE
Disable autocomplete on Edit Profile / Edit Account pages

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5189]
I just edited someone's user account on open.vf and my email auto-filled in their Title field. That's not a good thing.

**Comment by linc** [comment]
This just happened again in Firefox 57 on a user I've never edited before.

**Comment by linc** [comment]
`autocomplete="nothanks"` ???

**Comment by Charrondev** [comment]
What page does this title field show up on? Is it an extended profile field?

**Comment by initvector** [comment]
> What page does this title field show up on? Is it an extended profile field?

"Title" is a standard profile field. However, it requires the `Garden.Profile.Titles` config be set to `true`.

**Comment by Charrondev** [comment]
For some reason I don't see it on the open source forums 
![image](https://user-images.githubusercontent.com/1770056/33838056-50638df4-de5c-11e7-84c0-a643f796e0a2.png).

**Comment by linc** [comment]
Members can't edit their own title.
