### ISSUE TITLE
cannot find dashboard/setup

### ISSUE THREAD

**Issue by tykayn** [vanilla/vanilla#5191]
hi folks, i just downloaded a fresh pre-build version of vanilla 2.3 and cannot set it up on localhost.
when i go to http://localhost/vanilla , i am redirected to a "not found" page
http://localhost/vanilla/dashboard/setup

debug infos:

> my install folder is in chmod 777 recursive.
> PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies
> mod rewrite is enabled,
> mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
> i am on ubuntu 16.04 with php 7 (LAMP stack)

**Comment by DaazKu** [comment]
If you need help with your Vanilla installation you should direct your questions to https://open.vanillaforums.com/categories/vanilla-2-3-help

The issues in this repository are for bug reports.
