### ISSUE TITLE
Setting Garden.Cdns.Disable = true should make Vanilla use local versions

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#5207]
Setting Garden.Cdns.Disable = true makes Vanilla [not load jquery from ajax.googleapis.com](https://github.com/vanilla/vanilla/blob/e25fbcdea28685bb60e7fe232d99b7e7a01d126d/library/core/class.controller.php#L1729-L1734). But it doesn't make it start loading the local version (js/library/jquery.js), either, so stuff breaks.

**Comment by linc** [comment]
We no longer use the Google CDN.
