### ISSUE TITLE
NestedCollectionAdapter does not work well with non ascii locales

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5212]
[NestedCollectionAdapter::addLink()](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/library/class.nestedcollectionadapter.php#L35) use [slugify()](https://github.com/vanilla/vanilla/blob/master/library/core/functions.general.php#L3849) which strips any non ascii characters. 

Something like `Реакции` (Reactions) will get replaced by `n-a`.
When in the context of the dashboard site nav n-a is not a valid group and the link is then never added to the nav.

**Comment by nervoustwit** [comment]
This is also affecting the dropdown menu on the user profile page where mods now cannot mark a user as a troll or add notes to user in Japanese or Russian because it is passing an empty string to slugify.
