### ISSUE TITLE
Audit of redirect() and Controller->RedirectUrl

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5218]
In most cases, users should not be leaving the forum without being warned.
A review of every redirects needs to be done.

Both call to redirect() and $this->RedirectUrl should be reviewed.

~~It would also be wise to default redirect() to do a safeRedirect since it can be easy to forget that safeRedirect exists and what is the difference between the 2.~~ *This would introduce too many bugs if we do it*

~~We could deprecate safeRedirect and add a third parameter to redirect() which would do a safeRedirect by default.~~ See https://github.com/vanilla/vanilla/issues/5218#issuecomment-310513372

Depends on https://github.com/vanilla/vanilla/issues/5695

**Comment by DaazKu** [comment]
My current plan is to:
- deprecate `redirect()`, `redirectUrl()` and `Gdn_Controller()->RedirectUrl`
- create a `unsafeRedirect()` function which will be the counterpart to `safeRedirect()`
- create `Gdn_Controller->setSafeRedirect()` and `Gdn_Controller->setUnsafeRedirect()` which will take precedence over `Gdn_Controller()->RedirectUrl`
- Replace all call of `redirect()`, `redirectUrl()` to `unsafeRedirect()`
- Replace all assignation to `Gdn_Controller()->RedirectUrl` by `Gdn_Controller->setUnsafeRedirect()`

The PRs for this are almost done. Once this is approved I will start auditing all the unsafe calls.
After this update, awareness of the security implication of a redirect should be way more obvious.

**Comment by tburry** [comment]
Really I think redirect() is well named. I just think that safeRedirect() is maybe not properly named. Maybe we could also just make a parameter to check against whitelisted URLs?

WRT a controller method I'd prefer that the controller not get fatter also given that the API uses a different base class. Another option is a RedirectException that the dispatcher can handle.

**Comment by DaazKu** [comment]
The problem with the parameter is that we'd like it to be "safe" by default.
That way people won't call redirect incorrectly by default which is why we have non trusted redirection problem currently.

**Comment by DaazKu** [comment]
After an internal chat with Todd we ended up with the following plan:

- deprecate `redirect()`, `redirectUrl()` (It's almost an exact copy of redirect()), `safeRedirect()` `Gdn_Controller()->RedirectUrl`
- create `redirectTo($destination='', $statusCode=302, $trustedOnly=true)`
- create `Gdn_Controller->redirectTo($destination='', $statusCode=302, $trustedOnly=true)`
- replace all call to `redirect()`, `redirectUrl()` by `redirectTo($destination, $statusCode, false)`
- replace all call to `safeRedirect()` by `redirectTo($destination, $statusCode)`
- replace all assignation to `Gdn_Controller()->RedirectUrl` by `Gdn_Controller->redirectTo($destination, $statusCode, false)`

Then I will start the audit.
