### ISSUE TITLE
Dashboard: Change the "month/day" styling so they no longer appear as buttons

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5223]
Since we updated the dash to have a date range, the Day/Month options at the top are no longer tools to select anything, but rather status indicators. The issue is that, since they worked as buttons previously, they are causing some confusion on functionality. 

It is now essentially necessary to interact with the calendar, and the "today" that looks exactly the same, is actually a button.

**Comment by charrondev** [comment]
![image](https://user-images.githubusercontent.com/1770056/51815433-da056d80-228e-11e9-825f-77c8443ec684.png)

To clarify this issue:

The Day indicator and greyed out month indicator are what are referred to here.

- They look like buttons.
- They aren't clickable.
- They seem to be labels.

I think they're pretty confusing could just be outright removed. Is that ok with you @tburry?
