### ISSUE TITLE
Update "last" fields on category when deleting or moving posts

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5236]
The "last" fields (e.g. `LastCategoryID`, `LastDiscussionID`, `LastCommentID`) are updated when discussions and comments are added. However, they should also be updated when posts are deleted or moved. The next-most-recent post might be in another branch of the category tree, updating parent categories with the proper `LastCategoryID` might be tricky.

**Comment by ginahoy** [comment]
GDN_Category.LastDiscussionID & LastCommentID are not even updated when a new discussion is posted. I will open a new issue on this since it's unrelated to moving or deleting posts.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR.
