### ISSUE TITLE
Add header methods to the Garden\RequestInterface and Gdn_Request

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5240]
We are going to need to read request headers in a more structured way to do stuff like CORS. In order to do so we'll need to add header methods to the request object/interface.

Here are the methods we'll need:

```php
public function getHeaders(): array;
public function hasHeader($name): bool;
public function getHeader($name): string[];
public function getHeaderLine($name, $default = ''): string;
```

There are a few things to note here:

1. Header names should be parsed and normalized to the proper "Header-Name" notation from the incoming $_SERVER['HTTP_HEADER_NAME'].
2. Note the special cases in $_SERVER that are also considered headers: 'CONTENT_TYPE', 'CONTENT_LENGTH', 'PHP_AUTH_USER', 'PHP_AUTH_PW', 'PHP_AUTH_DIGEST', 'AUTH_TYPE'.
3. The **$name** arguments should take permissive names and be case insensitive. So I can call **hasHeader()** with "HTTP_HEADER_NAME", "HEADER_NAME", "Header-Name", "header-name" etc.
4. Unit test.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5963
