### ISSUE TITLE
API v2 CORS support

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5241]
Depends on #5240.

Since APIv2 use different controllers we're going to have to implement CORS separately. I haven't figured an elegant way to do so just yet so we'll probably just add an event to the Dispatcher.

- [ ] Meet with Todd on CORS support.
- [ ] Implement CORS support.

**Comment by DaazKu** [comment]
Blocked by https://github.com/vanilla/vanilla/issues/5240

**Comment by tburry** [comment]
CORS support ended up getting added already so I'm closing this.
