### ISSUE TITLE
Fail to open plugin settings when Vanilla is in a subdirectory

### ISSUE THREAD

**Issue by lazlo-bonin** [vanilla/vanilla#5273]
When trying to open a settings panel in the new dashboard, a 404 error is returned from the notification ajax in the bottom right corner. Looking at my Nginx access logs, I see that the request is attempted at the root (ex.: `GET /settings/oauth2?DeliveryType=VIEW&DeliveryMethod=JSON`) whereas other requests are taking into account the subdirectory (ex.: `GET /forum/utility/getfeed/news/5/extended HTTP/1.1`). The correct request should have been `GET /forum/settings/oauth2?DeliveryType=VIEW&DeliveryMethod=JSON`

I'm not familiar with the source, but I guess the part where the site URL gets added is missing somewhere in the new panel GUI.

**Comment by lazlo-bonin** [comment]
Found the fix: in `applications/dashboard/settings/helper_functions.php` line 164, replace:

`$media->addButton(dashboardSymbol('settings'), $settingsUrl, $attr);`

with:

`$media->addButton(dashboardSymbol('settings'), url($settingsUrl), $attr);`

**Comment by R-J** [comment]
Has been fixed with https://github.com/vanilla/vanilla/commit/ba21947b270a024a04ee77420b7571d495632061
