### ISSUE TITLE
Create plan to destroy Garden.SignIn.Allow

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5283]
Create a detailed plan & issue(s) for removing this permission.

Guests should be handled automatically as a special case.

All other roles shouldn't need to pass a permission check for authentication.

It's a major source of confusion and a piece of functionality that we haven't needed since 2011.

**Comment by initvector** [comment]
Closing in favor of tracking on new, more detailed RFC-style issue: #6198
