### ISSUE TITLE
Make sure that no indexes could be too large when using utf8mb4

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5284]
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html

> InnoDB has a maximum index length of 767 bytes, so for utf8 or utf8mb4 columns, you can index a maximum of 255 or 191 characters, respectively

We have one case where it COULD, in theory, be problematic and it is in the `GDN_UserAuthenticationToken` table:

```sql
`Token` varchar(128)
`ProviderKey` varchar(64)
```

In practice it will probably never happen but who knows.

**Comment by tburry** [comment]
I wonder if our db object supports a different encoding on a per-table basis. That would be the best, but probably not. Otherwise, I'd knock the provider key down. NBD.

**Comment by linc** [comment]
Let's also search around for additional `varchar(255)` definitions in our private repos as part of this.

**Comment by DaazKu** [comment]
Here is what i've found:

```
avatarstock.plugin.php:64 -> Path varchar(255)
class.wordpresimportmodel.php:52 -> UrlCode varchar(255)
class.disqusimporter.plugin.php:232 -> ForeignID varchar(200)
class.flagging.plugin.php:398 -> ForeignURL varchar(255)
class.sitehub.plugin.php:59 -> Url varchar(255)
class.sitehub.plugin.php:97 -> UrlCode varchar(255)
class.slugurls.plugin.pgp:29 -> Slug varchar(200)
class.subcomunities.plugin.php:45 -> Folder varchar(255)
class.vanillapop.plugin.php:[628,634,640,646] -> SourceID varchar(255)
```

**Comment by DaazKu** [comment]
We have 3 solutions that I know of here:

- Manually limit the index size to 191. 
    - This can cause collision...
- Shrink the column sizes.
   - We will need to do some verifications on the data first...
- Set the encoding to utf8 instead of utf8mb4 for these columns.
   - I do not think it is currently possible to do that using `Gdn_DatabaseStructure`.

**Comment by Charrondev** [comment]
This seems to have already been an issue [before](https://github.com/vanilla/vanilla/issues/2082)

**Comment by DaazKu** [comment]
The fix we did: https://github.com/vanilla/vanilla/pull/2712

**Comment by linc** [comment]
Yup. The issue now is just fix (resize) the ones we missed before, mostly outside of core.

**Comment by DaazKu** [comment]
https://github.com/vanilla/vanilla/pull/5402 will prevent data corruption on old installation.
The issue will have to be manually fixed if any problem occur but nothing will crash.
