### ISSUE TITLE
404 error message is not translation-friendly

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5289]
Substituting a "recordtype" into a preset sentence does not work well in languages that may need gender-specific references (el vs. la) or other issues. We got a little too efficient with it.

See also https://github.com/vanilla/vanilla/pull/5288

**Comment by nikoskip** [comment]
Thanks for creating the issue!

As a summarized idea: try to avoid using placeholders in nouns, at least nouns in spanish has a gender in contrast with english.

I really don't know if other languages has the same problem. But solving this we will get more accuracy translations, thus better user experience.

**Comment by charrondev** [comment]
This is worth keeping in mind with the new 404 pages.
