### ISSUE TITLE
Localization: WYSIWYG editor for emoticons in Spanish

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5291]
"In the WYSIWYG editor, the tooltip when hovering over the emoticons icon makes no sense whatsoever and is meaningless in Spanish"

Current ES: Texto ininteligible

Expected ES: Emoticonos

**Comment by charrondev** [comment]
This is not an issue in Rich Editor which is the default editor as of 2.8. Advanced Editor issues are now being de-prioritized if they do not have an active champion.

All rich editor emojis are native (and have native screen-reader support) and have titles set in the DOM for the picker.
