### ISSUE TITLE
Add endpoint for toggling a config

### ISSUE THREAD

**Issue by beckyvb** [vanilla/vanilla#5300]
Add an ajax endpoint that toggles a boolean config and updates the toggle in the view. It would be nice if it could optionally add `js-foggy` functionality to blur the settings if the toggle is disabled.

There are many settings pages where this would be handy:
Email -> `Garden.Email.Format` (This one isn't boolean, but it could be...)
Tagging -> `Vanilla.Tagging.EnableUI` (after https://github.com/vanilla/vanilla/pull/5292 is approved)
Roles & Permissions -> `Garden.PrivateCommunity`
Avatars -> `Garden.Profile.EditPhotos`
Plugins -> `Plugins.Pockets.ShowLocations`
Registration -> `Garden.Registration.ConfirmEmail`
Embedding -> `Garden.Embed.Allow'`

**Comment by linc** [comment]
Supplanted by #5751
