### ISSUE TITLE
Plural translation for minimum post length error message

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#5310]
The minimum post length error message does not check for the number of characters missing. We should have a plural and singular string.

**Comment by topcheese13** [comment]
MinLength string now `$Definition['ValidateMinLength'] = '%1$s is %2$s character(s) too short.';`

There are 2 possible solutions here

Either `$Definition['ValidateMinLength'] = '%1$s is %2$s character(s) too short.';`

Or
`$Definition['ValidateMinLengthSingular'] = '%1$s is %2$s character too short.';`
`$Definition['ValidateMinLengthPlural'] = '%1$s is %2$s characters too short.';`

I think the first approach is more generic but might cause more problems in different languages.

@linc

**Comment by linc** [comment]
Latter.
