### ISSUE TITLE
Dashboard hook checks MySQL version every page load

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#5313]
The Dashboard hooks file has a hook into `settingsController_render_before` in which it queries the MySQL version on every request to that controller. This is breaking the accounts system and probably should be a module instead, so that it can be disabled.

**Comment by linc** [comment]
This doesn't mention the query, and there's nothing in Dashboard's `settingsController_render_before`  but a PHP & MySQL version check today, so I believe this is resolved.

**Comment by linc** [comment]
1. Add an "always disable" setting in addition to the per-version disable.
2. Cache these checks for ~a minute.
