### ISSUE TITLE
Add IP packing/unpacking to DB level

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5323]
Unpacking and packing IP address fields should be moved down to the database level, so other models are not saddled with handling these fields. This can probably be done in `Gdn_Dataset`.

- We will pack/unpack columns that end in "IPAddress". Note that although jsonFilter looks at "IPAddresses" too this is probably a mistake and we no longer have such a field.
- Gdn_SqlDriver::namedParameter() is one method where they can be packed.
- You will probably have to make another version of PDO::quote() on the Gdn_SqlDriver that can handle packing too. Look for calls to quote and replace them with the appropriate method.
- In terms of unpacking I can only think that the Gdn_DataSet is the place to do it.
- While you are at it you can format DateTime objects too. Call format(DateTime::RFC3339).

**Comment by tburry** [comment]
Although packing IP addresses is kind of necessary given the size of the fields on IPv6, Vanilla should only know about them as strings. The packing and unpacking should be done inside of the database classes. This will require some refactoring and unit testing.

**Comment by tburry** [comment]
Also note that this will simplify the issue with the log table. Only direct columns with the correct name and type will be packed. All others will be left alone.

**Comment by DaazKu** [comment]
I spoke with Todd about this yesterday.

/quote [5:01 PM] Todd Burry: FYI: There is an issue where there isn't a clear serialize/unserialize instance method on Gdn_Model. That is something we should aim to slip in (protected), even if it is a no-op.

On the long term we could use the models' schema to auto detect what needs to be modified on select/insert

We could probably create a decorator around the SQL object like so:
```
$this->SQL = new SQLDecorator($this, $this->Database->SQL());
```

The SQLDecorator could then modify the data using the model instance when $this->SQL->query() is called.

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/8308

**Comment by tburry** [comment]
I'm wondering if we can close this one because the new model does everything more nicely. @initvector?
