### ISSUE TITLE
Function reactionButton() is used but not defined.

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5324]
https://github.com/vanilla/vanilla/blob/master/library/core/functions.render.php#L1616

I assume that function is defined as part of the closed source reactions addon.

Since rendering reactions is part of the OS version, too, I would expect to see such a function in functions.render.php.

**Comment by charrondev** [comment]
Permalink here https://github.com/vanilla/vanilla/blob/818e6a6dc387dd47a0a9fa78c6899aebf6ba7ecb/library/core/functions.render.php#L1881
