### ISSUE TITLE
Missing transifex strings, password strength

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5346]
"For a stronger password, increase its length or combine upper and lowercase letters, digits, and symbols."

I believe this was recently added, but I cant seem to find it in:
https://www.transifex.com/vanilla/vanilla/viewstrings/#pt/site_core/31977733

it looks like "ValidateStrength" is missing as well:
https://cloud.githubusercontent.com/assets/7501633/24212421/4c8a3482-0efd-11e7-95de-05723b8b3784.png

$Definition['ValidateStrength'] = 'The supplied %s is too weak. Try using a stronger password and use the strength meter as a guide.';

**Comment by charrondev** [comment]
These have been in the `locales` source strings for a while now. https://github.com/vanilla/locales/blob/master/tx-source/site_core.php#L606
