### ISSUE TITLE
/me actions not rendering. 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5356]
![image](https://cloud.githubusercontent.com/assets/7501633/24269799/a84c2350-0fe0-11e7-827b-4b78cfd83fcf.png)
They seem just straight up broken, all of these users have permission to use them, and the demo is on a base theme.

**Comment by charrondev** [comment]
I'm guessing this was some type of misconfiguration or an issue that has already been resolved. Some quick testing on 2.8 shows me that me-actions are rendering. For reference the config setting `Garden.Format.MeActions` needs to be enabled. Otherwise these don't get formatted.
