### ISSUE TITLE
Investigate failing Travis builds

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5379]
Our travis builds are failing a lot now and its becoming a big inconvenience. I'd like the build process to be tweaked to help us do some troubleshooting. Here are the things I want.

- Dump PHP error logs at the end of builds.
- Configure error logs to include stack traces.
- There are currently some notices coming out in the builds that can easily be fixed with an INI directive.
- Come up with some ideas on your own.

I'll consider this issue complete when we get some useful information about our failing builds.

**Comment by DaazKu** [comment]
Seems like this is not fixed.. https://travis-ci.org/vanilla/vanilla/jobs/224308262

**Comment by DaazKu** [comment]
For the specific remaining error: https://github.com/vanilla/vanilla/issues/5470
