### ISSUE TITLE
Facebook Connect plugin is broken: incorrect content type/use of file_get_contents

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#5381]
On several forums I manage, users are reporting Facebook Connect is no longer working; upon attempting a login with Facebook, one is presented with a form with an error up top reporting "UniqueID is required".

Some sleuthing revealed that the Facebook plugin (`plugins/Facebook/class.facebook.plugin.php`) is expecting a content type of "*/javascript" before it will attempt to json-decode responses from Facebook. This is incorrect, as Facebook reports the content type as application/json. This can be fixed by replacing instances of "javascript" with "json".

Further, the `getProfile` function is using file_get_contents, which does not generally work nicely with SSL (required to interact with Facebook). Interestingly, the generally accepted approach - using curl - is actually there in the function, but commented out. So, uncommenting it, and removing the file_get_contents call, resolves that issue.

Patch is attached.

[facebook.patch.txt](https://github.com/vanilla/vanilla/files/877347/facebook.patch.txt)

**Comment by DaazKu** [comment]
Already addressed: https://github.com/vanilla/vanilla/pull/5371/files#diff-fa8689b808080a1456afb013beefca68R486

Thank you for the report!

**Comment by derrickhand300** [comment]
Sorry for the simple question...Im new to vanillia and just installed last night-can you tell me where to upload thefacebook_patch.txt file to?

**Comment by x00** [comment]
you still use `file_get_contents`
