### ISSUE TITLE
User comment counter inconsistencies need an audit

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5391]
* Moving comments to the log doesn't appear to decrement User.CountComments.
* Maybe need a method to decrement User.CountComments?
* Maybe always recalculate (never increment) under 5? It's always an obsession to check this on a new forum and people lose their minds if it's off by 1.

Also check CountDiscussions for same.

**Comment by charrondev** [comment]
This should definitely be accompanied by some integration & unit tests once implemented.
