### ISSUE TITLE
Add unit tests for CORS support in API v2

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5392]
CORS support for API v2 was added with https://github.com/vanilla/vanilla/pull/5349, but now we need unit tests to verify present functionality and future compatibility.

Suggested tests:

* An instance of `Garden\Web\Data` with a `null` `data` property should return a status code of 204 by default.
* `Garden\Web\Data::getStatus` should return a code in the expected HTTP status code range. If a value was set out of that range, it should return a flat 500.
* `Garden\Web\PreflightRoute` should render any content.
* `Garden\Web\PreflightRoute` should only be triggered by an OPTIONS request.
* CORS headers should not be added to an instance of `Garden\Web\Data` if ...
  * ... no Origin header is sent.
  * ... the site host and the origin are the same.
* The Access-Control-Allow-Origin header should only be sent if an origin header is sent in the request and if the origin matches one of the allowed origins.
* The Access-Control-Allow-Methods header should only be sent if the Access-Control-Request-Method header was received.
* The Access-Control-Allow-Headers header should only be sent if the Access-Control-Request-Headers header is received.
* A single asterisk (*) is a valid origin. This value will allow all origins.
* If a scheme is specified in an allowed origin, the value from the Origin header must also match that scheme (e.g. an allowed origin with HTTPS as its scheme can only match against Origin headers that also have the HTTPS scheme).
* When setting allowed origins, you should be able to provide three different types of data: a single string, an array of strings or a callable value.
* If a callable value is used to determine if an Origin is allowed, the Access-Control-Allow-Origin header should not be sent unless that callable value returns `true` when passed the value of the Origin header.

**Comment by tburry** [comment]
CORS support can also be moved to a middleware which would make tests much easier to write.
