### ISSUE TITLE
Wrangle dependencies in core functions

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5393]
I want our functions files to be cleaned up so we know where stand alone functions are and where functions that use globals/statics are. Here is my proposed set of files:

- Let's move functions into the /library/functions directory.
- **core.php**: This is where the bulk of functions from functions.general.php. Only functions that don't depend on globals/statics go here. This file should be able to be included in any PHP script and every function should work.
- **framework.php**: These are the functions that depend on Vanilla being loaded and the container being configured. I have some ides for other stuff we can do here to make dependency inclusion in global functions easier, but for now I want existing functions moved here. Eventually we want this list to be very small.
- **compatibility.php**: These should include only functions that replicate global functions in newer versions of PHP that older versions don't have. We should be able to remove functions from this file as we up our minimum version requirement.
- **deprecated.php**: This file will include the same functions from our current functions.deprecated.php.
- **error.php**: The error handlers can just be copied for now.
- **validation.php**: Copy function.error.php.
- **render.php**: Copy functions.render.php.

This is just a moving around of functions with no change in functionality. Here are a few things to keep in mind:

1. Make sure the composer.json is properly updated.
2. Make sure to include files in the bootstrap in the same way.
3. Inf has a different bootstrap. Coodinate with them to schedule this update.

**Comment by tburry** [comment]
Pinging @kaecyra so he's aware of this change coming down the pipeline.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/7696
