### ISSUE TITLE
Formatting problems with mentions: add tokenization?

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5399]
We currently have a formatting problem with mentions.

Usernames containing valid "Formatting format" code are replaced.

For example, using markdown:
```
@"_k_" -> @"<em>k</em>"
```
Same for BBCode
```
@"[b]boldman[/b]" -> @"<b>boldman</b>"
```

Moving the parsing of mentions before the formatting doesn't solve the issue.
Do mentions -> format, using markdown:
```
@"_k_" -> <a rel="nofollow" href="/profile/_name_">@_name_</a> // This one is correct

// That one does a double anchor. They are side to side because htmLawed balances tags and anchors are not allowed inside another anchors.
@"[link](man)" -> <a rel="nofollow" href="/profile/%5Bname%5D%28lol%29">@</a><a rel="nofollow" href="lol">name</a> 
```

I think that the formatting pipeline needs a rework.
My suggestion would be:

- **Parse custom formatting like mentions and substitute them.**
- Do format transformation/formatting
- **Restore substitutions**
- format_filter
- Format links
- Emojis
- htmLawed

@linc told me that we want to redo the formatting pipeline. @tburry might have more information about how we are supposed to rework it.

**Comment by tburry** [comment]
I think it would be better to restrict allowable usernames. If necessary, something like the markdown editor can be made to not mangle mentions, but that's not an optimal solution.

I don't want to get into cases where other formatters have to know what they are operating on. They should always operate on HTML.

**Comment by DaazKu** [comment]
We cannot restrict usernames. We tried that already and we got a lot of problems doing it that way because of imports/SSO.

Usernames should be allowed to contain anything and be escaped properly!

**Comment by linc** [comment]
I'm in favor of tokenizing mentions to sidestep this issue forever. 

Every time we've tried to restrict usernames someone has twisted our arms into an exception, then we say "ok no mentions" and then one day that's bargain turns into a bug ticket instead.

While I'm in favor of all efforts to restrict usernames, I also like making this bulletproof once and for all so we stop this parade of issues.

**Comment by charrondev** [comment]
Non-security fixes will no longer be prioritized for advanced editor by the vanilla team. Rich Editor ships with Vanilla 2.8 as the default. https://github.com/vanilla/vanilla/pull/8302
