### ISSUE TITLE
Start filling in /api/v2/categories endpoints.

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5409]
There are two endpoints I'm looking for right now:

### GET /categories

Get the category tree structure. Even though this is the main index endpoint do this one second.

#### Parameters

- parentCategoryID?
- parentCategoryCode?
- maxDepth? Default 2
- page? If the parent category is display as flat then paging is allowed

#### Response (array)

- categoryID
- name
- description
- urlCode
- url
- countDisccussions
- countComments
- countAllDisccussions
- countAllComments
- level: The current level, starting at 1. So if I get a deeply
- children?: This will be an array of categories with the same structure

### GET /categories/search

Search for a categories.

#### Parameters

- query. The text query for the category name. Just do a like search where name like "query%".
- page?
- expand? Default false.

#### Response (array)

The response is always a flat array of categories with no tree structure.

- categoryID
- name
- description
- urlCode
- url
- countDisccussions
- countComments
- countAllDisccussions
- countAllComments
- parentCategoryID. If the parent is root (-1) make this null.
- parent? If expand is true
    - categoryID
    - name
    - urlCode
    - url

**Comment by initvector** [comment]
These updates have been rolled into https://github.com/vanilla/vanilla/pull/5341

**Comment by initvector** [comment]
Closing in favor of tracking the issue on the PR
