### ISSUE TITLE
Optimize category management sorting

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5415]
When sorting categories, the full current tree is currently set for a page to be processed. For larger sites with hundreds of categories, this can add a lot of overhead and possibly cause significant delay in the request being processed.

It might be more beneficial if we only sent the relevant information to the server (e.g. Category X has been moved under Category Y, under category Z).

It may also be worth pursuing a lockout of sorts, where categories cannot be re-ordered while there is a pending sort request in the browser.

**Comment by linc** [comment]
backport: `release/2017-Q1-6`

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: https://github.com/vanilla/vanilla/pull/5730
