### ISSUE TITLE
Safari now auto-links in WYSIWYG mode, breaking our embeds

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5433]
Pasting a text URL into the WYSIWYG formatter in Safari creates an HTML link "magically", thereby breaking our auto-embed detection. This appears to be a new feature in the browser.

**Comment by DaazKu** [comment]
This is the default behaviour of the browser. I do not think we should do an hack around it.

If you really want to paste the link without it being an anchor you need to use the "Paste and Match Style" functionality.

<img width="258" alt="screen shot 2017-05-12 at 11 47 48 am" src="https://cloud.githubusercontent.com/assets/2412909/26006036/03a590e8-3709-11e7-9742-c153b3fec3f6.png">

Personally I would suggest using a real browser like Chrome or Firefox.
![](https://medlineplus.gov/ency/images/ency/fullsize/19598.jpg)

**Comment by DaazKu** [comment]
The copied URL has a clear feedback that is it an anchor.
The editor tells you that it is (the anchor icon is selected) and the text is blue.

<img width="939" alt="screen shot 2017-05-12 at 12 10 57 pm" src="https://cloud.githubusercontent.com/assets/2412909/26006874/239af85e-370c-11e7-80c7-49fda7271453.png">

You can see the comparison.

<img width="950" alt="screen shot 2017-05-12 at 12 11 14 pm" src="https://cloud.githubusercontent.com/assets/2412909/26006916/4c351c72-370c-11e7-9c60-b05c12eb5bef.png">

**We had a suggestion about treating anchors having `href == trim(content)` as plain text for embedding purpose.**
I'm not sure I like the idea but we should at least discuss that as a possibility.

**Comment by DaazKu** [comment]
I'm closing this since we won't fix the way safari does its copy pasting.
