### ISSUE TITLE
DiscussionModel::categoryPermissions() causes a heavy cascade of querying

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5436]
When I call DiscussionModel::categoryPermissions() then CategoryModel::categories() gets called which joins users and recent posts. This is too heavy and causes some Sql pollution issues. This method needs to really be lightened up.

**Comment by R-J** [comment]
I have taken a look at that and thought about the following:

the vanilla app settings could add a method to the UserModel `getCategoryPermissions(UserID)`. There is exactly the same one in the RoleModel, but as far as I can tell it only echoes the categories with special permisions (which isn't useful here).

So it might look like that
~~~
public function getCategoryPermissions($userID) {
        $firstRole = $this->getRoles($userID)->firstRow();

        return array_column(
            Gdn::sql()
                ->select('c.CategoryID')
                ->from('Category c')
                ->from('Permission p')
                ->where('c.PermissionCategoryID', 'p.JunctionID', true, false)
                ->where('p.JunctionColumn', 'PermissionCategoryID')
                ->where('p.JunctionTable', 'Category')
                ->where('p.RoleID', $firstRole['RoleID'])
                ->where('p.`Vanilla.Discussions.View`', 1)
                ->orderBy('c.Sort')
                ->get()
                ->resultArray()
            ,
            'CategoryID'
        );
}
~~~

Afterwards the DiscussionModel could be changed to use that method.

But there are a lot of things I'm not sure about. One thing I have made [an issue](https://github.com/vanilla/vanilla/issues/5465).
