### ISSUE TITLE
Aspect ratio data needed in markup to make embedded content responsive

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#5447]
There's a trick to get embedded videos responsive, but it requires knowing the aspect ratio. The iframe has no natural height.

There's an internal function that transforms embedded videos into custom markup and then adds an iframe if someone clicks on the link. For compatibility with older themes, I would leave the markup the same, but I would like to see a class or data attribute added for 16:9 or 4:3 ratios on videos. Maybe a config option to opt out of hard coded video size would be nice, with a default to 16:9. Everybody wants responsive videos nowadays.

**Comment by charrondev** [comment]
Fixed with Rich Editor and the new embed system.
