### ISSUE TITLE
Synchronizing my vanilla fork repository does not work

### ISSUE THREAD

**Issue by AlexL777** [vanilla/vanilla#5449]
Hello Developers,

I would gladly balance my Fork Repository with the Original Branch 2.4, but unfortunately does not work in the console.

I'm going this way.

cd vanilla

git fetch upstream

git checkout release/2.4

git merge upstream/release/2.4

git push

After that I have no permissions to access your repo.

git remote -v shows me in the console that.

    git remote -v
    origin  https://github.com/AlexL777/vanilla.git (fetch)
    origin  https://github.com/AlexL777/vanilla.git (push)
    upstream        https://github.com/vanilla/vanilla.git (fetch)
    upstream        https://github.com/vanilla/vanilla.git (push)
    
How can I solve the problem?

Thanks in advance.

**Comment by linc** [comment]
Please use the forum for help with git issues. https://open.vanillaforums.com/discussions
