### ISSUE TITLE
Facebook: scope publish_actions should be optional

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5458]
This issue is based on that comment: https://open.vanillaforums.com/discussion/comment/247079/#Comment_247079

I don't use the Facebook plugin, so the description might not be correct, but as far as I understand it, that line causes some troubles:
`$FBScope = c('Plugins.Facebook.Scope', 'email,publish_actions');`

The publish_actions scope needs a review  of Facebook: https://developers.facebook.com/docs/facebook-login/permissions/#reference-publish_actions
This has two problems:
a) This isn't described anywhere (maybe a short link to the page above would be enough?)
b) That scope is only used if the user ticks "Enable Social Reactions.", correct? If yes, it should only be used if needed.

Maybe using publish_pages is an alternative, as stated in the comment:  https://developers.facebook.com/docs/facebook-login/permissions/#reference-publish_pages

Like I have said: most of this issue are assumptions, but if any of you has experience with the Facebook API, you might be able to judge that quickly from looking at the links! :+1:

**Comment by adrianspeyer** [comment]
Explore use of https://developers.facebook.com/docs/sharing/reference/share-dialog, which seems to work without submitting the app to use publish_actions.
