### ISSUE TITLE
Strange permission behavior

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5465]
I have a user who has member and moderator roles. But I would say that for permissions only the member role is taken into consideration. I've tested the following for the Debugger plugin following permissions:
1. Moderator and member has no view access => test user sees no debug output
2. Moderator view permission, member view permission => test user sees debug output
3. Moderator view permission, member has no view access => test user sees no debug output
4. Moderator has no view permissions, but member has view access => test user sees debug output

While 1 and 2 are certainly no surprise, it looks as if the second role has no meaning at all.

I've tested the same with category view permissions and the results are the same. I've created a "member only" category where I've excluded moderators and a "mods only" category where memebers have no access.

Users with member role only: sees member roles categories only
Users with moderator role only: sees mods roles categories only
Users with member & moderator role combined: sees member roles categories only (including the category moderators have no access to)

Based on that it appears that mixing roles is not possible or at least follows rule which are not transparent. I found nothing about that in [the docs](http://docs.vanillaforums.com/help/roles-permissions/). Is this expected behavior and simply undocumented?

(Vanilla 2.4 beta)

**Comment by linc** [comment]
I suggest providing better clarity when filing issues by summarizing the problem succinctly in the title. "Strange behavior" isn't a bug, it's an idea, and you jump into examples without summarizing what that means. That makes it far less likely for developers to pay attention to it. Spending time writing a great title is the most important part of filing issues.

**Comment by linc** [comment]
We've removed the Debugger plugin this past year, so I don't even have access to the referenced example any more. 

Permissions should be a "union" - the _greatest_ of all permissions granted by roles you have is the permission set you have. Any deviation from that should be reported.
