### ISSUE TITLE
Does the Redirector addon absolve us of needing those old .php redirects in root?

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5475]
These files are all redirects for ease of upgrading from legacy platforms:

- register.php
- showpost.php
- viewtopic.php
- showthread.php
- login.php

Can these be safely removed now that we have the Redirector plugin?

**Comment by DaazKu** [comment]
They actually conflict with the plugin in some cases! We do not used them on infra.

I have this in my nginx config:

```
    # Skip these %$@#
    location ~* "(login|register|showpost|showthread|viewtopic)\.php" {
        set $x_rewrite 1;
        rewrite ^ /_index.php$uri last;
    }
```

**Comment by DaazKu** [comment]
So I guess the answer would be yes we could ditch them.

**Comment by DaazKu** [comment]
Source: https://github.com/vanilla/addons/tree/master/plugins/Redirector
Ready to use: https://open.vanillaforums.com/addon/redirector-plugin
