### ISSUE TITLE
BBCode editor alignment broken

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5483]
Steps to reproduce:

* Enabled Advanced Editor plugin.
* Set editor type to BBCode
* Try to make a post with [left] [center] [right] tags.
* Observe

This seems to have been introduced with 5e31b076d.

**Comment by DaazKu** [comment]
```bbcode
[right]Right[/right]
[center]Middle[/center]
[center]Left[/center]
```

gets transformed to

```html
<div class="bbcode_right" style="text-align:right">
Right
</div>

<div class="bbcode_center" style="text-align:center">
Middle
</div>

<div class="bbcode_center" style="text-align:center">
Left
</div>
```

and then `Gdn_Format::htmlFilter()` filters it to

```html
<div>
Right
</div>

<div>
Middle
</div>

<div>
Left
</div>
```

**Comment by DaazKu** [comment]
Filtering last is causing problem for BBCode

**Comment by linc** [comment]
Sounds like either BBCode needs to enable a filtering exception, or we need to just globally allow that formatting.

**Comment by DaazKu** [comment]
"style" should be removed. The classes should probably be allowed.
