### ISSUE TITLE
SplitMerge: Add discussion option to merge

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5501]
When you wish to merge two discussions not on the same page, it's currently quite difficult. You need to find them both in a discussions list view, which can be non-trivial for older discussions. Adding the [necessary checkbox to search options](https://github.com/vanilla/vanilla/issues/5335) isn't a good solution, so we need a way to select "Merge" from one discussion view then locate the second discussion.

My proposal is a modal dialog that either auto-completes discussion titles or allows a discussions-only simple search and the selection of the second discussion. Worst case scenario, pasting a DiscussionID (from the URL of the second discussion) would suffice, but that's a really poor UX solution. The modal solution requires more planning, however, due to both design and scaling considerations.

**Comment by adrianspeyer** [comment]
I like the modal idea of the "auto-completes discussion titles".
Not to muddy the waters, but if I could comment on how I'd love to see this idea expanded (although it may cause more work). I think it could also be handy for when people are creating new discussions to suggest a topic that may have already been created. This could potentially stop a duplicate discussion from being created. Anyway I know the work involved in it, but I figure if you are going to spend the time in design and scale, why not expand it a bit more.

**Comment by linc** [comment]
Related content is definitely way beyond the scope of this issue.

**Comment by adrianspeyer** [comment]
I meant for the modal code, might be reusable in some way. Not suggesting it be built with this pull. Sorry if that was unclear.

**Comment by tburry** [comment]
I'm wondering why this kind of issue is scheduled for so soon? We have many higher priorities. I'd rather not have feature added that usurp the R&D roadmap.

**Comment by vrjrobitaille** [comment]
OnShape has just pinged be about this issue again. Is there any hope of this being sprinted in the near future?
