### ISSUE TITLE
Unit tests for text formatting pipelines

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5507]
Develop a basic set of unit tests for:

* Markdown
* BBCode
* HTML
* WYSIWYG
* TextEx
* Text

That cover:

* Span styles: Bold / italics / strike
* Block styles: Headings, lists, quotes, spoilers
* Code blocks (with many sub-tests here)
* Magic parsing: Emoji, Links, Embeds, Mentions
* `/me` parsing
* Magic parsing within `<code>` tags.

**Comment by tburry** [comment]
@linc I'd like to see /me actions to be removed. They are not often used and would cause no end of support issues if customers knew about them.

**Comment by tburry** [comment]
@linc and I thought this would be a good thing for @dannimajdalani to try out since unit testing would be a great competency for support.

We aren't sure if you know about unit testing or how we do it, so we can go through that too.

**Comment by charrondev** [comment]
https://github.com/vanilla/vanilla/pull/8205 added integration tests covering everything here.

To track additional unit tests as the formatting pipeline is refactored track on 

https://github.com/vanilla/vanilla/issues/8204
