### ISSUE TITLE
HTML Posts no longer render after upgrading to 2.3

### ISSUE THREAD

**Issue by Gillingham** [vanilla/vanilla#5509]
Starting all the way back at Vanilla classic my forums have been using HTML tags in posts for image embeds, links etc, using the buttonbar or just manually entering the HTML into posts.

Upon upgrading to 2.3 none of those posts are rendered as HTML, the HTML tags are just escaped and rendered as text.

`$Configuration['Garden']['InputFormatter'] = 'Html';` is set, no configuration was changed by me in the upgrade process.

This is a pretty huge breaking change.

**Comment by x00** [comment]
have you removed htmLawed plugin?

**Comment by Gillingham** [comment]
@x00 Interestingly no, the HtmLawed folder still exists under the plugins folder, but does not show up in the Manage Plugins view.
When upgrading I simply copy the newer version of vanilla over the old version in place, so it wouldn't have gotten removed.

**Comment by DaazKu** [comment]
It needs to be loaded too.

config.php
```php
$Configuration['EnabledPlugins']['HtmLawed'] = 'HtmLawed';
```

**Comment by Gillingham** [comment]
Shouldn't it be showing up in the plugins view to do that through the interface?

**Comment by DaazKu** [comment]
No. This is a special plugin. It will be merged into Vanilla's core to prevent that kind of problems.

**Comment by Gillingham** [comment]
Ok thanks, any timeline for when it will get merged or can I just keep an eye for when this issue gets closed?

**Comment by DaazKu** [comment]
If you have the above line in your `conf/config.php` everything should work fine.
Otherwise your problem is probably not with HtmLawed.

**Comment by Gillingham** [comment]
Yes adding that resolves the problem, but I still want to track when this gets merged into baseline so I dont need to worry about an invisible plugin breaking later installs or restores from backups etc.

**Comment by DaazKu** [comment]
https://github.com/vanilla/vanilla/issues/5547
