### ISSUE TITLE
API v2 endpoints need to propagate validation errors

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5526]
Even though we use the schema, validation errors still may occur in the models. Usually, this will be because the API is calling the model in a way it hasn't been called before, but could also represent custom validation that the schema missed. If that happens we should make sure the endpoint throws an exception.

What I'd do is make a utility method that can be called on a model that will inspect the validation object and convert anything that failed into a ValidationException and optionally throw it.

**Comment by initvector** [comment]
See https://github.com/vanilla/vanilla/commit/96d3a49cb08399c336235d33560d7ac153f34300
