### ISSUE TITLE
Add registration to UsersApiController

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5528]
### Proposed Solution

1. `public function post_registrationApply(array $body): array`
    * Will require the following fields: Name, Password, Email and DiscoveryText.
    * Use `UserModel::insertForApproval` to save registration.
1. `public function post_registrationBasic(array $body): array`
    * Will require the following fields: Name, Password and Email.
    * Use `UserModel::insertForBasic` to save registration.
1. `public function post_registrationInvitation(array $body): array`
    * Will require the following fields: Name, Password, Email and InvitationCode.
    * Use `UserModel::insertForInvitation` to save registration.

### Notes

1. Only the configured registration method's associated endpoint is active. If registration is set to "basic", then a POST to /api/v2/users/registrationApply is going to respond with an error.
1. Should acceptance of the TOS be a field that gets submitted?
1. CAPTCHA addons may need to be refactored to work with API requests.
1. `UserModel::register` currently only allows the configured registration method for the site. Since we're disabling endpoints that aren't configured, anyway, this probably isn't a big deal. However, adding the flexibility of passing a method override parameter to the function would be easy way to get around this limitation.
1. Extended fields (e.g. Profile Extender) are not supported and will be added in a future revision.
1. Required CAPTCHA values will need to be generated on the client, using the site's CAPTCHA config (e.g. reCAPTCHA keys). The client will be responsible for inserting the script to generate the widget and passing along the user-supplied answer with the rest of the request.

**Comment by tburry** [comment]
Hmm, I what do you think of the following:

### Applicants

```
POST /users/applicants // apply
GET /users/applicants // list applicatns
PATCH /users/applicants/id // approve/deny an applicant
```

### Basic registration

```
POST /users/register
```

### Invitations

Invitations can maybe use /invitations as a resource to manage actual invitations since an invitation is not a user. If this is odd we can also go against the /users/invitations endpoint to be similar to applicants.

```
POST /users/register-invite // claim an invitation and register
````

**Comment by initvector** [comment]
Applicants and basic registration make good sense. An invitation registration is almost identical to a basic registration, with the exception of requiring an invitation code. I like the idea of using /users/register for basic *and* invitations and having the invite code only required when the site's registration mode is invitation. However, having a sometimes-required field may not be intuitive or easy to document.

> Invitations can maybe use /invitations as a resource to manage actual invitations since an invitation is not a user. If this is odd we can also go against the /users/invitations endpoint to be similar to applicants.

I would say invitations are a separate resource in their own separate table, so they should be managed as a separate resource (e.g. /api/v2/invitations).

**Comment by tburry** [comment]
I think conditionally adding an invite code to basic registration is good.

**Comment by tburry** [comment]
I also wonder if the API should use invites/applicants vs invitations/applications. The former seems to indicate users while the latter could be event invitations or job applications.

Also, maybe if invites are a separate resource then applicants should look like a separate resource too WRT to the API. I can say that having applicants in a separate table would have made the back end a lot nicer.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5975
