### ISSUE TITLE
Add "pinned" support to /discussions endpoint index

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5534]
We'll need to add support for adding pinned discussions (announcements) to their proper position when pulling posts from the /discussions endpoint index.

Vanilla will be moving towards using "pin"/"pinned" instead of "announce"/"announced". These endpoint additions will implement the updated nomenclature.

1. `DiscussionApiController`
    1. Add a "pinned" option to the endpoint. This should be an optional boolean field.
    1. Add a "pinOrder" option to the endpoint. This should be an enum field, consisting of two options: "mixed" and "first".
    1. If the "pinned" parameter is `false`, do not include discussions with a truthy Announce field.
    1. If the "pinned" parameter is `true`, include ONLY discussions with a truthy Announce field.
    1. If the "pinned" parameter is `null` and "pinOrder" is "mixed", include discussions with a truthy Announce field in their natural sort order.
    1. If the "pinned" parameter is `null` and "pinOrder" is "first", include discussions with a truthy Announce field at the top of the first page of results.
1. `DiscussionModel`
    1. Update `DiscussionModel::calculate` to add a "Pinned" field, based on the value of "Announce". It will be cast to a boolean.
    1. Add a pinLocation enum that can either be "category" or "discussions". Announce of 1 means "discusisons" and announce of 2 means "category".

**Comment by tburry** [comment]
Just to clarify here. The current Announce will actually look like two fields:

1. A boolean of whether the discussion is pinned or not.
2. An enum field saying whether the discussion is pinned to just the category or to recent discussion lists too. We had discussed "global" as an option, but I'm worried that we may want an option that actually is global at some point.

The pinned filter field will be true, false, or not specified. Not specified means everything while true or false filters so this works more like any other filter.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5917
