### ISSUE TITLE
Add the DraftsApiController

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5535]
### Proposed Solution

1. Draft records returned by this endpoint should include the following fields:
    * `draftID`
    * `recordType` (e.g. "discussion", "comment")
    * `name` (e.g. the discussion title or `null` for a comment)
    * `body`
    * `insertUserID`
    * `dateInserted`
    * `updateUserID`
    * `dateUpdated`
    * `attributes` - This is where most of the current comment- and discussion-specific fields will go. This includes: `CategoryID`, `DiscussionID`, `Closed`, `Announce`, `Sink` and `Format`. Ideally, this will allow us to move to a more generic table format in the future. Simulating it now will make the transition easier, later.
1. `public function index($query): array`
    * Query the `Drafts` table, selecting open drafts for the current user, ordering by `DateInserted`, descending.
    * Allow filtering by `recordType`. Right now, "discussion" is a draft with no valid `DiscussionID` (null or less than 1) and "comment" is a draft with a discussion ID.
    * Paginate results.
1. `public function get($id): array`
    * Get a single draft by its unique ID in the format specified above.
1. `public function post(array $body): array`
    * Use the following fields to create a new draft:
        * `recordType` - enum - Currently, this is just "comment" and "discussion".
        * `name` - string - optional
        * `body` - string
        * `attributes` - object - All the resource-specific fields that may be needed for this draft.
1. `public function patch($id, array $body): array`
    * Edit an existing draft.
    * Parameters same as POST.
1. `public function delete($id): null`
    * Given a draft's unique ID, delete it.

### Notes

Querying a comment draft for a particular discussion isn't very easy with this interface. As it stands, I would need to query `recordType=comment` and then look through the attributes of all the records until I found (or didn't find) a `DiscussionID` value to match for a particular discussion. It might be worth adding `ForeignType` and `ForeignID` fields to proposed structure, so we could "attach" a draft to an existing record, potentially of a different type. I could then fetch a comment draft for discussion \#123 by querying `recordType=comment&foreignType=discussion&foreignID=123`.

**Comment by tburry** [comment]
Okay I unfortunately have some monkey wrenches to throw into this.

1. We are going to have the need to do something like "get the comment drafts for discussion xxx". For this I propose adding a parentRecordID field that can be queried. This way I can do recordType=comment&parentRecordID=<discussionID>.

2. This one is a bit more tricky, given our universal record format. I think drafts are going to be more useful if the UI is able to give an array of whatever and then get that back so that the UI state can be loaded/saved by anything. In this way the drafts API would truly be able be usable by any record.

    1. We could add an "attributes" column to the endpoint. This would load/save anything given to the draft. The following fields would be attributes: discussionID, categoryID, name, body, format, tags, closed, announce, sink. We would eventually refactor the actual drafts table to match this.
    2. We could duplicate the standard name, body, format columns into the main content to keep the draft compatible with the universal record type.
    3. We could keep the drafts compatible with the universal record type and have no attributes column.

I'm leaning towards abstracting the drafts to the "attributes" column as it will prevent clashes from happening between fields that a model may require and fields that GDN_Draft requires. This style of record format also works for tables like GDN_Log. Perhaps we have a necessary universal nested meta record and a universal record for union style data. I'm okay with that and converters can be made.

**Comment by tburry** [comment]
Also to note that I think once a relaxed solution is made and the GDN_Draft table is refactored then the recordType can be a string with no enum.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6018
