### ISSUE TITLE
Come up with a unified record format for endpoints that combine different records.

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5537]
Some endpoints return multiple types of records and we should make sure that API clients can look at them without too much processing. Here are my thoughts:

### Row Identification

The row needs to identify the type of record in it. For this we need the following fields:

- recordType
- recordID

### Common Fields

Common fields that tables already have are left alone.

- name
- body, format
- insertUserID, dateInserted, insertIPAddress
- updateUserID, dateUpdated, updateIPAddress

### Other Fields

Each record should leave its own fields in the row so that the client can do something with that row. The fields for each row should be the same as those offered by their own GET endpoints. This means the primary key will be returned twice.

I suspect for this to work well there should be an interface that the various API controllers can implement to fetch their records and join them into a dataset with just recordType and recordID.

**Comment by linc** [comment]
@initvector Believe this is where some of our meeting notes should go.

**Comment by initvector** [comment]
The original issue outlined the desired format, pretty well, already. Here, I am attempting to be more explicit and succinct in what's already been stated, in addition to making a couple minor suggestions for improvement.

### Proposed Solution

1. API endpoints returning datasets (multidimensional arrays) containing different types of resources (e.g. search) will need to include two additional fields:
    1. `recordType`: The type of resource (e.g. discussion).
    1. `recordID`: The unique ID of the resource row.
1. "Common" fields (e.g. name, body, format, insertUserID, dateInserted, insertIPAddress, updateUserID, dateUpdated, updateIPAddress) should be used as much as possible.
3. If a resource has a field that is analogous to a common field (e.g. "Text" and "Body"), it should populate that field with its value. This would be done so the data is easily consumed.
1. No further modification of the rows is necessary. Various fields, unique to each resource type, remain in the row as part of the full dataset.
1. Add an interface with a method for expanding a dataset of rows with only `recordType` and `recordID`.
    1. This interface method will be implemented by resource API controllers.
    1. It will take the barebones dataset and expand rows matching their resource type.
    1. The expanded fields will be limited to those returned by a default GET/id request to the endpoint.

**Comment by tburry** [comment]
This looks good. I added "attributes" as another list of fields. I think this would be a good page in our [writing APIs documentation](http://docs.vanillaforums.com/developer/framework/apiv2/resource-routing/) as a separate page. This would have to change from a numbered list to a doc page and I would add the definitive list of fields into a proper list under its own heading for easy scanning.

**Comment by initvector** [comment]
An issue for the docs page has been added: [vanilla/docs#111](https://github.com/vanilla/docs/issues/111)

An implementation will be added as part of #5535
