### ISSUE TITLE
API v2 Permissions

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5539]
Permissions are due for an overhaul in Vanilla and a good starting point is implementing the desired changes with the API.  Here's an overview of the proposed changes:

### Overview

1. A standard naming convention is needed. Right now, permissions are three levels deep and there isn't much in the way of standardization. The proposed format is: [resource].[action] (e.g. discussions.add). Addon names should not be included in the permission.
1. Permission names should be camel-case. There aren't a lot of two-word permission segments, but where there are, they need to be properly cased (e.g. resources.longAction).
1. The pluralized version of a resource should be used in the permission (e.g. "discussions", not "discussion")
1. The goal will be to try to match up permission actions with HTTP verbs, as closely as possible. If a POST is required, the permission would use the "add" action (e.g. discussions.add).
    * CRUD verbs
        * view: GET
        * add: POST
        * edit: PATCH
        * delete: DELETE
    * Standard combined verbs. These verbs can encompass multiple operations.
        * allow: Regular member operations
        * moderate: Moderator operations
        * manage: Administrator operations
    * If an action doesn't fit with a standard verb then creating a verb for a permission is fine, but should be done with caution.
1. Default category permissions should be represented by 0, not -1, as they are in the database.
1. **The initial version of the permission renaming will apply to the API and permission administration only.** The controllers will still request their permissions using the old permission names at this time. If/when we update all permissions then calls to the permissions should be backwards compatible which will require some optimization work seperate from this process.

### Format

The structure of permissions data used with the API should adhere to a standard format. The current proposed format is:

```json
{
  "permissions": {
    "global": {
      "reactions.negative.add": false,
      "discussions.add": false,
      "comments.add": true
  },
  "categories": [
    {
      "id": 123,
      "permissions": {
        "discussions.add": true,
        "comments.add": true
      }
    }
  ]
}
```

Global permissions go under the "global" key. Resource-specific permissions go under a key with the name of the resource.

### Deprecated Permissions

Some current permissions will be deprecated or at least changed enough to not be included in the API at this time. The API should not allow these permissions to be set, nor should it return them in any responses. In essence, deprecated permissions are invisible to the API.

The current list of proposed deprecated permissions:

- Garden.Activity.Delete
- Garden.Activity.View
- Garden.SignIn.Allow
- Garden.Curation.Manage
- Vanilla.Approval.Require
- Vanilla.Comments.Me

### Updated Permission Names

To better adhere to the new resource.action format, some permissions will need to be renamed. The following are the current list of proposed updated names:

| Old Permission | New Permission |
| -------------- | -------------- |
| Conversations.Moderations.Manage | conversations.moderate |
| Email.Comments.Add | comments.email |
| Email.Conversations.Add | conversations.email |
| Email.Discussions.Add | discussions.email |
| Garden.Moderation.Manage | community.moderate |
| Garden.NoAds.Allow | noAds.view |
| Garden.Users.Approve | applicants.manage |
| Garden.Settings.Manage | site.manage |
| Groups.Group.Add | groups.add |
| Groups.Moderation.Manage | groups.moderate |
| Reputation.Badges.Give | badges.moderate |
| Vanilla.Tagging.Add | tags.add |

Other permissions will naturally be renamed when the naming convention rules are applied, such as Garden.Community.Manage becoming community.manage and Garden.Staff.Allow becoming staff.allow.

### Consolidating Permissions

In an attempt to simplify permission management, some existing permission names will be consolidated under a single new permission. When setting this permission via the API, all the permissions underneath it should also be affected. The current proposed list of these consolidated permission groups:

| Consolidated Permission | Current Permissions Included |
| ----------------------- | ---------------------------- |
| discussions.moderate    | discussions.announce, discussions.close, discussions.sink |
| discussions.manage      | discussions.delete, discussions.edit |

For example, if a user grants discussions.moderate on a role, the role would then have the discussions.announce, discussions.close and discussions.sink permissions. The opposite would be true if discussions.moderate were revoked for a role. In a response, if the role had none of these permissions, the value for discussions.moderate would be `false`. If the role had some, but not all, the value would be `null`. If the role had all three, the value would be `true`.

### Converting Permissions

The permissions can be converted using the following method to map old permission names to old permission names and vice-versa.

1. Load all permissions from the database. The global permissions and per-category permissions should be differentiated in order to build the final permission structure.
1. Remove deprecated permission names.
1. The permissions that need to be updated should be updated using the full names.
1. Alter permission names to fit the established convention (drop the application, fix the casing). This should exclude the permissions that were specifically updated in the previous step.
1. Add the consolidated permission names, calculate the consolidations and remove the individual permissions.

**Comment by DaazKu** [comment]
Sounds great to me.

Shouldn't `Garden.NoAds.Allow` be `noAds.allow`?
The permissions if allowing users to have to ads.

**Comment by linc** [comment]
Alex mentioned using `use` instead of `allow` when I spoke with him earlier. After reading this spec, I agree it would be clearer. Our verbs are all in the form "This user may [view|edit|delete|manage|moderate] this resource." The verb `allow` doesn't fit into this formula, making it a bit of a non-parallel usage. I also think `use -> User` is an almost duh-level way of lining that up with moderate & manage.

One more pedantic note that builds on this + Alex's comment above: Perhaps `adFree.use`?
