### ISSUE TITLE
Roll the HtmLawed plugin into core

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5547]
I think it's time we remove the HtmLawed plugin and just put its functionality into core. This will prevent the plugin from being removed which causes serious unexpected behavior.

This mirrors what we did with BBCode and Markdown and is immensely sensible.

**Comment by x00** [comment]
+1

**Comment by tburry** [comment]
Does that count as a +2 @x00?

**Comment by x00** [comment]
Sure old skool :p
