### ISSUE TITLE
Double newline in text emails due to html changes and inflexible locale/concatenation/hard coded html

### ISSUE THREAD

**Issue by x00** [vanilla/vanilla#5554]
text emails are converting each newline to two newlines, causing massive gaps in text email

the move to html as has resulted in awkward hard coded formatting an locale stuff like

```php
        $Email->to($User->Email);
        $emailTemplate = $Email->getEmailTemplate();

        $Data = array();
        $Data['User'] = arrayTranslate((array)$User, array('UserID', 'Name', 'Email'));
        $Data['Sender'] = arrayTranslate((array)$Sender, array('Name', 'Email'));
        $Data['Title'] = $AppTitle;
        if (is_array($AdditionalData)) {
            $Data = array_merge($Data, $AdditionalData);
        }

        $Data['EmailKey'] = valr('Attributes.EmailKey', $User);

        $message = '<p>'.formatString(t('Hello {User.Name}!'), $Data).' ';

        $message .= $this->getEmailWelcome($RegisterType, $User, $Data, $Password);
```
concatenation of template of the  hard code paragraphs tag, etc. 

it makes it  difficult to format the welcome email and text email in general.

**Comment by x00** [comment]
example of the problem

```
XXXX http://xxxx.com/



Welcome Aboard!



Hello 0_equals! You have successfully registered for an account at TownFish. Here is your information:



          Username: xxx

          Email: xxx@xxx



You can access the site at http://xxxx.com/.You need to confirm your email address before you can continue.



Confirm My Email Address: http://xxx.com/entry/emailconfirm/xxx
```

you can see the newlines but also due to the formatting its is difficult of get rid of the 'Welcome Aboard!' and the repeating of the subject. 

It is not a question of a simple email template. 

You have story payload and the template split up into different parts, not ideal.

**Comment by x00** [comment]
the concatenation is the worst part IMO. I can understand why it being done for the html emails what with the buttons, etc. However it would have been better in both cases if there was simply a template which each of these elements were inserted into.

I wouldn't have minded if it was templates inserted into template becuase at least there they would have been a way to format things.

**Comment by x00** [comment]
the newline issue may be platform specific if that has not already been fixed.

**Comment by x00** [comment]
look like that issue has been fixed for a year but didn't make it into 2.3

https://github.com/vanilla/vanilla/blob/Vanilla_2.4b1/applications/dashboard/library/class.emailtemplate.php#L171-L176

**Comment by x00** [comment]
here it is

https://github.com/vanilla/vanilla/commit/c751ae53720efe4f6ccaabad29248fa8597e8d89

**Comment by x00** [comment]
work around is simply to patch the line.

**Comment by x00** [comment]
these locales are not longer used and that is a shame somethign equivalent would make things clearer. 

```php
$Definition['EmailNotification'] = '%1$s

Follow the link below to check it out:
%2$s

Have a great day!';
$Definition['EmailStoryNotification'] = '%1$s

%3$s

---
Follow the link below to check it out:
%2$s

Have a great day!';
```

**Comment by x00** [comment]
`Site Name http://sitename.com`

at the top of emails including open.vanillaforum.com's is kind of annoying and unnecessary, and a good example of how this html stripping to plain text can be an issue.

**Comment by x00** [comment]
I believe using a plain text locale/tpl in `plainTextEmail` is part of the solution.  

Obviously this class could be overridden too, but it makes more sense than just imploding all those values and convoluted formatting.

**Comment by linc** [comment]
This was updated naturally as part of the move to 2.5.
