### ISSUE TITLE
change "repeat" section in Pockets settings

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#5558]
Currently "repeat" and "given indexes" are confusing language in pockets. To actually set it to repeat, you have to select "repeat every", otherwise you are just picking the location (as far as I can tell). I dont believe repeat works for the header or footer, either. 

I've been trying to think of a more appropriate term. It seems like everything that falls under "repeat" are actually just secondary settings for each location. Perhaps when you select a drop down only the relevant options to that particular location should appear below?

**Comment by Charrondev** [comment]
This issue is in the wrong repo. Pockets live in `vanilla/addons`
Moved here: https://github.com/vanilla/addons/issues/525
