### ISSUE TITLE
Discuss/spec an /entry/connect replacement

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5563]
`/entry/connect` is a big bowl of spaghetti.

We need to redo it.

- Spec the current `/entry/connect` functionalities.
- Have a meeting with @tburry about what he has planned for the next version.
- Spec the new version.
- The new version has to be unit testable.

.. more info after the meeting!

**Comment by tburry** [comment]
Just a note that this will be a replacement for future addons. The current `/entry/connect` will remain legacy for quite some time.

**Comment by DaazKu** [comment]
# /autentication spec

This will replace `/entry/connect` in a distant future.
For the first iteration we will only implement everything that is needed for SSO authentication.

- We will need to make sure that there is no loss of functionality compared to `/entry/connect`.
This implies that we will need to test and analyses the old endpoint to find out how the different configurations interact with SSO. (configs: autoConnect, noemail, emailunique, nameunique.. registrationMethod: approval, invitation...)
- All this will need to be build over APIv2

`/authentication/{SSOAutenticator}`
- Lookup for a connection in user authentication table
OR
- Create a connection
  - To an existing user
  - To a new user

Notes:
- On registration:
  - The profile extender needs to be accounted for
  - Invitation codes

# Draft design

AuthencitationAPIController
1. replaces /entry/connect
1. thin wrapper

Authenticator
- signInURL()
- signOutURL()
- sso(RequestInterface $request) : UserInfo
1. Authenticator subclasses

UserInfo
1. Pure data object that we will pass around

SsoModel
- sso($providerKey, RequestInterface $data)
- ssoFromUser($userInfo) 
1. inject the DIC to instanciate authenticators)
