### ISSUE TITLE
'Dismiss' announcement animation hides the OP

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5572]
Currently, 'Dismiss' triggers a rollup animation on the discussion being dismissed, even in the single discussion view, thus hiding it.

I don't think any change at all should be triggered. No animation, no refresh - just nice and steady as you go.

**Comment by charrondev** [comment]
Acceptance Criteria from my POV would be as #7731 implements with our existing highlight animation. This would be consistent with what the `Sink` and `Unsink` buttons in the same menu do.
