### ISSUE TITLE
Upgrade to Htmlawed 1.2

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5579]
This is a feature release, not a security fix.

Please spend some time testing this to make sure we're not going to cause problems:

* All formatters
* Quotes, Spoilers, and other special classes/markup.
* Not allowing new problems into UGC.

http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s4.3

**Comment by DaazKu** [comment]
We already are on 1.2 https://github.com/vanilla/htmlawed/releases/tag/v2.2
