### ISSUE TITLE
[Docs] Emphasize Documentation and Help pages in the dashboard.

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5580]
It would help admins get acquainted with their forums easier and cut down on support requests if the the help pages and links in the sidebar were emphasized more clearly. Right now the titles in the sidebar are a font-weight of 100, and are barely noticeable, while the text is font-weight 200, which is quite difficult to read.

This kind of change would also benefit  

**Ex. Before**

![image](https://cloud.githubusercontent.com/assets/1770056/26078010/16223a5c-398c-11e7-8539-3f6426343153.png)

**Ex. After**

![image](https://cloud.githubusercontent.com/assets/1770056/26078065/45052f8c-398c-11e7-8780-c1584b77e389.png)

Certain pages would also benefit from linking directly to [our documentation](http://docs.vanillaforums.com/). 

These pages include: 

* Branding, Customize Theme, Layout
* Roles and Permissions (Link goes to a 404
* Badges and many other plugins in the [addons section](http://docs.vanillaforums.com/help/addons/)

Thoughts @tburry @linc ?

**Comment by linc** [comment]
I'm in favor of this.

Function > Aesthetic.

**Comment by DaazKu** [comment]
I'm also in favor of this if we lighten the font color a bit

**Comment by Charrondev** [comment]
This seems to have been fixed by #5618
