### ISSUE TITLE
Maximum Category Display Depth should be on the categories page.

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5583]
The maximum category display depth settings should is related to categories, not posting, and as such should be moved from one settings page to the other.

**Comment by linc** [comment]
While I agree the placement isn't perfect, I think it's better to not have an extra option on the "Manage Categories" page or open that Pandora's box of adding other knobs & dials to that page. 

If we were just going by appropriateness of the page without considering how out of place it would look, I'd actually put it on Appearance -> Layout.
