### ISSUE TITLE
Enable link embeds in discussions and comments toggle broken

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5605]
It appears to toggle 'on'. In fact, it still inserts/keeps a '1' in the config.

**Comment by linc** [comment]
<img width="680" alt="screen shot 2017-05-18 at 5 04 41 pm" src="https://cloud.githubusercontent.com/assets/117672/26223511/5a4fe5aa-3bec-11e7-914b-d02757de9927.png">

**Comment by initvector** [comment]
Closing in favor of tracking this issue on its associated PR: #5636
