### ISSUE TITLE
Disabled embeds will still allow HTML5 elements

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5611]
We should configure Htmlawed to block `video` and `audio` elements (any others?) when embeds are disabled globally.

Are there other conditions we should be looking at regarding configuration vs. HTML5 entities? Htmlawed v1.2 added support for all of them.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR.

https://github.com/vanilla/vanilla/pull/5652
