### ISSUE TITLE
Markdown: underscores in URLs trigger italics

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5615]
Two underscores in a URL trigger italics parsing, which breaks subsequent auto-link parsing.

This URL: `https://www.newegg.com/Product/Product.aspx?Item=N82E16826816054&cm_re=m65-_-26-816-054-_-Product`

Produces: 
<img width="733" alt="screen shot 2017-05-23 at 5 11 22 pm" src="https://cloud.githubusercontent.com/assets/117672/26376545/df9073a0-3fda-11e7-8315-585ca37299c7.png">

**Comment by charrondev** [comment]
Not an issue in Rich Format.
