### ISSUE TITLE
Image upload fails in advanced editor in TextEx mode

### ISSUE THREAD

**Issue by topcheese13** [vanilla/vanilla#5626]
Uploading an image in TextEx mode fails although the is no error message and the upload seems to be going through.

This happens by drag and dropping and image file or using the image upload button.

We should hide the button and drag and dropping an image should behave as a file upload.

First to hide the upload image button I think this line:

https://github.com/vanilla/vanilla/blob/master/plugins/editor/views/editor.php#L102

should be this just because it makes more sense to separate them and I think it was a bad copy paste to begin with:
`, 'div', array('class' => 'editor-dropdown editor-dropdown-image'));`

Then we need to hide it in css

```
.editor-format-textex {
  .editor-dropdown-image {
    display: none !important;
  }
}
```

Last but not least we need to trigger a standard file upload on drag and drop instead of the image upload/embedding process that currently occurs and fails.

**Comment by charrondev** [comment]
Fixed in Rich Editor which is the default editor as of 2.8.
