### ISSUE TITLE
Markdown lists not rendered if following line beginning with asterisk

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5627]
When a Markdown post is parsed, if a list follows a line beginning with an asterisk, the list will not properly render. For example:

```markdown
**Bold text**
- Item one
- Item two
- Item three
```

If you put an empty line between the line starting with an asterisk and the list, it renders without issue.

**Comment by charrondev** [comment]
A common mark example shows that our behaviour here is off spec.

https://spec.commonmark.org/dingus/?text=%23%23%20Try%20CommonMark%0A%0A**Bold**%0A-%20asdf%0A-%20asdfadf
