### ISSUE TITLE
Usernames with underscores can render as italics in Markdown

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5628]
This is mostly a regression of https://github.com/vanilla/vanilla/issues/2474, following recent updates to the formatting chain.

When mentioning a username containing underscores (e.g. \_username\_) in a Markdown post, the name is rendered in italics and does not link to the user's profile.

**Comment by DaazKu** [comment]
Regression source: https://github.com/vanilla/vanilla/pull/5502

**Comment by linc** [comment]
This duplicates #5399
