### ISSUE TITLE
BeforeDiscussionContent being fired from CategoriesController instead of DiscussionsController

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5633]
I'm creating a  `discussionsController_BeforeDiscussionContent_handler` function in my theme hooks and it isn't being called correctly. It does however work if I call `categoriesController_BeforeDiscussionContent_handler`, but "BeforeDiscussionContent" is fired in in [`applications/vanilla/views/discussions/table_functions.php`](https://github.com/vanilla/vanilla/blob/2d72dd56031dbe94da0036216aaacac3dd3f7666/applications/vanilla/views/discussions/table_functions.php#L80). Shouldn't the event be firing on that controller?

My themehooks:

```php
class MyThemHooks extends Gdn_Plugin {

    /**
     * Run once on enable.
     *
     * @return void
     */
    public function setup() {
        $this->structure();
    }

    /**
     * Run on utility/update.
     *
     * @return void
     */
    public function structure() {
        saveToConfig([
            'Routes.DefaultController' => ['categories', 'Internal'],
            // 'Vanilla.Categories.Layout' => 'table',
            // 'Vanilla.Discussions.Layout' => 'table',
            'Garden.Thumbnail.Size' => '200'
        ]);
    }

    // This does not run
    public function discussionsController_BeforeDiscussionContent_handler($sender) {
        echo "<td>test</td>";
    }
}
```

It does work if I call base instead of DiscussionsController though.

```php
class MyThemHooks extends Gdn_Plugin {

    /**
     * Run once on enable.
     *
     * @return void
     */
    public function setup() {
        $this->structure();
    }

    /**
     * Run on utility/update.
     *
     * @return void
     */
    public function structure() {
        saveToConfig([
            'Routes.DefaultController' => ['categories', 'Internal'],
            // 'Vanilla.Categories.Layout' => 'table',
            // 'Vanilla.Discussions.Layout' => 'table',
            'Garden.Thumbnail.Size' => '200'
        ]);
    }

    // This does run
    public function base_BeforeDiscussionContent_handler($sender) {
        echo "<td>test</td>";
    }
}
```

**Comment by initvector** [comment]
The current controller should be passed down to the function.

For example, if you have your homepage configured to "Categories" and your categories set to display as "Mixed", your homepage controller would be `CategoriesController`. That would be passed down to where the discussion table is built with `writeDiscussionRow`. The function's `$Sender` parameter (the current controller) is used to trigger the event. That is why it can sometimes be `DiscussionsController` or `CategoriesController`.
