### ISSUE TITLE
Required version for addons isn't checked in 2.5+

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#5657]
You can see that by simply changing e.g. `"vanilla": ">=2.0.18"` in `/plugins/vanillicon/addon.json` to `"vanilla": "2.9"`. Remove `/cache/addon.php` or restart memcached to make sure the addon info is updated.
Now enable Vanillicon and although it should fail, it can be enabled without problems.

In Vanilla 2.3 the RequiredApplication version number also isn't checked, but at least the RequredPlugins version number is.

**Comment by Charrondev** [comment]
To add to this, I believe at this point it is "application" specific. Requirements should be working for addons of the type: "addon" for sure after this https://github.com/vanilla/vanilla/issues/6146.
