### ISSUE TITLE
[Advanced Editor] Styling is bugged on iPad

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5663]
In wysiwyg, on the iPad, when using text styling (strikethrough for example) it seems to exhibit these behaviors:

- Tapping the button enable it but the focus seems to not work properly which makes you type in the void.
- If you double tap some text and highlight it, you can strike it through.
- Tapping the button multiple times seems to jump me to other parts of the "new discussion" form, such as title or tags.
- Tapping the button if enabled doesn't seem to disable it.

The [library handling all this](https://github.com/xing/wysihtml5) is 6 years old and very complex..

I tried to fix the first issue by forcer a focus after the command execution but it was still buggy. For the other problems I have not clue on how to fix them.

**Comment by linc** [comment]
Would it be better to disable WYSIWYG for iPads than allow this bug to exist?

**Comment by DaazKu** [comment]
If we decide not to fix it that would be an "ok" solution.
It is just a bit weird to says that WYSIWYG is incompatible with IPad.

Looking forward we should aim at replacing this library or it will bite us harder than this.

**Comment by DaazKu** [comment]
Forcing Simple Html for IPad could also be a potential solution. I tested and it seems to work.

**Comment by charrondev** [comment]
Fixed in Rich Editor which is the default editor as of 2.8.
