### ISSUE TITLE
Resolve and display paths of symlinked plugins when in Debug mode.

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5686]
It could be tied to a different config key, but I propose listing the path (resolved path if it is a symlink) of the each plugin in the plugins folder when Debug is enabled. This can be useful when trying to quickly find out where a plugin comes from especially when many addons are installed.

**Comment by DaazKu** [comment]
If you use PHPStorm it's actually really easy to know:

<img width="333" alt="screen shot 2017-06-21 at 1 34 36 pm" src="https://user-images.githubusercontent.com/2412909/27398030-65f58cfc-5686-11e7-9601-e2a6e87aa558.png">

**Comment by Charrondev** [comment]
Yes. I think this will just right quick IDE plugin to do what I would like
