### ISSUE TITLE
Muting a category hides it in the mixed layout of all categories

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5687]
If a site's Categories Layout is configured to Mixed, muted categories will not display in the root list of categories.

Current routine:

1. [`CategoriesController::index` calls `CategoriesController::discussions`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/controllers/class.categoriescontroller.php#L226) if the layout is configured as "mixed"
1. [`CategoriesController::discussions` calls `CategoryModel::getFull`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/controllers/class.categoriescontroller.php#L549) to load its category data.
1. [`CategoryModel::getFull` calls `CategoryModel::categoryWatch`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/models/class.categorymodel.php#L1943), which returns an array of category IDs the user is "following" (i.e. not muted).
1. Category IDs not in the result of `CategoryModel::categoryWatch` are [filtered out](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/models/class.categorymodel.php#L1965).

**Comment by initvector** [comment]
This seems to be triggered by a [remnant of a deprecated module: `CategoryFollowToggleModule`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/controllers/class.categoriescontroller.php#L542). This module would toggle the value of a user's "ShowAllCategories" preference. Since the module's ability to be rendered was removed when it was deprecated in #4549, it should be safe to kill this lingering reference.

**Comment by linc** [comment]
https://vanillaforums.teamwork.com/#tasks/6942521

**Comment by tburry** [comment]
Muting is going to get removed once category following is fully integrated. Can you just tie this issue to the appropriate following task?

**Comment by charrondev** [comment]
Muting has been removed.
