### ISSUE TITLE
Markdown quotes encoded in inform notifications

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5688]
If a site is configured to enable `Vanilla.Activity.ShowCommentBody` or `Vanilla.Activity.ShowDiscussionBody`, the posts content is saved as the `Story` field when creating an entry in `Activity` table. When inform messages are polled through `NotificationsController::inform`, the story field of each new activity is [run through `Gdn_Format::plainText` and then put through `htmlspecialchars`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/dashboard/controllers/class.notificationscontroller.php#L93). The call to `Gdn_Format::plainText` does not pass along a value for the `$Format` parameter, so the default (Html) is used.

If a user receives a notification of a Markdown-formatted post, containing a quote (denoted by the > character), encoded HTML character representations appear. Since the call to `Gdn_Format::plainText` doesn't actually pass the `$Format` parameter, its contents are treated as HTML. Markdown's quote indicator, the "greater than" character (>) is a special character in HTML. The post goes through HTML sanitization routines and the quote indicator is encoded. The ultimate result is the inform message seen by the user also contains an encoded representation of this character (&gt;).

**Comment by initvector** [comment]
This can probably be resolved by just giving it the proper format.

```php
$story = $Activity['Story'];
$format = $Activity['Format'] ?: 'Html';
$storyText = Gdn_Format::plainText($story, $format);
$Excerpt = htmlspecialchars($storyText);
$ActivityClass = ' Activity-'.$Activity['ActivityType'];
```

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8397
