### ISSUE TITLE
HTML special characters encoded in emailed post notification subject lines

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5690]
If a user sets their notification preferences to be emailed of posting activity, for example when someone comments on a discussion they've created, an email is sent to that user containing the name of the discussion in the subject line. If the discussion has HTML special characters in its name, an ampersand for example, these characters are encoded in the subject line (e.g. &amp;amp;). For comment notifications, specifically, this seems to be due to `CommentModel::save2` [fetching its associated discussion with `DiscussionModel::getID`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/models/class.commentmodel.php#L974), which runs its result [through `DiscussionModel::calculate`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/models/class.discussionmodel.php#L1658), wherein the name is [put through `Gdn_Format::text`](https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/applications/vanilla/models/class.discussionmodel.php#L927). By the time the activity record is built and the email is queued up at the end of `CommentModel::save2`, the characters have been encoded.

**Comment by jamesinc** [comment]
So looking at it, it looks like `Gdn_Format::plainText` is called, and this does indeed appear to call `html_entity_decode`, but it then immediately re-adds HTML entities:

https://github.com/vanilla/vanilla/blob/a6b3f239deffb753abf43e1905cd776401cd5664/library/core/class.format.php#L1088-L1091

**Comment by jamesinc** [comment]
Okay I can confirm that the issue is solved with the following change to class.activitymodel.php

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.activitymodel.php#L1027

Becomes:
```php
$email->subject(sprintf(t('[%1$s] %2$s'), c('Garden.Title'), html_entity_decode(Gdn_Format::plainText($activity['Headline']))));
```

I'm happy to submit a pull request for this, but I'm not sure if there's any risks associated with allowing HTML characters in e-mail subject lines.

**Comment by jamesinc** [comment]
This bug still exists
