### ISSUE TITLE
Add SPAM log count to Me module

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5693]
The Me module has counters for the moderation queue, but not the SPAM queue. It looks like the SPAM queue count was removed with 8753802369da5c2ee1427178821d4c3a5c4d2402 in response to #1491, but it's not clear why.

It seems like there should be a SPAM queue count to accompany the moderation queue count.

**Comment by linc** [comment]
The spam queue is not a to do list. It should be ignored, as in email. We don't want a red number for a task we want to spare the user from ever doing.
