### ISSUE TITLE
Gdn_Session::validateTransientKey requires POST when forcing valid

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5694]
`Gdn_Session::validateTransientKey` has a [built-in kludge](https://github.com/vanilla/vanilla/blob/efb56b55daff68e31b7f1d104ec6ca56a688e901/library/core/class.session.php#L658) that only respects the `$ForceValid` flag if the current request is a postback. I don't see a documented reason for why this behavior is required. It seems like validating a transient key shouldn't be dependent on the type of request being made.

Can this process be streamlined to remove this postback requirement or, better yet, simplified to `if $ForceValid is true then return true`?

**Comment by charrondev** [comment]
@initvector Does this still seem relevant to you? What is the use case this would enable?

**Comment by initvector** [comment]
There are several instances throughout Vanilla and its addons where the TK is passed in the URL, either as a path parameter or part of the query string, as part of a get request. `Gdn_Session::validateTransientKey` allows you to bypass TK checks by passing in a boolean `true` as its `$ForeignKey` parameter. However, the "kludge" cited in this issue means it's only ever going to work for post requests. The aforementioned get requests would fail under similar circumstances.

The TK probably shouldn't be in any URLs to begin with, since I'm pretty sure they're all write operations under the guise of a read request, but fixing those instances is probably going to be a much more involved undertaking.

**Comment by charrondev** [comment]
Yeah I understand that. Basically all of our forum menus do write operations on GETs. (Thank you jquery `.Hijack`).

What I'm trying to understand is: Is this even something we want to do? My understanding is that we never should _never_ make another GET request like this that requires a transient key, so why would we  want to improve the developer experience of it?

**Comment by initvector** [comment]
> My understanding is that we never should _never_ make another GET request like this that requires a transient key, so why would we want to improve the developer experience of it?

The existing get requests using TKs we have now are broken to this "force valid" feature of `validateTransientKey`. Fixing it wouldn't be about making it easier for future requests of a similar nature to make, although I do concede that would be a consequence.

If memory serves, this particular issue was more relevant a couple years ago when API v1 was more commonly used. With API v2, it isn't a concern. It still might be possible to run into this issue when using access-token authentication outside of the API, but that is likely very uncommon (and probably should be unsupported).

**Comment by charrondev** [comment]
> The existing get requests using TKs we have now are broken to this "force valid" feature of `validateTransientKey`. Fixing it wouldn't be about making it easier for future requests of a similar nature to make, although I do concede that would be a consequence.

Is there a particular item that's broken as a result of this?

**Comment by initvector** [comment]
Here's a handful that would fail under the aforementioned conditions:

1. [`ActivityController::delete`](https://github.com/vanilla/vanilla/blob/5256cb1646b1ce790821162b679991a64935664e/applications/dashboard/controllers/class.activitycontroller.php#L201)
1. [`ActivityController::deleteComment`](https://github.com/vanilla/vanilla/blob/5256cb1646b1ce790821162b679991a64935664e/applications/dashboard/controllers/class.activitycontroller.php#L161)
1. [`MessageController::dismiss`](https://github.com/vanilla/vanilla/blob/5256cb1646b1ce790821162b679991a64935664e/applications/dashboard/controllers/class.messagecontroller.php#L66)
1. [`RoutesController::delete`](https://github.com/vanilla/vanilla/blob/5256cb1646b1ce790821162b679991a64935664e/applications/dashboard/controllers/class.routescontroller.php#L120)
1. [`DiscussionController::deleteComment`](https://github.com/vanilla/vanilla/blob/5256cb1646b1ce790821162b679991a64935664e/applications/vanilla/controllers/class.discussioncontroller.php#L729)

After invoking `Gdn::session()->validateTransientKey(true)`, a developer might expect _all_ their transient key checks to pass. They would be wrong. All post requests would pass their TK checks, but any other TK checks wouldn't be "forced" to `true`. It's unnecessarily inconsistent. It isn't even doing much to deter the creation of additional get requests to endpoints with TKs in them. It only ensures you can't force those particular checks.
