### ISSUE TITLE
Mention suggestions not completing in Internet Explorer

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5697]
The following error is encountered in Internet Explorer 11, when clicking a username from the list of mention suggestions.

> IndexSizeError
> [jquery.atwho.js (641,10)](https://github.com/vanilla/vanilla/blob/efb56b55daff68e31b7f1d104ec6ca56a688e901/js/library/jquery.atwho.js#L641)

### To Recreate

1. Open an Internet Explorer 11 window.
1. Create a new discussion or begin a new comment.
1. Attempt to mention a user. You'll need to use a username with a common beginning. The suggestion menu will need to appear, preferably with several options.
1. Click an item from the suggestions menu. The suggestions menu should disappear and you'll be dropped back to the text field. The suggestion you chose will not have been autocompleted. The text will remain the same as when you clicked on the suggestion.

**Comment by slafleche** [comment]
In PR: https://github.com/vanilla/vanilla/pull/5793
