### ISSUE TITLE
Rethink the way we generate URLs

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5700]
We should create a new class that takes the Gdn_Request object to help creating proper urls and deprecate Gdn_Request->url().

## Current problems
- Gdn_Request->url is bloated and really hard to update. 
    - It was designed to receive a path and generate an URL to the current site but is used to parse any URLs
        > This method allows safe creation of URLs that need to reference the application itself
        > ....
        > @param string $path of the controller method.
    - The $withDomain option evolved to become a mess that accepts 5 different values and one of them is not even documented.
- We have big time problems to generate proper links with webroot/subcommunities
- Calling url(url($path)) can result in bugged URLs (especially with webroot)

## Desired functionalities
1. Pass a `$path`(relative URL) or an `$url`(absolute URL). Let's call this a `$destination` from now on.
1. Relative `$destination`: (always assumed be relative to the forum itself)
    - Being able to force the URL to be absolute.
    - Being able to force the URL to use ssl `https://`, use normal http `http://`,  or use the current scheme `//`
        - The force scheme feature could be config driven by default.
        - If the forced scheme match the current scheme we can keep the URL relative.
1. Absolute `$destination`:
    - External:
        - Force the scheme if manually specified otherwise return as is. *not sure if we want to go there but the current method can do that*
    - Internal:
        - Being able to make the URL relative.
        - Being able to force the scheme like described above.
1. Cache, on a per request basis, the arguments and the resulting URL for fast return and double parsing prevention. This will make `url(url(url(url($destination))))` return the same thing than `url($destination)`. If we do this right even `url(url(url(url($destination, params1..), params2..), params3..), params4..)` could use the cache made by the first call to url($destination, params1...) to return the proper URL

**Comment by charrondev** [comment]
See `Gdn_Request::getSimpleUrl()`

https://github.com/vanilla/vanilla/blob/master/library/core/class.request.php#L1673-L1678
