### ISSUE TITLE
Poor installation instructions

### ISSUE THREAD

**Issue by attardi** [vanilla/vanilla#5702]
Installation instructions claim to be simple, but are incomplete and installation fails.
They start with:
Upload Vanilla's pre-built version to your server.
without saying that this is a zip file which should be unzipped, presumably, in the DocumenRoot of the web server. I got the file vanilla-core-2-3-1.zi, and I unzipped it into /var/www/html/vanilla
Then it says:
Navigate to that folder in your web browser.
I assume this means to open http://server/vanilla.
Unfortunately what I get is:
The requested URL /vanilla/dashboard/setup was not found on this server.
which is correct, since there is no folder dashboard in the distribution.

Please advise.

**Comment by linc** [comment]
Did the `.htaccess1` file copy over?

**Comment by maddiecain** [comment]
I am having the same issue. There is a file called .htaccess, but no file called .htaccess1. Could this be the cause of the problem?

**Comment by linc** [comment]
It was just a typo. `.htaccess`.

**Comment by maddiecain** [comment]
Ok, thanks for clarifying. I have .htaccess, and I tried the original contents and these contents I found on a forum:
# Modified
# If you modify this file then change the above line to: # Modified
<IfModule mod_rewrite.c>
   RewriteEngine On
   # Certain hosts may require the following line.
   # If vanilla is in a subfolder then you need to specify it after the /.
   # (ex. You put Vanilla in /forum so change the next line to: RewriteBase /forum or whatever name you have given your forum if in a subdirectory)
   RewriteBase /
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^(.*)$ index.php\?p=$1 [QSA,L]
</IfModule>

And both are giving me this error. Do you have any guidance/suggestions on how to fix this?

**Comment by linc** [comment]
I suggest pursuing this on the forum https://open.vanillaforums.com/discussions until a concrete change can be suggested.
