### ISSUE TITLE
BBCode parser encodes < and > inside code tags

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5720]
The `<` and `>` symbols, when used inside `[code]` BBCode tags, get rendered as `&lt;` and `&gt;`. Something something parse order failure.

Possibly related: https://github.com/vanilla/vanilla/pull/5646

**Comment by linc** [comment]
Backport to `release/2017-Q2-6`

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: https://github.com/vanilla/vanilla/pull/5724
