### ISSUE TITLE
Certain custom plugins break when toggling on.

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#5732]
At the heart of the issue is that Gdn::PluginManager()->GetPluginInstance({pluginclass}) which is executed before the execution of the plugin in the line:
```
Gdn::FactoryInstall('MentionsFormatter', 'MarvelHeroesPlugin', __FILE__, Gdn::FactorySingleton, Gdn::PluginManager()->GetPluginInstance('MarvelHeroesPlugin'));
```
cannot find the plugin class because it is not registered.

**Comment by nervoustwit** [comment]
Also effects uc4sso plugin

**Comment by DaazKu** [comment]
We can probably move that call in a hook.
Not a core issue per say.

**Comment by linc** [comment]
Yeah, this needs to be sorted out in the individual addons by modifying the timing of those calls, I believe.
