### ISSUE TITLE
Inserting a too-large text into the DB silently truncates the inserted value

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#5738]
Currently I've only encountered this in the Pockets plugin, but if you attempt to set the body of a pocket to something larger than the maximum character count of a TEXT column in MySQL it currently just truncates the text and gives no notice that you are attempting to insert something too large. The DB  driver should throw an exception to force developers to handle this case in their plugins. In the case of a Pocket, cutting off html at an arbitrary point can easily result in invalid markup being produced and screw up the entire page.

**Comment by bleistivt** [comment]
In strict mode MySQL will reject values that are too long.
#5177
