### ISSUE TITLE
Make Gdn_Format::bigNumber() locale aware

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#5741]
This is currently listed as an @todo on the DocBlock for the function, so I figured I should make a proper issue. This function should be locale aware. Not all languages use "B", "M", and "K" to represent 1 000 000 000, 1 000 000, and 1 000 respectively, and different languages use different decimal and thousands separators. Some use `,`, some use ` `, and some use `.` in different places.

We should set a default, and have a language strings for `THOUSANDS_SEPERATOR`, `DECIMAL_SEPERATOR`, `ABBREVIATION_THOUSANDS`, `ABBREVIATION_MILLIONS`, and `ABBREVIATION_BILLIONS`.

**Comment by DaazKu** [comment]
In french it would be
1000 -> k
1000000 -> M
1000000000 -> G

**Comment by charrondev** [comment]
Locale aware number formatting is now provided by https://github.com/vanilla/vanilla/blob/master/library/src/scripts/components/NumberFormatted.tsx using the `numeral` library.
