### ISSUE TITLE
Tags privacy cannot be controlled

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5745]
There are currently no way to restrict the display of tags.
This can be a problem in some edge case scenario.

Example: Let's say you have an "Admin Section" category and you tag some discussion but don't want these tags to be show in your public section of the forum.
This is a legitimate issue, even if rare.

We should do so research about a possible solution to this problem. Especially when we will [improve tagging](https://github.com/vanilla/vanilla/issues/5295).

See https://github.com/vanilla/internal/issues/984#issuecomment-313507907

**Comment by R-J** [comment]
I guess this issue is closed by this PR: https://github.com/vanilla/vanilla/pull/5749

**Comment by DaazKu** [comment]
Not it is not:

> Example: Let's say you have an "Admin Section" category and you tag some discussion but don't want these tags to be show in your public section of the forum.
This is a legitimate issue, even if rare.

**Comment by DaazKu** [comment]
There also is a need to make some tags "private" in the sense that we would like to use Tagging internally without a "Tag" being displayed on the UI.
This would be a way to add metadata on records.
