### ISSUE TITLE
Installing Vanilla 2.3.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by rjmolesa** [vanilla/vanilla#5748]
NM. Please ignore. Close. Delete.

**Comment by rjmolesa** [comment]
NM. Please ignore. Close. Delete.

**Comment by DaazKu** [comment]
In case someone use the search feature and stumble on this issue:

Original content:

> I'm doing a fresh install in an isolated network for research purposes. Simply decompressing the file into the html directory and trying to access that URL to install it gives me:
>
> PHP Fatal error: require_once(): Failed opening required '/var/www/html/vanilla/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/vanilla/bootstrap.php on line 50
>
>  in /var/log/apache2/error.log
>
> The index.php page in totally blank.

Answer: You need to run composer install as [specified in the documentation](https://github.com/vanilla/vanilla#readme)
