### ISSUE TITLE
Add /configuration endpoint to API v2

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5751]
API v1 has a [/configuration endpoint](http://docs.vanillaforums.com/api/forum-administration). API v2 will need to implement a similar endpoint for managing a site's configuration.

**Comment by linc** [comment]
We should do this as a new endpoint for exclusively whitelisted items that are reasonable to set over API (like site title). We should sit down and brainstorm this out, and it may involve more endpoints or nested arrays.
