### ISSUE TITLE
[Question] - Vanilla API

### ISSUE THREAD

**Issue by deinok** [vanilla/vanilla#5759]
Vanilla Docs talk about something called [Simple API](http://docs.vanillaforums.com/api/).
There is no information about how to enable it or how to install it.

**Comment by Charrondev** [comment]
The `Simple API` plugin is available only on Vanilla Cloud hosting. You can read about the different Vanilla Forums hosting options [here](https://vanillaforums.com/en/plans/).

For forum administrators on Vanilla Cloud hosting the `Simple API` plugin is enabled like any other plugin - through the `plugins` menu in the dashboard.
