### ISSUE TITLE
Markdown formatter can produce invalid html output with bbcode spoiler tags

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#5761]
The markdown editor is capable of producing invalid html markup. This can entirely break a pages flow if a browser parses it properly. This visual output may to appear completely different, but it depending on theme and how the browser parses this issue along with the rest of the page it can completely break the page flow. An example can be found on a live site [here](https://forums.marvelheroesomega.com/discussion/3919/improvements-to-loot-boxes-and-costume-changes-coming-soon/p23)

**Steps to Reproduce**

1. Open a vanilla forum with the advanced editor set to markdown
2. Create a post or comment with the following body
```markdown
> [spoiler]
>
> [/spoiler]
```
3. Observe the html output. The primary Chrome Dev tools view may attempt to correct the mistake, so you will need to look in the true source, which can be accessed in the chrome dev tools through the following menu
![image](https://user-images.githubusercontent.com/1770056/28142195-c8bb04b8-672d-11e7-94f7-46bff20c2660.png)

**Expected Output**
```html
<blockquote class="UserQuote">
    <div class="QuoteText">
        <p>[spoiler]</p>
    </div>
</blockquote>
<blockquote class="UserQuote">
    <div class="QuoteText">
    </div>
</blockquote>
<blockquote class="UserQuote">
    <div class="QuoteText">
        <p>[/spoiler]</p>
    </div>
</blockquote>
```

**Real ouput**
```html
<blockquote class="UserQuote">
    <div class="QuoteText">
       <p><div class="Spoiler"></p>
    </div>
</blockquote>

<p>&gt;</p>

<blockquote class="UserQuote">
    <div class="QuoteText">
        <p></div></p>
    </div>
</blockquote>
```

## Root Cause

Pretty sure this comes from our `legacySpoilers` formatting.

https://github.com/vanilla/vanilla/blob/7d8464da520795331cf84456466c952e90bcc046/library/core/class.format.php#L950-L958

**Comment by linc** [comment]
Are you reporting multiple scenarios and only giving one example, or are you specifically reporting that quotes + spoilers together generate invalid HTML? Your title implies the former, your description the latter.

**Comment by Charrondev** [comment]
The latter. I've updated the title
