### ISSUE TITLE
Endpoint /discussions/promoted: cache expiry

### ISSUE THREAD

**Issue by badpix11** [vanilla/vanilla#5762]
The Endpoint /discussions/promoted allows to provide an integer "how long in seconds to cache the content". [http://docs.vanillaforums.com/api/discussions/](http://docs.vanillaforums.com/api/discussions/)

If you provide 0 (zero) as expiry (?expiry=0) the content will not expire until the cache is cleared.

This can cause issues on some sites, because the endpoint doesn't require auth and may fill up the memcache with old and never expiring content. Forums which use this module will only show old promoted content to all users.

Solutions would be:
Bind the expiration-time to auth users
Limit the input like between 1 and 60 (or x) seconds

**Comment by DaazKu** [comment]
Expiry is set in [PromotedContentModule->load()](https://github.com/vanilla/vanilla/blob/5c36b9d0e3ae869f41baa4ce0689749a2153c862/applications/vanilla/modules/class.promotedcontentmodule.php#L76).
