### ISSUE TITLE
Migrate /users/notifications functionality to API v2

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5771]
The [/users/notifications](https://blog.vanillaforums.com/api-users-notifications) endpoint from API v1 (or similar functionality) needs to be migrated to API v2.

**Comment by initvector** [comment]
On hold per @tburry while we reevaluate notifications in Vanilla.

**Comment by tburry** [comment]
We have what we need from this endpoint.

**Comment by charrondev** [comment]
See `/api/v2/notifications`
