### ISSUE TITLE
Create 'Advanced Categories' settings page

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#5781]
Vanilla has a few configuration settings for categories that are scattered either scattered around the dashboard, or not exposed at all.

These include

- `Vanilla.Categories.Use` - enables categories
- `Vanilla.Categories.MaxPages` - Sets max amount of available pages
- `Vanilla.Categories.MaxDisplayDepth` - Sets the depth where subcategory nesting starts
- `Vanilla.Categories.PerPage` - Sets the amount of categories per page
- `Vanilla.Categories.HideModule` - Hides the default categories module (usually in the panel)

I propose creating a tab in the categories pane of the dashboard for the category settings. It should be extendable so that is can be hooked by various addons.

If nothing else the `Vanilla.Categories.MaxDisplayDepth` settings should be pulled out of the 'Posting' section and put somewhere else.

**Comment by DaazKu** [comment]
@tburry ?

**Comment by Charrondev** [comment]
`Vanilla.Category.Use` doesn't need to be there but I think there's a case to be made for the other 2 that are currently not exposed, `Vanilla.Categories.MaxPages` and `Vanilla.Categories.HideModule`. Maybe `Vanilla.Categories.MaxPages` could be limited to system level users only?

**Comment by chrisvanpatten** [comment]
Minor/unimportant voice chiming in… but it would be so cool to have `HideModule` available (presumably would be on the hosted platform?). Using CSS to do it now which is fine but any add'l customisation is always appreciated ^__^

**Comment by linc** [comment]
This is better than #5583.

**Comment by linc** [comment]
If we were going to do this, I'd want to move "Manage Categories" under the Moderation top nav, and put this under Settings top nav instead.
