### ISSUE TITLE
Users with delete user permissions should not be able to delete themselves

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#5789]
I had a moderator on my forum go berserk and hard-delete his own account. This caused operational issues for us as in doing so he also deleted all his activity in his capacity as moderator (i.e. threads/comments detailing forum rule breaches and things like that).

I had no idea moderators and other users with the delete permission could delete _themselves_, and I don't think it should be possible.

My request is to add a check to prevent users self-deleting. It could be configurable for backwards-compatibility.

**Comment by charrondev** [comment]
## Investigation required before proceeding

- Can a user delete other users with delete permission?
- Are `IsAdmin` users protected?
- What do we want this to actually reflect?
