### ISSUE TITLE
Create /authentication endpoint

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5802]
The spec is there: https://github.com/vanilla/vanilla/issues/5563#issuecomment-301902989
We need to make sure that [all the configurations](https://github.com/vanilla/vanilla/issues/5591#issuecomment-317837904) are honoured.

Note: Coordinate with OPs to make sure that `/authentication` is excluded from being cached.

**Comment by linc** [comment]
I suggest attempting to break this down a bit. Usually we leave '16' story points as a placeholder for "we need to break this down more before we sprint it" not something that actually happens during a sprint.

**Comment by DaazKu** [comment]
Tracking will be done on the PR https://github.com/vanilla/vanilla/pull/5831
