### ISSUE TITLE
First user in new forum can create new discussions/comments without verification.

### ISSUE THREAD

**Issue by romeojulietthotel** [vanilla/vanilla#5804]
This problem was seen on a new 2.3.1 install and for the first user to register. The first user was able to create a new discussion and write comments to that discussion before being verified via email. This seems like a bug to me but maybe Vanilla requires captcha which I don't have enabled. So maybe it's a feature when captcha's not enabled.

I tried the same with the next user registered and was unable to create discussions/comments.

**Comment by linc** [comment]
The first user is created as part of the install process. Are you using a separate install process that doesn't do this?

**Comment by romeojulietthotel** [comment]
From what I can remember, I just did a default install.  But since decided to use another platform.
