### ISSUE TITLE
Travis CI build failing on Trusty

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5815]
Travis CI is gradually making Trusty the default distro for builds. Vanilla's Travis build is not currently compatible with the Trusty distro. The following error is encountered:

> Syntax error or access violation: 1044 Access denied for user 'travis'@'%' to database 'vanilla_test'

Related: #5637

**Comment by DaazKu** [comment]
> [2:56 PM] Alexandre Chouinard: we have until September 22 to update our travis to run on Trusty instead of Precise because we are using sudo: false
[2:57 PM] Alexandre Chouinard: https://blog.travis-ci.com/2017-08-31-trusty-as-default-status#once-more-with-calendar

@linc You will need to assign someone to do this

**Comment by DaazKu** [comment]
Seems like we could use [sudo: required](https://github.com/vanilla/vanilla/issues/5637#issuecomment-306507915) but this still entails some change.
We should probably aim at being compliant with Trusty right away.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6028
