### ISSUE TITLE
Increase complexity of email confirmation token

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5817]
The email confirmation token is currently an 8-character token from a 36-character pool (upper + digits). At 1000 requests per second, that's an average brute force time of 4 years. Significantly more resources could bring this down to _perhaps_ (if the target can accommodate many multiples of that in requests without triggering a DDoS warning) a week. This is still a poor vector however, because it's much simpler to Mechanical Turk additional user registrations, for which we have no real code-based defense in the product.

Because it's trivially simple to increase the complexity into the "impossible" range, we should do so. I suggest a 12-character token and expanding the pool to include lowercase letters.

**Comment by initvector** [comment]
Closing in favor of tracking on associated PR: #5822
