### ISSUE TITLE
Audit permissions

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5828]
* Combine / rename existing permissions where appropriate.
* Figure out backwards-compatible transition.
* Blocker for API v2 permissions.

**Comment by Charrondev** [comment]
I feel like these permissions: 
![image](https://user-images.githubusercontent.com/1770056/29139467-14df7e30-7d15-11e7-9c1f-f0490aea39c5.png)

Could do with some more explicit names. If not internally than in the frontend. `Vanilla.Comments.Me` doesn't explain itself very well. I jumped into it a little and it seems to be about actions on your own posts? Most site admins probably don't have a very good concept of what that does.

`Vanilla.Approval.Require` isn't self explanatory either. Approval for what? Comments? Posts? Some other action?

`Vanilla.Tagging.Add` Seems fine though.

**Comment by linc** [comment]
closed by #5539
