### ISSUE TITLE
Invalid default value for 'DateExpires'

### ISSUE THREAD

**Issue by RubbaBoy** [vanilla/vanilla#5832]
When installing Vanilla for the first time with a clean apache server and MySQL server, the error "Invalid default value for 'DateExpires'" occurs.

**Comment by DaazKu** [comment]
Probably related: https://github.com/vanilla/vanilla/issues/5763

**Comment by DaazKu** [comment]
See this article for a possible workaround: https://www.percona.com/blog/2016/10/18/upgrading-to-mysql-5-7-beware-of-the-new-strict-mode/

**Comment by linc** [comment]
The workaround is to disable MySQL's strict mode.

**Comment by linc** [comment]
Note from @DaazKu:

> This can be reproduced on MySQL and MariaDB but **not** on Percona

Vanilla uses Percona exclusively internally and for our automated testing, which is how this slipped by us. That was a major question for me.
