### ISSUE TITLE
BBCode doesn't support 'size'

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5833]
Our previous changes to the BBCode parsing order mean we need to amend our markup generated for parsing the `[size]` tag such that it can pass thru HTMLawed.

see also https://github.com/vanilla/vanilla/issues/5483

**Comment by charrondev** [comment]
I'm going to close this because the direction we've moved in for user content involves a much more restricted subset of user content. Various heading sizes are available for using different size text. These sizes can also be adjusted through theming.
