### ISSUE TITLE
[API v2] Associative arrays should be marked as objects in the schema

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5852]
For example: https://github.com/vanilla/vanilla/blob/514c3deb9b735e7e363aae10714b3e634608dc10/applications/dashboard/controllers/Api/UsersApiController.php#L80

Since the returned data is always JSON, a PHP associative array is not an array but an object.

**Comment by tburry** [comment]
That schema shows an array of role style objects so array is correct there.

**Comment by DaazKu** [comment]
Yup you are right. My bad. I god confused by the affectation of $this->schema.
