### ISSUE TITLE
Nested quotes should not notify authors

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5853]
We use `@mentions` to quote, which works well. However, a many-tiers-deep nest of quotes causes a cacophony of notifications, which does not work well. I propose we either remove mentions from tier-2 downward, or parse them out before detecting notifications.

This may also be a point at which we say "is this really even an addon anymore?"

**Comment by charrondev** [comment]
This is fixed with Rich Editor (it was one of the design considerations). Does that satisfy the issue for you @linc ?

**Comment by linc** [comment]
Yes
