### ISSUE TITLE
Backspacing after a quote can trap your cursor in WYSIWYG

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5860]
When quoting another user, the original post content is inserted into the new post. The input cursor is moved to follow the new content. If you're in WYSIWYG mode and you backspace past the beginning of the current line, the input cursor will be pulled into the quote. Since there's no content after the quote at this point, you won't be able to move back down past it.

### Steps to Reproduce
1. Enable the Advanced Editor and Quotes addons.
1. Configure WYSIWYG as the Advanced Editor format.
1. Create a comment on an existing discussion.
1. Quote a post from the discussion.
1. Backspace until your cursor appears in the quoted content.
1. Try to get back down beneath the quoted content.

**Comment by charrondev** [comment]
Non-security fixes will no longer be prioritized for advanced editor by the vanilla team. Rich Editor ships with Vanilla 2.8 as the default. https://github.com/vanilla/vanilla/pull/8302
