### ISSUE TITLE
Latency between quoting a post and it appearing in the editor

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5861]
Using the Quotes addon, a user can click a "Quote" link in a post to insert that post's content in their comment as a quote. The way this works is a request is sent to the server, which returns the properly-formatted code (BBCode, Markdown, HTML, etc.) to insert. Since this is a separate request, there is a delay between when the link is clicked and the content is inserted. Depending on the user's connection and the server's response time, this delay can be significant enough to noticeable. This noticeable delay can sometimes cause users to click the "Quote" link multiple times, because they aren't seeing the responsiveness they expect.

It may be beneficial to disable "Quote" links after clicking them, at least until the request completes.

**Comment by R-J** [comment]
I'm a big fan of microinteractions. If you disable the button, your users will see a disabled button. That is no clear message. We've all experienced "frozen" interfaces where the button looks disabled but you are never sure what is really causing that.

A disabled button would only look similar to broken which is not what you would like to present to your users.

I like buttons which "react" in an understandable way:
https://dribbble.com/shots/2201051-Activate-Button
https://dribbble.com/shots/1426764-Submit-Button
https://codepen.io/cemre/pen/wFjIB

I know that this is a pattern which is not found at any other place in Vanilla and the UI should be consistent, but maybe it could be changed for all buttons which have AJAX actions in the background.

**Comment by chrisvanpatten** [comment]
Agreed with @R-J — a third "pending" or "waiting" state is more intuitive from a UX perspective. The button would still need to be _technically_ disabled, but shouldn't look the same.

**Comment by charrondev** [comment]
This issue is fixed in Rich Editor. The new default editor as of Vanilla 2.8.

The route taken was to focus the editor immediately and insert an embedded comment. This displays a loading indicator.

![image](https://user-images.githubusercontent.com/1770056/52377314-7b7c8400-2a32-11e9-813a-82cba667fa63.png)
