### ISSUE TITLE
Manually entering a username while connecting can dodge requirements

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5866]
If connecting via SSO and you need to manually enter a username, it's possible the username validation and requirement restrictions may not be applied. This might be possible with other SSO addons, but I've experienced it specifically with jsConnect.

Steps to reproduce:

1. Enable autoconnect on a site.
1. Attempt to connect a new account, using a name that already exists on the site.
1. You'll be prompted to enter the password for the existing user or create a new name.
1. If you enter a new name, you can enter pretty much whatever you want. It appears to skip all validation.

This seems to be due to the following:
1. [`EntryController::connect` asking SSO addons to interpret and modify the incoming data.](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/dashboard/controllers/class.entrycontroller.php#L438)
1. [Addons, like jsConnect, use this event to inject the Name and Email fields.](https://github.com/vanilla/addons/blob/8725d2c1f080f6aa8a8bf599034281864f2857ca/plugins/jsconnect/class.jsconnect.plugin.php#L420)
1. [`EntryController::connect` performs some connection logic, based on the presence of the Name or Email fields.](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/dashboard/controllers/class.entrycontroller.php#L558)
1. [This ultimately trickles down to a condition where creating a user or not is determined.](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/dashboard/controllers/class.entrycontroller.php#L714)
1. [A user is potentially created based on ConnectName (the field the user entered), although it's never properly validated.](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/dashboard/controllers/class.entrycontroller.php#L729)

**Comment by linc** [comment]
Make sure any fix here also addresses the username blacklist, as per #6006.

**Comment by initvector** [comment]
Closed by #7148
