### ISSUE TITLE
Vanilla.Comments.AllowSelfDelete not allowing users to delete own comments

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5867]
The Vanilla.Comments.AllowSelfDelete config should allow users to delete their own comments, so long as the comment is still able to be edited. With this config enabled, a normal site user should be able to make a request to [`DiscussionController::deleteComment`](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/vanilla/controllers/class.discussioncontroller.php#L720) and have their comment deleted.

37f99dd tweaked the logic of determining if the comment can be edited. However, the ability to delete a comment is now based on [if the discussion can be edited](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/vanilla/controllers/class.discussioncontroller.php#L741). The check should be changed to verify the comment is still editable.

*Side note: Adding and editing comments is done in `PostController`. Maybe deleting comments should be moved there too.*

**Comment by charrondev** [comment]
Digging in a little bit, the key piece here is that when the permission check for deleting a comment is done, it [checks the discussion instead](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/vanilla/controllers/class.discussioncontroller.php#L720).

Properly resolving the issue would look like the following:

- Move the `DiscussionModel`'s [editContentTimeout](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.discussionmodel.php#L252-L263) method up to `Gdn_Model`. The parameter names should be made more generic and the description updated.
- Update `DiscussionModel->canEdit` to use `Gdn_Model->editContentTimeout`  and remove `DiscussionModel->editContentTimeout`.
- Create a `canEdit` function on the `CommentModel` similar to [the one on the DiscussionModel](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.discussionmodel.php#L229-L243)
- Use this check in place of the [discussion check when deleting a comment](https://github.com/vanilla/vanilla/blob/41dd256854a93da28bc5f5b0274bea1c3fb6b646/applications/vanilla/controllers/class.discussioncontroller.php#L720).
- Use this same check in place the freeform checks in the `helper_functions` [getCommentOptions](https://github.com/vanilla/vanilla/blob/master/applications/vanilla/views/discussion/helper_functions.php#L427-L479).

**Comment by R-J** [comment]
I like the idea of pulling the editContentTimeOut to the Gdn_Model! I've tried my hands on your suggested changes: https://github.com/vanilla/vanilla/pull/6782#pullrequestreview-105025448
