### ISSUE TITLE
Profile pages for discussions and comments not checking Garden.Profiles.View

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5870]
Vanilla adds a couple profile pages: [/profile/comments](https://github.com/vanilla/vanilla/blob/27e57016f48c964782df35a5e1b13f1e528b5ebe/applications/vanilla/settings/class.hooks.php#L826) and [/profile/discussions](https://github.com/vanilla/vanilla/blob/27e57016f48c964782df35a5e1b13f1e528b5ebe/applications/vanilla/settings/class.hooks.php#L885). Neither of these profile pages verify the current user has the Garden.Profiles.View permission, whereas [`ProfileController::activity` does](https://github.com/vanilla/vanilla/blob/27e57016f48c964782df35a5e1b13f1e528b5ebe/applications/dashboard/controllers/class.profilecontroller.php#L120). For the sake of consistency, it seems like the discussions and comments profile pages should also be checking this permission.

**Comment by charrondev** [comment]
Fixed with https://github.com/vanilla/vanilla/commit/f41f09c254a4913d51bdf9d090e94d13304dc145
