### ISSUE TITLE
Oauth2 redirection returns 500

### ISSUE THREAD

**Issue by aniruddha-ezest** [vanilla/vanilla#5871]
I have configured oauth2 plugin. After clicking Sign In, I get OAuth Approval page.
On clicking Authorize button on the page, I receive internal server error on 'xx.xx.xx.xx/entry/oauth2?code=rvFgmo&state=target%3D%252Fdiscussions'
How do figure out the issue, as I am not able to login again.

**Comment by charrondev** [comment]
I understand it's been a while, but in order for an issue like this to be actionable it needs reproduction steps. If you need assistance please check our [open source forum](https://open.vanillaforums.com). This issue tracker is for verified bugs or detailed feature requests/planning only.
