### ISSUE TITLE
Investigate improving memory usage when moving a discussion

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#5872]
When a discussion is moved, part of the routine is to iterate over the affected categories and update them. This isn't an issue on most sites, but sites with hundreds of categories and millions of posts can quickly exhaust the available memory on a server, especially when leaving behind a "redirect" discussion.

Anything that can be done to improve memory usage in this area would be beneficial.

**Comment by charrondev** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/7899
