### ISSUE TITLE
Using B) as an emoji code is bad

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5875]
I don't like it A) because it's not single-use and B) it messes up my multi-point explanations all the time.

**Comment by R-J** [comment]
But it looks cool :sunglasses:

**Comment by charrondev** [comment]
Fixed in Rich Editor, the default editor as of Vanilla 2.8.

There is no ambiguity in the rich format. Rich Editor uses real emojies, and dedicated data structures for lists.
