### ISSUE TITLE
/tokens

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5876]
This endpoint requires the modifying GDN_AccessToken to add the AccessTokenID auto-increment column.

The /tokens endpoints will initially be for granting/revoking personal access tokens.

## POST /tokens

- name: A user-defined name indicating what the access token will be used for.
- transientKey: The users's CSRF token. This limits the endpoint to the web UI (more or less).

Create an access token. The type of access token will be "personal". The name doesn't have a column so add it to the attributes.

### Output

- accessTokenID
- name
- accessToken: This is the signed access token suitable for making requests.
- dateInserted

## GET /tokens

Get the active personal access tokens for a user. This does not include expired or revoked tokens.

### Output

- accessTokenID: An ID used to revoke the token.
- name
- dateInserted

## DELETE /tokens/:id

Revoke the access token with the given ID.

## GET /tokens/:id

- transientKey: The users's CSRF token. This limits the endpoint to the web UI (more or less).

Reveal the access token with the given ID.

### Output

- accessTokenID
- name
- accessToken
- dateInserted

This is the same as the output for POST /tokens

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5877
