### ISSUE TITLE
Activity story is not formatted before being send by email

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5891]
How do reproduce:
- Set `Vanilla.Activity.ShowCommentBody = true`
- Configure your notification settings to receive notification when a user comments on discussion you have created.
- Create the following comment with another user:
```
Styled text:
[b]Bold[/b]
[i]Italic[/i]
[s]Strike[/s]
```
![screen shot 2017-08-25 at 1 21 52 pm](https://user-images.githubusercontent.com/2412909/29724915-61fed974-8998-11e7-8c95-cd041c435a91.png)

Expected result:

```
Styled text:
Bold
Italic
Strike
```

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8237
