### ISSUE TITLE
Implement ConversationModel::delete() and ConversationMessageModel::delete()

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5897]
The deleted records need to go in the log table.
We need to be able to restore a conversation/message but the content of them should not be shown unless the `Conversations.Moderation.Allow` config is enabled and that the user has the `Conversations.Moderation.Manage` permission.

This is required to finish implementation of DELETE /api/v2/conversations/:id

https://github.com/vanilla/vanilla/blob/5de232fb9a7b382518a9c896fdcb8d4eb2c1077d/applications/conversations/controllers/api/ConversationsApiController.php#L89-L92

**Comment by charrondev** [comment]
I'm closing this issue because it is not actionable or on our near roadmap. It may be revisited in the future at which point we will come up with user stories for the various scenarios we would like to handle and will implement those user cases.
