### ISSUE TITLE
Copy access token js and icon

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5898]
The /profile/tokens endpoint allows personal access tokens to be generated and viewed. A newly generated token shows the token and the user then manually copies it by select the text and hitting command C. What would be nice would be a copy icon that would copy the access token using something like clipboard.js when clicked.

Below is the look and feel of the page. I'd coordinate with design and @slafleche for the bit of HTML. In our current theme just putting the SVG in the view as a symbol will suffice.

<img width="766" alt="personal_access_tokens" src="https://user-images.githubusercontent.com/97432/29843775-0e581f10-8cdb-11e7-92c1-2179078865aa.png">

**Comment by slafleche** [comment]
PR: https://github.com/vanilla/vanilla/pull/6060
