### ISSUE TITLE
UserModel::expandUsers optimization

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5899]
`expandUsers` should be optimized to fetch all users before populating instead of fetching them one by one. Once the cache is made this is not a big issue but on the first load (or if you do not have caching enabled) this is pretty bad.

**Comment by DaazKu** [comment]
> [10:35 AM] Ryan Perry: Expanding users: I was looking back through  my notes with Todd, from February/March. He originally wanted a "pseudo-option" in the $where param (e.g. "expand") of UserModel::joinUsers. We wanted to be able to control whether or not other records would be joined in when querying. It was implemented and then ditched in favor of that expandUsers function, which works on a single row or an array of rows, has very limited parameters and just always returns the full row. Addons modifying the output schema can switch up what fields are available. However, when we ditched the pseudo-option, we lost the ability to control whether or not records (categories and users) were joined in. The expandUsers function appears to have originally been used for one row, but quickly changed to work with multiple rows, but never optimized for that.
[10:38 AM] Alexandre Chouinard: Not now but we should statute on which one we want to keep and refactor the code accordingly
[10:38 AM] Alexandre Chouinard: There is no reason for the 2 to coexist
[10:39 AM] Alexandre Chouinard: expandUsers with option could definitely replace joinUsers

**Comment by initvector** [comment]
Closing in favor of tracking on the associated issue #5901
