### ISSUE TITLE
Security feature: Block non-trusted domain embeds

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#5902]
Because of the nature of UGC and the Internet, you can add images from many sources that are hosted elsewhere. They, in turn, receive HTTP requests from users that show basic browser info and IP address. This could lead to situations where a nefarious actor could plant an image to collect this sort of meta data. This is pretty limited in usefulness in 99% of forum use cases, but it could still be something that some forum runners, especially in sensitive topic areas or corporate use cases, wish to eliminate.

Proxying all embedded images is a bit too complex of a solution for most open source servers, in our estimation. We also don't want to outright block all of this content, since this is a very tablestakes forum feature.

We should provide a standard option in the Security section of the Dashboard to disable embedded content that is not from domains on the Trusted Domains list. This seems like a fine compromise for concerned parties to opt into, rather than removing this functionality from the platform.

**Comment by tburry** [comment]
This is done.
