### ISSUE TITLE
[API v2] Inconsistencies between schema related to inclusion of method parameters

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5911]
A good example of this is when a method like `get()` defines [id in its schema](https://github.com/vanilla/vanilla/blob/675d4d532b10002810523105fa4f405b12a542b0/applications/vanilla/controllers/api/CommentsApiController.php#L159) but a different method like [patch()](https://github.com/vanilla/vanilla/blob/675d4d532b10002810523105fa4f405b12a542b0/applications/vanilla/controllers/api/CommentsApiController.php#L323) -> [CommentAPIController::commentPostSchema()](https://github.com/vanilla/vanilla/blob/675d4d532b10002810523105fa4f405b12a542b0/applications/vanilla/controllers/api/CommentsApiController.php#L76) does not.

We need to address this. Either we do or we don't!

**Comment by DaazKu** [comment]
We should probably have Swagger read the methods signature to know whether id should or not be present in the documentation.

**Comment by DaazKu** [comment]
So the proper way to address this in POST/PATCH is to have 2 'in' schemas.

```php
$this->idParamSchema('in;);
$this->postParamSchema('in')->setDescription('blabla');
```

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6043
