### ISSUE TITLE
Users API field translations

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5920]
I've been looking at the user object and would like to make some of the fields more clear in terms of the API.

- **confirmed** should be renamed to **emailConfirmed**.
- **verified** should be renamed to **bypassSpam**

In addition to these changes I think these should just be treated as fields that can be given to POST and PATCH rather than having a PUT /users/id/verify style endpoint. In this case emailConfirmed defaults to 1 and bypassSpam defaults to 0.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated issue: #5951
