### ISSUE TITLE
Private Conversation missing in Messages All when using PHP 7.1 on Master.

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#5922]
I noticed I get a notification of a new private conversation in the mebox, but it not showing on the messages page until the other party responds. Using Php 7.1 and latest master.

**Comment by adrianspeyer** [comment]
I should add, when I click on the email notification, the message is there.

**Comment by bleistivt** [comment]
It's at the end of the list, because DateConversationUpdated is NULL.
This has been causing me a lot of trouble, I will submit a fix in a moment.

**Comment by linc** [comment]
Thanks very much!
