### ISSUE TITLE
Move some of the discussions PUT endpoints into fields for the PATCH endpoint

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#5937]
I think we should try to be as pure as possible with our API which means allowing most fields to be set in POST and PATCH rather than giving specific endpoints.

- [x] PUT /discussions/{id}/close should become the **closed** field.
- [x] PUT /discussions/{id}/sink should become the **sink** field.
- [x] PUT /discussions/{id}announce will become the **pinned** and **pinLocation** fields.

**Note**: This complicates the permissions on the endpoints a bit. Users with certain permissions can access only some fields on the endpoint. It's possible that a **permissionField** method on the controller base class might be helpful here. It can throw an error if a specific field is specified, but the user doesn't have permission.

**Note**: The PUT /discussions/{id}/bookmark will remain as is since that is not information on the discussion resource itself.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #5958
