### ISSUE TITLE
vanilla reloops setup from home link

### ISSUE THREAD

**Issue by 2Epic** [vanilla/vanilla#5939]
I am running plesk and php7 i installed vanilla 2.3.1 it installs with no issue but after install if i click home link it redirects me to set up page again over and over also it seems to have login issues aswell. if i logout then login it says incorrect info but if i refresh it logs me in.

**Comment by 2Epic** [comment]
http://example.com/subfolder  dont work but http://example.com/subfolder/index.php does

**Comment by linc** [comment]
I suggest pursuing help for this on the forum https://open.vanillaforums.com/discussions and then an issue can be filed when it's tracked down to something more concrete.
