### ISSUE TITLE
Add CSS classes to notification preferences table

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5955]
These table headers and rows/columns of the profile notifications table should have css classes on them so they can be targeted more robustly. This settings page can be found at `/profile/preferences/`. This will also need a backport to the current release branch in order to be used by the client.

**Comment by slafleche** [comment]
We're going to be updating these tables soon in the new base theme. For now you can use the "headers" attribute to target columns like so: `.PrefCheckBox[headers='GeneralEmailHeader'] {}`
