### ISSUE TITLE
Add the Group API controller

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5971]
### Endpoints

```
GET POST /groups
GET PATCH DELETE /groups/:id
```

### Notes

- These are mostly straightforward CRUD for groups.
- `GET /groups` needs a filter for my groups.
- `GET /groups` needs to be an order param. (dateInserted, dateLastComment, countMembers, countDiscussions). FYI: The convention for ordering in the APIv2 should be columnName sorts ascending and -columnName sorts descending.
- The groups addon needs to add an optional groupID parameter to POST/PATCH discussion to associate a discussion with a group. Group permissions must be checked for validity when associating a discussion to a group which may require a custom validator in the schema.

**Comment by linc** [comment]
Issue moved to [vanilla/internal #1210](https://github.com/vanilla/internal/issues/1210) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #1211](https://github.com/vanilla/internal/issues/1211) via [**ZenHub**](https://www.zenhub.com/)
