### ISSUE TITLE
Add the GroupMember API controller

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5972]
### Endpoints

| Endpoint | Description |
| -------- | ----------- |
| GET /groups/:id/members | List the members in a group. |
| POST /groups/:id/members | Allow a moderator to moderator to add a user to a group. |
| POST /groups/:id/join | Join a group. |
| POST /groups/:id/leave | Leave a group. |
| PATCH /groups/:id/members/:userID | Change a user's role within a group. |
| DELETE /groups/:id/members/:userID? | Remove a user from a group or leave a group. |
| GET /groups/:id/invites | List the invitations for a group. |
| POST /groups/:id/invites | Invite a user to the group. |
| DELETE /groups/:id/invites/:userID | Delete an invitation from a group. |
| GET /groups/:id/applicants | List the applicants for a group. |
| PATCH /groups/:id/applicants/:userID | Approve or deny a group applicant. |
| POST /groups/:id/apply | Apply to a private group. |

### Notes

- `/join` is used to join a public group or accept an invitation.

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #1205](https://github.com/vanilla/internal/issues/1205) via [**ZenHub**](https://www.zenhub.com/)
