### ISSUE TITLE
Add GroupEvent API Controller

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5973]
### Ednpoints

| Endpoint | Description |
| -------- | ----------- |
| GET /events | List events. |
| POST /events | Create an event. |
| PATCH /events/:id | Update an event. |
| DELETE /events/:id | Delete an event. |
| GET /events/:id/participants | List event participants. |
| POST /events/:id/participants | RSVP to an event. |

### Notes

- The events endpoint is made global even though events are currently only a part of groups because events may become global at some point.
- Lowercase GDN_Event.Attending values for the API.
- GDN_UserEvent has an "invited" status which I think shouldn't be allowed in the endpoint.
- A user that RSVPs can change their status by calling `POST /events/:id/participants` again.

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #1206](https://github.com/vanilla/internal/issues/1206) via [**ZenHub**](https://www.zenhub.com/)
