### ISSUE TITLE
[SSO] There is no feedback that a session could not be started when connecting over SSO

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#5988]
We [start the session](https://github.com/vanilla/vanilla/blob/3ed9e2ba2e0f2f6bdfc6ba7c2988c1a0d60597d5/applications/dashboard/controllers/class.entrycontroller.php#L550), it fails and we redirect to the supplied target. 
0 feedback that the session could not start due to permission problems (like if the user was banned)

**Comment by linc** [comment]
This is being inquired about by the success team for followup, perhaps for 2.5.
