### ISSUE TITLE
Mentions: Autocomplete dropdown is being reordered by Chrome

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#5992]
@mention result set dropdown is different between browsers, chrome is reordering the result based on id

Chrome 
![chromemention](https://user-images.githubusercontent.com/31856281/30975797-2a2648ca-a441-11e7-8c64-add18545f35e.png)

Mozilla
![mozillamention](https://user-images.githubusercontent.com/31856281/30975798-2a296ef6-a441-11e7-8c80-f4d72711d417.png)

**Comment by DaazKu** [comment]
- Which one is supposed to be correct?
- Which is chrome and which is Firefox in your screenshot?

That doesn't seem to be the case on my side.

Chrome left, Firefox right

![ffvschrome](https://user-images.githubusercontent.com/2412909/30977090-855b9bb6-a444-11e7-8054-f37df1a5f0d2.png)

**Comment by dannimajdalani** [comment]
Mozilla is correct, result is from their live site

http://youview.vanillacommunities.com/

**Comment by charrondev** [comment]
Fixed in Rich Editor, the default editor as of Vanilla 2.8.
