### ISSUE TITLE
/api/v2/media endpoint should be validate files by mimetype

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#5994]
We currently validate file uploads using extension only. It is more proper to use MIME type validation to prevent masking malicious files by changing their extension.

**Comment by charrondev** [comment]
I'm kind of confused what the purpose of this file is then https://github.com/vanilla/vanilla/issues/7229

**Comment by tburry** [comment]
I think we are going to need to sniff the mime type on uploaded files to prevent sniffing. I'm hoping we can use [mime_content_type](https://www.php.net/manual/en/function.mime-content-type.php) as a start here. I can see checks like this:

1. Don't allow files to upload if their extension does not match the specified mime type.
2. Don't allow files to upload if their mime type does not match the sniffed mime type.
3. Add the [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) to file uploads.

Any other ideas?

**Comment by tburry** [comment]
There is also [a package](https://github.com/ralouphie/mimey) we could use for file extensions rather than maintain our own.

**Comment by tburry** [comment]
I think we are good on this now.
