### ISSUE TITLE
EntryController should redirect to the homepage if user is signed in

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#5999]
Many other sites do this. It would make sense for the entry page to redirect to the homepage if a user is currently authed. If a user wants to sign in as a different user (I don't think it's good practice to encourage multiple accounts per user) then they can sign out first.

**Comment by linc** [comment]
I don't think this is good behavior. Escalating your permission state shouldn't make a page inaccessible. Here's an easy one: Putting a Message on the Sign In page and then wanting to view + make further edits. You shouldn't need multiple browsers / Incognito Mode to review basic forum functionality as an admin.
