### ISSUE TITLE
Validation should not use '%s is required.' as translation string

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6001]
"Body" and "Password" are currently translated as single words that is causing undesirable messages being displayed when combined with error messages 
"Body is required" translated to "Corps est obligatoire" should be "Votre message est vide"
"Password is required" translated to "Mot de passe est obligatoire" should be "Votre Mot de passe est obligatoire"

**Comment by linc** [comment]
The solution is to break out all uses of this string as separate translation strings, and then add them to the locales repo.
