### ISSUE TITLE
Not validating blacklisted usernames when connecting over SSO

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#6006]
There is a [validation rule](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermodel.php#L2051) in the UserModel::save() function that restricts user's from choosing a user name that is also an API endpoint. This validation is bypassed when users create a user name when connecting over SSO because Vanilla uses the convenience method [UserModel::insertInternal()](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermodel.php#L929)  that doesn't have this validation rule applied.

**Comment by linc** [comment]
This is a subset of https://github.com/vanilla/vanilla/issues/5866
