### ISSUE TITLE
Addon Manager does not enable required addons for themes

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6022]
The `ThemeManager` does not seem to properly enable required addons for themes. They just get ignored entirely.

Taking a look inside it, the theme manager seems to call `checkRequirements` but never calls `lookupRequirements` like the PluginManager does. Maybe the addon manager should  be responsible for managing the requirements of an addon instead of having to place the logic in the `ThemeManager` and `PluginManager`?

**Comment by Charrondev** [comment]
Closed in favor of #5108

**Comment by Charrondev** [comment]
It seems #5108 hasn't actually implemented everything necessary for this so I'm going to re-open this.
