### ISSUE TITLE
[APIv2] PUT should not be used to do a partial update

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6023]
Explanation: https://stackoverflow.com/questions/28459418/rest-api-put-vs-patch-with-real-life-examples

TL;DR PUT needs to have all field passed in the body to be used.

**Comment by initvector** [comment]
I don't think this is necessarily applicable, since we aren't using any URLs where PUT is called on the base endpoint (e.g. /api/v2/users). It's only called on specific fields (e.g. /api/v2/users/ban). We can view these fields as a "sub-resource" and the value is being replaced.

**Comment by DaazKu** [comment]
That's a fair point and that makes sense.
