### ISSUE TITLE
Default all table to InnoDB if MySQL version > 5.6

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6029]
*Note: I'm hijacking this issue mainly to get the PR I reworked reviewed.*

InnoDB support fulltext in MySQL 5.6+ so we should create all the table using InnoDB instead of using MyISAM if the MySQL version allows it.

The whole "supportFullText" feature also needs a revamp. More details about that there: https://github.com/vanilla/vanilla/issues/5555

**Comment by R-J** [comment]
This should be done with 2.8 since requirements now are MySQL 5.7
https://docs.vanillaforums.com/developer/installation/self-hosting/#requirements

**Comment by initvector** [comment]
Closed by #9470
