### ISSUE TITLE
oauth2 plugin throws 400 ERROR code

### ISSUE THREAD

**Issue by aniruddha-ezest** [vanilla/vanilla#6031]
https://localhost/vanilla/index.php?p=/entry/oauth2&code=6I0kea&state=target%3D%252F

![issue](https://user-images.githubusercontent.com/22446195/31502244-1e4b4010-af8a-11e7-90e7-d8258439884c.png)

**Comment by linc** [comment]
This is not sufficient information for a bug report. Please include steps to reproduce, and the expected result.
