### ISSUE TITLE
[APIv2] Standardize the way we normalize controllers' input and output.

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6033]
There's currently a pattern used in most APIv2 controllers where we 
- normalize input data (which is identical to the schema) to match a resource (which matches the database structure)
- normalize a resource so that it matches the schema before outputting it.

Here are some example,

- Input normalization
    - [DraftApiController::translateRequest()](https://github.com/vanilla/vanilla/pull/6018/files#diff-9cf5fecf04c53dfe1914f16feaa4ff35R318)
    - [ConversationsApiController::normalizeInput()](https://github.com/vanilla/vanilla/blob/master/applications/conversations/controllers/api/ConversationsApiController.php#L429)
    - [UserApiController::translateRequest()](https://github.com/vanilla/vanilla-patches/pull/123/files#diff-11bff59f8425fdfdf29f1d45f2f52a6fR424)
- Output normalization:
    - [RolesApiController::prepareRow()](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/api/RolesApiController.php#L170) (That one is widely used)
    - [ConversationApiController:: translateParticipantStatus()](https://github.com/vanilla/vanilla/pull/6030/files#diff-125dbe0d3f52b236f9a7e9fcab096e6dR476)
    - [DraftApiController::prepareRow()](https://github.com/vanilla/vanilla/pull/6018/files#diff-9cf5fecf04c53dfe1914f16feaa4ff35R307) which just calls [DraftApiController::translateRow()](https://github.com/vanilla/vanilla/pull/6018/files#diff-9cf5fecf04c53dfe1914f16feaa4ff35R363)
    - [DraftApiController::prepareRow()](https://github.com/vanilla/vanilla/blob/master/applications/conversations/controllers/api/ConversationsApiController.php#L447)

We should stick with 2 names and refactor the code to use them.

Suggestions for the names:

- `inputToRecord()` + `recordToOutput()`
- `normalizeInput()` + `normalizeOutput()`
- `schemaToRecord()` + `recordToSchema()`

**Comment by linc** [comment]
Mostly I want it to be 2 words and not stick the word `To` in the middle of it.

I'd like something slightly non-parallel, like `normalizeInput()` and `prepareOutput()`. I don't like frequently-used method names to only be differentiated by a couple letters in the middle; feels like an error waiting to happen.

**Comment by tburry** [comment]
My vote is normalizeInput() + normalizeOutput().

**Comment by initvector** [comment]
What about `normalizeRequest` (input) and `normalizeRow` (output)? They're "slightly non-parallel" and are clearly "normalization" functions.

**Comment by DaazKu** [comment]
Request and Row are too generic for my taste. 
I vote for `normalizeInput()` and `normalizeOutput()` which should be located at the top and bottom of the methods near the input and output of said methods.

**Comment by DaazKu** [comment]
Closing in favour of tracking on the associated PR
