### ISSUE TITLE
Additional date filtering in comments, discussions and users endpoints

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6034]
Adding row filtering by the date it was created or updated needs to be implemented in the comments, discussions and users endpoints.

"dateInserted" and "dateUpdated" parameters need to be added to each endpoint index. They will use a special notation to specify date comparison operations or ranges. A parser to support these date values is going to be a project unto itself: [#6037](https://github.com/vanilla/vanilla/issues/6037)

It will be possible to use these date filters together (e.g. getting all rows created since X and updated since Y).

### Comments

The comments index currently requires at least `discussionID` or `userID` parameter. This requirement will need to be expanded to include the date filters.

`CommentModel` basically has two methods for querying comments: `getByDiscussion` and by `getByUser2`. Neither of these is a good fit for querying all comments by date criteria. There are events in the existing methods that allow addons to hook in and modify the result. Both fire an "AfterGet" event. A new, general-use function should be implemented on `CommentModel` for querying comments that includes the "AfterGet" event. This function should be able to accept an array of arbitrary "where" conditions, which will allow passing over "inserted" and "updated" date range filters.

The new comment query method should optionally impose the permissions of the current user on the result. See [`CommentModel::getByUser2`](https://github.com/vanilla/vanilla/blob/9ae51020f2d17f1baf9b0133b8ffbc8475ace5bb/applications/vanilla/models/class.commentmodel.php#L413).

### Discussions

The discussions index uses `DiscussionModel::getAnnouncements` and `DiscussionModel::getWhereRecent` to query rows. Each of these functions allow arbitrary "where" conditions. The limitations on date inserted and updated can be passed directly.

View permissions are handled by the existing methods used in `DiscussionModel`.

### Users

The users index uses `UserModel::search` to fetch user rows. The method has a `$filter` parameter. This parameter supports some special keywords (e.g. "Keywords" and "Optimize"), but also acts as an array of "where" clauses to send along with the user query. Date range filtering conditions on inserted and updated date columns can be passed directly to this function.

The index is already protected by a check for user management permissions.

**Comment by DaazKu** [comment]
We need to kill "after" and update any code we own that use it if needs be. We are not gonna deprecate something before the release.

DateUpdated is not indexed on any tables.
Querying using that parameter will be really slow on big tables.

We should probably start talking about filters and indexes at some point.

**Comment by initvector** [comment]
> We need to kill "after" and update any code we own that use it if needs be. We are not gonna deprecate something before the release.

I'm also in the "kill it" camp, but I want to get a consensus before deciding its simply going to be removed. I *think* this is the first time an endpoint has had its parameters changed after being published to the master branch. It has been available to users for a while. Of course there should be no expectation the features won't change, since there's been no official release, but the fact still remains users could be affected by this.

> DateUpdated is not indexed anywhere. Querying using that parameter will be really slow on big tables.

Agreed. If we're filtering on it, it should be indexed.

**Comment by linc** [comment]
Since `DateUpdated` filtering is not something we plan to use in the application, I think it would be fine to leave it unindexed and address it if it becomes a problem on specific sites. If we start adding indices for every customer request and possible use case, we're gonna have a problem. A slow API query is an acceptable tradeoff, especially since the only declared use case for that so far is a once-daily query to get updated discussions.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6156
