### ISSUE TITLE
Spam Count Is Showing to Users 

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6036]
# Current Behaviour

When a users reports a post, the reported post user can see the number of times he has been reported and by who. This can be turned off by selecting "don't show" under reactions addon, however this will turn off this feature for all reactions. There is also a count that show next to flag indicating the number of times the post has been flagged.

# Requested Fix

Have the ability to turn of the pop-up that shows who flagged the post and disable the count next to it

![thumb_projectfile](https://user-images.githubusercontent.com/31856281/31513276-e2ca3d94-af5b-11e7-93c6-bfb24b9d4c81.png)

**Comment by linc** [comment]
Issue moved to [vanilla/internal #1332](https://github.com/vanilla/internal/issues/1332) via [**ZenHub**](https://www.zenhub.com/)
