### ISSUE TITLE
Fork Swagger to OpenAPI

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#6046]
We want to move the swagger plugin to core, but not as a plugin.

- Move the code to the dashboard application.
- The endpoint should be /api/v2/open-api/v2 and /api/v2/open-api/v2/summary rather than /api/v2/swagger and /api/v2/swagger/summary

The model can still be the SwaggerModel for the v2 endpoint.

**Comment by DaazKu** [comment]
From a support perspective I think that the menu item should probably stay named API v2.
Pretty much everything that refers to it has v2 in the name (public doc, the url, etc..)
We could confirm with sales and supports.

**Comment by DaazKu** [comment]
Exclude authenticate and authenticator docs
