### ISSUE TITLE
Group Leaders Unable to Edit Users Comments

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6048]
## Current Behaviour

Group leaders cannot edit comments posted in their group even though "Group Settings"/"Allow Leaders of a Group to edit or delete comments" is toggled on.

## To Reproduce

- Create a group
- Join users to the group and comment
- Try to edit any of the comments as a  group leader, an error "You do not have permission to do 
   that" 

![137ef9d20dc9f3873fc6d9f0c1f15004](https://user-images.githubusercontent.com/31856281/31681091-3766a630-b344-11e7-99a3-fafc97cf4d1f.png)
![13d4c07da2247f677dad39c640de0dbb](https://user-images.githubusercontent.com/31856281/31681201-8aff1f66-b344-11e7-9cf4-e85d4ac2fb9a.png)

**Comment by DaazKu** [comment]
Wrong repository.
Also, you made me investigate the issue to find out why it was happening and I told you exactly what was the problem. 
Why is this not part of the issue?

The [fix](https://github.com/vanilla/internal/pull/1190/files#diff-3451297306c99112509719952323a135R414) is already merged we only need the backport now.

**Comment by dannimajdalani** [comment]
I was requested to create a new issue ..
