### ISSUE TITLE
ProfileExtender: add new type of field

### ISSUE THREAD

**Issue by masiorama** [vanilla/vanilla#6053]
Hello, I'm trying to understand what should be the right way to add more types of field in the ProfileExtender plugin.

For instance, if I would like to add a dropdown with multiple selection to display on the registration form and on the user profile.

Am I supposed to hack directly in the code of the plugin or are there hooks to do that?

Thanks in advance.

**Comment by R-J** [comment]
Good news! The ProfileExtender supports textboxes, dropdowns and checkboxes out of the box.

By the way: the open source support [forum](https://open.vanillaforums.com/discussions) is a better place for discussing on how to avoid having to "hack" Vanilla. See you there! :wink:

**Comment by masiorama** [comment]
Thanks!
