### ISSUE TITLE
Promoted Content Module breaks with large amounts of tracked user activity in private categories

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6059]
The Promoted Content Module strips out items a user can't see after collecting all of the records. This means if a community has any tracked users that are active moderators they can totally empty out the promoted content module for normal users.

**Steps to reproduce**
- Create a role `RoleA`
- Create a PromotedContentModule tracking `RoleA`. Set the limit to 9 (the default). Set it to track only 'Discussions' not comments
- Make enough posts as a user with `RoleA` to fill up the module.
- Make some posts in a private category (or report a few posts, this creates a post from your account in the private Reported Post's category).
- Watch as the Promoted Content module empties out

**Possible Solutions**
- Allow category exclusions in the promoted content module
- Recursively fetch additional content until there is enough items.
- Use a separate final output limit from the # of items fetched from the DB.

**Comment by linc** [comment]
See also https://github.com/vanilla/vanilla/issues/2462
