### ISSUE TITLE
APIv2 Pagination

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6069]
> [12:56 PM] Todd Burry: Paging having no guarantee of records is a core principle and we should document that.
[1:05 PM] Alexandre Chouinard: We need a way to signal that there is no more record to be fetched then.

We should update:
```
'limit:i?' => [
                'description' => 'The number of items per page.',
```
to
```
'limit:i?' => [
                'description' => 'Desired number of items per page. See {DocumentationLink} for more details.',
```
- [x] Create the documentation on docs.vanillaforums.com
- [x] Address the EOF problem
    - After filtering, a page could have 0 results and the next one could have multiple results. We need a way to notify the consumer that there is no more records to fetch. A possible solution could be to send an EOF custom header or something along those lines.

**Comment by tburry** [comment]
I think we can document as: 'The max number of items per page.'. A note about paging in the API docs will also be good.

**Comment by DaazKu** [comment]
We are going to use [JSON API pagination](http://jsonapi.org/format/#fetching-pagination)

The next page link will tell if there is more data to fetch or not.
