### ISSUE TITLE
Twitter embed does not display in Preview mode

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6070]
# Issue

When you share a twitter link in a post, and click on preview, only shows the link unlike Instagram, Pinterest.

# To Reproduce

Share this link in a post and click preview

https://twitter.com/vanilla/status/814160323867447296

## Current behaviour

![twitterlink](https://user-images.githubusercontent.com/31856281/32000586-257a8708-b965-11e7-8dd9-bc786f1568aa.png)

## Correct behaviour

![twittercorrect](https://user-images.githubusercontent.com/31856281/32000585-256c7136-b965-11e7-8e4a-bb81057fbdb2.png)

**Comment by DaazKu** [comment]
Works on my local setup.
![screen shot 2017-10-25 at 10 05 51 am](https://user-images.githubusercontent.com/2412909/32003091-1ad58ba2-b96c-11e7-8be6-30904d9a5f85.png)

**Comment by DaazKu** [comment]
The twitter card HTML is present in the preview but `window.tweets()` is not called to render the card.
This is a javascript issue.
