### ISSUE TITLE
Allow SVG uploads in the dashboard

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6089]
It seems there are some significant [security concerns surrounding user-uploadable SVGs].

That doesn't mean we shouldn't allow SVG uploads in the dashboard from people with `Garden.Settings.Manage` permission. These users/admins already have numerous easier ways to XSS their users.

Even then any of these security concerns may not be as large of a factor when an SVG is [rendered in an image context](https://www.w3.org/wiki/SVG_Security) `<img src="some.svg">`.

**Things to consider**
- Having a separate pipeline that doesn't generate thumbnails
- Enforcement of dimensions/aspect ratios

**Comment by DaazKu** [comment]
/quote Even then any of these security concerns are no longer a factor when an SVG is rendered in an image context <img src="some.svg">.
It is not true that the security concerns are no longer a factor. Simply accessing the SVG will trigger scripts embedded in it.

<img width="1118" alt="screen shot 2017-11-01 at 3 58 25 pm" src="https://user-images.githubusercontent.com/2412909/32296789-96e717b2-bf23-11e7-9e76-25f0c19cca16.png">

**Comment by Charrondev** [comment]
This is true, which is why this functionality should only be enabled for users with sufficient permissions until there is a bullet-proof method of sanitizing SVGs in PHP.

**Comment by DaazKu** [comment]
A good start would be https://github.com/darylldoyle/svg-sanitizer

**Comment by linc** [comment]
Supplants https://github.com/vanilla/vanilla/issues/5520

**Comment by Crell** [comment]
This is still an issue.  This is in reference to admin users, so presumably they're trustworthy, no?  If the admin user uploads an SVG logo with an embedded Javascript snippet, presumably he knows what he's doing.  And if not, he's malicious enough that he would do something nefarious anyway through ample other avenues.

**Comment by DaazKu** [comment]
The title was a bit misleading here.

The real issue is not about trusting site admins. 
It's about having sane protections against potential XSS vulnerabilities. Someone could, unknowingly, very easily upload an SVG he took from the internet containing some harmful script on their forum.
