### ISSUE TITLE
Update RolesApiController to allow getting a paginated list of permissions per role

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6098]
### GET /roles/permissions

This is a pageable list of permissions.

| Parameter  | Type |
| -------- | -------- |
| roleID     | int |
| type       | string [global\|cateogry] |
| page       | int |
| categoryID | int (short form for type=category&id=xxx) |

```
[
    {
    "roleID": int,
    "type": (category|global),
    "id": int,
    "permissions": { }
  }
]
```

**Comment by charrondev** [comment]
@initvector Does this still need to be implemented? I see a GET /api/v2/roles/:id/permissions.

**Comment by initvector** [comment]
That endpoint only responds to the patch and put verbs, not get.

**Comment by charrondev** [comment]
Ah I understand. So this isn't to get a list of all of the permissions of a particular role (Which the GET `/roles/:id?expand=permissions`) will do, but it to list __all possible permissions__.
