### ISSUE TITLE
Update RolesApiController to allow overwriting all permissions for a role

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6099]
### PUT /roles/:id/permissions

Overwrite all of the permissions on a role.

- Any global permissions that are not specified are set to false.
- Any categories that are not specified are deleted in GDN_Permission.
- Any categories that are specified set non-sepcified permissions to false.

**Comment by charrondev** [comment]
This seems to be have been implemented around Vanilla 2.6 

![image](https://user-images.githubusercontent.com/1770056/53468144-0abffa80-3a27-11e9-82b3-cff550b9bd87.png)
