### ISSUE TITLE
Update RolesApiController to allow copying attributes from one role to another

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6100]
### POST /roles/copy

```
{
  fromRoleID?: int,
  fromRoleType?: string, enum['guest','unconfirmed','applicant','member','moderator','administrator']
  toRoleID?: int,
  fields: string|string[], emum["permissions"]
}
```

**Comment by charrondev** [comment]
@initvector Do we have user stories or a need to still do this or was it just .a nice to have? Thinking about internal uses going forward I don't necessarily see the utility of this existing as mentioned here.

**Comment by initvector** [comment]
To my knowledge, this was a "nice to have", many moons ago, shortly after the basic CRUD of the roles API resource was implemented. I don't think there's been a whole lot of demand for it.
