### ISSUE TITLE
Advanced Editor in WYSIWYG: Page jumps to top when trying to edit very long OPs

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6114]
### Issue

When Advanced Editor Plugin is Enabled with WYSIWYG format, editing a discussion with a large text body cause the page to jump to the top

### to Reproduce

1. Enable Advanced Editor Plugin with WYSIWYG format
2. Open a New Discussion page
3. Paste the test in the attached file
4. Try editing that text, you'll constantly be bumped to the top of the page

### Plugin - class.editor.plugin.php

[Link](https://github.com/vanilla/vanilla/blob/master/plugins/editor/class.editor.plugin.php)

### Test Text

[Test Text](https://github.com/vanilla/vanilla/files/1448587/test.docx)

**Comment by linc** [comment]
Please stop filing issues In Capital Case and make the titles concise, descriptive sentences.
