### ISSUE TITLE
Facebook integration breaks when not using SSL

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6120]
It seems the facebook integration no longer works form `http://` addresses. It only works over `https://`. We should add a note to the plugin warning about this if the site does not force `https://`.

The error given is generally the following: 
```json
{
   "error": {
      "message": "Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "CFXiwYBtDm4"
   }
}
```

**Comment by PedroCavaleiro** [comment]
I have my website running over HTTPS with redirection if someone tries to use http and still get this error

**Comment by charrondev** [comment]
I'm closing this because it's 2019. You're site should be served over https.
