### ISSUE TITLE
Remove allowNull from schema definitions

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#6126]
The garden schema had support for an allowNull property which is an extension from JSON schema. 

The correct way to specify allow null is to specify multiple types which garden schema now supports. The allowNull property will be getting removed from garden schema so it would be best to remove it from API schemas now. Luckily, there is a way to do it already with short schemas:

Old way:

```php
Schema::parse([
    'photo:s' => [
        'allowNull' => true,
        'minLength' => 0,
        'description' => 'Raw photo field value from the user record.'
    ]
])
```

New way:

```php
Schema::parse([
    'photo:s|n' => [
        'minLength' => 0,
        'description' => 'Raw photo field value from the user record.'
    ]
])
```

In fact, that short syntax notation was made in anticipation of this very change.

**Comment by initvector** [comment]
Closing in favor of tracking on the associated PR: #6135
