### ISSUE TITLE
Addon requirements don't properly verify names or version of required addons

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6146]
## Steps to reproduce
- Create a new addon and symlink it into the plugins folder
- Create an `addon.json` file it with the following require key
```
"require": {
    "alskdfjl;askdjfl;aksdfj": ">1.0",
    "vanilla": ">= 4320"
}
```
- Attempt to enable the addon

## Expected Behaviour
The addon will not be enabled and an error will be displayed. The first addon does not exist and the second addon does not have a compatible version.

## Actual Behavior
The addon is successfully enabled with no visible warnings.

**Comment by tburry** [comment]
FYI: This could have been reproduced with a fixture. I'll add that to your other PR.
