### ISSUE TITLE
Some API endpoints have edge case hard limits that cannot be circumvented

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6149]
- Token API Controller -> https://github.com/vanilla/vanilla/pull/5877#discussion_r135101862
- Role API Controller -> https://github.com/vanilla/vanilla/pull/6141#issuecomment-345071472
    - See also: #6150

**Comment by initvector** [comment]
See also: #6150

**Comment by charrondev** [comment]
Closing in favour of the subissues.
