### ISSUE TITLE
Get permissions via API on roles with more than 100 permission rows

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6150]
If a role has more than 100 permission rows (global permissions + individual category permission configurations), the API will not allow the role's permissions to be expanded in the response (currently throws an HTTP 416).

What would be a good way to provide the ability to read these complex permission setups with the /roles endpoint?

**Comment by charrondev** [comment]
@initvector Could we just get rid of the count entirely? This endpoint is protected by the `Garden.Settings.Manage` permission so I don't see the need for pagination here. No potential for DoS.

**Comment by initvector** [comment]
I don't think the limit is there to protect against *intentional* DoS. Sites with particularly complex permission setups have the potential to see real performance impacts if this endpoint isn't used sparingly. That said, in a *very brief* survey, the most complex permission setup I came across had about 600 permission rows on a few roles. The basic massaging of permission data this endpoint does would probably not see a tremendous spike in resource usage between 100 and 600 rows. So, while I'm hesitant to completely uncap the permissions that can be returned, I'm very open to increasing this limit to something much higher, while still providing some semblance of protection.
