### ISSUE TITLE
API error message contain artifacts

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6168]
I don't know where the 1 and the . come from but we need to get rid of them!

https://dev.vanilla.localhost/api/v2/discussions/?dateInserted=[2018-01-01,2017-01-01]
```
{
  "message": "End of 1dateInserted. range must come after beginning.",
  "status": 400,
  "errors": Array[1][
    {
      "field": "",
      "code": "invalid",
      "path": "dateInserted",
      "message": "End of 1dateInserted. range must come after beginning."
    }
  ]
}
```

**Comment by initvector** [comment]
Fixed with:

1. https://github.com/vanilla/garden-schema/pull/28
1. https://github.com/vanilla/garden-schema/pull/29
