### ISSUE TITLE
Formatting Signatures with IPB Format  "Target=_blank"

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6173]
When IPB format is used in signatures, "target= "_blank" is not being filtered from the signature.
We currently filter "target= "_blank" in comments and discussions as this is a minor security concern.

**Comment by linc** [comment]
Issue moved to [vanilla/addons #577](https://github.com/vanilla/addons/issues/577) via [**ZenHub**](https://www.zenhub.com/)
