### ISSUE TITLE
Add tests for pagination utilities for APIv2 endpoints

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6174]
We currently have no real test coverage of the following methods that are generally used for pagination in our API endpoints:

- `offsetLimit()`
- `ApiUtils::morePagerInfo()`
- `ApiUtils::numberedPagerInfo()`

**Acceptance criteria**

Obtain test coverage for these methods.

**Comment by charrondev** [comment]
I've re-worked the issue to have more clear acceptance criteria in order to pay down this technical debt.

**Comment by tburry** [comment]
These functions now have test coverage so I'm going to close.
