### ISSUE TITLE
PermissionModel->getJunctionPermissions() returns broken permissions when there is more than one row with no RoleID

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#6180]
Permissions getJunctionPermissions() returns broken permissions when there is more than one row with no RoleID in the Permissions table. When the method gets the default junction permissions it gets all the permission rows where RoleID = 0 and the JunctionTable is the junction that you are looking for (say Category). For some reason there can be more than one row with the same JunctionTable and no RoleID and no Permissions assigned to it (also, the JunctionID seems to always = -1). If there is, it will return these empty permissions instead.

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.permissionmodel.php#L555

**Comment by linc** [comment]
You tend to write what the actual title should be as the first sentence in issues, I'm noticing.
