### ISSUE TITLE
[APIv2] Clarify "format" parameter for Discussions, Messages, and Comments

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6191]
It seems like the format is meant to be the editor format. We should make this clearer by

- Making this key an Enum. We only have a few editor types.
- Adjusting the description. We currently have "The input format of the record." This would be better as "The format of the initial editor input for the record."
- Making sure this shows in the /discussions endpoint as well. Currently it has no description in the parameters model (and therefor doesn't show up in the Example) and doesn't show up in the Response model or value at all.

**Comment by DaazKu** [comment]
- We could make this en enum but it is possible to install more format in Vanilla. I suggest creating a separate an issue for this.
- The description reflects exactly what the fields is used for. It is the input format of the record. I think that putting references to the editor in the description is not correct. It binds the description to one perspective in particular. 
- The response is always in HTML so there is no need to show what the "input format" was for that record.

On a side note, this issue should have been flagged with the R&D notes label and we could have discussed it during our R&D meeting.

**Comment by tburry** [comment]
I think removing the format from output formatted endpoints and only including it in get_edit would be a good idea. Making an enum is something we could do, but I know right now that has to be extendable and we don't have a really nice way of doing that right now. Perhaps we make it a function call and add an extension point later.

**Comment by Charrondev** [comment]
So after discussion it seems that the format and the original content will be only be accessible in get_edit as @tburry posted above. All other endpoints will return only the html. Maybe in the future we can offer the format and original content through an expand parameter, but we shouldn't need it right now.
