### ISSUE TITLE
Phase Out Garden.SignIn.Allow permission

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6198]
The `Garden.SignIn.Allow` permission is a common source of confusion for users configuring permissions on a role. Its primary purpose seems to be determining if there is an active user session. If the current user has the `Garden.SignIn.Allow` permission, they must not be a guest. However, there are better methods of determining whether or not a user is logged into the site (see [`Gdn_Session::isValid`](https://github.com/vanilla/vanilla/blob/aec797045f14cafb38716b85f9063dbc80429ee9/library/core/class.session.php#L407)). That said, it is not a simple undertaking to remove the seemingly-redundant permission. The primary roadblock is its prolific usage.

Since the permission cannot simply be removed, it'll have to be phased out. One possible solution:

1. Remove the permission from the UI.
1. Remove the permission from the database.
1. Make the permission a virtual one. Permission checks for `Garden.SignIn.Allow` will return the result of `Gdn::session()->isValid()`. Maybe a deprecation notice should be thrown.
1. Addons (including Vanilla) should be reviewed and references to `Garden.SignIn.Allow` should be removed and replaced with checks using `Gdn::session()->isValid()` where possible \*.
    1. New permissions defaulting to `Garden.SignIn.Allow` should instead default to true.
    1. A function to redirect a user to sign-in based on the result of `Gdn::session()->isValid()` can be used to substitute some `Garden.SignIn.Allow` checks where a redirect would normally occur.

*\* The API v2 endpoint standard requires a permission check to be performed at the top of every action. This necessitates a permission like `Garden.SignIn.Allow` when all that needs to be verified is the user is signed in.*

**Comment by DaazKu** [comment]
I think that removing it from everywhere and creating a shim in all `permissions()` methods would be good enough.
