### ISSUE TITLE
Tabnabbing vulnerability on links with target="_blank"

### ISSUE THREAD

**Issue by guih** [vanilla/vanilla#6205]
Hey there,

It would be nice to have automated prevention against tabnabbing vulnerability for forum users' provided links.

To prevent that, it would have to detect links with `target="_blank"` and add `rel="noopener"` and maybe `rel="noreferrer"`.

Here's more info about the vulnerability and how to fix it: https://dev.to/ben/the-targetblank-vulnerability-by-example

**Comment by Charrondev** [comment]
As far as I can see here, we no longer use target="_blank" on user content. It is no longer placed by default by any of our editors, and it is explicitly stripped out by our HTML filterer unless you change the config setting `Garden.Html.BlockedAttributes`.

https://github.com/vanilla/vanilla/pull/5261

**Comment by guih** [comment]
Thanks @Charrondev!
Yeah, it makes total sense.
Maybe it could be some long-term future improvement alongside with `Garden.Html.BlockedAttributes` setting.

**Comment by Charrondev** [comment]
This still applies to the LinkTypes addon.

**Comment by Charrondev** [comment]
## Notes

- Audit for any internal use of window.opener (especially with sign in links) to be sure they aren't broken (Look for .PopupWindow class).
