### ISSUE TITLE
Move User information under the 'extra' index in SSOData

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6217]
> Todd: Currently everything is flat on one level. We want to put all user's information under the "extra" index. `$ssoData['extra']['email']`

**Comment by DaazKu** [comment]
My understanding of this is that we want to create a separation between the providers data and the "sensible fields" authenticatorName, authenticatorID, authenticatorIsTrusted.
Instead of moving all the other fields under a specific index which would complicate the usage of the array like object I suggest the following change:

(Not tested but it would be something like this)
```php

    /**
     * SSOData constructor.
     *
     * @param array $providerData
     * @throws \Exception If a non associative array is passed to the constructor.
     */
    public function __construct($authenticatorName, $authenticatorID, $authenticatorIsTrusted, array $providerData = []) {
        if (array_key_exists(0, $providerData)) {
            throw new \Exception(__CLASS__.' can only be initialized with an associative array.');
        }
        $this->authenticatorName = $authenticatorName;
        $this->authenticatorID = $authenticatorID;
        $this->authenticatorIsTrusted = $authenticatorIsTrusted;

        foreach($providerData as $name => $value) {
            $this[$name] = $value;
        }
    }

    /**
     * Set property on this object.
     *
     * @throws \ErrorException If you try to set an immutable field.
     * @param mixed $offset The offset to assign the value to.
     * @param mixed $value The value to set.
     */
    public function offsetSet($offset, $value) {
        if (in_array($offset, $this->immutableFields)) {
            throw new \ErrorException("$offset cannot be modified after initialization.");
        }
        $this->$offset = $value;
    }
```

By doing this we will ensure that:
- SSOAuthenticators set the values properly 
- Providers data will never be able to overwrite the sensitive fields
- It will be impossible to change the value of these property once the object has been initialized.

**Comment by tburry** [comment]
I'd rather see this:

1. The object has properties for the authentication provider.
2. The object has an array for the user.
3. Separate methods are used to get/set the user and authentication provider fields. The user object will have specific methods for our common fields (id, name, email, photo) and a generic method to set other fields.
