### ISSUE TITLE
Groups breaks the swagger addon (generated API Docs)

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6224]
Enabling the groups addon seems to prevent the swagger addon from loading the APIv2 documentation. Hitting the endpoint `/api/v2/swagger` returns 

```json
{
    "message": "Argument 1 passed to GroupsHooks::discussionSchema_init_handler() must be an instance of Garden\\Schema\\Schema, instance of DiscussionsApiController given",
    "status": 0
}
```

This seems to have been introduced by this PR https://github.com/vanilla/vanilla/commit/918febe8c35dc8c16d0af9fbddd4590d16c14330

**Comment by initvector** [comment]
This was due to a change in core that the Groups addon was being updated for. That Groups PR has now been merged.

Closed by vanilla/internal#1305
