### ISSUE TITLE
Need to update Vanilla logo to most recent one

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#6229]
The following logos are out of date and need a look at by Dan

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/design/images/vanilla-logo-46px@2.png

https://github.com/vanilla/vanilla/blob/master/applications/dashboard/design/images/vanilla-logo-46px.png

**Comment by danmaitland** [comment]
Ok here are both those logos using the same names.
![vanilla-logo-46px](https://user-images.githubusercontent.com/17601564/33889154-414ee842-df1d-11e7-8903-3f870d93942a.png)
![vanilla-logo-46px 2](https://user-images.githubusercontent.com/17601564/33889161-460f3f6c-df1d-11e7-83d4-27d06257faa0.png)

**Comment by adrianspeyer** [comment]
See https://github.com/vanilla/vanilla/pull/6230
