### ISSUE TITLE
OS permissions audit neeed on Vanilla-generated files

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6254]
PHP's default file permissions are wide open. For example, the default file mode for [`mkdir`](http://php.net/mkdir) is 777. Vanilla should strive to tighten these permissions and explicitly define the file mode to at least 775 for directories and 664 for files.

An audit should be performed on files and directories created by Vanilla to verify their permissions are properly limited, within reason.

**Comment by R-J** [comment]
Still a problem in Vanilla 2.8

Vanilla runs perfectly fine with 775 on
cache/
uploads/
conf/config.php

and 755 for the rest.

**Comment by charrondev** [comment]
@R-J I think there is some confusion on this issue (it could do to be better specified). This issue specifically is not about the file-system permissions in the source code, it's about file-system permissions in files and directories created by vanilla's PHP-FPM process (eg. conf, cache, etc).

You're issue was about our OSS build tool resetting file permissions to 777. That should be resolved in https://github.com/vanilla/vanilla/pull/8888 and the proper permissions should be in all OSS releases going forward.
