### ISSUE TITLE
Upgrade from 2.3 to 2.5 fails

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#6272]
Version 2.3 had a [SettingsController](https://github.com/vanilla/vanilla/blob/release/2.3/applications/vanilla/controllers/class.settingscontroller.php) in the vanilla application folder. As long as that file exists, several sections of the dashboard are not accessible.
After deleting that file and running /utility/update, everything was okay for me.

**Comment by linc** [comment]
Updated the upgrade instructions per your suggestion in that discussion. I don't see a good workaround that doesn't involve manually removing that file.

**Comment by R-J** [comment]
The main problem is that removing files during the normal update is not possible. But what about kind of "deprecating" files before removing them from packages by leaving a file with just a comment like so:

~~~
<?php
/**
 * DEPRECATED: Settings controller
 *
 * This class has been removed in Vanilla version 2.4
 */
~~~
