### ISSUE TITLE
YouTube embed eats 'related video' suppression parameter

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#6358]
Appending `?rel=0` to a YouTube URL suppresses "related videos" from showing at the end of videos. Our current parsing eats this.

There are a number of regression tests that must be manually checked when making changes to this code. See in the inline documentation around it.

**Comment by DaazKu** [comment]
We should take the time to unit test those changes.

**Comment by tburry** [comment]
The function in Gdn_Format gets the full URL so we can look for the parameter and pass it through to the embed. Make sure to use parse_url() and not a regex for the rel=0.
