### ISSUE TITLE
Switching to caching permissions via memcached instead of GDN_User.Permission causes existing database-cached permissions to be locked in place

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6359]
## Issue

Column GDN_User.Permissions does not get cleared after a new role or category is updated causing old permissions to get locked in place.
This field is currently getting cleared when caching isn't enabled.
[class.usermodel.php#L4765](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/models/class.usermodel.php#L4765)

**Comment by initvector** [comment]
I can confirm permissions cached in the `User.Permissions` column aren't wiped out when an actual caching mechanism, like Memcached, is being used. However, permissions shouldn't be loaded from that `User.Permissions` column when the other caching mechanism is loaded, either. The field would still hold the old data, but the user's actual permissions should be loaded from the caching system (e.g. Memcached).

To test this, I assigned a single role to a user (Member). I signed in as the user and observed the permissions of the row in `User.Permissions`. I enabled caching with Memcached. I signed in as an administrator user and changed the Member role to remove the `Garden.Email.View` permission. I checked the `User.Permissions` column for my test user's row and confirmed the field was not updated. I put a breakpoint just before dispatching starts in Vanilla's index.php and observed the `permissions` property of `Gdn_Session` for my test user. While the `Garden.Email.View` permission was still in the user's `User.Permissions` column, the permission __*was not*__ present in the actual permissions array for the user on the site.

When recreating this issue, did you encounter the behavior with a particular permission check or permission?

### Relevant lines:
* [Call to `UserModel::clearPermissions` in `RoleModel::save`](https://github.com/vanilla/vanilla/blob/843f23a5729fc4257b4b72e874f9e1d6105ec479/applications/dashboard/models/class.rolemodel.php#L618)
* [Database update skipped in `UserModel::clearPermissions` if caching is enabled](https://github.com/vanilla/vanilla/blob/843f23a5729fc4257b4b72e874f9e1d6105ec479/applications/dashboard/models/class.usermodel.php#L4772)
* [`UserModel::getPermissions` returning permissions from the cache (e.g. Memcached) if available](https://github.com/vanilla/vanilla/blob/843f23a5729fc4257b4b72e874f9e1d6105ec479/applications/dashboard/models/class.usermodel.php#L4803)
* [Permissions being set in `UserModel::getSession` with `UserModel::getPermissions`](https://github.com/vanilla/vanilla/blob/843f23a5729fc4257b4b72e874f9e1d6105ec479/applications/dashboard/models/class.usermodel.php#L1746)
* [`Gdn_Session::start` setting up its permissions by referencing `UserModel::$Permissions` after invoking `UserModel::getSession`](https://github.com/vanilla/vanilla/blob/843f23a5729fc4257b4b72e874f9e1d6105ec479/library/core/class.session.php#L435)

**Comment by dannimajdalani** [comment]
When this was tested, the user had no permission on a specific category in GDN_User.Permissions, 

That user was not receiving on-site notifications from @mentions in that category that he didn't have permission on, once GDN_User.Permissions was cleared, the user got his @mention on-site notifications.
