### ISSUE TITLE
"Something has gone wrong." page when trying edit roles.

### ISSUE THREAD

**Issue by starikan** [vanilla/vanilla#6361]
Fresh install version 2.5. After install there was all great. I edited the roles with my needs. But after I get Something has gone wrong page when click edit or add role on ?p=/dashboard/role page. I.e. ?p=/role/edit/16

All plugins that I added I disabled.

**Comment by charrondev** [comment]
From the release 2.5 notes:

> If your forum still uses URLs including ?p=, support for this URL structure has ended. Follow these steps to switch to the simpler format:
> 
> 1. Confirm your server is setup to handle rewrites. On Apache, using the .htaccess file provided will accomplish this. Additional setup is required on nginx and other platforms.
> 2. Test whether it is working by visiting /discussions - if you see a discussions list (rather than a 404), it is likely setup correctly.
> 3. Open /conf/config.php and find the line with $Configuration['Garden']['RewriteUrls'] = false; and delete the entire line.
> 
> Your site should immediately switch to “pretty” URL paths instead of using the ‘p’ parameter. If there is a problem, re-add the line to your config and do further troubleshooting.
