### ISSUE TITLE
Fix docs links in social connect plugins

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6370]
Relevant https://github.com/vanilla/docs/pull/198

In this repo:
- Facebook
- Twitter
- Google Plus

**Comment by DaazKu** [comment]
As per https://github.com/vanilla/docs/pull/198#issuecomment-355574675

<img width="1083" alt="screen shot 2018-01-15 at 11 25 23 am" src="https://user-images.githubusercontent.com/2412909/34952177-dfcd939a-f9e6-11e7-8232-6df0902f9719.png">
