### ISSUE TITLE
dbencode/dbdecode is now incompatible with PHP objects

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6373]
We found out one place (see #6371) where a PHP object was stored in the database. Our new encoding functions do not work with objects.

We need to either shim the function to handle PHP objects properly or audit our codebase to pre serialize and post unserialize them.

**Comment by charrondev** [comment]
- The OpenID plugin has been deleted.
- `dbencode`/`dbdecode` now use JSON serialization instead of `serialize`.
