### ISSUE TITLE
Punctuation in usernames creates broken links when mentioned

### ISSUE THREAD

**Issue by cbeckley13** [vanilla/vanilla#6377]
Specifically ones that have a period. For example, "first.last". When I attempt to mention a user within a comment like @first.last, then the link to that user's profile is broken. It only links to @first which is not a user (or may be another user). I know that I could use @"first.last" to make the link to that user work properly, but when a user types @fir... and the pick list open and they choose a name expecting it to link to that user, then it's too late to use the quotes as it is already a broken link. Of course we can add instructions to do this and hopefully most will remember, but I was hoping there was a way to either stop new registers from using periods or a way to allow user names with periods in them to work in this manner automatically.

**Comment by DaazKu** [comment]
What version of Vanilla are you using? This has been fixed a year ago:
https://github.com/vanilla/vanilla/pull/5076

The auto complete now quotes any name that doesn't contain only "word" letters or "-"

**Comment by DaazKu** [comment]
> I was hoping there was a way to either stop new registers
As a side note this is possible by changing `Garden.User.ValidationRegex`.
https://github.com/vanilla/vanilla/blob/f30141c503422b84040c26463fffa18c0ea3a4c5/library/core/functions.validation.php#L246-L263
