### ISSUE TITLE
Backwards compatibility issues with application controller routing 

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6378]
When attempting to reach a method with a name matching an existing controller, on a controller matching the name of an enabled application, the index of the controller the method is named after will be triggered. This was not the case in Vanilla <= 2.3. This issue appears to have been introduced with dispatcher logic refactoring in #4158 and #4160.

### Example
An application named Widgets has a `WidgetsController` class with a `categories ` method. In Vanilla 2.3, you could trigger `WidgetsController::categories` by visiting /widgets/categories. This was due to `Gdn_Dispatcher::analyzeRequest` [first performing a check for `FooController` under the Widgets application](https://github.com/vanilla/vanilla/blob/9b83468e7a0ed731e4e1f5645079d22cb4b946fd/library/core/class.dispatcher.php#L528), then falling back to [looking for `WidgetsController`](https://github.com/vanilla/vanilla/blob/9b83468e7a0ed731e4e1f5645079d22cb4b946fd/library/core/class.dispatcher.php#L532).

Controller lookups are now performed with a single call to `Gdn_Dispatcher::findController`. This method was also updated in the aforementioned PRs. The example URL from above now pops "widgets" off the URL, because it matches an application, and grabs the following segment (categories) as the controller. A simple `class_exists` check is performed on the controller segment. The result is /widgets/categories displaying the Vanilla categories page, because the Vanilla application has a `CategoriesController` class. To trigger the proper method now, you would use /widgets/widgets/categories.

### Recreate
1. Create a controller under an application and name it the same thing as the application (e.g. `WidgetsController` under the Widgets application).
1. Add a method on the new controller that matches the name of an existing controller (e.g. "discussions" or "categories").
1. Attempt to trigger the new method by only using the controller and method names (e.g. /widgets/discussions).
1. The index of the controller chosen from step two should be displayed.

**Comment by linc** [comment]
The workaround is basically "don't name your application the same thing as one of its controllers".

The alternative workaround is "don't name a method to overlap with a common controller name" which I think is a bit more difficult.

I'd be keen to hear from @tburry on whether he thinks we'll fix this. If we don't fix it soon, it probably won't be worth fixing since everyone will need to work around it.

**Comment by charrondev** [comment]
Hah! https://github.com/vanilla/vanilla/pull/8312

I'm going to sum this up as _don't use `Gdn_Controller` & `Gdn_Dispatcher` any more_. If you do follow the rule specified by @linc here.

New solutions are `Garden\Dispatcher` & `Vanilla\Web\Page`.
