### ISSUE TITLE
Add basic ability to follow to the categories

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6397]
An overview of the "category following" feature can be found on the parent issue: #6026

- Add non-static `follow` method to `CategoryModel`.
- Users can follow or unfollow a category.
- Only signed-in users can follow a category.
- You can only follow categories where `DisplayAs` = discussions.
- The category following UI should display conditionally based on the `Vanilla.EnableCategoryFollowing` config setting. There should be a way to toggle this setting in the dashboard. The config and control will be added as part of this issue. The subsequent UI tasks for this feature will rely on the config being available.
- Add PUT /api/v2/categories/:id/follow
    - Given a category ID and a boolean follow field, the current user can follow or unfollow the specified category.
- Add API unit tests to verify functionality

**Comment by angeloudy** [comment]
I can see you've added PUT /api/v2/categories/:id/follow to the API but only for the user with a token accessing the API, but we really need to be able to set this through the API for lots of users (we are importing them from elsewhere). Is there a variation of this API for this purpose? Something like:

`PUT /api/v2/users/:id/categories/:id/follow`
