### ISSUE TITLE
Add filter dropdown to categories page to show followed categories or all

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6402]
Add filter dropdowns to the application to switch followed categories and all. The new base theme has this functionality planned already, but the current base theme is going to need some work later and ideation will need to be updated at that time.

The "followed" category list will be displayed as flat.

**Comment by slafleche** [comment]
For discussions equivalent, see https://github.com/vanilla/vanilla/issues/6409

**Comment by slafleche** [comment]
Using markup from https://github.com/vanilla/vanilla/issues/6414

**Comment by slafleche** [comment]
Markup and CSS ready to go. Put on hold until we're ready to "wire it up".
