### ISSUE TITLE
Add filter dropdown to discussions page to show followed categories or all

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6409]
Similar to https://github.com/vanilla/vanilla/issues/6402, but for discussions.

Add filter dropdowns to the application to switch followed categories and all. Needs to work for Modern and Table layouts.

**Comment by slafleche** [comment]
Using markup from https://github.com/vanilla/vanilla/issues/6414

**Comment by Charrondev** [comment]
Is this already done?
