### ISSUE TITLE
Rich Editor - Allow @mentions

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6412]
The rich editor should allow for `@mentioning` users. The `@` symbol have inline lookup autocompletion. The created mention should be saved with the username, link to the profile, and userID.

**Comment by slafleche** [comment]
Should also use popper.js. 
Markup will come from: https://github.com/vanilla/vanilla/issues/6408

**Comment by Charrondev** [comment]
Closing in favor of #6588
