### ISSUE TITLE
Rich Editor - Investigate Emoji Support

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6427]
The rich editor should support rich emojis and have a picker on the desktop for selecting these emojis.

Something that out of the box matches what we're looking for the picker is the [onesignal emoji picker](https://github.com/OneSignal/emoji-picker). We'll need to audit it though.

Whether or not this is a 3 or 8 point item probably depends on whether or not that picker is good enough.

**Comment by slafleche** [comment]
So looking at this demo, it looks like they're not native emojis, it's not accessible and their markup would need to be reworked to avoid conflicts with theme styles...

**Comment by slafleche** [comment]
This repo doesn't have a lot of popularity, but maybe something "lower level" like this would be less problematic in the long run... https://github.com/amio/emoji.json

**Comment by slafleche** [comment]
This one's more popular: https://github.com/milesj/emojibase

**Comment by Charrondev** [comment]
If you look at the demo the first 2 examples are of input fields that don't support unicode input. It uses sprite-sheets as a fallback.

The 3rd example uses real emojis. I agree though that we're not going to be able to use that one. That emojibase library looks pretty solid. I'm renaming this task and we can subtask it from here.

**Comment by slafleche** [comment]
I made a compatibility task for the future. I asked Todd and as a first iteration, we can just have native emojis in a scrollable list. In the future we can offer fallback images and categories, maybe even a search. But as a first step, let's just have a working list of native ones.

**Comment by slafleche** [comment]
I think we should use this library for having access to the emoji list, it also has some utility functions that may be useful: https://github.com/milesj/emojibase

As a fallback, I like Twitter's solution: https://github.com/twitter/twemoji

We can use these as a first iteration to make a simple emoji picker, one big scrollable dropdown, with all emojis listed in there.
