### ISSUE TITLE
New versions of MySQL or MariaDB have unrecognized timestamp default

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#6483]
I updated my localhost MySQL and am not getting this on structure:

```sql
alter table `GDN_UserAuthenticationToken`
-- [Existing: `Timestamp` timestamp not null default CURRENT_TIMESTAMP, New: `Timestamp` timestamp not null]
change `Timestamp` `Timestamp` timestamp not null;
```

It looks like timestamp columns are getting a default of CURRENT_TIMESTAMP which makes the database structure think columns need to be altered. Leaving this as is seems to work okay, but will trigger alter tables on structure which could be a significant problem.

**Comment by DaazKu** [comment]
Related issue: https://github.com/vanilla/vanilla/issues/5763
PR that introduced the change https://github.com/vanilla/vanilla/pull/6376
