### ISSUE TITLE
Rich Editor - Paragraph Level Formatting toolbar

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6501]
Implement the UI of the paragraph level toolbar. This should always be on the beginning of the currently selected line.

It's buttons should have the following options:

- H1
- H2
- code-block
- blockquote

**Comment by slafleche** [comment]
The paragraph level formatting toolbar needs to work more like a "radio button" than "checkboxes". The only difference is you can have nothing selected, which is implicitly a regular paragraph.

**Comment by Charrondev** [comment]
Closed by #6648
