### ISSUE TITLE
Rich Editor - Server side rendering of spoiler blot

### ISSUE THREAD

**Issue by Charrondev** [vanilla/vanilla#6517]
- Output should be compatible with our existing spoiler.

**Comment by slafleche** [comment]
I'm going to close this task because it's redundant 

I've split up the embed elements as follows:

HTML/CSS: https://github.com/vanilla/vanilla/issues/6508
Blots: https://github.com/vanilla/vanilla/issues/6603
Server side rendering: https://github.com/vanilla/vanilla/issues/6605
