### ISSUE TITLE
Pagination with rel=“next” and rel=“prev”

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6522]
According to this Google blog post, we should be adding links with "next" and "prev" links in the header when we have pagination.

https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html

**Comment by DaazKu** [comment]
Related https://github.com/vanilla/vanilla/issues/6480
Here is the RFC btw https://tools.ietf.org/html/rfc5988#page-7

**Comment by tburry** [comment]
This can be done in the PagerModule itself. It can look for Gdn::controller()->Head and add the tags upon rendering. Kind of an odd way to do it, but it will catch every page that has pagination.

**Comment by DaazKu** [comment]
There's a new WebLinking class introduced in https://github.com/vanilla/vanilla/pull/6537
We can inject it (or call the container) and call `addLink()` on it (from the pager module) and make sure that we do a `setHeader($webLinkingObject->getLinkHeader);` before rendering the page.

**Comment by DaazKu** [comment]
Page one should always be / and not p1. Or there should be a canonical to make sure that we do not duplicate the page.

**Comment by armstrongkatie** [comment]
TW task for Ryan to log the hours for this prioritized issue (paid service): https://vanillaforums.teamwork.com/#tasks/8484531
