### ISSUE TITLE
Rich Editor - Compatibility with Sphinx search

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#6534]
The rich editor stores its content as JSON which means that Sphinx will have a hard time crawling the content. This needs to be addressed or else the rich text posts will not be searchable.

I recommend augmenting the storage of the rich text posts to include a plain text version of the post. Sphinx should be able to crawl the plain text. You will probably have to come up with a solution to obscure the JSON from sphinx so that every rich text isn't returned when I search for example "attributes".

**Comment by charrondev** [comment]
I've done some testing and sphinx is having difficult with the `\n` escaped newlines found throughout the inserts.

Additionally JSON keys get indexed everywhere, such as `insert`, `attributes`, and various embed keys.
