### ISSUE TITLE
Spec out handling of a React component factory

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6536]
Create a `ComponentRepo` class which can register components into a global repository so that they can be overridden and fetched dynamically.

**Functions needed**
- `getComponent(string): React.Component`
- `setComponent(string, React.Component)`
- `overrideComponent(string, React.Component)`

This class needs to be a Singleton and should also be exposed globally.

Should be to mount components dynamically anywhere with the attribute `data-component: "ComponentName"`.

**Comment by tburry** [comment]
This is done in #6865.
