### ISSUE TITLE
Replace image cropper with a better implementation

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6547]
**Describe the Feature**

Our current image cropper is rather fragile, and not really responsive. It requires 1:1 pixel mapping to work properly and isn't really suited to the task of a cropping a medium/high res photo on a smaller device. We should replace it with something better.

**User Story**

As a user with profile upload permission:

- I want to upload photos from my mobile device.

As a theme developer

- I want to be able to adjust the space the image cropped takes up.

**Acceptance Criteria**

- New cropper is resizable.
- Cropper forces square photos.
- Cropper works on touch devices.

**Comment by slafleche** [comment]
Agreed, there's no good way to fix the existing editor to be responsive.

**Comment by charrondev** [comment]
This is probably the biggest wart in our product on mobile.
