### ISSUE TITLE
#latest jumping to next page rather than last read comment. 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#6554]
#latest should take you to the last comment that you read in the thread. In my memory  this used to take you to the last comment in the thread at the time that you read it. Currently it exhibits an odd behavior, from Val's testing: 

- I open a new thread (for me) that has several pages of comments already (there are 30 comments per page)
- I open the thread and read the discussion, and start scrolling through page 1 of comments.
- I scroll about half way down the page - say to comment #15
- I go back to the categories page, tralala do other things
- I go back to that first thread, and instead of opening on page 1, I'm brought to page 2, comment 31
and this behavior is consistent, if I repeat the same steps, the next time i got back to the thread, I'm on page 3, comment 61, and the next time page 4, comment 91.

Able to replicate this easily on PA. 

We recently made adjustments to some of this behavior here: https://github.com/vanilla/vanilla/pull/6244 but this change doesn't seem to be in effect.

**Comment by DaazKu** [comment]
> Work as intended
