### ISSUE TITLE
Addon Key for Toggle

### ISSUE THREAD

**Issue by austins** [vanilla/vanilla#6559]
For Vanilla 2.5, it looks like the _addon name_ is being used for the toggle slug on the `/settings/applications` page. For example, I have an app called "Basic Pages" and the toggle link is `/settings/applications/all/Basic%20Pages`. This causes an "Application not found." error.

Should the _addon key_ be used for the toggle slug instead? It would then be `/settings/applications/all/basicpages`, which will allow the addon to be looked up successfully. Even so, there seems to be more underlying code in the enable/disable application methods that prevent it from successfully toggling.

**Comment by Charrondev** [comment]
Are you using the [addon.json](https://docs.vanillaforums.com/developer/addons/addon-info/) format for defining your application's metadata?

**Comment by austins** [comment]
Yes, I'm using the addon.json format like so:

~~~
{
  "key": "basicpages",
  "name": "Basic Pages",
  "description": "Basic Pages is an application that provides a way for you to create basic public pages for static content in Garden.",
  "version": "2.1.8",
  "url": "http://vanillaforums.org/addon/basicpages-application",
  "license": "GNU GPL v2",
  "authors": [
    {
      "name": "Austin S.",
      "homepage": "https://github.com/austins"
    }
  ],
  "icon": "basicpages.png",
  "type": "addon",
  "require": {
    "vanilla": ">=2.5"
  },
  "setupController": "setup"
}
~~~

**Comment by charrondev** [comment]
@austins This issue doesn't have anyone internal that seems to care for it. I'm not going to close it but I'd just recommend not using applications anymore.

Addons should be able to be converted to a plugin with a few minor changes and setting the priority in addon.json to be 10.
