### ISSUE TITLE
Rich Editor - Sanitize paste

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6563]
Remove all styles from pasted text in the editor. 

Later we might improve the editor and recognize pasting in images or video, but as a first step just get rid of stylings.

**Comment by Charrondev** [comment]
A little bit of digging shows me that by default quill attempts to mimic the styles of whatever we have pasted. This is actually not entirely undesirable, but we would only allow this using strictly sanitized html with whitelisted classes. Definitely not any inline styles.

**Comment by Charrondev** [comment]
https://github.com/quilljs/quill/issues/640

**Comment by Charrondev** [comment]
The various garbage styles that we're getting deleted on paste are now being stripped.
