### ISSUE TITLE
Rich Editor - Optimize Emoji Picker

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6575]
The first iteration of the emoji toolbar was to simply list out all the emojis in the menu. The emoji list is over a thousand, so it takes a second or two to render. We should have some sort of lazy loading for this component.

**Comment by Charrondev** [comment]
There are a few things we could do to optimize this.

- Dynamically load the emoji list with a dynamic `import()` call.
- Use [react-virtualized] to re-use dom nodes on scrolling.
- Do the initial render as soon as the as the json is returned. Use CSS to hide/show the menu. The biggest time sync is the initial render, and even if we speed it up there's no need to un-render the list until that editor instance is destroyed.

**Comment by slafleche** [comment]
If we use react-virtualized and we only show 1 tab at a time is there a point to hiding/showing the menu with CSS? It should be pretty efficient.

**Comment by slafleche** [comment]
This will be particularly important when we use Twemoji with fallback images.... it's a LOT of image to download on what's likely an older machine.

**Comment by slafleche** [comment]
We'll have categories. Here's the list we'll use for the first version:

- smileys-people
- animals-nature
- food-drink
- travel-places
- activities
- objects
- symbols 
- flags

**Comment by slafleche** [comment]
- Look up "pure components" for emoji component
- Use emoji for key instead of number (for filtering)
- Look up how facebook handles categories (possibly use anchors instead of tabs)
