### ISSUE TITLE
Rich Editor - Emoji backwards compatibility

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6577]
We've decided to use https://github.com/twitter/twemoji for backwards compatibility. We need to implement it with our emoji picker component.

**Comment by Charrondev** [comment]
To flesh this out a little bit more, twemoji will need to be run in 3 places. 

- On the emoji flyout (inside of the react component).
- On the quill emoji blots (inside the blot).
- On the rendered output of already created posts.

**Comment by slafleche** [comment]
Duplicate: https://github.com/vanilla/vanilla/issues/6531
