### ISSUE TITLE
Accessibility - Alternate "close" HTML

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6579]
Going forward, we want to change the markup for close buttons in flyouts or modals. We need a way to get one or the other depending on the theme we're using.

**Comment by charrondev** [comment]
What exactly does this mean?

**Comment by slafleche** [comment]
The markup for the "close" buttons in Vanilla are anchor tags. I'd like to replace them with true buttons, but we need a strategy to not break older themes.

**Comment by slafleche** [comment]
The markup change is easy, the harder part is the strategy for updating the old markup. It shows up in a lot of places.

**Comment by charrondev** [comment]
We ended up just using the the `<CloseButton /> ` component for this.
