### ISSUE TITLE
Rich Editor - Can't get out of code block

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6582]
There's some improvements to be made for the codeblock styles in the editor

- [ ] Don't allow links or any other styles inside of code blocks
- [ ] Selecting any part of the code block and then clicking on the code block in the menu gets rid of the whole code block.
- [ ] If you select regular text AND a codeblock, styles will only affect the non code block elements
- [ ] If only the code block is selected, the only styling option you have is to remove the code block

- [ ] Allow to "arrow out" of the block (i.e. be able to arrow your way out of the block to continue typing next to it
- [ ] Allow to clicking next to the block to exit out of it
- [ ] Don't capture tabs (we might add an option to support tabs in the future)
- [ ] Proper space between inline code block and other letters. (no left space if it's the first element in a paragraph, no right space if it's the last element, but we want proper space between other words

**Comment by Charrondev** [comment]
Doing this is going to require a much better understanding or Quill and in particular it's parchment library. Parchment is not very well documented so I'm going to need to go through it and leave some comments along the way before I can do this properly.

I'm going to fork parchment into the vanilla org so I can make some issues.

**Comment by slafleche** [comment]
PR open for success criteria: https://github.com/vanilla/roadmap/pull/31

**Comment by Charrondev** [comment]
Closed by #6725
