### ISSUE TITLE
Rich Editor - Make generic flyout component

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6587]
This component will be used by the editor first, but it should be a generic component we can use anywhere in Vanilla.

We've already got some accessible flyouts in the editor, but we need to make them generic enough to be used anywhere and get that accessible functionality for "free".

Remember to put the flyout AFTER the toggle button to get the natural tab order working without any JS.

**Comment by charrondev** [comment]
Closing because the component exists now. https://github.com/vanilla/vanilla/blob/978119bdc451284b2cd4785e66319d3292152f7b/library/src/scripts/components/dropdown/DropDown.tsx
