### ISSUE TITLE
Rich Editor - @mention menu

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6588]
Add @mention menu to editor. It should behave very similarly to the current way the @mention works.

There's already markup for it in the /richeditorstyles page. Note that we want to use `<mark>` tags for the highlighted text from the search.

**Comment by Charrondev** [comment]
Addition: The created mention should be saved with the username, link to the profile, and userID. It will need a custom blot. The lookup should use the new APIv2 endpoint.

**Comment by charrondev** [comment]
Closed with #6412
