### ISSUE TITLE
Update Gdn_Controller breadcrumb microdata to JSON-LD

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6590]
We've had requests to update breadcrumb in Vanilla to use newer micro data format for SEO.

The proper format will be `JSON-LD`. `Vanilla\Web\Page` and `default-master.twig` implement this format properly. This would need to be brought back to `Gdn_Controller` and the old master view through the `HeadModule`.

**Context**

See:
- `Vanilla\Navigation\Breadcrumb`
- `Vanilla\Navigation\BreadcrumbModel::crumbsAsJsonLD()`

**Comment by charrondev** [comment]
I don't think this one is a won't fix. It's easy enough to bring back. In fact with https://github.com/vanilla/knowledge/issues/1190 getting a bunch of stuff into JSON-LD, we'll likely have a shared model for formatting this microdata that can be shared between `Gdn_Controller` and `Vanilla\Web\Page`

**Comment by x00** [comment]
google search console is now issuing warning over data-vocabulary.org depreciation
