### ISSUE TITLE
Rich Editor - Syntax highlighting for code blocks

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6612]
The rich editor's code block is missing syntax highlighting.

**Comment by Charrondev** [comment]
This is currently provided by a plugin (on the rendered HTML output). The plugin is Syntax Prettifier. 

- Do we still want to provide this syntax highlighting as a separate plugin.
- Do we consider in-editor syntax highlighting part of the MVP?
- Does the highlighting in editor and the highlighting in the rendered output have to be identical? This essentially means redoing our syntax highlighting plugin if that's the case.

**Comment by charrondev** [comment]
This might also be a good time to fix https://github.com/vanilla/vanilla/issues/7852
