### ISSUE TITLE
News and Updates is Blank

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#6613]
![image](https://user-images.githubusercontent.com/425366/36163078-46ddd974-10b6-11e8-8225-0f99b6b501c5.png)
There is no feed showing blog or news content in the Vanilla dashboard.

**Comment by Charrondev** [comment]
Hmm. This is something wrong with the vanilla open source forum. The news is normally fetched from here: https://open.vanillaforums.com/vforg/home/getfeed/news/5/extended. Now that is returning 404.

**Comment by Charrondev** [comment]
It seems to be an issue with the open feed central plugin. https://github.com/vanilla/community/tree/master/plugins/openfeedcentral

**Comment by adrianspeyer** [comment]
We moved the blog feed at some point and I could have sworn it was working. Not sure what happened, as the move happened in the fall (last year).

**Comment by adrianspeyer** [comment]
I should add, in the future, I'd love to have the "updates" be tied to a feed for the business version of Vanilla -- and the open source can keep the open source release issues. I am working on a new community for this in the near future and having that feed in our customer dashboards would be great!

**Comment by Charrondev** [comment]
The RSS feeds are still working. The issue seems to be in requesting them from the client side. Unless this is very high priority, it should be able to wait until next sprint.

**Comment by adrianspeyer** [comment]
@Charrondev as long as it gets sprinted, I'm cool. Just don't want it to get lost.

**Comment by linc** [comment]
Do we have a timeline on when this started?

**Comment by linc** [comment]
The issue is we moved the feed functionality from the vforg app to an addon. I'm not sure when it became a problem, because that change was made several months ago (for the 2.5 release, I think) and it's been working since then. I added a route to open.vanillaforums.com to correct the problem.
