### ISSUE TITLE
Advanced Editor in WYSIWYG with chrome browser: mouse right-click triggers an undo event when using lists

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6621]
## Details

Creating a discussion with any type of list(ordered, numbered..) and having advanced editor set to WYSIWYG while using chrome causes a mouse click to trigger an undo event.

### Creating a Discussion with a list, while using WYSIWYG and Chrome

![originaldiscussion](https://user-images.githubusercontent.com/31856281/36228103-3ac58ca4-11a1-11e8-9054-ba11ecafb32b.png)

### Right-Click Triggers UndoEvent

![undoevent1](https://user-images.githubusercontent.com/31856281/36228115-4705ba98-11a1-11e8-9bb9-ee691c2414b6.png)

### Right-Click again

![undoevent2](https://user-images.githubusercontent.com/31856281/36228126-530a3d00-11a1-11e8-9461-70c617e25156.png)

**Comment by Charrondev** [comment]
If this ends up being more complicated than 2 points, I'm going to punt it to the next sprint.
