### ISSUE TITLE
Search is crippling large sites

### ISSUE THREAD

**Issue by JReko** [vanilla/vanilla#6628]
When a site has a large amount of discussions and/or comments, multiple search queries will time out and cause the db server to go down.

Adding a check on user search for the number of rows in the discussion and comment tables to prevent this behaviour is a possible solution.

**Comment by tburry** [comment]
I think the solution here would be to add a table status call to ensure that the number of rows in the discussion or comment tables don't exceed a threshold. If any one of the tables exceed the threshold then show an error message with a clean message that support will immediately know about so they can go and enable sphinx.

This is a good measure for OSS too. The threshold can be removed or increased on such installations, but the protection is necessary.

**Comment by charrondev** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/9515
