### ISSUE TITLE
Rich Editor - Spoiler Blot

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6632]
The spoiler blot is more complex than the other types of embeds we have. We want the container to be uneditable, but the contents to be editable.

- [x] Fix blot to allow more complex html structure
- [x] Add button on top of spoiler to goggle it
- [ ] Write JS to toggle spoiler
- [ ] Create unique ID needed for `aria-controls` and `aria-controlledby` attributes (ties to https://github.com/vanilla/vanilla/issues/6586)

**Comment by Charrondev** [comment]
The requirements here are actually being discussed. After speaking with @tburry the spoiler will not be collapsable in the editor.

Proposal here:

https://github.com/vanilla/roadmap/pull/34/files

**Comment by Charrondev** [comment]
Closed by #6725
