### ISSUE TITLE
Rich Editor - Editing a Rich Editor post after the plugin is disabled

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6638]
The rich editor saves the "quill delta" in the old textarea, they show up in the drafts as json.

It's also an issue if you had a draft saved and you turn off the plugin, the draft gets loaded back as a delta, not as text.

**Comment by Charrondev** [comment]
So I guess there are 2 parts to this:

- Editing a rich editor post, without the plugin enabled (does it convert to plaintext?). @tburry What should this look like?
- Adding plaintext formatting for the rich editor.

**Comment by charrondev** [comment]
The final solution as implemented was to just load old posts with the old editor.

Converting of old formats to newer ones will be tracked here https://github.com/vanilla/vanilla/issues/6768
