### ISSUE TITLE
Pricing Page - word needs to be taken out

### ISSUE THREAD

**Issue by achowd** [vanilla/vanilla#6642]
https://vanillaforums.com/en/plans/ 

The word "emotify" comes up twice in the pricing plan features table. One of them needs to be taken out. 
![screen shot 2018-02-19 at 11 29 34 am](https://user-images.githubusercontent.com/36638451/36387908-41aeb21e-1568-11e8-8bb7-b1af74f579e6.png)

**Comment by Charrondev** [comment]
Thanks for the report. I'm going to move this issue into our internal repo for the website.
