### ISSUE TITLE
Cannot acces Home page of forum

### ISSUE THREAD

**Issue by TD89** [vanilla/vanilla#6643]
When accessing the home page of my fresh install on vanilla forums I get a page not found error. I turned on debugging in my config and that gives me this error message(see attached screen shot).
![vanillaissue](https://user-images.githubusercontent.com/14932520/36389996-4d75a952-156f-11e8-9b52-6fa9210d6ab1.PNG)

**Comment by charrondev** [comment]
Your Vanilla application isn't started properly. This certainly an installation problem. If you haven't figured this out already I'd recommend heading over to https://open.vanillaforums.com which is the recommended place for self hosting advice.
