### ISSUE TITLE
New /authenticate pages

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#6661]
This is for the new /authenticate/signin and /authenticate/connect pages. We want them to be complete and ready to launch before making them 100% active.

- Add /authenticate/signin
  - This endpoint will list all the possible authenticators and allow you to use them to sign in
  - Hitting /authenticate/signin/type[-id] will either show you the signIn form or redirect you to the SignIn url of the SSOAuthenticator.
  - Every SignIn buttons should redirect the user to /authenticate/signin/type[-id] with no parameters other than "redirect".
- Add /authenticate/connect/type[-id]
  - This endpoint will receive SSO Provider data.

**Comment by DaazKu** [comment]
See https://github.com/vanilla/vanilla/issues/6669 -> https://github.com/vanilla/vanilla/issues/6663 instead
