### ISSUE TITLE
OpenApi (Swagger) spec fails validation

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6670]
Our OpenApi spec does not currently pass validation. This means we can't generate API clients from it. I've done some research and we could generate some pretty good clients if we fix our validation errors.

Dropping our spec into the [swagger editor](http://editor.swagger.io/) reveals a host of errors, but it seems like it's mostly the same couple of errors over and over again.

It seems we're caught somewhere in between OpenApi 2 and 3. Because we return multiple values all over the place it would probably be beneficial to move to open api 3 and resolve all of these validation errors in the process.

**Comment by Charrondev** [comment]
A few of the common issues I found:

## Path parameters need must be required.

If a parameter has `"in": "path"` it must also have `"isRequired": true`

https://swagger.io/docs/specification/describing-parameters/
> In OpenAPI, a path parameter is defined using in: path. The parameter name must be the same as specified in the path. Also remember to add required: true, because path parameters are always required.

If it's really an optional path parameter you need a different endpoint description.

## Query params can only contain primitive types

https://swagger.io/docs/specification/2-0/describing-parameters/
> Query parameters only support primitive types. You can have an array, but the items must be a primitive value type. Objects are not supported.

We use an object in a query parameter with our datetime schema. We might want to validate that way, but we should kludge it to be a string for the output spec.

**Comment by charrondev** [comment]
Closed with https://github.com/vanilla/vanilla/pull/7541
