### ISSUE TITLE
Rich Editor - Ensure security without using HtmlLawed

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6674]
Since we are generating all HTML content ourselves on the server, we shouldn't need HtmlLawed. Instead we can strictly sanitize all content in the json sent to the server. Ideally this should be done in one pass initially so that no additional work is required afterwards.

Additionally automated tests with malformed and malicious json should be added that attempt XSS.

**Comment by initvector** [comment]
> charrondev commented:
> This might be a good place for some inspiration
>
> https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json
