### ISSUE TITLE
Theme compatibility for New Register and Login pages

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6681]
- [ ] Test for compatibility with themes
- [ ] Document when old or new pages should be used
- [ ] Alert theming, CSMs and support about new feature

**Comment by charrondev** [comment]
I'm closing this so we can start fresh with issues when we revisit this project. We'll likely start fresh on the frontend pages with `Vanilla\Web\Page` and dropping of previous theme compatibility on the pages.
