### ISSUE TITLE
Add category to expandable fields in discussions API v2 endpoint

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6685]
The discussions API v2 endpoint currently supports three expandable fields: `insertUser`, `lastUser` and `lastPost`. Expanding these fields inserts a child object representing the associated resource (e.g. expanding `insertUser` will take the `insertUserID` and add its associated user row under the `insertUser` key). Category should be added to this list of expand options, to allow basic category information to be included. This will allow easier building of discussion lists, where looking up associated category information would be common, but require additional processing in the API-consuming client.

**Comment by chrisvanpatten** [comment]
Dupe of #6640, but this issue is likely my fault too since I sent the request into my CSM and it might have gotten logged internally :)

**Comment by initvector** [comment]
Thanks for filing the original issue and thanks for spotting the dupe!

Closing in favor of tracking on #6640
