### ISSUE TITLE
Advanced editor - right click URL dialogue closes it on Firefox

### ISSUE THREAD

**Issue by eythian** [vanilla/vanilla#6697]
To reproduce:
* Use Firefox
* Copy a link or something into your clipboard
* Select some text in the wysiwyg editor
* Click the URL button to make this selection a link
* Right click to paste into the URL box

What happens:
* The URL entry box immediately disappears, as soon as the right-click menu appears

What should happen:
*  The URL entry box should remain, allowing the user to paste into it

Workaround:
* Use shift-insert or another paste key-combo to paste

Versions:
* Firefox 59.0b7 (64-bits) on Linux (but I've had a report from someone on a platform that almost certainly isn't Linux.)
* Advanced editor plugin: Version 1.8.1 (ships with Vanilla)
* Vanilla version 2.5

**Comment by charrondev** [comment]
Fixed in Rich Editor which is the default editor as of 2.8.
