### ISSUE TITLE
Rich Editor - Emoji Picker Browser Compatibility

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6706]
For MVP we don't need to worry too much about older browsers, but there are some issues we should address. Old OSs, like Windows 7 have big scroll bars that mess with the width of our components.

I have an idea to fix this. We can refactor the emoji picker to be a list instead of a grid, and we'll make a emoji row component that contains a list of emojis. That way, we can flex the content. We can add enough padding that on old browsers, we don't have x overflow and on newer browsers, they're properly spaced.

Not required for MVP.

**Comment by charrondev** [comment]
Emoji picker has been fully implemented with the editor release in 2.7
