### ISSUE TITLE
[API doc] Fix UI issue with "Example value" tab

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6716]
- "Example Value" tab is cut 
![screen shot 2018-02-27 at 2 29 02 pm](https://user-images.githubusercontent.com/2412909/36750079-9d7b266e-1bca-11e8-98b3-b43f9f0f8fe5.png)

**Comment by charrondev** [comment]
Fixed as of 2.8 at least. Probably was fixed sooner.

![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/89af8651-f49e-47d6-81f4-2b85c276ec53)
