### ISSUE TITLE
[API doc] Fix UI issue of deeply nested schemas

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6717]
Deeply nested schema are really hard to see properly. `GET /authenticate/session` for example:
![screen shot 2018-02-27 at 2 35 07 pm](https://user-images.githubusercontent.com/2412909/36750450-82cc436a-1bcb-11e8-9961-a371ddf8de6f.png)

**Comment by charrondev** [comment]
This is a bit better than it was at this point:

![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/e50a2e83-93f8-4c08-ae8b-918e49fe1aa2)

I don't think we can do much better (not our UI). We should propably try to steer away from deeply nested schemas as well.
