### ISSUE TITLE
[API doc] Fix multi types not being properly displayed

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6718]
Multi types are not properly handled.
{TYPE} || Null for example:
![screen shot 2018-02-27 at 2 38 30 pm](https://user-images.githubusercontent.com/2412909/36750606-f43fb52c-1bcb-11e8-9b65-d53b3560a269.png)

**Comment by cchabilall83** [comment]
this was put to the side and i'm completely forgot about it, I will put in this sprint.

**Comment by linc** [comment]
Acceptance criteria:

* Remove `null` from comma-separated list and set 'nullable' flag instead.
* Modify `true` flag for `expand` to use `'all'` instead so that it's a consistent type with the array of other string options.

**Comment by tburry** [comment]
Addressed in #7541, #7540, #7539

**Comment by charrondev** [comment]
Could we double check to see if https://github.com/vanilla/vanilla/issues/7538 is resolved after these PRs? https://github.com/vanilla/vanilla/issues/7538

**Comment by linc** [comment]
https://github.com/vanilla/vanilla/pull/7541
