### ISSUE TITLE
GDN_Log table needs pruning

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6720]
GDN_Log table is not getting pruned. Some clients have logs dating back to 2011 which caused dashboard/log/edits screen not to load.

**Comment by tburry** [comment]
We should probably prune different operations at different dates. I'm okay with pruning everything except **Delete, Ban,** and **Pending** operations. You can still use the Prunable trait and just override the prune method.

**Comment by DaazKu** [comment]
Ban and Pending are relatively low on most sites. Delete on the other end can get quite high.

I was thinking on pruning `'Edit','Spam','Moderate','Error'` at `c('Logs.PruneAfter.Common', '3 months')`
and `'Delete'` at `c('Logs.PruneAfter.Delete', '1 year')`.

Is that good?

**Comment by tburry** [comment]
That's sounds good.
