### ISSUE TITLE
redirect http to https .htacess no works

### ISSUE THREAD

**Issue by tecnoterabyte** [vanilla/vanilla#6730]
Hi, redirect http to https .htacess no works

`* Original
* If you modify this file then change the above line to: # Modified

<IfModule mod_rewrite.c>
    RewriteEngine On

    ***
    * Certain hosts may require the following line.
    * If vanilla is in a subfolder then you need to specify it after the /.
    * (ex. You put Vanilla in /forum so change the next line to: RewriteBase /forum)
    ***
    *RewriteBase /

    * Make sure that / doesn't try to go to index.php without a rewrite :)
    DirectoryIndex disabled

    ***
    * Deny access to certain directories that SHOULD NOT be exposed.
    ***
    RewriteRule (^|/)\.git - [L,R=403]
    RewriteRule ^cache/ - [L,R=403]
    RewriteRule ^cgi-bin/ - [L,R=403]
    RewriteRule ^uploads/import/ - [L,R=403]
    RewriteRule ^vendor/ - [L,R=403]

    ***
    * Prevent access to any php script by redirecting the request to /index.php
    * You can add an exception by adding another RewriteCond after this one.
    * Example: RewriteCond %{REQUEST_URI} !^/yourscriptname.php$
    * You can comment out this section if it causes you problems.
    * This is just a nice to have for security purposes.
    ***
    RewriteCond %{REQUEST_URI} !/index.php$
    RewriteRule (.+\.php) [E=X_REWRITE:1,E=X_PATH_INFO:/$1,L]

    ***
    * Redirect any non existing file/directory to /index.php
    ***
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule (.*) index.php [E=X_REWRITE:1,E=X_PATH_INFO:/$1,L]

    ***
    * Add the proper X_REWRITE server variable for rewritten requests.
    ***
    RewriteCond %{ENV:REDIRECT_X_REWRITE} .+
    RewriteCond %{ENV:REDIRECT_X_PATH_INFO} (.+)
    RewriteRule ^index\.php -[E=X_REWRITE:1,E=!REDIRECT_X_REWRITE,E=X_PATH_INFO:%1,E=!REDIRECT_X_PATH_INFO,L]
</IfModule>

```
<IfModule mod_headers.c>
   <FilesMatch '(?<!embed)\.(css|js|woff|ttf|eot|svg|png|gif|jpeg|jpg|ico|swf)$'>
      Header set Cache-Control "max-age=315360000"
      Header set Expires '31 December 2037 23:59:59 GMT'
   </FilesMatch>
</IfModule>

**php -- BEGIN cPanel-generated handler, do not edit
**Configure el paquete “ea-php71” como el lenguaje de programación predeterminado “PHP”.
<IfModule mime_module>
  AddType application/x-httpd-ea-php71 .php .php7 .phtml
</IfModule>

**php -- END cPanel-generated handler, do not edit
    RewriteCond %{HTTP_HOST} ^catatumbo\.org$ [OR]ç
    RewriteCond %{HTTP_HOST} ^www\.catatumbo\.org$
    RewriteCond %{REQUEST_URI} !^/[0-9]+\..+\.cpaneldcv$
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/.+$
    RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/[0-9a-zA-Z_-]+$
    RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
    RewriteRule ^/?$ "https\:\/\/catatumbo\.org\/" [R=301,L]

<IfModule php7_module>
   php_flag display_errors Off
   php_value max_execution_time 90
   php_value max_input_time 60
   php_value max_input_vars 1000
   php_value memory_limit 32M
   php_value post_max_size 8M
   php_value session.gc_maxlifetime 1440
   php_value session.save_path "/var/cpanel/php/sessions/ea-php71"
   php_value upload_max_filesize 2M
   php_flag zlib.output_compression Off
</IfModule>
**END cPanel-generated php ini directives, do not edit
```

**Comment by charrondev** [comment]
This repo is targeted at tracking issues for our the application. If you are looking for advice on self hosting please you may be interested in https://open.vanillaforums.com
