### ISSUE TITLE
Rich Editor - Compatibility with core Themes

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6732]
This issue should encompass everything we need for compatibility with out built-in themes. There may be more outside of what is explicitly listed here.

- [ ] Ensure new editor contents render correctly (Paragraphs, blockquotes, code blocks, etc.)

- [ ] Bootstrap 3 has a bunch of extra padding on the bottom of the button bar at the bottom of the editor.

- [ ] Test rich embed in FF
- [ ] Test rich embed in Safari
- [ ] Test rich embed in Edge
- [ ] Test rich embed in IE 11

**Comment by slafleche** [comment]
This might even be a theme to theme implementation. I suggest we make an epic for compatibility and we can tie in issues regarding browser and theme compatibility in there.

**Comment by charrondev** [comment]
From https://github.com/vanilla/vanilla/issues/7162

### Description
Spacing issues with editor.

### Issue severity
Minor

### Steps to reproduce
1. Edit existing post

### Screenshot (if applicable)

<img width="845" alt="screen shot 2018-07-18 at 13 38 22" src="https://user-images.githubusercontent.com/19651440/42898062-110628e8-8a90-11e8-95ba-55ce126a06e6.png">

**Comment by charrondev** [comment]
From @slafleche https://github.com/vanilla/vanilla/issues/7162

### Description
Spacing issues in new groups

### Issue severity
Minor

### Steps to reproduce
1. Create new group 

### Screenshot (if applicable)

<img width="787" alt="screen shot 2018-07-18 at 13 40 39" src="https://user-images.githubusercontent.com/19651440/42898113-3942adae-8a90-11e8-9a4c-a62fc9b92fbb.png">
