### ISSUE TITLE
Functions in functions.general.php can't be overwritten by plugins

### ISSUE THREAD

**Issue by Caylus** [vanilla/vanilla#6734]
According to the docs, overriding functions declared in functions.general.php at the bottom of a plugin is the preferred method of extending functionality (because it's easy to disable/enable, presumably).

Functions.general.php is given as an example.

https://docs.vanillaforums.com/developer/addons/function-overrides/

However, if I try to override a function it throws an error because the function is already declared - presumably functions.general.php is loaded before the plugins are.

**Comment by Charrondev** [comment]
We're currently using this pattern in numerous production environments and it is working properly.

A few more details would be helpful here. What version of Vanilla and what functions are you trying to override. Is it any function that causes this behaviour?

**Comment by Caylus** [comment]
Hey Charrondev, I'm trying to override GetMentions.

I'm using version 2.5.

This is the error that I get: PHP Fatal error:  Cannot redeclare getMentions() (previously declared in C:\\xampp\\htdocs\\vanilla-2.5\\library\\core\\functions.general.php:1484) in C:\\xampp\\htdocs\\vanilla-2.5\\plugins\\AFunctionOverride\\class.aFunctionOverride.php on line 15

I can replicate the problem with getConnectionString.

This is the code for the plugin that I use:
<?php
if (!defined('APPLICATION'))
    die();
$PluginInfo['AFunctionOverride'] = array(
    'Name' => 'AFunctionOverride',
    'Description' => 'Overrides default Vanilla functions',
    'Version' => '1.0',
    'License' => 'GPL v2',
    'RequiredApplications' => array('Vanilla' => '>=2.5')
);
class aFunctionOverridePlugin extends Gdn_Plugin {
}
//placed this function override outside of class definition, because otherwise it wouldn't override the function you wanted to override
/*function getMentions($Mixed) {
    }*/

function getConnectionString(){}

If I try to override a function not declared in functions.general.php but for example in functions.render.php (such as UserURL) it works fine.

In functions.render.php there's a comment on line 398 "
     * Return a url for a category. This function is in here and not functions.general so that plugins can override." which seems to imply that functions in functions.general.php aren't supposed to be overridable by plugins?

**Comment by charrondev** [comment]
This actually seems to be a result of these 4 files being declared in composer so they are loaded before anything else.

```
        "files": [
            "library/core/functions.error.php",
            "library/core/functions.general.php",
            "library/core/functions.compatibility.php",
            "library/core/functions.deprecated.php"
        ],
```

In light of https://github.com/vanilla/vanilla/issues/7696 I don't think we have any intention of making these overridable.

https://github.com/vanilla/vanilla/issues/8204 which is currently on our immediate roadmap involves restructuring our formatting pipeline which would allow for things like mention formatting to be more pluggable through [our DI container](https://docs.vanillaforums.com/developer/framework/dependency-injection/).
