### ISSUE TITLE
Rich Editor - Skips over empty code block with up arrow

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6737]
Reference https://github.com/quilljs/quill/issues/1988

**Comment by charrondev** [comment]
This seems to be fixed in the latest `quill/2.0` branches so I'm going to leave this alone. The Code Block seems to have been totally redone, so this should be fixed upstream before launch.

**Comment by poshest** [comment]
Shame 2.0 is still not out! I'm also facing this issue.
