### ISSUE TITLE
Rich Editor - Style highlighted state for block elements

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6739]
We currently don't have any way to know if a block element is selected in the rich editor. We know when the contents are selected, but not the block.

We should add a listener to selection changed in the editor and apply an overlay with `background-color: Highlight;` on the overlay to match the OS's highlight colour.

**Comment by slafleche** [comment]
FYI: Mockup available in Editor mockup.

**Comment by charrondev** [comment]
Related #6999

**Comment by charrondev** [comment]
This has been implemented.
