### ISSUE TITLE
New account email confirmation url: Possible social engineering attack

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6749]
## Details

Anytime a user creates a new account, an activation link is sent through his email. 

In theory this could be used in a Social Engineering attack where you would create an account that is very similar to another one, give the link to the target and ask him to put sensitive information in the account. Then the attacker can retrieve these information since it is his account.

**Comment by charrondev** [comment]
@linc Is this even possible to fix? I don't think there's really anything to be done for this.

I'd like to close this as a wont' fix.
