### ISSUE TITLE
Rich Editor - IE11 Issues

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6764]
## Images are "resizable"

For some reason IE11 thinks images should be resizable in content editable in IE11.

https://stackoverflow.com/questions/40172690/how-to-disable-ie11-webbrowser-for-image-resizing
https://stackoverflow.com/questions/21864047/how-to-disable-elements-selection-and-resizing-in-contenteditable-div

**Comment by slafleche** [comment]
I tested with debug off and hotreload off:

![Screen Shot 2018-07-03 at 10.57.28.png](https://images.zenhubusercontent.com/582b7208e40e5714b1705650/a8a97f1d-216f-462a-b5b8-c774c4a17866)

**Comment by charrondev** [comment]
It seems we are missing polyfills for some Object methods. `Object.values`, `Object.includes`, `Object.entries`. I'm hoping to clear this up pretty easily with https://github.com/vanilla/vanilla-cli/issues/80 and a new version of babel, but it could also be caused by a polyfill failing to load.

**Comment by charrondev** [comment]
These polyfills were implemented some time ago (and updated multiple time). See the `@vanilla/polyfills` package.
