### ISSUE TITLE
{dashboard_link} directing to the wrong place

### ISSUE THREAD

**Issue by mrpta** [vanilla/vanilla#6781]
After upgrading from 2.3 to 2.5 the placeholder for our dashboard link directs to dashboard/settings which throws the error:

Call to undefined method Gdn_Statistics::IsEnabled()

It looks like 'dashboard/settings' rather than 'dashboard/settings/home' is hardcoded into the Gdn_Theme->link() method.

Is it as simple as amending this method?

**Comment by charrondev** [comment]
I'd recommend upgrading past 2.5.

As of 2.8 I can confirm that the `/settings/dashboard` will redirect to you last visited dashboard page. The page is stashed in your session and redirected to when you visit it.

**Comment by mrpta** [comment]
Hi @charrondev thanks for the feedback - currently running 2.8.1 and have the same problem.

Default link is to: /dashboard/settings/

`The error occurred on or near: /home/paulus/dev.mi6community.com/plugins/OLDVanillaStats/class.vanillastats.plugin.php
71:       $Sender->FireEvent('DefineAdminPermissions');
72:       $Sender->Permission($Sender->RequiredAdminPermissions, '', FALSE);
73:       $Sender->AddSideMenu('dashboard/settings');
74: 
75:       if (!Gdn_Statistics::IsEnabled() && Gdn_Statistics::IsLocalhost()) {
76:          $Sender->Render('dashboardlocalhost', '', 'plugins/VanillaStats');
77:       } else {
78:          $Sender->AddJsFile('plugins/VanillaStats/js/vanillastats.js');
79:          $Sender->AddJsFile('plugins/VanillaStats/js/picker.js');`

**Comment by charrondev** [comment]
Have you tried removing the `OLDVanillaStats`? I'm pretty sure that's not a valid plugin at this point in time. Especially since that's where your error is coming from.
