### ISSUE TITLE
@mention autocomplete cant search for names with accented characters

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#6783]
![image](https://user-images.githubusercontent.com/7501633/37265442-5e3aaa0e-2581-11e8-944e-064d73bacf17.png)

Adding an accented character to an @mention stops the lookup process, making it difficult to use on sites if they have a large userbase, and the accented character appears early in the name. In this example, after the Ä is included in the name, the autocomplete box goes away. 

https://vanillaforums.teamwork.com/#tasks/8317326

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/6165
