### ISSUE TITLE
Implement session management

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#6785]
We currently don't fully implement session-based authentication. We issue a cookie with certain limitations, but that cookie is then valid until:

1. The time limit elapses.
2. The user's info changes.
3. The global cookie salt changes, invalidating ALL site cookies.

Therefore there is not a way to invalidate a particular user's login. This would be advantageous for more secure management of user logins. However, it requires a good deal of work on our authentication system.

The first step in remedying this would be creating an Epic with a series of steps to transition to full session management. This should include discussion of backwards compatibility issues with the rest of the team, especially regarding the use of SSO tokens in API v1 and avoiding a mass-signout event if at all possible.

This conversation needs to involve Ops.

**Comment by linc** [comment]
Related to  #5640

**Comment by derrickeason** [comment]
Hey! Was just curious if there were any plans to address this? I know it's quite low priority but we have a customer that asks about the status every so often.

**Comment by shaunamcclemens** [comment]
This is still being requested by Enterprise level clients (support issue 1389), removing stale label.
