### ISSUE TITLE
Text flowing outside of divs when posting an activity

### ISSUE THREAD

**Issue by rickdaalhuizen90** [vanilla/vanilla#6793]
#### UserAgent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

#### Steps to reproduce the problem:
(For this example i used https://binary.vanillacommunity.com)

1. Register an account at e.g. *.vanillacommunity.com/entry/register
2. Sign in and go to the profile page: *.vanillacommunity.com/profile/username.
3. Post a new Activity with a long title description using markdown e.g.``` # aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://example.com)```

#### What is the expected behaviour?
When posting a activity that has a text with a long description "using markdown", (in this case # title and link), the text flows outside of the div when the activity is posted on the page. The expected behaviour would be, that the text would stay wrapped inside of the div element.

#### What went wrong?

![screenshot](https://i.imgur.com/hZh146n.png)

#### Does this work in other browsers?
Yes

- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6

#### How to fix this?
Adding a word-wrap: break-word; to the effected div elements

**Comment by charrondev** [comment]
Fixed with keystone, the new default theme as of 2.8.
