### ISSUE TITLE
Rich Editor - Fix active default active colour in toolbars

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6809]
@danmaitland has provided the colour #0291DB to be the default active colour.

![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/bfdfda06-de79-4dfc-a0f2-cca681ae27ed)

**Comment by slafleche** [comment]
Create a sass variable in the editor styles with a "!default". Later, we'll hook it up to theme variables.

**Comment by charrondev** [comment]
Closing for https://github.com/vanilla/vanilla/issues/6732
