### ISSUE TITLE
class.format.php: video embed code stripped away for plain text emails

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6815]
### Details

Whenever a link that auto embeds is posted in a comment like a YouTube or Twitter, the generated notification plain text email is missing the link text.

![image](https://user-images.githubusercontent.com/31856281/37525206-953d4f96-2902-11e8-8ced-59d3625b6095.png)

**Notification email sent without the link**

![image](https://user-images.githubusercontent.com/31856281/37525193-87995308-2902-11e8-9199-58e824c5c0c8.png)

**Instead of** 

![image](https://user-images.githubusercontent.com/31856281/37525332-f4a4133e-2902-11e8-9680-535392052bb2.png)

 

Ryan's Notes:

https://github.com/vanilla/vanilla/blob/e7f487b1952198076e9d34f1801471f756a5906b/library/core/class.format.php#L1284

 It's creating the embed code for the video, then stripping it away for the email.

**Comment by charrondev** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/8237
