### ISSUE TITLE
Facbook Social Connect: new security changes & redirect URI

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6818]
### Details

Currently, Using facebook social connect, you can sign-in from the home page and the few listed valid OAuth redirect URIs. The sign-in works on the homepage but if you're in a discussion ready to comment and want to login, you can't. Now you can't use a wildcard of any sort so you can't list any discussion URL in the redirect section.

### To replicate

-sign-in with FB - will work from homepage,
-logout then go into a discussion and try to sign-in with FB again.

### Solution, using strict mode with state parameters

https://developers.facebook.com/docs/facebook-login/security/#strict_mode

**Comment by nervoustwit** [comment]
The problem stems from the fact that we append the Target uri to the callback uri. So far the only solutions I can see are:
1.  Not add a Target URI, when you log in with Facebook you are directed back to the homepage of the forum.
2. Create a cookie with the Target uri
