### ISSUE TITLE
Password check when changing a user email address

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#6826]
###  Details

When a user edits his profile to change his email address, we are not performing a password check before the email gets changed.If a user forgets to logout while using a public pc, another user can change his email and gain access to his account.

**Comment by initvector** [comment]
I'm pretty sure this was already resolved with #6056. If you haven't re-authenticated (or signed-in) within 20 minutes of attempting to change your email address, you have to enter your password again.

**Comment by dannimajdalani** [comment]
Tested with the mentioned change. Closed by #6056
