### ISSUE TITLE
Add Pull Request template

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6839]
We need a pull request template for this repo to add some consistency to out pull requests. It should cover the following:

- Having an issue before the PR.
- Adding a description.
- Where/How did you test the changes.

**Comment by DaazKu** [comment]
And here is the documentation on how to do that: https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by charrondev** [comment]
An example from our locales repo: https://github.com/vanilla/locales/blame/master/.github/pull_request_template.md

**Comment by charrondev** [comment]
Done. We have 1 now.
