### ISSUE TITLE
Reconsidering use of 'nofollow' in user-generated content

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#6848]
### Current situation:
* By default, `nofollow` is applied to every UGC link in Vanilla plus mentions.
* It is controlled by the `DisplayNoFollow` property on the GDN_Format class, but to my knowledge nothing at all has modified this property.

### Background:
* The `nofollow` attribute is respected by search engines in different ways, but universally removes any rank gained from the link in question. Google goes further and literally does not follow the link (even to index it). Guessing whether these claims are completely true or not is fruitless, so we'll take them at face value.
* The purpose of `nofollow` is to remove the incentive to spam forums by neutering the potential gain. It's impossible for us to gauge the effectiveness of this; forums still get spammed, and we've always had it on all links in UGC to my knowledge.

**My concern:** Are we actively hurting the open Internet by blindly adding `nofollow` to every link? Forums are an important part of the non-monopoly ecosystem of the Internet and we're basically denying all search engine ranking to what we link to from our own communities. I think this is a bad position to be in.

**The challenge:** If we were to alter our `nofollow` policy, what is a reasonably safe way of doing this without encouraging spammers? And, how can we do it in a broadly-designed way that doesn't require additional configuration by site admins?

### Considerations:
* We've talked about how to rework the `Verified` user property to be more meaningful and broad in Vanilla and I believe that is still a goal. I'm strongly in favor of coupling these issues.
* We now have security settings that encourage adding "Trusted Domains" that we could perhaps leverage in part of the solution.
* We've talked about making Ranks a core feature. Is this more appropriate as part of Ranks? I'm skeptical of this because I think Ranks is more about user-facing features (rewards) and we should couple trust issues with it less, not more.

**Comment by linc** [comment]
Practical example:

Discussion named "[Post count not updating](https://open.vanillaforums.com/discussion/35885/post-count-not-updating)" on which I post a probably answer to why discussion count wouldn't be working.

Then an older discussion gets bumped, "[Discussion count not updating](https://open.vanillaforums.com/discussion/35832/discussion-count-doesnt-update-itself)" in which I post a link to my answer in the first discussion.

Ideally, the first discussion would get ranked higher because the link indicates it actually has the answer to the search terms in the second discussion. That being the first result leads to a better click-thru rate, user satisfaction, etc which is self-fulfilling SEO goodness. The problem is our current policy of slapping `nofollow` on every link - even if it's to our own forum! - means there is no such transfer whatsoever.

It seems to me the lowest-level fruit here is that links to the SAME FORUM should at least be granted an exception.

**Comment by charrondev** [comment]
The issue with not tying it rank, is I could easily imagine a case where you want the "verified" user whose links get followed to require a higher standard than simply verifying an email. Criteria like account age, points, or a certain role being attained would all be things I would want to consider for a user to not be a spam account. Ranks already has all of these things, so the question is do we remake this functionality or not?

**Comment by adrianspeyer** [comment]
We have a customer AgileBits (hi @shaunamcclemens), who has brought up the challenge of content within their domain, ie. blog or knowledge base should not be no-follow. Maybe a consideration of whitelisting certain domains. The other option, they see, is people with the staff permission, via ranks (perhaps) would then have all links being followed. 

There seems to be setting for this, but it's not easy to use for customer where a custom plugin is not an option.

https://github.com/vanilla/vanilla/blob/master/library/core/class.format.php#L27

**Comment by charrondev** [comment]
That option will not apply to the rich editor at all in its current form, but could be passed in. Knowledge base seems like the type of thing that would likely never have no follow links, as it is the definition of trusted content.

**Comment by kaecyra** [comment]
After talking with @tburry we've come to a compromise of adding a global dashboard-visible toggle for nofollow, which would affect the GDN_Format calls to htmLawed. This will be considered roadmap acceleration if @shaunamcclemens customer wants it ASAP.

**Comment by kaecyra** [comment]
Our first pass, and what we're willing to build at this current moment, is a global toggle. Having a whitelist is a good idea and I suggested it to Todd as well, but it makes the feature much more complex because the GDN_Format toggle is binary and there's easy way to make the toggle conditional on the URL being rendered right now.

**Comment by linc** [comment]
This compromise sounds like the worst of both worlds. We have some known issues around Akismet & spam detection that aren't fully resolved yet. Allowing customers to blindly 100% opt-out of `nofollow` seems like pointing a gun at their foot and saying "Click here to fire".
