### ISSUE TITLE
Fix Headings

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6852]
We've added some aria attributes to improve the heading structure for screen readers. It would be better to actually update them, but we're dependent on some [type of config](https://github.com/vanilla/vanilla/issues/6851) to prevent breaking themes.

**Comment by charrondev** [comment]
I'm closing this as an issue. I don't think there's any real path to fixing these without essentially rewriting the views in our new system which doesn't exhibit these issues.

If you have plan for updating all of old views to look conditionally before making a heading, than we can re-open this.
