### ISSUE TITLE
Use "real" buttons

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6853]
We've added `role="button"` to several links that are used as buttons. For forward compatibility, we'd like to update these with a [theme config](https://github.com/vanilla/vanilla/issues/6851).

**Comment by charrondev** [comment]
I'm closing this as an issue. I don't think there's any real path to fixing these without essentially rewriting the views in our new system which doesn't exhibit these issues.

If you have plan for updating all of old views to look conditionally before making a heading, than we can re-open this.

Similar to https://github.com/vanilla/vanilla/issues/6852
