### ISSUE TITLE
Add class to edit profile button on edit profile page

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#6868]
On the Profile Page the edit profile dropdown has the class "Button-EditProfile", once you go to the Edit Profile Page the button doesn't have this class anymore.

It would be really good for theming if this class was consistent between both pages.

**Comment by slafleche** [comment]
@igraziatto On the edit page, we no longer have that button, there's a link instead... I'm not sure what you mean here. Both the button and the link have the same (poorly named) class: "ProfileButtons".
