### ISSUE TITLE
Searching for available classes in core

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6877]
The AddonManager has the handy method [findClasses()](https://github.com/vanilla/vanilla/blob/e9181b6ac9c4d336503f74f0c2abf7bd4c4563f8/library/Vanilla/AddonManager.php#L217) that allows us to find classes using glob patterns. Unfortunately it does not allow us to find classes in vanilla core.

This feature should probably be added to VanillaClassLocator which could then be used to find any classes.

To implement this we could use composer's autoloader class map which already contains the mapping of all the classes. The only problem is that PSR-4/PSR-0 rules are not in the classmap by default. This could easily be fixed with the [optimize-autoloader](https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-1-class-map-generation) config.

**Comment by tburry** [comment]
I'm not super sure I want to go down this route. If this is for something specific then I'd maybe just add the ability to register a class in the AddonManager and do it manually or add the ability to search a list of predefined namespaces and use class_exists with them.

**Comment by DaazKu** [comment]
The specific use case:

https://github.com/vanilla/vanilla/blob/5dab145fa2ee284f23cb76facf508f3f469acd36/library/Vanilla/Models/AuthenticatorModel.php#L154-L164

We cannot find fixtures in the unit tests and we cannot find Authenticators added in core.
Composer with the optimized option already has a cached class map of everything in core so we could replicate what the addon manager does for core classes.

We *could* manually add these classes to the addonManager but it's a bit weird because it doesn't have anything to do with addons and it forces us to remember that we have to add the classes for them to be "available".
Another solution would be to have VanillaClassLocator map all core classes itself and cache the result (like AddonManager) but composer autoloader "already" does that so it would be a shame to do it again.

**Comment by DaazKu** [comment]
An alternate solution would be to force Authenticator classes to be registered on the AuthenticatorModel for them to be available.

```php
AuthenticatorModel::registerAuthenticator({AuthenticatorClass});
AuthenticatorModel::unregisterAuthenticator({AuthenticatorClass});
```

**Comment by tburry** [comment]
You could also have fixtures not have a namespace and make the core authenticators have a predefined namespace. You could even give the fixtures the same namespace as core.

**Comment by DaazKu** [comment]
Replaced by https://github.com/vanilla/vanilla/issues/6929
