### ISSUE TITLE
Spec out Tags endpoint

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#6901]
We need a spec for the tags API v2 endpoint and discussions endpoint updates to make use of tags.

**Comment by JosephFleming** [comment]
Hey, here are some ideas for tag API:

-GET list of discussions with tag_id
-GET count with tag_id
-Be able to see both of these stats over a range of time

The overall goal would be to be able to track some analytics related to tags

**Comment by vrjrobitaille** [comment]
Roadmap for Q1 2021. Closing this out in  favour of PBI - https://github.com/vanilla/roadmap/issues/100
