### ISSUE TITLE
Spec out the rest of the media embeds

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#6906]
Discuss what we need to work on for the media embeds.

**Comment by charrondev** [comment]
Summary from the meeting:

Create a `EmbedManager`.
- Dependencies injected through the container.
- Handles rendering of embed content.
- Handles scraping of urls.
- Quill Renderer uses it to render embed content.

Scrape API changes:
- Schema changes:
  - `type: string` (eg. vimeo, youtube)
  - `renderType: string` (eg. text, video, script-required, iframe)

Loading javascript for embeds that need it:
- Always loaded if the editor is on the page.
- Otherwise data-script tag is added and matched to a whitelist. Async loaded from the client side.

**Comment by initvector** [comment]
@tburry is going to write up a doc for the requirements necessary and we'll get those updates sprinted. I am assuming that will take the place of https://github.com/vanilla/vanilla/issues/6916.
