### ISSUE TITLE
Rich Editor - Add "no style" to paragraph menu

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#6909]
The paragraph menu should have a "no style" in the menu to make it easier to understand and undo styles.

The accessibility should also be updated to have each button as a "radiobutton" and not a toggle.

**Comment by charrondev** [comment]
Since this is actually not going to be a strict radio button after the latest mockups, I'll only be adding the no style button.

**Comment by charrondev** [comment]
> The accessibility should also be updated to have each button as a "radiobutton" and not a toggle.
It's clear that this is going to remain a radiogroup so I'm going to leave that out of this PR. We can revisit it in the future, but even if all of the items stay exclusive it doesn't really behave 100% like a radio group.
