### ISSUE TITLE
Ability to change the default password hash algorithm via Admin panel

### ISSUE THREAD

**Issue by nshusa** [vanilla/vanilla#6913]
Can we get a feature where we can change which algorithm Vanilla uses to hash passwords?

![https://i.imgur.com/es76OWu.png](https://i.imgur.com/es76OWu.png)

E.g I'm integrating forums with the game I'm making. So if a user creates an account via the forums they don't need to create an account in-game and vice versa. However, Vanilla uses "Vanilla" algorithm as default method but I'd rather use Blowfish as I have a nice library for the language my game is written in. Whereas the language I'm using for my game doesn't have any libraries for the "Vanilla" method. So I would have to create one.

**Comment by charrondev** [comment]
I don't think we have any intention of making this selectable.

We don't recommend using Vanilla as an identify provider. A more standard setup would be to use some external identify provider and configure Vanilla to use that with an SSO plugin or integration.

https://docs.vanillaforums.com/help/sso/jsconnect/ allows you to build a pretty custom SSO solution.
