### ISSUE TITLE
Basic mobile theme - scrolls to top after Back

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#6926]
1. Access a forum using Basic Mobile theme on a mobile device (e.g. https://greasyfork.org/forum/)
2. Scroll down, click a discussion.
3. Press Back in your browser.

You are returned to your previous position for a second on the index page, then you get scrolled to the top. It should not scroll you back to the top.

This is the code that's doing it - https://github.com/vanilla/vanilla/blob/58d62c56a550a9ef3a30ed63bacfa4c4ec83f9fe/themes/mobile/class.mobilethemehooks.php#L42-L48

**Comment by charrondev** [comment]
While I recognize this as a bug, we have no intention of fixing this. We've now shipped keystone as our default mobile theme which does not exhibit this issue.
