### ISSUE TITLE
/profile/picture Throws Wrong Exception When GD Is Missing

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#6943]
Please see this discussion: https://open.vanillaforums.com/discussion/comment/252352/#Comment_252352

A user got a 404 status return when he tried to access /profile/picture simply because he hadn't installed the GD extension. Not sure if 500 or 501 would be correct, but both are better than 404.

**Comment by charrondev** [comment]
Closing for #6945

**Comment by charrondev** [comment]
Re-opening. This issue should be handled in its own fix.

**Comment by charrondev** [comment]
https://github.com/vanilla/vanilla/pull/6946/ require the GD extension.
