### ISSUE TITLE
Followed Categories Should Have A CSS Class

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#6955]
Just looked at the new category following feature and the first thing I noticed was that I do not have a visible feedback if I click "Follow" on a category on /categories. I think that there should be CSS class for ul.DataList.CategoryList > li#Category_x for followed categories (unfollowed is default so I do not think a special class would make sense)
Having that css class also in /discussions would be nice.

Main reasons for such a class:

1. A followed category is a category of special interest and therefore it would be fine to be able to highlight discussions in such a category
2.  After clicking Follow/Unfollow the user has no visible feedback that his action was a success
3. When looking on the list of categories later on a user has to switch between All and Following to see which categories he is already following

**Comment by charrondev** [comment]
Leaving this one, because it's the type of thing that would be a good onboarding task. It's simple and super easy to implement with no risk.
