### ISSUE TITLE
Cannot delete moderation logs

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#6976]
<img width="1076" alt="upload" src="https://user-images.githubusercontent.com/2412909/38438346-39428d8a-39a8-11e8-8cbc-2a1689688080.png">

**Comment by LauraMakesArt** [comment]
@DaazKu Seems that this fix was deployed, but the error still occurs just as described and clients are reporting back, can you investigate?

**Comment by dannimajdalani** [comment]
I got this error when tested locally

![error1](https://user-images.githubusercontent.com/31856281/38871768-b9d8d0d8-421f-11e8-8be8-b284e3511169.png)

We are calling 
https://github.com/vanilla/vanilla/blob/017304c3f1a07a8e7bdd291dd3bfd08cec49951f/applications/dashboard/models/class.logmodel.php#L197

that calls

https://github.com/vanilla/vanilla/blob/017304c3f1a07a8e7bdd291dd3bfd08cec49951f/library/database/class.sqldriver.php#L2075
which is expecting $logIDs  to be an array 
https://github.com/vanilla/vanilla/blob/017304c3f1a07a8e7bdd291dd3bfd08cec49951f/library/database/class.sqldriver.php#L2076
