### ISSUE TITLE
Advanced Editor should link to a document specifying the allowed syntax

### ISSUE THREAD

**Issue by JasonBarnabe** [vanilla/vanilla#6979]
The Advanced Editor plugin includes text like "You can use [Markdown](https://en.wikipedia.org/wiki/Markdown) in your post.". This links to Wikipedia. It would be good for it to link to a document that describes all the allowed syntax, for example [what GitHub uses](https://guides.github.com/features/mastering-markdown/).

**Comment by charrondev** [comment]
Non-security fixes will no longer be prioritized for advanced editor by the vanilla team. Rich Editor ships with Vanilla 2.8 as the default. https://github.com/vanilla/vanilla/pull/8302

A rich editor equivalent issue does exist though: https://github.com/vanilla/vanilla/issues/8276
