### ISSUE TITLE
Uncached database query: Participated

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#6983]
This query is causing very high QPS in production:

```
select d.*, w.DateLastViewed as `DateLastViewed`, w.Dismissed as `Dismissed`, w.Bookmarked as `Bookmarked`, w.CountComments as `CountCommentWatch`, w.Participated as `Participated`, d.DateLastComment as `LastDate`, d.LastCommentUserID as `LastUserID`
from GDN_Discussion d
left join GDN_UserDiscussion w on d.DiscussionID = w.DiscussionID and w.UserID = 0
where d.DiscussionID = ?
```

Above is the "prepare" statement; Tim points out that the zero for UserID is already set here, which is a clue.

My cursory inspection suggests it's the WatchUserID being set to zero, which is itself possibly a byproduct of the Category Following work.

**Comment by DaazKu** [comment]
Well that's the query from `DiscussionModel->getID()`.
User data is automatically join to this query and since `w.UserID = 0` it means that the query comes from guests.

**Comment by DaazKu** [comment]
I don't have the time to find out why it is called that much for guests.

Additional information would be great.
Is this affecting all clusters?
If not, which site seems affected the most? (Probably a customization that's present on a non cached page)

**Comment by kaecyra** [comment]
site ID 5015319
site ID 5021738

In general seems to be hitting db4.cl311 quite hard, along with db9.cl412.
