### ISSUE TITLE
Rich Editor - Check overflowing titles on popovers

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7011]
Check if long titles can break UI for popovers

**Comment by charrondev** [comment]
As far as long text goes, the popover titles are fine:

![image](https://user-images.githubusercontent.com/1770056/38639625-cef56be0-3d9f-11e8-8138-53a3d19f3e93.png)

But the descriptions aren't 
![image](https://user-images.githubusercontent.com/1770056/38639642-dd6fa8b6-3d9f-11e8-8527-d9fda92e1212.png)
