### ISSUE TITLE
Restore the breadcrumb under the editor

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#7014]
https://github.com/vanilla/vanilla/pull/6516
https://github.com/vanilla/support/issues/1

We implemented this change and have had nothing but confusion since. When the changed was proposed I assumed we were only removing the breadcrumb from groups. Removing it completely eliminates all our bottom navigation, and the end users immediately noticed.

**Comment by DaazKu** [comment]
Todd
> The breadcrumb should be built in the controller and send to the view as data
