### ISSUE TITLE
Add foregroundColor to Authenticators schema

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#7021]
Both backgroundColor and foregroundColor can be null and AuthenticatorAPIController::normalizeOuput() will have to fill these field with default values if they are missing (same the for Icon)

**Comment by DaazKu** [comment]
@slafleche I'm gonna need those defaults

**Comment by slafleche** [comment]
[ssoIcons.zip](https://github.com/vanilla/vanilla/files/1908715/ssoIcons.zip)

yahoo
	bg: #40008F
	fg: #fff
sign_in	
	bg: #0291db
	fg: #fff
openid
	bg: #F8941C
	fg: #fff
github
	bg: #fff
	fg: #000
microsoft
	bg: #fff
	fg: #000
google
	bg: #fff
	fg: #000
linkedin
	bg: #0077B5
	fg: #fff
facebook
	bg: #4A70BD
	fg: #fff
disqus
	bg: #35A9FF
	fg: #fff
twitter
	bg: #1DA1F2
	fg: #fff
