### ISSUE TITLE
User Search - Refactor how the search conditions are built

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#7050]
They way we generate the search query should be reworked.
To be spec'd out

related to 
[Issue#6989](https://github.com/vanilla/vanilla/issues/6989)
[PR#6381](https://github.com/vanilla/vanilla/pull/6381)
[PR#7042](https://github.com/vanilla/vanilla/pull/7042)

**Comment by initvector** [comment]
The "optimized" search performs an AND comparison, where we probably want an OR.

#6381 fixed an issue with issue with searching users and MySQL's strict mode. Part of the fix included adding a condition to the user search query that can potentially require a user's ID be in a list of IDs (i.e. run one query to get all users with the IP address, then update the user search query to require a user ID from that list).

Searching for an IP address triggers adding the IP filters, but also still tries to perform name matching based on the IP address (e.g. searching for 192.168.1.1 will search for users with that IP and usernames starting with 192.168.1.1). I don't think it's impossible for a user to have a name in the format of an IP address, so it's probably worth keeping it like this.

The resulting query for searching users with an IP address *should* look like: select all rows from Users where the user ID is in (1, 2, 3, 4, 5) OR the last IP address is 192.168.1.1 OR the username starts with 192.168.1.1. Currently, an optimized search includes the last condition as an AND. The query currently would be executed as: select all rows from Users where (the last IP address is 192.168.1.1 AND the username starts with 192.168.1.1) OR the user ID is in (1, 2, 3, 4, 5). Unless there was some incredible coincidence where the user's name was the same as their IP address, the first condition group is almost always going to fail. This doesn't make sense and can lead to unexpected results.
