### ISSUE TITLE
The ssostatetoken cookie is being set unnecessarily

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7067]
When I sign in with my username/password I am noticing the ssostatetoken being created even though I don't need it.

- The ssostatetoken should only be created when needed for SSO.
- The ssostatetoken should be cleaned up after use.

**Comment by DaazKu** [comment]
On my local setup, with Twitter and Facebook enabled the token is not set. We are gonna need more details.

**Comment by DaazKu** [comment]
The cookie is indeed not properly deleted though.

Also:
/code [11:04 AM] Todd Burry: If it is never consumed it doesn't get cleaned up. I think the delete should be elsewhere.
[11:05 AM] Todd Burry: Like if I sign out it should be removed with all other cookies.
[11:05 AM] Todd Burry: Or if I successfully sign in with something else.
