### ISSUE TITLE
Add embed classes

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#7079]
#6916 includes creating a new `EmbedManager` class, along with individual service embed classes. The issue starts off with two embed service classes: YouTube and Vimeo. There needs to be reasonable parity with existing embed support, so more embed classes are needed.

- [ ] Getty Images #7127
- [ ] Imgur #7209
- [ ] Instagram #7210
- [ ] Pinterest #7128
- [ ] SoudCloud #7125
- [ ] Twitch
- [ ] Vine
- [ ] Wistia

Most of the data-gathering code could be harvested from `WebScraper`. HTML code could be taken from `Gdn_Format`.

**Comment by charrondev** [comment]
I'll handle the HTML code and integration. The code is actually quite different now from what it was in `Gdn_Format`.

**Comment by charrondev** [comment]
Closing for #6509
