### ISSUE TITLE
API v2: updating Idea "statusNotes" does not actually publish it. 

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#7103]
https://vanillaforums.teamwork.com/#tasks/8606240

There is a video attached to this task that walks through this issue but the basic summary is if you use:
http://laura.vanillademo.com/api/v2/discussions/6373/idea 
{
  "statusID": 7,
  "statusNotes": "Hey Cool, Im pleoeoenjw this status with the API"
}

It will update the StatusID, However, the ID will only show in the discussion list. When you open the thread, the Ideation UI will generically show it as "Active" and with no notes. 

If you EDIT the idea status, the correct ID will be selected in the dropdown, and "statusNotes" will appear in the form for editing. Hitting submit will correct both.
 
![image](https://user-images.githubusercontent.com/7501633/39216071-e6209d68-47df-11e8-8034-8f2adb90d6e6.png)

**Comment by initvector** [comment]
Issue moved to [vanilla/internal #1571](https://github.com/vanilla/internal/issues/1571) via [**ZenHub**](https://www.zenhub.com/)
