### ISSUE TITLE
ModerationController::confirmDiscussionMoves is exhausting allowed memory size

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7105]
### Details

Moving a discussion from one category to another is exhausting the allowed memory size and is causing a "500 Internal server error".
php-error {"level":"Fatal","error":"Allowed memory size of *** bytes exhausted..

**Error when moving a discussion**
![tt22](https://user-images.githubusercontent.com/31856281/39258757-c22fdb14-4882-11e8-8c0c-f96fefd3936c.png)

**Comment by DaazKu** [comment]
Can you please put more detail to help us reproduce the error?
If I was to try that on my test forum with 20 categories would that be a problem?
What do I need to have to reproduce the problem? Some configurations? A certain amount of categories? A specific category tree structure?

**Comment by dannimajdalani** [comment]
As this could not be replicated locally, I created a ticket in the support repo to provide more details.
[#27](https://github.com/vanilla/support/issues/27)

**Comment by DaazKu** [comment]
Thanks a lot!

**Comment by DaazKu** [comment]
I was not able to replicate on my local setup. See vanilla/support#27 for more details.
