### ISSUE TITLE
Social Groups Discussions: DiscussionController::bookmark requires "Vanilla.Discussions.View"

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7106]
# Details

We recently did a security patch that fixes the ability of any user to bookmark a discussion he has no access to.
https://github.com/vanilla/vanilla-patches/pull/149

We are now requiring "Vanilla.Discusisons.View" permssion when bookmarking a discussion
https://github.com/vanilla/vanilla/blob/4df02ea78330e7a3b5836ee33af0f91e26979311/applications/vanilla/controllers/class.discussioncontroller.php#L447

# Issue

This is causing the below error when trying to bookmark a discussion inside a group

![ssr2](https://user-images.githubusercontent.com/31856281/39263909-8491f062-4891-11e8-81a1-21d314b48809.png)

Social Groups do not usually have "Vanilla.Discussions.View" permission checked, since they are meant to be hidden from the user.
![social_groups_member](https://user-images.githubusercontent.com/31856281/39264024-c5e4fb0e-4891-11e8-9d35-5a893a7a972f.png)

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #1565](https://github.com/vanilla/internal/issues/1565) via [**ZenHub**](https://www.zenhub.com/)
