### ISSUE TITLE
/api/v2/authenticate does not fully respect Garden.SignIn.Allow permission

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7119]
## To Reproduce
- Create a user of a role with no signin permisson
- Attempt to authenticate using the `/api/v2/authenticate/password` endpoint

## Expected
- The user is denied the signin similarly to with the EntryController.

## Actual
- The successful response is received, but a Session is not started.

**Comment by DaazKu** [comment]
Gdn_Session::start() doesn't do anything to notify that something has gone wrong. We will need to ensure that the session was "properly" started in SSOModel and AuthenticateAPIController.
Ensure that unit test are added for that case too.
