### ISSUE TITLE
Announcements no longer pinned on top of recent-discussions

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7121]
# Details
 
Recent change introduced in #6948 is causing announcements not to get pinned on top of recent-discussions page

## Before 

![before_change](https://user-images.githubusercontent.com/31856281/39322410-d191f332-4957-11e8-89d8-293cda9b568b.png)
## After

![after_change](https://user-images.githubusercontent.com/31856281/39322426-d6d64b5e-4957-11e8-8b79-c86b05bcd076.png)

**Comment by DaazKu** [comment]
#6948 was just fixing a bug introduced by #6934 so the real problem probable starts from there or before.

**Comment by vrjrobitaille** [comment]
@initvector The behaviour I've observed is that it will work initially if you announce a post, or if you unannounce a post and reannounce it, it will work. Maybe this is a subcommunities issue as I've observed it consistently on GoodGame and intermittently on MCOC and TFTF communities - when you unannounce and reannounce a post it will work initially but if you switch subcommunities it will scramble again.

**Comment by initvector** [comment]
Thanks! I was finally able to figure out the root cause (caching) and have a PR open to address it (#7240).

**Comment by vrjrobitaille** [comment]
Amazing! Thanks @initvector
