### ISSUE TITLE
Don't count links & quotes in character count for posting

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7136]
If you employ the "Minimum character count" for posting, the intent is to prevent "non-responses" of just emoji or overly brief replies - you want to encourage real conversation that requires forming full sentences. Therefore, I think it would be appropriate to discount links & quotes when checking that threshold to make sure the count is being respected and not bypassed (in spirit) by using those things to bypass it.

**Comment by charrondev** [comment]
Related and tracking on https://github.com/vanilla/vanilla/issues/8836 instead.
