### ISSUE TITLE
Activity translation: Allow override ALL (format, etc.)

### ISSUE THREAD

**Issue by unlight** [vanilla/vanilla#714]
In short, need make FormatActivityHeadline locale dependent.
- Add function FormatActivityHeadline (functions.render.php)
- Replace Gdn_Format::ActivityHeadline by FormatActivityHeadline()
  <pre>function FormatActivityHeadline($Activity, $ProfileUserID = '', $ViewingUserID = '') {
  Gdn_Format::ActivityHeadline($Activity, $ProfileUserID = '', $ViewingUserID = '');
  }</pre>

**Comment by x00** [comment]
Are you planning to do any thing with this?

https://github.com/vanilla/vanilla/blob/b94c27ed88badd5320aec68a1f648d1ef89e5790/applications/dashboard/models/class.activitymodel.php#L147

I'll send a pull request 

` $Row['Headline'] = formatString($Row['HeadlineFormat'], $Row);`

to

` $Row['Headline'] = formatString(t($Row['HeadlineFormat']), $Row);`

I'm guessing this will not make it into a 2.1 update?

**Comment by x00** [comment]
I'm actually thinking 

`$Activity['Headline'] = FormatString(t("HeadlineFormat.{$Data['ActivityType']}", $Row['HeadlineFormat']), $Activity);`

would be better

**Comment by x00** [comment]
https://github.com/vanilla/vanilla/pull/3211
