### ISSUE TITLE
Extend OAuth2 Plugin/Class to support OIDC compliance.

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#7141]
Auth0 is deprecating its OAuth2 workflow for OAuth2 OpenID Connect workflow which is significantly different. Among other things it sends the AccessToken in a signed JWT. See:

http://openid.net/specs/openid-connect-core-1_0.html

We need to add a flag to our OAuth2 plugin to allow for clients to follow a strict OAuth2/OIDC workflow.

**Comment by charrondev** [comment]
@nervoustwit Do we still need to do this or is it moot point now that we've removed OpenID?

**Comment by shaunamcclemens** [comment]
FWIW, The customer who requested this is churning.

**Comment by mauricioschneider** [comment]
Hey! I'm part of the Developer Support team at Auth0, and recently helped one of our Support Engineers to assist a customer that was having issues setting up signup/login in Vanilla Forums via Auth0.

We used to support authentication by sending user credentials to our Authentication API via the `/oauth/ro` endpoint, but this has been deprecated some time ago, as the OP stated.

Is it safe to assume based on this open ticket that at the time Vanilla Forums doesn't support the current OAuth/OIDC implementation that Auth0 uses, where applications are expected to redirect the user to our [`/authorize` endpoint](https://auth0.com/docs/api/authentication#authorize-application)?
