### ISSUE TITLE
Rich Editor - Fix and finalize styles for lists in the editor.

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7149]
Quill actually handles lists and nesting while keeping the list flat. The list styles are provided by a stylesheet. As a result we'll likely need to manage our lists in a manner like this.

https://github.com/quilljs/quill/blob/develop/assets/core.styl#L56-L113

**Comment by slafleche** [comment]
@charrondev Do you have a branch where I can make lists? Can I reproduce this? Do we already have server side rendering for lists?
