### ISSUE TITLE
Rich Editor - Design in editor file attachments

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7161]
Needs Mockups + requirements.

- Final file attachment
- Uploading state with a progress bar.
- File upload error state with an okay or something.

This requires a generic error and our current loading state screenshots.

**Comment by charrondev** [comment]
Screenshot of a current error state.

![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/28c3f1e6-6b63-4c23-8cfc-0078bdb6aeee)

**Comment by ElisaAlmeida** [comment]
It's done. 
Page's name:
- Mobile: Article Widgets
- Desktop: Revision History

The link:
https://drive.google.com/drive/folders/10T0idJVtRNb1RoddzX7FPPxhYZkhB6GQ?ogsrc=32

**Comment by initvector** [comment]
Closing this, since it's reported as "done" by @ElisaAlmeida
