### ISSUE TITLE
usercontroller fire the BeforeUserEdit event before the user data is set.

### ISSUE THREAD

**Issue by mepsteinj** [vanilla/vanilla#7171]
Dear team,
I'm developing a plugin for vanilla that make use of **BeforeUserEdit** event in the user controller.
This event is fired before the user data is set. I know that I can manipulate the user data in the arguments TargetUser array, but for me this is an ugly hack because we have the **getValue / setValue** methods.

Moving the event **$this->fireEvent("BeforeUserEdit");** after **$this->Form->setData($user);** fix this issue. 

Regard,
Michael

**Comment by charrondev** [comment]
The intention going forward is actually not pass along the full instances to event handlers, and pass _just_ the data that we explicitly want to be modify-able.
