### ISSUE TITLE
Cannot Sign in vanila forum

### ISSUE THREAD

**Issue by angeloudy** [vanilla/vanilla#7188]
We have been running vanila forum for a long time. Then suddenly I cannot login any more.
When I click on 'sign in', the popup windows displays all the discussions instead of the login form.
By inspecting the html, I found that the sign in was redirecting to '/discussions'.

Any ideas?

**Comment by charrondev** [comment]
This isn't an issue we're currently experiencing ourselves or in our production environments. As a result this is likely a configuration issue. I'd even guess it's probably something to do with an SSO setup.

This issue tracking is for strictly technical issues. For configuration issues, or setup instruction, I'd recommend heading over to our [Open Source Community Forums](https://open.vanillaforums.com), where you are more likely to receive assistance.

When you make a post there, please be sure to provide as much technical detail as you can about your setup, vanilla versions, custom plugins, or SSO configuration.
