### ISSUE TITLE
Fix unit tests bootstrapping corruption in between tests

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#7204]
We need to refactor our unit test environment so that tests stop corrupting the container.

APIv2 tests do that properly already but the other tests are a nightmare.
The main issue is that many tests in library/code rely on the bootstrapping done in [phpunit.php](https://github.com/vanilla/vanilla/blob/2f9fa23e7f45aa5c4ed00fc2aff017890f31beba/tests/phpunit.php#L37)
Just create one test in LibraryCore with BootstrappingCorruptionTest.php and use the bootstrapping trait. You'll some the following error starting to pop up in other tests: 
```
Garden\Container\NotFoundException : Class Config does not exist.
 /srv/vanilla-repositories/vanilla/vendor/vanilla/garden-container/src/Container.php:447
 /srv/vanilla-repositories/vanilla/vendor/vanilla/garden-container/src/Container.php:690
 /srv/vanilla-repositories/vanilla/vendor/vanilla/garden-container/src/Container.php:351
 /srv/vanilla-repositories/vanilla/vendor/vanilla/garden-container/src/Container.php:773
 /srv/vanilla-repositories/vanilla/library/core/class.gdn.php:137
 /srv/vanilla-repositories/vanilla/library/core/functions.general.php:3232
 /srv/vanilla-repositories/vanilla/tests/Library/Core/GeneralFunctionsTest.php:97
 /srv/vanilla-repositories/vanilla/vendor/phpunit/phpunit/phpunit:53
 ```

Another problem is that in our own tests we some time do not use the container to new up instances which is relatively problematic since we now mostly rely on the container to inject dependencies (This means that we shouldn't really care about constructors arguments anymore).
This could go in a separate issue I suppose.

**Comment by tburry** [comment]
#7289 should fix this.

**Comment by DaazKu** [comment]
All unit tests requiring proper bootstrapping now uses the BootstrapTrait.
