### ISSUE TITLE
addon.json doesn't support UTF8

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7227]
Many author names require UTF8 characters to put them in the addon file. Example:

```
    "authors": [
        {
            "name": "Felix Kütt",
```

Currently this simply breaks the addon.

Original report: https://open.vanillaforums.com/discussion/36255/prototyping-custom-themes-for-2-5-x-using-xampp-resolved#latest

**Comment by Megalomaniak** [comment]
A temporary solution might be to mention this in documentation. BTW I take it that broken links in docs should be reported to the docs repo?

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla-cli/issues/31

@Megalomaniak Reporting any broken links on that repo would be appreciated. I did a comb through of our logs a few months ago and fixed any broken links that people were actively visiting, but I guess I'm not too surprised that there are some links from less-visited docs that I didn't catch them.
