### ISSUE TITLE
Editor: update mimetypes list 

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7229]
# Details

Trying to upload a file with exntesion ("psd","swf", "doc", "xls", "ppt", "rar"), generates a "failed to upload" error.
[mimetypes.php](https://github.com/vanilla/vanilla/blob/master/plugins/editor/mimetypes.php) needs to be updated to cover more mimetypes for the mentioned file extensions.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/5994
