### ISSUE TITLE
Facebook SSO: Replace file_get_contents()

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7235]
Some servers block use of `file_get_contents()` (by setting `allow_url_fopen` to `false` in `php.ini`) so we should either avoid it or list it as a requirement. In this case, using cURL (preferably via `ProxyRequest()` or its successor) would sidestep adding this requirement in favor of one we already have.

Reported: https://open.vanillaforums.com/discussion/comment/252746/#Comment_252746

**Comment by zlorkovic** [comment]
I've made quick PR for this issue, using same cURL options which are used in other methods in this plugin.
https://github.com/vanilla/vanilla/pull/7233

**Comment by charrondev** [comment]
Fixed by https://github.com/vanilla/vanilla/pull/7233
