### ISSUE TITLE
Rich editor CSS is clashing with markdown code blocks

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7251]
Markdown formats code blocks with a `<pre><code>` wrap. Its looks as though the rich editor CSS is unaware of this and is formatting the `<code>` within the `<pre>` as if it was inline code.

Here is a screenshot including the offending rule.

<img width="1248" alt="code_formatting_ _t1" src="https://user-images.githubusercontent.com/97432/40500304-52a6dd7e-5f52-11e8-907b-f73fc6ed072c.png">

**Comment by slafleche** [comment]
@charrondev how difficult will it be to update the Quill objects? Do you think this is strictly a CSS problem, or we'll need to rewrite some of the code block objects?
