### ISSUE TITLE
2.6 gives 404 error during initial setup

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7258]
## Details

Vanilla-core-2-6 dowloaded from [open.vanillaforums.com/download](https://open.vanillaforums.com/download) fails during installation with a "404" error.

## 404 error

<img width="788" alt="screen shot 2018-05-25 at 11 25 26 am" src="https://user-images.githubusercontent.com/31856281/40552696-75276e10-600e-11e8-80ff-c66869812a95.png">

## Note

Completed the setup by renaming .htaccess.dist to .htaccess 
https://github.com/vanilla/vanilla/blob/20b7bdee817ad5c8e3ebfd5269df141541b3f5a8/applications/dashboard/controllers/class.setupcontroller.php#L70
### Tested using XAMPP

**Comment by whu606** [comment]
I have the same issue, and others have reported this on the community forum.

If you add /index.php?p=/dashboard/setup it goes to the installer screen, but then once the fields are completed and Continue id pressed, it reverts to dashboard/setup with a 404 error.

I was unable to complete installation using the 2.5 htaccess.

**Comment by linc** [comment]
Probably related to https://github.com/vanilla/vanilla/issues/7262

**Comment by linc** [comment]
Make sure we also resolve https://github.com/vanilla/vanilla/issues/7263 as part of this.

**Comment by DaazKu** [comment]
At some point [someone pointed out that when you update your vanilla installation we were overwriting .htaccess file](https://github.com/vanilla/vanilla/issues/2216) which can cause problems.

To address that issue we decided to rename .htaccess to .htaccess.dist and require people to update their .htaccess file with whatever is new in .htaccess.dist when upgrading.
**Huge potential of this causing problem if we add something important to the .htaccess.dist file**

We also added an option to rename .htaccess.dist to .htaccess when installing vanilla.

**~Oct 14, 2016** - Not too long after that we [changed urls to default to the "pretty" format](https://github.com/vanilla/vanilla/pull/4623) which essentially made it impossible to install vanilla on apache without an .htaccess to rewrite the URLs.

**~Jul 13, 2017** - We realized that this was a mistake and [reverted back to not rewrite URLs by default](https://github.com/vanilla/vanilla/pull/5740)

**~Jan 8, 2018** - [We reverted back the previous fix for some reason](https://github.com/vanilla/vanilla/pull/6279)

**Comment by DaazKu** [comment]
@initvector Ryan just pointed out to me that we could be breaking some nginx installation by not preserving the config (If they do not set X_REWRITE) in their nginx config.

**Comment by danno151** [comment]
I'm getting this too. I have not been able to fix it whatsoever. You can see everything that I've tried in this community discussion: https://open.vanillaforums.com/discussion/36386/vanilla-2-6-installation-issue-s/p1?new=1
