### ISSUE TITLE
New posts marker odd phrasing 2.5.2

### ISSUE THREAD

**Issue by pmmikes** [vanilla/vanilla#7261]
After updating to 2.5.2, threads with more than one unread post is marked as "[number] new plural", instead of "[number] new".
![screen shot 2018-05-26 at 15 11 36](https://user-images.githubusercontent.com/2046357/40577060-48ad5cf2-60f7-11e8-9e31-b0184e347a02.png)

edit: this is related to the default en locale.

**Comment by charrondev** [comment]
This is definitely not the case in Vanilla 2.8+.

![image](https://user-images.githubusercontent.com/1770056/54099507-0fbe6b80-4390-11e9-95a2-9ac1ffe3f425.png)
