### ISSUE TITLE
Rich Editor - Error with empty poll body

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7290]
I was working on the polls plugin and created a poll with no body text. I got an error right here https://github.com/vanilla/vanilla/blob/master/library/core/class.format.php#L2454

Polls in Vanilla are allowed to not have body text, so the text loaded for the poll is empty string, which is invalid JSON.

Not sure if this is for MVP or not, but it's incompatible with the polls plugin.

Maybe @charrondev can tell me if there would be problems to this solution, but since this is specific to the editor, maybe we can just add this:

```php
if (empty($deltas)) {
    $deltas = "{}";
}
```

**Comment by charrondev** [comment]
This is still an issue but no longer blocks the post. The following occurs and may be put back to blocking a post in the future.

![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/fd21000e-3ecb-44e4-a20f-1d464373fdbe)

As a workaround at the moment a user can add some content to their post.

**Comment by tburry** [comment]
Closes https://github.com/vanilla/support/issues/336
