### ISSUE TITLE
Maybe a bug at authentication method

### ISSUE THREAD

**Issue by cod3box** [vanilla/vanilla#7304]
Hi, after playing with vanilla the last 10 days i found a little bug regarding the authentication. Login and register forms shouldn't be accessible when a user is already loged in the site.
Steps to reproduce the issue: Log in on the site and then visit the link https://open.vanillaforums.com/entry/login or https://open.vanillaforums.com/entry/register

Those 2 pages shouldn't be accessible after successful user login. Maybe a redirect to the home page or a popup alert like "YOU ARE ALREADY LOGED IN" should do the trick.

PS I am not quite sure if this bug is already reported by other users

**Comment by charrondev** [comment]
This is intentional and not a bug.

@linc Seems to have the strongest feeling here, but this system allows users to change their account without having to sign in again.
