### ISSUE TITLE
/api/v2/users/:id get users by id email field is required

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7320]
## Details 

Calling endpoint /api/v2/user/:id with a user that does not have an email, returns
<img width="170" alt="screen shot 2018-06-05 at 7 39 31 pm" src="https://user-images.githubusercontent.com/31856281/41008279-32748600-68f8-11e8-97d2-85e9e82c8d8b.png">

<img width="351" alt="screen shot 2018-06-05 at 7 36 15 pm" src="https://user-images.githubusercontent.com/31856281/41008223-cdd65188-68f7-11e8-8fbd-95eef2fc498f.png">
 
https://github.com/vanilla/vanilla/blob/75d796b1c70001317daba29985538b712f825882/applications/dashboard/controllers/api/UsersApiController.php#L794

**Comment by topcheese13** [comment]
The criteria
---
If you have some users with no emails you probably have this configuration setting `Garden.Registration.NoEmail = true`.

The problem
---
Making an api call to /api/v2/users/{id} returns error message "email is required" in cases where user doesn't have an email.

The cause
---
We validate this api call with the fullSchema.
```
$schema = Schema::parse([
            'userID:i' => 'ID of the user.',
            'name:s' => 'Name of the user.',
            'password:s' => 'Password of the user.',
            'hashMethod:s' => 'Hash method for the password.',
            'email:s' => [
                'Email address of the user.',
            ],
            'photo:s|n' => [
                'minLength' => 0,
                'description' => 'Raw photo field value from the user record.'
            ],
            'photoUrl:s|n' => [
                'minLength' => 0,
                'description' => 'URL to the user photo.'
            ],
            'emailConfirmed:b' => 'Has the email address for this user been confirmed?',
            'showEmail:b' => 'Is the email address visible to other users?',
            'bypassSpam:b' => 'Should submissions from this user bypass SPAM checks?',
            'banned:i' => 'Is the user banned?',
            'dateInserted:dt' => 'When the user was created.',
            'dateLastActive:dt|n' => 'Time the user was last active.',
            'dateUpdated:dt|n' => 'When the user was last updated.',
            'roles:a?' => $this->schema([
                'roleID:i' => 'ID of the role.',
                'name:s' => 'Name of the role.'
            ], 'RoleFragment'),
        ]);
        return $schema;
```

Which makes the email being required.
