### ISSUE TITLE
Home page canonical URL

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7326]
Since by default, the home page in Vanilla is either /categories or /discussions, the canonical url on those pages defaults to /categories or /discussions. It should be just the root url.

For simplicity sake, I'm going to refer to the /categories page, but it also apply to /discussions or best of if that's what they chose as a home page.

There are 2 main cases I think we need to consider:
1. The client has alternate or additional content on the home page, which may merit having different canonical urls for the home page and the /categories page. Although rarer, it is possible
2. The client has the same content for the /categories and the home page. In which case we should: Fix the navigation (Breadcrumbs, navigation links in panel) and have a redirect to the home page from /categories.

Are there other edge cases? I feel like we should spend time fixing navigation. It's really important to our users and for SEO.

**Comment by adrianspeyer** [comment]
Good read on the topic: https://moz.com/blog/rel-canonical
