### ISSUE TITLE
Facebook Login: Domain not included in app domains 

### ISSUE THREAD

**Issue by PedroCavaleiro** [vanilla/vanilla#7340]
Hi, i'm having a really hard time setting up the Facebook Login
I keep getting this response

`{
   "error": {
      "message": "N\u00e3o \u00e9 poss\u00edvel carregar o URL: O dom\u00ednio deste URL n\u00e3o est\u00e1 inclu\u00eddo nos dom\u00ednios da aplica\u00e7\u00e3o. Para poderes carregar este URL, adiciona todos os dom\u00ednios e subdom\u00ednios da tua app ao campo Dom\u00ednios da App nas defini\u00e7\u00f5es da tua app.",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "Gtzbt720UpE"
   }
}`

Witch is the error "The domain of this URL is not included in the application domains"
I tried many things
I'm unable to disable strict mode on the facebook app settings
I'm forcing my website to use HTTPS
On the facebook app settings the API is set to v3.0 and I can't change it

I'm using vanilla forums 2.6

These are my app settings
![captura de ecra 2018-06-11 as 03 14 39](https://user-images.githubusercontent.com/1993871/41209829-dcd496cc-6d25-11e8-876d-7049df126e7a.png)
![captura de ecra 2018-06-11 as 03 14 46](https://user-images.githubusercontent.com/1993871/41209830-dcf36782-6d25-11e8-990a-e98ffea5211d.png)
![captura de ecra 2018-06-11 as 03 14 13](https://user-images.githubusercontent.com/1993871/41209831-dd11425c-6d25-11e8-967c-fd5701ac78e7.png)

**Comment by charrondev** [comment]
Hi, thanks for filing an issue. We try to use this issue tracker for tracking features and bugs for the product.

If you're looking for assistance configuring your facebook SSO I'd recommend the following:

- Check out our public documentation https://docs.vanillaforums.com/help/sso/social-connect/#facebook
- Head over to our open source forums and see if anyone in the community is able to assist you. https://open.vanillaforums.com
