### ISSUE TITLE
Unknown column 'd.discussionID in where clause' when bookmarking a discussion with a multisite setup

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7341]
## Details
Enable Subcommuntiy plugin
Bookmark a discussion

<img width="286" alt="screen shot 2018-06-11 at 1 40 39 pm" src="https://user-images.githubusercontent.com/31856281/41247793-27ecd7e4-6d7d-11e8-90c4-cae21dddc16f.png">

**Comment by LauraMakesArt** [comment]
@dannimajdalani and @francisbo Please make sure that you add additional details to this issue before you forget about them, we'll work on this next sprint.

**Comment by LauraMakesArt** [comment]
https://github.com/vanilla/vanilla/pull/7342#issuecomment-396402858

I believe Ryan's comments on this PR are relevant to this issue.

**Comment by topcheese13** [comment]
Should we also revert this PR https://github.com/vanilla/vanilla/pull/7342#issuecomment-396402858 (2 commits) from master ? @initvector @linc

**Comment by initvector** [comment]
I'd rather see the object pollution issues fixed on master, instead of rolling back the fix that exposes them.

**Comment by topcheese13** [comment]
As long as this is on somebody's radar, that we have this broken thing on master !

**Comment by initvector** [comment]
> As long as this is on somebody's radar, that we have this broken thing on master !

That's what issues are for! 😄
