### ISSUE TITLE
Add the $me smartID

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7344]
Smart IDs currently translate secondary keys to primary keys. One smart ID that would be very nice would be to have `$me` translate into the currently authenticated user's ID.

- If there is no signed in user then an exception should be thrown.
- The smart ID code might require a colon which would need to be changed.
- Since there is a custom `UserSmartIDResolver` the code can be added there.
- The smart ID docs need to be updated.
- Unit test.

**Comment by chrisvanpatten** [comment]
This would be really nice to be able to get the current user in APIv2: https://github.com/vanilla/vanilla/issues/6845

**Comment by charrondev** [comment]
Just for the record, that API endpoint is available as of Vanilla 2.8.
