### ISSUE TITLE
 Facebook: Blank page after signing in on embedded sites

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7345]
## Details
 
Using facebook social connect on sites with embedding enabled, displays a blank page with the error

```
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
Refused to display 'https://www.facebook.com/dialog/oauth?client_id=... in a frame because it set 'X-Frame-Options' to 'deny'.
```

Details in [Support #37](https://github.com/vanilla/support/issues/37)

**Comment by charrondev** [comment]
Workaround's detailed here https://stackoverflow.com/questions/14915152/loading-iframe-facebook-load-denied-by-x-frame-options
