### ISSUE TITLE
How to set roles when creating a new user through API

### ISSUE THREAD

**Issue by angeloudy** [vanilla/vanilla#7349]
I am trying to create lots of users with the API. But I couldn't set roles when creating user, nor can I update the roles after they were created.

Here's the python code I used to create users

```
    data = {
        'Name': username,
        'Password': password,
        'Email': email,
        'emailConfirmed': 'true',
        'showEmail': 'false',
        'RoleID': [36]
    }
    r = requests.post(api_url + '/users?access_token=' + access_token, data)
```
I am getting the following error message with the code above

```
{
    "message": "roleID is not a valid array.",
    "status": 422,
    "errors": [
        {
            "field": "roleID",
            "code": "invalid",
            "message": "roleID is not a valid array."
        }
    ]
}
```
I also tried replace ` 'RoleID': [36]` with  `'role': [36]` and `'role': [{'RoleID': 36, 'name': 'myrole'}]`, which successfully create the users, but the roles were not added.
I wonder the syntax of `        'RoleID': [36]` is wrong, if so, what's the correct syntax?

**Comment by angeloudy** [comment]
Fixed by adding `[]` to RoleID

```
    data = {
        'Name': username,
        'Password': password,
        'Email': email,
        'emailConfirmed': 'true',
        'showEmail': 'false',
        'RoleID[]': [36]
    }
```

**Comment by ari** [comment]
This really should be fixed in the vanilla API docs since it is very unexpected. Maybe you want to re-open it so the swagger model can be brought into sync?
