### ISSUE TITLE
2.5: Saving discussion drafts always fail

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#7350]
The problem comes from [here](https://github.com/vanilla/vanilla/commit/40da294a818a5ae2a48865c41da522e10e941a36#diff-6efe3c9a9ea0ea6ffab6d52f4cede153), as far as I can tell.

At [first](https://github.com/vanilla/vanilla/blob/release/2.5/applications/vanilla/controllers/class.postcontroller.php#L124) the session is defined with a lower case starting letter `$session` and [later on](https://github.com/vanilla/vanilla/blob/release/2.5/applications/vanilla/controllers/class.postcontroller.php#L245) it is used with an upper case `$Session`

I assume that the main reason is the usage of $Session in PostController comment() method.

**Comment by charrondev** [comment]
Fixed with https://github.com/vanilla/vanilla/commit/b032a35f2cab4b81e325b7d8ee6aea205879a941#diff-6efe3c9a9ea0ea6ffab6d52f4cede153

I'm not sure what release that was out with, but I think it was 2.6.
