### ISSUE TITLE
Themes cannot be defined as desktop and mobile themes at the same time

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#7363]
A Vanilla OS user is [creating a responsive theme](https://open.vanillaforums.com/discussion/36373/possible-to-make-a-responsive-theme-work-with-mobile-without-editing-config-php#latest) and would like to make it show up in "normal" themes and mobile themes at the same time (that's the sense of responsive design)

A theme addon has the `IsMobile` key to determine if it can be used as a mobile theme. But using that key automatically disqualifies it from being used as a desktop theme. 

<hr>

While `IsMobile` defaults to `false`, it might be possible to add a `IsDektop` key which defaults to `not IsMobile` , which would be `true` for current desktop themes and `false` for current mobile themes.

There's no reason why a theme shouldn't be a mobile and a desktop theme at the same time. So a theme could use both keys at the same time.

My first assumption is that only the SettingsController has to be changed when mobile/desktop themes are filtered like that (example for desktop themes):
~~~
            // Remove mobile themes, as they have own page.
            if (isset($theme['IsMobile']) && $theme['IsMobile']) {
                unset($themes[$index]);
            }
~~~
to
~~~
            // Remove mobile only themes, as they have own page.
            if (val('IsMobile', $theme) && !val('IsDesktop', $theme)) {
                unset($themes[$index]);
            }
~~~

If you are open to this approach, I would make a PR

**Comment by charrondev** [comment]
I'd imagine there will be a different solution to this in 2.8. 1st class support for a responsive theme is on the radar, and the will likely take the form of a value in the `addon.json` like `isResponsive`.

For now the simplest solution is to simply enable the theme as both the `Garden.Theme` and the `Garden.MobileTheme` at the same time.

This can be automatically done in themehooks.

```php
class MyThemeHooks extends Gdn_Plugin {
    /**
     * Run once on enable.
     */
    public function setup() {
        saveToConfig([
            'Garden.MobileTheme' => 'my-theme-key'
        ]);
		
		// Do other things in setup...
    }
}
```

**Comment by R-J** [comment]
Thanks for the extensive information. I was tempted to suggest "isResponsive", too, but I found that too limited. What if there will be another terminology for themes than can be used on desktop and mobile or if "responsive" isn't the right word for such theme.
In the end it should be named after its purpose and not the design pattern of one theme.
