### ISSUE TITLE
Recent changes to the dispatcher causes the tagging to disappear from discussion forms

### ISSUE THREAD

**Issue by topcheese13** [vanilla/vanilla#7364]
Referencing the 2 commits where the explained behaviour was created.
 
https://github.com/vanilla/vanilla/commit/7ccf037c42c1e94020ba3bbcea95e1962a5535ad
https://github.com/vanilla/vanilla/commit/55ffac0779e5ac59fb225780fc142fe8d7bd879c

`dispatchController()` => `findControllerMethod()` => `filterName()`

The fact that we now do this in the `filterName()` method
```
$result = implode('', array_map('ucfirst', explode('-', $name)));
```

We then assigned the result to `$controllerMethod` and `$controller->RequestMethod`.

This leads to the tag module to add tags under the discussion text area to be not displayed

https://github.com/vanilla/vanilla/blob/master/applications/vanilla/settings/class.hooks.php#L315

We compare the RequestMethod ('Discussion') with in_array to `['discussion', 'editdiscussion', 'question', 'idea']`.

This could possibly affect other things around the platform. I believe a possible fix would be to use
```
lcfirst(implode('', array_map('ucfirst', explode('-', $name))));
```
in the `filterName()` method, as we use camel casing with a lower letter first as a standard.

**Comment by charrondev** [comment]
The simple solution to this is not to check the `RequestMethod` on the controller. There is no good reason that check should be used.

We should be checking the theme section. All post pages have a section of `PostDiscussion` which is obtained through a call to `Gdn_Theme::section('PostDiscussion');`

This check https://github.com/vanilla/vanilla/blob/master/applications/vanilla/settings/class.hooks.php#L315 should be replaced with one like the following:

```php
// Section PostDiscussion will match idea, question, discussion, edit discussion, polls etc.
// This will still not work for polls because /post/polls does not fire "AfterDiscussionFormOptions".
if (inSection("PostDiscussion")) {

}
```

@cdepage I would have commented if I had noticed but this also would have handled https://github.com/vanilla/vanilla/pull/7066.

**Comment by linc** [comment]
@charrondev I believe you meant to tag @cchabilall83

**Comment by tburry** [comment]
I agree with much of what @charrondev said. However, I'm hoping the smaller change in #7444 will help us out as per @topcheese13's last suggestion.
