### ISSUE TITLE
Messages in profile's panel broken with config

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7373]
# Bug with messages in profile

## Steps to reproduce:

1. Create a message in `/dashboard/message`, set the page to "Profile Page" and position to "Below Side Bar".
1. Check that the message shows up on your profile page
1. Change your site settings to have `Garden.Profile.ShowActivities: false`.
1. Refresh your profile page, the message is gone.

## Expected behaviour:
The message should be there for all profile pages

**Comment by charrondev** [comment]
The issue is actually unrelated to that flag specifically and can be reproduced by going to any profile page other than activity. The check here should be similar the pockets check for profile page and show up everywhere on the ProfileController.
