### ISSUE TITLE
How to set someone as Banned via API v2?

### ISSUE THREAD

**Issue by garygreen** [vanilla/vanilla#7379]
Currently it doesn't seem possible to set someone as banned in the API - you can assign the "Banned" role, but not the specific ban flag.

![image](https://user-images.githubusercontent.com/1702638/41731588-abcfeb54-7576-11e8-914d-a5754accc26a.png)

**Comment by charrondev** [comment]
Not sure exactly when this was implemented. I think in 2.7, but with 2.8 APIv2 definitely can ban users.

![image](https://user-images.githubusercontent.com/1770056/52391158-e4cbb980-2a69-11e9-892d-7ad78687e904.png)

**Comment by garygreen** [comment]
@charrondev that's different. I understand you can ban people with the dedicated API but you CANNOT set the "Banned" attribute on the actual user. Maybe there is a discrepancy there?

**Comment by garygreen** [comment]
Nevermind, actually. I think it maybe a new API route as when I was last testing this I think I set it as a banned role as opose to using the dedicated API.

**Comment by charrondev** [comment]
Looking a little deeper this was actually put in 2 years ago but maybe just didn't get documented properly? As far as I can tell PUT `/api/v2/users/:id/ban` has always explicitly set the `Banned` flag on the user record.

**Comment by garygreen** [comment]
Excellent, thanks a lot for the info 👍
