### ISSUE TITLE
Update Checkbox/Radio button Markup

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7386]
We've got themes that are using jQuery plugins for style checkbox/radio button styles. We want to get rid of these plugins and replace them with a CSS only solution.

Steps to update:

- [ ] Modify Vanilla checkbox render function with new markup. We're not changing all of it, we'll be adding some new classes and adding a few new elements inside for styling. The new elements will be hidden by default. The goal here is that it will **look the same**, after this change
- [ ] Add SCSS partials in core to support a few different checkbox/radio button styles. We'll need styles for the different looks for our core themes
- [ ] Update Core themes to not use checkbox plugin and include style partial with the style they want.
- [ ] Inform support and explain upgrade path for older themes

**Comment by charrondev** [comment]
Closing as we've settled on just using using the default checkbox for keystone. If we get mockups for our next core theme that includes custom check boxes we can revisit at that time.
