### ISSUE TITLE
Is there a need for AccessToken.DateExpires default to current timestamp?

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#7388]
There are some hosting services which only offer MySql version which do not allow to have a table with more than one CURRENT_TIMESTAMP default value.
The only table definition that requires this is for [AccessToken](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/settings/structure.php#L280-L292) (DateInserted and DateExpires).

When a token [is issued](https://github.com/vanilla/vanilla/blob/master/library/core/class.accesstokenmodel.php#L43-L54) i.e. a table entry is created, a DateExpires date is created with the php script so that the default value is not needed. Removing that default value in the Database would do not change functionality and would keep minimum requirements low.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/8128
