### ISSUE TITLE
[MySQL Strict Mode] User additions and user edits break with at least 1 manually applicable rank

### ISSUE THREAD

**Issue by topcheese13** [vanilla/vanilla#7390]
<img width="1026" alt="screen shot 2018-06-26 at 11 24 58 am" src="https://user-images.githubusercontent.com/15312192/41922660-9a30af62-7933-11e8-8ccc-a382944f8b02.png">

It breaks because of strict mode but it's also faulty.

We fetch only manually applicable ranks in the form, so we shouldn't be updating this part of the record when the first empty option is selected. Even updating to a `NULL` is wrong as the user might have an automatically applied rank already assigned to him. We don't want to overwrite that with a NULL, so solution is to not update ranks when the empty option of the select box is selected or fetch all ranks even the ones that aren't manually applicable and update the record properly.

Same thinking applies when we create a user.

**Comment by topcheese13** [comment]
The Criteria
---
* Ranks enabled
* At least one manually applicable rank.

The problem
---

This problem has 2 parts.

1. Creating a user or editing one, prompts you with the a form. Both forms have a select box for rank. The select box includes an option like this one `<option value=""></option>`, the other options are the manually applicable ranks. For example `<option value="111">test</option>`. The first problem we have with this that has nothing to do with MySQL strict mode is, if you only want to edit, let's say, a username, we still send the form with the select option `<option value=""></option>` for rank. Which updates the user with a RoleID to 0. There is a possibility we just overrode a that was automatically given to the user as those ranks aren't part of the select box.

2. The strict mode problem, fixing problem 1 could potentially handle problem 2. With strict mode enabled you can't insert an empty string in an integer column which make any create/edit a user operation fail when you leave the select box on the `<option value=""></option>` option. 

The possible solution
---

1. Include all ranks in the form, even the none manually applicable one and fix our code to insert NULL when the `<option value=""></option>` is selected. I'm assuming that this isn't what we are looking for.

2. Showing the current rank as the selected option even if it's not manually applicable. Keeping the empty select box option but inserting a NULL when selected.

**Comment by topcheese13** [comment]
@tburry, @linc wanted me to run this by you, to see what's acceptable to you and maybe draw up a simple markup of the solution.

**Comment by tburry** [comment]
Here is what I should do.

1. Assigning the user an empty rank should cast it to null.
2. Assigning a user a null rank should only be done if they currently have a rank that is applied manually. This check can be done in the model maybe.

**Comment by topcheese13** [comment]
Shouldn't this be a low level mysql fix, where we always default to NULL on empty strings for inserts and updates ?

**Comment by tburry** [comment]
That's only the case for non-string fields and I do believe the model does this in some cases. There must be a bug there somewhere with ranks.
