### ISSUE TITLE
Visiting Layout page introduces invalid setting in config.php

### ISSUE THREAD

**Issue by francosolerio** [vanilla/vanilla#7392]
On a fresh install of Vanilla 2.6, opening the Layout panel of the Settings page (even before making any change or committing with save) a wrong setting is introduced in conf/config.php that makes the root of the forum unavailable with a big custom Page Not Found message.

The original config file has:
`$Configuration['Routes']['DefaultController'] = 'discussions';`

After visiting Layout the same line becomes:
`$Configuration['Routes']['DefaultController'] = array('', 'Internal');`

If I manually edit the line and restore the original line, the homepage is accessible again. But as soon as I go to the Layout panel, the file gets messed up again.

System info:
Ubuntu 16.04.4 LTS
PHP 7.2.7

Steps to reproduce:

1) Download and unzip the Vanilla package
2) Compile the form with the database settings etc
3) Access the homepage (everything works)
4) Access Dashboard
5) Click on Settings and select the Layout page on the left
6) Access the homepage of the forum -> PAGE NOT FOUND

**Comment by charrondev** [comment]
It might be a good idea to resolve https://github.com/vanilla/multisite/issues/154 at the same time as this.

**Comment by twenster** [comment]
I confirm this bug is still available in version 2.6.4.
Also, when saving the layout, $Configuration['Garden'] array is rewritten and emptied.
