### ISSUE TITLE
Add granular configuration options for content embeds and dashboard configuration

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7452]
Blocked by https://github.com/vanilla/vanilla/issues/8299.

I'd like to be able to implement 1 UI for all formats.

Vanilla could use a new top level dashboard page that allows particular embeds to be toggled on and off. Each embed would get it its own configuration option ex. `Embeds.Codepen.Enabled`.

These options could then be exposed in a new top level dashboard page for embeds.

**Comment by vrjrobitaille** [comment]
Hey Adam! Also very much agree with this. Having a means to granularly configure which embeds you'd like to allow would be a great feature for us to add in the future, I know of a few customers that would be happy about this. I've added this to our PM Backlog, but will close this out in Git so we can keep this Git Roadmap a little more focused on the shorter (2-4 month) term.
