### ISSUE TITLE
Update Vanilla Default Master

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7460]
Smarty needs features to enable dynamic layouts in views.

- Register a new custom resource that can search for files within a theme. To start new layouts are only allowed in the dashboard app.
    - (see "registerResource" function)
- Force views to be rendered with `$escape_html = true` to prevent XSS attacks in the future.
    - Main views will always escape HTML. This does break BC, but there are not any views developed in smarty. We need to check though. Gdn_Controller or Gdn_Smarty should be able to handle this.
    - Create a tag to make a view opt-in/opt-out of HTML escaping at the template level.
    - Because Knowledge will use Smarty views, we will probably need new smarty functions to support the functionality required by a full view. Stephane can do that as it goes.
        - New filters for output formatting.
        - New block helpers for wraps.
- Views can/will extend a layout. Layouts are defined in resources/views
- Controllers using new layout will set a meta that will be used to do $_NoPanel. This is a basic level of compatibility.
    - This will tell views to use blocks.
- There are page layouts and widget layouts.
    - Page layouts are one a page. Widget layouts can be repeated.
    - Page layouts are extended by views.
    - All layouts will not include old assets.
    - Widget layouts may be implemented as block helpers instead.
- We need to add features to make sorting of assets easier.

**Comment by charrondev** [comment]
The full scope of this issue is no longer relevant as we are doing our frontend views in React. No smarty or custom systems required.
