### ISSUE TITLE
Releases page does not contain 2.5.2 and 2.6 version same way as it is for 2.5.1

### ISSUE THREAD

**Issue by bojars** [vanilla/vanilla#7505]
Looking at https://github.com/vanilla/vanilla/releases page I see that version 2.5.1 includes such statement: "Hey! Use the attached vanilla-2.5.1.zip to complete the upgrade steps in the README, not the "source code" versions. Otherwise you're on your own." But for 2.6 I can find only source code versions, does it mean 2.5.2 and 2.6 versions are not yet verified (not safe to use)?

**Comment by charrondev** [comment]
I'd recommend taking a look here. Please use the latest version that you can from that page.

https://docs.vanillaforums.com/developer/changelog/

Versions less than `2.5.2` are missing some important security patches. The `2.5.x` branches are the last Vanilla version to support PHP 5.6 so it has receive backported security patches. It will not receive them indefinitely. 

---

We're going to need to decide what we want to do with the Github releases tab. We haven't kept it up to date, so we can either:

- Be stricter about updating it in tandem with our open.vanillaforums.com releases and docs updates.
- Remove the github releases tab
- Tag a release with details that all future releases will be noted on our Docs site.

**Comment by bojars** [comment]
Thanks for reply. I do not mind release page you mentioned, however github releases page have advantage that I use - changing only version number in link to download archive gives content for chosen version without need to go to page and figure out url - makes it easier to maintain setup I have with Docker.

Now have such link where VANILLA_VERSION is replaced 

> https://github.com/vanilla/vanilla/releases/download/Vanilla_${VANILLA_VERSION}/vanilla-${VANILLA_VERSION}.zip

But to use latest version have to change whole URL, that does not have any version indication in url as such

**Comment by linc** [comment]
The releases page needs to be updated.

**Comment by charrondev** [comment]
Later versions of the `2.5` and `2.6` branches have been tagged and added to the releases page.
