### ISSUE TITLE
Embedding of same site does not work with private communities

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7512]
Moved from @adrianspeyer https://github.com/vanilla/vanilla/issues/7162#issuecomment-406023147

### Description
Links on own domain, if for a closed category, the preview is not descriptive enough.

### Issue severity
Moderate --  lots of support based communities that are SSO and for only paid customers will be an issue.

### Steps to reproduce
1. Paste link from a non-guest available category

### Screenshot (if applicable)
![image](https://user-images.githubusercontent.com/425366/42899382-da71c022-8a93-11e8-9957-8312197ea6a4.png)

**Comment by initvector** [comment]
This is being rolled into #7521
