### ISSUE TITLE
Link embeds not showing their Title in rendered view

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7513]
### Description

Facebook doesn't recognize our User Agent header (I'm sure other sites don't either). We should be using a user agent header that will get sites to give us the same thing other do.

### Issue severity

Minor. Sites shouldn't be checking UA headers anyways.

### Steps to reproduce

1. Try to embed a public facebook link.

### Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/1770056/42967556-9ff41f04-8b6e-11e8-836e-34e9ecd442a4.png)

**Comment by cchabilall83** [comment]
Closed by #7531
