### ISSUE TITLE
Rich Editor link validation needs improvement

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7514]
Validation of links inputted in these menus should match how the server validates the links.

- Links must have a protocol of http, https, tel, or mailto
- This should apply for the link input, automatic link detection conversion, and embed insert menu. See `isValidUrl()`.

**Comment by tburry** [comment]
Is this issue fleshed out enough to bump to **ready to sprint**?

**Comment by charrondev** [comment]
Probably not. I didn't really put enough detail on it. I don't remember exactly what's wrong at this point besides it allowing URLs without protocols. I'll need to test it a bit.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/7599
