### ISSUE TITLE
Touchscreen text selection menus conflict with Rich editor inline menu

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7518]
### Description

Inline menu conflicts with device copy/paste menu for devices with inline copy/paste menus (eg. iOS/windows in touch mode). Strategy required.

### Issue severity

Medium

Why medium?

- You can scroll and the inline menu is still accessible.
- iOS puts some inline formatting items in its own menu.

### How do other editors deal with this issue

They don't. Not other editor I could see handles inline menus well for this. They all either

- Don't offer a mobile experience.
- Don't offer inline formatting on mobile (but what about midsize touch devices such as iPads? Do we care?).
- Require native mobile apps instead of a web experience.
- Allow both menus to overlap.

### Steps to reproduce

1. Use the editor on an iPad (I'm unsure if this applies to windows touchscreen devices).
2. Make a text selection
3. Observe the overlapping copy/paste and inline formatting menus.

### Screenshot (if applicable)

![image](https://user-images.githubusercontent.com/1770056/43089334-5acf3cc2-8e72-11e8-8282-fc49b0fe83d5.png)

## Proposed solution

Have the contextual menu be fixed at the top where the normal menu for embeds, paragraph formatted is. Have it replace those when there is a selection.

**Comment by tburry** [comment]
Closes https://github.com/vanilla/support/issues/213

**Comment by charrondev** [comment]
@tburry What do you think of doing what we did with the paragraph menu and just putting it in the embed bar on mobile?

**Comment by tburry** [comment]
Questions:

1. We moved the embed bar up top right?
2. Does the embed bar stick on mobile?
3. Could this be a mobile-only feature?

I think if we can answer yes to those questions then I am for it.

**Comment by charrondev** [comment]
> We moved the embed bar up top right?

In KB. It's still on the bottom for the forum.

> Does the embed bar stick on mobile?

Only on KB.

> Could this be a mobile-only feature?

Having formatting in the embed bar is currently exclusively on mobile. I can imagine it would be the same for the inline one.

---

After a little investigation though it seems we have visual issues with the mobile versions:

![image](https://user-images.githubusercontent.com/1770056/62224934-75ce7e00-b385-11e9-82de-caea1691044a.png)

![image](https://user-images.githubusercontent.com/1770056/62224948-7f57e600-b385-11e9-98ca-bd5a68886a6a.png)

**Comment by tburry** [comment]
I'm guessing the complaints are on the forum side and we'll need a bit more of a rethinking for that.

**Comment by charrondev** [comment]
Another report here: https://github.com/vanilla/support/issues/1131
