### ISSUE TITLE
Add rich format to advanced editor dropdown conditionally

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7527]
When rich editor is enabled the advanced editor dropdown is disabled and the current format being use is displayed.

**Comment by cchabilall83** [comment]
@charrondev 
If the advanced editor is enabled will the rich editor be disabled?

**Comment by charrondev** [comment]
Current acceptance criteria from @tburry and @linc 


1) Enabling Rich Editor adds 'rich text' to the formatting dropdown in the advanced editor plugin and auto-selects it.
2) Selecting a formatting option other than 'rich text' functionally disables the Rich Editor (new posts default to whatever format is selected).
3) Rendering for all formats including rich still work even if they are not the currently selected main format. (This is already the case. You should not have to change anything to make this happen).

**Comment by charrondev** [comment]
@tburry I'd like to add one more success criteria here. Since multiple plugins are now contributing to available formats, we should move that formats dropdown out of the advanced editor plugin and into the "Posting" page of the dashboard. Plugins such as the rich editor and advanced editor could then add their formats to that list.

**Comment by cchabilall83** [comment]
@charrondev The last success criteria should be put into it's own separate issue as it would change the complexity of the current issue.
