### ISSUE TITLE
Rich Editor - Creating a link in a long post scrolls to top of page

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7568]
Steps to reproduce:

1. Make a long post
2. Scroll down
3. Create a link in your post on the bottom, hit "enter"

Result:
You jump to the top of the page

Expected result:
keep my place

May be related or the same bug as: https://github.com/vanilla/vanilla/issues/7567

**Comment by charrondev** [comment]
Resolved as of 2.8
