### ISSUE TITLE
Rich Editor - Pasting Inside Code Block 

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7569]
Steps to reproduce:

1. Create a new code block (or edit an existing one and select all the contents)
2. Paste some real code

Example
```
{  
      "insert":{  
         "embed-external":{  
            "data":{  
               "url":"https:\/\/imgur.com\/gallery\/arP2Otg",
               "type":"imgur",
               "name":null,
               "body":null,
               "photoUrl":null,
               "height":null,
               "width":null,
               "attributes":{  
                  "postID":"arP2Otg",
                  "isAlbum":false
               }
            },
            "loaderData":{  
               "type":"link",
               "link":"https:\/\/imgur.com\/gallery\/arP2Otg",
               "loaded":true
            }
         }
      }
   }
```

Result:
Only the last line is in the code block

Expected result:
The whole paste would stay in the code block.

Hypothesis:

I suspect because we have special handling of new lines in the code block, it interprets the new lines of the code the same as pressing "enter".

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8136
