### ISSUE TITLE
Rich Editor - Large posts error out with no message

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7570]
I originally came across this issue editing an old post, so I thought maybe I had some bad data, but it happened again in a new post.

Steps to reproduce:
Use this delta and try to save your post:
[delta.txt](https://github.com/vanilla/vanilla/files/2270215/delta.txt)

Note that there's an empty "error" up top (that you don't see without scrolling by the way, should be a popup or make it visible somehow).

<img width="867" alt="screen shot 2018-08-08 at 08 36 29" src="https://user-images.githubusercontent.com/19651440/43837336-2e6a7a2c-9ae6-11e8-8d50-2734482fbbb9.png">

Expected result:

I expect to save, but if there's an error because of the size of my post, I expect to see it. There's no visible feedback after hitting post and there's no error.

**Comment by vrjrobitaille** [comment]
Mercy Ships reporting this on staging. Glad to hear you've got it.
