### ISSUE TITLE
Rich Editor - Hitting Return 2 times to escape formatting should put you on a new line

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7580]
**Applies To:** All block formats except plain paragraph.

When I hit return 2 times to escape a formatted block and there is text below then the last return should enter  new line rather than putting me at the beginning of the next piece of text. Currently, it puts me in the next block.

## Steps to reproduce

1. Format some text as a quote.
2. Immediately after the quote format some text as a spoiler.
3. Go back to the end of the quote.
4. Hit enter twice.

The quote is escaped, but I am now in the spoiler. I should be in an empty line between the quote and spoiler.

- [x] Headings work fine.
- [ ] Spoilers don't add the empty line to any of the other formats.
- [ ] Quotes don't add the empty line to any of the other formats.
- [x] Code blocks work as expected.

**Comment by bleistivt** [comment]
In addition to this, could an empty line be added, every time a block gets turned into a quote/spoiler?

I know that you can just hit return twice or press the arrow down key. But it was very confusing to me, when I first tried out the editor.

I quoted the only paragraph that I had written and then tried clicking below it to set the cursor there, which didn't work as there was no empty line. This is probably also what most users will try.

Popular text editors (like google docs) always allow you to click below your content to set the cursor to the end of the document.

**Comment by charrondev** [comment]
@bleistivt I think something like https://github.com/vanilla/vanilla/issues/7597 would satisfy that right?
