### ISSUE TITLE
'You' Reference in Activity still pointing to /profile/You (open.vanillaforums.com)

### ISSUE THREAD

**Issue by prdgymx** [vanilla/vanilla#7585]
As similarly referenced in #2989 and #3157 - on the https://open.vanillaforums.com/activity page immediately after a recent registration I am still being directed to https://open.vanillaforums.com/profile/You when clicking on the activity noting my own registration while logged in.

I am assuming the installation here is the most recent version.

**Comment by bleistivt** [comment]
Note that these activity sentences are literally untranslateable in languages where the verb has to change accordingly. I have completely dropped `{RegardingUserID,You}` in favor of `{RegardingUserID,user}` and replaced every verb with an arrow (e.g. `&rarr;`) in my local translation. This also avoids the issue.
