### ISSUE TITLE
Rich Editor - Reorder paragraph menu

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7587]
I just want things reordered a bit. The order I want is:

- H2
- H3
- Quote
- Spoiler
- Code block
- Paragraph

**Comment by bleistivt** [comment]
I know this has been changed before (#7517), but "H2" and "H3" is not intuitive for non-technical users. People will wonder why they can not use H1. As far as the user is concerned, what is actually an `<h2>` is the largest heading that can be added in a comment and thus should say "H1".

**Comment by charrondev** [comment]
Longer term I think it will end up as big T and little t for title and subtitle. There are plans for some larger changes to the line level formatting menu.

We intend to iterate a bit after this initial release of Rich Editor.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/8434
