### ISSUE TITLE
Rich Editor - Spoiler heading inconsistency

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7589]
We changed the wording in the spoiler warning, but it doesn't seem to be updated in the editor:

<img width="788" alt="test_formatting_ _t1" src="https://user-images.githubusercontent.com/97432/43913274-a31a6746-9bd2-11e8-9b23-349559047b90.png">

The correct text is **Spoiler Warning**.

**Comment by charrondev** [comment]
I'm labelling this as enhancement because that was the previous specification (the other one you are looking at is advanced editor text in keystone).
