### ISSUE TITLE
Test Email Notifications from Rich Editor Posts

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7592]
@slafleche commented on [Tue Jul 31 2018](https://github.com/vanilla/rich-editor/issues/92)

We never did any testing with e-mail notifications from rich editor posts.

@adrianspeyer reported an issue with images leaving big gaps... We may need a simplified rendering of embeds for e-mails.

**Comment by adrianspeyer** [comment]
please also see this new issue:
https://github.com/vanilla/vanilla/issues/7678
HTML elements in notifications
