### ISSUE TITLE
Rich Editor - Embed icon too similar to codeblock

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#7609]
I feel that the icon for embed links is too similar to the code icon.

Also, what's the purpose of the menu?
If I would use the editor as it stands right now, I would probably hide it, since links are already turned into embeds when pasted.

**Comment by charrondev** [comment]
The explicit UI is there for the same reason that bold and italic formatting options are there. While you and I may be power users and comfortable with a keyboard shortcut for various options, for some users these shortcuts are unknown. A few other use cases

- Partially sighted or visually impaired users. Explicit UI is generally better for accessibility.
- Mobile users who are less likely to complete a Paste + Enter key combo.

**Comment by charrondev** [comment]
Here you can see the icons used in the latest `master` branch. This will be the icon set for the 1.0 release of Rich Editor.

![image](https://user-images.githubusercontent.com/1770056/51813948-e2f24100-2286-11e9-9c79-54bc11e6722c.png)
