### ISSUE TITLE
安装2.6遇到数据库问题：Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

### ISSUE THREAD

**Issue by 464979532** [vanilla/vanilla#7630]
![11](https://user-images.githubusercontent.com/3524108/44127536-52580e06-a070-11e8-894b-431e71cd5a88.jpg)

**Comment by charrondev** [comment]
Vanilla is not currently strict mode compliant. Please see the self hosting requirements. https://github.com/vanilla/vanilla#self-hosting-requirements

Related #5177 https://github.com/vanilla/vanilla/issues/7425

If you have additional details to add to this issue feel free. Strict mode compliance is something we would like to work towards, but is not an immediate priority.

Even if it were a single screenshot does not make an actionable issue so I'm closing this.
