### ISSUE TITLE
Rich Embed - 500 error embedding youtube home page

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7633]
Steps to reproduce:

1. paste "https://www.youtube.com/" in editor
2. Hit enter

Expected result:
It should be an embedded link

Actual result:

<img width="877" alt="screen shot 2018-08-15 at 10 16 42" src="https://user-images.githubusercontent.com/19651440/44152758-5881d8b2-a074-11e8-9919-78bd8335b323.png">

**Comment by tburry** [comment]
I can no longer reproduce this.
