### ISSUE TITLE
Rich Editor: Notification Popups & Emails for Private Conversations contain JSON

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#7678]
Using Rich Editor:
Started a personal conversation and sent messages show HTML Elements
![image](https://user-images.githubusercontent.com/425366/44667267-53e7b100-a9e8-11e8-8f51-394fbbe1d487.png)

Both in the Growl
![image](https://user-images.githubusercontent.com/425366/44667222-3286c500-a9e8-11e8-9cce-8326b792e316.png)

And the email the person receives.

@charrondev not sure this is the right place for reporting this issue, so please move as appropriate.

**Comment by adrianspeyer** [comment]
Steps to reproduce:
1. Rich editor enabled
2. Send a private message with bold, strike through or line breaks
3. Both email and pop-up notification in Vanilla will send with attributes.

**Comment by charrondev** [comment]
Fixed in emails, but not in notifications. We just need to run `Gdn_Format::excerpt` on the notification output.
