### ISSUE TITLE
Deprecate global c() function and get rid of calls to that where is possible

### ISSUE THREAD

**Issue by alex-mtl** [vanilla/vanilla#7688]

**Comment by R-J** [comment]
What about `saveToConfig()` and `touchConfig()`?

If the only reason for deprecating `c()` is a performance reason, than it wouldn't be needed to replace those two. But on the other hand, if there is no "read from config" shortcut, it wouldn't be consistent to keep them.

If you want to get away from global functions - and that seems to be the main reason - then they should be deprecated, too.

**Comment by alex-mtl** [comment]
@R-J Long term goal is to get rid of all global functions. c() and t() in the first place just because they are widely called everywhere and we need much more time to investigate and refactor.

I think you are right we can do saveToConfig() and touchConfig() deprecation in parallel.
