### ISSUE TITLE
Update StopForumSpam documentation & description

### ISSUE THREAD

**Issue by topcheese13** [vanilla/vanilla#7690]
You basically need to read the code to know what this plugin is doing.

There is no readme and the addon.json file is only adding to the confusion for me

>"description": "Got spammer problems? This integrates the spammer blacklist from stopforumspam.com to mitigate the issue.",

StopForumSpam is only looking for spam on registration.

**Comment by charrondev** [comment]
The plugin checks emails & ips against an API of known spammers and blocks them from registering. Seems pretty straightforward to me.

**Comment by topcheese13** [comment]
> The plugin checks emails & ips against an API of known spammers and blocks them from registering.

 Which you wouldn't know from the addon doc/description.
