### ISSUE TITLE
Recursive class lookups from the root of an addon do not work

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7702]
Due to `''` not being an actual path, recursive lookups were not happen so classes that are not in the explicitly defined folders are not working. This means a class place in say a top level `Utils` folder will not be loaded. I'm mainly looking for acceptance criteria of a fix for this.

### Remove the root lookup

If we decide we only want to classes to be in specific subfolders than we should removed the first `''` entry because it doesn't match anything and gives the _impression_ that you can have classes in the root.

### Allow lookups from the root

If we want to allow classes to be looked up from the root the primary reason would likely be to allow cleaner namespacing:

Eg:

```
Vanilla\Addons\SomeAddon\Utils -> /vanilla/plugins/some-addon/Utils

// instead of

Vanilla\Addons\SomeAddon\Utils -> /vanilla/plugins/some-addon/library/Utils
```

If we do this though we may need to add exclusions for these lookups. We don't want to be looking in folders such as `node_modules`, `bower_components`, or `vendors`.

### Start all namespaces in a single directory

The biggest reason why a library folder feels a little bit weird is that your structure ends up like the following:

```
/vanilla/plugins/some-addon/library/Utils/MyUtils.php -> Vanilla\Addons\SomeAddon\Utils\MyUtils
/vanilla/plugins/some-addon/controllers/MyController.php -> Vanilla\Addons\SomeAddon\Controllers\MyController
/vanilla/plugins/some-addon/models/MyModel.php -> Vanilla\Addons\SomeAddon\Models\MyModel
```

The primary issue here is that we have things of the same namespace with different gaps based on the pre-whitelisted folder. Instead something like:

```
/vanilla/plugins/some-addon/library/Utils/MyUtils.php -> Vanilla\Addons\SomeAddon\Utils\MyUtils
/vanilla/plugins/some-addon/library/Controllers/MyController.php -> Vanilla\Addons\SomeAddon\Controllers\MyController
/vanilla/plugins/some-addon/library/Models/MyModel.php -> Vanilla\Addons\SomeAddon\Models\MyModel
```

Would map more consistently.

**Comment by tburry** [comment]
We need to make classes in the root work. I'm reluctant to search every subfolder, but perhaps we can search all subfolders that:

1. Match our current whitelist or:
2. Begin with a capital letter to match our namespace convention.

There are unit tests around all of this so adding new functionality should be fairly straightforward.

**Comment by charrondev** [comment]
So acceptance criteria for changing the implementation of this function:

## Classes will be auto-loaded from a plugin if:
- The filename ends with `.php`.
- The file exists in the top level of the plugin.
- The file exists anywhere recursively in a top level directory beginning with a capital letter.
- The file exists anywhere recursively in a top level directory named one of following: 
  - `controllers`
  - `library`
  - `src`
  - `models`
  - `modules`
- Filename/filepath is `/settings/class.hooks.php` in the root of the plugin
