### ISSUE TITLE
Pull framework/library/editor js/css of out of dashboard application

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7708]
## Dashboard

A few pieces in particular here are "global"/framework related and not really part of the dashboard specifically. In my mind these are:

### JS
- Top level JS utilities live `application`, `dom`, `utility`, `embeds`, `apiv2`, `permissions`.
- `bootstrap` file.
- some parts of the `components` folder.
- Everything in `user-content`

### Styles
- Variable sheets (primary one and editor)
- embed styles
- User related styles from authenticate page
- Editor styles that are not forum specific. These should be moved to the rich-editor plugin.

**Comment by slafleche** [comment]
Is this part of this sprint? I won't have time this sprint.

**Comment by charrondev** [comment]
Closed by #7751
