### ISSUE TITLE
Emoji fallback replacing trademark character

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#7710]
A client reported this issue: https://github.com/vanillaforums/ea/issues/117

It seems on the latest version of IE and Edge there's a fallback for emojis that it's getting in the way of the browser render special characters (like "trademark" for example).

@slafleche mentioned that this fallback should only target `.userContent`

**Comment by vrjrobitaille** [comment]
I have a client building their own theme that's run into this issue. Is there anything we need to do or anything they can do to get passed this issue?

**Comment by charrondev** [comment]
There isn't any manually workaround for this. It just needs to be fixed. Escalate it to support if it's a pressing issue.

**Comment by slafleche** [comment]
We have a function that searches for emojis and replaces them for Browsers without full native support.

There are 2 issues we have now. One of them is that our current check doesn't work properly in latest Chrome. I suggest looking at what Modernizr is doing. See https://github.com/vanilla/vanilla/issues/8132

The other problem is we're looking through the entire page. We should limit the scope of the search to elements in `.userContent` classes.

Test no longer working: https://github.com/vanilla/vanilla/blob/master/library/src/scripts/dom.ts#L245

Modify to only target user content, using the `.userContent` class: https://github.com/vanilla/vanilla/blob/master/library/src/scripts/user-content/emoji.ts#L11

**Comment by nervoustwit** [comment]
I'm not sure @slafleche 's suggestion of only targeting .userContent is the best idea if that does not include titles and navigation. The client who noticed this his trademark imojis all over their navigation. (see: https://battlefront-forums.ea.com/)

I was able to fix their display with CSS in javascript. I think getting the test to work again would best be handled by R & D.

**Comment by slafleche** [comment]
@nervoustwit What are the issues with .userContent? You could target anything else separately for a theme. 

I'm not suggesting you write your own test. I took that from Modernizr's test. I suggested you look up what they're currently using for checking emoji support and use that.

**Comment by slafleche** [comment]
I haven't tested, but looks like Modernizr uses the following now:

```JS
emojiSupport = () => {
  var ctx = document.createElement("canvas").getContext("2d");
  ctx.fillText("😗", -2, 4);
  return ctx.getImageData(0, 0, 1, 1).data[3] > 0;
};
```
