### ISSUE TITLE
UserModel::connect does not relax username validation for trusted SSO providers

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#7713]
#7250 introduced several improvements to username validation. One of the key portions was tightening username requirements, in general, while still allowing trusted SSO providers to have more lax username validation. The allowances for trusted SSO providers were primarily added to `EntryController::connect`. However, embedded SSO uses its own connection method: `UserModel::connect`. This method does not seem to have the same allowances for trusted SSO providers. They will need to be added.

**Comment by linc** [comment]
You'll also want to know about this for reference: https://github.com/vanilla/vanilla/pull/7677
