### ISSUE TITLE
Move to JSON-based config

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7719]
Vanilla currently uses a PHP-based config which writes valid PHP code in form of an associative array (`$Configuration`) that is nested ~3 levels deep. This creates a very easy-to-load system but writing PHP code with an application is inherently insecure.

We've begun moving our complex stored data to JSON encoding, including our `Attributes` fields. We moved our cloud configs to use JSON many years ago, and it's time to make that a core feature of the application.

This would be a prime opportunity to reevaluate generally how we interact with the configuration, including perhaps using the new base model.

### Acceptance Criteria
* Create a `conf/config.json` file as the new "source of truth" for forum configuration.
* Migration our defaults to `conf/config-defaults.json`. Maintain current behavior.
* Do not break compatibility with our cloud setup.
* Maintain backwards compatibility and create an automatic upgrade path.
* Do not delete or overwrite the existing `conf/config.php` to allow for data verification by individuals after the upgrade is complete.

**Comment by charrondev** [comment]
## About addon default configs

Do we have to maintain loading of the old PHP configs or will it be enough to say: here's 2 conversion scripts. 1 to run against you own vanilla install that will parse addon configs once, and bring it's contents into a single ignored `legacy-addon-configs.json` and a tool to convert your PHP default config to a JSON one.

**Comment by linc** [comment]
We shouldn't add upgrade steps or tools. I'd expect the solution to update/convert the config correctly on utility/update and be invisible to the user. Until utility/update makes the conversion, it should continue reading the old config.

**Comment by bleistivt** [comment]
Will this new config.json also be nested?

**Comment by linc** [comment]
> Will this new config.json also be nested?

Our current cloud implementation is nested, yes. The scope of this would not include renaming existing config values, either.
