### ISSUE TITLE
Debugger plugin removal?

### ISSUE THREAD

**Issue by bleistivt** [vanilla/vanilla#7723]
As per this comment it has been removed:
https://github.com/vanilla/vanilla/issues/5465#issuecomment-354010519

The debugger plugin is still in master but does not work:

    Call to undefined method Gdn_Database::queries()

**Comment by charrondev** [comment]
It seems that must have slipped through the crack. I'm imaging the intention was to remove the Debugger plugin and use the debugbar plugin instead. @tburry Did we have intentions to open source that?

**Comment by charrondev** [comment]
Resolution of this was to move `debugbar` into the GPLv2 licensed `addons` repo. https://github.com/vanilla/addons/tree/master/plugins/debugbar
