### ISSUE TITLE
Audit multi-type API parameters

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#7732]
Vanilla is dialing back the usage of multi-type parameters for its API for the sake of becoming more OpenAPI-compliant. The "expand" parameter is the primary culprit, because it allows string values for specifying fields to expand, as well as a boolean `true` to expand all available fields. This boolean value is no longer necessary, because a string "all" can be used, instead.

Multi-type API parameters need to be located and documented, so we may begin deprecating them and removing them from the system.

**Comment by charrondev** [comment]
@initvector Do we still need this issue?

**Comment by initvector** [comment]
The `expand` input field should be all set, but we need to resolve the `body` output field for the quote endpoints. I've opened up a separate, more specific issue (#8281).
