### ISSUE TITLE
Upgrade from 2.0.9 to latest (2.6.1?)

### ISSUE THREAD

**Issue by taat** [vanilla/vanilla#7744]
How can I upgrade from 2.0.9 running PHP 5.3 to the latest version running PHP 7.0?
Database differences are so big.

I tried to upload new files and run /utility/upgrade - bunch of different errors, mostly about missing database fields, after I add them manually it redirects me to the login page and then I'm not able to login using old credentials.

The second try is that I installed clean 2.6.1 on PHP 7.0 server and now I'm stuck (vanilla2export.php tool supports only v.1 version?)

I also tried to checkout Version_2.1 tag and run it using current 2.0.6 database, but got bunch of http 500 errors.

Any hints how to do the upgrade properly?

**Comment by charrondev** [comment]
I appreciate what you're looking to get advice on here, but you seem to have posted this in the incorrect place. We try to focus our issue tracker on bug reports, and planned product features.

You're likely looking for our open source forums where you might find a user(s) that has completed a similar migration as you. https://open.vanillaforums.com.
