### ISSUE TITLE
Rich Editor - Pasting many lines only formats one/some lines.

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7746]
## Steps to Reproduce

1. Go to a blank line.
2. Format that line as a code block.
3. Copy several lines from a text editor or something.
4. Paste into the code block.

## Result

Only the last line that was pasted is formatted as code. The other lines are plain paragraphs.

## Expected Result

Every line that was pasted should be block level code.

## Also Applies to

- Quote block format: More of the lines are formatted properly, but not all of them.
- Spoiler block format: Same behavior as quotes.

**Comment by charrondev** [comment]
Related https://github.com/vanilla/vanilla/issues/6740
