### ISSUE TITLE
API v2 DateTimeImmutable returns different values over API and when dispatched internally

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7762]
## Situation

Call an API endpoint that contains values implementing the `DateTimeImmutable`  schema. Eg. anything with a `dateLastUpdated` `dateInserted` etc both internally (by calling the API endpoint through PHP. Eg. `SomeApiController::get($id)`) and externally (going through the dispatcher/routing `POST /some/$id`).

## Expected results

The result on both ends has the same structure.

## Actual results

The results differ.

### Internal dispatch

The date time will have a value similar to:

```php
[
    'dateInserted' => [
        'date' => '2018-08-27 21:43:10.000000',
        'timezone_type' => 3,
        'timezone' => 'UTC',
    ]
];
```

### External dispatch

When dispatched externally the APIv2 resources will be returned with just a the date string.

```json
{
   "dateInserted": "2018-08-27 21:43:10.000000"
}
```

**Comment by tburry** [comment]
Let me know if the changes I recommended are good enough to close this issue.

**Comment by charrondev** [comment]
Too summarize what @tburry and I discussed:

What's missing is wrapping the output in the `Vanilla\Web\Data` class. This provides certain filtering when serialized to JSON.

The question now is should our API return `Vanilla\Web\Data` items internally, or should it be the responsible of the call site to use `Data::box()` to create the data itself.

**Comment by initvector** [comment]
> The question now is should our API return Vanilla\Web\Data items internally, or should it be the responsible of the call site to use Data::box() to create the data itself.

I'm inclined to say it is the responsibility of the internal caller to modify the data as it needs to. The object remaining available to internal code makes more sense to me. With server-side components, PHP can make use of these objects, so it seems unnecessary to transform them back into a string. External consumers of the API are more likely better equipped to handle the standardized date-time string, that they can parse into their own client's language object equivalent, if necessary.

**Comment by charrondev** [comment]
That makes sense to me. I'm going to close out this issue and update the call site to box the data itself.
