### ISSUE TITLE
Change log: filter logs based on category view permissions

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#7763]
### Issue

Users with role 'Moderator' can view 'change log' from all categories under '/log/edits' even if the permission to view certain categories has been revoked.

### Plan
The logs page is in the Dashboard, but the concept of categories is in Vanilla (app).
We'll need to add a filter hook to [logcontroller::edits() ](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/controllers/class.logcontroller.php#L195) then use the filter in the Vanilla application's hooks file to remove items of type Discussion or Comment that belong to a category you don't have permission to view.

### Support ticket details
[#94](https://github.com/vanilla/support/issues/94)

**Comment by tburry** [comment]
I'm wondering if we can only give permission to this page to users that have permission to all categories or make the log permission separate so that admins can decide to grant access.

**Comment by LauraMakesArt** [comment]
Just wanted to note that the clients specific request was that we filter the logs by the accounts permissions. If we cant for various reasons, I would say that creating a separate permission would be the optimal solution. 

If thats the direction we're going, the CSM would appreciate a good explanation as to why in the linked issue ( https://github.com/vanilla/support/issues/94 ) so they can pass it along to the client.

**Comment by tburry** [comment]
My reasoning is more a matter of time. We aren't going to add major functionality changes in the form of "bug fixes". The change log itself is low level functionality and checking permissions within it will create more support over time.

Longer term we will give access to a change log for individual posts from the frontend so we can more easily check permission just on a single post. I do believe PA had this functionality.

**Comment by tburry** [comment]
Added to product board.
