### ISSUE TITLE
Wrong direct when changing username and clicking "Back to Profile"

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#7795]
On the **Edit Profile** page when editing the **username**, clicking the "Back to Profile" button directs you to the old username's profile page.

**Steps to reproduce:**
- Click "Edit Profile"
- Edit the Username and hit "Save" (do the password check if necessary)
-  Click "Back to Profile"
- You are going to be redirected to a page with the message "User not found". If you check the URL, it redirected you to the the old username profile page.

**Comment by charrondev** [comment]
Using the existing system of ajax for that page, we need to use `Gdn_Controller::jsonTarget()` to update the url of the back link.
