### ISSUE TITLE
LogModel has bugged `delete()` method

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7819]
I'm quite sure this last line doesn't do anything.

```
    /**
     * Delete records from the log table.
     *
     * @param array $where The where clause.
     * @param array $options Options for the delete.
     * @return mixed
     */
    public function delete($where = [], $options = []) {
        if (!is_array($where)) {
            $logIDs = explode(',', $logIDs);
```

Introduced in https://github.com/vanilla/vanilla/commit/45e7c5a4ddcf918cbd57cc0104d902f78edeb4b1 via #6814

**Comment by charrondev** [comment]
I think I might be missing the point of the issue here. Prior to that commit delete supported a string CSV or an int array of IDs as its first parameter.

Further down in the method a deprecation the old functionality is implemented and a deprecation log is added.
