### ISSUE TITLE
Add delete operation to base model

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#7827]
At present, `Vanilla\Model\Model` only supports insert, select and update database operations. A delete operation should now be supported. The existing `Gdn_Model::delete` method can be used as inspiration, but take care to avoid any of its numerous deprecations.

**Comment by charrondev** [comment]
Delete is implemented here https://github.com/vanilla/vanilla/blob/a2ff7e14d5196cc0e082fbdd94fc92872dcb803e/library/Vanilla/Models/Model.php#L72
