### ISSUE TITLE
Rich Editor - Trim extra newlines/whitespace and return an empty string for empty inserts

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#7841]
The rich editor easily gets a newline at the end of posts just because users will often click there or hit return on their keyboards before finishing a thought. The rich editor should trim this data before saving to avoid seeing visible empty lines when viewing posts.

A related issue is that functionally empty posts are being autosaved to drafts because of the JSON wrapper.

## Proposal

1. Right trim the last insert of a rich content post.
2. If the insert becomes empty then remove it altogether.
3. Repeat for the next-last insert until you come to a non-empty insert.
4. An empty array is then removed entirely.

## Example

```json
[{"insert":"\n"}]
```

### Right trim.

```json
[{"insert":""}]
```

### Remove empty insert

```json
[]
```

### Remove empty array

```
// empty
```

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8193
