### ISSUE TITLE
Regression in url() from PR #7624

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#7844]
The "optimizations" implemented for url() in https://github.com/vanilla/vanilla/commit/d05b24e11db8276a1b38c28d5dce3885fb43b1af and merged through https://github.com/vanilla/vanilla/pull/7624 have resulted in a cache poisoning problem for that function.

The algorithm used to generate the static key which stores previously generated results from $withDomain is overly general and misses several cases.

The spec for the `url()` function is:

```
    /**
     * Takes a route and prepends the web root (expects "/controller/action/params" as $Destination).
     *
     * @param string $path The path of the controller method.
     * @param mixed $withDomain Whether or not to include the domain with the url. This can take the following values.
     * - true: Include the domain name.
     * - false: Do not include the domain. This is a relative path.
     * - //: Include the domain name, but use the "//" schemeless notation.
     * - /: Just return the path.
     * @return string Returns the resulting URL.
     */
```

The cachekey algorithm is:

```
$staticKey = ($withDomain ? '1-' : '0-').($ssl ? '1-' : '0-').$path;
```

That means only 2 possible cache keys for $withDomain will be possible, when its value could be any of 4 things. 

The result is that a call to `url()` with any of the "truthy" arguments will make subsequent truthy calls return the same thing no matter what they actually want to receive.

Call me crazy, but refactoring a function this deep inside Vanilla without a **unit test** is one of the more insane things I've seen this year.

Thank you to @DaazKu for spotting this as the source of my problems over the last 2 hours.

**Comment by charrondev** [comment]
This is the same reason I was requesting unit tests for https://github.com/vanilla/vanilla/pull/7789.
