### ISSUE TITLE
error while updating to vanilla 2.6.2

### ISSUE THREAD

**Issue by pioc92** [vanilla/vanilla#7848]
Hi, i update my forum from 2.6.1 to 2.6.2, i made all the things in readme file and i have this error when i go to the admin dashboard:

Fatal Error in DashboardHooks.dashboardNavModule_init_handler();
Class 'Vanilla\FeatureFlagHelper' not found

Please help

**Comment by pioc92** [comment]
quick fix : I replace in /applications/dashboard/settings/class.hooks.php:331

->addLinkIf(
\Vanilla\FeatureFlagHelper::featureEnabled('Import') && $session->checkPermission('Garden.Import'),
t('Import'),
'/dashboard/import',
'forum-data.import',
'',
$sort
);
by

->addLinkIf('Garden.Settings.Manage', t('Import'), '/dashboard/import', 'forum-data.import', '', $sort);

It was the older class.hooks.php line....

**Comment by R-J** [comment]
@pico92 that is a good fix, but there is a new, more explicit permission here in 2.6.2: "Garden.Import". I guess that should be used instead of the former "Garden.Settings.Manage".

Therefore I would advise:
~~~
            ->addLinkIf(
                $session->checkPermission('Garden.Import'),
                t('Import'),
                '/dashboard/import',
                'forum-data.import',
                '',
                $sort
            );
~~~

**Comment by x00** [comment]
you could add this helper in looks like it go missed out.

**Comment by pioc92** [comment]
Vanilla 2.6.3 correct the issue
