### ISSUE TITLE
Rich Editor code blocks need to use a <pre> tag instead of <code>

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7852]
HTMLMinifiers like cloudflare's require the `<pre>` tag to not strip whitespace. They do not parse CSS so `white-space: pre` is not sufficient. These will need to be updated in both the client and server rendering.

**Comment by DaazKu** [comment]
As per the HTML5 Spec: https://www.w3.org/TR/html5/textlevel-semantics.html#the-code-element

**Comment by slafleche** [comment]
Adam's right. It's not wrong to use `pre`, but pre is styling, not semantic.

I'm fine using `pre`, but Adam said it'll require a fair amount of work. It doesn't matter in the end to me which solution we use, but it needs to been one of the two.
