### ISSUE TITLE
Revisit translation bundles

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#7863]
Vanilla currently separates its translations into logically-grouped files, but they all get loaded for each request. This means a discussion page is loading translations it will likely never use (e.g. the body of the "confirm your email" message).

The project needs a better way to logically breakdown its separate translations (e.g. by resource, by size) and the ability to independently load or retrieve them.

**Comment by tburry** [comment]
There is some movement on this front with our database translation work. As far as this particular issues is concerned I think I would like to close it as stale.
