### ISSUE TITLE
Moderation Log table does not display formatted content previews

### ISSUE THREAD

**Issue by LauraMakesArt** [vanilla/vanilla#7874]
![image](https://user-images.githubusercontent.com/7501633/46168833-2ac47580-c25f-11e8-9b57-35be635ea9dd.png)
Also the moderation queue. 

I wasnt seeing an issue associated with this, hopefully its not a duplicate.

**Comment by charrondev** [comment]
I'm renaming this issue though because it is in no way rich editor specific. We do not format ANYTHING in the log table. Even from the other editors.

Example from the WYSIWYG editor.

![image](https://user-images.githubusercontent.com/1770056/46173038-273ae980-c273-11e8-9eb2-1548f002aeac.png)

**Comment by tburry** [comment]
Closes https://github.com/vanilla/support/issues/269.

**Comment by vrjrobitaille** [comment]
Niantic also reporting this now. Please note that if you are using a non-latin locale like Japenese or Chinese, then you cannot read the content that is being reported as spam as these characters are encoded as well. Niantic is not able to moderate its Japanese posts without approving the content first.

**Comment by vrjrobitaille** [comment]
N.B. that Asus and Niantic both use Chinese and Japanese respectively so getting this fixed ASAP is imperative.

**Comment by vrjrobitaille** [comment]
@tburry Do you have an ETA on this one? It's impacting Niantic's ability to moderate their Japanese content. They launched their Beta last week and roughly 12k users joined.

**Comment by charrondev** [comment]
@tburry if you’d like we can I quick fix of just running the format method (will at least make it look not broken). That should give us a bit of breathing room for a better improvement there.

**Comment by tburry** [comment]
I'm okay with the quick fix, but am unsure if it will work with the content expansion.

**Comment by vrjrobitaille** [comment]
I just need something, anything to go back to the clients with. They're getting very aggitated that they can't read the content in the queues. Harry Potter is launching on Monday.

**Comment by vrjrobitaille** [comment]
Just an updated screenshot, but to give you an idea of what they are dealing with:

![Screen Shot 2019-06-13 at 2 46 13 PM](https://user-images.githubusercontent.com/18470831/59459155-1a066080-8dea-11e9-846f-cd23dbb466c7.png)

**Comment by vrjrobitaille** [comment]
@charrondev @tburry  Can I get a link to the PR for that plain text temp-fix? Sorry to be a pest. The issue is coming up again and again in our Support meetings. Shauna's clients are following up about it, as are mine, specifically Asus, Niantic and Cofense. There are also product ideas submitted around this because, due to the fact that  it's been going on for 9 months or so, some of our clients assume this is the default behaviour.

**Comment by shaunamcclemens** [comment]
This is an issue for Equinox and Quicken.

**Comment by vrjrobitaille** [comment]
FYI just got the following from one of my clients : 
"We're planning to turn off the spam filter for our forum today as there is no way for us to moderate it in the current situation. "

**Comment by vrjrobitaille** [comment]
This is now blocking the Harry Potter Wizards Unite Launch

**Comment by tburry** [comment]
Update: There is a PR ready for approval, but I've held off bugging the R&D team because they are behind on their sprint.

**Comment by vrjrobitaille** [comment]
Ok, so I imagine this won't make it into the patch that is being deployed tomorrow?
