### ISSUE TITLE
Rich Editor doesn't work with Gdn_Format::to() 

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#7884]
This is a fairly useful and commonly seen convention in Vanilla:

`$formattedContent = Gdn_Format::to($content->Body, c('Garden.InputFormatter'));`

Because the Rich Editor doesn't register 'Rich' as an InputFormatter under the old system, content made with it will come out as raw JSON. This causes bad interactions with addons.

**Comment by charrondev** [comment]
I think there may be some misunderstanding around this. Rich editor did not change the way formatters are called. It is formatted through Gdn_Format::to() in all of its most common usages. Eg. comments, discussions, messages, etc.

```php
$formattedContent = Gdn_Format::to($content->Body, c('Garden.InputFormatter'));
```

Is not the correct way to get the format for a given piece of existing content, nor is it the correct way to get the config value (`Garden.MobileInputFormatter` must be considered as well).

When reading an existing piece of content, the input formatter it was created with must be read, normally save in the DB or form in a field called `Format`. I had a discussion with @dannimajdalani about this earlier today.

When creating a new post you want to check the default format, in which case you __do not__ check the config value directly. Instead `Gdn_Format::defaultFormat()` should be called.

**Comment by linc** [comment]
> If you call `Gdn_Format::to()` with `Rich` or `rich` as the second parameter, you will **NOT** get JSON as your output.

You're correct, I misread this last night.
