### ISSUE TITLE
Rich Editor menu shadows have appear differently

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#7893]
## Before

![image](https://user-images.githubusercontent.com/1770056/46378980-5d111100-c66b-11e8-9614-8634506acde8.png)

## After

![image](https://user-images.githubusercontent.com/1770056/46378997-69956980-c66b-11e8-9a66-8f1e5bf42664.png)

---

The shadows have gotten much harsher and the border of the nub has a different thickness now. This seems to be after https://github.com/vanilla/vanilla/pull/7889

**Comment by slafleche** [comment]
The border width looks the same for me on my local host on master. The shadow, is however, harsher and makes the border stick out. I'll fix that.

**Comment by slafleche** [comment]
Will be fixed with: https://github.com/vanilla/vanilla/pull/7896

It's a small fix, so I'll lump it with the work I'll be doing this morning.
