### ISSUE TITLE
Social Reactions & Entry should have rel="nofollow"

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#7918]
**Describe the bug**
Seeing a rise in 401 and 403 errors on links for social reactions (Twitter, Facebook and Google) and entry in new Google Webmaster tools reports.

**Vanilla info**
I thought we had added rel="nofollow" to all reactions and entry links, but it seems not to be there for Google, Facebook, Twitter reactions.

**To Reproduce**
Check any social reaction link
![image](https://user-images.githubusercontent.com/425366/46870206-f2469f00-cdfb-11e8-9200-145fd234f3f2.png)

**Expected behaviour**
A  full SEO audit of links, where rel="nofollow" should be applied, includes any reactions, as well as entry/register and entry/signin.

**Additional context**
This adds to crawl budget unnecessarily

**Comment by dannimajdalani** [comment]
The nofollow attribute was added to the 'leaving' page but not social reactions.
https://github.com/vanilla/vanilla-patches/issues/432.

**Comment by adrianspeyer** [comment]
Yes, but the links to Twitter and Facebook, should also be no-follow, as there is no SEO benefit and the Google Webmaster Tools is reporting them as issues for community owners :(

**Comment by dannimajdalani** [comment]
Yeh, Its in the current sprint, creating a PR shortly.

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8117
