### ISSUE TITLE
Fix Embed styles

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#7948]
Looks like there were a few regressions on the embeded links.

The title has a link color, not FG color and the meta data has bad margin.

**Comment by charrondev** [comment]
A few other details I'm noticing:

- In KB the embed selected outlines don't seem correct.
- In KB the embed loading seems incorrect.
- In KB in the editor clicks inside the embed content seem broken. I think we had a special class that was looked at to add some type of pointer-events none on them.
