### ISSUE TITLE
Site owners marking a category as read doesn't mark them as read

### ISSUE THREAD

**Issue by JReko** [vanilla/vanilla#7953]
The problem
---
In the UI when viewing a category you have the option to mark a complete category as read through the cog well.

When doing so with the site owner (`Admin = 1` on the user table), the unread discussions under that category don't get marked as read.

You obviously need to have unread discussions to test this.

The cause
---
Here is the call stack that we are interested in. Most specifically the `categoryPermissions` function.
![screen shot 2018-10-19 at 12 28 53 pm](https://user-images.githubusercontent.com/15312192/47231729-c0a17b00-d39b-11e8-8565-4aee098a2ca8.png)

```
public static function categoryPermissions($escape = false, $forceRefresh = false) {
        if (is_null(self::$categoryPermissions) || $forceRefresh) {
            $session = Gdn::session();

            if ((is_object($session->User) && $session->User->Admin)) {
                self::$categoryPermissions = true;
            } elseif (c('Garden.Permissions.Disabled.Category')) {
                if ($session->checkPermission('Vanilla.Discussions.View')) {
                    self::$categoryPermissions = true;
                } else {
                    self::$categoryPermissions = []; // no permission
                }
            } else {
                $categories = CategoryModel::categories();
                $iDs = [];

                foreach ($categories as $iD => $category) {
                    if ($category['PermsDiscussionsView']) {
                        $iDs[] = $iD;
                    }
                }

                // Check to see if the user has permission to all categories. This is for speed.
                $categoryCount = count($categories);

                if (count($iDs) == $categoryCount) {
                    self::$categoryPermissions = true;
                } else {
                    self::$categoryPermissions = [];
                    foreach ($iDs as $iD) {
                        self::$categoryPermissions[] = ($escape ? '@' : '').$iD;
                    }
                }
            }
        }

        return self::$categoryPermissions;
    }
```

This if statement `if ((is_object($session->User) && $session->User->Admin)) {` is only reached by the site owner other users go into the else statement where we call `$categories = CategoryModel::categories()`. This is important because in that call we assign the categories to the class variable 

```
/** @var array Merged Category data, including Pure + UserCategory. */
    public static $Categories = null;
```

If we keep going through the call stack
![screen shot 2018-10-19 at 12 42 34 pm](https://user-images.githubusercontent.com/15312192/47232004-7e2c6e00-d39c-11e8-8f81-4e32576ca7cf.png)

```
public static function categories($ID = false) {
        if ((is_int($ID) || is_string($ID)) && empty(self::$Categories)) {
            $category = self::instance()->getOne($ID);
            return $category;
        }

        if (self::$Categories == null) {
            self::loadAllCategories();

            if (self::$Categories === null) {
                return null;
            }
        }

        if ($ID !== false) {
            if (!is_numeric($ID) && $ID) {
                $Code = $ID;
                foreach (self::$Categories as $Category) {
                    if (strcasecmp($Category['UrlCode'], $Code) === 0) {
                        $ID = $Category['CategoryID'];
                        break;
                    }
                }
            }

            if (isset(self::$Categories[$ID])) {
                $Result = self::$Categories[$ID];
                return $Result;
            } else {
                return null;
            }
        } else {
            $Result = self::$Categories;
            return $Result;
        }
    }
```

In the case of a normal user `self::$Categories` is not empty which means because we already previously in the stack called `self::loadAllCategories()` but we never do for the super user.

The problem is it's in `CategoryModel loadAllCategories()` that we call the `CategoryModel joinUserData()`, and it's that function that is responsible for "marking it as read".

Therefore since `CategoryModel loadAllCategories()` is never called for a super user we end up in the first if statement of the `CategoryModel categories()` function. Again:

```
public static function categories($ID = false) {
        if ((is_int($ID) || is_string($ID)) && empty(self::$Categories)) {
            $category = self::instance()->getOne($ID);
            return $category;
        }
```

We do return that category but we never got that chance to join the user's data and mark it as read.

**Comment by topcheese13** [comment]
I have talked to Ryan about this, what came out is that it's weird that we depend on the category permission check to load categories.

This specific problem happens in the index method of the categories controller and only for the site owner. The proposed fix was to load categories directly in the index method after the permission check. This was categories will be loaded regardless of if you are site owner or whatever else.

I asked if we should check for the same or different faulty behaviour of the same kind elsewhere and since the scope of this is so narrow, let's just fix this specific case and move on.

**Comment by bleistivt** [comment]
I can not reproduce this. But when a function depends on `CategoryModel` returning user specific data it has to be set explicitly like this:

    $this->categoryModel->setJoinUserCategory(true);
