### ISSUE TITLE
Rich-Editor: YouTube embeds appear as black box

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#8002]
### Details

Posting a YoutTube url with rich-editor enabled returns a black box.

### Stephane's Notes

There's a class we need to remove from the embed video HTML. I'm not sure how/when you want to patch it. We can book a meeting if you want to.

**Comment by slafleche** [comment]
The fix is easy. It's been fixed on master. If you need to do it sooner, I can help do it on a patch.

**Comment by charrondev** [comment]
This seems to have rolled out in one of the 2.8 releases. I'm not sure if it made it to the release notes.

**Comment by charrondev** [comment]
Fixed in 2.8 final.
