### ISSUE TITLE
API V2: /discussions api call fails when migrated discussion names have invalid markup

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#8018]
### Details

When making an /discussions API v2 call with a discussion that has the name ex. "&lt;cond testname" 
the calls fails with the error "name is required". The name is getting filtered by strip_tags(); that returns an empty string when sent an invalid markup, in this case "<cond" does not get filtered to "cond".

### Reason

In [class.format.php#L2153](https://github.com/vanilla/vanilla/blame/5b6fd5b423f59a430cdf1e2654bce4366382ce6c/library/core/class.format.php#L2153) we call `html_entity_decode('&lt;cond testname', ENT_QUOTES, 'UTF-8');` discussion name is now "<cond testname".
at this point "<cond testname" should be filtered for invalid markup, because calling strip_tags with invalid markup will return an empty string (what is currently happening).
Next we call [class.format.php#L2160](https://github.com/vanilla/vanilla/blob/5b6fd5b423f59a430cdf1e2654bce4366382ce6c/library/core/class.format.php#L2160) that is supposed to take care of the invalid markup but the Regex in place is not doing so.
In [class.format.php#L2161](https://github.com/vanilla/vanilla/blame/5b6fd5b423f59a430cdf1e2654bce4366382ce6c/library/core/class.format.php#L2161) we call strip_tags(''<cond testname");that is causing the error (name is required).

### strip_tags with invalid markup

```
echo strip_tags('<bad HTML string here<br>');  returns empty string
echo strip_tags('<bad HTML<br> Hello!');  returns empty string
echo strip_tags('<bad HTML> Hello!');  Hello!
```

### /discussions API V2 call error

![screen shot 2018-11-12 at 11 33 59 am](https://user-images.githubusercontent.com/31856281/48361161-e81ff680-e66e-11e8-8277-ec43e4b74eb1.png)

### API V2 /discussions Call
[API Ref. get_discussions](https://docs.vanillaforums.com/help/apiv2/swagger/#/Discussions/get_discussions)
`http://dev.vanilla.localhost/api/v2/discussions?access_token=..`

### Note

Creating a discussion with the name "<cond" will fail with the error "You have entered an invalid discussion title". The above error was noticed because of migration data.

**Comment by dannimajdalani** [comment]
**Ryan's notes:** 

it should probably be done with defensive programming in DiscussionModel.
 On the other hand, it would be nice if Garden Schema had the option to filter out rows that failed validation, instead of killing the whole response. But I don't think that's as likely to be implemented in the immediate future.

**Comment by charrondev** [comment]
Why are we using `strip_tags` in the first place? It should be the responsibility of the UI to escape its content, not the model.

**Comment by dannimajdalani** [comment]
The UI is already escaping the content (We can't create a discussion with invalid markup, its fails) , the problem here is for migrated discussions with invalid names.

**Comment by charrondev** [comment]
We shouldn't be doing strip tags in the first place is what I'm saying.

`The <Header /> component is broken` should not be modified!

**Comment by bleistivt** [comment]
I believe with #9612 this can be closed as well-

**Comment by charrondev** [comment]
This was actually fixed back in january with https://github.com/vanilla/vanilla/pull/7724
