### ISSUE TITLE
Rich Editor emoji menu close icon is incorrect

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8022]
**Describe the bug**
The emoji menu seems to have been messed up a little in some recent editor changes.

![image](https://user-images.githubusercontent.com/1770056/48431672-423cbc80-e740-11e8-8076-b5de6e8b5737.png)

I'm thinking we're missing styles for `buttonIcon` but I could be wrong.

**Comment by slafleche** [comment]
Can't reproduce. Any steps?

**Comment by charrondev** [comment]
1. Pull latest master of Vanilla
2. Open emoji picker.

I found the issue and will fix it in my coming editor PR. https://github.com/vanilla/vanilla/commit/28e53e13bd3e747c41d390cde2748505d08085dd#diff-49d98918898ba2f62034dcb501b05f8fL107 here we stopped passing legacyMode into the close button prop.
