### ISSUE TITLE
Discussions - Body field's maximum amount of characters is limited for utf8 

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8042]
The `Body` field on GDN_Discussion is of type `Text` which is a maximum of approximately  64,0000 bytes.  UTF8 characters can be up to 4 bytes each, which would only allow approximately 16,000 characters.  These are extreme cases, but should it be taken into consideration? Some clients have enormous posts and if the characters are encoded in UTF8, it will cause issues.  

Possible Solution:

Going forward for new clients change the body field to type `Mediumtext` or `Longtext`?

**Comment by linc** [comment]
The best solution is:
* Change the Discussion `Body` field to `MediumText` with its own maximum setting (capped at 200,000 characters or whatever we decide is an actual reasonable limit).
* Set the Comment maximum body size to 15,000 to work within its current constraints assuming 100% UTF8.

Unfortunately doing a structure update on the Discussion will be a bad time, so for now we're gonna monkey patch this by capping both under 65,000 (to 50,000) with #8039. If we had a way to opt new sites into MediumText without forcibly updating older sites, that'd be a nice path forward.

**Comment by tburry** [comment]
We already have a structure threshold so we should okay modifying the field. Updating existing sites could still be slow so it just needs to be coordinated. If you go forward with the GDN_Discussion change let me know.

**Comment by charrondev** [comment]
## Discussions
I can see a pretty clear path forward, but if we were to be doing a modification the discussions table like this in way that requires coordinated updates, would it hurt to also lump in the 2 main new columns we wanted to add to discussions? Namely `bodyRendered` and `attributes`?

**Path 1**

- Update `GDN_Discussions.Body` to be a `MediumText`.
- Add a column `GDN_Discussions.BodyRendered` that is also a `MediumText`.
- Add a column `Attributes` that is `Text`.

**Path 2**

- Write a config flag in new setups that will cause structure to create new sites' `Body` to be a `MediumText`
- Apply a different maximum validation limit for these sites.
- Gradually migrate existing sites.

If **Path 1** is an option I'd like for us to do it. It gives us more flexibility and aligns with how we want to be storing our content going forward.

## Comments

Comments seem to be more difficult to the sheer amount of them across the board. Sites with 10m+ rows I think?

Any changes there would us to put together a plan for this type of migration. Maybe with Ops expanding though its more of a possibility though.
