### ISSUE TITLE
Something has gone wrong page when accessing the Dashboard

### ISSUE THREAD

**Issue by PCTipsGR** [vanilla/vanilla#8044]
**Describe the bug**
When I try to access the Dashboard section of my Vanilla forums I am getting the "Something has gone wrong" error.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
Yeah, it is a fresh install with no addons.
2. Did you follow our generic troubleshooting steps already?
Where are they? :smile: 
3. What Vanilla version are you using?
Vanilla 2.6.4
4. When did the issue start?
Ever since I installed my forums using Softaculous

**To Reproduce**
1. Go to the settings icon
2. Click on 'Dashboard'
3. See error

**Expected behavior**
Dashboard to show up so that I can change some things.

**Screenshots**
![https://sp00py.ru/chris/vzum5qq1.png](https://sp00py.ru/chris/vzum5qq1.png)

**Additional context**
I can provide anyone who can help me with a test account on my forum, as I said it is a fresh install, nothing touched, and I have nothing to fear or lose.

**Comment by PCTipsGR** [comment]
Well, damn me :laughing: 

My host just replied (I contacted them) and said they moved my account to PHP 5.6.35 recently. I changed it to 7.0 and it worked.

Strangely enough, when I changed it to PHP 7.2, the same bug was occuring and changing my version to PHP 7.0 was the solution, any ideas why 7.2 does not work?

**Comment by R-J** [comment]
You can find troubleshooting tips in the documentation: https://docs.vanillaforums.com/developer/troubleshooting/

Your PHP 7.2 might not have some required PHP extensions installed. But that should be asked and discussed on open.vanillaforums.com

**Comment by PCTipsGR** [comment]
Thanks, when I go to forums it says me to open an issue here for a bug.. Anyway, since I don't need 7.2 and can work with 7.0, it is all fine.
