### ISSUE TITLE
Add a subcommunity chooser in the menu

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8054]
The new theme always has a sub-community chooser in the menu when sub-communities is turned on. Here are the components as I see it:

1. An endpoint to get a list of sub-communities.
2. The frontend will need to know the current sub-community so the correct one is selected.
3. The sub-community dropdown should be wired up on the frontend.

**Comment by initvector** [comment]
Issue moved to [vanilla/multisite #203](https://github.com/vanilla/multisite/issues/203) via [**ZenHub**](https://www.zenhub.com/)
