### ISSUE TITLE
Rich Editor - Table Support

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8056]
## Context

Users want to be able to insert tables in Knowledge Articles and discussisons.

Most of the time, the user will have a table created in Excel, Google Sheets, Smartsheet, or another similar service. 

Uses want to be able to copy paste tables from one service to Vanilla to include in their articles. Copy/pasting, should match the styling given in the original format.  

Some customers might leverage the ability to create tables in Vanilla from scratch, but this is less of a concern if we're able to support the copy/pasting of tables. 

## User stories

**As a content creator I can paste a table into a discussion or comment** 
- If I am using a service like Google Sheets, Smartsheet, Numbers, Excelt, I am able to copy a series of rows and columns and past them into my Vanilla discussion, comment or articlle. 

**As a content creator I can create a table in my Vanilla content**

## Dev Notes

We should be able to get there most of the for by using Quill 2.0 when it releases. How big this issue is will depend on much squabbling there will be over particular UX.

**Requirements**
- Copy/Paste support (migrations and user pasting).
- Table insertion UI.
- Table blots in frontend.
- Server side blots.
- Unit Tests

## MVP

- I should be able to insert a table, with custom row/column count and edit cells. Cells don't have to be WYSIWYG.
- The table should have semantic th, thead where necessary.
- I should be able to add rows/columns to an existing table.
- I should be able to insert a row/column in the middle of a table.
- I should be able to delete the table.
- The first row of a table is always a heading by default.
- The table must be keyboard navigable and there can't be a keyboard trap (i.e. you should be able to escape the table with just the tab key).

### Acceptance Criteria

- Cells can be multi-line.
- Keyboard shortcuts should be thought out.
- Cell edges should be clear when editing even if they don't show when viewing.

![image (3)](https://user-images.githubusercontent.com/97432/79389004-35775600-7f3c-11ea-93c8-ebf034d93e5d.png)

## PBIs

- I should be able to be able to specify the first row as headings and the first column as headings.
- I should be able to move rows up/down.
- I should be able to move columns left/right.
- I should be able to delete a row/column.
- The table should automatically add rows as you edit (accessibility?).
- I should be able to copy/paste a table into the editor and have it work.
    - I should be able to copy/paste the table within the editor.
- When I convert a post from another format, then tables should convert.
- I  should should choose the alignment of columns.
- I should be able to apply inline formatting to cells.
    - Inline formatting can apply to the entire cell (bold, italic, strike, code).
    - I should be able to have links in cell.
    - I should have a mix of inline content like the rest of the WYSIWYG editor.
- I should be able to choose a table display style in the theme editor.
- I should be able to add a caption to the table.
- I should be able to click column headings to sort the table when viewing ala Wikipedia.
    - I can specify a sort when editing.
- I should be able to insert images to cells.

**Comment by jamesinc** [comment]
Subscribed, hopefully Quill 2.0 drops soon, though work seems to be progressing slowly.

**Comment by vrjrobitaille** [comment]
Closing this out in favour of the roadmap item for this task that is linked with our PM tools - https://github.com/vanilla/roadmap/issues/168
