### ISSUE TITLE
Categories - cache not calculating CountAllDiscussions correctly

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8058]
**Issue**

The categories cache isn't storing CountAllDiscussions correctly.  This behaviour appears to be happening only with categories that have child categories.  When a discussion is commented on, the cache is being rebuilt and CountAllDiscussions is being incremented and then stored in the cache.  The DB value is correct however.

The calculateData method appears to be the culprit, it's called every time the category cache is rebuilt.

https://github.com/vanilla/vanilla/blob/d022d069cee29aba408439f6d5d33b2981bbc75f/applications/vanilla/models/class.categorymodel.php#L666

This what's in my local cache:
![screen shot 2018-11-22 at 3 41 29 pm](https://user-images.githubusercontent.com/36996270/48921840-86cb0500-ee70-11e8-9d16-368ee4378500.png)

This is the DB:
![screen shot 2018-11-22 at 4 09 10 pm](https://user-images.githubusercontent.com/36996270/48921895-fa6d1200-ee70-11e8-89a4-65ac4a0561af.png)

**Solution:**

TBD

**Comment by alex-mtl** [comment]
There are some related issues:

https://github.com/vanilla/vanilla/issues/7897
https://github.com/vanilla/vanilla/issues/7885
https://github.com/vanilla/vanilla/issues/7883

And some research was done but not merged here:

https://github.com/vanilla/vanilla/pull/7843/files
