### ISSUE TITLE
Editors not mounting on the activity page

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8064]
When adding a comment to an item on the activity list (profile page) the form doesn't offer the option of converting the text into a link.

![group](https://user-images.githubusercontent.com/31521020/49028073-8df35b00-f16f-11e8-9f14-142a3472ec23.png)

**To Reproduce**
On the profile page, activity list, click on "comment" on any item and try to add a link.

**Additional context**
Code link https://github.com/vanilla/vanilla/blob/master/applications/dashboard/views/activity/helper_functions.php#L87
Client issue https://github.com/vanillaforums/playkot/issues/46

**Comment by charrondev** [comment]
We don't actually mount rich or advanced editors here which is the cause of this.
