### ISSUE TITLE
Throttle data pulls for conversations and notifications in MeBox component

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8103]
The MeBox component is currently pulling new data for conversations and notifications, whenever the component is mounted. In some cases, this is causing two API requests for every time a new route is loaded.

The data should only need to be updated once the page is initially loaded and only at a set interval, thereafter.

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8309
