### ISSUE TITLE
Choose new static routing dispatching system

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8119]
We have a few different option here:

Each of these solution I mention a request object, but I don't strictly see the need to immediately replace our RequestInterface here. The benefit to moving to a PSR-7 compliant implementation of course if uniformity and better integration with other libraries.

## Small packages

- Router - [nikic/FastRoute](https://github.com/nikic/FastRoute)
- Request object - [nyholm/psr7](https://packagist.org/packages/nyholm/psr7)
- Dispatcher -Continue using our existing dispatcher, although likely roll a new route class.
- Middleware - Middleware for our existing dispatcher. Do we need routing/http middleware? PSR-15?

## Symphony

@alex-mtl You seemed to be championing this so maybe you could chime in a bit here. I was doing a bit of reading though and the Symphony 4 router seems to not only be blazing fast but dependency free. https://medium.com/@nicolas.grekas/making-symfonys-router-77-7x-faster-1-2-958e3754f0e1

## Laravel

Ops seems to be jumping on the Laravel train so I see benefit of trying to keep our teams using similar tools. Maybe @DaazKu could give a brief overview of the decisions made there.

This may be too heavy for our needs though. The Laravel router builds on the Symphony router, but has many other laravel dependencies.

**Comment by tburry** [comment]
Closing as stale. Combustion Beavers will work on if we do this.
