### ISSUE TITLE
Specify how addons should declare routes for static routing

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8120]
Considerations:

- Will depend on #8119 
- Must work without loading the entire addon system.
  - Likely should be located in a well known location.
- Must be cache-able based on an entire multi-tenant site (eg. we need to be able to have a cache saved that includes possible routes from all addons).
- Must explicitly declare the controller class and method to handle the addon.

**Comment by tburry** [comment]
Closing as stale.
