### ISSUE TITLE
Proposal: update minimum requirements

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8128]
I suggest to upgrade minimum requirements to PHP 7.1 and MySQL 5.6.5

#### PHP 7.0

There have been [reports on the OS forum](https://open.vanillaforums.com/discussion/36849/unable-to-see-existing-threads-after-update#latest) about problems with PHP 7.0 which could be solved by updating to 7.1.

I was trying to help someone with PHP 7.0 and ensured all was set up correctly, but there were still errors that I did not understand. Since PHP 7.0 gets no security updates any more, the hoster could be convinced to update and I did not have to track down the real PHP error. Right after the update everything was running smoothly.

#### MySQL 5.0

There also have been problems with "[There can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT](https://open.vanillaforums.com/discussion/comment/252824/#Comment_252824)" error message which requires MySQL 5.6.5 to disappear.

**Comment by charrondev** [comment]
We're intending to this do the PHP version bump with our next release to open source, so that one will definitely be happening. @initvector @linc Any thoughts on bumping up the minimum MySQL version? I don't really have the context for how often we've done that.

**Comment by charrondev** [comment]
Closing this because we bumped to PHP 7.1 last year with Vanilla 3.0.

This December Release 4.0 is coming which will require PHP 7.2
