### ISSUE TITLE
QA for 2.8: Test install & upgrade processes

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8147]
* [ ] Test an install of Vanilla 2.8b from scratch. Verify defaults, stub content, and basic functionality.
* [ ] Test an upgrade from Vanilla 2.6.4 to Vanilla 2.8b. **Note any extra steps in the README**. Verify basic functionality and that settings have not been altered.
* [ ] Test an upgrade from Vanilla 2.5 to Vanilla 2.8b, following the README.

**Comment by linc** [comment]
ur a chore

**Comment by initvector** [comment]
Closing as complete per @linc
