### ISSUE TITLE
Assemble release notes for 2.8

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8148]
Assemble comprehensive release notes from Vanilla 2.8. 

* It must include anything since the 2.6 fork that wasn't backported as a patch. 
* It should be organized by feature (dashboard section, addon, etc). 
* Avoid adding notes for issues both created & patched within the time period since they were never distributed.
* Security issues can be described by type + system effected, e.g. "Fix CSRF in the Widget addon".
* Try to put yourself in the shoes of a user and make every line about features or fixes intelligible to a non-developer. Split developer-only notes into a separate section (e.g. changes to our framework).

**Comment by charrondev** [comment]
## .Rich Editor

Shipping as a Vanilla's new default editor, Rich Editor provides a number of improvements over 
Advanced Editor.

- An improved WYSIWYG experience. All formatting options now display display live, in the editor.
- Improved accessibility and keyboard navigation.
- A new minimal & contextual visual design.
- Support for over 1000 native emojis.
- A new, pluggable, rich embed system. Addons can add their own rich embeds. New built in embeds include
  - An improved video embed (YouTube, Twitch, Vimeo, Wistia).
  - Codepen.
  - Comments and Discussions from your own forum.
  - Any publicly accessible web-site.
  - Improved versions of the existing other embeds (twitter, instagram, getty, Soundcloud).
- Code block syntax highlighting, live, and in-editor.
- Improved text alignment & metrics.
- A safer, more efficient storage format.

**Comment by charrondev** [comment]
https://open.vanillaforums.com/discussion/37120/vanilla-2-8-release-notes#latest
