### ISSUE TITLE
Google Plus Sign-in Deprecated by January 29th 2019

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#8153]
Google will kill Google Plus by end of the month. Here is the migration doc
https://developers.google.com/identity/sign-in/web/quick-migration-guide

This documentation will also have to be updated:
https://docs.vanillaforums.com/help/sso/social-connect/

Discussion: 
https://open.vanillaforums.com/discussion/36884/google-plus-sign-in-is-deprecated-by-google#latest

**Comment by cchabilall83** [comment]
Task breakdown for Google+ migration to Google signin

1) Get google+ sigin working locally (3pts)
- Client clientid with google api
- Understanding the workflow

2) Update Work flow (if necessary) (5-8pts)
-  use Google library?
- https://developers.google.com/identity/sign-in/android/backend-auth#verify-the-integrity-of-the-id-token
-  When new work plugin activated we have to deactivate old google+ plugin

3) Migrate Sign-in button (1pt)

4) Test local setup (1pt)

5) Test infrastructure(1pt)
