### ISSUE TITLE
Hide editor dialog on option click

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8196]
On the **Advanced Editor** when using **Markdown** (not sure if it happens on the other options) on mobile opening any dialog and clicking on a option doesn't close the dialog after.

I debugged a little and found this: https://github.com/vanilla/vanilla/blob/master/plugins/editor/js/editor.js#L446
It seems that indeed it closes the dialog but it opens right next for no apparent reason.

**To Reproduce**
1. Make sure you have Advanced Editor enabled and it's set as Markdown on mobile.
1. Go to a discussion and scroll to the comment form.
1. Type some text.
1. Open the "paragraph" dialog and chose any option.

**Expected behavior**
The dialog should close after you have chosen something, but it doesn't. It's no big deal when you're in a modern browser, but iOS 8 and lower has this bug that displays the caret on top of the dialog.

Client issue: https://github.com/vanillaforums/king/issues/153

**Comment by charrondev** [comment]
Fixed in Rich Editor which is the default as of 2.8.
