### ISSUE TITLE
Design placeholder loaders for articles and search results

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8198]
When a record or page is loading we display a default spinner in its place. A nicer loader would show a placeholder or watermark representation of the data. Here is an example from one of our other apps:

![Hootsuite.png](https://images.zenhubusercontent.com/57087d1abf93871ccd991f73/07361f1a-1972-4583-9cf8-671d6fff0676)

Becomes:

![Hootsuite.png](https://images.zenhubusercontent.com/57087d1abf93871ccd991f73/2c854cba-5fa7-4938-902a-f086b72604eb)

The placeholder animation we currently use follows the following logic:

- The boxes animate over a subtle shade of grey to indicate the loading.
- The boxes take up the same vertical space as the text they represent, but the box itself is 60% of the font size which we determined to be visually pleasing. It's important to have a consistent relative size like this in order to simplify the implementation.
- The widths of the text boxes for single line items is just eyeballed to look good reasonable since we don't know how many characters will eventually look good.
- When making a placeholder for body text we usually display three boxes of differing widths.
- Avatars are replaced by a box the same size. Round avatars would be circles.

In a perfect world we'd make custom placeholders for every type of data we load, but for now lets design placeholders for the following:

- [ ] An article page. So the article itself.
- [ ] The search results page which would be a single search result.

**Comment by charrondev** [comment]
@tburry Could we get one for the breadcrumbs and the navigation? Those are are also present on the article page.

**Comment by ElisaAlmeida** [comment]
Done. Link:
https://drive.google.com/drive/folders/1GKYtvhA5__xYlrtWFQvmg2jZULHDMoGX
Desktop: Article loading, Search loading, Category loading
