### ISSUE TITLE
Unify Rich and older text formatting pipelines

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8204]
__WIP PR: https://github.com/vanilla/vanilla/pull/8980__

**Describe the Feature**

https://github.com/vanilla/vanilla/pull/8202 implements a new formatting pipeline with a `FormatInterface` and `FormatFactory` exposing numerous registered formats to a consuming class. The `Vanilla\Formatting\Formats\RichFormat` has already been implemented.

A similar implementation should be done for the existing formats. The rest of `Gdn_Format` should then be trimmed down, and replaced with calls to the `FormatFactory`.

**Acceptance Criteria**

Each of these could probably be done in their own pull request.

- [x] Integration tests add for all exposed Gdn_Format format methods. - https://github.com/vanilla/vanilla/pull/8205
- [x] New format classes implemented for:
  - [x] `html`
  - [x] `wysiwyg`
  - [x] `bbcode`
  - [x] `markdown`
  - [x] `text`
  - [x] `textex`
- [x] Replace the internals of `Gdn_Format` with calls to `FormatService`.
- [ ] Simplify and replace internals of `BodyFormatValidator` with `FormatService::filter`.

**Additional context**

The existing formatting pipeline has pretty much no tests, so those will need to be built out before making the change.

**Related Issues**

- https://github.com/vanilla/vanilla/issues/5507

**Comment by thunderer** [comment]
I left a comment at one of the PRs, but since it's merged I'll repeat it here:

Hi @charrondev, @initvector - would you be interested in evaluating a new BBCode processing library? I would like to hear your thoughts about https://github.com/thunderer/Shortcode. I'll be happy to answer all your questions and feature requests. Thanks!

**Comment by charrondev** [comment]
@thunderer to give you a little bit of context, we’ve been putting most of our recent effort into our new Rich Editor which stores its data as structured JSON. We don’t have any plans on our side to introduce new formatting options into BBCode editor.

That said I’m not opposed to a faster BBCode parser and when this set of updates completed it should be relatively easy to implement an alternative to our BBCode format that implements ‘Vanilla/Contracts/Formatting/FormatInterface’ and replace the implementation in the dependency injection container either in core or from an addon.

As a team implementing something like that is not on our roadmap but we would accept contributions if they passed our existing integration tests and benchmark faster. If that’s something your interesting in doing is recommend making an issue with out “New Feature” template and I can try and offer a bit of guidance on how to get started with something like that.

**Comment by charrondev** [comment]
Related https://github.com/vanilla/addons/issues/709
