### ISSUE TITLE
Convert components to use typestyle: Batch 1

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8207]
Components must be converted to typestyle and demo-able in both dark & light.

Light will be the variable defaults, with hard-coded theme response form the server providing dark theme variables. Disabling this hard-coded response should be able to flip the component from dark to light.

**Comment by slafleche** [comment]
See: https://app.zenhub.com/workspaces/vanilla-rd-556cc3adbfcecd111b957933/issues/vanilla/knowledge/683

And https://github.com/vanilla/knowledge/issues/684
