### ISSUE TITLE
Implement location picker category chooser UI for guides

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8221]
## Category Picker on the post page

  - Guide has articles listed in with the content & has a way to select the position of the you are posting. __Mockups required__. I've pasted the wireframe here.
![image.png](https://images.zenhubusercontent.com/59527c8361b4ca3b0a727689/b85698a9-83c3-408d-ac88-47b81d4c341d)
  - Help center is exactly as it is now, with no articles mixed in and no manual positioning.

**Comment by ElisaAlmeida** [comment]
the mockup @slafleche 
https://drive.google.com/drive/folders/1GKYtvhA5__xYlrtWFQvmg2jZULHDMoGX
