### ISSUE TITLE
Rich Editor image copied from the clipboard

### ISSUE THREAD

**Issue by DaazKu** [vanilla/vanilla#8227]
Images copied from the clipboard are uploaded but not displayed.

**To Reproduce**
1. Copy an image from your clipboard in the rich editor

**Expected behavior**
The image should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/2412909/51346361-7481d780-1a6b-11e9-9ff9-85248306c0d3.png)

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/8218

There's some issues with differentiating between file/image uploads on paste at the moment, but I intend to handle it in the linked issue.
