### ISSUE TITLE
Implement Trusted Domains for Rich Editor

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8254]
Rich Editor currently does not implement the trusted domains feature of of the advanced editor formatters.

**User Story**

As a site owner I would like links created in rich editor to respect the trusted domain configuration options for the site.

**Acceptance Criteria**

- Links made by rich editor will be filtered on output to contain redirect through the /leaving pages unless they are in the whitelist of trusted domains.

**Comment by tburry** [comment]
I would make all links filter through the redirect and then have *that* page check to see if the domain is trusted.
