### ISSUE TITLE
Can't quote after posting a comment

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8256]
After I post a comment and it automatically gets added to the bottom of the discussion, the quote button no longer works. Clicking it produces a javascript error and does not put the quite into the editor:

<img width="975" alt="rich_editor__attachment_uploads_ _vanilla_staff_and_slack_-_vanilla_forums" src="https://user-images.githubusercontent.com/97432/51565317-b5109500-1e5f-11e9-8720-b05eaa43ca45.png">

**Comment by charrondev** [comment]
I'm unable to reproduce this on my localhost or on our test clusters on infrastructure. I think this will need more detailed reproduction steps.

**Comment by tburry** [comment]
I can no longer reproduce.
