### ISSUE TITLE
Add ability to set canonical URL for discussions via the API

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8260]
Vanilla automatically generates canonical URLs for discussions in its `DiscussionController` and `DiscussionsController`. The ability to override this value over the API is  needed.

### Requirements

1. A user should be able to override the canonical URL for a discussion using the discussions resource in API v2. This can only be done once. If the canonical is attempted to be set again, an error is thrown.
1. A message should be displayed at the top of the discussions page if a custom canonical URL has been detected (e.g. "This discussion has a more recent version here."). This message will link to the custom canonical URL. Actually visualization of the UI to be done [here](https://github.com/vanilla/vanilla/issues/8261).
1. Canonical URL tags generated by the page should use the custom canonical URL, if available.

**Comment by alex-mtl** [comment]
Closed by #8556
