### ISSUE TITLE
Implement discussion canonicalization notification UI

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8261]
Implement UI for the notification that a discussion has been moved to a knowledge article.

This UI should be implemented as some HTML before the rendered output of the discussion using info message style. For example see the rich editor error HTML.

The text content of this message should be 

```
This discussion has a more [recent version](https://link-to-article)
```

Where the markdown there is an actual link. This should __not__ be part of the discussions contents.

**Comment by ElisaAlmeida** [comment]
It's done.  The link:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c82daa7b062a1bc667bb5c6

**Comment by tburry** [comment]
More information [here](https://github.com/vanilla/roadmap/blob/master/knowledge/data.md#convert-discussion-to-article) and [here](https://github.com/vanilla/roadmap/blob/master/knowledge/pages.md#convert-discussion-to-article).
