### ISSUE TITLE
Keystone: Edit Profile Menu Not Aligned

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#8263]
**Describe the bug**
Edit profile button is not looking proper (see screenshot)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to profile
2. Click on little person icon to edit profile

**Screenshots**
![image](https://user-images.githubusercontent.com/425366/51747585-ecf22500-2077-11e9-8be1-77b690865983.png)

**Comment by charrondev** [comment]
I have a fix already in this PR https://github.com/vanilla/vanilla/pull/8233.

I should get some time to finish it next week.
