### ISSUE TITLE
Back button is hijacked when using jsconnect "/sso" url

### ISSUE THREAD

**Issue by garygreen** [vanilla/vanilla#8268]
**Describe the bug**

The back button is hijacked when you login to the "/sso" endpoint, so when you press back button on your browser it'll re-attempt to login/authenticate. If you rapidly press twice, it'll go back to the originating page successfully.

**To Reproduce**

1. Using the following HTML to link to the forum (e.g. from your navigation section).

```html
<a href="http://my-site.com/forum/sso?target=/categories/general">Forum</a>
```

2. Click on the Forum link and let the sso system sign you in successfully.

3. Click back button once on the browser, it'll then re-attempt to navigate to `/sso` url again (back button has been hijacked).

**Expected behaviour**

Upon clicking the back button, it should redirect you back to the originating page.

**Comment by garygreen** [comment]
The sso / authentication stage is the "middle man" and user's should absolutely NOT be endlessly redirected back to that page. The "true" target end page here is "/forum/categories/general" or if the "target" is omitted, the forum homepage. User's would not expect to press back button and then attempt to sso login again.

Question: why would a user press to 'go back' WANT to login again? What purpose is that? Their intention is to go back to the *initiating page*.

In an ideal world, the url would be something like:

```
http://my-site.com/forum/categories/general?autologin=true
```

The way it works at the moment IS hijacking the back button. Simple as that.

**Comment by garygreen** [comment]
Btw, I have a fix working on my local copy, but sounds like a PR would not even be accepted as it's already working as intended. Bizarre.

**Comment by garygreen** [comment]
The problem as demonstrated:

![back-vanilla-sso-hijack](https://user-images.githubusercontent.com/1702638/51802876-31332000-2246-11e9-8a0f-33db3a9882ab.gif)

Proposed fix is to rewrite the browser history in `jsconnect.js`:

```js
jQuery(document).ready(function($) {
var jsUrl = gdn.definition('JsAuthenticateUrl', false);
if (jsUrl) {
   // Fix back button:
   var referer = gdn.definition('HTTP_REFERER');
   if (referer && window.history) {
      window.history.replaceState({}, '', referer)
   }
```

Then in `class.jsconnect.plugin.php` in the function `EntryController_JsConnect_Create` add the refererr so JS can see it as a definition:

```php
$Sender->AddDefinition('HTTP_REFERER', $_SERVER['HTTP_REFERER']);
```

Would doing this likely break any existing applications? I don't believe it would.

If Vanilla forum isn't going to fix this, then can we at least get some kind of js+php hook so we can work around this in our own apps? I don't like the idea of hacking js code internally, as that creates fragile updates and we'll need to apply our mods again each time we update.

**Comment by charrondev** [comment]
It's not on our immediate roadmap to resolve this. This type of UX will definitely be a consideration when revisit authentication (and properly consider the true scope of it). I'm probably the least risk-averse member of the core team and I wouldn't even consider making a change like that to our current SSO system. There are probably greater than 100k different code paths that can occur with all the of the different plugins, server side implementations, users signing in, permission structures, etc. It wouldn't surprise me in the least if some implementation, particular JS based ones, rely somewhere on the history being there.

## Possible avenues forward

### New authentication implementation

@linc has gone shed a little bit of light on this, but were relatively recently, working on creating an entirely new authentication system. We'll probably come back around to this but there are many hurdles in the way, the least of which are the initial implementation. Porting of existing SSO integrations, external security audits, and a lot testing will need to be done.

### Add an opt-in method for the existing SSO implementation

This would involve implementing this history modification in core as you propose, but it would need to ___off by default___. Existing SSO implementations would have to indicate to the SSO system that they would like to opt in to this behaviour. After testing and verification individual implementations could opt in.

### Add some hooks so for a 3rd party plugin to enable this

I'm more of a fan of the previous option, but this is viable as well.


## Wrap-up

I would support contributions for the 2nd and 3rd methods provided they came with adequate documentation. The first option we'll need to do as a team is probably a ways off.

**Comment by garygreen** [comment]
> There are probably greater than 100k different code paths that can occur with all the of the different plugins

Not really. Your talking about the SSO system in general, but the suggestion I'm making is purely to do with SSO connect thru ONE code path which is thru sso in js. That should be relatively easy to test?

> It wouldn't surprise me in the least if some implementation, particular JS based ones, rely somewhere on the history being there.

It's ONLY the js one that needs fixing, so you don't need to worry about the others. Plus I doubt even the edge cases would rely on a certain history state, but as you mentioned it could be a possibility that can be alleviated by:

1) Add this to the next major version of Vanilla (breaking changes between versions is to be minimised, but expected)

and/or 2) make this a opt-in feature but immediately deprecate it to discourage it's "optional" behaviour, then see how it plays out in production. If all the edge cases are working correctly, as you mentioned, then you can turn it on by default in the next version. Reason for deprecating it immediately is because I have absolutely NO idea why anybody would WANT to break the back back button and cause an endless loop - it should be the default behaviour.

**Comment by garygreen** [comment]
> I'm probably the least risk-averse member of the core team and I wouldn't even consider making a change like that to our current SSO system

I'm pretty least risk adverse as well. I'm a strong believer in keeping things iterating fast - ANYTHING can go in the next major version. There's no point having ideas and coding stuff if you never ship 😄 though appreciate vanilla have business considerations to make as well.

**Comment by charrondev** [comment]
I'd support a PR implementing 2.
