### ISSUE TITLE
Rich Editor: Disappearing nested quote

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8270]
https://open.vanillaforums.com/discussion/36949/hiring-fix-my-forum#latest

Preview:
<img width="922" alt="screen shot 2019-01-26 at 2 39 42 pm" src="https://user-images.githubusercontent.com/117672/51791908-64a77900-2178-11e9-8e80-3d1648c278e0.png">

Actual:
<img width="920" alt="screen shot 2019-01-26 at 2 40 01 pm" src="https://user-images.githubusercontent.com/117672/51791909-66713c80-2178-11e9-82e9-247500ad3676.png">

**Comment by charrondev** [comment]
This was already fixed.

https://github.com/vanilla/vanilla/pull/8236

I think it just didn't make it into the `2.8.dev.6` release.
