### ISSUE TITLE
Keystone - alignment and shadow on reactions

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#8296]
<img width="133" alt="screen shot 2019-01-31 at 11 39 09" src="https://user-images.githubusercontent.com/19651440/52069522-e3236280-254c-11e9-9d13-f36fda392c7d.png">

Add text shadow on the reactions. example `text-shadow: black 0px 0px 5px;`

![feedbackkeystone1](https://user-images.githubusercontent.com/19651440/52069523-e3236280-254c-11e9-8a93-083cc9829675.jpg)

Odd alignment here. "Announcement" should be aligned with the title.

The grey box is too tight. Have the same spacing you have elsewhere. I would try to align the second line a bit higher OR make the avatars a bit bigger to line up with the bottom of the second line.

**Comment by charrondev** [comment]
Could we also get the standard border radius on the upvote box?
