### ISSUE TITLE
Implement better permission checks for rich editor uploads

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8306]
A few things to keep in mind:

- On the forum we need to check category specific permissions. An endpoint will need to be made to provide these permissions, similar to the /users/me endpoint.
- Our API currently maps both `Garden.Uploads.Allow` and `Plugins.Attachments.Upload.Allow` into `uploads.add`. These permissions are not the same. The first allows image uploads only. The second allows generic file uploads.
- Verify that the implemented UI meets acceptance criteria.

> ### Permissions
> The ability to upload file attachments should a separate permission so that users can be allowed to embed images, but not files.
> 
> Users without permission should see a disabled file attachment button with the title "You don't have permission to attach files."

I'm thinking we should create a new permission named more appropriately than `Plugins.Attachments.Upload.Allow` for the file uploads.

## Related

Recent advanced editor https://github.com/vanilla/vanilla-patches/pull/469

**Comment by vrjrobitaille** [comment]
Hey Adam! I very much agree with you here, a separate permission for file upload vs profile upload would make things easier for users. As we have no immediate plans to tackle this, I've copied your notes and insights into Product Board [here](https://vanillaforums.productboard.com/feature-board/264971-feature-prioritization/notes/8759934), so we can track the need and open Git issues for it as it becomes a high priority, or when we can couple it with some other work we're doing.
