### ISSUE TITLE
Vanilla\Web\Data::jsonFilter is eggregiously slow

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8308]
In my mind this method shouldn't need to exist at all.

[See this profile](https://blackfire.io/profiles/a06fac74-ba9e-423e-8e06-b9cbeac1ace2/graph?settings%5Bdimension%5D=timeline&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=metrics&selected=&callname=main())

- We're the ones that create the `DateTime`s in the first place. We should extend that and create a JsonSerializable version that works the way we want.
- The ip addresses should be handled in their individual API endpoints. Walking the whole tree to do this stringEndsWith is incredibly expensive.

**Comment by tburry** [comment]
I agree with this in principle with the logic of this and the new model is meant to handle stuff like this. Bigger picture is that removing `jsonFilter` is premature optimization at this point though. And if you are going to do that then you have to weigh the performance of a native `DateTime` against a PHP subclass of it.
