### ISSUE TITLE
Rich Editor: collapsable code blocks

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#8314]
**Describe the Feature**

When dealing with more than 10 lines of code, it would be interesting to make it collapsible (like spoiler), so the discussion post or comment is not so long

**User Story**

Scott from RapidMiner deals with code over 100-200 lines, and is needing to use combo of code and spoiler tags, but it's hard to teach the user community to do the same.

**Acceptance Criteria**

A list of the minimum requirements that a pull request must meet in order to call the feature complete.

Set a limit on lines of code or blockquote before it's collapsible

**Comment by charrondev** [comment]
So I will say there is a relatively easy workaround that we have implemented in our new base themes/keystone etc. and that is setting a max-height on the code block element using CSS.

That doesn't invalidate this as a feature, (which involve this max-height + a button to remove the limit), but they aren't stuck without having a limit.

**Comment by adrianspeyer** [comment]
Good solution if on keystone, so thanks for that. In this case, theme change is not an option.

**Comment by charrondev** [comment]
It seems I was mistaken. Keystone does not implement this at all, so this actually does become a little bit more important. I'm thinking it's open source forum that properly implements this then.

**Comment by tburry** [comment]
In general, I think a better approach to supporting hundreds of lines of code would be to support gist embeds. Showing small code snippets inline is nice, but when you need to type a bunch of stuff a dedicated IDE is better.
