### ISSUE TITLE
Rich Editor addon.json is missing license key

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8342]

**Comment by charrondev** [comment]
Does it really need it? Other built-ins like flagging don't have one https://github.com/vanilla/vanilla/blob/master/plugins/Flagging/addon.json.

- Every file in the plugin has an doc block at the top declaring `gpl-2.0-only` to be the license.
- The addon is source controlled in a repo with a top level `LICENSE.md` of `gpl-2.0-only`.
- The addon is only distributed with vanilla core which ships with this license.

As such I don't really feel the license in addon.json is necessary here.

**Comment by R-J** [comment]
Since it is part of Vanilla it will not need it, I agree.

But for uploading plugins to the OS forum addon repo, that key is a requirement. Only recently you've moved some plugins to the addon repo and if there will be the requirement to update any of those plugins to the addon section on open.vanillaforums.com, a missing license key will be a showstopper.

**All plugins in the addon repo need to have that key.**

Therefore, although not explicitly needed in the rich editor, I think it would be a good habit to add the license.

Copying a plugin to make it the start for a new idea is a) something I do sometime and b) something I advise others to do sometimes. Therefore it might make sense to stress the license of plugins in the addon.json.

Those two scenarios are not that important, I know. But adding a license key isn't much work either.
