### ISSUE TITLE
Keystone: Spacing on the comment title form is off

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8350]
The spacing between the **Leave a Comment** heading and the comment box is too small.

<img width="978" alt="semantic_versioning_ _vanilla_staff" src="https://user-images.githubusercontent.com/97432/52490491-d6c58800-2b92-11e9-9af0-5cf7185eff46.png">

Reference Issue: https://github.com/vanilla/themes/issues/264

**Comment by ElisaAlmeida** [comment]
Hey @igraziatto, I created an image with the correct padding. See the image below, I added 8 px, so with the line height we have the same padding as we have for the button.

<img alt="screen shot 2019-02-08 at 1 19 37 pm" width="1023" src="https://user-images.githubusercontent.com/45467951/52497618-7b03fa80-2ba4-11e9-9c0e-0983f45c39ab.png">

If you have any questions, let me know.
