### ISSUE TITLE
Keystone: Line-itis on the comments page

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8355]
This is sort of related to #8350. There are too many lines with too cramped of spacing on the comments page.

I'd like to see some consistency in the lines and spacing between `h2` headings on the comments page of discussions.

<img width="1025" alt="national_suicide_prevention_lifeline_guide_released__dealing_with_suicide_ _vanilla_staff" src="https://user-images.githubusercontent.com/97432/52509371-ddb9be00-2bc5-11e9-92c3-631af00adf31.png">

In the above screenshot there are two headings, but their spacing is inconsistent. It also looks odd when a heading is boxed between two lines. Perhaps @ElisaAlmeida can clean up the design a little?

**Comment by ElisaAlmeida** [comment]
Hello Isis, please find a screenshot with the new spacing between elements. We won't have a line before the title, you can remove. About the spacing, after the title "Comments" or "Leave a Comment" we'll have 8px + the line-height (see the image below). And we increase the top margin from the title "Leave a comment", will be the same as the "Comments": 20px + the line-height.

<img width="1019" alt="screen shot 2019-02-11 at 3 58 03 pm" src="https://user-images.githubusercontent.com/45467951/52593001-da1c7600-2e15-11e9-94ac-11b115ab5906.png">

If you have any questions, let me know.
