### ISSUE TITLE
Keystone: Vertical alignment on panel counts

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8361]
The vertical alignment on panel counts is too high. It looks like it can be fixed by removing the bottom margin on the specific `.Panel h4 .Count` selector, but design should confirm.

<img width="264" alt="vanilla_staff" src="https://user-images.githubusercontent.com/97432/52521985-895a2100-2c4d-11e9-9eee-b913eb167b74.png">

**Comment by ElisaAlmeida** [comment]
Hey Isis, 

please find below an image with the correct alignment.

<img width="368" alt="screen shot 2019-02-11 at 4 21 56 pm" src="https://user-images.githubusercontent.com/45467951/52594605-edc9db80-2e19-11e9-82dc-71d1ec724706.png">

If you have any question, let me know.
