### ISSUE TITLE
Keystone: Rich editor zooms on mobile

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8369]
When I'm posting a comment on mobile the browser zooms when the rich editor receives focus. This is presumably because the font is less than 16px in the editor. We usually do 16px as the body text font size for mobile.

![unadjustednonraw_thumb_4549](https://user-images.githubusercontent.com/97432/52538738-18e1fb80-2d44-11e9-84f0-eb6d26b532af.jpg)

In the above screenshot it's hard to see, but the padding is not visible because the browser zooms. When I post it stays zoomed which is a UX issue.

**Comment by charrondev** [comment]
This is fixed in foundation BTW.
