### ISSUE TITLE
Keystone - Banner colour Desktop vs Mobile

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#8374]
Custom banner colour is not consistent between desktop and mobile.

**Vanilla info**
https://console.vanilladev.com/sites/view/config/6031218/tpfadfa.vanillacommunities.com

**Screenshots**
![image](https://user-images.githubusercontent.com/43580255/52581453-cc0c2c80-2df8-11e9-983d-9e342905e577.png)

![image](https://user-images.githubusercontent.com/43580255/52581469-d5959480-2df8-11e9-958a-c9a30659f016.png)

**Comment by FarhanVanilla** [comment]
@igraziatto Sorry, I'm not able to assign it for some reason.

**Comment by FarhanVanilla** [comment]
Also, this is what happens on desktop when i scrunch the window size 
![image](https://user-images.githubusercontent.com/43580255/52582447-3c1bb200-2dfb-11e9-912a-e0951ee29093.png)

**Comment by Bparm** [comment]
@FarhanVanilla This is because you need to set CustomTheme.OverrideMobile: True in the config to apply the styles to mobile.
