### ISSUE TITLE
Rich Editor conflict with Reactions: Reacting removes code colored syntax

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8377]
Reproduced on OSS forum: https://open.vanillaforums.com/discussion/36997

Reacting to a comment removes code syntax coloring from all comments. The entire code block turns the default gray color. Refreshing the page re-colors the code. Reacting again removes it.

**Comment by linc** [comment]
The "Draft saved" notification appears to trigger the same effect.

**Comment by charrondev** [comment]
I can't reproduce this even on the given link as of `release/2019.009`. Please re-open if you still can.
