### ISSUE TITLE
Keystone:  can't switch mobile theme back to Keystone.

### ISSUE THREAD

**Issue by rhysboswarva** [vanilla/vanilla#8385]
- set Desktop Theme to Keystone (it also sets the mobile theme to Keystone)
- click Mobile Themes tab
- change the Mobile Theme (e.g. to Lithe)
At this point there is no option to change the Mobile Theme back to Keystone.  Only way I could do it was to change the Desktop Theme to something else, then back to Mobile Theme

@igraziatto

**Comment by charrondev** [comment]
This is actually a bit of a core product deficiency. We haven't updated the themes page and ages and the way keystone sets itself as a mobile is really just a big workaround.

If you don't mind I'm going to close in favour of https://github.com/vanilla/vanilla/issues/7363.
