### ISSUE TITLE
theme-boilerplate: Make icons for the Themes section on the Dashboard

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8388]
Whenever when someone gets the [boilerplate package](https://www.npmjs.com/package/@vanillaforums/theme-boilerplate) the screenshot that comes as default is a Vanilla logo with the blue background with very little thought put into it.

It would be nice to have an icon or image that represents what the boilerplate is.

This image would display on dashboard/settings/themes :
![screen shot 2019-02-14 at 12 24 33 pm](https://user-images.githubusercontent.com/31521020/52805155-f9a0e200-3053-11e9-918c-101bcd221ecf.png)

And here for mobile:
![screen shot 2019-02-14 at 12 24 45 pm](https://user-images.githubusercontent.com/31521020/52805164-fe659600-3053-11e9-8f3e-2cabf1b19af1.png)

**Comment by ElisaAlmeida** [comment]
Hello Isis,

I sent you an e-mail with the images. If you have any questions, let me know.

thx,
Elisa
