### ISSUE TITLE
Keystone: OverrideMobile: True should be set in config when Keystone is applied

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#8395]
Because Keystone is mobile responsive and applies itself in the MobileTheme section, an extra step, namely, adjusting the config to CustomTheme.OverrideMobile.True, is required to apply the CSS changes to mobile. Note that you need to visit the site on an actual mobile device to see the issue.

I am not sure what happens if you change to a different theme (though I don't know why you would) to that config setting so that should be considered.

Leaving it as is is going to result in a lot of support when users inevitably forget to make this config setting. It's also a bad experience for our clients if they require us to do something to get their theme to work.

@igraziatto

**Comment by oliveratgithub** [comment]
I manually "fixed" this by adding

```"isMobile": true,```

within the file `/themes/keystone/addon.json`

But this should be added by default; at least as long as Vanilla is not reading & listing Themes that only use the `"isResponsive": true,`-setting to list a Theme under "Mobile Themes" as well.
