### ISSUE TITLE
RichEditor has typo for config setting

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8396]
In line 11 you find the definition "Quote":
`   const QUOTE_CONFIG_ENABLE = "RichEditor.Quote.Enable";`

In line 30 it is used like that "Quote**s**":
`        saveToConfig('RichEditor.Quotes.Enable', true);`

Not sure what the consequences are or what would be preferred...

**Comment by charrondev** [comment]
The consequence here is that rich quotes will not be enabled on new installations, even if we want it to be. It's not exactly critical because the dashboard toggle to enable (appears when you select the rich format) handles this properly. It should be an easy enough fix though.

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/8691
