### ISSUE TITLE
Add ability to choose format type when advanced and rich editor are disabled

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8409]
Currently we set Garden.InputFormatter = 'rich' in the config-defaults file.  Type _rich_ shouldn't be the fall back format, it poses a problem if users are unable to post in rich format.  The default should be set to something like _markdown_.  When the rich-editor is enable during setup it will then set the config value to type _rich_.  So _rich_ will be the primary format type, but the fall back will be _markdown_.

**Comment by charrondev** [comment]
After some in-person discussion with @cchabilall83 I've requested he make this issue broader. I think the current defaults are appropriate and the real use case here is to use a format like `BBCode`/`Markdown` without any editor.

This is currently possible by setting the config value manually, but we could also move those 2 formats form the Advanced Editor event hook into the core default values with no editor.
