### ISSUE TITLE
Rich Editor posting invalid json

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8419]
Currently there are some posts are being saved with invalid json in the body.  This is causing requests to fail and throw 500 errors.  I'm in the process of gathering more data and reproduction setups.  

details can be seen in Vanilla/Support#212.

We should do the following:

1) Prevent invalid json from being posted
2) Fortify the filter method we are using currently.

More info to come.

**Comment by charrondev** [comment]
3. Fix the thing that's tripping up the parser. Error here. It can be triggered pretty easily by submitted a post while a file is uploading.

![image](https://user-images.githubusercontent.com/1770056/53102328-6d7e3700-34f9-11e9-9ca1-ff55a5296d0c.png)

**Comment by michaeltyson** [comment]
Users are seeing this on some "My Drafts" pages, as well as a few active thread pages. Checking the database reveals that, sure enough, the JSON in the Body field is a dictionary with numeric keys, rather than an array.

**Comment by michaeltyson** [comment]
I repaired my database thus:

    UPDATE `GDN_Comment` SET `Body` = JSON_EXTRACT(`Body`, '$.*') WHERE `Body` LIKE '{%' AND JSON_VALID(`Body`)
