### ISSUE TITLE
Message notifications show JSON, rather than text content

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#8427]
**Describe the bug**
On-site notifications for incoming messages show JSON content, rather than the actual message text.

**Vanilla info**
Observed on open.vanillaforums.com on Feb 20.

**Screenshots**
![screen shot 2019-02-20 at 16 15 57](https://user-images.githubusercontent.com/184008/53068062-1729ec00-352b-11e9-8112-73a3d1fb3230.jpg)

**Comment by charrondev** [comment]
@pioc92 Actually reported this very recently. I have a PR open for it already. https://github.com/vanilla/vanilla/pull/8397

Closing in favour of #7678

**Comment by michaeltyson** [comment]
Whoops, beg pardon.

**Comment by charrondev** [comment]
Ha no problem. The 2.8 release has brought on a big influx of bug reports and feature requests with keystone and rich editor. Trying to triage them a prioritize them all.
