### ISSUE TITLE
Sporadic issue when using rich quotes: "null is not an object" in rich-editor.min.js

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#8428]
**Describe the bug**
Unclear how this reproduced, but a javascript error occurs when using rich quotes sometimes - perhaps related to the subsequent use of the quotes button after making a post, but I wasn't able to reproduce this.

**Vanilla info**
2.8/Keystone

**To Reproduce**
Unclear.

**Screenshots**
![screen shot 2019-02-20 at 16 45 59](https://user-images.githubusercontent.com/184008/53069252-5823ff80-352f-11e9-8f1c-3ef07159f168.jpg)
![screen shot 2019-02-20 at 16 46 10](https://user-images.githubusercontent.com/184008/53069253-58bc9600-352f-11e9-99c9-bcde5a05ec7e.jpg)

**Comment by charrondev** [comment]
Without reproduction steps we can't really do much with the issue. A lot has changed even since 2.8 so if something like this comes up again please file a new issue.
