### ISSUE TITLE
Update paragraph menu for rich editor - Tab UI for paragraph menu

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#8434]
Redesign UI for paragraph menu based on new mockups.

Switch to a "tab" panel layout. Must be accessible. New features will be estimated on separately, except this task includes more levels of paragraphs.

Related: https://github.com/vanilla/vanilla/issues/8435
Related: https://github.com/vanilla/vanilla/issues/8436
Related: https://github.com/vanilla/vanilla/issues/8531

**Comment by charrondev** [comment]
From @ElisaAlmeida 

> Hello Stéphane,
> 
> so this is the mockup for our new editor paragraph menu:
app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7d7a3754f0d1bc904f3c44
> 
> I did 2 options: 1 has the same design that we have today (that is gray) and the other one, is the one that we want to implement in the future. If it's not complicated to code the second option now, better!
> 
> When you start, we can talk about it.

**Comment by ElisaAlmeida** [comment]
The mockup for our new editor paragraph menu:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7d7a3754f0d1bc904f3c44

**Comment by slafleche** [comment]
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-2/menubar-2.html
