### ISSUE TITLE
Design the new editor paragraph menu 

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8437]
This is the paragraph menu with additional support for h2-h5 and list indent/outdent. There are [currently mockups](https://drive.google.com/drive/u/0/folders/1yMK0n1oag4KYvrydICeFDjHobQoyc8TX), but we need to finalize them with reduced scope.

**Comment by slafleche** [comment]
@ElisaAlmeida if you're part is done and you have an issue for the implementation, you can close this issue. Bonus points if you add a link to the new task.

**Comment by charrondev** [comment]
FWIW there was a new task opened, but I closed it and pointed it to your existing UI task.
