### ISSUE TITLE
Style Regressions from #8449

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8456]
https://github.com/vanilla/vanilla/pull/8449

Some visual regressions are left over after that pull request

## Compact Search

|Actual|Mockups|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/53428279-8040b200-39b8-11e9-9515-e43f4c7f5aa6.png)|![image](https://user-images.githubusercontent.com/1770056/53348121-764f7e00-38e8-11e9-8e6a-71127e95e07a.png)

- Incorrect background colour
- Incorrect border radiuses on the right side.
- This affects mobile and desktop.

## Dropdowns

|Actual|Mockups|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/53428378-af572380-39b8-11e9-9019-1b7361696a57.png)|![image](https://user-images.githubusercontent.com/1770056/53348416-01307880-38e9-11e9-9fce-e49963ba6f11.png)|

- Hover styles incorrect.

|Actual|Mockups|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/53428483-e0cfef00-39b8-11e9-9391-e2aeb5fd5fac.png)|![image](https://user-images.githubusercontent.com/1770056/53428565-05c46200-39b9-11e9-92fa-01d518385f2f.png)|

Normal dropdowns seem to be missing the top and bottom paddings now. We should make sure we __don't__  accidentally add it back on something like the mebox dropdowns. Maybe we need a prop to control this?

## Nav Manager

|Actual|Mockups|
|---|---|
|![image](https://user-images.githubusercontent.com/1770056/53347829-ea3d5680-38e7-11e9-9e29-b65801fec70b.png)|![image](https://user-images.githubusercontent.com/1770056/53347811-df82c180-38e7-11e9-9221-9126d47e2640.png)|

- Too much horizontal padding.

**Comment by slafleche** [comment]
Everything but the "Compact Search" is in my next PR. I'll double check with Elisa to make sure things didn't change. I added that border radius after talking to her.

**Comment by slafleche** [comment]
Moved dropdown issue to another task: https://github.com/vanilla/knowledge/issues/731
