### ISSUE TITLE
Rich Editor: Box size on Warning & Notes

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#8458]
**Describe the bug**
Warning & Notes, the window is too skinny.

**Vanilla info**
This is on hosted, using Keystone

**To Reproduce**
1. Go to any profile
2. Click on Add Note or Add Warning
![image](https://user-images.githubusercontent.com/425366/53516992-9a9f8c00-3a9b-11e9-9eb7-53f10fcb104d.png)

**Expected behavior**
The box seems a bit small. Older editor, the box was a bit larger.

**Comment by charrondev** [comment]
Fixed in 2019.004.
