### ISSUE TITLE
Empty categories need a design iteration

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8459]
This page needs some love:

![empty-category.png](https://images.zenhubusercontent.com/57087d1abf93871ccd991f73/40028331-c210-4c91-bae6-1c7e629247c2)

I think in this case the "This category does not have any articles" should be displayed similar to a no search results which is just simple text. The button can stay as is or just be a link.

**Comment by tburry** [comment]
Just adding Stephane to mark this as a multi-person task.

**Comment by ElisaAlmeida** [comment]
I created the page @slafleche. It's on Zeplin: Latest Mockup.

**Comment by ElisaAlmeida** [comment]
#748 > implementation issue.
