### ISSUE TITLE
Rich Quoting a discussion requires edit permissions

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8463]
**Describe the bug**
Attempting to quote a discussion fails unless the user has the `Discussion.Edit` permission for that resource.

**To Reproduce**
1. Sign in with a user _without_ the `Vanilla.Discussion.Edit` permission.
2. Copy a link to a discussions
3. Go to make a rich post somewhere.
4. Attempt to embed that comment
5. Observe the error:

![image](https://user-images.githubusercontent.com/1770056/53529323-3b9d3f80-3aba-11e9-8d1e-17b951f64a27.png)

The style of the error is also broken.

**Expected behavior**

No error displays and the post embeds.

**Additional context**

This is likely because we need the raw content of the post in order embed so it uses the GET `/api/v2/discussions/:id/quote` endpoint. This endpoint is not actually **editing** a post and shouldn't use the edit permission, just the read one.

**Comment by planitnov** [comment]
there is an open permission set:
https://github.com/vanilla/vanilla/blob/7563b78f16cd969bd81a55a0d30e031681741051/applications/vanilla/controllers/api/DiscussionsApiController.php#L347-L348
