### ISSUE TITLE
Add consistent navigation to the keystone header

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8465]
Mobile & Desktop should both have the following links:

- Community.
- Help (with KB) if enabled.

**Comment by ElisaAlmeida** [comment]
Adam,

please find below the link with the mockup:
Desktop:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7ff205ede03b34df4a5476
Mobile:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7ff205081f474d0097dfe3

**Comment by charrondev** [comment]
Ah oops, looks like were sharing the same task. This is my sprinted task for implementation of the feature.
