### ISSUE TITLE
New editor paragraph menu

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#8487]
Hello Stéphane,

so this is the mockup for our new editor paragraph menu:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7d7a3754f0d1bc904f3c44

I did 2 options: 1 has the same design that we have today (that is gray) and the other one, is the one that we want to implement in the future. If it's not complicated to code the second option now, better!
 
When you start, we can talk about it.

**Comment by charrondev** [comment]
Closing for https://github.com/vanilla/vanilla/issues/8434
