### ISSUE TITLE
Add breadcrumb to results on search endpoint of categories API resource

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8496]
GET requests to [/api/v2/categories/search](https://github.com/vanilla/vanilla/blob/0aedb5a837b4515f7d55543722d2576c85625fa6/applications/vanilla/controllers/api/CategoriesApiController.php#L191) should include the ability to expand the item's breadcrumbs. This could be an update to the endpoint's expand parameter.

**Comment by charrondev** [comment]
See `Vanilla\Navigation\Breadcrumbs`

**Comment by tburry** [comment]
I would like to lessen the breadcrumbs that we display to include just the following:

- **Guides**: Just the knowledge base link.
- **Help Center**: Knowledge base > category > category > etc.
