### ISSUE TITLE
Design application update notice

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8503]
When the application has deployed a new version of the code there should be an alert box to urge an update.

"The application has been updated. Refresh to get the latest version." **Refresh**

- In the message above **Refresh** is a button.
- This message should be fixed near the top and hover over everything.
- This won't act like a modal, but should have the same shadow effect as one due to its importance. (It would be a modal, but we want to give the user a chance to save work before refreshing so it just floats).

**Comment by ElisaAlmeida** [comment]
It's done. The mockup:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c914b9cc4b29f250d0fa654
