### ISSUE TITLE
Conversion prompt when editing a non rich format

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#8505]
Hey Adam @charrondev :

The mockup:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c79b03ec36416627a3c64e0

When a user edits an article that is formatted as a non-rich post the editor converts the article which may wreck adversely affect some of the formatting. So, in this case, we will put an alert at the top of the editor that tells the user what happened and have an additional cancel button.

The message should say: "The text has been converted from FORMAT. As a result, you may lose some of your formattings. Do you wish to continue?"
There will be OK/Cancel buttons.
OK dismisses the message.
Cancel is the same as hitting cancel at the top of the editor.

**Comment by charrondev** [comment]
Closed by https://app.zenhub.com/workspace/o/vanilla/knowledge/issues/869
