### ISSUE TITLE
Design mobile revisions page

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8532]
The desktop version of this page has drafts and revisions combined. The [mobile mockup](https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7d76cf006431bcf6597c03) needs to have the drafts section and the **Load More** button added.

**Comment by ElisaAlmeida** [comment]
It's done. 
Mockups:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c915482c2d2d2052d257d49
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c9154829663d7251971443c
