### ISSUE TITLE
InThisDiscussion addon is duplicating user names based on their number of comments

### ISSUE THREAD

**Issue by linc** [vanilla/vanilla#8543]
<img width="244" alt="Screen Shot 2019-03-15 at 3 19 26 PM" src="https://user-images.githubusercontent.com/117672/54456810-1d7c4400-4736-11e9-9a6e-53758f0cfaa8.png">

Seems bad.

**Comment by linc** [comment]
https://open.vanillaforums.com/discussion/36983/vanilla-2-8-is-now-available#latest

**Comment by linc** [comment]
I believe this was caused in https://github.com/vanilla/vanilla/pull/8394

**Comment by bleistivt** [comment]
This was fixed by #8546
