### ISSUE TITLE
Rich Editor: no way to delete rich content on mobile

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8548]
The keyboard on my mobile browser (Fennec on Android) behaves strange around embedded content. Hitting the delete key right after rich content makes the keyboard simply disappear. It is also not possible to mark such a content. 

Problem can be reproduced by inserting a url from a mobile device and trying to delete it afterwards

**Comment by charrondev** [comment]
@R-J The unfortunate thing is there is just no way to get the keyboard to stay up properly consistently across browsers.

I think what we really need to some tooltip when an embed is selected to delete/remove it.

**Comment by R-J** [comment]
I tried if there is some long-press action, that would be something others might think of, too. But having an overlay with a delete button would be more intuitiv

**Comment by charrondev** [comment]
Long presses tend to be overly hidden for something that should probably be obvious. It also gets more complicated on iOS devices that have pressure sensitivity to trigger different actions while holding.

**Comment by jamesinc** [comment]
Hey, you guys have implemented a focus popup that lets you set alt text on images, have you considered adding a ❌delete button too?

**Comment by charrondev** [comment]
We have! We actually got some mockups from our designed recently, so it's in our near term roadmap.

![image](https://user-images.githubusercontent.com/1770056/65769141-dfa6a200-e100-11e9-9957-e4adc3f2373a.png)

**Comment by charrondev** [comment]
WIP PR here https://github.com/vanilla/vanilla/pull/9767

**Comment by tburry** [comment]
Closes https://github.com/vanilla/support/issues/276.
