### ISSUE TITLE
combinePaths function returns invalid URL on Windows

### ISSUE THREAD

**Issue by austins** [vanilla/vanilla#8551]
The [combinePaths function](https://github.com/vanilla/vanilla/blob/90604602f64b91d38ba74193f50e6947df0734ef/library/core/functions.general.php#L600) returns invalid URL on Windows.

First noticed in DiscussionFilter module's "Recent Discussions" link. I have not investigated whether other links where combinePaths has been called have this issue as well.

**Environment info:**
1. Vanilla 2.8.1
2. Windows Server 2019, IIS 10, PHP 7.2.7 (VC15 x64), MariaDB 10.3.13
3. Windows 10 with Laragon software stack: Apache 2.4.37, PHP 7.3.2, MariaDB 10.3.13

**To reproduce:**
1. Have Vanilla running on PHP under Windows.
2. Go to any page where the DiscussionFilter is shown.
3. See the "Recent Discussions" link href is `href="/\discussions"`. This causes the browser to navigate to `https://discussions/` when clicked.

This appears when hosted under both IIS and Apache, so it doesn't seem to be caused by the choice of web server.

**Expected behavior:**
The "Recent Discussions" link href should be `/discussions`.

**Additional context:**
- Above observations are with Vanilla at root of domain. I've tested with moving Vanilla to a subfolder (e.g. /forum) and the href looks like `/forum/\discussions`, which is invalid too, but the browser will route it to `http://example.com/forum//discussions` when clicked so it will route correctly nonetheless.
- https://open.vanillaforums.com/discussion/comment/256248/#Comment_256248

**Debugging notes:**
- Regarding the "Recent Discussions" link itself, if you change [this line in Gdn_Theme::Link](https://github.com/vanilla/vanilla/blob/90604602f64b91d38ba74193f50e6947df0734ef/library/core/class.theme.php#L260) to pass a delimiter argument like `$path = combinePaths(['/', $route], '/');`, the link href is fixed as expected.
- Looking at the root cause, the combinePaths function uses the DS constant as the default delimiter. This function seems to be called across many files in Vanilla _for both links and file paths_, so I'm not sure if changing this would adversely affect its usage across Vanilla.
- Upon changing the default delimiter in combinePaths to `'/'`, Vanilla still functions as expected overall. For instance, controllers still load the master view paths correctly. I haven't checked every single link, though.
- Again, DS is `\` on Windows and `/` on Linux. Windows supports both backslashes and forward slashes as a path separator. If necessary, backslash is only good for file paths, but URLs should always use forward slash.

Open to discussion with Vanilla devs on what a good fix may be.

**Comment by hynsey** [comment]
Is there any resolution to this? I have this exact situation, and it is causing problems on the site. Appreciate if there is any quick workaround I can apply. Thanks.
