### ISSUE TITLE
Keystone Theme - Avatars in Conversations

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#8560]
**Describe the bug**
Avatars and Conversation titles in the Mailbox overlap. Issue was reported to me by GolfWRX and I was able to replicate it on my staging site. 

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
2. Did you follow our generic troubleshooting steps already?
3. What Vanilla version are you using?
4. When did the issue start?

**To Reproduce**
1. Go to your Inbox
2. View all messages
3. Scroll down

**Expected behavior**
Avatars and conversations titles should not overlap. Should be easy to read. It seems like there's no padding around the avatar class.

**Screenshots**
![image](https://user-images.githubusercontent.com/43580255/54721244-cf9d7c80-4b37-11e9-8b25-04c1102a6489.png)

![image](https://user-images.githubusercontent.com/43580255/54721258-daf0a800-4b37-11e9-992d-0394081b3bb5.png)

**Comment by charrondev** [comment]
@FarhanVanilla These reproduction steps don't work outside of their specific site. Have you followed standard troubleshooting steps? It might be best to handle this as an internal support issue, but this is definitely not the case on any other site I try. Maybe some pocket or custom theme?

**Local Machine**
![image](https://user-images.githubusercontent.com/1770056/54723933-7afdff80-4b3f-11e9-947f-a113a1f596ae.png)

**OSS Forum**

![image](https://user-images.githubusercontent.com/1770056/54723944-87825800-4b3f-11e9-8004-65bee4a16a71.png)

**Staff Forum**

![image](https://user-images.githubusercontent.com/1770056/54723958-92d58380-4b3f-11e9-8f78-b4a4952d27ac.png)

**Comment by FarhanVanilla** [comment]
The first screenshot is from my demo. It appears to only happen on the second line of the conversation title. 

If it's an issue that only happens on GolfWRX I'll have him check his custom theme.

**Comment by charrondev** [comment]
It would help to link so somewhere it's happening in that case.
