### ISSUE TITLE
"Recent discussions" link has unnecessary slash on Windows/ISS

### ISSUE THREAD

**Issue by vintprox** [vanilla/vanilla#8561]
**Describe the bug**

"Recent discussions" link in sidebar (2nd on fresh installation) redirects to wrong location `/index.php?p=/\discussions` or `//discussions` (when using friendly URLs). Additional slash is unnecessary there, also I don't have idea how it appears.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? **It's happening with bare minimum.**
2. Did you follow our generic troubleshooting steps already? **Unreleated.**
3. What Vanilla version are you using? **2.8.1**
4. When did the issue start? **Since installation.**

**To Reproduce**

1.1. Go to main page via `/`.
1.2. Click "Recent discussions".
1.3. Link sends to `//discussions` which is wrongly typed, which leads to Not Found.

2.1. Go to main page via `/index.php?p=/`.
2.2. Click "Recent discussions".
2.3. Link sends to `/index.php?p=/\discussions` which is wrongly typed, which leads to Not Found.

**Expected behavior**

Wanted to see recent discussions after pressing this link but no luck.

**Screenshots**

![image](https://user-images.githubusercontent.com/5708819/54744452-1773e080-4bd8-11e9-9acc-b63efd9bd47f.png)

It's second on screenshot. Russian language. Language doesn't affect the link.

**Comment by charrondev** [comment]
I went and dug up the context, because it seemed similar, but in the future I would recommend linking the open source forum thread on the subject and mentioning that you are using ISS.

https://open.vanillaforums.com/discussion/37123/recent-discussions-link-has-backslash-in-it-index-php-p-discussions

**Comment by vintprox** [comment]
@charrondev good observation. Yes, unfortunately I have to use Windows on my testing environment, so it should not be an issue when deployed to Linux according to what you noticed.
I hope that it doesn't affect many links so in that case I rate it as potentially low prioritized fix.

**Comment by charrondev** [comment]
In that I'm going to close this one. Please track over at #8551. @austins has informed us that `/` is actually a valid path separator on windows, so we just remove our OS-specific handling in this regard everything should work correctly on windows.

I'd support a PR doing that, but I don't have a windows machine to test on.
