### ISSUE TITLE
Keystone: Navigation for Community Owners on Mobile

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#8564]
Currently there is no menu item on a mobile for people to be able to access the dashboard. Which means unless you know the url to the dashboard by heart, there is no way for an admin or staff to log-in to review the moderation/spam queue on the go.
![IMG_B3B87E975BBB-1](https://user-images.githubusercontent.com/425366/54821525-ccf67080-4c78-11e9-9c23-bf40e2c3952a.jpeg)

**Comment by charrondev** [comment]
Did you try looking in the MeBox?

![image](https://user-images.githubusercontent.com/1770056/54938562-edcef800-4efc-11e9-993d-f66157317f14.png)
