### ISSUE TITLE
Keystone Theme - Missing New Message Button from Inbox Screen

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#8584]
**Describe the bug**
There's no button to create a new message from the inbox screen. 

**Vanilla info**
1. Basic Keystone theme has this issue.

**To Reproduce**
1. Go to Inbox Screen
2. See error

**Expected behavior**
Expected to see a button to send messages from the inbox screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/43580255/55004212-309dd800-4fb0-11e9-9930-1cf2d3c9f321.png)

**Comment by charrondev** [comment]
Current workaround:

![image](https://user-images.githubusercontent.com/1770056/55044385-84d8a480-5010-11e9-8c19-d352b04b987c.png)

Use the `+` button in the MeBox.
