### ISSUE TITLE
Link to first topic in Discussion

### ISSUE THREAD

**Issue by Dr-Sommer** [vanilla/vanilla#8601]
**Describe the bug**
The Link of the 1st Topic in a Discussion links to the latest topic of the discussion (whithout "#latest" !)  

**Vanilla info**
using Ver.2,8, but I think this was always faulty since 2.0

**To Reproduce**
1. Go to 1st Topic of the Discussion
2. Click on the Date to get the Link
3. save the Link for example in the same Discussion. ATTENTION! It has to have more than one Page of topics! So save the link to the 2nd Page ore above!
4. klick on the link
5. The link jumps to the latest topic, instead of the 1st.

**Expected behavior**
It must jump to the 1st topic!

**Comment by charrondev** [comment]
Verified. The discussion permalink goes to the wrong location.

**Comment by Dr-Sommer** [comment]
Still the same issue, Vanilla 3.3
