### ISSUE TITLE
Keystone - Search Bar Disappears

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#8610]
**Describe the bug**
Search bar disappears when screen width is from 770 - 994px.
By the default the search lives on the top of the top of the side panel. As such it disappears when the side panel hides. It reappears at the top across the width of the page.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
Core Vanilla
2. Did you follow our generic troubleshooting steps already?
3. What Vanilla version are you using?
4. When did the issue start?

**To Reproduce**
1. Reduce the width of the window to between 770 - 994px and you'll notice it disspears.

**Expected behavior**
Would be nice if the wider search appears right away.

**Screenshots**
![image](https://user-images.githubusercontent.com/43580255/55245231-1dda0c00-5219-11e9-8dd2-df7c639e3eeb.png)

![image](https://user-images.githubusercontent.com/43580255/55245285-32b69f80-5219-11e9-9159-c6bbcdd8bd11.png)

**Additional context**

**Comment by igraziatto** [comment]
Issue reported here: https://github.com/vanillaforums/golfwrx/issues/19
