### ISSUE TITLE
Collect translation strings

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8630]
We need a resource in the locales repo with all of the necessary translation strings for the knowledge base so that it can be translated.

- Call the resource `site_kb.php`.
- Just collect as many strings as possible for this and make a PR against the [locales repo](https://github.com/vanilla/locales).
- Any missing strings are bugs that can be done when caught, but shouldn't block this issue.

**Comment by charrondev** [comment]
Do a search of the following directories.

- `library/src/scripts`
- `knowledge`

Search for the following:

- `<Translate`
- `t("`
- `t('`
- `Gdn::translate(`

**Comment by alex-mtl** [comment]
It is ready check related PRs:
vanilla/locales#186
#8743
vanilla/knowledge#961
