### ISSUE TITLE
Google Sign-In Plugin

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8638]
**Google Sign-In Plugin**

Add the ability for end-users to login to Vanilla using their Google account.  This will replace the current Google+ which has been deprecated by Google.

> Google Sign-In is a secure authentication system that reduces the burden of login for your users, by enabling them to sign in with their Google Account—the same account they already use with Gmail, Play, and other Google services.

**User Story**

As a user I would like to allow members to login to the community using their Google Account.

**Acceptance Criteria**

- Create basic plugin with plugin class, settings view, js folder, design folder for CSS.
- Add a toggle to '/social/manage' for Google Sign-In (Similar to Google+).
   - Add settings menu to configure 
- Add Plugin to extend Vanilla's Oauth2 class
  - Create a config form for dashboard:
    - Create a view (twig template).
    - Create form fields/validation: Client ID and Client Secret
    - Write user instructions.
  - Create button to link to Google Sign In
  - Make call to Google's OpenID discovery to get the OAuth2 endpoints.
- Create client facing docs (with links to Google's docs).
- Create technical docs (README).
  - Add testing steps.
- Delete Google Plus plugin.
- Create graphics (create issue).
- Update existing Google+ UnitTest.

**Additional context**

**Mockups**

**Related Issues**

**Comment by vrjrobitaille** [comment]
Epic seems to be completed.
