### ISSUE TITLE
Delete Google+ Plugin

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#8646]
Delete the Google+ plugin. Support ended Apr. 2

**Comment by charrondev** [comment]
Blocked for sure by these guys which have a hard coded plugin check for it. https://github.com/vanillaforums/amplify/blob/8a12f9fb2d237327391dc0746470a3b3743a6621/themes/amplifystudent/views/entry/signin.php

**Comment by alex-mtl** [comment]
@charrondev Can we move plugin to that repository then?

**Comment by charrondev** [comment]
That site is no longer valid. I had @linc archive the repo.

**Comment by vrjrobitaille** [comment]
This seems to have been completed here - https://app.zenhub.com/workspaces/rd-kb-556cc3adbfcecd111b957933/issues/vanilla/vanilla/8667
