### ISSUE TITLE
Link Warning Leaving feature not compatible with Rich Editor

### ISSUE THREAD

**Issue by Kippinn** [vanilla/vanilla#8649]
Hi, I found out that a feature I use, the "Warn users when they are leaving" is not working anymore on Vanilla 2.8.1 and Ruch Editor 1.0.1.

**Comment by charrondev** [comment]
The trusted domains feature has not yet been implemented in Rich Editor. You can track the issue/feature development over at https://github.com/vanilla/vanilla/issues/8254.

Rich Editor is under active development so this is on our near term roadmap. For example recently, we added more heading levels, nested lists, and improved formatting menus. This will probably be the next enhancement.
