### ISSUE TITLE
Emoji Auto insert error in Advanced Editor

### ISSUE THREAD

**Issue by Dr-Sommer** [vanilla/vanilla#8679]
Vanilla Version: 2.8 (This Bug seems to be till Ver. 2.0)
Editor used: Advanced Editor in HTML mode from Dane MacMillan

**Describe the bug**
After changing from bold to italic to normal Text format and using in between the Emojis in WRITTEN Form ( for example >>>` :smile: `)
The first written emoji is ok, then after altering the fontstyle and typing the emoji again, it copy itself wrongly into the text... 🙄
(see the [Pictures in the Vanilla Help Forum](https://open.vanillaforums.com/discussion/comment/256603#Comment_256603)) 

**To Reproduce**
write a text in bold, after type for example " :smi " for smile and then press enter (to take over the emoji from the dropdown list)
type something in normal style and also type in an emoji and press enter
change again in bold or italic and goto 1

**Expected behavior**
Set Emoji without Errors

**Additional context**
Here The Topic from Vanilla Help Forum, with Images of the Problem:
https://open.vanillaforums.com/discussion/comment/256603#Comment_256603

**Comment by charrondev** [comment]
Advanced Editor is no longer an actively developed plugin. I'd recommend moving to the Rich Editor, which has much more robust handling of Emojis among other things. 

It is our default editor starting with Vanilla 2.8.
