### ISSUE TITLE
Rich Editor - Unable to edit comments with 'Plugins.editor.ForceWysiwyg' enabled

### ISSUE THREAD

**Issue by cchabilall83** [vanilla/vanilla#8711]
### Issue
When trying to edit  'rich' format comments, with a post format of 'wysiwyg' and the Plugins.editor.ForceWysiwyg equal true, the editor doesn't mount properly and users aren't able to edit their comments.

### Details

It appears that because the editor has a format="Wysiwyg" the rich editor is trying to mount but since the format type isn't rich we get this error.

```
async~mountEditor.min.js:193 Uncaught (in promise) Error: Unsupported initial editor format Wysiwyg
    at Module.hn (async~mountEditor.min.js:193)
    at rich-editor.min.js:19
    at NodeList.forEach (<anonymous>)
    at rich-editor.min.js:19
    at c (vendors.min.js:42)
    at Generator._invoke (vendors.min.js:42)
    at Generator.e.(anonymous function) [as next] (https://dev.vanilla.localhost/dist/forum/vendors.min.js?h=2.8.1+2019.005:42:8411)
    at r (vendors.min.js:12)
    at s (vendors.min.js:12)
```

### To Replicate

1. Enable Rich Editor
2. Create discussion and comment with rich format 
3. Change post format to Wysiwyg
4. Toggle "Reinterpret All Posts As Wysiwyg" to on
5. Try to edit the new comment

### Possible Solution:

TBD

**Comment by charrondev** [comment]
Followup notes from the support demo:

This is caused by having both Rich Editor enabled & the the wysiwyg reintrepret issue because both of them run their `gdn_form_beforebodybox_handler` events.

In fixing this you can either:

1. Ensure Rich Editor is disabled when this configuration option is checked.
2. Make WYSIWYG editor aware of the `Rich` format, and do NOT respect the re-interpret configuration of the post is rich.
3. Make Rich editor aware of this setting.

I think 2 is the best option. Maybe have WYSIWYG disable the rich editor configuration on startup if that option is checked?

@initvector Do you have any thoughts here?

**Comment by cchabilall83** [comment]
I think option 2 seems the best @initvector any suggestions?

**Comment by initvector** [comment]
Of these options, I like number three the best.

- Enabling/disabling an addon based on a config's status, which can change at any time, seems like a slippery slope.
- If the "error" is in Rich Editor, I think that's where the fix should go. Advanced Editor is attempting to do what it says it'll do: convert everything to WYSIWYG. If Rich Editor doesn't play well with that, it should be defensive about it. These cross-addon interactions can make for headaches, but I like the idea of Rich reading another addon's config much more than the idea of Advanced Editor managing Rich Editor's enabled status or having specialized handling for Rich Editor's format in Advanced Editor.

**Comment by charrondev** [comment]
@initvector I'd liken it to a battle for what gets to control the event.

Rich Editor see the body box event fired with the format "Rich" and goes "I can handle this".

We need to keep in mind what behaviour we want here. In the future Rich Editor will be capable of essentially doing the exact same thing and in that case, I think Rich Editor should be the one that can reinterpret WYSIWYG, not the other way around.

@cchabilall83 In case you didn't already, the simple workaround is to disable Rich Editor if you aren't using the rich format and are using the re-interpret setting, and have existing rich posts.

**Comment by initvector** [comment]
> We need to keep in mind what behaviour we want here. In the future Rich Editor will be capable of essentially doing the exact same thing and in that case, I think Rich Editor should be the one that can reinterpret WYSIWYG, not the other way around.

I don't think kludging Addon A to fix problematic behavior in Addon B is the solution. If an addon is functioning as expected, but Rich Editor isn't compatible with that behavior, I don't think it should be the responsibility of the other addon to have a special case setup for Rich Editor. It sounds like Rich Editor can have a very simple check to overcome this issue. As such, that seems like the more sensible avenue to me.

**Comment by charrondev** [comment]
After some discussion with @initvector we've concluded that a proper fix to this would likely best come when R&D implements conversions of Advanced Editor posts to rich editor, along with some minor UI tweaks, and a renaming of the configuration value.

Until then, this workaround should be sufficient.

**Comment by cchabilall83** [comment]
I will notify the csm about the work around.
