### ISSUE TITLE
Make sign-in pages use AJAX for form submissions

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8714]
Vanilla's entry pages are one of the only areas of the application that require a guest user to have a cookie. This is due to transient key checks that are performed in some requests. Alternative, cookie-less methods of these checks should be implemented on at least the registration and sign-in pages.

The proposed implementation is forgoing the cookie for guests, hijacking their entry form submissions with JavaScript and instead submitting them as AJAX requests, which should include the X-Requested-With header. Vanilla supports this as an alternative to its transient-key-based CSRF protection (introduced in #7068). The method is based on [an OWASP article](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.md#use-of-custom-request-headers), which proposes the use of custom headers, along with host and referrer validation.

**Comment by charrondev** [comment]
Investigate what's going to `.js-form` (currently in `global.js`). I'm bumping up the point total because I'm unsure of what the exactly uses this.

**Comment by alex-mtl** [comment]
Please work same branch [feature/8578-x-request-with](url) as: https://github.com/vanilla/vanilla/pull/8763
feature/8578-x-request-with
