### ISSUE TITLE
Inbox icon on Mebox component persists if Conversations is off

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#8730]
Even if the "Conversations" application is off, the inbox icon on the Mebox is still there, leading to a 404.

**Comment by charrondev** [comment]
This is the `<MeBox />` react component being referred to. I needs awareness of if conversations is enabled or not.

**Comment by charrondev** [comment]
After some brief discussion we've decided to preceed similar to the current system, where core is aware of conversations, and just takes the addon enabled config.
