### ISSUE TITLE
ProfilePhoto in Mebox changes when you're on an another user profile page

### ISSUE THREAD

**Issue by irina-vanillaforums** [vanilla/vanilla#8731]
The Profile Photo of your user changes when you're going on an another user profile page to his Profile Photo. 

![Screen-Shot-2019-04-25-at-10 12 28-AM](https://user-images.githubusercontent.com/47985967/56742771-61a23180-6743-11e9-830e-6365dbc6180d.jpg)

**Comment by charrondev** [comment]
Mobile only it seems. Likely related to `NewFlyouts` version of the MeBox.
