### ISSUE TITLE
No spacing for the icons in Mobile navigation (profile page )

### ISSUE THREAD

**Issue by irina-vanillaforums** [vanilla/vanilla#8739]
Removing the display flex ( back to block ) and also adding justify-content: space-between worked for me.

![Screen Shot 2019-04-26 at 4 04 12 PM](https://user-images.githubusercontent.com/47985967/56833978-28022100-683e-11e9-83e8-1521b7eac964.png)

<img width="374" alt="Screen Shot 2019-04-26 at 4 09 30 PM" src="https://user-images.githubusercontent.com/47985967/56834050-60096400-683e-11e9-8bb3-d9bd516b0d8d.png">

**Comment by tburry** [comment]
I'm guessing this is already dealt with.
