### ISSUE TITLE
Embedded comments do not respect formatting config or dashboard settings

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8748]
**Describe the bug**
When using embedded comments, the site's format settings are not respected.

**To Reproduce**
1. Set up embedded comments.
2. Set your text format as `Rich`.
3. Go to a page with embedded comments.
4. Notice a plain text area.

Expected behavior:
The format that I set in my dashboard should be used.

or

1. Set up embedded comments.
2. Set your text format as `Markdown`.
3. Go to a page with embedded comments.
4. Put markdown in the text area.
5. Make a post.
6. Notice the markdown did not get converted into HTML.

Expected behavior:

Markdown is rendered when the text format is set configured to be markdown.

**Additional context**
There's been some back and forth about this such as in https://github.com/vanilla/support/issues/272.

@tburry To me locking these into an older format is worse than before, because now, on top of not using the editor, if my forum format is set to markdown it will not be respected.

**Comment by charrondev** [comment]
I'm leaving this open until the backports are done. Targets are `release/2019.006` and `release/3.0`.

**Comment by cchabilall83** [comment]
Backports
https://github.com/vanilla/vanilla/pull/8818
https://github.com/vanilla/vanilla/pull/8817
