### ISSUE TITLE
Failed to embed Google Docs or Craigslist content

### ISSUE THREAD

**Issue by ligyxy** [vanilla/vanilla#8753]
**Describe the bug**
In Rich editor, I can see embed content through a craigslist link
<img width="543" alt="Screen Shot 2019-04-30 at 4 45 53 PM" src="https://user-images.githubusercontent.com/2060045/56992195-85141480-6b67-11e9-81e6-b53f81adfa3f.png">
However, after submitting the post, the content is gone in the post.
<img width="275" alt="Screen Shot 2019-04-30 at 4 47 25 PM" src="https://user-images.githubusercontent.com/2060045/56992258-a7a62d80-6b67-11e9-8b26-26f09c9dbf54.png">
By checking the HTML, there is nothing between "Before Embed" and "After Ember".

Other links, like Youtube, still work though.

From what I remember, embed Craigslist content worked in previous 2.8.* version.

**To Reproduce**
1. Start a new post
2. Paste a Craigslist URL
3. Type enter, it should generate embed content
4. Submit the post, can't see the generated embed content

**Comment by ligyxy** [comment]
After testing, it looks like this error also happens with google docs link.

**Comment by charrondev** [comment]
I've seen something like this before. It could be a multitude of things. There are actually a few things happening incorrectly here though.

- We should be getting a proper response when scraping those sites.
- If we don't get a proper response we should be displaying an error message. It looks like the error message isn't showing up.

**Comment by charrondev** [comment]
Seems to be working fine after the embed system refactoring.

![image](https://user-images.githubusercontent.com/1770056/62380848-2076a600-b518-11e9-94a0-dd4b33c890bc.png)

This should be going out in 3.2
