### ISSUE TITLE
Add NavigationModel

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#8758]
A data model is required for managing navigation data for the site. This model will need to handle setting and getting records with at least the following fields:

1. `name` - The name of the link, passed through translation.
1. `url` - The link's route, passed through url() or something like that.
1. `key` - An optional unique key used to identify the link.

### Requirements
1. The data source can either be a database table or the site config (not both). It will be up to the developer implementing this feature the determine their preferred data source.
1. The data produced by this model will be utilized by API v2 endpoints which will be responsible for returning an array of navigation items.
1. Needs to be capable of polling addons for a "default" navigation structure.
1. Addons that are disabled should have their navigation disabled or removed.

See [Navigation API](https://github.com/vanilla/roadmap/blob/master/theming/config-navigation.md) for current data requirements.

**Comment by charrondev** [comment]
Closing in favour of https://github.com/vanilla/vanilla/issues/10019
