### ISSUE TITLE
translations.js failed (2: No such file or directory)

### ISSUE THREAD

**Issue by xaozai** [vanilla/vanilla#8774]
**Describe the bug**
The following errors are constantly appearing in /var/log/nginx/error.log:
2019/05/08 12:48:14 [error] 439#439: *1899 open() "/home/pi/forum/api/v2/locales/ru/translations.js" failed (2: No such file or directory),

However, the forum works and does not give any errors in the web browser.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
I'm not sure. How to find out what the problem is? The plugins that I use: Advanced Editor, All Viewed, Markups, Quotes, Rich Editor, The Contents Of The Stub, The Syntax Prettifier.
I use one application: Conversations.
And I use A Dark style of Keystone theme.

2. Did you follow our generic troubleshooting steps already?
No. I assume that the value of the localeKey variable in the source code is incorrectly assigned.

3. What Vanilla version are you using?
2.8.1

4. When did the issue start?
I assume that the problem appeared after localization was installed.

**To Reproduce**
1. Install the Russian localization.
2. Work with the forum.
3. Check the web server error log.

**Expected behavior**
I think there should be no errors related to the web application in the error.log.

**Comment by charrondev** [comment]
This is certainly a result of your nginx configuration. Would you mind sharing your `server` block for your vanilla setup?

That `.js` file is actually dynamically generated and returned by PHP-FPM. It's not a static file living on the disk. As a result nginx should _try_ the file, then fall back to PHP-FPM if it's not there.

**Comment by xaozai** [comment]
Here's my server block.

```
server {

	listen ip:81;
	
	server_name forum.local "";
	
	root /home/pi/forum;

	index index.php;

	location ~* \.(jpg|jpeg|gif|css|png|js|ico)$ {
		access_log off;
		expires max;
	}

	location / {
		try_files $uri $uri/ =404;
	}
			
	location ~ \.php$ {
		fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
		include snippets/fastcgi-php.conf;
	}
	
	## Begin - Security
	location ~* /(.git|cache|bin|logs|backups|tests)/.*$ { return 403; }
	location ~* /(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
	location ~* /user/.*\.(txt|md|yaml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
	location ~ /(LICENSE.txt|composer.lock|composer.json|nginx.conf|web.config|htaccess.txt|\.htaccess) { return 403; }
	## End - Security
}
```
Please tell me what the problem is. There is a mistake here?

**Comment by charrondev** [comment]
You're missing a fallback from your asset block. Take a look at this example from my localhost (similar to what I run in production).

You need something similar to `try_files $uri @vanilla;`. 

```conf
server {

    server_name dev.vanilla.localhost;
    listen 80 default_server;

    listen 443 default_server ssl;
    ssl_certificate      /certificates/vanilla.localhost.crt;
    ssl_certificate_key  /certificates/vanilla.localhost.key;

    root /srv/vanilla-repositories/vanilla;
    index index.php;

    # Hardening
    location ~* "/\.git" { deny all; return 403; }
    location ~* "^/build/" { deny all; return 403; }
    location ~* "^/cache/" { deny all; return 403; }
    location ~* "^/cgi-bin/" { deny all; return 403; }
    location ~* "^/uploads/import/" { deny all; return 403; }
    location ~* "^/conf/" { deny all; return 403; }
    location ~* "^/tests/" { deny all; return 403; }
    location ~* "^/vendor/" { deny all; return 403; }

    location ^~ "/favicon.ico" { access_log off; log_not_found off; return 404; }

    # /index.php handler
    location ~* "^/index\.php(/|$)" {
        # send to fastcgi
        include fastcgi.conf;

        # Needed by Vanilla
        fastcgi_param X_REWRITE 1;

        fastcgi_pass php-fpm;
    }

    # If it is a php script disallow its execution by redirecting the call it to /index.php
    # location ~* "\.php(/|$)" {
    #    rewrite ^ /index.php$uri last;
    # }

    location ~* "\.php(/|$)" {
        # send to fastcgi
        include fastcgi.conf;
        fastcgi_pass php-fpm;
    }

    # Set expires headers on various assets
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|eot|svg|ttf|woff|pdf)$ {
        access_log off;
        expires max;
        try_files $uri @vanilla;
    }

    # Default location handling
    location / {
        try_files $uri @vanilla;
    }

    location @vanilla {
        fastcgi_param X_VANILLA 1;
        rewrite ^ /index.php$uri last;
    }
}
```

**Comment by xaozai** [comment]
@charrondev, hank you! It seems that changing the configuration file solved the problem. Now the logs is clean.
