### ISSUE TITLE
Add core docker images into the repo

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8791]
We currently have our https://github.com/vanilla/vanilla-docker setup but we are looking to bring a better organized, alpine based docker setup into core.

These should probably live in a subfolder of `bin` where the rest of the script for setup will live.

Ideally these should cherry-pick from @initvector's personal configuration and our vanilla-docker one.

We don't need all of the containers from there though. We need

- Nginx
- PHP-FPM
- Sphinx
- Memcached
- MySQL/percona

This means we will be dropping from this initial version Apache and the other MySQL engines.

## Other changes

The current vanilla-docker has a ton nested directories. I'd like us to flatten this out considerably. In our repo configuration files should live next their containers and mapped to an appropriate directory in the repo. I don't want to see a single `/etc`, `/opt`, `/usr`, `/local` directory in the source, regardless of where they map to in the container.

No support for custom nginx/PHP-FPM configurations are required here.

**Comment by tburry** [comment]
I'm going to veto this. I don't want to see a docker setup inside our core source code repo.

**Comment by charrondev** [comment]
Vetoed by @tburry
