### ISSUE TITLE
Lists break further input 

### ISSUE THREAD

**Issue by Krisstoffer** [vanilla/vanilla#8834]
This one has been hard to replicate but it's somewhat annoying and I'll do my best to explain it - in a nutshell when you paste in some content, then using the buttons on the right outside of the text area to turn it into a bulleted list (could also be a thing with numbered haven't checked) it will then sometimes (nearly always) simply not allow any additional content it just seems to blank it out it's very odd.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? fairly cetain
2. Did you follow our generic troubleshooting steps already? yup
3. What Vanilla version are you using? 3.0 RC
4. When did the issue start? day zero

**To Reproduce**
1. create post
2. paste/post content
3. turn it into a bullet list
4. attempt to add further content

**Expected behavior**
I can add additional content without the requirement to post then edit to add further changes I wouldn't previously 

**Screenshots**
N/A

**Additional context**
nup

**Comment by charrondev** [comment]
I'll be trying to reproduce this today along. I'm planning to tackle some other list issues that were introduced when we added nested lists and this seems like one of them.

**Comment by alex-mtl** [comment]
@Krisstoffer If you can attach somehow the original text/html/content you are trying to paste it would help a lot.

**Comment by Krisstoffer** [comment]
Due to need to publish I have sadly just persisted with publishing and carried on, however, the next occurrence I will certainly pass the information on - my apologies I understand it's very difficult to resolve an issue when not all relevant information is provided.

I shall be doing some writing in the morning (10 hours from the time of posting) if I encounter the issue I will provide as much information as I can.

**Comment by Krisstoffer** [comment]
IT took some time before I found something that glitched it out so here are the steps I took.
1. the article in question is here: https://www.gog.com/game/swine_hd_remaster
1a. the specific list in question was copied from features down (screenshot of what i copied below)

![Screen Shot 2019-05-23 at 19 55 03](https://user-images.githubusercontent.com/700503/58250759-bbbf0280-7d94-11e9-8d6c-a1f2f93124ee.png)

I then proceeded to paste that content into my article which already contained above it some text by myself (written in the editor) and an embedded youtube video

After the paste I highlighted the list to ensure it was indeed a list and clicked the list option and selected bulleted - I cannot confirm if I have done this in every step I have received this issue but it's more than likely. 

After which I copied the original articles link (on GOG) and attempted to paste it in but in every case it just flicked and nothing is pasted in.

I was able to enter down a line then start typing random crap but then I went to delete it and the editor performed very oddly deleting the random text and pushing me into the list (hard to explain) 

I'm aware this is not a lot to go on and could be very specific to me issue but this is about as much information as I can provide - Once I save the article/post I can edit it and continue as normal.

**Comment by Krisstoffer** [comment]
I did take a look at GDN_Discussion -> body and exported what was in body into the attached file prior to me making my edits - unsure how useful it will be tho 

[pre-edit.txt](https://github.com/vanilla/vanilla/files/3212013/pre-edit.txt)

**Comment by alex-mtl** [comment]
Screenshot is not very helpful in this case.  I would prefer to have an initial document (html, docx, pdf) where that fragment was copied from.

**Comment by alex-mtl** [comment]
So far can not reproduce it on my localhost. 
Could you provide some extra info please?
What OS are you using? what Browser?

**Comment by Krisstoffer** [comment]
per my previous comment, Google Chrome (version info above) MacOS

**Comment by charrondev** [comment]
Darnit. We're also using Chrome and MacOS. The pre-edit body might be helpful. I'll give this a real shot at reproduction next week, but this is going to very difficult  to fix if we can't narrow it down.

**Comment by Krisstoffer** [comment]
I assume we are now at the point where this has not been replicated beyond anyone other than myself and as such should probably be closed pending feedback from future users who also happen to encounter this issue.

**Comment by charrondev** [comment]
I appreciate the sentiment. It's likely theres a bug here, but unless we can reproduce it reliably (and write a test for it) I don't think we'll be to resolve it.

If anyone is able to get it to happen again please comment give reproduction steps. We can re-open the issue and tackle it from there.
