### ISSUE TITLE
Google SSO button is looks weird on it's background

### ISSUE THREAD

**Issue by Krisstoffer** [vanilla/vanilla#8835]
The new Google Sign-in plugin does not appear in the header next to twitter and facebook (and it's icon is a little meh)

**User Story**

As a human with eyes I would like the button to join/have the option to join it's fellow buttons twitter and facebook and be less ugly. 

**Acceptance Criteria**

**Additional context**
Vanilla 3.x (RC) 

**Mockups**

**Related Issues**

**Comment by charrondev** [comment]
So looking at this you are essentially stating

- The Google sign-in button does not appear in the header like the other social sign-on buttons. (bug)
- The icon itself is kind of ugly?

As I understand this is the icon we use for the Google sign-in which looks pretty standard to me. Do you have any screenshots or examples to illustrate what you mean?

![icon](https://user-images.githubusercontent.com/1770056/58111071-c2941c80-7bbe-11e9-8cac-1c3202dffb26.png)

**Comment by Krisstoffer** [comment]
purely objective of course but the facebook and twitter icons blend into the background they are on, the google one doesn't - a personal opinion of course. 

![image](https://user-images.githubusercontent.com/700503/58114394-3c152480-7c2a-11e9-800f-ccd119b2cc86.png)

I'm not a designer but obviously, it cannot go on blue like the others due to the fork in the G being blue itself but something like:
![on-black](https://user-images.githubusercontent.com/700503/58114683-e12ffd00-7c2a-11e9-8d40-d7dc14342950.jpg)
![on-white](https://user-images.githubusercontent.com/700503/58114684-e12ffd00-7c2a-11e9-8d59-4ab1c501afe8.jpg)

seems cleaner than the odd blue box with a white box then the logo stuck in the middle

**Comment by charrondev** [comment]
I see what you mean. The icon should blend better with the background of the button. Thanks for the screenshots they're informative.

@ElisaAlmeida Is this something you could take a look at next sprint?

**Comment by ElisaAlmeida** [comment]
> I see what you mean. The icon should blend better with the background of the button. Thanks for the screenshots they're informative.
> 
> @ElisaAlmeida Is this something you could take a look at next sprint?

yes, sure. I can work on that.
