### ISSUE TITLE
Rich Post Rendering - Length validation is innacurate

### ISSUE THREAD

**Issue by Krisstoffer** [vanilla/vanilla#8836]
**Describe the bug**
So far as I can tell when inserting a link (embedded content) for example youtube, twitter, the additional content outside of "just" the link is counting towards the post count limit. I'm unsure if this is intentional or a bug but it does mean that text posts with basic images (inserted) seem to count far less than if I used an embedded media method (text + Flickr for example) 

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? yep
2. Did you follow our generic troubleshooting steps already? yep
3. What Vanilla version are you using? 3.0 RC
4. When did the issue start? day zero

**To Reproduce**
1. post an embed heavy post
2. count 
3. be confuzzled how your short post is over the limit

**Expected behavior**
links (embeds) count as 1 per link and not the entire embed code (total guess thats the cause btw) 

**Screenshots**
not really applicable 

**Additional context**
I like cake.

**Comment by charrondev** [comment]
This is definitely a valid bug. Just for reference which editor are you using?

**Comment by Krisstoffer** [comment]
Sorry, I should have included that information, both Desktop and Mobile have been left on the default Rich Editor.

**Comment by charrondev** [comment]
For some context around this, the rich format enables us to definitely be smarter about how we count post content in stuff like this, but we haven't fully integrated that into all of our existing systems. I've working over the past few months to make easier to re-use or override implementations in the formatting pipeline and this is one of the things along that I'd like to target.

**Comment by charrondev** [comment]
**Acceptance Criteria**

- A common method on `FormatInterface` is exposed to handle the changes maybe `textLength(string $body)`?
- This measures the plaintext length (roughly) of the post.
- We compare to this for most length validation.
- We still maintain a length validation message at the upper limit (eg. DB column size). We don't want posts silently truncating. For any posts less than the size of the `TEXT` column, we use a better length reason by working against plaintext, if it's over DB column limit we still have to check against the main content length.

**Comment by nervoustwit** [comment]
@charrondev, is there a reason why we don't use the renderPlainText() method to do this?

https://github.com/vanilla/vanilla/blame/master/library/core/functions.validation.php#L627

**Comment by charrondev** [comment]
@nervoustwit That would probably work out just fine. It's still recommend making a dedicated method on the format for it though. If you want to have it default to running the same way for everyone, you can take advantage of the inheritance, like I do with `renderExcerpt()`.

https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/BaseFormat.php#L24-L44

You'll then to need to add it to 

- [FormatInterface](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Contracts/Formatting/FormatInterface.php)
- [FormatService](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/FormatService.php)

This is opens things up for us to tweak it in the future.

**Comment by nervoustwit** [comment]
This https://github.com/vanilla/vanilla/pull/10095 closes this issue.
