### ISSUE TITLE
Boilerplate: AfterBody event has moved

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8856]
The [default.master.tpl in /applications/dashboard](https://github.com/vanilla/vanilla/blob/master/applications/dashboard/views/default.master.tpl#L37
) fires the AfterBody like that:

~~~
    {event name="AfterBody"}
</body>
</html>
~~~

This is a great place to add JavaScript files which shouldn't block anything or should be loaded after content is loaded without the need to add any listeners. The DebugBar plugin uses it for that.

If content should be displayed after the Footer, the AfterBody is the event to use.

In the [Boilerplate](https://github.com/vanilla/vanilla/blob/master/themes/theme-boilerplate/views/default.master.tpl#L81-L106) it has moved inside of the `<main>` tag, before panel and footer:

~~~
  {asset name="Content"}
  {event name="AfterBody"}
</main>
<aside class="Panel Panel-main">
  {asset name="Panel"}
 </aside>
 ...
<div class="Frame-footer">
  {include file="partials/footer.tpl"}
</div>
...
<div id="modals"></div>
</body>
</html>
~~~

I don't see any reason for this event being moved that much in the DOM tree. If something should be done at that place, the AfterRenderAsset event is already fired (and plugins like Pockets are already using AfterRenderAsset).

Because a) AfterBody is not needed directly below {asset...}, b) it is at the end of the DOM tree in all other themes and c) there is no alternative way to add something before the closing body tag, I think it is an error which needs to be fixed.

**Comment by charrondev** [comment]
@R-J I believe this was intentional. The language chooser from the multilingual plugin gets put in there, which is a pretty poor fit for that.

If you need you're code to run after the body has executed why not use wrap it in the following?

```
document.addEventListener("DOMContentLoaded", () => {
  // My code here.
});
```

Alternatively something like the debug bar plugin, could add an external script file with the `defer` attribute set.

**Comment by R-J** [comment]
I know this is not too relevant, but I honestly cannot understand why this has been done. If something should have been moved from the bottom of the DOM to another place, than the logical step would have been to use another event, not to move the event. Look at that code:

~~~
    public function base_afterRenderAsset_handler($sender, $args) {
        if ($args['AssetName'] !=='Content') {
            return;
        }
        echo '<!-- Hello from AfterRenderAsset -->';
    }
    public function base_afterBody_handler($sender, $args) {
        echo '<!-- Hello from AfterBody -->';
    }
~~~

The html result looks like that:
~~~
...
<!-- Hello from AfterRenderAsset -->
<!-- Hello from AfterBody -->
...
~~~

If there was a need for adding something to this place, than it could have been done without any problems. To me it seems as if somebody solved some "problem" by changing the structure instead of using what was already there.

Therefore moving the AfterBody event has been an error. All what was needed was using the existing AfterRenderAsset event.

**Comment by charrondev** [comment]
Huh, looking deeper this looks like it was just a simple mistake then. I was confusing in my head the AfterBody and Foot events.

**Comment by R-J** [comment]
Phew!
