### ISSUE TITLE
Attachment Upload Problem

### ISSUE THREAD

**Issue by mlohoar** [vanilla/vanilla#8858]
Attachment failed to add to comment with error message 'You are not allowed to upload files in this category'.

1. Enable permissions on attachments.
1. Activate Advanced Editor.
1. Click the add file - uploads OK.
1. Click to 'Post Comment'
1. Error message displayed

Seems to be class.editor.plugin.php line 998

**original:**
`&& $category['AllowFileUploads'] !==1`

**suggested:**
`&& $category['AllowFileUploads'] !=1`

on local IIS the value of $category['AllowFileUploads'] is 1, on Linux shared hosting $category['AllowFileUploads'] is "1"

**Comment by charrondev** [comment]
I would be more inclined to fix whatever is transforming the value than perform a loose equality check.

Could you describe the hosting environment where you're having issues in more detail?

- PHP version
- DB version

**Comment by mlohoar** [comment]
Local is Windows IIS  php 7.2.7  DB Maria DB 10.3.13
Shared is litespeed php 7.1 DB Maria 10.0.38

**Comment by charrondev** [comment]
Which one is the having the issue though? Local, shared, or both?

**Comment by mlohoar** [comment]
Sorry...
It was working locally  Windows IIS php 7.2.7 DB Maria DB 10.3.13,
But failed when I install on the share hosting:
litespeed php 7.1 DB Maria 10.0.38

**Comment by pinchies** [comment]
Whoops, didn't see this was still in discussion.
https://github.com/vanilla/vanilla/pull/8958

I'm on 
Vanilla version: 3.0.1
PHP version: 7.2.19
SQL Server version: 5.7.26
Server Software: LiteSpeed

cPanel Version | 80.0 (build 15)
-- | --
Apache Version | 2.4.39
Default PHP Version | 7.0.33
MySQL Version | 5.7.26
Architecture | x86_64
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 2.6.32-896.16.1.lve1.4.54.el6.x86_64
