### ISSUE TITLE
Connect Registration causes 404

### ISSUE THREAD

**Issue by Krisstoffer** [vanilla/vanilla#8874]
**Describe the bug**
Setting Registration to "Connect" works fine, however on the frontend when a user clicks the Registration button they are taken to "entry/register?Target=discussions" which presents a "Page not found" aka 404 - this does not seem like the correct behaviour

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
Sure

2. Did you follow our generic troubleshooting steps already?
Yeppers

3. What Vanilla version are you using?
3.0 RC1 

4. When did the issue start?
When I noticed it?

**To Reproduce**
1. go to the dashboard
2. into registration
3. set it to "connect"
4. watch recaptcha disappear (bye recaptcha!) 
5. open another browser (and/or Incognito mode) click register in front-end .. POW! 404

**Expected behavior**
Unsure, I guess I would expect to be presented with a modal box offering me the SSO options or directed to a page with similar results i.e give users a clue 

**Screenshots**
n/a

**Additional context**
Yeah, sign in works great! Make it work like that please :D

**Comment by charrondev** [comment]
Thanks for filing this issue. Do you know if this was happening before using the 3.0RC? In other words was this an issue using the Vanilla 2.8 release?

**Comment by Krisstoffer** [comment]
This is my first vanilla install, jump in the slightly less than deep end.

**Comment by charrondev** [comment]
Welcome to Vanilla then! I'm sorry to say though I'm a bit too busy to do a full reproduction around this in the next couple of weeks.

I know SSO configuration steps can be kind of hairy though, so I'd recommend trying over at https://open.vanillaforums.com/ in the meantime and see if you can rule out it being a configuration based error and we can go from there.

**Comment by Krisstoffer** [comment]
Thanks, I'm not too concerned about time frames etc as I have no plans to enable the option unless substantial growth occurs on my site - but that's another story. 

I have opened a post per suggestion will see where it leads: https://open.vanillaforums.com/discussion/37332/registration-connect-only-results-in-404#latest

**Comment by Krisstoffer** [comment]
This is still an issue in 3.1 - more info posted to the topic above to help clarify.
