### ISSUE TITLE
Rich Editor: pasting code blocks can result in display bugs

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#8906]
If you paste a code block after some normal text, the complete line gets formatted as code. If you undo that one or more words of the former written text will be rendered like the code block has been rendered. But that formatting is only displayed. When that text is posted, the text has no format.
While trying around formats have been different color or bold formatting:

Here are the steps to reproduce:
1. Write some lines and format the as code paragraph (must be code paragraph, not inline code) like that:
~~~
one two three
~~~
2. Mark the "two" and copy that.
3. Delete the complete block.
4. Start writing some words: "five four three"
5. Paste the paragraph formatted "two" from the clipboard.
6. This will render the complete line a code paragraph, not what I wanted, so use CTRL+Z to undo

You can also check this by copying some words of the code formatted paragraph in [this discussion](https://open.vanillaforums.com/discussion/37344/incorrect-datetime-value) and type some words in the comment field, paste and undo what you have pasted. You should see the effect immediately

![color bug](https://user-images.githubusercontent.com/3996187/58938269-c609d500-8774-11e9-805e-bb666e5ebdee.jpg)

![bold bug](https://user-images.githubusercontent.com/3996187/58938381-ff424500-8774-11e9-962a-f78253543b9c.jpg)

Both texts appear as not formatted when posted, but when editted the formatting appears again. You can check that [here](https://open.vanillaforums.com/discussion/37345/formfull#latest)

**Comment by andrewdodson** [comment]
Adding to this issue, if you take a code block and paste it as a point in an ordered list, it comes out as: 

![image](https://user-images.githubusercontent.com/19805402/61312981-839dd400-a7c7-11e9-8c6b-a679f336701b.png)

I'd expect it to format itself to be in-line with the restraints of the ordered list.

**Comment by charrondev** [comment]
@andrewdodson The feature request for nested codeblocks in lists is here. https://github.com/vanilla/vanilla/issues/9057 I don't see that happening for a long time though.

Could you file a separate bug for the paste issue? It's likely a different root case than the one in this issue.
