### ISSUE TITLE
Clean up the Spam Queue, Moderation Queue, and Changelog

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8907]
As our content has changed some bugs and UX issues have crept into our log system. We need to update these systems to fix these issues and to support some upcoming integrations.

## Spam & Moderation Queues

These two queues can still look the same and use the same view logic so the changes can be treated as one.

- The content column needs to be wider to make viewing the content easier.
- The content needs to be rendered in HTML so that image moderation and links can be observed to aid moderation. This will affect the expand/collapse logic. Note that these queues currently render the unformatted data so the new rich format looks a little more off in this context.

My suggestion is the following:

- Move the **Posted By** column into the content column, displaying it like the header in a post. Add the posted by's avatar.
- Move the **Date** and **Type** columns into the column as post meta. Use our `Gdn_Format::dateFull(..., 'html')` for the dates and show the proper timezone for the user. We can still show the full date, but don't need the timezone stuff.
- Move the **Flagged By** column to the end so that the content column is first.
- Just expand/collapse the post by height so that it can display as HTML. We can use a white gradient or something like that.

## Change Log

Fully fixing the change log is a little beyond the scope of this issue right now, but I think we can make some improvements.

- The change log should use more or less the same view logic it has right now. Most likely we should fork the view logic from that of the moderation queues to avoid too much branching in the view.
- The content needs to be rendered to plain text to show the diffs. This isn't optimal, but it's the best we can do right now.
- The **Flagged By** column is a bit confusing. If it relates to the update user then can we rename it to **Updated By**?
- The content column looks to be formatting properly, but we need to confirm.

**Comment by slafleche** [comment]
Are we planning on making a React view for this? Use the old system?

**Comment by charrondev** [comment]
Definitely a react view. My thought was to unify it w/ the content embeds for the most part. To make some new shared components that we mount in the quote embeds and here.

I'd like to use the same content component, expand collapse component, and user meta component between this and the quote embed.

**Comment by charrondev** [comment]
I had put this comment on the Zeplin view, but I'll repeat it here:

@ElisaAlmeida 

My understanding is that we're supposed to be rendering this with full (or limited) user content. How do embeds, images, file uploads, etc look in this? Do they get cut off or do we have to fit the whole thing in the pre-expanded section
