### ISSUE TITLE
Design moderation queue mockups

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8908]
Here is the current design of the moderation queue:

<img width="1350" alt="Moderation_Queue_—_T1" src="https://user-images.githubusercontent.com/97432/58974591-bbf5cf80-8790-11e9-9a2f-1bb3bebd686d.png">

I'm not looking to make drastic changes here, so the changes will involve moving things around a bit. The suggestions are on #8907, but we should meet to talk about them.

**Comment by ElisaAlmeida** [comment]
When we have a lot of text in the Content column, we'll have a button that expands. When the user clicks on the button, a pop up will show the content.

**Comment by ElisaAlmeida** [comment]
It's done. The link:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5d02b0a8f033df15f0d94b15
