### ISSUE TITLE
Create alternative designs for the comment, discussion, and article embeds

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8909]
Our existing comment embed looks like the following:

![image](https://user-images.githubusercontent.com/1770056/58988706-40a41600-87b0-11e9-9b48-8ad222cc1567.png)

This component never went through the design process and could probably be improved in the following ways:

1. Don't do expand/collapse. The UX is pretty terrible. Instead we should have some way of selecting the range of content to to show in the embed.
2. Adjust the user meta style to be a bit more standardised. I did a quick example of a comment embed.

![image](https://user-images.githubusercontent.com/1770056/58988954-d475e200-87b0-11e9-8cd6-6a1e961b74f5.png)

**Comment by ElisaAlmeida** [comment]
It's done. The mockup:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5cab9f90fcb28ca12e508444
