### ISSUE TITLE
Create URL generator interfaces and structure

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#8913]
## Technical Requirements

**ModelFactory**

- Can fetch models based on record type.

**Models**

- Take the rule generator and use that for generating URLs where possible.

**UrlGeneratorService**
- Some base class or interface `UrlGeneratorInterface`/`AbstractUrlGenerator`.
- 1 single url generator service.
- Addons can register a URL generator.
- Addons can override the URL generation callable in the container.

**RecordJoiner**

Implement to make fetching of collections of records that require more than just their recordID for the URL more efficient.

- Interface can be implemented by models.
- Specifies how to join records to a set of rows.
- Model factory also implements, and can use all models to expand particular `recordType` across multiple types.

## Issues in the past with URL generation

The incorrect URL could get put in the cache when domains change.

Possible solutions:

- Purge cache when custom domain changes.
- Only ever store partial URLs in cache.

**Comment by tburry** [comment]
Just keep in mind that this is in service of https://app.zenhub.com/workspace/o/vanilla/multisite/issues/206.
