### ISSUE TITLE
Rich Editor: When pasting an image it positions it above the text

### ISSUE THREAD

**Issue by jasonsavard** [vanilla/vanilla#8957]
Type a line in the comment field and hit enter then paste an image.
The image will be incorrectly placed above the text instead of below where the cursor is located.
This worked fine in v2.8.3

**Before pasting**

![image](https://user-images.githubusercontent.com/1268278/59553090-d7fe2b80-8f5d-11e9-9b21-4351b50097b0.png)

**After pasting image moves above text**

![image](https://user-images.githubusercontent.com/1268278/59553096-ef3d1900-8f5d-11e9-81b2-4acbfd1134a7.png)

Note: Interesting workaround if I hit the up then down arrow keys before pasting then the image is correctly positioned.

**Comment by charrondev** [comment]
It looks like the cursor position isn't being updated correctly when the enter key is pressed.

Thanks for the report. I'm off on vacation the next couple weeks, but I should be able to take a look after that. If you wanted to go digging yourself before then, the requisite handlers are `<EditorContent />`.

https://github.com/vanilla/vanilla/blob/60f2d99ebbce135e49b7787e98fa6589c1c3b8b8/plugins/rich-editor/src/scripts/editor/EditorContent.tsx

**Comment by jasonsavard** [comment]
The issue does not seem resolved in v3.0.2 which I downloaded here https://github.com/vanilla/vanilla/releases/download/Vanilla_3.0.2/vanilla-3.0.2.zip
and I cleared the cache.
