### ISSUE TITLE
Rich editor nested ordered lists should change their numbering systems.

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#8985]
Currently indented ordered lists always use the 1,2,3 numbering system regardless of nesting:

![Test_Moderations_Queue_—_T1.png](https://images.zenhubusercontent.com/57087d1abf93871ccd991f73/5fd0648c-3afc-4260-b1fc-7b8bdf653811)

I would like the nesting levels to look like this:

1. First level keep the same (1. 2. 3...)
2. Second level use a. b. c...
3. Thirst level use i. ii. iii.
4. Use 1. 2. 3. etc.
5. Use a. b. c...
6. Use i. ii. iii.
7+ Use 1. 2. 3.

----

Also, the regular list styles are broken

**Comment by charrondev** [comment]
This is purely a CSS thing. The user content styles define the styles they want for the pattern `ul ul li`, etc.

**Comment by tburry** [comment]
You need to check this against:

1. KB editior and article views.
2. Rick editor in the community.
