### ISSUE TITLE
Keystone: Dusk theme option does not have advanced search options

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#8987]
When using Keystone and the theme option 'Dusk' there is no chevron with advanced search options to expand after you have made a search. 

-Enable Keystone
-Enable theme option dusk (note that the hero image plugin was not being used in this case.
-make a search on the forum to get to search results page
-Observe that there is no chevron or option to expand your search should you want to filter down.

![Screen Shot 2019-06-21 at 12 53 24 PM](https://user-images.githubusercontent.com/24961134/59938858-332f9280-9424-11e9-9017-1cae833b37fe.png)

**Comment by Bparm** [comment]
@igraziatto

**Comment by charrondev** [comment]
@igraziatto Any chance you could get an estimate on this?

**Comment by igraziatto** [comment]
I'll take a look.
