### ISSUE TITLE
Rich Editor: When pasting an image it positions it above the text (reopened ticket)

### ISSUE THREAD

**Issue by jasonsavard** [vanilla/vanilla#8988]
(This bug was originally closed here #8957 but the issue was not resolved after I tested it on v3.0.2 that supposedly had the fix)

Type a line in the comment field and hit enter then paste an image.
The image will be incorrectly placed above the text instead of below where the cursor is located.
This worked fine in v2.8.3

**Before pasting**

![image](https://user-images.githubusercontent.com/1268278/60096905-36769700-9720-11e9-9e76-c3c1844c7eef.png)

**After pasting image moves above text**

![image](https://user-images.githubusercontent.com/1268278/60096916-3d9da500-9720-11e9-8425-b21397485463.png)

Note: Interesting workaround if I hit the up then down arrow keys before pasting then the image is correctly positioned.

**Comment by charrondev** [comment]
Hmm. I'll take a look. I might have messed up the backport to the 3.0 branch, because it is working properly on master. Thanks for the re-opening the ticket!

I've been on vacation for the last two weeks which is why I hadn't noticed.

**Comment by charrondev** [comment]
Instead of going for another attempt of backporting to 3.0, I've just done a [3.1 announcement and release](https://open.vanillaforums.com/discussion/37418/vanilla-3-1-is-now-available)

**Comment by jasonsavard** [comment]
Excellent it looks resolved in 3.1, thank you very much.
(merci, je suis de Montréal aussi)
