### ISSUE TITLE
CSS Bugs - Editor in Forum

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9000]
The close button needs a "appearance: none;" on it.

The spoiler has alignment issues. Probably inheriting styles it shouldn't on the forum side.

<img width="1072" alt="Screen Shot 2019-07-02 at 15 49 10" src="https://user-images.githubusercontent.com/19651440/60542100-1f681400-9ce1-11e9-9a48-f511b8496f9c.png">

**Comment by dannimajdalani** [comment]
W'ell be adding 
```
 .richEditor {
        .buttonClose {
            appearance: none;
            border: 0;
        }

        .spoiler {
            .iconButton {
                justify-content: center;
                display: flex;
            }

        }
```
to [_richEditorLegacy.scss#L161](https://github.com/vanilla/vanilla/blob/d9686a9c9781fbb364a6fb289c1b39176ad0272d/applications/dashboard/scss/compatibility/editor/_richEditorLegacy.scss#L161
)
