### ISSUE TITLE
Rich editor: shift+enter for line-break on desktop

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9032]
I would like the rich editor to support the insertion of linebreaks `<br/>` when the user presses `<Shift>+<Enter>`, similar to how many other WYSIWYG editors function. Currently the only way to break line is to start a new paragraph.

There are many legitimate uses for linebreaks, such as when presenting formatted text, like an address.

**Comment by charrondev** [comment]
Even though https://github.com/vanilla/vanilla/issues/9142 is newer, we'll be tracking this issue over there.

Closing as a duplicate of https://github.com/vanilla/vanilla/issues/9142
