### ISSUE TITLE
Rich editor: de-duplication of whitespace

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9033]
For example, if a user types a line, then hits enter several times, then types another line, their post will have a large chunk of whitespace in the middle.

There aren't really any legitimate use-cases for doing this (especially given that there is spoiler tag functionality).

I would like an option I can set to disable multiple empty elements, e.g. `<p></p><p></p><p></p><p></p><p></p>` will be rendered as `<p></p>`

**Comment by charrondev** [comment]
@jamesinc The team actually had a lot of discussion around this and ended up at a middle ground where we trim all trailing whitespace.

The question really comes down to whether or not we want the user to have full control of their posts or not, and in this we had decided on some middle ground.

Personally I'm of exactly the same opinion as you, _this extra whitespace looks stupid._

_**But,**_, as a team we came to the conclusion that due the the WYSIWYG nature of the editor, if the user put that whitespace there, _they must have wanted it._

**Comment by charrondev** [comment]
@tburry I'd just like to get your confirmation that I've got that correctly here.

**Comment by tburry** [comment]
We actually tried something like this way back when and a very vocal number of users through a fit over losing their whitespace. It's part of many forum cultures to use whitespace to separate a joke's setup from its punchline.

Looking at it another way: Eating whitespace that a user intends is unexpected behavior which will lead to increased support requests. We try to avoid such "magic" behavior.

**Comment by jamesinc** [comment]
That's fair enough, in my case I will probably upload a plugin to do some more aggressive whitespace pruning.

**Comment by R-J** [comment]
> Looking at it another way: Eating whitespace that a user intends is unexpected behavior which will lead to increased support requests. We try to avoid such "magic" behavior.

I would like to use this cite in order to strengthen the demand for being able to insert a normal line break. At least my personal expected behaviour when pressing the return-key is that a line break is inserted and not a new paragraph which adds some whitespace that I haven't "requested"

**Comment by charrondev** [comment]
@R-J That's easy enough to resolve with some styling changes.

I don't know if we have an issue open currently, but I would support shift+enter for a line break. To us the default should be Enter === New Paragraph.
