### ISSUE TITLE
Rich editor (on mobile) opportunistically converts things to embeds but is then unable to render them

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9041]
**Description**
The Rich editor, on mobile devices, will opportunistically convert a link to an embed when the user hits return to start a new line. However, if it's **not** one of the standard built-in embed types (YouTube, SoundCloud, etc), although it appears to render sensibly in the editor, it is not rendered when the comment is viewed.

**Vanilla info**
1. Vanilla 3.1
2. Tried with distributed 3.1 rich-editor plugin and also with a freshly-rolled build from master, which behaved the same way

**To Reproduce**
1. On mobile (or any platform where  hitting return causes the forum to attempt to convert a link to an embed), embed a non-standard link. News articles work well.
2. Verify the embed displays in your editor
3. Save the comment

**NB:** if you re-open the comment for editing, the embed is displayed properly in the editor

**Expected behavior**
1. Link is recognised/converted  into  an embed in editor, and subsequently displays properly when viewed
2. Links not recognised are not converted to embeds and displayed as plain links when viewed.

**Screenshots**
Paste link to something "embeddable":
<img width="362" alt="Screen Shot 2019-07-12 at 1 48 35 pm" src="https://user-images.githubusercontent.com/219819/61101135-1418a380-a4ac-11e9-9d37-ffb819c72515.png">

Link is turned into embed:
<img width="362" alt="Screen Shot 2019-07-12 at 1 48 46 pm" src="https://user-images.githubusercontent.com/219819/61101111-0105d380-a4ac-11e9-8281-5f344e24f3d6.png">

Nothing displays:
<img width="374" alt="Screen Shot 2019-07-12 at 1 49 19 pm" src="https://user-images.githubusercontent.com/219819/61101118-04995a80-a4ac-11e9-8c4c-55d7f98318d4.png">

**Comment by charrondev** [comment]
@jamesinc I'm unable to reproduce the issue you are showing on Vanilla 3.1. Do you maybe have a live link open anywhere that I could see this in action?

I am aware that `master` is currently broken, but that is because of the new embed system that is currently in preview. This new embed system is not part of 3.1.

https://open.vanillaforums.com/discussion/37419/new-embed-system-preview-information

The fix to the _new embed system_ is in this branch. https://github.com/vanilla/vanilla/pull/9042

**Example from my local build of 3.1**

![Jul-12-2019 11-06-51](https://user-images.githubusercontent.com/1770056/61138457-8a5ddb80-a495-11e9-97eb-fc1a727339c4.gif)

**Comment by jamesinc** [comment]
@charrondev in that case it's presumably something to do with my forum/addon config, I'll investigate further and isolate the cause and report back.

**Comment by jamesinc** [comment]
Okay, I found the root cause, in my installation the directory `./library/Vanilla/Formatting/Embeds/` was slightly wrong, it has `linkEmbed.twig` where it should have had `LinkEmbed.twig`. Replacing that and `LinkEmbed.php` solved the problem. I'm still not sure how rsync missed that, but a recursive diff of library against the 3.1 zip extract picked it up. 🤷‍♂

**Comment by charrondev** [comment]
I'll add a special release note around that just in case, although I think it's floated around since the last release.

I do remember some particularly sticky casing change done there at some point but it was a while ago.
