### ISSUE TITLE
Rich Editor - Unable To Put Images Into A List

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#9053]
When attempting to upload an image into an ordered/bulleted list, the image simply refuses to upload and it makes ordering an image in this particular way impossible.  It was possible to do this with Advanced Editor.  

**To Reproduce**
1. Start a discussion or comment
2. Start an ordered or bulleted list.
3. Put the cursor in the first item of the list
4. Click the 'Upload Image' button or drag/drop an image to the editor.  The image should appear where the cursor is (in the list)
5. The image will not upload.  

**Expected behavior**
The image should upload as expected and place itself into the list.  Pressing enter/return should continue the list (new bullet/next number).  

**Additional context**
This is an issue brought up by Lightspeed.

**Comment by charrondev** [comment]
Actually having images inside of lists would potential be possible but is a ton of work. Fixing the bug of the upload not working is much simpler.

@andrewdodson Could you split this into 2 issues?

1. The bug: Uploads while in a list fail.
2. The feature: Images nested inside of lists.

**Comment by andrewdodson** [comment]
@charrondev Sure thing.  They'll be up in a couple of minutes.

**Comment by charrondev** [comment]
Duplicate https://github.com/vanilla/vanilla/issues/9056
