### ISSUE TITLE
Rich Editor - Deleting A Single List Element Destroys Entire List's Formatting

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#9054]
**Describe the bug**
When creating a complicated list with multiple indents, accidentally hitting backspace at a bad time can delete a list element and have the effect of completely ruining the list.  

**To Reproduce**
1. Create a list with multiple indented levels
2. Go to the first point in the list, between the text you wrote and the number " 1. "
3. Hit backspace
4. Observe as entire list's formatting collapses.  

**Expected behavior**
A typing mistake of this nature shouldn't have the effect of ruining the entire list.  

**Screenshots**
Client submitted video of issue.  
[Vanilla_-OL_element_deletion_destroys_formatting.zip](https://github.com/vanilla/vanilla/files/3398264/Vanilla_-OL_element_deletion_destroys_formatting.zip)

**Additional context**
Issue submitted by Lightspeed.

**Comment by charrondev** [comment]
It will likely be some time before this is resolved.

Implementing these nested lists was quite complicated and this edge case was specifically held back during our implementation. We'd like to fix it, but it's a lot of work relative to the payoff and there are currently higher priority issues.

In the meantime they should be able to CMD+Z and get their list formatting back.
