### ISSUE TITLE
Rich Editor - Allow nesting things in lists

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#9055]
**Describe the bug**
When the user attempts to upload an image or file into a list, the upload fails.  

**To Reproduce**
1. Create a list
2. One one of the list's lines, attempt to upload and image or file
3. The item will not upload at all.  

**Expected behavior**
The image should be uploaded.

**Additional context**
Issue originally submitted by Lightspeed.

## Acceptance Criteria

- Images can be inserting in a list.
- List items can have multiple paragraphs in them (or paragraphs and embed).
- Shift Enter can be used to add another line to a list item.

**Comment by vrjrobitaille** [comment]
From the customer/product perspective. I should be able to create a list of instructions with supporting visuals.

<img width="349" alt="Screen Shot 2020-11-26 at 8 54 51 AM" src="https://user-images.githubusercontent.com/18470831/100359260-4c4b5400-2fc5-11eb-9499-b7888e5aef5b.png">
