### ISSUE TITLE
Rich Editor - Formatting Tool Does Not Appear If Highlighted Area Includes Line Break

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#9073]
**Describe the bug**
The formatting tool that pops up when highlighting text within the Rich Editor does not appear if there is a line break within the highlighted text.  

**To Reproduce**
1. Create a few lines of text within Rich Editor
2. Highlight the text, observe the formatting tool appears
3. Put a line break anywhere within the text
4. Highlight all the text again, observe that the formatting tool does not appear

**Expected behavior**
The formatting tool should appear whenever text is highlighted.  

**Screenshots**
*With No Line Break:*
![image](https://user-images.githubusercontent.com/19805402/61543937-67da3e00-aa12-11e9-8ca3-e315c74ecfda.png)

*With Line Break:*
![image](https://user-images.githubusercontent.com/19805402/61543988-7aed0e00-aa12-11e9-901b-dc40c882e20b.png)

**Additional context**
Issue submitted by Lightspeed.  This problem seems to be creating problems when they're copy/pasting code from other sources (and they want to put it into a code block).

**Comment by charrondev** [comment]
Code blocks are made with the menu on the left.

The inline menu intentionally does appear when crossing line breaks.

**Comment by tburry** [comment]
Adam is correct. This is a feature of the editor.
