### ISSUE TITLE
Story Book - Site nav

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9103]
Explain how Site nav and site node work (recursive)

**Comment by charrondev** [comment]
This is not done yet, but still should be.

**Comment by tburry** [comment]
I am closing items that are not PBIs and are unlikely to get done anytime soon. If you want this issue opened you can move it to your tasks board. Just keep in mind that adding an issue for everything you may want to do will add a tonne of noise to your board and render it difficult to manage.
