### ISSUE TITLE
If you go to the forum using IPv6 address, links to the discussion does not work, they look cropped.

### ISSUE THREAD

**Issue by xaozai** [vanilla/vanilla#9121]
If you go to the forum using IPv6 address, links to the discussion does not work, they look cropped.

**Comment by alex-mtl** [comment]
Any screenshots? any example of crapy links?

**Comment by xaozai** [comment]
For example, we have the forum address: [302:61d4:2d32:c2b9::2]:80
Links are as follows: http://[302:80/discussion/35/discusion-name-part#latest
In Firefox (Ctrl + Shift + I):
![firefox](https://user-images.githubusercontent.com/8542452/61956458-d0eb2400-afc5-11e9-8c79-7dc7778cb339.png)

**Comment by alex-mtl** [comment]
Ok. So you mean your HOST for forum is ipv6 address. I will check it.

**Comment by xaozai** [comment]
Initially, the forum was installed on IPv4 and worked on both IPv4-address and domain name. Later, IPv6 was added to the server configuration and there were problems with working with IPv6.

**Comment by alex-mtl** [comment]
I have patch in progress.  Please wait it dhould be released soon.

**Comment by xaozai** [comment]
I try to fix it myself.

In file `library/core/class.request.php` made changes after the line with the comment "The host can have the port passed in, remove it here if it exists":
```
          // The host can have the port passed in, remove it here if it exists
          // xaozai {
          //$hostParts = explode(':', $host, 2);
          //$host = $hostParts[0];
 
          //$rawPort = null;
          //if (count($hostParts) > 1) {
          //    $rawPort = $hostParts[1];
          //}
          $hostParts = explode(':', $host);
          $PartsCount = count($hostParts);
          $rawPort = null;
          if($PartsCount < 7) { //IPv4 or DN
                  $hostParts = explode(':', $host, 2);
                  $host = $hostParts[0];
                  if (count($hostParts) > 1) {
                          $rawPort = $hostParts[1];
                  }
          }
          else {
                  $pos_ = stripos($host, ']:');
                  if ($pos_ != false) { //IPv6 with port specified
                      $host = substr($host, 0, $pos_ + 1);
                      $rawPort = $hostParts[$PartsCount - 1];
                  }
          }
          // xaozai }
```
In file `applications/dashboard/controllers/class.setupcontroller.php` made changes before the line with the code "$Domain = Gdn::request()->domain();":
```
                  // le {
                 //$Host = array_shift(explode(':', Gdn::request()->requestHost()));
                 $Host = Gdn::request()->requestHost();
                 $hostParts = explode(':', $Host);
                 $PartsCount = count($hostParts);
                 if($PartsCount < 7) { //IPv4 or DN
                     $hostParts = explode(':', $Host, 2);
                     $Host = $hostParts[0];
                 }
                 else {
                         $pos_ = stripos($Host, ']:');
                     if ($pos_ != false) { //IPv6 with port specified
                         $Host = substr($Host, 0, $pos_ + 1);
                     }
                 }
                 // le }
                 $Domain = Gdn::request()->domain();
```

Now links are formed correctly.
But when I try to log into the forum by entering a username and password, the forum redirects me to the exit page. And if I close the logout page and request the home page again, I'll be logged into the forum.
Please tell me where and what needs to be corrected.

**Comment by alex-mtl** [comment]
@xaozai I'll create a PR (work-in-progress) just to share with you what I have and what is working fine to me. So you can use that code. Should be there today or tomorrow.

Sorry for the delay.

**Comment by xaozai** [comment]
@alex-mtl, thank you!
I use your code, links are now working, but I still have a problem with the redirect to the exit page when I log in to the forum. This only happens when using IPv6. When using IPv4, this does not happens. I'm confused...
And another question: is there a need to modify the file "`applications/dashboard/controllers/class.setupcontroller.php`" (see above)?

**Comment by alex-mtl** [comment]
@xaozai Could you record the process to make a gif? and/or track what is going on in browser: what are ajax calls? is it real http 301 redirection to logout? 

I have not that much time to play with it to replicate the issue. Nut I'll try till the end of the week.

By the way you can try to use another browser or reset your browser cache . Sometimes browser keeps some 301 redirection rules in the cache so even if page does not require 301 now but it had it before browser can behave based on previous page response.

**Comment by xaozai** [comment]
I get to the page "Leaving" with the address: http://[my:IPv6]:xx/home/leaving?Target=http://[my:IPv6]:xx/discussions
I already cleared my browser cache and cookies...

**Comment by alex-mtl** [comment]
So both links seem correctly formatted. What is the difference when you have `domain.com` or ipv4 address instead?

**Comment by xaozai** [comment]
After pressing the button to send login and password, the following occurs:
![01](https://user-images.githubusercontent.com/8542452/65055763-6e385800-d978-11e9-8f85-b49f8adfb671.png)

And the console displays a bunch of errors: Error while fetching an original source: request failed with status 404

![02](https://user-images.githubusercontent.com/8542452/65056115-fc144300-d978-11e9-9ecc-ea1f7609980b.png)

**Comment by alex-mtl** [comment]
There is something very unclear on your screenshots. 

On one hand you have your `200` responses when `POST` and `GET`.
On other hand you refer to console  warnings, which tell that there are some `404`s.
Please check which files (full path url) are failing with `404`?

**Comment by xaozai** [comment]
Yes, this is strange. And I do not understand what is happening. %(
When I go to the forum using IPv6, requests are made for files that really do not exist.
For example, the file "_utilities.scss" does not exist on the disk at all (it is in the screenshot). And this applies to all of these files.
When using IPv4, these errors do not occur.

**Comment by alex-mtl** [comment]
I think there are 2 independent bugs.

- 1st redirect through `home/leaving` page. Now I am able to reproduce it and I continue my research about it.

If you need it "done" in emergency/patch mode you can disable security feature:
**Warn users if a link in a post will cause them to leave the forum**
on this page `{host.com}/dashboard/settings/security`

- 2nd weird 404, I don't have it, but I suspect it relates to the build process and nginx/apache configuration you have. This 2nd one is kind unrelated to ipv6 changes I think.

**Comment by alex-mtl** [comment]
Do you need this ipv6 feature for production? or that is your dev environment?

**Comment by xaozai** [comment]
I have this option disabled.

![111](https://user-images.githubusercontent.com/8542452/65076077-e286f180-d9a0-11e9-9bd7-9fb30dc45f17.png)

The problem is still present.

Is it possible that all these problems are related to the theme used?
References to nonexistent files are in `themes/keystone/design/custom_default.css.map`.
I use Keystone Dark theme...

Forum is used in several overlay networks simultaneously. 
One of these networks currently uses IPv6 addressing. DNS is under development...
So I'm trying to make it work on this network.
Well, just in case the forum is "hanging" on a non-standard port 81.

**Comment by alex-mtl** [comment]
No. If you have that feature disabled, you should kind never have `home/leaving` page view.

I would suspect that you have different config files in your `config` folder for specific domains. And for this one (ipv6) you have that feature enabled somehow.

**Comment by xaozai** [comment]
No, I only have one configuration file (`config.php`) in the `conf` folder and it has the following values:
```
$Configuration['Garden']['Cookie']['Domain'] = '';
$Configuration['Garden']['Format']['WarnLeaving'] = false;
```

**Comment by xaozai** [comment]
@alex-mtl, could you please review this code in function "urlMatch" (`library/core/functions.general.php`):
```
...
         if (!empty($patternParts['host'])) {
             $p = $patternParts['host'];
             $host = $urlParts['host'];

             if (!fnmatch($p, $host)) {
                     if (substr($p, 0, 2) !== '*.' || !fnmatch(substr($p, 2), $host)) {
                       return false;
                 }
             }
         }
...
```
I think the problem with the leaving page lies here.
This function returns false and because of this, the "isTrustedDomain" function also returns false for IPv6.

**Comment by xaozai** [comment]
I've been experimenting...
Made these changes to the file `library/core/class.controller.php`:
```
     /**
      * Set the destination URL where the page will be redirected after an ajax request.
      *
      * @param string|null $destination Destination URL or path.
      *      Redirect to current URL if nothing or null is supplied.
      * @param bool $trustedOnly Non trusted destinations will be redirected to /home/leaving?Target=$destination
      */
     public function setRedirectTo($destination = null, $trustedOnly = true) {
         if ($destination === null) {
             $url = url('');
         } elseif ($trustedOnly) {
                 // xaozai {
                 //$url = safeURL($destination); //xaozai commented
                 $url = url($destination);// xaozai
                 // xaozai }
         } else {
             $url = url($destination);
         }

         $this->redirectTo = $url;
         $this->RedirectUrl = $url;
     }
 }

```
The problem with the redirect to `home/leaving` is gone.
