### ISSUE TITLE
Rich Editor: Link Rendering not working after update

### ISSUE THREAD

**Issue by Unkorneglosk** [vanilla/vanilla#9135]
On many forums we encounter after update to Vanilla 3.1
The HTML code generated from a Rich post is only: 
`<p><br></p>`
Where the link preview should be.

**Comment by charrondev** [comment]
You'll need to specify a bit more detail than that.

Generated from what input? What are the reproduction steps?

**Comment by Unkorneglosk** [comment]
It's happening for every link that must get the link preview.
The reproduction steps are simple: paste a link and hit enter. 
We tried with all plugins (except rich) disabled, clearing cache etc. Nothing works.
We did update from 2.8, without any problem except this rendering fail.

**Comment by charrondev** [comment]
Hmm. That's pretty unfortunate. With some testing on 3.1 and master I've found that I still can't reproduce this issue myself though.

We ran 3.1 on our infrastructure for a few weeks with no problems as well.

Do you have a live site (staging maybe?) that I could check and see if I can reproduce it? If so shoot a email to my the one listed on my github profile.

**Comment by Unkorneglosk** [comment]
After some investigation it was a mistake from my host during a server update. It was causing many problems all over their infrastructures and their clients websites. 
It happends at the same time I did update my partners forums at the same time, confusing me about problem source.

**Comment by charrondev** [comment]
Thanks for coming back and updating the issue. I'm glad you got the issues with you hosting provider worked out.
