### ISSUE TITLE
Inconsistency in Vanilla's website

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#9137]
Hello Isis, 

I saw some inconsistency in our website and I think it's important to fix. 
- Icon color x Text color:
as you can see in the screenshot below, the icon color doesn't match the text color, it has to be the same as other icons... 
![Screen Shot 2019-07-22 at 11.48.57 AM.png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/3788a752-ef5c-4432-8b4f-f5199fb270dd)
Please change the text color = icon color.
- Alignment
I saw different alignments between icon and text. See the screenshot below:
Centered:
![Screen Shot 2019-07-29 at 5.00.09 PM.png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/ad1dfc0a-6a2e-442c-ace6-8d6265b0a8e6)
Align to the left:
![Screen Shot 2019-07-29 at 5.00.59 PM.png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/18791b20-4a53-45a8-9793-020cb031eaaa) 
The left alignment is in KB Page, Forum, Q&A. I think it should be center aligned.

If you have questions, please let me know.

**Comment by irina-vanillaforums** [comment]
PR with @slafleche

**Comment by irina-vanillaforums** [comment]
It's on prod https://vanillaforums.com
