### ISSUE TITLE
Rich Editor - @Mentions Cause Editor To Fail in IE11

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9141]
When attempting an @mention in the Rich Editor while using Internet Explorer, the editor will suffer several identical 'object errors' and then the comment text field will collapse.  

This behavior does not occur with the Advanced Editor. 

Screenshots below:

Console errors
![image](https://user-images.githubusercontent.com/19805402/52876399-207b1900-3125-11e9-9be4-723db8ae5b00.png)

Expanded
![image 1](https://user-images.githubusercontent.com/19805402/52876408-23760980-3125-11e9-9454-1f17eb678a39.png)

Collapsed text field.
![image](https://user-images.githubusercontent.com/19805402/52876438-34267f80-3125-11e9-9667-0d08d4293726.png)

**Comment by tburry** [comment]
Closes https://github.com/vanilla/support/issues/211.

**Comment by charrondev** [comment]
We'll need a polyfill for `String.prototype.normalize`
