### ISSUE TITLE
Update reports successful when errors encountered

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#9144]
*Note: My PR is for a bug fix, but should also close this issue. I sort of hijacked this issue in order to get my PR reviewed.*

If errors are encountered during a utility-update, the site still reports a "successfully updated" response, unless debug mode is enabled. This appears to be due to [`UpdateModel::runStructure`](https://github.com/vanilla/vanilla/blob/16f43e0e179d22b6c5a804b419cdda8b61e0a63a/applications/dashboard/models/class.updatemodel.php#L660) catching all exceptions from addon structure methods and only re-throwing them if the site's debug mode is enabled. This is problematic, because beyond simply hiding specifics of the errors, the response indicates everything was successful.

**Comment by tburry** [comment]
Note the comment [here](https://app.zenhub.com/workspaces/vanilla-rd-roadmap-556cc3adbfcecd111b957933/issues/vanilla/internal/1932#issuecomment-517729499). If we do the work to secure the endpoint then I think it's okay to start surfacing more errors.
