### ISSUE TITLE
Don't Show Unrelated Videos At The End Of Youtube Embeds

### ISSUE THREAD

**Issue by andrewdodson** [vanilla/vanilla#9175]
**Describe the Feature**

In the past, there was a toggle when sharing Youtube videos that would block the related videos from showing up at the end of the video.  Recently, Youtube did away with this feature.  

A workaround exists where you're able to add ?rel=0 at the end of the embed url, and it only shows other videos in that video's channel (this use to completely block related videos, but now it has this function). 

Example: 
https://www.youtube.com/embed/APwwGy4GzK8  <-- This embed will share videos from all over Youtube. 

https://www.youtube.com/embed/APwwGy4GzK8?rel=0 <-- this embed will only share videos in the channel's selection  

(This does not work with normal Youtube URLs - just the ones you pull when using their embed tool)  

Currently, when trying to embed the above URLs (any of them) with either the embed tool or using smart embed, it results in a 422 error. 

![image](https://user-images.githubusercontent.com/19805402/62875610-51619280-bcf1-11e9-8e9e-36873f125cb3.png)

Essentially, we're looking for a way to embed videos and keep users focused on the client's product/channel.  

**User Story**

Experian is requesting this.  They want to be able to show their own videos and, when they finish, keep users focused on their product/the community rather than accidentally showing them an off-topic video that might drive them from the site.  

**Acceptance Criteria**

- Ability to embed a video and, at the end, for it to show only videos in the user's channel.

**Comment by charrondev** [comment]
This is the relevant piece of code that would need updating:

https://github.com/vanilla/vanilla/blob/3cf9c9e91e2f5d2f73bc55c60e7e57ffa93627ef/library/Vanilla/EmbeddedContent/Factories/YouTubeEmbedFactory.php#L49-L55

I think our new youtube embed might be missing some URL support that the old one had as well. That should be looked into and test cases should be added for all of these formats.

```php
// http://www.youtube.com/playlist?list=PL4CFF79651DB8159B
// https://www.youtube.com/playlist?list=PL4CFF79651DB8159B
// https://www.youtube.com/watch?v=sjm_gBpJ63k&list=PL4CFF79651DB8159B&index=1
// http://youtu.be/sjm_gBpJ63k
// https://www.youtube.com/watch?v=sjm_gBpJ63k
// http://youtu.be/GUbyhoU81sQ?t=1m8s
// https://m.youtube.com/watch?v=iAEKPcz9www
// https://youtube.com/watch?v=iAEKPcz9www
// https://www.youtube.com/watch?v=p5kcBxL7-qI
// https://www.youtube.com/watch?v=bG6b3V2MNxQ#t=33
```

In addition to those, the `youtube.com/embed/APwwGy4GzK8?rel=0` format should be added.

**Comment by tburry** [comment]
This issue appears to be stale. However, the youtube link doesn't even embed at all anymore. It just goes in as a link.

**Comment by charrondev** [comment]
@tburry We don't embed all of the URL formats listed there (included the one in the original post).

A url that already has `/embed` doesn't match our matcher. That's what the issue is for.

**Comment by tburry** [comment]
Okay I see the issue. The embed adds the `showRelated: false` to the data, but it is not obeyed when the video is rendered.

**Comment by charrondev** [comment]
Do we want to handle all of the other URL types? The showRelated fix is simple.

**Comment by tburry** [comment]
It looks like the embed URL is transformed from the iframe. I'm not sure if we need to handle that one unless it's something users are likely to insert by accident.
