### ISSUE TITLE
Draft button does not block saving empty draft with rich editor

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9198]
This is a bug in discussion.js, here: https://github.com/vanilla/vanilla/blob/master/applications/vanilla/js/discussion.js#L49

Save draft is using an empty-string test to decide whether or not something is draft-savable, however when rich editor is used, you never have an empty string, your empty string equivalent is `[{\"insert\":\"\\n\"}]`. So, clicking save draft will always save a draft (even empty). Additionally, if you have auto-save enabled, it will auto-save empty drafts, though this only seems to be triggered once you have interacted with the comment form, but even after you submit a comment to a discussion, you will end up with a new draft of an empty comment afterwards.

**To reproduce**
1. Go to a discussion
2. Click 'Save draft' on an empty comment
3. Check your drafts page

Anecdote: I patched this on my own forum thusly, however a proper fix should probably check for the presence of rich editor.

```
            if (jQuery.trim($(textbox).val()) == ''
                    || jQuery.trim($(textbox).val()) == '[{\"insert\":\"\\n\"}]')
                return false;
```

**Comment by charrondev** [comment]
We had handled this over at `autosave.js` previously, so the autosave drafts are working properly.

https://github.com/vanilla/vanilla/commit/1f5132ccbc44b25d34be42942ad722557a207eb7

We can implement something like that here.

**Comment by jamesinc** [comment]
@charrondev examining autosave.js, it looks like that is also part of this bug. The comment input textarea contains rich editor markup strings, **including** escape characters, and autosave.js is attempting to match unescaped strings.

* This (what I wrote above) works: `'[{\"insert\":\"\\n\"}]'`
* This (from autosave.js) does not match an empty textarea: `'[{"insert":"\n"}]'`
