### ISSUE TITLE
Rich Editor speed issues under certain circumstances

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#9211]
I browse the OS forum with Firefox on Windows. The problem appears on two different maschines: when writing longer comments, especially if there are code blocks in the comment, the editor slows down more and more. I have experienced this only two days ago when writing that comment: https://open.vanillaforums.com/discussion/comment/257939/#Comment_257939

**Comment by charrondev** [comment]
I will note our current syntax highlighting implementation is incredibly inefficient. Grossly inefficient even. It could definitely use some optimization.

Does this happen to you even without the code blocks, or is it fine otherwise?
