### ISSUE TITLE
@mentions cause rich editor to fail in all browsers

### ISSUE THREAD

**Issue by jamesinc** [vanilla/vanilla#9231]
_Foreword: there is a similar bug reported in #9141, however that one looks to have a different root cause._

I've been seeing the same issue in Firefox and Chrome, and had users reporting it also.

When selecting a username for a `@mention` (whether by mouse click or keyboard), the comment field collapses and is deleted from the DOM. Just like the behavior reported in #9141

This does not always happen immediately, in Firefox it usually happens on the second mention, and in Chrome it took three or four mentions to trigger it.

The consoles of both browsers report the same React error:

```
Invariant Violation: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
    o vendors.min.js:33
    o vendors.min.js:33
    Zo vendors.min.js:33
    enqueueSetState vendors.min.js:33
    setState vendors.min.js:25
    value async~mountEditor.min.js:128
    Ho vendors.min.js:33
    qo vendors.min.js:33
    xs vendors.min.js:33
    unstable_runWithPriority vendors.min.js:42
    xs vendors.min.js:33
    Ds vendors.min.js:33
    Is vendors.min.js:33
    Cs vendors.min.js:33
    Zo vendors.min.js:33
    enqueueSetState vendors.min.js:33
    setState vendors.min.js:25
    value async~mountEditor.min.js:128
    value async~mountEditor.min.js:128
    t async~mountEditor.min.js:128
vendors.min.js:33
    uo vendors.min.js:33
    callback vendors.min.js:33
    ro vendors.min.js:33
    no vendors.min.js:33
    Ho vendors.min.js:33
    qo vendors.min.js:33
    xs vendors.min.js:33
    unstable_runWithPriority vendors.min.js:42
    xs vendors.min.js:33
    Ds vendors.min.js:33
    Is vendors.min.js:33
    Cs vendors.min.js:33
    Zo vendors.min.js:33
    enqueueSetState vendors.min.js:33
    setState vendors.min.js:25
    value async~mountEditor.min.js:128
    value async~mountEditor.min.js:128
    t async~mountEditor.min.js:128
```

React error #&#x2060;185 is:

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Steps to reproduce**

1. Open a conversation or discussion comment box
2. `@mention` a user
3. `@mention` additional users until the box collapses.

**Comment by charrondev** [comment]
@jamesinc I think this may be fixed in vanilla 3.2. Are you able to reproduce it with that version or on `https://open.vanillaforums.com`?

**Comment by jamesinc** [comment]
@charrondev I'll upgrade my forum to 3.2 and report back

**Comment by jamesinc** [comment]
@charrondev yup all good in 3.2 thanks
