### ISSUE TITLE
Missing HTML encoding in MeBox Inbox

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#9241]
This issue has been observed on the current open.vanillaforums.com installation. I've received a message with an ampersand in it and this is how it looks like:
![encoding](https://user-images.githubusercontent.com/3996187/64079257-c4a16780-cce5-11e9-8c3c-0c56365674c0.jpg)

To recreate simply write a message with a "&" in it to yourself and look in the MeBox drop down

**Comment by charrondev** [comment]
PR out now: https://github.com/vanilla/vanilla/pull/9243

If you notice any more of these please report them and we'll fix them quickly. Some recent changes in the formatting pipeline for security purposes might mean we are double escaping things in certain places. They are easy to fix when noticed, but need to be individually verified so we don't accidentally introduce XSS.

I wish more of these views were using twig or react which are automatically escaped. I may do a couple PRs to start converting these views.
