### ISSUE TITLE
`Splash` component has a diff in chromatic on every pull request

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9248]
**Describe the bug**
We have a false positive change being detected because of the randomized IDs in chromatic.

**To Reproduce**

Visit https://www.chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5d6fcf3ca0c1890020e31f5c

**Expected behavior**
IDs are consistent between renders

**Comment by slafleche** [comment]
I've also noticed it happens fairly frequently that one page will have element a few pixels lower. When running the tests again, it fixes the issue. My guess here is the page doesn't have time to fully render before the screen shot happens. Is there some sort of setting we can tweak to change how long Chromatic waits before checking?
