### ISSUE TITLE
Invite target missing a placeholder & description.

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9273]
**Describe the bug**
The invite target feature is confusing/doesn't make sense.

**To Reproduce**
1. Go the the registration settings.
2. Change method to invite.
3. See field "invite target" with no information.

**Expected behavior**
The field should have a description and placeholder.

**Screenshots**
![image](https://user-images.githubusercontent.com/1770056/64558415-cc7a9080-d311-11e9-94bc-b3cdd4814a58.png)

**Additional context**

The following feedback was given during the review process of https://github.com/vanilla/vanilla/pull/8950, but no actions were taken on it.

> - Should it be a full URL? Does it work with one? (spoiler, it didn't)
> - Relative to the root of the site?
> - How does it work if the site is served in a subfolder (like hub/node)? It it the full path or everything after the folder?
> 
> A description & placeholder value would help make this clearer. Please run the final description text by @tburry and be sure to add it in the dashboard file in the locales repo.

**Comment by tburry** [comment]
This should work with a full URL, but will not work if the URL is a non-trusted domain.

**Comment by tburry** [comment]
**Placeholder:** https://
**Description:** Users will be redirected to this URL after accepting an invitation. It can be a full URL or a path to redirect within the site.

**Comment by tburry** [comment]
After you get the description in can you call me over? I just want to see the visuals.
