### ISSUE TITLE
Implement new theme system variables in keystone theme options

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9288]
**Describe the Feature**

Variables using our new theming system should be added for keystone theme options.

**Objectives**

- Theme variables should be configured for each theme option.
- The new subcommunity chooser & Rich Editor should have an appearance that "fits in" with the rest of the theme option. Common things to configure would be 
  - border style & radii
  - bg, fg, and primary colors.
  - button style.
  - titlebar/header style.

## Options

- [ ] Dark
- [ ] Dusk
- [ ] Cerulean
- [ ] Classic
- [ ] Coral

**Comment by alexbrohman** [comment]
@charrondev still committed to working on this but services pipeline is filling up so will revisit when possible.

**Comment by tburry** [comment]
I just want to see if this is still relevant.

**Comment by charrondev** [comment]
It's not.
