### ISSUE TITLE
User Interface - Translation Page

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#9322]
We need to create a page in the Dashboard where the user is able to see all the languages, do translations...
- Wireframes 
- User Interface

**Comment by ElisaAlmeida** [comment]
It's done. Let me know if it's correct or missing something:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d8a83623689f40274faa6f2
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d8a8363f97e0a1844a811ed
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d8a8364bf10816131940427

**Comment by tburry** [comment]
I've made a few comments in zeplin.

**Comment by ElisaAlmeida** [comment]
It's done:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d8a83623689f40274faa6f2
