### ISSUE TITLE
Rich format error with an embed after a list

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9324]
The following [article](https://success.vanillaforums.com/kb/articles/113-2019-013) has an HTML rendering bug when an embed is after a list. The embed is put inside the list rather than after it.

The following screenshot shows the HTML in question in the dev tools. Notice that the `</ul>` is after the embed `<div>`.

<img width="1498" alt="2019_013_-_Vanilla_Success" src="https://user-images.githubusercontent.com/97432/65270165-98a92300-dae8-11e9-9b89-2845fd585afe.png">

**Comment by charrondev** [comment]
Confirmed on my localhost, this is still a thing even after the latest list fixes. Here's the body content that reproduces:

```json
[
    { "insert": "List Item" },
    { "attributes": { "list": { "depth": 0, "type": "bullet" } }, "insert": "\n" },
    {
        "insert": {
            "embed-external": {
                "data": {
                    "url": "https://us.v-cdn.net/6030677/uploads/698/E2G3E1MAL7AD.png",
                    "name": "image.png",
                    "type": "image/png",
                    "size": 48779,
                    "width": 746,
                    "height": 682,
                    "embedType": "image"
                },
                "loaderData": { "type": "image" }
            }
        }
    }
]
```
