### ISSUE TITLE
DEBUG mode: Trying to create a new category fatals.

### ISSUE THREAD

**Issue by nervoustwit** [vanilla/vanilla#9334]
When creating a new category (with subcommunities turned on, maybe in all cases) you are sent to: `vanilla/settings/addcategory?parent=` which throws a fatal error:

```
Impossible to access an attribute ("CategoryID") on a null variable.
```

```
The error occurred on or near: /var/www/frontend-a2b55416aab93a/applications/vanilla/views/vanillasettings/editcategory.twig
62:     {{ form.imageUploadPreview(
63:         'Photo',
64:         t('Photo'),
65:         '',
66:         'vanilla/settings/deletecategoryphoto/' ~ category.CategoryID
67:     ) }}
68: 
69:     {#
70:         // Extended fields may be defined through some addon.
```

<img width="1174" alt="Screen Shot 2019-09-25 at 9 51 26 AM" src="https://user-images.githubusercontent.com/2651070/65608404-26b75a80-df7c-11e9-8de7-a906dc3e61a7.png">

**Comment by charrondev** [comment]
Just a note, this is only in debug mode, because our twig renderer is configured to raise errors like this after some recent changes.

**Comment by x00** [comment]
confirm

**Comment by the-REAL-beautysleep** [comment]
I'm was having this issue also.
I opened the **config.php** file in **conf** folder and changed $Configuration['Debug'] = true; to $Configuration['Debug'] = false; as @charrondev  pointed out.
My question is, is there a GUI way to do this?

**Comment by nervoustwit** [comment]
Hey @the-REAL-beautysleep I know this question has been here for a while. No their is no GUI for toggling Debug mode on and off. I think it's a conscious decision on the part of Vanilla because it is not recommended to leave a site in Debug mode for a long time we want to make it something you wouldn't do by accident. Debug mode can expose code paths to potential hackers.
