### ISSUE TITLE
Designs for responsive tooltip component

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9341]
Designs for responsive tooltip component. 

See https://github.com/vanilla/multisite/issues/275

**Comment by ElisaAlmeida** [comment]
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5d7bdef2c4c48b5f876e3e7b

On mobile, the tooltip won't appear.

**Comment by ElisaAlmeida** [comment]
For desktop we'll have the tooltip and the modal:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d976a7113d2f850b6a9e814
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b51adda150306980f6baf
For mobile will be just the modal:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b51ad15f0ba6b6ffed8c8
