### ISSUE TITLE
Design - Update Knowledge bases product info

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9343]
Knowledge Base Table w/ site sections

As a site owner, with site sections enabled, I should be able to clearly see which knowledge bases do not have a product assigned. Some warning icon should be displayed in the table.
When hovering the icon a tooltip containing information about the error should be displayed.
As a site owner I should be able to see all "Locations" that are available for a knowledge base.
One location should be available per-site section assigned to the knowledge base.
If no locations are accessible, "No Products" should be displayed.
As a site owner I should see some warning if the product assigned has no locations.

See https://github.com/vanilla/multisite/issues/275

**Comment by ElisaAlmeida** [comment]
Desktop:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b829c1133670881f97014
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b829c574d8d6b998178f4
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b829dbef5566bab4358ef
Mobile:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b829d574d8d6b9981794b
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b829dc8d95b6c42f135c8
