### ISSUE TITLE
Design - Update Subcommunities table for products

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9344]
Subcommunities Table

As a user, with site sections enabled, I should be able to clearly see which subcommunities do not have a product assigned. Some warning icon should be displayed in the table.
When hovering the icon a tooltip containing information about the error should be displayed.
The Product column should display "No Product" when the no products are assigned.

See https://github.com/vanilla/multisite/issues/275

**Comment by ElisaAlmeida** [comment]
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d65407546e50e9b42143151
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d976a7113d2f850b6a9e814

**Comment by ElisaAlmeida** [comment]
Desktop:
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d65407546e50e9b42143151
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d976a7113d2f850b6a9e814
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b51adda150306980f6baf
Mobile: (for mobile, we won't have the Tooltip, just the modal)
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b51adda150306980f6c02
https://app.zeplin.io/project/5d0cf4c83418a6702b634982/screen/5d9b51ad15f0ba6b6ffed8c8
