### ISSUE TITLE
UI for the New Theming System

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#9364]
User Interface for the New Theming System.

Create all the pages for the New Theming:
- Page on the Dashboard
- Style Guide Page
- Customization Page (HTML, CSS, JS pages)

**Comment by ElisaAlmeida** [comment]
I did some screens. The Dashboard:
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da08428c5f0e0261f44484e
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da09782ddcc77305268390a
The Tabs:
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da0cfb0d2d3af23439146eb
The HTML:
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da0f54c5b79ea308076141f
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da0f75f405c62237f2d8885
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/screen/5da0f5535a1f85260866f6dc

**Comment by charrondev** [comment]
Just a note: this project is not visible to me at least.

**Comment by ElisaAlmeida** [comment]
next Friday (Nov 8th) we'll present it to the team.

**Comment by ElisaAlmeida** [comment]
The project:
https://app.zeplin.io/project/5d8a5a6cacd3a86143741c38/dashboard
