### ISSUE TITLE
Don't cache 302 redirects

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9374]
I had an issue on my phone where I was clicking into a private community and would continuously get the sign in page even after I signed in. Here is what I think is happening:

1. Click a discussion link.
2. 302 to sign in page (response cached).
3. Sign in page (response cached).

We recently made changes to cache all of /entry and I think that this is one of the repercussions. What I would like to try is either:

1. Set response headers to not cache any 302 redirect.
2. If the above is felt to be too risky then just don't cache the private community redirects.

It's my hope that not caching the redirects will help. If it doesn't it is still a positive change in its own right.

**Comment by charrondev** [comment]
I had the same thing happen to me this morning.
