### ISSUE TITLE
Rich Editor - Images are displayed at 600px

### ISSUE THREAD

**Issue by FarhanVanilla** [vanilla/vanilla#9394]
**Describe the bug**
Images uploaded in a thread are displayed at 600px. 1024 by 1024 has been set as the image upload limit but images are displayed much smaller than that. Imagine it's being done through CSS. 

**Vanilla info**
1. Core issue while implementing the alt-text input for image embeds.

**To Reproduce**
1. Upload any image. Inspect the image size. 

**Expected behavior**
Images should display in the size being described by the images upload in posting.

**Screenshots**

**Additional context**

**Comment by FarhanVanilla** [comment]
https://vanillaforums.happyfox.com/staff/ticket/52384#237562

**Comment by charrondev** [comment]
Relates git issues from support repo:

- https://github.com/vanilla/support/issues/830
- [and this one](https://github.com/vanillaforums/golfwrx/issues/286)

**Comment by charrondev** [comment]
Fixed in 2019.018 https://success.vanillaforums.com/kb/articles/137-release-2019-018
