### ISSUE TITLE
Gdn_Request::url() is polluted by multisite

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9410]
- When there is a subcommunity path in the URL it is impossible to accurate generate a absolute URL (like a canonical) using this method.

Example.

- The site has a webroot `vanilla.localhost/dev`
- I am some model, and want to generate the canonical URL for some resource by it's site section.
- I create my resource path `/canonical-site-section/my-resource/52-slug-path-here`.
- I want to append this to the full web root.
- Attempt to use `Gdn_Request::url()`.

There are 2 different scenarios.

1. I have no site section in my current request path. **This works fine.** Url is `https://vanilla.localhost/dev/canonical-site-section/my-resource/52-slug-path-here`
2. I have a site section in my current request path. The user requested `vanilla.localhost/dev/non-canonical-site-section/my-resource/2-non-canonical`. **This Fails**. The generated URL will have both site sections. `vanilla.localhost/dev/non-canonical-site-section/canonical-site-section/my-resource/52-slug-path-here`

## What happened?

The subcommunities plugin polluted the request object by modifying the web root even though the webroot didn't really change. This makes the method innapropriate for making canonical URLs.

## Proposal

A new method.

**Comment by alex-mtl** [comment]
new method `getSimpleUrl` is implemented
