### ISSUE TITLE
Add Vidyard for Auto-Embed

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#9416]
Since we are already have Vimeo, Wistia, and others, can we consider Vidyard as an auto-embed 

https://knowledge.vidyard.com/hc/en-us/articles/360010001713

**Comment by slafleche** [comment]
@charrondev do you think this would be a good task for Neena? Adrian also mentionned tiktok

**Comment by vrjrobitaille** [comment]
We're definitely open to adding new smart-embeds and we do when time permits or professional services are scheduled. Currently Vidyard, Survey Monkey and Kaltura are the most requested types that we do not yet support, but demand has still be relatively low. If you or someone you speak with is in need of a specific embed type I ask you to send an email to Product so we can record those requests and plan accordingly. If it is a must have feature, submit a request with a CSM or file an estimate request, and we may be able to do something as a service if the requested type is not on our immediate roadmap. I will close this issue for now for the sake of our developers and our Github backlog, but know that we are aware and tracking the need within our Product Management software and we'll get these things into Github as soon as they are actionable.
