### ISSUE TITLE
rel="ugc instead of "no follow"

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#9428]
We should modify `"no follow"` with` rel="nofollow ugc"`

rel="ugc": UGC stands for User Generated Content, and the ugc attribute value is recommended for links within user generated content, such as comments and forum posts.

Details:
https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

**Modified OP for clarity as pointed out by RJ**

**Comment by slafleche** [comment]
@charrondev do you think this would be a good task for Neena?

**Comment by R-J** [comment]
You shouldn't replace it. You can use `rel="nofollow ugc"`. That shouldn't influence other search engines.

**Comment by charrondev** [comment]
@charrondev It might be a good introduction to the formatting pipeline. Again though this is exclusively a backend task so maybe something else would be a better fit for onboarding.

@R-J you are absolutely correct.

**Comment by adrianspeyer** [comment]
@R-J absolutely - I was writing the issue too quickly, but you are right.

**Comment by nervoustwit** [comment]
This was handled by this PR https://github.com/vanilla/vanilla/pull/9691
