### ISSUE TITLE
API V2: Get Social Groups comments by insertUserID does not return a result

### ISSUE THREAD

**Issue by dannimajdalani** [vanilla/vanilla#9457]
### Details

Getting a user's comments by running api/v2/comment?insertUserID=.. returns no result.
when the comment is from a Social Groups discussion.

**Comment by tburry** [comment]
Isn't this only the case for social groups comments?

**Comment by dannimajdalani** [comment]
> Isn't this only the case for social groups comments?

That's right. I edited the title/details of this ticket.

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #2044](https://github.com/vanilla/internal/issues/2044) via [**ZenHub**](https://www.zenhub.com/)
