### ISSUE TITLE
Implement Modular Homepage

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9491]
**Describe the Feature**

The homepage of the site should be configurable as a modular homepage, with re-organizable/configurable content. Addons should be able to provide modules for use.

**User Story**

As a site administrator I would like to be able to customize my homepage contents with multiple different types of content in the order of my choosing. Some example of content I may want to place here:

- A hero w/ a search bar
- A hero w/ a title.
- A featured content list.
- A list/carousel of content by users of a certain role.
- A list/carousel of recent or hot discussions.
- A leaderboard.
- A list of user's currently online.
- A list/carousel of recently updated articles.
- A grid of certain forum categories w/ icons & titles displaying.
- A grid of knowledge bases w/ icons & titles displaying.
- Site counts (user online, total discussions, total users)
- A custom pocket.

**Acceptance Criteria**

- Addons must be able to provide modules for configuration.
- Modules should be 100% independant & fetch their own data.
- This must not affect current site's homepage defaults.
- Site admins should be able to configure what content appears here. For a first iteration this may be configured through some JSON configuration, but a drag/drop UI would be ideal.
- Configuration should be able to be specified to a particular module.
- Modules should be able to take a full row.
- Certain modules should able to be configured to a smaller, half-width row. (and stacked with another module in the row).

**Mockups**

These aren't final mockups, but here's a few examples of common custom homepage elements.

|Name/Type|Image|
|---|---|
|Category Grid|![image](https://user-images.githubusercontent.com/1770056/67637479-778add80-f8b1-11e9-99fe-de3c7c1daff9.png)|
|Category Grid, leaderboards, hot discussions|![image](https://user-images.githubusercontent.com/1770056/67637495-9db07d80-f8b1-11e9-96af-4b81725b46cb.png)|
|Custom Pocket|![image](https://user-images.githubusercontent.com/1770056/67637501-abfe9980-f8b1-11e9-9bd9-2247c7e76077.png)|
|Site counts|![image](https://user-images.githubusercontent.com/1770056/67637509-b882f200-f8b1-11e9-86d2-609ef280f527.png)|
|Category Grid|![image](https://user-images.githubusercontent.com/1770056/67637526-cd5f8580-f8b1-11e9-927c-0a3dc885ef70.png)|
|Discussion List|![image](https://user-images.githubusercontent.com/1770056/67637535-dcdece80-f8b1-11e9-979d-5a74494965bc.png)|
|Online users|![image](https://user-images.githubusercontent.com/1770056/67637542-e49e7300-f8b1-11e9-93ef-44258970e6e7.png)|
|Custom Pockets|![image](https://user-images.githubusercontent.com/1770056/67637544-ecf6ae00-f8b1-11e9-998f-b8693b659abf.png)|
|Search Hero|![image](https://user-images.githubusercontent.com/1770056/67637550-fe3fba80-f8b1-11e9-9d8b-abaf2f965183.png)|
|Category Grid|![image](https://user-images.githubusercontent.com/1770056/67637553-0566c880-f8b2-11e9-93dc-f2e4331e35e8.png)|
|Kb Grid|![image](https://user-images.githubusercontent.com/1770056/67637573-23342d80-f8b2-11e9-9fde-a0b4eaa85d0b.png)|
|Popular/recent articles|![image](https://user-images.githubusercontent.com/1770056/67637599-65f60580-f8b2-11e9-84e1-7c2208811c10.png)|
|Featured Articles|![image](https://user-images.githubusercontent.com/1770056/67637601-7312f480-f8b2-11e9-869d-896f38d2edb5.png)|
|Online Variations|![image](https://user-images.githubusercontent.com/1770056/67637605-8625c480-f8b2-11e9-9a01-61f88812f83e.png)|

**Related Issues**

- https://github.com/vanilla/vanilla/issues/4908

**Comment by tburry** [comment]
Issue moved to [vanilla/internal #2281](https://github.com/vanilla/internal/issues/2281) via [**ZenHub**](https://www.zenhub.com/)
