### ISSUE TITLE
Error in LocalesApiController: Class 'Locale' not found

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#9499]
A fatal error is thrown in LocalesApiController:

```
Fatal Error in LocalesApiController.{closure}();
Class 'Locale' not found
The error occurred on or near: /var/www/vanilla/applications/dashboard/controllers/api/LocalesApiController.php

 99: 
100:         $populate = function (array &$row, array $locales) {
101:             $displayNames = [];
102:             foreach ($locales as $locale) {
103:                 $displayName = \Locale::getDisplayLanguage($row["localeKey"], $locale);
104: 
105:                 // Standardize capitalization
106:                 $displayName = mb_convert_case($displayName, MB_CASE_TITLE);
```

The method `getDisplayLanguage()` indeed is used twice, but not defined in the code base of the release 3.3

**Comment by R-J** [comment]
Thanks, I already found help on the forum! 👍

**Comment by initvector** [comment]
The `Locale` class requires PHP's [intl extension](https://www.php.net/manual/en/book.intl.php) to be enabled. Previous usages of this class were [wrapped in a `class_exists`](https://github.com/vanilla/vanilla/blob/696ae3668c702d583b22525ebc3523cd05118b6e/library/core/class.smarty.php#L92). Vanilla doesn't currently cite the intl extension in its requirements. To truly resolve this issue, I think we'll need to update Vanilla's requirements or find a way to gracefully handle the absence of this class.

**Comment by charrondev** [comment]
We can stub it out in the API now with a class exists check, and can make Intl a requirement in 4.0 with some clear messaging.

**Comment by linc** [comment]
This still causes the 3.3 release to fatally crash any forums without that extension installed on their server when they go to upgrade.

Like mine.

**Comment by garygreen** [comment]
I'm also having the same issue with recent PHP upgrade - we don't use any locales except english, so why MUST this be a requirement for the intl php extension? For those on shared hosting who cannot easily install/enable that module it just seems a bit silly to me.
