### ISSUE TITLE
Rich Editor's Blockquote doesn't use the blockquote tag

### ISSUE THREAD

**Issue by slafleche** [vanilla/vanilla#9500]
Changing this isn't too difficult. The difficulty is making sure it doesn't with themes.

## Changing the tag

- Add `public static tagName = 'blockquote'` to [BlockquoteContentBlot](https://github.com/vanilla/vanilla/blob/dc203b9a8cc1319ed060a8cc0eaaf3b81b980d95/plugins/rich-editor/src/scripts/quill/blots/blocks/BlockquoteBlot.ts#L23)
- Update `BlockquoteLineTerminatorBlot::getGroupOpeningTag()` and `getGroupClosingTag()` [here](https://github.com/vanilla/vanilla/blob/dc203b9a8cc1319ed060a8cc0eaaf3b81b980d95/library/Vanilla/Formatting/Quill/Blots/Lines/BlockquoteLineTerminatorBlot.php#L27-L39)

**Comment by slafleche** [comment]
@charrondev wasn't there an issue regarding the blots in Rich editor?

**Comment by charrondev** [comment]
We had resolved the issue preventing it some time ago. The changes as recommended in the issue shouldn't pose any problems.
