### ISSUE TITLE
AdminCheck code is not resusable

### ISSUE THREAD

**Issue by donShakespeare** [vanilla/vanilla#9532]
Vanilla 3+
The codes in `vanilla/applications/vanilla/js/discussion.js` are unlike those in the neighbouring files. While AJAX-fetching pages in Vanilla Forum everything works except codes written like this:
https://github.com/vanilla/vanilla/blob/d7c96d70838741f9e7461256a6eae8bf6b6efd6c/applications/vanilla/js/discussions.js#L26

https://github.com/vanilla/vanilla/blob/d7c96d70838741f9e7461256a6eae8bf6b6efd6c/applications/vanilla/js/discussions.js#L33

Vanilla Forum Code sweetly tends to be like
```
$(document).on('click', '.AdminCheck :checkbox', function() {
```
Cheers!

**Comment by charrondev** [comment]
Yeah, looks like an issue of those events not being delegated.
