### ISSUE TITLE
Vanilla\Formatting\Formats\RichFormat is using the wrong namespace for FileEmbed

### ISSUE THREAD

**Issue by egarciajulia** [vanilla/vanilla#9601]
Describe the bug
---
Class `Vanilla\Formatting\Formats\RichFormat` is using class `Vanilla\Formatting\Embeds\FileEmbed` which is not there anymore.

use statement: [Here](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Formats/RichFormat.php#L14)
class usage: [Here](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Formats/RichFormat.php#L143)

I'm speculating that the potential class that it might be needed to be included is `Vanilla\EmbeddedContent\Embeds\FileEmbed` [Here](https://github.com/vanilla/vanilla/blob/master/library/Vanilla/EmbeddedContent/Embeds/FileEmbed.php)
It also looks like `FileEmbed::EMBED_TYPE` was refactored to `FileEmbed:: TYPE`

**Comment by charrondev** [comment]
Not sure when you say this, but looking on master (and the last release) and the exact link your referenced, the reference is correct.

https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Formatting/Formats/RichFormat.php#L14
