### ISSUE TITLE
Deal with the community/theme matching issues

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9614]
We have a customer that is using the KB and would like it matched to their community. This is mostly fine, but there are some issues that will need KB support and some issues that will require the community theme to change. We want to coordinate with services to come up with a good solution to this.

Here are some things that need addressing.

1. Margins are different on either site. Let's try and get the community to change this one.
2. The customer wants "Help" to be "Learning Center" I want to make sure the translation  key is not just "Help" but something like "Help Menu".
3. They have a right aligned menu. I'm hoping we can get the customer to change this.
4. The KB will need a bookmarks menu. This can be scheduled in a future sprint.

**Comment by slafleche** [comment]
Here's a backup of the client's custom theme customizations as of November 18th 2019.

[css](https://github.com/vanilla/vanilla/files/3860905/css.txt)

[html](https://github.com/vanilla/vanilla/files/3860906/html.txt)

**Comment by slafleche** [comment]
Closing this issue for the coding side. To follow up with client see issue: https://github.com/vanilla/support/issues/1118
