### ISSUE TITLE
SubcommunityChooser location is inconsistent between KB and Keystone 

### ISSUE THREAD

**Issue by igraziatto** [vanilla/vanilla#9700]
**On mobile:**
The SubcommunityChooser was added to the mobile navigation on Keystone:
![Screen Shot 2019-11-27 at 11 33 32 AM](https://user-images.githubusercontent.com/31521020/69743558-9f699d00-110c-11ea-87e9-5549f16b243a.png)

Where it really should have been implemented next to the mebox icon, as is on the KB:

![Screen Shot 2019-11-27 at 11 53 14 AM](https://user-images.githubusercontent.com/31521020/69743590-adb7b900-110c-11ea-9b2e-42e1d2474d4b.png)

**Comment by charrondev** [comment]
Fixed with the homepage configurations on subcommunities. This will navigate to the homepage of the subcommunity.
