### ISSUE TITLE
User password change via API v2

### ISSUE THREAD

**Issue by SchmidtWebmedia** [vanilla/vanilla#9735]
I create a new user via API v2. This works fine. But if a user want to change the password afterwards, I don't have an API endpoint.
Is this still a missing feature or is there a reason why this function is not available?

**Comment by charrondev** [comment]
Have you actually tried it?

From what I can see the `PATCH /users/:userID` endpoint supports patching the password if the user making the patch has `Garden.Users.Edit` permission.

This is likely just a documentation error.

**Comment by SchmidtWebmedia** [comment]
I've activated permission. I checked the checkbox at Garden.Users.Edit in the roles. 

I want to change user "DummyUser" with UserID 6. He has the role "member". I've assigend "Garden.Users.Edit" to the role.

This is what I call at the API:

`PATCH https://www.domain.de/api/v2/users/6`

`{
"bypassSpam": true,
"email": "test@test.com",
"emailConfirmed": true,
"name": "DummyUser",
"password": "Test123"
}`

I'm getting following error:
`{
  "message": "You need the Garden.Users.Edit permission to do that.",
  "status": 403,
  "permissions": [
    "Garden.Users.Edit"
  ],
  "description": null
}`

**Comment by SchmidtWebmedia** [comment]
Could it be that in the following line, the field 'password?' is missing?:

https://github.com/vanilla/vanilla/blob/00b4f242dc33b8df5b6ce742adeb4e0b3fb9f389/applications/dashboard/controllers/api/UsersApiController.php#L894

**Comment by charrondev** [comment]
That's the root issue. In addition the `openapi/user.yml` doc would need to be updated, and the `UsersTest` API test updated to account for the extra field.

This currently isn't a high priority for us, but we are accepting contributions.

**Comment by SchmidtWebmedia** [comment]
I could fix it if you want. 
In the documentation I read something about contributers aggreement, but this links to an error 404.

**Comment by charrondev** [comment]
Sorry about that, do you know what doc? I can update the link.

Our CLA can be found here https://cla-assistant.io/vanilla/vanilla.

We have a bot that will prompt you agree digitally when you make your first pull request.

**Comment by SchmidtWebmedia** [comment]
First: Here are the broken link: https://docs.vanillaforums.com/developer/contributing/pull-requests/#pull-request-checklist

And I don't have permission to push into a new branch here. Is there another repository or what I'm doing wrong?

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/pull/9773
