### ISSUE TITLE
Akismet is not using HTTPS

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#9744]
The Akismet plugin, when it communicates with Akismet's API, is using port 80 and standard unencrypted HTTP. Akismet's API supports HTTPS, so we should be doing that.

https://github.com/vanilla/vanilla/blob/master/plugins/Akismet/class.akismet.php#L106

https://akismet.com/development/api/#detailed-docs

**Comment by dannimajdalani** [comment]
PR: https://github.com/vanilla/vanilla/pull/9864
