### ISSUE TITLE
Create functions.framework.php for functions with framework dependencies

### ISSUE THREAD

**Issue by initvector** [vanilla/vanilla#9770]
## Acceptance Criteria

- Move all "impure" functions to a new `functions.framework.php`. These are functions that reference `Gdn::` or other static variables. There are going to be some decisions to make here that might not be 100% clear.
- We should then be left with pure functions that can then be covered in tests.

**Comment by charrondev** [comment]
Just a thought, but a lot of the "impure" ones with `Gdn` references can also be covered pretty easily. Use `MinimalContainerTestCase`. For a lot of them nothing else is likely required. Some may require some additional minimal container rules before running the test.
