### ISSUE TITLE
Can't select second user in Rich Mentions when there are multiple users with the same name

### ISSUE THREAD

**Issue by testing3-apps** [vanilla/vanilla#9781]
Hello,
I've disabled the unique user name function on my forum because my website only allows registrations/login using email address, I'm using JsConnect plugin for SSO.
So there are two users with the same user name "Test"

When I try to mention one of them in any post, it always picks the older profile from the list, even clicking the new user's name.

For example, when I write @ Test it shows both users in the drop-down list-

1.Test
2.Test

And no matter which one I click, it always picks the first profile.

My Vanilla version is 3.3.
Please let me know if you need any other info.
Kind Regards

**Comment by charrondev** [comment]
What editor are you using?

If you are using advanced editor, there really isn't much we're looking to do. Rich Editor can handle this better but we don't have any tests against it and could do to improve it.

**Comment by testing3-apps** [comment]
Hello,
Thanks for your reply.
I think I’m using the rich editor for both mobile and desktop, both are set to “Rich” in the “Posting Settings”
Please let me know if you need more info.
Kind Regards

**Comment by testing3-apps** [comment]
Any update on this?

**Comment by testing3-apps** [comment]
It's been over a year, is there any plan to fix this issue?
