### ISSUE TITLE
Make "All Notifications" and "Mark Read" more easily accessible

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9804]
**Describe the bug**
There is no way to mark a notification as read in the new MeBox.

**To Reproduce**
1. Enable the foundation theme.
2. Send some notifications to yourself somehow.
3. Open the notifications mebox menu.
4. Try to make the notification icon go away.

**Expected behavior**
In the old mebox, opening the menu clears notifications.

## Acceptance Criteria

- Create an API endpoint to clear a user's notifications. (Looks like this is already there https://github.com/vanilla/vanilla/pull/10532)
- Call the endpoint when the new notifications menu opens.
- If this call is successful, the notifications counter should immediately reduce to 0.
- If the user refreshes the page and re-openes the menu, their should be no notifications.

**Comment by vrjrobitaille** [comment]
Just noting here, there is the Mark All Read option and the "All Notifications" link which both clear your new notifications. These are a bit buried though. A simple solution would be to change the position of those two options to be more easily seen. @ElisaAlmeida thoughts?

**Comment by ElisaAlmeida** [comment]
> Just noting here, there is the Mark All Read option and the "All Notifications" link which both clear your new notifications. These are a bit buried though. A simple solution would be to change the position of those two options to be more easily seen. @ElisaAlmeida thoughts?

IMO, when the user clicks into a specific notification for the 1st time, the blue circle that was there should disappear, and the red icon on the top of the notification icon should disappear too (if the user had just 1 message unread). I don't think we need to change the position of the "mark all read" and "all notifications" cause the problem is another one: the expected behavior is not working correctly.

**Comment by vrjrobitaille** [comment]
@ElisaAlmeida I agree, and the devs  can address that  bit, but I still think we can improve the UX  a bit here  for access the "Mark all read" and "View Notifications" option. Maybe we don't need  to change the  position, but what are your  thoughts on  anchoring the two options so  that the user doesn't need  to scroll all the  way to the bottom of the  list to access them. Here's an example of the issue, it'ss apparent on sites with many notifications.  Take  a look at what my notifications are  like:

<img width="542" alt="Screen Shot 2020-06-19 at 11 13 08 AM" src="https://user-images.githubusercontent.com/18470831/85148309-fc01e600-b21d-11ea-8f8b-eded4c2ef103.png">

Those two options can still  be where they are, but should be available to me no matter where I am in the list. 

![dbEf8j4JAr](https://user-images.githubusercontent.com/18470831/85148699-70d52000-b21e-11ea-98c7-4245dca11472.gif)

**Comment by ElisaAlmeida** [comment]
> @ElisaAlmeida I agree, and the devs can address that bit, but I still think we can improve the UX a bit here for access the "Mark all read" and "View Notifications" option. Maybe we don't need to change the position, but what are your thoughts on anchoring the two options so that the user doesn't need to scroll all the way to the bottom of the list to access them. Here's an example of the issue, it'ss apparent on sites with many notifications. Take a look at what my notifications are like:
> 
> <img alt="Screen Shot 2020-06-19 at 11 13 08 AM" width="542" src="https://user-images.githubusercontent.com/18470831/85148309-fc01e600-b21d-11ea-8f8b-eded4c2ef103.png">
> 
> Those two options can still be where they are, but should be available to me no matter where I am in the list.
> 
> ![dbEf8j4JAr](https://user-images.githubusercontent.com/18470831/85148699-70d52000-b21e-11ea-98c7-4245dca11472.gif)

that's true, I agree with you... we should anchor the buttons. I'll create a mockup for that and If I have another idea, I'll add it.

**Comment by ElisaAlmeida** [comment]
The mockup has been updated:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5c7d6e1d310547bc7e28d2e8
