### ISSUE TITLE
Make new Mobile TitleBar Designs

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9820]
## TitleBar mobiles variants w/ Branding

How do we fit the following on mobile?

- MeBox
- Overall site navigation
- KB nav.
- Search
- Logo (Centered or left aligned).

**Comment by ElisaAlmeida** [comment]
I did some options starting here:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5e0e252f4fe89418e1b4aa6d

**Comment by ElisaAlmeida** [comment]
The mockups:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5e010e1808fcb816e7a4c8c1

Prototype for both options:
https://projects.invisionapp.com/share/FWVGG1TNADV#/screens/399766420_Knowledge_Base_-_Chooser_Guest_Burger

https://projects.invisionapp.com/share/FWVGG1TNADV#/screens/399773671_Knowledge_Base_-_Chooser_Guest_Burger_chevron_kb1
