### ISSUE TITLE
Titlebar has leaked into the global error pages

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9835]
Our global title bar now has the react menu which it should not have:

<img width="1679" alt="The_Essence_—_T1" src="https://user-images.githubusercontent.com/97432/70863151-18d9fb80-1f13-11ea-8851-c98c0c6d5d66.png">

**Comment by charrondev** [comment]
A few questions on this, because I can't reproduce off-hand on my localhost.

1. Does this happen on all of your error pages or just certain ones?
2. Do you have CustomizeTheme enabled? If you do could you bring your laptop by or share the contents of it?

**Comment by tburry** [comment]
I couldn't reproduce this trivially on my localhost. We can close this for now and I'll file a new ticket if it resurfaces.
