### ISSUE TITLE
Rich Editor: Image height ratio not being respected for wide images on mobile

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#9844]
Based on the latest release notes, when uploading an image, the following should happen: 

> Wide images will now be displayed at the full content width.
Tall images will now display at their full height.
Small images will not be stretched. Instead they will be remain their original size.
Images will default to using center alignment, but respect the alignment options of Advanced Editor

A prospect noted this bug to me and Adam confirmed it to be a bug when I showed him. 

The bug: Wide images are currently not scaling their height proportionally.

To reproduce:
1. Upload a wide image to a post
2. View on mobile
3. The wide image will be stretched and not scale down proportionally. 

Expected behaviour: 
Wide images will scale down in height to proportionally fit on mobile devices.

**Comment by charrondev** [comment]
Note this seems to be iOS/mobile safari specific.

**Comment by Bparm** [comment]
@charrondev  You can see it on the release notes actually that the images get totally distorted on IOS mobile:
https://success.vanillaforums.com/kb/articles/137-release-2019-018

**Comment by slafleche** [comment]
https://github.com/vanilla/vanilla/pull/9878

**Comment by charrondev** [comment]
Closed by https://github.com/vanilla/vanilla/issues/9844
