### ISSUE TITLE
How to stop recaptcha?

### ISSUE THREAD

**Issue by yuebanyidiudiu** [vanilla/vanilla#9849]
Version:3.3
Because of GFW(Great Firewall of China) in China ,We can't visit the web `http://recaptcha.net/`.
Is there someway I can stop it?
Or
Is it possible  to make the recaptcha optional?

**Comment by oliveratgithub** [comment]
You can simply disable the plugin `reCAPTCHA Support` from Settings > Plugins ?

At least this is what I did on my local dev instance to not have to enter reCaptcha when testing.
