### ISSUE TITLE
More than one BodyBox on a page gives invalid html

### ISSUE THREAD

**Issue by R-J** [vanilla/vanilla#9852]
1. Go to a discussion and look at the BodyBox which is textarea#Form_Body
2. Now edit a comment so that a second BodyBox is rendered that one also is textarea#Form_Body

https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute: 
> When specified on HTML elements, the id attribute value must be unique amongst all the IDs in the element's tree

**Comment by charrondev** [comment]
This really comes down to a fundamental limitation of how we handle IDs in our `Gdn_Controllers`. The second bodybox that gets rendered in is rendered on the server, and has no awareness of the previous request which complicates things.

We tried some time ago to do "smart" ID generation for `Gdn_Form` but it broke too many things.

This is essentially a fixed problem in our new system. Some day in the near future we'll have an alternative React-based discussion view. All IDs generated in our new system use our `useUniqueID` hook, and they are ensured to be globally unique within the page.

**Comment by charrondev** [comment]
@R-J Part of the reason for the "won't fix" is because actually fixing it is pretty risky and will take a lot of effort.

The benefit on the other hand is minimal to fix it for its own sake. While not ideal, browsers render it just fine.

If you have some concrete bug that affects usability as a result, we can evaluate solutions for that separately.

**Comment by R-J** [comment]
Actually I was trying to add an editor script which synchronizes with the input element specified by its ID:

~~~
 public function gdn_form_beforeBodyBox_handler($sender, $args) {
        echo '<trix-editor input="Form_Body"></trix-editor>'; 
~~~

As you can see, this will obviously fail if another textarea#Form_Body is created. For me that's no big deal since I was only toying around. 

I don't have deeper knowledge about web accessibility, but I'd guess that multiple IDs can be a problem: https://www.deque.com/blog/unique-id-attributes-matter/
The "correct" answer for getElementById when there are duplicate IDs is "undefined": https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-getElBId

But there never has been reports about misbehaviours and this problem, if I understand you correctly, will not persist for very much longer. Therefore "won't fix" is okay for me.

**Comment by charrondev** [comment]
> But there never has been reports about misbehaviours and this problem, if I understand you correctly, will not persist for very much longer. Therefore "won't fix" is okay for me.

Yeah, in the meantime if you do want to workaround you could specify more deeply your selector. Eg. `document.querySelector("#formID #editorID")`
