### ISSUE TITLE
Register a new account IS BROKE!

### ISSUE THREAD

**Issue by zohozer** [vanilla/vanilla#9870]
Hi.

I just come here to report that actually it is impossible to create a new user account on godotforums.org and open.vanillaforums.com. I searched for an email support address for this forums and found none, so this seems the only place where I can report that this forums are not able to create new user accounts.

I do tried on both this forums to create a new user account without success. I do tried different browsers with the same result.

Seems that after completing all the required fields and pressing the "Sign Up" button, it is jumping back to the same page asking "Tell us why you want to join!". After completing this question and pressing the captcha button again and pressing the "Sign Up" button again, the SignUp button spins forever, without to actually create a new account.

Please fix the user creation account issue.

**Comment by charrondev** [comment]
I'm unable to reproduce this. I just created a brand new account on `open.vanillaforums.com`.

godotforums.org is not maintained or run by us. We just make the software. Maybe there is some misconfiguration on their end, but this is the wrong place for this.
