### ISSUE TITLE
Finish off variable/asset integration with Foundation theme

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9879]
The Foundation theme should implement the base set of variables and assets so that it is usable as a base. A real customer will have to use it as a service to fully QA it as a later task.

## Acceptance Criteria

- [x] Basic colors
- [x] Secondary colors
- [x] Background images: home and generic
- [x] Font families
- [x] Addons: Reactions, badges, groups, ranks, Q&A, ideation, KB.
- [x] Secondary Addons: online, Github ticket escalation, Warnings & Notes.
- [x] swap out search on forum side with new search

This can be visibly QA'd with a dark mode theme to ensure no fonts disappear and there are no obvious white background blocks.

Let's think that we are going to demo a dark theme.

**Comment by slafleche** [comment]
Fix bugs and make sure the merge is a net positive and not regression bugs.

**Comment by tburry** [comment]
Done when existing PRs are merged.
