### ISSUE TITLE
Basic inline theme preview header/footer

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla#9882]
As a themer I want to see my theming changes previewed in real time (or near real time) so that I can see the effect of my changes as I write them.

## Acceptance Criteria

- A split pane shows a sample theme with header/footer and the same theme as the color editor.
- There needs to be some UX decisions made on how the preview updates.
    - Automatically as you type.
    - When you hit a quick key.
    - A toggle for either/or.

**Comment by vrjrobitaille** [comment]
@tburry Would you consider this issue complete? Or is there something else to this PBI we are still working towards?

**Comment by tburry** [comment]
This is not complete as it's a different PBI. It's a good example of something we may not do though.
