### ISSUE TITLE
Open Source Release 4.0 Blockers

### ISSUE THREAD

**Issue by charrondev** [vanilla/vanilla#9888]
This issue is set up for use of tracking before making the official 4.0 OSS release.

- [x] Document new version requirements (MySQL 5.7+, PHP 7.2+, Intl extension added).
- [x] Get foundation theme to a shippable state.
- [ ] ~~Document foundation theme setup.~~
- [x] Gather release notes
- [x] Add config key to put back back full-text indexes

**Comment by anaggh** [comment]
* The php-intl requirement is not yet documented here - https://success.vanillaforums.com/kb/articles/157-self-hosting-basics
* Document that PHP 8.x is not supported by vanilla.
