### ISSUE TITLE
Vanillicons SHA1 now just as unsafe as MD5?

### ISSUE THREAD

**Issue by DivineDominion** [vanilla/vanilla#9899]
In Septembwr 2019, the hash function for Vanillicons changed from MD5 to SHA1. It now appears SHA1 is just as unsecure and would need to be replaced in accordance with your new policy: https://success.vanillaforums.com/kb/articles/114-why-vanillicon-avatars-changed

SHA1 collision links: https://mjtsai.com/blog/2020/01/08/chosen-prefix-collision-for-sha-1/

This is meant to bring up the issue to your attention. Like with MD5, this has no practical consequences for avatar generation.

Please feel free to close if you are aware of the hash problem.

**Comment by charrondev** [comment]
@DivineDominion in addition to the algorithm change, we also started truncating the hashes used to generate Vanillicons, so even if you could generate a collision you would not be able to reverse the image and get a users email.

For that reason the algorithm itself ends up being irrelevant.
