### ISSUE TITLE
Upgraded Vanilla 3.3 fails to attach Images due to missing default value for StorageMethod in GDN_Media table

### ISSUE THREAD

**Issue by oliveratgithub** [vanilla/vanilla#9906]
## Describe the bug
After upgrading Vanilla (2.0.18.4 previously) to the most recent version 3.3 release, I noticed the "Attach image"-function on Activities and Discussions/Comments failing with an error in the frontend/UI:

_Note: I did run `/utility/update` and - multiple times - `/utility/structure`._

> "Request failed with status code 400."
<img width="1051" alt="vanillaforums 3_3 image attachment frontend error" src="https://user-images.githubusercontent.com/280207/72106315-72292500-332f-11ea-987e-830724f78727.png">
<img width="1343" alt="vanillaforums 3_3 image attachment dev console error" src="https://user-images.githubusercontent.com/280207/72106928-9afdea00-3330-11ea-9072-deac4183c680.png">

After digging into this problem, I noticed the image is actually successfully uploaded into a folder under `/uploads/` - however it is not written into the GDN_Media database table.

Inspecting the browser dev console while trying to upload/attach an image to a Comment, more details where presented: the "media" API call responded with

```
{
    "message": "Validation Failed",
    "status": 400,
    "errors": [
        {
            "field": "storageMethod",
            "code": "ValidateRequired",
            "status": 400,
            "message": "storageMethod is a required field."
        }
    ]
}
```
<img width="877" alt="vanillaforums 3_3 media API call error response" src="https://user-images.githubusercontent.com/280207/72106394-95ec6b00-332f-11ea-87ab-a15533a9400a.png">

I was able to resolve the issue - hence having uploaded image attachments successfully being added to the `GDN_Media` table, by chaning the "Default value" for the column `StorageMethod` from `<empty>` to `"local"` – OR by setting "Allow Null: true".
<img width="1572" alt="vanillaforums 3_3 gdn_media fix storagemethod to allow null" src="https://user-images.githubusercontent.com/280207/72106418-a00e6980-332f-11ea-84f2-ae94451caf8c.png">

In my opinion, there seems to be something missing within `/utility/structure` integrity checks for the database, by not checking or not properly adjusting this column on the `GDN_Media`-table.

## Vanilla info
_1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?_
Yes, all Addons - at least non-official - have been disabled at this stage, due to the preceeding upgrade work.

_2. Did you follow our generic troubleshooting steps already?_
Yes, I ran `/utility/update` successfully, following - multiple times - the `/utility/structure` commands.

_3. What Vanilla version are you using?_
Version 3.3

_4. When did the issue start?_
Was there right after the upgrade.

## To Reproduce
_Steps to reproduce the behavior:_
Well I had the issue on my local AND on the productive instance of Vanilla Forums right after the upgrade from a pretty old version 2.0.18.4 to the newest version 3.3. So it seems to be related to upgrading an - existing, old version - database.

I cannot tell how it behaves or since what newer version it happens, when upgrading a post 2.0.18.4 version to the new Vanilla Forums 3.3.

## Expected behavior
Attaching images in an Activity-post or Discussion/Comment should not only upload the image file into `/uploads/`, but also create the proper, corresponding entry in `GDN_Media` - thus without showing an error in the Frontend / UI.

**Comment by charrondev** [comment]
@oliveratgithub My understanding is this column is some old remnant removed long ago.

I would recommend removing the column entirely from your database.

**Comment by oliveratgithub** [comment]
Thanks for your insights @charrondev 👍

If that’s the case, then my recommendation under the reported bug here would be, to add this as a db integrity check & resolve it using `/utility/structure` or even `/utility/update`
