### ISSUE TITLE
PNG Images as Banner Images  - Not respecting Alpha channel

### ISSUE THREAD

**Issue by MaxDore1** [vanilla/vanilla#9936]
**Describe the bug**
When uploading a .png image as a banner image, the alpha channel is replaced by black. 

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using? Yes
2. Did you follow our generic troubleshooting steps already? Yes
3. What Vanilla version are you using? 
4. When did the issue start? I noticed today, others say its been happening for a few days. 

**To Reproduce**
1. Go to any dashboard (tested on maximedore.vanillademo.com) 
2. Add a Banner Image through Branding and SEO, ensuring it's a PNG with an alpha background
3. Save - image will replace alpha with black

**Expected behavior**
Image will retain alpha

**Screenshots**
![Screen Shot 2020-01-15 at 3 33 14 PM](https://user-images.githubusercontent.com/57997758/72468973-5a78f300-37ac-11ea-92e4-bd7e4901caa7.png)

**Additional context**

**Comment by charrondev** [comment]
@MaxDore1 A fix was implemented and deployed earlier today (backported to 2020.001)

Please try uploading your image again.
