### ISSUE TITLE
New Dashboard Image Uploads don't show loading indicator

### ISSUE THREAD

**Issue by Bparm** [vanilla/vanilla#9943]
I cannot upload banner images, whether .png or .jpg with the banner settings. Some might work but the vast majority suddenly do not.

Sample images:
![Atrium2banner](https://user-images.githubusercontent.com/24961134/72544407-49d08780-3855-11ea-9619-546758b1dcb8.jpg)

![community-home-banner-v1](https://user-images.githubusercontent.com/24961134/72544416-505eff00-3855-11ea-8def-2cf56af41de7.png)
![data-home-banner](https://user-images.githubusercontent.com/24961134/72544433-57860d00-3855-11ea-84f0-865018ba89cf.png)

Steps to reproduce:
1. Try to upload these images using the banner image upload settings under Branding.
2. You can't. 
Observe that you can't. 

Expectations: That I can upload banner images.

Tested on my demo site brendan.vanillademo.com

**Comment by andrewdodson** [comment]
Did some quick testing.  

Was able to confirm the issue with the replication steps - none of those images appeared to save when uploading them to the banner options in Branding. 

I tested with a jpg image and that worked fine.  I then converted one of the images that Brendan provided to jpg and after that, it saved just fine in the Dashboard. 

![bannjpg test](https://user-images.githubusercontent.com/19805402/72551928-d5511500-3863-11ea-8d3a-81ee3e89c0f5.jpg)


Appears to be an issue with png files specifically.

**Comment by Bparm** [comment]
@andrewdodson the first red imag is a jpeg and I couldn't upload it on my demo site.

**Comment by andrewdodson** [comment]
Let me know if this one works for you:

![redjpg](https://user-images.githubusercontent.com/19805402/72552654-565cdc00-3865-11ea-9673-0203e5e4802d.jpg)


What is your source for these images?

**Comment by charrondev** [comment]
@Bparm This is a problem of us not showing a good loader.

You just need to wait a second before hitting submit.

Big images take a while, even if we show the preview right away, and if you submit before the image finishes uploading, you get this issue.

**Comment by charrondev** [comment]
## Reproduction steps:

- Go the branding page.
- Upload a "large-ish" image such as one of the ones above.
- Immediately hit save before the image finishes uploading.
- Notice image didn't upload.

## Proposed solution

- Block submission of the form until the image finishes uploading.
- Show a loading indicator over the image.
