### ISSUE TITLE
[Keystone] New site spawned with invisible title

### ISSUE THREAD

**Issue by kaecyra** [vanilla/vanilla#9951]
I created a new site which used Keystone. When I visited it for the first time, the title text (which usually shows the site name) was not displayed. Upon investigation by @igraziatto it seems that the title font color is the same as the background, so it is effectively hidden. See attached screenshot:

![Screen Shot 2020-01-17 at 10 22 51 AM](https://user-images.githubusercontent.com/248212/72623670-911d4d80-3913-11ea-9bc5-74b0fff4acef.png)

**Comment by charrondev** [comment]
@igraziatto I'd recommend waiting a couple days to tackle this. 

I've got this PR out that does some hefty refactoring of keystone and boilerplate https://github.com/vanilla/vanilla/pull/9935 and it will certainly create conflicts.

**Comment by kaecyra** [comment]
The fact that this is customer facing doesn't bug you at all? 

Customers who are using Keystone with no uploaded banner logo, just text, currently have no visible title. This seems like something you want to "wait a couple days" before fixing? 

👎

**Comment by charrondev** [comment]
@kaecyra alternatively she could put it right on top of my branch. Were we planning to do a backport for it? If we weren't it'll be a while before it goes out anyways, and waiting until Monday/Tuesday for the merge conflicts to be avoided would be ideal.
