### ISSUE TITLE
Google is sunsetting support for data-vocabulary

### ISSUE THREAD

**Issue by adrianspeyer** [vanilla/vanilla#9962]
https://webmasters.googleblog.com/2020/01/data-vocabulary.html

https://github.com/vanilla/vanilla/search?q=data-vocabulary&unscoped_q=data-vocabulary

Those using the software will start to get a warning like below
![image](https://user-images.githubusercontent.com/425366/72838807-0748e980-3c5f-11ea-886f-de489678233e.png)

**Comment by adrianspeyer** [comment]
Lines affected 
https://github.com/vanilla/vanilla/blob/40ac277352d8a56155e534251807616242d337db/library/core/class.theme.php#L106

https://github.com/vanilla/vanilla/blob/40ac277352d8a56155e534251807616242d337db/library/core/class.theme.php#L126

**Comment by vrjrobitaille** [comment]
Asus, MSE and PEX are all asking questions about this. Do we have an idea of how we're handling this?
