### ISSUE TITLE
Mockups Related Articles

### ISSUE THREAD

**Issue by ElisaAlmeida** [vanilla/vanilla#9976]
As a member I should be able to see a list of related articles when viewing an article to allow me to find the help I may be interested in easily (and increase engagement).

The list of related should automatically be generated.

Create different examples: bullets, columns, images... Bellow, King reference:

![image (7).png](https://images.zenhubusercontent.com/5c2e30a34b5806bc2b00a266/b8df02cf-7747-4c0b-b1d8-0d168891234f)

**Comment by vrjrobitaille** [comment]
Example of articles with long "On this page" nav menu: 

- https://success.vanillaforums.com/kb/articles/115-addon-master-list
- https://community.partnerize.com/kb/articles/39-partner-and-affiliate-marketing-glossary

**Comment by ElisaAlmeida** [comment]
For the Related Articles component, we'll show on the Articles Page in the end of the page. The idea is to show max 4 articles related. See the mockup:

Desktop:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5e31d315167b105633606e42

Mobile:
https://app.zeplin.io/project/5c65db78a981283c0b8d956e/screen/5e31d317922d4d961b762797
