### ISSUE TITLE
Brand New install and Getting Errors

### ISSUE THREAD

**Issue by MrCaspan** [vanilla/vanilla#9983]
I just installed last night the latest stable code and I am running into an issue

I first noticed this issue when I was trying to do a test post and I got an error that said the Body cannot be left blank. Then I realized when I refreshed the post page that the rich editor shows up then disappears after 1 second. I checked the Google console and I am seeing this error in the console

![2020-01-24 11_32_17-Window](https://user-images.githubusercontent.com/19710296/73085937-9b07f900-3e9d-11ea-9157-e13ae68da7c1.png)

I cannot figure out what is going on. Also when I go to the API settings page I see this:

![2020-01-24 11_36_13-Window](https://user-images.githubusercontent.com/19710296/73086024-c4288980-3e9d-11ea-90bf-1b2500015338.png)

Any Ideas? I have tried turning off all plugins with the same issue. If I change to editor to text in Post settings instead of rich the editor does show up and allows me to post.

**Comment by charrondev** [comment]
I see you found some assistance on the OSS forum https://open.vanillaforums.com/discussion/37894/new-install-and-i-am-getting-weird-issues

This issue tracker is for tracking bugs and features. If you have any further configuration questions please continue to use the OSS forum.
