### ISSUE TITLE
Vanilla is completely broken on older browsers (e.g. iOS 9)

### ISSUE THREAD

**Issue by michaeltyson** [vanilla/vanilla#9988]
Vanilla 3.3 is completely non-functional on older browsers, including Safari on iOS 9. This also applies to the installation on open.vanillaforums.com. All pages appear completely blank -- although on open.vanillaforums.com, a page will load occasionally.

In the console are the following errors:

*Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead* **jquery.js:1**
*SyntaxError: expected expression, got ')'* **flyouts.js:17:761**
*unreachable code after return statement* **editor.js:18:48**
*TypeError: e.querySelectorAll(...).forEach is not a function* **shared.min.js:223:7254**
*Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.* **jquery.js:3:49126**

Interestingly, the times that open.vanillaforums.com actually loads, the *e.querySelectorAll(...).forEach* error does not appear in the console, suggesting that this might be the main issue.

This can be easily reproduced on up-to-date systems by using an [older version of Firefox](https://ftp.mozilla.org/pub/firefox/releases/48.0.2/), for example.

It's important that these older browsers remain supported, as there are still plenty of people still running iOS 9 who are unable to update because their devices are too old.

**Comment by michaeltyson** [comment]
The fix is to wrap the two *e.querySelectorAll(...).forEach* calls from *shared.js* (both on line 223 in the minified version) in an Array.from() as per this StackOverflow answer: https://stackoverflow.com/a/41054307

**Comment by michaeltyson** [comment]
And to fx the error in js/flyouts.js:

`
                var $handle = $(this).find(
                    ".FlyoutButton, .Button-Options, .Handle, .editor-action:not(.editor-action-separator)",
                );
`

should lose the trailing comma:

`
                var $handle = $(this).find(
                    ".FlyoutButton, .Button-Options, .Handle, .editor-action:not(.editor-action-separator)"
                );
`

**Comment by michaeltyson** [comment]
And another one in bootstrap.js - line 133 in the minified version needs an Array.from() wrapper.

**Comment by charrondev** [comment]
We have a polyfilling strategy to fill in these array methods on NodeLists, but it might not be working safari right now. The polyfills are the ones here: https://github.com/vanilla/vanilla/blob/master/packages/vanilla-polyfill/index.js.

The conditional logic for loading them is here:

https://github.com/vanilla/vanilla/blob/master/library/Vanilla/Web/Asset/InlinePolyfillContent.js.twig

There might be something preventing this from loading though, because I do see the `forEach` in the polyfill list.

**Comment by michaeltyson** [comment]
Thanks @charrondev.

Another example, one I've not been able to reproduce because I don't have an iOS 9 installation available (and this doesn't happen in the old Firefox build I was testing with):

![a4kvrc75iglj](https://user-images.githubusercontent.com/184008/73405947-5f5faa00-4349-11ea-98cd-c0da0077d7e6.jpeg)

Which, when Javascript is disabled, looks correct again:


![rggpj6kbbbs1](https://user-images.githubusercontent.com/184008/73405975-70102000-4349-11ea-957b-84716f1e3d99.jpeg)

**Comment by charrondev** [comment]
Hallelujah, finally got it figured out.

https://github.com/vanilla/vanilla/pull/10350
